'use strict';
// Dossier HPE v3 au close du 2026-09-23 (lot R04). Contenu éditorial et niveaux propres au titre ;
// calculs, provenance et preuves délégués au gabarit commun tools/lib/analysis-v3-r04.cjs.
const R = require('../../../../tools/lib/analysis-v3-r04.cjs');
const GEN = 'analyses/HPE/_runs/20260924/build-hpe.cjs';
// Actions préférentielles obligatoirement convertibles le 1er septembre 2027 : 30 millions de titres, entre
// 2,5352 et 3,1056 actions ordinaires chacun selon le cours moyen. Au-dessus de 50 / 2,5352 = 19,72 $, le taux
// minimal s'applique : 76,056 millions d'actions, ajoutées au dénominateur (et non comptées comme dette).
const COMMON = 1327464779, PREF_CONV = 30e6 * 2.5352;

R.build({
  ticker: 'HPE', shortName: 'Hewlett Packard Enterprise', cik: 1645590, generator: GEN, mode: 'breakout',
  xbrl: { ttm: { rev: ['Revenues'], ebit: ['OperatingIncomeLoss'], ni: ['NetIncomeLoss'], da: ['DepreciationDepletionAndAmortization'], ocf: ['NetCashProvidedByUsedInOperatingActivities'] },
    instant: { ltd: ['LongTermDebtNoncurrent'], std: ['DebtCurrent'], cashEq: ['CashAndCashEquivalentsAtCarryingValue'] }, da: ['da'], debt: ['ltd', 'std'], cash: ['cashEq'] },
  scenarioBasis: 'ebitda', scenarioMultiple: 12,
  valuationBasis: 'GAAP douze mois au 2026-07-31 (XBRL SEC) ; EBITDA = résultat opérationnel + amortissements, qui incluent ceux des équipements loués par la division de financement ; gain de 444 M$ sur la cession de H3C, et ses 118 M$ d’impôt, hors résultat opérationnel donc hors EBITDA ; dette = emprunts à court et long terme au 31 juillet, financement compris ; trésorerie = liquidités du 31 juillet ; 1 327,5 millions d’actions ordinaires au 27 août plus 76,1 millions issues de la conversion obligatoire des préférentielles au taux minimal ; multiple de douze fois l’EBITDA = hypothèse éditoriale',
  levels: { trigger: { d: '2026-06-02', c: 2 }, stop: { d: '2026-09-21', c: 3 }, abandon: { d: '2026-09-17', c: 3 }, s1: { d: '2026-09-23', c: 3 }, r1: { d: '2026-09-23', c: 2 }, r2: { d: '2026-09-21', c: 2 } },
  supports: ['s1', 'stop', 'abandon'], resistances: ['r1', 'r2', 'trigger'],
  targets: ({ entry, abandon }) => { const range = entry - abandon; return { tp1: entry + range, tp2: entry + 1.5 * range, range }; },
  levelsMethod: 'Déclencheur = plus haut du 2 juin, sommet de la série ; bas du couloir = plus bas du 17 septembre ; stop = plus bas du 21 septembre ; TP1 = déclencheur + hauteur du couloir ; TP2 = déclencheur + 1,5 × hauteur ; plafond = (TP1 + 1,5 × stop) / 2,5 arrondi au cent inférieur ; pourcentages depuis l’entrée ; R/R = gain / risque.',
  inventory: 24,
  reviewScope: 'Dépôts EDGAR de Hewlett Packard Enterprise du 1er novembre 2025 au 23 septembre 2026 (24 formulaires hors formulaires 3, 4, 5 et 144), dont le 10-K de l’exercice clos le 31 octobre 2025. Les 8-K de gouvernance (items 5.02, 5.07) et d’information (item 7.01), les procurations et leurs compléments, le formulaire SD, le rapport 11-K du plan d’épargne, le S-8 du plan salarié et les 8-K d’accords du 17 et du 28 novembre sont écartés comme non décisionnels ; les prospectus 424B2 et 424B5 de mars sont repris par le 8-K du 18 mars. Les 10-Q des deux premiers trimestres sont couverts par celui du troisième.',
  docs: [
    ['2026-09-03', '10-Q', '0001645590-26-000080', 'hpe-20260731.htm', 'q3-10q__hpe-20260731.htm',
      'Rapport trimestriel au 31 juillet 2026 : 1 327 464 779 actions au 27 août ; 30 millions de préférentielles obligatoirement convertibles ; cession du solde de H3C en mai pour environ 1,36 Md$, gain de 444 M$ hors exploitation, sur lequel pèsent 118 M$ d’impôt. Stocks de 11,8 Md$ contre 6,4 Md$ en octobre ; dette de 20,2 Md$.'],
    ['2026-09-02', '8-K / Exhibit 99.1', '0001645590-26-000078', 'ex-991x922026x8k.htm', 'q3-8k__ex-991x922026x8k.htm',
      'Communiqué du troisième trimestre, daté du 2 septembre : revenus de 12,2 Md$ (+34 %), marge opérationnelle GAAP de 11,4 %, réseau à 2,9 Md$ (+74,9 %), serveurs à 6,8 Md$ (+35,3 %). Prévision relevée : 13,9 à 14,8 Md$ au quatrième trimestre, bénéfice GAAP de 2,93 à 3,03 $ par action sur l’exercice, flux libre d’au moins 3,75 Md$.'],
    ['2025-12-18', '10-K', '0001645590-25-000130', 'hpe-20251031.htm', 'fy25-10k__hpe-20251031.htm',
      'Rapport annuel de l’exercice clos le 31 octobre 2025 : conversion obligatoire des préférentielles le 1er septembre 2027 en 2,5352 à 3,1056 actions chacune ; concurrents cités, Dell, Super Micro, Cisco et Lenovo ; aucun client à plus de 10 % des créances de financement, un distributeur à 10 % des créances.'],
    ['2026-06-01', '8-K', '0001645590-26-000052', 'hpe-20260601.htm', 'jun01-8k__hpe-20260601.htm',
      'Accord de coopération avec le fonds activiste Elliott amendé le 29 mai : conseil limité à 14 administrateurs jusqu’à l’assemblée 2027 ; nomination de Christopher Hsu au conseil. Gouvernance, sans effet sur le capital.'],
    ['2026-03-18', '8-K', '0001140361-26-010222', 'ef20068126_8k.htm', 'mar18-8k__ef20068126_8k.htm',
      'Émission de 2,0 Md$ d’obligations en quatre tranches, à taux variable 2028 et à 4,500 %, 4,600 % et 5,250 % pour 2028, 2029 et 2033 : de la dette, pas d’actions.'],
  ],
  needles: {
    q3q: [0, ['common stock outstanding as of August 27, 2026 was 1,327,464,779 shares', '30,000,000 shares issued and outstanding as of July 31, 2026', 'the Company recorded a gain on sale of equity interest of $ 444 million', '$ 118 million of net income tax charges resulting from the gain on the H3C divestiture', 'closed on the sale and disposition of 13.8 % of the total issued share capital of H3C for approximately $ 987 million', 'closed on the sale of the remaining 5.2 % of the total issued share capital of H3C for approximately $ 370 million', 'Inventory 11,823 6,352', 'Long-term debt 17,343 17,756', 'erm borrowings $ 2,901 $ 4,609', 'Cash and cash equivalents $ 6,216 $ 5,773', 'On July 2, 2025, the Company completed the Juniper Networks merger']],
    q3: [1, ['Record revenue of $12.2 billion, up 34% year-over-year', 'GAAP of 11.4%, up 870 basis points', 'Networking revenue was $2.9 billion, up 74.9% from the prior-year period', 'Server was $6.8 billion, up 35.3% from the prior-year period', 'HPE estimates revenue to be in the range of $13.9 billion to $14.8 billion', 'GAAP diluted net EPS to be in the range of $2.93 to $3.03', 'now expects free cash flow to be at least $3.75 billion', 'return at least 75% of free cash flow to shareholders in Q4', 'raising its revenue growth outlook range to 13% to 17%', 'GAAP of $1.06, up $0.85 from the prior-year period', 'Cash flow from operations : $1.6 billion', 'HPE (NYSE: HPE) today announced financial results for the third quarter ended July 31, 2026']],
    annual: [2, ['into between 2.5352 shares and 3.1056 shares of common stock', 'expected to be September 1, 2027', 'such as Dell Technologies Inc., Super Micro Computer, Inc., Cisco Systems, Inc., and Lenovo Group Ltd.', 'one distributor accounted for 10% of the Company\'s accounts receivable balance']],
    elliott: [3, ['with Elliott Investment Management L.P.', 'will not exceed 14 directors until the 2027 Annual Meeting', 'the Board has appointed Christopher P. Hsu']],
    notes: [4, ['$300,000,000 in aggregate principal amount of the Company’s Floating Rate Notes due 2028', '$600,000,000 in aggregate principal amount of the Company’s 5.250% Notes due 2033']],
  },
  sectionDocs: { verdict: [1, 0], business: [1, 0, 2], news: [1, 0], earnings: [1], capitalStructure: [0, 2, 4], filingsReview: [0, 1, 2, 3, 4], risks: [0, 1], globalScore: [1], meta: [1], disclaimer: [1], macro: [0], options: [1], social: [1], header: [0] },
  score: { business: 26, technical: 6, capital: 0, calendar: -2, dilution: -1, risk: 25 },
  peers: true,
  peerFicheSha: { DELL: '7906c0763bab8365744b6916769d7f0dcf06a69930de19fb9b965edfb72def56', SMCI: '7d7e5bff72958a7604dc8883e1a3579e1705c5a33640c3871e6ea8a13527a081', ANET: 'd59c99444c4069fb2ef7f2d049605415f5918e200296266168ca1c026bd56d67', FTNT: 'a77c9d70133b6b9f4719d8b8413294e7c166212fa0e306a0959067acfd890c6f' },
  shares: { value: COMMON + PREF_CONV, doc: 0 },
  route: (p, { prov, dep, B }) => /^news\.[01]\./.test(p) ? prov('bars', B, 'Ouverture et clôture lues sur les barres certifiées ; écart d’ouverture = ouverture / clôture de la veille − 1 ; comparaison avec SMH et les pairs sur la même séance.', [dep('comparison', '')]) : null,
  riskScoreReason: 'Jugement qualitatif sur dix : titre triplé en dix mois, écarts d’ouverture de plus de 8 % deux fois en septembre, stocks presque doublés et plafond d’achat très proche du déclencheur.',
  compose: c => {
    const { fr, usd, pct, sgn, close, prev, bars, N, tech, st, M, adv, ret, G$, marketCap, ev, scn, lv, entry, stop, tp1, tp2, abandon, cap, rr1, rr2, riskAtr, sizeExample, ref, market, docs, raw, peerStat, peerFiche } = c;
    const gs = c.gapStats(cap - entry), bufAtr = (cap - entry) / tech.atr14, blocked = gs.up / gs.total * 100;
    const bufPct = (cap / entry - 1) * 100, bk = c.breakoutStats(bufPct), rt = c.retestStats(bufPct, (1 - stop / entry) * 100), bufOpen = bk.buyable / bk.n;
    const cmp = raw.comparison_bars.data.items[0].results[0].data;
    const dr = (sym, d) => { const b = cmp.find(x => x.symbol === sym).bars, i = b.findIndex(x => x[0] === d); return pct(b[i][4], b[i - 1][4]); };
    const bar = d => bars.find(b => b[0] === d), prevOf = d => bars[bars.findIndex(b => b[0] === d) - 1];
    const d0903 = bar('2026-09-03'), p0903 = prevOf('2026-09-03'), d0914 = bar('2026-09-14'), p0914 = prevOf('2026-09-14');
    const low1120 = bar('2025-11-20'), run = close / low1120[3];
    const evRev = ev / G$.rev, evEbitda = ev / G$.ebitda, niX = G$.ni - (444e6 - 118e6), pe = marketCap / niX;
    const dellEb = peerFiche('DELL', 'EV/EBITDA GAAP').value, smciEb = peerFiche('SMCI', 'EV/EBITDA GAAP').value, anetEb = peerFiche('ANET', 'EV/EBITDA GAAP').value, ftntEb = peerFiche('FTNT', 'EV/EBITDA GAAP').value;
    const cscoEb = peerStat('CSCO'), ntapEb = peerStat('NTAP');
    const ext20 = pct(close, tech.ema20);
    return {
      meta: { lang: 'fr', dir: 'ltr', level: 'intermediate', tags: ['us', 'equities', 'ai-chain', 'technology', 'hardware'], grade: 'B-', date: '2026-09-24', dateDisplay: '24 septembre 2026', version: 3, status: 'watch', assetType: 'stock', levelsCloseDate: c.REF,
        description: 'Hewlett Packard Enterprise : Juniper qui double le réseau, des revenus à +34 % et un titre revenu sous son sommet de juin. Dossier au close du 23 septembre 2026, statut surveiller.',
        ogDescription: 'HPE : revenus +34 %, réseau +74,9 % avec Juniper, prévision relevée ; titre à 62,33 $, sous le sommet de 63,90 $ du 2 juin ; niveaux à surveiller.',
        lastMcpRefresh: raw.status.captured_at, levelsVerifiedAt: raw.status.captured_at,
        statusHistory: [{ at: raw.status.captured_at, from: 'wait', to: 'watch', note: 'refonte v3 du 24 septembre : nouveau scénario, clôture de référence du 2026-09-23', close }] },
      header: { ticker: 'HPE', name: 'Hewlett Packard Enterprise Company', exchange: 'NYSE', sector: 'Serveurs, réseau, stockage et financement d’équipements', price: close, changePct: pct(close, prev),
        badges: [{ text: 'SURVEILLER — ACTIVATION AU-DESSUS DU SOMMET DU 2 JUIN', color: 'blue' }, { text: 'Chaîne IA — serveurs et réseau des centres de données', color: 'purple' }],
        metrics: { marketCap: fr(marketCap / 1e9, 1) + ' Md$', volume: fr(bars[N][5] / 1e6, 1) + ' M', evEbitda: fr(evEbitda, 1) + '×' }, halalStatus: 'unknown' },
      verdict: { score: 54, conviction: 'Moderate', bias: 'Neutral',
        confidence: 'Score éditorial non prédictif. Les chiffres d’entreprise viennent des dépôts SEC et des données XBRL officielles ; les niveaux, du close certifié du 23 septembre.',
        summary: 'HPE a publié le 2 septembre un troisième trimestre à 12,2 Md$ de revenus (+34 %), porté par le réseau, 2,9 Md$ (+74,9 %) depuis l’intégration de Juniper, et par les serveurs, 6,8 Md$ (+35,3 %). La prévision annuelle a été relevée. Le 3 septembre, le titre a ouvert ' + fr(Math.abs(pct(d0903[1], p0903[4])), 1) + ' % sous la veille avant de finir en hausse de ' + fr(pct(d0903[4], p0903[4]), 1) + ' % ; il clôture le 23 à ' + usd(close) + ', environ ' + fr(run, 1) + ' fois son plus bas du 20 novembre 2025 et juste sous le sommet du 2 juin, ' + usd(entry) + '. À ' + fr(evEbitda, 1) + ' fois l’EBITDA GAAP des douze derniers mois, préférentielles converties, HPE se paie moins que Dell (' + dellEb + '), mais nettement plus que Super Micro (' + smciEb + '). Signal utile : une clôture au-dessus de ' + usd(entry) + ', avec un plafond d’achat à ' + usd(cap - entry) + ' seulement au-dessus.',
        whyBuy: [
          'Revenus du troisième trimestre de 12,2 Md$ (+34 %) et marge opérationnelle GAAP de 11,4 %, en hausse de 8,7 points.',
          'Réseau à 2,9 Md$ (+74,9 %) avec Juniper, à 22,0 % de marge opérationnelle de segment.',
          'Prévision de flux libre relevée à au moins 3,75 Md$ sur l’exercice, et 75 % au moins promis aux actionnaires au quatrième trimestre.',
          'Cadre 2027 relevé : croissance des revenus de 13 à 17 % et flux libre d’au moins 5,0 Md$.'],
        whyAvoid: [
          'Le titre vaut environ ' + fr(run, 1) + ' fois son plus bas de novembre 2025, et deux écarts d’ouverture de plus de 8 % en septembre montrent sa nervosité.',
          'Les stocks ont presque doublé depuis octobre, à 11,8 Md$ : un ralentissement des livraisons pèserait sur le flux de trésorerie.',
          '76 millions d’actions naîtront de la conversion obligatoire des préférentielles le 1er septembre 2027, au cours actuel.',
          'Le directeur général Antonio Neri a vendu 250 000 actions le 11 septembre, selon son formulaire 4.'],
        controlChecklist: [
          { label: 'Historique de cours', status: 'pass', statusLabel: 'Trois cents séances continues', evidence: 'Série quotidienne certifiée au close du 23 septembre, source de repli documentée.', action: 'Niveaux et indicateurs recalculés sur cette seule série.' },
          { label: 'Calendrier', status: 'warn', statusLabel: 'Micron le 30 septembre', evidence: 'Micron publie le 30 septembre après la clôture selon deux calendriers concordants, non confirmé ici par l’émetteur ; le coût des mémoires touche les serveurs de HPE. Aucune date de résultats de HPE disponible dans le calendrier collecté ; la date du quatrième trimestre n’est pas annoncée.', action: 'Réduire une position ouverte avant la publication de Micron.' },
          { label: 'Capital', status: 'warn', statusLabel: 'Préférentielles à convertir', evidence: '30 millions de préférentielles se convertiront le 1er septembre 2027 en 76,1 millions d’actions au taux minimal, soit environ 5,7 % de plus.', action: 'Raisonner sur 1 403,5 millions d’actions, pas sur 1 327,5 millions.' }] },
      business: { theme: 'Serveurs d’IA et classiques, réseau d’entreprise et de centres de données, stockage et financement',
        overview: '<p>HPE vend des serveurs, dont des systèmes pour l’IA, du réseau d’entreprise et de centres de données, du stockage, et finance une partie de ces équipements par sa division de services financiers. Au troisième trimestre de l’exercice 2026, clos le 31 juillet, les revenus ont atteint 12,2 Md$ (+34 %) : 9,0 Md$ pour le cloud et l’IA, dont 6,8 Md$ de serveurs, et 2,9 Md$ pour le réseau.</p><p>Le réseau a changé de dimension avec Juniper, racheté le 2 juillet 2025 pour environ 13,4 Md$ en numéraire : ses revenus ont progressé de 74,9 %, dont une hausse de 270 % dans le routage. La marge opérationnelle GAAP du groupe atteint 11,4 %, le résultat opérationnel un record, et la prévision de l’exercice a été relevée, avec un flux libre d’au moins 3,75 Md$.</p><p>La société a aussi soldé sa participation dans le chinois H3C en mai, pour environ 1,36 Md$, avec un gain de 444 M$ enregistré hors exploitation. Un accord de coopération avec le fonds activiste Elliott, amendé en mai, encadre la composition du conseil. Le 10-K cite Dell, Super Micro, Cisco et Lenovo comme concurrents dans les serveurs.</p>',
        moat: 'L’avantage tient à la combinaison du réseau, désormais renforcé par Juniper, des serveurs et du financement : HPE peut vendre un centre de données complet et le financer. Il est plus fort dans le réseau, où les marges atteignent 22 %, que dans les serveurs, où les grands clients mettent les assembleurs en concurrence.',
        segments: [
          { name: 'Cloud et IA', revenue: '9,0 Md$ au troisième trimestre', pct: '74 % des revenus', description: 'Serveurs 6,8 Md$, stockage 1,3 Md$, services financiers 0,9 Md$.' },
          { name: 'Réseau', revenue: '2,9 Md$ au troisième trimestre', pct: '24 % des revenus', description: 'Campus, centres de données, sécurité et routage issus de Juniper.' }],
        sourceRefs: [ref(1), ref(0), ref(2)],
        coverageMatrix: [
          { facet: 'Cours et historique', status: 'COUVERT', decision: 'Trois cents séances continues, close certifié ; base des niveaux et des indicateurs.' },
          { facet: 'Résultats et guidance', status: 'COUVERT — PRIMAIRE', decision: 'Communiqué du 2 septembre et 10-Q ; date du quatrième trimestre non annoncée.' },
          { facet: 'Capital et dette', status: 'COUVERT — PRIMAIRE', decision: 'Préférentielles convertibles comptées au dénominateur, obligations de mars et cession de H3C séparées.' },
          { facet: 'Agrégats GAAP', status: 'COUVERT — XBRL', decision: 'Douze mois glissants au 31 juillet 2026, reconstitués depuis les données XBRL officielles.' },
          { facet: 'Comparables et transmission', status: 'COUVERT — LOCAL', decision: 'Corrélations recalculées sur barres certifiées depuis la fin mars.' },
          { facet: 'Initiés', status: 'PARTIEL', decision: 'Vente du directeur général et d’un administrateur en septembre ; couverture officielle incomplète.' },
          { facet: 'Options', status: 'NON EXPLOITABLE', decision: 'Chaîne relevée en séance le 24 septembre, non rattachée à la clôture de référence.' }] },
      news: [
        { date: '2026-09-03', title: 'Ouverture à ' + sgn(pct(d0903[1], p0903[4]), 1) + ', clôture à ' + sgn(pct(d0903[4], p0903[4]), 1), impact: 'positive', detail: 'Le communiqué est daté du 2 septembre ; la première séance qui le reflète est celle du 3. Ce jour-là, le titre ouvre à ' + usd(d0903[1]) + ', ' + fr(Math.abs(pct(d0903[1], p0903[4])), 2) + ' % sous la clôture de la veille, ' + usd(p0903[4]) + ', descend à ' + usd(d0903[3]) + ', puis clôture à ' + usd(d0903[4]) + ' (' + sgn(pct(d0903[4], p0903[4]), 2) + '). SMH fait ' + sgn(dr('SMH', '2026-09-03'), 2) + ' et Dell ' + sgn(dr('DELL', '2026-09-03'), 2) + ' la même séance : la clôture suit celle de Dell ; c’est l’ouverture en forte baisse, absente chez les pairs, qui est propre à HPE. Un stop placé la veille sous 50 $ aurait été exécuté à l’ouverture, bien plus bas que prévu.', source: 'Barres certifiées', sourceUrl: c.evidenceUrl },
        { date: '2026-09-14', title: 'Gap de ' + fr(pct(d0914[1], p0914[4]), 1) + ' % à l’ouverture', impact: 'negative', detail: 'Après une hausse de ' + fr(pct(bar('2026-09-11')[4], prevOf('2026-09-11')[4]), 1) + ' % le 11 septembre, le titre ouvre à ' + usd(d0914[1]) + ' (' + sgn(pct(d0914[1], p0914[4]), 2) + ') et clôture à ' + usd(d0914[4]) + ' (' + sgn(pct(d0914[4], p0914[4]), 2) + '). Dell fait ' + sgn(dr('DELL', '2026-09-14'), 2) + ', Super Micro ' + sgn(dr('SMCI', '2026-09-14'), 2) + ' et SMH ' + sgn(dr('SMH', '2026-09-14'), 2) + ' la même séance : le repli touche tous les serveurs, HPE plus que les autres ; aucun dépôt ouvert ici n’en donne la cause.', source: 'Barres certifiées', sourceUrl: c.evidenceUrl },
        { date: '2026-05-28', title: 'Cession du solde de H3C', impact: 'neutral', detail: '13,8 % du capital de H3C cédés le 13 mai pour environ 987 M$, puis 5,2 % le 28 mai pour environ 370 M$ ; gain de 444 M$ hors exploitation au troisième trimestre.', source: 'Hewlett Packard Enterprise — SEC', sourceUrl: docs[0].url }],
      fundamentals: { rows: [
          { metric: 'Revenus du troisième trimestre', value: '12,2 Md$', signal: '+34 % sur un an, communiqué du 2 septembre', signalColor: 'green', _src: 1 },
          { metric: 'Réseau du troisième trimestre', value: '2,9 Md$', signal: '+74,9 % avec Juniper, marge de segment de 22,0 %', signalColor: 'green', _src: 1 },
          { metric: 'Prévision du quatrième trimestre', value: '13,9 à 14,8 Md$', signal: 'Bénéfice GAAP de l’exercice guidé entre 2,93 et 3,03 $ par action', signalColor: 'blue', _src: 1 },
          { metric: 'Revenus GAAP sur douze mois', value: fr(G$.rev / 1e9, 2) + ' Md$', signal: 'Douze mois glissants au 31 juillet 2026 (XBRL SEC)', signalColor: 'blue', _src: 'gaap' },
          { metric: 'Résultat opérationnel GAAP sur douze mois', value: fr(G$.ebit / 1e9, 2) + ' Md$', signal: 'Marge de ' + fr(G$.ebit / G$.rev * 100, 1) + ' %, douze mois glissants au 31 juillet 2026', signalColor: 'amber', _src: 'gaap' },
          { metric: 'Résultat net GAAP sur douze mois', value: fr(G$.ni / 1e9, 2) + ' Md$', signal: 'Dont 444 M$ de gain sur la cession de H3C, hors exploitation, et 118 M$ d’impôt associé', signalColor: 'amber', _src: 'gaap', _also: [0] },
          { metric: 'Flux de trésorerie opérationnel sur douze mois', value: fr(G$.ocf / 1e9, 2) + ' Md$', signal: 'Douze mois glissants au 31 juillet 2026', signalColor: 'green', _src: 'gaap' },
          { metric: 'Dette au 31 juillet 2026', value: fr(G$.debt / 1e9, 2) + ' Md$', signal: 'Emprunts à court et long terme, division de financement comprise', signalColor: 'amber', _src: 'gaap' },
          { metric: 'Stocks au 31 juillet 2026', value: '11,8 Md$', signal: 'Contre 6,4 Md$ au 31 octobre 2025 : les commandes de serveurs d’IA immobilisent du fonds de roulement', signalColor: 'amber', _src: 0 },
          { metric: 'Liquidités au 31 juillet 2026', value: fr(G$.cash / 1e9, 2) + ' Md$', signal: 'Trésorerie et équivalents', signalColor: 'blue', _src: 'gaap' },
          { metric: 'EV/EBITDA GAAP', value: fr(evEbitda, 1) + '×', signal: 'Valeur d’entreprise au close du 2026-09-23, 1 403,5 millions d’actions préférentielles converties, sur EBITDA GAAP douze mois au 2026-07-31', signalColor: 'amber', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus Dell à ' + dellEb + ', Super Micro à ' + smciEb + ', Arista à ' + anetEb + ' et Fortinet à ' + ftntEb + ' (fiches publiées, même base et même date), Cisco à ' + fr(cscoEb, 1) + '× et NetApp à ' + fr(ntapEb, 1) + '× (statistiques courantes du 24 septembre, non point-in-time) : HPE se paie entre les assembleurs et les spécialistes du réseau.', _src: 'market', _peers: ['CSCO', 'NTAP'], _peerFiches: ['DELL', 'SMCI', 'ANET', 'FTNT'] },
          { metric: 'EV/revenus GAAP', value: fr(evRev, 2) + '×', signal: 'Valeur d’entreprise au close du 2026-09-23 sur revenus GAAP douze mois au 2026-07-31', signalColor: 'blue', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus la marge opérationnelle GAAP de ' + fr(G$.ebit / G$.rev * 100, 1) + ' % : les revenus sont volumineux et peu margés hors réseau.', _src: 'market' },
          { metric: 'P/E GAAP hors cession de H3C', value: fr(pe, 1) + '×', signal: 'Capitalisation au 2026-09-23, préférentielles converties, sur résultat net GAAP douze mois au 2026-07-31 moins le gain de 444 M$ de H3C net des 118 M$ d’impôt publiés par le 10-Q, soit 326 M$', signalColor: 'amber', source: 'Clôture certifiée, XBRL SEC et 10-Q', comparison: 'Versus le P/E brut de ' + fr(marketCap / G$.ni, 1) + '× : la cession, nette d’impôt, flatte le résultat de ' + fr(326e6 / G$.ni * 100, 1) + ' %.', _src: 'market', _also: [0] },
          { metric: 'EV/EBITDA — scénario de compression (hypothèse éditoriale)', value: fr(scn.price, 2) + ' $ par action', signal: 'Scénario : multiple ramené à douze fois l’EBITDA GAAP douze mois au 2026-07-31 par hypothèse, bilan du 31 juillet, préférentielles converties, soit ' + fr(scn.downside_pct, 0) + ' % sous le close du 2026-09-23', signalColor: 'red', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus Super Micro à ' + smciEb + ' (fiche publiée) : douze fois correspond au multiple de l’assembleur ; ce que coûterait de perdre la prime du réseau, pas un objectif.', _src: 'market', _peerFiches: ['SMCI'] }],
        sourceRefs: [ref(0), ref(1), market('fondamentaux et statistiques')] },
      earnings: { quarters: [],
        beatNote: 'Troisième trimestre de l’exercice 2026 : revenus de 12,2 Md$ (+34 %), marge opérationnelle GAAP de 11,4 % et ajustée de 16,2 %, bénéfice GAAP de 1,06 $ par action, au-dessus de la fourchette annoncée, flux opérationnel de 1,6 Md$. La guidance du quatrième trimestre vise 13,9 à 14,8 Md$ de revenus et 1,12 à 1,22 $ de bénéfice GAAP par action ; celle de l’exercice, 2,93 à 3,03 $ et au moins 3,75 Md$ de flux libre. Le cadre 2027 vise 13 à 17 % de croissance. La date du quatrième trimestre est non annoncée par l’émetteur, et indisponible dans le calendrier collecté.',
        nextEarnings: 'Date non annoncée par l’émetteur et indisponible dans le calendrier collecté.',
        sourceRefs: [ref(1)] },
      capitalStructure: { sharesOutstanding: '1 327 464 779 actions ordinaires au 27 août 2026 (page de garde du 10-Q) et 30 000 000 de préférentielles obligatoirement convertibles',
        sharesAuthorized: 'Actions autorisées non reprises : non décisionnel pour ce dossier.', dilutionRisk: 'moderate',
        shareHistory: 'Base retenue : actions ordinaires en circulation plus conversion obligatoire des préférentielles. Les 30 millions de préférentielles à 7,625 %, émises pour 1,5 Md$, se convertiront automatiquement le 1er septembre 2027 en 2,5352 à 3,1056 actions chacune selon le cours moyen ; au-dessus de 19,72 $, le taux minimal s’applique, soit 76,1 millions d’actions nouvelles, environ 5,7 % de plus. Elles sont comptées au dénominateur et non comme dette. Passage au nombre dilué : 1 327,5 millions d’actions ordinaires au 27 août, plus 76,1 millions issues des préférentielles, soit 1 403,5 millions ; les attributions salariales ne sont pas ajoutées. Les actions ordinaires émises passent de 1 318,3 millions au 31 octobre 2025 à 1 328,1 millions au 31 juillet 2026, par les plans salariés. La dette atteint 20,2 Md$, dont 2,0 Md$ d’obligations émises en mars.',
        warrants: [], atm: { active: false, authorized: 'Aucun programme d’émission d’actions sur le marché relevé', used: 'Sans objet', remaining: 'Sans objet' },
        sourceRefs: [ref(0), ref(2), ref(4)] },
      filingsReview: { summary: 'Cinq dépôts décisionnels ouverts et hachés. Ils montrent un groupe transformé par Juniper, un réseau qui porte les marges, une participation chinoise soldée et une dilution programmée par les préférentielles. L’activisme d’Elliott encadre la gouvernance sans toucher au capital.',
        filings: docs.map(d => ({ date: d.date, form: d.form, accession: d.accession, finding: d.finding, url: d.url })),
        contrarianRisks: [
          'La croissance du réseau mélange Juniper, racheté en juillet 2025, et la croissance interne : la part organique n’est pas isolée dans les documents ouverts.',
          'Les stocks presque doublés depuis octobre supposent des livraisons rapides ; un retard de processeurs ou une annulation les rendrait coûteux.',
          'La conversion des préférentielles ajoutera environ 5,7 % d’actions en septembre 2027.',
          'Le directeur général a vendu 250 000 actions après la publication, dans la hausse.'] },
      technicals: { rsi14: +tech.rsi14.toFixed(2), macd: +tech.macd.toFixed(2), macdSignal: +tech.macdSignal.toFixed(2), ema20: +tech.ema20.toFixed(2), ema50: +tech.ema50.toFixed(2), ema200: +tech.ema200.toFixed(2),
        ma50Type: 'EMA', ma200Type: 'EMA', ma50Available: true, ma200Available: true, atr14: +tech.atr14.toFixed(2),
        badges: ['Au-dessus des moyennes à vingt, cinquante et deux cents séances', fr(Math.abs(pct(close, entry)), 1) + ' % sous le sommet du 2 juin', 'Écarts d’ouverture de plus de 8 % en septembre'],
        supports: [lv('s1'), stop, abandon], resistances: [lv('r1'), lv('r2'), entry],
        setupNote: 'Le titre clôture à ' + usd(close) + ', ' + fr(ext20, 1) + ' % au-dessus de sa moyenne à vingt séances et ' + fr(Math.abs(pct(close, entry)), 1) + ' % sous le sommet du 2 juin, ' + usd(entry) + ', retesté le 21 septembre à ' + usd(lv('r2')) + '. Avant activation, aucune entrée ; une clôture sous ' + usd(abandon) + ', le bas du 17 septembre, abandonne le scénario. Activation sur une clôture au-dessus de $' + entry.toFixed(2) + '. Après activation, stop sous $' + stop.toFixed(2) + ', le plus bas du 21 septembre, soit ' + fr(riskAtr, 2) + ' ATR sous le déclencheur. Supports : ' + usd(lv('s1')) + ', ' + usd(stop) + ' et ' + usd(abandon) + '. Résistances : ' + usd(lv('r1')) + ', ' + usd(lv('r2')) + ' et ' + usd(entry) + ' ; au-dessus, les objectifs sont des projections de la hauteur du couloir.',
        wyckoff: 'Non utilisé : le profil de volume n’est pas exploité dans ce dossier.',
        sourceRefs: [market('barres quotidiennes et indicateurs recalculés')] },
      options: { callOI: 'Non exploitable', putOI: 'Non exploitable', cpRatio: 'Non exploitable', maxPain: 'Non exploitable', ivMean: 'Non exploitable', skew: 'Chaîne relevée en séance le 24 septembre, non rattachée à la clôture de référence', unusual: 'Aucune activité inhabituelle qualifiée', sourceRefs: [market('options')] },
      shortInterest: { siPct: fr(st.shortPercentOfFloat * 100, 2) + ' % du flottant', daysToCover: fr(st.shortRatio, 2) + ' jours, date de règlement non précisée par le snapshot', ctb: 'Coût d’emprunt non disponible à la collecte', trend: 'Positions vendeuses modérées ; aucune thèse de rachat forcé des vendeurs.', squeezeScore: 'Non pertinent', sourceRefs: [market('positions vendeuses')] },
      insiders: { signal: 'Le directeur général Antonio Neri a vendu 250 000 actions le 11 septembre, environ 15,1 M$ selon son formulaire 4 ; l’administrateur Gary Reiner, 17 000 actions le 14 septembre. Aucun achat relevé. Couverture officielle partielle : aucun solde net publié.',
        recentTransactions: [],
        sourceRefs: [market('formulaires 4')] },
      macro: { indicators: [{ name: 'Clôture de référence', value: c.REF, signal: usd(close) + ', séance complète' }, { name: 'Rendement cinq séances', value: sgn(ret(5)), signal: 'Descriptif' }, { name: 'Rendement vingt et une séances', value: sgn(ret(21)), signal: 'Descriptif' }],
        regime: 'neutral', impact: 'HPE vit de l’investissement des entreprises et des opérateurs dans les centres de données et le réseau. Un ralentissement des dépenses d’équipement, ou une hausse du coût des mémoires non répercutée, toucherait d’abord les serveurs, dont les marges sont les plus minces.' },
      risks: { riskScore: 6, riskProfile: 'High',
        riskSummary: 'Le risque de HPE est d’abord dans la nervosité du titre : deux écarts d’ouverture de plus de 8 % en septembre, dans un sens puis dans l’autre, après un triplement en dix mois. Viennent ensuite des stocks presque doublés, la publication de Micron le 30 septembre, qui fixera le ton sur le coût des mémoires, et une dilution de 5,7 % déjà programmée pour 2027.',
        riskCards: [
          { title: 'Écarts d’ouverture violents', severity: 'high', icon: 'fa-arrows-up-down', points: ['Ouverture à ' + sgn(pct(d0903[1], p0903[4]), 1) + ' le 3 septembre.', 'Gap de ' + fr(pct(d0914[1], p0914[4]), 1) + ' % le 14 septembre.'], verdict: 'Un stop peut être franchi d’un coup à l’ouverture : dimensionner comme si la perte pouvait dépasser le stop.' },
          { title: 'Stocks et coûts des composants', severity: 'medium', icon: 'fa-microchip', points: ['Stocks de 11,8 Md$ contre 6,4 Md$ en octobre.', 'Micron publie le 30 septembre, dans l’horizon du plan.'], verdict: 'Une hausse des prix de mémoire annoncée par Micron serait lue comme une pression sur les marges des serveurs.' },
          { title: 'Dilution programmée', severity: 'medium', icon: 'fa-money-bill-trend-up', points: ['76,1 millions d’actions à naître le 1er septembre 2027.', 'Déjà comptées au dénominateur de ce dossier.'], verdict: 'La valorisation par action est calculée sur la base diluée ; celle des sites qui l’ignorent paraît plus flatteuse.' },
          { title: 'Exécution de l’entrée', severity: 'medium', icon: 'fa-door-closed', points: ['Plafond à ' + usd(cap - entry) + ' au-dessus du déclencheur, ' + fr(bufAtr, 2) + ' ATR.', 'Environ ' + fr(blocked, 0) + ' % des ouvertures récentes auraient dépassé cet écart.'], verdict: 'Beaucoup de déclenchements ne seront pas achetables au prix prévu : laisser passer plutôt que payer plus haut.' }],
        pedagogy: 'Le 3 septembre montre la différence entre gap et slippage. Le gap, c’est l’ouverture à ' + usd(d0903[1]) + ' quand la veille finissait à ' + usd(p0903[4]) + ' : tout stop placé entre les deux est exécuté au premier prix disponible. Le slippage, l’écart entre prix voulu et prix obtenu dans une séance normale, reste faible sur environ ' + fr(adv / 1e9, 1) + ' Md$ échangés par séance. Sur ce titre, la taille de la position doit tenir compte du gap, pas seulement de la distance au stop.' },
      tradeIdea: { status: 'watch', statusNote: 'Surveiller. Avant activation : aucune entrée ; une clôture sous ' + usd(abandon) + ' abandonne le scénario. Activation : clôture au-dessus de ' + usd(entry) + ', puis achat à l’ouverture suivante seulement sous ' + usd(cap) + ', ou par ordre limité à ce plafond pendant trois séances, annulé après une clôture sous ' + usd(entry) + ' et jamais laissé actif sur une ouverture sous ' + usd(stop) + '. Après activation : stop sous ' + usd(stop) + '. L’ancien plan du 27 août, neutralisé par la publication du 2 septembre, n’a jamais été activé.',
        entry, stop, tp1, tp2,
        stopPct: pct(stop, entry).toFixed(1) + '%', tp1Pct: '+' + pct(tp1, entry).toFixed(1) + '%', tp2Pct: '+' + pct(tp2, entry).toFixed(1) + '%',
        rr: '1:' + rr1.toFixed(2) + ' TP1 / 1:' + rr2.toFixed(2) + ' TP2',
        entryNote: 'Déclencheur sur clôture au-dessus du plus haut du 2 juin, pas sur un franchissement en séance. Entrée à l’ouverture suivante uniquement sous ' + usd(cap) + ' : au-delà, le R/R vers TP1 tomberait sous 1,5 avec le même stop. Ce plafond n’est qu’à ' + usd(cap - entry) + ' au-dessus du déclencheur, soit ' + fr(bufAtr, 2) + ' ATR. Mesure : sur les ' + gs.total + ' dernières séances, ' + gs.up + ' ouvertures ont dépassé la clôture de la veille de plus de ' + usd(cap - entry) + ', soit environ ' + fr(blocked, 0) + ' % ; l’écart d’ouverture médian, dans un sens ou dans l’autre, vaut ' + usd(gs.medAbs) + '. Sur la série, ' + bk.n + ' clôtures ont cassé un plus haut de vingt séances : ' + bk.inBand + ' ont fini à moins de ' + fr(bufPct, 2) + ' % au-dessus du niveau cassé, l’écart relatif du plafond, et ' + bk.buyable + ' ont ensuite ouvert sous ce seuil, soit environ ' + fr(bufOpen * 100, 0) + ' % des cassures' + (bufOpen < 0.25 ? ' : l’entrée à l’ouverture est quasi inexécutable.' : ' : l’entrée à l’ouverture reste possible, mais moins d’une fois sur deux.') + ' Plan de repli : si l’ouverture dépasse le plafond, un ordre à cours limité à ' + usd(cap) + ', valable trois séances, garde le même R/R et le même stop. Bornes de cet ordre : il est annulé après toute clôture sous le déclencheur, ' + usd(entry) + ' ; il n’est pas laissé actif à l’ouverture d’une séance qui ouvre sous le stop, ' + usd(stop) + ', ni si le stop est touché avant exécution. Rejouées avec ces bornes sur les ' + rt.miss + ' cassures non achetables à l’ouverture, l’ordre aurait été exécuté ' + rt.back + ' fois' + (rt.stopSame ? ', dont ' + rt.stopSame + ' avec le stop touché la même séance' : ', sans que le stop soit touché la même séance') + (rt.gapUnder ? ' ; ' + rt.gapUnder + ' fois retiré sur une ouverture sous le stop' : ' ; aucun retrait sur ouverture sous le stop') + (rt.fillCloseUnder ? ' ; ' + rt.fillCloseUnder + ' de ces exécutions ont fini la séance sous le niveau cassé.' : ' ; aucune exécution n’a fini la séance sous le niveau cassé.') + ' La borne de clôture sous le déclencheur n’est pas comptée à part : une telle clôture suppose que le plafond a été touché dans la séance, donc que l’ordre a déjà été exécuté. Définition statistique, identique au gabarit du lot précédent : une cassure est la première clôture au-dessus du plus haut des vingt séances précédentes, la veille ayant clôturé à ce niveau ou dessous ; le plan, lui, s’active sur toute clôture au-dessus du déclencheur.' + ' Objectifs : TP1 à une hauteur de couloir au-dessus du déclencheur, TP2 à une fois et demie. Liquidité : environ ' + fr(adv / 1e9, 1) + ' Md$ échangés par séance, médiane des vingt dernières. Exemple de taille, non personnalisé : avec un budget de perte de 100 $, le risque au plafond, ' + usd(cap - stop) + ' par action, donne ' + sizeExample + ' actions ; un gap comme celui du 3 septembre pourrait doubler la perte réelle.',
        horizon: 'Dix séances après activation',
        thesis: 'Le marché a d’abord douté du trimestre, puis l’a racheté dans la séance du 3 septembre ; le titre est revenu sous son sommet de juin. Une clôture au-dessus de $' + entry.toFixed(2) + ' montrerait que les acheteurs paient la prime du réseau. Avant activation, une clôture sous ' + usd(abandon) + ' abandonne le dossier. Après activation, le stop sous $' + stop.toFixed(2) + ' limite le coût d’une fausse sortie. TP1 à ' + usd(tp1) + ' et TP2 à ' + usd(tp2) + '. Ne pas anticiper le déclencheur, ne pas acheter un gap au-dessus du plafond, réduire avant la publication de Micron.',
        catalysts: ['Une clôture au-dessus du plus haut du 2 juin, sur un volume au moins égal à la médiane récente.', 'La publication de Micron le 30 septembre, date donnée par deux calendriers concordants, après la clôture selon l’un d’eux : le coût des mémoires touche les serveurs.', 'Tout commentaire sur la croissance interne du réseau hors Juniper.'],
        invalidation: ['Avant activation : une clôture sous ' + usd(abandon) + ', bas du couloir, abandonne le scénario.', 'Après activation : une clôture sous ' + usd(stop) + ' invalide le trade.', 'Ouverture au-dessus de ' + usd(cap) + ' après la clôture de déclenchement : pas d’achat à l’ouverture ; seul l’ordre limité à ' + usd(cap) + ' reste valable trois séances.', 'Ordre limité de repli annulé après une clôture sous ' + usd(entry) + ', retiré avant toute ouverture sous le stop à ' + usd(stop) + ' et si le stop est touché avant exécution.', 'Une baisse de prévision d’un grand assembleur de serveurs avant activation annule la thèse.'] },
      globalScore: { profile: 'Réseau renforcé, serveurs portés par l’IA, titre nerveux',
        keyTakeawaysPositive: ['Revenus +34 %, réseau +74,9 %.', 'Marge GAAP record de 11,4 %.', 'Flux libre d’au moins 3,75 Md$ guidé.'],
        keyTakeawaysNegative: ['Titre triplé en dix mois.', 'Stocks presque doublés.', 'Préférentielles : 5,7 % d’actions en plus en 2027.'],
        mindsetTip: 'Un titre qui ouvre à −8 % et finit à +5 % le même jour dit une chose : le marché n’est pas d’accord avec lui-même. Réduire la taille, c’est accepter ce désaccord plutôt que de le parier.' },
      social: { platforms: [], sourceRefs: [market('sentiment non retenu faute de mesure qualifiée')] },
      disclaimer: 'Document de recherche éducatif. Ni conseil financier, ni signal de trading. Statut surveiller : aucun ordre actif.',
    };
  },
  groups: [
    { name: 'Référence des serveurs d’entreprise', order: 1, transmission: 'Le titre coté qui co-évolue le plus avec HPE depuis fin mars, premier concurrent cité par le 10-K.', rows: [
      ['DELL', 'leader', 'Premier assembleur de serveurs d’IA', 'Corrélation la plus forte avec HPE depuis fin mars ; ses commandes et ses marges se lisent directement sur les serveurs de HPE.']] },
    { name: 'Pairs directs', order: 1, transmission: 'Mêmes acheteurs de serveurs, de réseau et de stockage.', rows: [
      ['SMCI', 'direct_peer', 'Assembleur de serveurs d’IA', 'Concurrent cité par le 10-K ; ses marges montrent la pression des grands clients sur les prix des serveurs.'],
      ['CSCO', 'direct_peer', 'Réseau d’entreprise et serveurs', 'Concurrent cité par le 10-K et premier rival du réseau renforcé par Juniper.'],
      ['ANET', 'direct_peer', 'Réseau des centres de données', 'Concurrent sur les commutateurs des centres de données, segment où HPE croît de 112 %.'],
      ['NTAP', 'direct_peer', 'Stockage de données d’entreprise', 'Concurrent sur le stockage ; sa croissance mesure la demande de données liée à l’IA.'],
      ['IBM', 'direct_peer', 'Serveurs, stockage et services', 'Concurrent sur les infrastructures des grands comptes et le cloud hybride.']] },
    { name: 'Amont : processeurs et mémoires', order: 1, transmission: 'HPE achète processeurs et mémoires : leurs prix et leurs allocations font ses marges de serveurs.', rows: [
      ['NVDA', 'upstream', 'Processeurs graphiques des serveurs d’IA', 'Fournisseur des processeurs d’IA ; ses allocations fixent le rythme des livraisons de systèmes.'],
      ['AMD', 'upstream', 'Processeurs et accélérateurs', 'Fournisseur de processeurs de serveurs et d’accélérateurs, notamment pour le calcul haute performance.'],
      ['INTC', 'upstream', 'Processeurs de serveurs', 'Fournisseur de processeurs pour les serveurs classiques ; ses délais de livraison conditionnent la partie non IA du parc.'],
      ['MU', 'upstream', 'Mémoires DRAM et HBM', 'Fournisseur de mémoires ; publie le 30 septembre, dans l’horizon du plan, avec un effet direct sur les coûts.']] },
    { name: 'Second ordre : réseau et sécurité', order: 2, transmission: 'Même cycle d’équipement réseau que Juniper et les campus de HPE.', rows: [
      ['CIEN', 'second_order', 'Réseau optique longue distance', 'Même vague d’investissement dans les liaisons entre centres de données que le routage de Juniper.'],
      ['NOK', 'second_order', 'Réseau optique et routage', 'Concurrent de Juniper dans le routage des opérateurs ; ses commandes éclairent ce segment.'],
      ['FFIV', 'second_order', 'Distribution applicative et sécurité', 'Même clientèle de centres de données et de sécurité réseau.'],
      ['FTNT', 'second_order', 'Pare-feu et réseau sécurisé', 'Concurrent de la sécurité réseau de HPE ; son cycle de renouvellement touche les mêmes campus.'],
      ['PANW', 'second_order', 'Plateforme de sécurité', 'Concurrent sur la sécurité réseau, segment de HPE en hausse de 75,6 %.'],
      ['HPQ', 'second_order', 'Ordinateurs et imprimantes d’entreprise', 'Même clientèle d’entreprises pour l’équipement informatique ; sert surtout de repère de multiple, sans lien commercial documenté.']] },
    { name: 'Contrôles sectoriels', order: 2, transmission: 'Paniers de référence pour isoler ce qui est propre à HPE.', rows: [
      ['SMH', 'sector_proxy', 'Panier de semi-conducteurs', 'Mesure le cycle de ses fournisseurs : un écart avec ce panier isole ce qui est propre à HPE.'],
      ['XLK', 'sector_proxy', 'Panier technologique du S&P 500', 'Contrôle large de la technologie : un mouvement commun avec ce panier n’a rien de spécifique.'],
      ['QQQ', 'sector_proxy', 'Grandes valeurs du Nasdaq', 'Contrôle large : un mouvement commun avec ce panier n’a rien de spécifique au titre.']] },
  ],
  eventDefault: { leader: 'Aucune publication dans les quatorze jours collectés ; ses commandes de serveurs restent le signal à suivre', direct_peer: 'Aucune publication dans les quatorze jours collectés ; ses prix et ses marges peuvent déplacer les parts de marché', upstream: 'Aucune publication dans les quatorze jours collectés ; prix et allocations à suivre', second_order: 'Aucune publication dans les quatorze jours collectés ; ses commandes éclairent le cycle réseau', sector_proxy: 'Panier sans publication propre ; exposé aux résultats de ses grandes pondérations' },
  eventRisk: { MU: 'Publication le 30 septembre après la clôture, date donnée par deux calendriers concordants et non confirmée ici par l’émetteur : risque de gap sur les coûts de mémoire, dans l’horizon du plan' },
  blastDoc: 2,
  scenarios: c => [
    { scenario: 'bullish', trigger: 'Micron rassure sur les volumes et les assembleurs confirment la demande.', firstOrder: 'Le titre clôture au-dessus du sommet du 2 juin.', secondOrder: 'Dell et Arista suivent ; SMH confirme.', confirmation: 'Une clôture au-dessus de ' + c.usd(c.entry) + ' avec Dell en hausse.', contradiction: 'Un dépassement du sommet pendant que Dell recule.' },
    { scenario: 'mixed', trigger: 'Pas de nouvelle propre avant la publication de Micron.', firstOrder: 'Le titre oscille entre le bas du 17 septembre et le sommet de juin.', secondOrder: 'L’écart avec Dell reste faible, sans information propre au titre.', confirmation: 'Des clôtures entre ' + c.usd(c.abandon) + ' et ' + c.usd(c.entry) + ' pendant plusieurs séances.', contradiction: 'Une sortie franche d’un côté ou de l’autre.' },
    { scenario: 'bearish', trigger: 'Hausse des prix de mémoire annoncée par Micron, ou baisse de commandes d’un grand cloud.', firstOrder: 'Le titre repasse sous le bas du 17 septembre.', secondOrder: 'Les assembleurs reculent plus que le réseau.', confirmation: 'Une clôture sous ' + c.usd(c.abandon) + ' avec Dell en baisse.', contradiction: 'Un repli des serveurs que HPE ne suit pas grâce au réseau.' }],
  contradictions: c => ['Le trimestre bat la prévision, mais le titre a ouvert à ' + c.sgn(c.pct(c.bars.find(b => b[0] === '2026-09-03')[1], c.bars[c.bars.findIndex(b => b[0] === '2026-09-03') - 1][4]), 1) + ' avant de se retourner : la lecture du marché a changé en une séance.', 'Une corrélation élevée avec Dell ne prouve pas un lien commercial ; le distributeur à 10 % des créances n’est pas nommé.'],
  missingData: c => ['Aucun client à plus de 10 % du chiffre d’affaires et un distributeur non nommé : aucun client coté n’entre dans les comparables comme client documenté.', 'Croissance interne du réseau hors Juniper non isolée ; date du quatrième trimestre non disponible.', 'Chaîne d’options relevée en séance, non rattachée à la clôture ; sentiment non retenu.', 'Barres d’une source de repli pour toutes les séries.'],
  limitations: ['Barres d’une source de repli (Webull).', 'Options non rattachées à la clôture de référence.', 'Dette de la division de financement incluse dans la valeur d’entreprise.'],
});
