'use strict';
// Dossier NOW v3 au close du 2026-09-23 (lot R04). Aucun plan actif : le titre est au milieu de son couloir
// de septembre et aucun stop structurel ne donne un R/R de 1,5 ; les niveaux du 27 août restent affichés
// comme référence archivée. Calculs, provenance et preuves délégués au gabarit tools/lib/analysis-v3-r04.cjs.
const R = require('../../../../tools/lib/analysis-v3-r04.cjs');
const GEN = 'analyses/NOW/_runs/20260924/build-now.cjs';

R.build({
  ticker: 'NOW', shortName: 'ServiceNow', cik: 1373715, generator: GEN, mode: 'archived',
  xbrl: { ttm: { rev: ['RevenueFromContractWithCustomerExcludingAssessedTax'], ebit: ['OperatingIncomeLoss'], ni: ['NetIncomeLoss'], da: ['DepreciationDepletionAndAmortization'], ocf: ['NetCashProvidedByUsedInOperatingActivities'] },
    instant: { ltd: ['LongTermDebt'], std: ['ShortTermBorrowings'], cashEq: ['CashAndCashEquivalentsAtCarryingValue'], msc: ['AvailableForSaleSecuritiesDebtSecuritiesCurrent'], msn: ['AvailableForSaleSecuritiesDebtSecuritiesNoncurrent'] }, da: ['da'], debt: ['ltd', 'std'], cash: ['cashEq', 'msc', 'msn'] },
  scenarioBasis: 'revenue', scenarioMultiple: 7,
  valuationBasis: 'GAAP douze mois au 2026-06-30 (XBRL SEC) ; dette = obligations et billets de trésorerie à leur valeur comptable du 30 juin ; trésorerie = liquidités et titres négociables à court et long terme, participations stratégiques exclues ; 1 033,9 millions d’actions au 30 juin ; multiple de sept fois les revenus = hypothèse éditoriale',
  levels: { s1: { d: '2026-09-23', c: 3 }, s2: { d: '2026-09-18', c: 3 }, s3: { d: '2026-09-11', c: 3 }, r1: { d: '2026-09-15', c: 2 }, r2: { d: '2026-08-31', c: 2 }, r3: { d: '2026-01-02', c: 2 } },
  supports: ['s1', 's2', 's3'], resistances: ['r1', 'r2', 'r3'],
  inventory: 27,
  reviewScope: 'Dépôts EDGAR de ServiceNow du 1er janvier au 23 septembre 2026 (27 formulaires hors formulaires 3, 4, 5 et 144), dont le 10-K de l’exercice 2025. Les 8-K de gouvernance (items 5.02, 5.07), les procurations et leurs compléments, le rapport annuel illustré, le 8-K d’information du 13 février et les prospectus d’obligations 424B2 et 305B2, repris par le 8-K du 15 mai, sont écartés. Les S-8 enregistrent les plans d’actions repris lors des rachats : pas des levées de fonds. Le 10-Q et le communiqué du premier trimestre sont couverts par ceux du deuxième.',
  docs: [
    ['2026-07-23', '10-Q', '0001373715-26-000076', 'now-20260630.htm', 'q2-10q__now-20260630.htm',
      'Rapport trimestriel au 30 juin 2026 : Armis racheté le 20 avril pour environ 7,6 Md$ en numéraire ; 4,0 Md$ d’obligations émises en mai, prêt relais de 4 Md$ remboursé ; 2,08 Md$ de dette à court terme. 20,2 millions d’actions rachetées au semestre ; environ 1 034 millions d’actions au 30 juin. Marge brute des abonnements à 73 % contre 80 % un an plus tôt.'],
    ['2026-07-22', '8-K / Exhibit 99.1', '0001373715-26-000072', 'erq2fy26.htm', 'q2-8k__erq2fy26.htm',
      'Communiqué du deuxième trimestre, publié après la clôture : abonnements de 3 877 M$ (+24,5 %), obligations de performance à douze mois de 13,20 Md$ (+21 %), résultat opérationnel GAAP de 162 M$ (4 %). Prévision d’abonnements 2026 relevée à 15 760–15 780 M$ ; troisième trimestre attendu à 3 975–3 980 M$ (+20,5 %).'],
    ['2026-01-29', '10-K', '0001373715-26-000007', 'now-20251231.htm', 'fy25-10k__now-20251231.htm',
      'Rapport annuel 2025 : un partenaire fédéral intégrateur, non nommé, a représenté 11 % des revenus de 2025 comme de 2024, et 11 % des créances : c’est un revendeur auprès des administrations. Concurrents cités : Microsoft, Oracle, SAP, Salesforce et Workday.'],
    ['2026-04-22', '8-K', '0001373715-26-000054', 'now-20260417.htm', 'apr22-8k__now-20260417.htm',
      'Prêt à terme non garanti de 4 Md$, échéance 16 octobre 2026, destiné à financer une partie du prix d’Armis ; remboursé depuis selon le 10-Q.'],
    ['2026-05-15', '8-K', '0001193125-26-226644', 'd60522d8k.htm', 'may15-8k__d60522d8k.htm',
      'Émission de cinq séries d’obligations non garanties à échéances 2028, 2031, 2033, 2036 et 2056, pour 4,0 Md$ au total selon le 10-Q : elles refinancent le prêt relais d’Armis. De la dette, aucune action nouvelle.'],
  ],
  needles: {
    q2q: [0, ['for preliminary purchase price consideration of approximately $ 7.6 billion, settled in cash', 'we issued five series of fixed-rate senior unsecured notes for an aggregate principal amount of $ 4.0 billion', 'Repayment of term loan ( 4,000 )', 'Short-term debt, net 2,082', 'Long-term debt, net 5,435 1,491', 'shares outstanding: 1,033,862 and 1,047,278', 'Common stock repurchased — — ( 20,154 ) ( 2,333 )', 'As of June 30, 2026, there were approximately 1,034 million shares', 'Unrealized (gains) losses on strategic investments ( 360 ) ( 5 )', 'Subscription 73% 80% 75% 81 %', 'Amortization of purchased intangibles 219 25 NM 296 46 NM', 'Business combination and other related costs 75 14 NM', 'On March 2, 2026, we acquired all outstanding shares of Veza Technologies', 'Proceeds from issuance of commercial paper, net of discount 3,534', 'Strategic investments 2,073 1,542', 'approved and declared a 5 -for-1 split of our common stock']],
    q2: [1, ['Subscription revenues of $3,877 million in Q2 2026, representing 24.5% year-over-year growth', 'Current remaining performance obligations of $13.20 billion as of Q2 2026, representing 21% year-over-year growth', 'Income from operations $ 162 4 % $ 1,173 29.5 %', 'Subscription revenues $15,760 - $15,780 22.5 %', 'Subscription revenues $3,975 - $3,980 20.5 %', 'Free cash flow $ 634 16 %', 'ServiceNow AI crossed $1 billion in annual contract value in Q2 2026', 'ServiceNow surpassed $1 billion in AWS Marketplace transactions', 'ServiceNow and Accenture launched a joint offering to help enterprises migrate off legacy cybersecurity platforms', 'ServiceNow and NVIDIA deepened their partnership', 'Other income (expense), net 206 (3) 288 (14)', 'Unrealized (gains) losses on strategic investments (273) (5) (360) (5)', 'The conference call will begin at 2 p.m. Pacific Daylight Time (21:00 GMT) on July 22, 2026']],
    annual: [2, ['We had one customer, a U.S. federal channel partner and systems integrator, that represented 11 % and 12 % of our accounts receivable balance as of December 31, 2025 and 2024, respectively, and 11 % of our total revenues', 'enterprise application software vendors, both cloud-based and on-premises, such as Microsoft, Oracle, SAP, Salesforce and Workday']],
    term: [3, ['providing for a $4 billion unsecured term loan (the "Term Loan") that matures on October 16, 2026', 'to finance a portion of the cash consideration used to acquire Armis Security Ltd.']],
    notes: [4, ['the 2028 Notes, the 2031 Notes, the 2033 Notes, the 2036 Notes and the 2056 Notes']],
  },
  sectionDocs: { verdict: [1, 0], business: [0, 1, 2], news: [1, 0], earnings: [1], capitalStructure: [0, 3, 4], filingsReview: [0, 1, 2, 3, 4], risks: [0, 1], globalScore: [1], meta: [1], disclaimer: [1], macro: [1], options: [1], social: [1], header: [0] },
  score: { business: 26, technical: 2, capital: 1, calendar: 0, dilution: 0, risk: 25 },
  peers: true,
  peerFicheSha: { CRM: '763ea84630b4e183af526f8436a95a9ad6eb0a229067dffef1ef057fd9a0f6a3', ORCL: '3545a580330902ddfea6118a62f49a6d7e8fa8c5ced1763f57d1793a5af3e4d3', DDOG: '4aa033d564c5b77f2d8334c69347e5a4dd745de8369a3ccd7aa7157abac422e4' },
  shares: { value: 1033862000, doc: 0 },
  route: (p, { prov, dep, B }) => /^news\.[01]\./.test(p) ? prov('bars', B, 'Ouverture et clôture lues sur les barres certifiées ; écart d’ouverture = ouverture / clôture de la veille − 1 ; comparaison avec IGV et les pairs sur la même séance.', [dep('comparison', '')]) : null,
  riskScoreReason: 'Jugement qualitatif sur dix : rachat d’Armis financé par la dette, marge GAAP écrasée par l’amortissement des actifs acquis et titre au milieu d’un couloir sans point d’entrée.',
  compose: c => {
    const { fr, usd, pct, sgn, dfr, close, prev, bars, N, tech, st, M, adv, ret, G$, marketCap, ev, scn, lv, entry, stop, tp1, tp2, rr1, rr2, ref, market, docs, raw, peerStat, peerFiche, archive } = c;
    const cmp = raw.comparison_bars.data.items[0].results[0].data;
    const dr = (sym, d) => { const b = cmp.find(x => x.symbol === sym).bars, i = b.findIndex(x => x[0] === d); return pct(b[i][4], b[i - 1][4]); };
    const bar = d => bars.find(b => b[0] === d), prevOf = d => bars[bars.findIndex(b => b[0] === d) - 1];
    const d0723 = bar('2026-07-23'), p0723 = prevOf('2026-07-23'), d0827 = bar('2026-08-27'), p0827 = prevOf('2026-08-27');
    const low0723 = d0723[3], run = pct(lv('r2'), low0723);
    const igv21 = M.IGV.return21d, own21 = ret(21);
    const evRev = ev / G$.rev, evEbitda = ev / G$.ebitda, evFwd = ev / 15.77e9;
    const crm = peerFiche('CRM', 'EV/revenus GAAP').value, orcl = peerFiche('ORCL', 'EV/revenus GAAP').value, ddog = peerFiche('DDOG', 'EV/revenus GAAP').value, crmEb = peerFiche('CRM', 'EV/EBITDA GAAP').value;
    const wday = peerStat('WDAY', 'enterpriseToRevenue'), adbe = peerStat('ADBE', 'enterpriseToRevenue');
    // Test d'un achat sur cassure du plus haut du 31 août, stop sous le bas du 18 septembre, objectif le plus haut du 2 janvier.
    const bo = { e: lv('r2'), s: lv('s2'), t: lv('r3') }; bo.rr = (bo.t - bo.e) / (bo.e - bo.s);
    const niX = G$.ni - 360e6 * 0.79;
    // Ancien plan du 28 août (archive) : condition sur clôture de quinze minutes au-dessus de l'entrée archivée.
    const A = archive.tradeIdea, iA = bars.findIndex(b => b[0] === '2026-08-28'), iC = bars.findIndex((b, i) => i >= iA && b[4] > A.entry);
    const cA = bars[iC], after = bars.slice(iC), lowA = after.reduce((m, b) => b[3] < m[3] ? b : m), highA = after.reduce((m, b) => b[2] > m[2] ? b : m);
    const hz = bars[iC + 10];
    const archNote = 'Leur condition, une clôture de quinze minutes au-dessus de ' + usd(A.entry) + ', a très probablement été remplie le ' + dfr(cA[0]) + ' sur la base des clôtures et des plus hauts (clôture ' + usd(cA[4]) + ', plus haut ' + usd(cA[2]) + ') ; les barres de quinze minutes manquent pour l’affirmer. Depuis, le stop archivé à ' + usd(A.stop) + ' n’a pas été touché (plus bas ' + usd(lowA[3]) + ' le ' + dfr(lowA[0]) + ') et le TP1 à ' + usd(A.tp1) + ' non plus (plus haut ' + usd(highA[2]) + ' le ' + dfr(highA[0]) + '). L’horizon de dix séances a échu le ' + dfr(hz[0]) + ', clôture à ' + usd(hz[4]) + ', soit ' + sgn(pct(hz[4], A.entry), 1) + ' sur l’entrée archivée.';
    return {
      meta: { lang: 'fr', dir: 'ltr', level: 'intermediate', tags: ['us', 'equities', 'ai-chain', 'software', 'technology'], grade: 'B-', date: '2026-09-24', dateDisplay: '24 septembre 2026', version: 3, status: 'no-trade', assetType: 'stock', levelsCloseDate: c.REF,
        description: 'ServiceNow : des abonnements à +24,5 %, Armis payé 7,6 Md$ en numéraire et un titre coincé au milieu de son couloir. Dossier au close du 23 septembre 2026, aucun plan actif.',
        ogDescription: 'ServiceNow : abonnements +24,5 %, prévision relevée, mais marge GAAP à 4 % après Armis ; titre à 140,78 $, entre 130 et 150 $ ; pas d’entrée au cours actuel.',
        lastMcpRefresh: raw.status.captured_at, levelsVerifiedAt: raw.status.captured_at,
        statusHistory: [{ at: raw.status.captured_at, from: 'wait', to: 'no-trade', note: 'refonte v3 du 24 septembre : aucun plan au cours actuel, clôture de référence du 2026-09-23', close }] },
      header: { ticker: 'NOW', name: 'ServiceNow, Inc.', exchange: 'NYSE', sector: 'Logiciel d’automatisation des processus d’entreprise et de sécurité', price: close, changePct: pct(close, prev),
        badges: [{ text: 'AUCUN PLAN — MILIEU DE COULOIR', color: 'gray' }, { text: 'Chaîne IA — agents et gouvernance de l’IA en entreprise', color: 'purple' }],
        metrics: { marketCap: fr(marketCap / 1e9, 0) + ' Md$', volume: fr(bars[N][5] / 1e6, 1) + ' M', evRevenue: fr(evRev, 1) + '×' }, halalStatus: 'unknown' },
      verdict: { score: 54, conviction: 'Low', bias: 'Neutral',
        confidence: 'Score éditorial non prédictif. Les chiffres d’entreprise viennent des dépôts SEC et des données XBRL officielles ; les niveaux, du close certifié du 23 septembre.',
        summary: 'ServiceNow a publié le 22 juillet des abonnements à 3 877 M$, en hausse de 24,5 %, et relevé sa prévision annuelle à 15 760–15 780 M$. Le même trimestre montre ce qu’a coûté Armis, racheté le 20 avril pour environ 7,6 Md$ en numéraire : un résultat opérationnel GAAP de 162 M$, soit 4 % des revenus, une marge brute des abonnements tombée de 80 % à 73 %, et une dette passée de 1,5 à 7,5 Md$. Le titre, après un plus bas de ' + usd(low0723) + ' le 23 juillet, est remonté jusqu’à ' + usd(lv('r2')) + ' le 31 août, puis a reculé dans un couloir de 130 à 150 $ ; il clôture à ' + usd(close) + '. À ' + fr(evRev, 1) + ' fois ses revenus GAAP des douze derniers mois, il se paie près du double de Salesforce (' + crm + '). Aucun plan : au milieu du couloir, aucun stop structurel ne laisse un R/R de 1,5.',
        whyBuy: [
          'Abonnements du deuxième trimestre de 3 877 M$ (+24,5 %) et obligations de performance à douze mois de 13,20 Md$ (+21 %).',
          'Prévision d’abonnements 2026 relevée à 15 760–15 780 M$ ; marge de flux libre visée à 35 % sur l’année.',
          '20,2 millions d’actions rachetées au premier semestre : le nombre d’actions a baissé de 1,3 % depuis décembre.',
          'La société revendique plus de 1 Md$ de valeur annuelle de contrats sur son offre d’IA au deuxième trimestre.'],
        whyAvoid: [
          'Résultat opérationnel GAAP de 162 M$ au trimestre, 4 % des revenus, après 219 M$ d’amortissement des actifs acquis et 75 M$ de coûts liés aux rachats.',
          'Dette de 7,5 Md$ au 30 juin, contre 1,5 Md$ en décembre, dont 2,08 Md$ à court terme.',
          'Le troisième trimestre est guidé à +20,5 % d’abonnements, contre +24,5 % au deuxième : la croissance ralentit, rachats compris.',
          'Au close du 23 septembre, la valeur d’entreprise représente ' + fr(evRev, 1) + ' fois les revenus GAAP des douze mois clos le 30 juin.'],
        controlChecklist: [
          { label: 'Historique de cours', status: 'pass', statusLabel: 'Trois cents séances continues', evidence: 'Série quotidienne certifiée au close du 23 septembre, en base ajustée du fractionnement par cinq de décembre 2025.', action: 'Supports et résistances lus sur cette seule série.' },
          { label: 'Point d’entrée', status: 'fail', statusLabel: 'Milieu de couloir', evidence: 'Clôture à ' + usd(close) + ' entre ' + usd(lv('s3')) + ' et ' + usd(lv('r2')) + ' ; un achat sur cassure du 31 août ne vise que ' + usd(bo.t) + ' pour un stop sous ' + usd(bo.s) + '.', action: 'Pas de plan tant que le titre n’a pas choisi un côté du couloir.' },
          { label: 'Calendrier', status: 'pass', statusLabel: 'Accenture le 1er octobre', evidence: 'Aucune date de résultats de ServiceNow dans les quatorze jours collectés ; le calendrier de marché place le troisième trimestre au 28 octobre, date non confirmée par l’émetteur dans les dépôts ouverts. Accenture, partenaire commercial, publie le 1er octobre selon deux calendriers concordants, avant l’ouverture selon l’un d’eux.', action: 'Vérifier la date de ServiceNow avant tout nouveau plan.' }] },
      business: { theme: 'Plateforme d’automatisation des processus, de gestion des services informatiques et de sécurité',
        overview: '<p>ServiceNow vend par abonnement une plateforme qui gère les demandes et les incidents des services informatiques, puis les processus des ressources humaines, du service client et de la sécurité. Au deuxième trimestre 2026, les abonnements ont atteint 3 877 M$, en hausse de 24,5 %, sur 3 987 M$ de revenus totaux. Les obligations de performance à douze mois, 13,20 Md$, progressent de 21 %.</p><p>La société a changé de taille en 2026. Elle a racheté Veza, spécialiste de la gouvernance des identités, le 2 mars, puis Armis, spécialiste de l’inventaire et de la sécurité des équipements connectés, le 20 avril, pour environ 7,6 Md$ en numéraire. Le financement est passé par un prêt relais de 4 Md$, remboursé depuis par 4,0 Md$ d’obligations émises en mai, et par des billets de trésorerie : la dette atteint 7,5 Md$ au 30 juin, contre 1,5 Md$ en décembre. L’amortissement des actifs acquis atteint 219 M$ au trimestre contre 25 M$ un an plus tôt, et la marge brute des abonnements tombe à 73 % contre 80 % ; le 10-Q attribue la hausse des coûts d’abonnement aux effectifs et aux marchés réglementés, et prévoit que l’amortissement des actifs acquis continue de peser.</p><p>Un partenaire fédéral intégrateur, non nommé, a représenté 11 % des revenus de 2025 : c’est un revendeur auprès des administrations, pas un client final. Le 10-K cite Microsoft, Oracle, SAP, Salesforce et Workday comme concurrents.</p>',
        moat: 'L’avantage tient à la place de la plateforme dans l’entreprise : elle enregistre les actifs, les incidents et les demandes de tous les services, ce qui rend son remplacement long et risqué. Il est solide dans l’informatique, moins établi dans la sécurité, où Armis doit encore faire ses preuves face aux spécialistes.',
        segments: [
          { name: 'Abonnements', revenue: '3 877 M$ au deuxième trimestre', pct: '97 % des revenus', description: 'Plateforme, flux de travail, sécurité et IA.' },
          { name: 'Services professionnels et autres', revenue: '110 M$ au deuxième trimestre', pct: '3 % des revenus', description: 'Déploiement et formation, en perte brute.' }],
        sourceRefs: [ref(0), ref(1), ref(2)],
        coverageMatrix: [
          { facet: 'Cours et historique', status: 'COUVERT', decision: 'Trois cents séances continues, base ajustée du fractionnement de décembre 2025.' },
          { facet: 'Résultats et guidance', status: 'COUVERT — PRIMAIRE', decision: 'Communiqué du 22 juillet et 10-Q ; date du troisième trimestre non annoncée par l’émetteur.' },
          { facet: 'Capital et dette', status: 'COUVERT — PRIMAIRE', decision: 'Prêt relais, obligations de mai, billets de trésorerie et rachats d’actions séparés.' },
          { facet: 'Agrégats GAAP', status: 'COUVERT — XBRL', decision: 'Douze mois glissants au 30 juin 2026, reconstitués depuis les données XBRL officielles.' },
          { facet: 'Comparables et transmission', status: 'COUVERT — LOCAL', decision: 'Corrélations recalculées sur barres certifiées depuis la fin mars.' },
          { facet: 'Initiés', status: 'PARTIEL', decision: 'Trois ventes de dirigeants fin août ; couverture officielle incomplète.' },
          { facet: 'Options', status: 'NON EXPLOITABLE', decision: 'Chaîne relevée en séance le 24 septembre, non rattachée à la clôture de référence.' }] },
      news: [
        { date: '2026-07-23', title: 'Gap de +' + fr(pct(d0723[1], p0723[4]), 1) + ' % effacé, clôture à ' + sgn(pct(d0723[4], p0723[4]), 1), impact: 'negative', detail: 'Le communiqué est publié le 22 juillet après la clôture, la conférence commençant à 14 h, heure du Pacifique. Le 23, le titre ouvre à ' + usd(d0723[1]) + ', ' + fr(pct(d0723[1], p0723[4]), 2) + ' % au-dessus de la clôture de la veille, ' + usd(p0723[4]) + ', puis clôture à ' + usd(d0723[4]) + ' (' + sgn(pct(d0723[4], p0723[4]), 2) + '). IGV fait ' + sgn(dr('IGV', '2026-07-23'), 2) + ' la même séance : l’écart propre au titre est d’environ ' + fr(Math.abs(pct(d0723[4], p0723[4]) - dr('IGV', '2026-07-23')), 1) + ' point de baisse.', source: 'Barres certifiées', sourceUrl: c.evidenceUrl },
        { date: '2026-08-27', title: 'Hausse de ' + fr(pct(d0827[4], p0827[4]), 1) + ' % avec le logiciel', impact: 'positive', detail: 'Ouverture à ' + usd(d0827[1]) + ' (' + sgn(pct(d0827[1], p0827[4]), 2) + '), clôture à ' + usd(d0827[4]) + '. IGV a pris ' + sgn(dr('IGV', '2026-08-27'), 2) + ', Salesforce ' + sgn(dr('CRM', '2026-08-27'), 2) + ' et Workday ' + sgn(dr('WDAY', '2026-08-27'), 2) + ' la même séance : environ ' + fr(pct(d0827[4], p0827[4]) - dr('IGV', '2026-08-27'), 1) + ' points de la hausse sont propres au titre ; aucun dépôt ouvert ici n’en donne la cause.', source: 'Barres certifiées', sourceUrl: c.evidenceUrl },
        { date: '2026-05-15', title: '4,0 Md$ d’obligations pour refinancer Armis', impact: 'neutral', detail: 'Cinq séries à échéances 2028 à 2056 ; elles remplacent le prêt relais de 4 Md$ du 17 avril. De la dette, aucune action nouvelle.', source: 'ServiceNow — SEC', sourceUrl: docs[4].url }],
      fundamentals: { rows: [
          { metric: 'Abonnements du deuxième trimestre', value: '3 877 M$', signal: '+24,5 % sur un an, communiqué du 22 juillet', signalColor: 'green', _src: 1 },
          { metric: 'Obligations de performance à douze mois', value: '13,20 Md$', signal: '+21 % sur un an', signalColor: 'green', _src: 1 },
          { metric: 'Prévision d’abonnements 2026', value: '15 760 à 15 780 M$', signal: 'Relevée ; troisième trimestre attendu entre 3 975 et 3 980 M$ (+20,5 %)', signalColor: 'blue', _src: 1 },
          { metric: 'Résultat opérationnel GAAP du trimestre', value: '162 M$', signal: '4 % des revenus, contre 11 % un an plus tôt', signalColor: 'red', _src: 1 },
          { metric: 'Revenus GAAP sur douze mois', value: fr(G$.rev / 1e9, 2) + ' Md$', signal: 'Douze mois glissants au 30 juin 2026 (XBRL SEC)', signalColor: 'blue', _src: 'gaap' },
          { metric: 'Résultat opérationnel GAAP sur douze mois', value: fr(G$.ebit / 1e9, 2) + ' Md$', signal: 'Marge de ' + fr(G$.ebit / G$.rev * 100, 1) + ' %, douze mois glissants au 30 juin 2026', signalColor: 'amber', _src: 'gaap' },
          { metric: 'Résultat net GAAP sur douze mois', value: fr(G$.ni / 1e9, 2) + ' Md$', signal: 'Dont 360 M$ de plus-values latentes sur participations au premier semestre 2026, hors exploitation ; celles du second semestre 2025, comprises dans les douze mois, ne sont pas isolées ici', signalColor: 'amber', _src: 'gaap', _also: [0] },
          { metric: 'Flux de trésorerie opérationnel sur douze mois', value: fr(G$.ocf / 1e9, 2) + ' Md$', signal: 'Douze mois glissants au 30 juin 2026', signalColor: 'green', _src: 'gaap' },
          { metric: 'Dette au 30 juin 2026', value: fr(G$.debt / 1e9, 2) + ' Md$', signal: 'Obligations et billets de trésorerie, dont 2,08 Md$ à court terme ; 1,49 Md$ en décembre', signalColor: 'amber', _src: 'gaap' },
          { metric: 'Liquidités et titres négociables au 30 juin 2026', value: fr(G$.cash / 1e9, 2) + ' Md$', signal: 'Hors 2,07 Md$ de participations stratégiques, non comptées', signalColor: 'blue', _src: 'gaap', _also: [0] },
          { metric: 'EV/revenus GAAP', value: fr(evRev, 1) + '×', signal: 'Valeur d’entreprise au close du 2026-09-23, 1 033,9 millions d’actions, sur revenus GAAP douze mois au 2026-06-30', signalColor: 'amber', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus Salesforce à ' + crm + ', Oracle à ' + orcl + ' et Datadog à ' + ddog + ' (fiches publiées, même base et même date), Workday à ' + fr(wday, 1) + '× et Adobe à ' + fr(adbe, 1) + '× (statistiques courantes du 24 septembre, non point-in-time) : ServiceNow garde une prime nette sur les éditeurs d’applications.', _src: 'market', _peers: ['WDAY', 'ADBE'], _peerField: 'enterpriseToRevenue', _peerFiches: ['CRM', 'ORCL', 'DDOG'] },
          { metric: 'EV/EBITDA GAAP', value: fr(evEbitda, 1) + '×', signal: 'Valeur d’entreprise au close du 2026-09-23 sur EBITDA GAAP douze mois au 2026-06-30 (résultat opérationnel + amortissements)', signalColor: 'red', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus Salesforce à ' + crmEb + ' (fiche publiée, même base et même date) : l’écart vient en partie d’une marge GAAP comprimée par les rachats de 2026.', _src: 'market', _peerFiches: ['CRM'] },
          { metric: 'EV sur abonnements prévus pour 2026', value: fr(evFwd, 1) + '×', signal: 'Valeur d’entreprise au close du 2026-09-23 sur le milieu de la prévision d’abonnements de la société (15,77 Md$)', signalColor: 'amber', source: 'Clôture certifiée, XBRL SEC et communiqué du 22 juillet', comparison: 'Versus le multiple glissant : la prévision tenue ramène le multiple d’environ un point, sans le rapprocher de Salesforce.', _src: 'market', _also: [1] },
          { metric: 'P/E GAAP hors plus-values sur participations', value: fr(marketCap / niX, 0) + '×', signal: 'Capitalisation au 2026-09-23 sur résultat net GAAP douze mois au 2026-06-30, moins les 360 M$ de plus-values latentes du premier semestre 2026 seulement, nettes d’un impôt au taux fédéral de 21 % : le 10-Q ne publie pas l’impôt attaché à ces gains, à la différence de HPE qui publie celui du gain H3C', signalColor: 'red', source: 'Clôture certifiée, XBRL SEC et 10-Q', comparison: 'Versus le P/E brut de ' + fr(marketCap / G$.ni, 0) + '× : les gains du premier semestre flattent le résultat douze mois de près de ' + fr((1 - niX / G$.ni) * 100, 0) + ' % ; ceux du second semestre 2025, non isolés, rendraient la correction plus forte.', _src: 'market', _also: [0] },
          { metric: 'EV/revenus — scénario de compression (hypothèse éditoriale)', value: fr(scn.price, 2) + ' $ par action', signal: 'Scénario : multiple ramené à sept fois les revenus GAAP douze mois au 2026-06-30 par hypothèse, bilan du 30 juin, soit ' + fr(scn.downside_pct, 0) + ' % sous le close du 2026-09-23', signalColor: 'red', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus Oracle à ' + orcl + ' et Salesforce à ' + crm + ' (fiches publiées) : sept fois se situe entre les deux ; ce que coûterait l’alignement, pas un objectif.', _src: 'market', _peerFiches: ['ORCL', 'CRM'] }],
        sourceRefs: [ref(0), ref(1), market('fondamentaux et statistiques')] },
      earnings: { quarters: [],
        beatNote: 'Deuxième trimestre 2026 : abonnements de 3 877 M$ (+24,5 %), revenus totaux de 3 987 M$ (+24 %), résultat opérationnel GAAP de 162 M$ et ajusté de 29,5 %, flux libre de 634 M$. La guidance d’abonnements 2026 est relevée à 15 760–15 780 M$ (+22,5 %), pour une marge opérationnelle ajustée de 31,5 % et une marge de flux libre de 35 % ; le troisième trimestre vise 3 975 à 3 980 M$, soit +20,5 %, sur 1,05 milliard d’actions diluées. La date du troisième trimestre, non annoncée par l’émetteur dans les dépôts ouverts, est placée au 28 octobre par le calendrier de marché.',
        nextEarnings: 'Date non annoncée par l’émetteur ; le calendrier de marché indique le 28 octobre.',
        sourceRefs: [ref(1)] },
      capitalStructure: { sharesOutstanding: '1 033 862 000 actions au 30 juin 2026 (bilan du 10-Q, en milliers : 1 033 862)',
        sharesAuthorized: 'Actions autorisées non reprises : non décisionnel pour ce dossier.', dilutionRisk: 'low',
        shareHistory: 'Base retenue : actions en circulation, après le fractionnement par cinq du 17 décembre 2025. Elles passent de 1 047,3 millions au 31 décembre 2025 à 1 033,9 millions au 30 juin 2026, soit 1,3 % de moins, après 20,2 millions d’actions rachetées au semestre pour 2,23 Md$. Passage au nombre dilué : la guidance du troisième trimestre retient 1,05 milliard d’actions diluées, les attributions salariales ajoutant environ 1,5 %. Armis et Veza ont été payés en numéraire : aucune action nouvelle. Les S-8 de l’année enregistrent les plans d’actions repris lors des rachats : réserves de rémunération, pas des levées de fonds. La dette atteint 7,52 Md$ au 30 juin : 5,44 Md$ d’obligations, dont 4,0 Md$ émises en mai, et 2,08 Md$ de dette à court terme, essentiellement des billets de trésorerie.',
        warrants: [], atm: { active: false, authorized: 'Aucun programme d’émission d’actions sur le marché relevé', used: 'Sans objet', remaining: 'Sans objet' },
        sourceRefs: [ref(0), ref(3), ref(4)] },
      filingsReview: { summary: 'Cinq dépôts décisionnels ouverts et hachés. Ils décrivent une croissance organique encore forte, mais un bilan transformé par Armis : 7,6 Md$ payés en numéraire, une dette quintuplée et une marge GAAP écrasée par l’amortissement des actifs acquis. Aucune dilution : les rachats d’actions continuent.',
        filings: docs.map(d => ({ date: d.date, form: d.form, accession: d.accession, finding: d.finding, url: d.url })),
        contrarianRisks: [
          'La contribution d’Armis aux revenus n’est pas isolée dans les documents ouverts : la croissance interne réelle reste inconnue.',
          'La guidance du troisième trimestre à +20,5 % prolonge le ralentissement, alors qu’Armis ajoute déjà des revenus.',
          '2,08 Md$ de dette à court terme devront être refinancés ; le coût dépendra des taux.',
          'La marge brute des abonnements a perdu sept points en un an : si elle ne remonte pas, la prime sur Salesforce se justifie moins.'] },
      technicals: { rsi14: +tech.rsi14.toFixed(2), macd: +tech.macd.toFixed(2), macdSignal: +tech.macdSignal.toFixed(2), ema20: +tech.ema20.toFixed(2), ema50: +tech.ema50.toFixed(2), ema200: +tech.ema200.toFixed(2),
        ma50Type: 'EMA', ma200Type: 'EMA', ma50Available: true, ma200Available: true, atr14: +tech.atr14.toFixed(2),
        badges: ['Couloir de ' + usd(lv('s3')) + ' à ' + usd(lv('r2')), 'MACD sous sa ligne de signal', 'Au-dessus des moyennes à vingt, cinquante et deux cents séances'],
        supports: [lv('s1'), lv('s2'), lv('s3')], resistances: [lv('r1'), lv('r2'), lv('r3')],
        setupNote: 'Le titre clôture à ' + usd(close) + ', au milieu du couloir ouvert depuis le 31 août entre ' + usd(lv('s3')) + ', plus bas du 11 septembre, et ' + usd(lv('r2')) + ', plus haut du 31 août, avec un RSI à ' + fr(tech.rsi14, 1) + ' et un MACD repassé sous sa ligne de signal. Supports : ' + usd(lv('s1')) + ', bas du 23 septembre, ' + usd(lv('s2')) + ', bas du 18, et ' + usd(lv('s3')) + '. Résistances : ' + usd(lv('r1')) + ', plus haut du 15 septembre, ' + usd(lv('r2')) + ', puis ' + usd(lv('r3')) + ', plus haut du 2 janvier. Un achat sur clôture au-dessus de ' + usd(bo.e) + ' avec un stop sous ' + usd(bo.s) + ' risquerait ' + usd(bo.e - bo.s) + ', soit ' + fr((bo.e - bo.s) / tech.atr14, 2) + ' ATR, pour viser ' + usd(bo.t) + ' : R/R de ' + fr(bo.rr, 2) + ', très loin du minimum de 1,5. Au-dessus de ' + usd(bo.t) + ', les repères de décembre 2025 sont trop éloignés pour servir d’objectif sur dix séances.',
        wyckoff: 'Non utilisé : le profil de volume n’est pas exploité dans ce dossier.',
        sourceRefs: [market('barres quotidiennes et indicateurs recalculés')] },
      options: { callOI: 'Non exploitable', putOI: 'Non exploitable', cpRatio: 'Non exploitable', maxPain: 'Non exploitable', ivMean: 'Non exploitable', skew: 'Chaîne relevée en séance le 24 septembre, non rattachée à la clôture de référence', unusual: 'Aucune activité inhabituelle qualifiée', sourceRefs: [market('options')] },
      shortInterest: { siPct: fr(st.shortPercentOfFloat * 100, 2) + ' % du flottant', daysToCover: fr(st.shortRatio, 2) + ' jours, date de règlement non précisée par le snapshot', ctb: 'Coût d’emprunt non retenu comme signal', trend: 'Positions vendeuses faibles ; aucune thèse de rachat forcé des vendeurs.', squeezeScore: 'Non pertinent', sourceRefs: [market('positions vendeuses')] },
      insiders: { signal: 'Trois ventes de dirigeants fin août, entre 135 et 148 $ : Jacqueline Canney, directrice des ressources humaines et de l’IA, environ 7 800 actions le 28 août ; l’administrateur Paul Chamberlain, 2 700 actions le 27 ; Paul Fipps, président des opérations clients, environ 2 000 actions le 31. Montants faibles au regard de la capitalisation. Aucun achat relevé. Couverture officielle partielle.',
        recentTransactions: [],
        sourceRefs: [market('formulaires 4')] },
      macro: { indicators: [{ name: 'Clôture de référence', value: c.REF, signal: usd(close) + ', séance complète' }, { name: 'Rendement cinq séances', value: sgn(ret(5)), signal: 'Descriptif' }, { name: 'Rendement vingt et une séances', value: sgn(ret(21)), signal: 'Descriptif' }],
        regime: 'neutral', impact: 'ServiceNow dépend des budgets informatiques des grandes entreprises et des administrations, relativement stables. Avec 7,5 Md$ de dette, dont une partie à court terme, la société est désormais plus sensible au niveau des taux qu’avant Armis.' },
      risks: { riskScore: 5, riskProfile: 'Moderate',
        riskSummary: 'Le risque de ServiceNow n’est pas la demande : les abonnements croissent encore de plus de 20 %. Il tient au prix payé pour Armis, 7,6 Md$ en numéraire, qui a fait passer la dette de 1,5 à 7,5 Md$ et la marge GAAP à 4 % au trimestre, et à une croissance qui ralentit malgré ce rachat. Le titre, lui, n’offre pas de point d’entrée : il est au milieu d’un couloir de vingt dollars.',
        riskCards: [
          { title: 'Rachat d’Armis financé par la dette', severity: 'medium', icon: 'fa-money-bill-trend-up', points: ['7,6 Md$ en numéraire, 4,0 Md$ d’obligations émises en mai.', 'Dette de 7,5 Md$ au 30 juin, dont 2,08 Md$ à court terme.'], verdict: 'Le bilan reste solide, mais la marge de manœuvre pour d’autres rachats a fondu.' },
          { title: 'Croissance qui ralentit', severity: 'medium', icon: 'fa-chart-line', points: ['Abonnements +24,5 % au deuxième trimestre, +20,5 % guidés au troisième.', 'Contribution d’Armis non isolée.'], verdict: 'Si la croissance interne tombe sous 20 %, la prime sur Salesforce deviendra difficile à défendre.' },
          { title: 'Marge GAAP comprimée', severity: 'medium', icon: 'fa-scale-unbalanced', points: ['Résultat opérationnel GAAP de 162 M$, 4 % des revenus.', 'Amortissement des actifs acquis de 219 M$ au trimestre, contre 25 M$.'], verdict: 'Cet amortissement pèsera plusieurs années sur les comptes GAAP, même si l’activité tient.' },
          { title: 'Pas de point d’entrée', severity: 'low', icon: 'fa-door-closed', points: ['Clôture au milieu du couloir 130–150 $.', 'R/R de ' + fr(bo.rr, 2) + ' sur une cassure du 31 août.'], verdict: 'Attendre que le titre sorte du couloir plutôt que d’acheter au milieu.' }],
        pedagogy: 'Un couloir, c’est une zone où acheteurs et vendeurs se neutralisent : acheter au milieu, c’est prendre le risque des deux bords sans l’avantage d’aucun. Le R/R, rapport entre le gain visé et la perte acceptée, ne devient intéressant qu’aux bornes. Le gap du 23 juillet rappelle aussi qu’une ouverture en hausse après un bon trimestre peut se retourner dans la séance : le slippage, l’écart entre prix voulu et prix obtenu, compte moins que ce retournement. Quand un plan reviendra, la taille de la position se calculera sur la distance au stop et un budget de perte fixé d’avance ; la publication de fin octobre, datée par le calendrier de marché, reste un risque de gap à ne pas porter sans l’avoir réduit.' },
      tradeIdea: { status: 'no-trade', archiveReferenceClose: archive.meta.levelsCloseDate,
        statusNote: 'Aucun plan. Les niveaux affichés sont ceux, archivés, du dossier du 27 août ; aucun ordre n’y est plus attaché. ' + archNote + ' Un nouveau plan ne sera construit que sur une clôture au-dessus de ' + usd(lv('r2')) + ' avec une base plus serrée, ou sur un retour tenu vers ' + usd(lv('s3')) + '.',
        entry, stop, tp1, tp2,
        stopPct: pct(stop, entry).toFixed(1) + '%', tp1Pct: '+' + pct(tp1, entry).toFixed(1) + '%', tp2Pct: '+' + pct(tp2, entry).toFixed(1) + '%',
        rr: '1:' + rr1.toFixed(2) + ' TP1 / 1:' + rr2.toFixed(2) + ' TP2',
        entryNote: 'Niveaux historiques affichés pour mémoire, non exécutables : plan du 27 août très probablement activé le ' + dfr(cA[0]) + ', horizon échu le ' + dfr(hz[0]) + ' à ' + sgn(pct(hz[4], A.entry), 1) + ', stop et TP1 non touchés. Un achat sur clôture au-dessus du plus haut du 31 août, ' + usd(bo.e) + ', avec un stop sous le bas du 18 septembre, ' + usd(bo.s) + ', risquerait ' + usd(bo.e - bo.s) + ' pour viser le plus haut du 2 janvier, ' + usd(bo.t) + ' : R/R de ' + fr(bo.rr, 2) + '. Liquidité : environ ' + fr(adv / 1e9, 1) + ' Md$ échangés par séance, médiane des vingt dernières.',
        horizon: 'Aucun horizon : pas de plan au cours actuel',
        thesis: 'Le marché a d’abord vendu le trimestre, puis racheté tout le logiciel en août. ServiceNow reste une plateforme de premier plan, mais sa croissance ralentit, sa marge GAAP a fondu avec Armis et le titre n’offre pas de point d’entrée. Aucun ordre : attendre une sortie du couloir, dans un sens ou dans l’autre, puis reconstruire des niveaux.',
        catalysts: ['Une clôture au-dessus de ' + usd(lv('r2')) + ' après une base plus étroite, qui donnerait un stop plus proche.', 'Un retour tenu vers ' + usd(lv('s3')) + ', bas du couloir.', 'La publication d’Accenture le 1er octobre, date donnée par deux calendriers concordants, pour la demande de services autour des plateformes.'],
        invalidation: ['Toute entrée au cours actuel contredit ce dossier.', 'Une clôture sous ' + usd(lv('s3')) + ' ouvrirait un retour vers le gap de juillet et repousserait tout plan.', 'Un nouveau rachat financé par la dette changerait la lecture du bilan.'] },
      globalScore: { profile: 'Plateforme de qualité, bilan alourdi, titre sans entrée',
        keyTakeawaysPositive: ['Abonnements +24,5 %, prévision relevée.', '13,20 Md$ de contrats à douze mois.', 'Rachats d’actions, aucune dilution.'],
        keyTakeawaysNegative: ['Dette passée de 1,5 à 7,5 Md$.', 'Marge GAAP de 4 % au trimestre.', 'Titre au milieu de son couloir.'],
        mindsetTip: 'Une bonne société au mauvais prix d’entrée reste un mauvais trade. Le couloir finira par se casser : c’est à ce moment-là qu’un plan aura un stop proche et un objectif lisible.' },
      social: { platforms: [], sourceRefs: [market('sentiment non retenu faute de mesure qualifiée')] },
      disclaimer: 'Document de recherche éducatif. Ni conseil financier, ni signal de trading. Aucun plan actif : aucun ordre attaché aux niveaux archivés.',
    };
  },
  groups: [
    { name: 'Référence des applications d’entreprise', order: 1, transmission: 'Le concurrent coté qui co-évolue le plus avec ServiceNow depuis fin mars, cité par le 10-K.', rows: [
      ['CRM', 'leader', 'Plateforme de gestion de la relation client', 'Corrélation la plus forte avec ServiceNow depuis fin mars ; ses prévisions donnent le ton des budgets d’applications.']] },
    { name: 'Pairs directs cités par le 10-K', order: 1, transmission: 'Mêmes budgets d’applications d’entreprise : gains de part et prix se lisent directement.', rows: [
      ['SAP', 'direct_peer', 'Progiciel de gestion intégré', 'Concurrent cité par le 10-K sur les processus d’entreprise.'],
      ['WDAY', 'direct_peer', 'Ressources humaines et finance en nuage', 'Concurrent cité par le 10-K sur les processus des ressources humaines.'],
      ['MSFT', 'direct_peer', 'Suite logicielle et agents d’IA', 'Concurrent cité par le 10-K, partenaire sur la gouvernance des agents ; ses offres groupées pèsent sur les prix.'],
      ['ORCL', 'direct_peer', 'Applications et base de données', 'Concurrent cité par le 10-K sur les applications d’entreprise.'],
      ['ADBE', 'direct_peer', 'Logiciels de contenu et d’expérience client', 'Éditeur d’applications comparable par la taille ; sert de repère de multiple.']] },
    { name: 'Amont : clouds et calcul', order: 1, transmission: 'La plateforme s’appuie sur les places de marché et les processeurs des grands clouds pour distribuer ses agents d’IA.', rows: [
      ['AMZN', 'upstream', 'Place de marché AWS', 'Plus de 1 Md$ de transactions sur la place de marché AWS selon le communiqué du 22 juillet.'],
      ['GOOGL', 'upstream', 'Cloud et modèles d’IA', 'Fournisseur d’infrastructure et de modèles pour les agents ; concurrent potentiel sur l’automatisation.'],
      ['NVDA', 'upstream', 'Processeurs et logiciels d’IA', 'Partenariat élargi sur la gouvernance des agents selon le communiqué ; son rythme de déploiement fixe la demande d’outils de contrôle.']] },
    { name: 'Aval : intégrateurs', order: 1, transmission: 'Les intégrateurs déploient la plateforme chez les clients : leurs carnets de commandes précèdent les signatures.', rows: [
      ['ACN', 'downstream', 'Intégrateur et partenaire commercial', 'Offre commune de migration de la cybersécurité selon le communiqué du 22 juillet ; publie le 1er octobre.']] },
    { name: 'Second ordre : logiciels et sécurité voisins', order: 2, transmission: 'Budgets voisins des mêmes directions informatiques et de sécurité.', rows: [
      ['TEAM', 'second_order', 'Outils des équipes informatiques', 'Concurrent sur la gestion des services informatiques des entreprises moyennes.'],
      ['HUBS', 'second_order', 'Logiciel de relation client', 'Même cycle de budgets d’applications ; forte corrélation depuis fin mars.'],
      ['DDOG', 'second_order', 'Observabilité des infrastructures cloud', 'Ses alertes alimentent la gestion des incidents ; budget des mêmes équipes.'],
      ['MDB', 'second_order', 'Base de données en nuage', 'Budget voisin des mêmes développeurs d’applications, sensible aux mêmes arbitrages de dépenses.'],
      ['PANW', 'second_order', 'Plateforme de sécurité', 'Concurrent de la nouvelle offre de sécurité issue d’Armis.'],
      ['CRWD', 'second_order', 'Sécurité en nuage', 'Concurrent sur la sécurité des actifs et des identités.']] },
    { name: 'Contrôles sectoriels', order: 2, transmission: 'Paniers de référence pour isoler ce qui est propre à ServiceNow.', rows: [
      ['IGV', 'sector_proxy', 'Panier de logiciels américains', 'ServiceNow y pèse lourd : un écart avec ce panier isole ce qui est propre au titre.'],
      ['QQQ', 'sector_proxy', 'Grandes valeurs du Nasdaq', 'Contrôle large de la technologie : un mouvement commun avec ce panier n’a rien de spécifique au titre.']] },
  ],
  eventDefault: { leader: 'Aucune publication dans les quatorze jours collectés ; sa prochaine prévision donnera le ton des applications', direct_peer: 'Aucune publication dans les quatorze jours collectés ; ses annonces de prix ou de produits peuvent déplacer les parts de marché', upstream: 'Aucune publication dans les quatorze jours collectés ; ses investissements en IA restent le signal à suivre', downstream: 'Publication le 1er octobre, date donnée par deux calendriers concordants, avant l’ouverture selon l’un d’eux, non confirmée ici par l’émetteur : risque de gap sectoriel sur les services', second_order: 'Aucune publication dans les quatorze jours collectés ; ses prévisions éclairent les budgets voisins', sector_proxy: 'Panier sans publication propre ; exposé aux résultats de ses grandes pondérations' },
  eventRisk: {},
  blastDoc: 2,
  scenarios: c => [
    { scenario: 'bullish', trigger: 'Le logiciel reprend sa hausse et Accenture confirme la demande de projets autour des plateformes.', firstOrder: 'Le titre sort du couloir par le haut, au-dessus du plus haut du 31 août.', secondOrder: 'Salesforce et Workday suivent ; IGV confirme.', confirmation: 'Une clôture au-dessus de ' + c.usd(c.lv('r2')) + ' avec IGV en hausse.', contradiction: 'Une sortie par le haut pendant qu’IGV recule.' },
    { scenario: 'mixed', trigger: 'Pas de nouvelle propre avant la publication de fin octobre.', firstOrder: 'Le titre oscille entre ' + c.usd(c.lv('s3')) + ' et ' + c.usd(c.lv('r2')) + '.', secondOrder: 'L’écart avec IGV reste faible, sans information propre au titre.', confirmation: 'Des clôtures dans le couloir pendant plusieurs séances.', contradiction: 'Une sortie franche d’un côté ou de l’autre.' },
    { scenario: 'bearish', trigger: 'Accenture déçoit sur les projets, ou rotation hors du logiciel.', firstOrder: 'Le titre casse le bas du 11 septembre.', secondOrder: 'Les éditeurs d’applications les plus chers reculent davantage.', confirmation: 'Une clôture sous ' + c.usd(c.lv('s3')) + ' avec IGV en baisse.', contradiction: 'Un repli du secteur que le titre ne suit pas.' }],
  contradictions: c => ['La prévision est relevée, mais la croissance guidée du troisième trimestre ralentit alors qu’Armis ajoute déjà des revenus : les deux lectures coexistent.', 'Une corrélation élevée avec Salesforce ne prouve pas un lien commercial ; le partenaire fédéral à 11 % des revenus n’est pas nommé.'],
  missingData: c => ['Le partenaire fédéral à 11 % des revenus de 2025 n’est pas nommé : aucun client coté n’entre dans les comparables comme client documenté.', 'Contribution d’Armis et de Veza aux revenus non isolée dans les documents ouverts.', 'Chaîne d’options relevée en séance, non rattachée à la clôture ; sentiment non retenu.', 'Barres d’une source de repli pour toutes les séries.'],
  limitations: ['Barres d’une source de repli (Webull).', 'Options non rattachées à la clôture de référence.', 'Croissance interne hors rachats non isolée.'],
});
