'use strict';
// Dossier Reddit (RDDT) v3 au close du 2026-09-25. Refonte complète de la v2 anglaise du 14 février 2026
// (fiche « info », plan entrée 0). Contenu éditorial et repères propres au titre ; calculs, provenance et
// preuves délégués au gabarit tools/lib/analysis-v3-r07.cjs (REF=2026-09-25, run 20260927).
// Agrégats GAAP lus dans les données XBRL officielles de la SEC (companyfacts, 10-Q du 30 juin inclus) :
// exercice = année civile ; douze mois glissants au 2026-06-30 = exercice clos le 31 décembre 2025 (10-K)
// + semestre clos le 30 juin 2026 (10-Q) − semestre clos le 30 juin 2025. Aucune dette financière : les clés
// dette sont vides. Trésorerie = liquidités + titres de placement courants au 30 juin. Actions = Class A
// (146 103 200) + Class B (46 293 310) au 29 juillet (page de garde du 10-Q), la Class B portant dix voix.
// Valorisation par les revenus : société à très forte marge, l'EV/revenus gouverne. Aucun bon de
// souscription, aucun programme d'émission sur le marché ; la seule dilution est la rémunération en actions,
// partiellement compensée par un programme de rachat de 1,0 Md$ autorisé le 4 février 2026.
const R = require('../../../../tools/lib/analysis-v3-r07.cjs');
const GEN = 'analyses/RDDT/_runs/20260927/build-rddt.cjs';
const SHARES = 146103200 + 46293310; // 192 396 510 : Class A + Class B au 29 juillet, poids économique identique

R.build({
  ticker: 'RDDT', shortName: 'Reddit', cik: 1713445, generator: GEN,
  xbrl: {
    ttm: {
      rev: ['RevenueFromContractWithCustomerExcludingAssessedTax'],
      ebit: ['OperatingIncomeLoss'],
      ni: ['NetIncomeLoss'],
      ocf: ['NetCashProvidedByUsedInOperatingActivities'],
      capex: ['PaymentsToAcquirePropertyPlantAndEquipment'],
    },
    instant: {
      cashEq: ['CashAndCashEquivalentsAtCarryingValue'],
      sti: ['AvailableForSaleSecuritiesDebtSecuritiesCurrent'],
    },
    da: [], debt: [], cash: ['cashEq', 'sti'],
  },
  scenarioBasis: 'revenue', scenarioMultiple: 6,
  valuationBasis: 'GAAP douze mois au 2026-06-30 (XBRL SEC) : revenus = exercice clos le 31 décembre 2025 (10-K) + semestre clos le 30 juin 2026 (10-Q) − semestre clos le 30 juin 2025. Capitalisation = clôture certifiée du 2026-09-25 × 192 396 510 actions (Class A et Class B au 29 juillet). Valeur d’entreprise = capitalisation − trésorerie (liquidités + placements courants au 30 juin) ; aucune dette financière. Valorisation par les revenus : marge brute de 91 %, l’EV/revenus gouverne. Scénario : multiple d’EV/revenus ramené à six fois les revenus GAAP douze mois, trésorerie du 30 juin inchangée ; ce que coûterait un retour au niveau des grandes plateformes publicitaires si la croissance décélérait, pas un objectif.',
  shares: { value: SHARES, doc: 1 },
  // Repères courants (barres certifiées, par date). Plan de repli tactique dans le couloir post-résultats :
  // entrée sur repli vers le support triple-testé, stop sous le plancher de la base, objectifs au haut du couloir.
  levels: {
    trigger: { d: '2026-09-09', c: 3 },  // 145,166 — support récent, haut de la zone triple-testée
    stop: { d: '2026-08-03', c: 3 },      // 140,05 — plancher de la base post-résultats
    abandon: { d: '2026-08-03', c: 3 },   // 140,05 — clôture en dessous = scénario abandonné
    r1: { d: '2026-09-21', c: 2 },        // 160,35 — plus haut du 21 septembre, mi-haut du couloir (TP1)
    r2: { d: '2026-09-14', c: 2 },        // 166,18 — plus haut du 14 septembre, haut du couloir (TP2)
    s1: { d: '2026-09-09', c: 3 },        // 145,166 — support triple-testé (20/08, 01/09, 02/09, 09/09)
    s2: { d: '2026-08-03', c: 3 },        // 140,05 — plancher de la base
    s3: { d: '2026-07-31', c: 3 },        // 135,222 — plus bas du gap de résultats
  },
  targets: ({ lv }) => ({ tp1: lv('r1'), tp2: lv('r2') }),
  supports: ['s1', 's2', 's3'], resistances: ['r1', 'r2'],
  levelsMethod: 'Repères lus sur les barres certifiées, par date. Entrée sur repli vers le support triple-testé du couloir de septembre (145 $), stop sous le plancher de la base post-résultats (140 $), objectifs au mi-haut (160 $) et au haut (166 $) du couloir. R/R = gain / risque. Plan de repli tactique dans le couloir, non un signal de retournement de tendance : le titre reste sous ses moyennes.',
  inventory: 18,
  reviewScope: 'Dépôts EDGAR de Reddit du 25 septembre 2025 au 25 septembre 2026, déclarations de détention (formulaires 3, 4, 5) exclues. Dix-huit dépôts inventoriés ; quatre ouverts et hachés : communiqué du deuxième trimestre 2026 (8-K, Exhibit 99.1), 10-Q du trimestre clos le 30 juin, 10-K de l’exercice clos le 31 décembre 2025 et communiqué du quatrième trimestre 2025 annonçant le programme de rachat (8-K, Exhibit 99.1). La procuration (DEF 14A), les 8-K de gouvernance (item 5.02), le S-8 des plans salariés et les 13G des gestionnaires passifs sont écartés comme non décisionnels ; aucun S-1, S-3, 424B, bon de souscription, obligation convertible ni programme d’émission sur le marché n’apparaît dans la période.',
  docs: [
    ['2026-07-30', '8-K / Exhibit 99.1', '0001713445-26-000098', 'earningspressreleaseq226.htm', 'q2-8k-ex991__earningspressreleaseq226.htm',
      'Communiqué du deuxième trimestre 2026 (clos le 30 juin) : revenus de 805 M$ (+61 %), huitième trimestre consécutif au-dessus de 60 % ; revenus publicitaires de 762 M$ (+64 %), autres revenus de 43 M$ (+24 %) ; marge brute de 91,3 % ; résultat net de 253 M$ (31 % des revenus), bénéfice dilué par action de 1,25 $ ; EBITDA ajusté (non-GAAP) de 343 M$ ; flux de trésorerie libre de 261 M$ ; utilisateurs actifs quotidiens (DAUq) de 130,3 millions (+18 %), hebdomadaires (WAUq) de 514,6 millions (+24 %) ; rachat de 1,5 million d’actions Class A pour 235 M$ dans le trimestre. Prévision du troisième trimestre : revenus de 860 à 870 M$, EBITDA ajusté de 385 à 395 M$.'],
    ['2026-07-31', '10-Q', '0001713445-26-000100', 'rddt-20260630.htm', 'q2-10q__rddt-20260630.htm',
      'Rapport trimestriel au 30 juin 2026 : 146 103 200 actions Class A et 46 293 310 actions Class B au 29 juillet ; aucune dette financière ; 1 486,8 M$ de liquidités et 1 299,5 M$ de titres de placement courants ; capitaux propres de 3 285,7 M$. Programme de rachat d’actions autorisé le 4 février 2026 pour un montant maximal de 1,0 Md$ de Class A, sans échéance ; 1 523 502 actions rachetées sur le semestre.'],
    ['2026-02-06', '10-K', '0001713445-26-000022', 'rddt-20251231.htm', 'fy25-10k__rddt-20251231.htm',
      'Rapport annuel de l’exercice clos le 31 décembre 2025 : structure à trois classes, la Class B portant dix voix par action (contrôle des fondateurs), la Class C sans droit de vote et aucune émise ; les autres revenus proviennent de la licence de contenu et de produits vendus aux utilisateurs ; Google, les grands moteurs et les modèles de langage cités comme sources de trafic et concurrents pour l’attention.'],
    ['2026-02-05', '8-K / Exhibit 99.1', '0001713445-26-000020', 'earningspressreleaseq425.htm', 'feb05-8k-ex991__earningspressreleaseq425.htm',
      'Communiqué du quatrième trimestre et de l’exercice 2025 annonçant un programme de rachat d’actions de 1,0 Md$ : revenus 2025 de 2,2 Md$ (+69 %), résultat net de 530 M$ (24 % des revenus) ; quatrième trimestre à 726 M$ (+70 %) et DAUq de 121,4 millions (+19 %).'],
  ],
  needles: {
    results: [0, ['Revenue of $805 million grew 61%', 'increased 18% year-over-year to 130.3 million', '514.6 million', 'Net income of $253 million', 'Diluted EPS of $1.25', 'Adj. EBITDA 1 of $343 million', 'Free Cash Flow 1 was $261 million', 'We repurchased 1.5 million shares of our Class A common stock', 'Total fully diluted shares outstanding were 207.0 million']],
    guidance: [0, ['$860 million to $870 million', '$385 million to $395 million']],
    balance: [1, ['146,103,200 shares of Class A common stock, 46,293,310 shares of Class B common stock', '1,486,838', '1,299,519']],
    buyback_note: [1, ['Share Repurchase Program', 'purchase up to $ 1.0 billion of our Class A common stock']],
    annual: [2, ['Class B common stock', 'ten votes', 'Other revenue consists of revenue from content licensing']],
    buyback_ann: [3, ['Announces $1 Billion Share Repurchase Program', '2025 Revenue grew 69%']],
  },
  sectionDocs: { verdict: [0, 1], business: [2, 0], news: [0], earnings: [0], fundamentals: [0, 1], capitalStructure: [1, 3], filingsReview: [0, 1, 2], risks: [2, 1], globalScore: [0], meta: [0], disclaimer: [0], macro: [2], options: [0], social: [2], header: [0], shortInterest: [1], insiders: [1] },
  score: { business: 30, technical: -6, capital: 6, calendar: 0, dilution: -3, risk: 25 },
  peers: true,
  riskScoreReason: 'Jugement qualitatif sur dix : entreprise de très haute qualité — croissance de 61 %, marge brute de 91 %, résultat net et flux de trésorerie libre positifs, bilan sans dette et 2,8 Md$ de trésorerie, rachat d’actions actif — mais bêta supérieur à deux, valorisation au-dessus des grandes plateformes publicitaires, décélération des utilisateurs quotidiens et risque structurel de désintermédiation par la recherche assistée par IA, dont Reddit dépend pour une part de son trafic. Le risque n’est pas le bilan, c’est le prix et la dépendance au trafic externe.',
  compose: c => {
    const { fr, usd, pct, sgn, close, prev, bars, N, tech, st, M, adv, ret, G$, marketCap, ev, scn, entry, stop, tp1, tp2, cap, rr1, rr2, riskAtr, sizeExample, ref, market, docs, raw, peerStat, lv } = c;
    const bar = d => bars.find(b => b[0] === d), prevOf = d => bars[bars.findIndex(b => b[0] === d) - 1];
    const dol = n => n.toFixed(2) + ' $'; // niveau précis en décimale à point, cité pour la traçabilité du plan
    const cmp = raw.comparison_bars.data.items[0].results[0].data;
    const dr = (sym, d) => { const b = cmp.find(x => x.symbol === sym).bars, i = b.findIndex(x => x[0] === d); return pct(b[i][4], b[i - 1][4]); };
    const d0730 = bar('2026-07-30'), d0731 = bar('2026-07-31'), p0730 = prevOf('2026-07-30');
    const evRev = ev / G$.rev, pe = marketCap / G$.ni, evFcf = ev / G$.fcf, opMargin = G$.ebit / G$.rev * 100;
    const metaRev = peerStat('META', 'enterpriseToRevenue'), googlRev = peerStat('GOOGL', 'enterpriseToRevenue'), pinsRev = peerStat('PINS', 'enterpriseToRevenue'), rblxRev = peerStat('RBLX', 'enterpriseToRevenue'), appRev = peerStat('APP', 'enterpriseToRevenue'), nflxRev = peerStat('NFLX', 'enterpriseToRevenue');
    return {
      meta: { lang: 'fr', dir: 'ltr', level: 'intermediate', tags: ['us', 'equities', 'comms', 'ai', 'technology'], grade: 'B', date: '2026-09-27', dateDisplay: '27 septembre 2026', version: 3, status: 'watch', assetType: 'stock', levelsCloseDate: c.REF,
        description: 'Reddit : +61 % de revenus et 91 % de marge brute, mais un titre cassé depuis juillet et une dépendance au trafic de recherche que l’IA menace. Dossier au close du 25 septembre 2026, statut surveiller, aucune entrée au cours actuel.',
        ogDescription: 'Reddit : revenus +61 %, marge 91 %, flux libre positif, sans dette ; mais titre sous ses moyennes, valorisation au-dessus des géants publicitaires, risque IA. Surveiller, pas d’entrée.',
        lastMcpRefresh: raw.status.captured_at, levelsVerifiedAt: raw.status.captured_at,
        statusHistory: [...(c.archive.meta.statusHistory || []), { at: raw.status.captured_at, from: 'info', to: 'watch', note: 'refonte v3 du 27 septembre au close du 25 : ancienne fiche « info » du 14 février remplacée ; titre sous ses moyennes à vingt, cinquante et deux cents séances après le repli de −21 % du 31 juillet, plan de repli tactique dans le couloir défini, aucune entrée au cours actuel', close }] },
      header: { ticker: 'RDDT', name: 'Reddit, Inc.', exchange: 'NYSE', sector: 'Médias sociaux et publicité en ligne', price: close, changePct: pct(close, prev),
        badges: [{ text: 'SURVEILLER — AUCUNE ENTRÉE AU COURS ACTUEL', color: 'blue' }, { text: 'Chaîne IA — donnée et attention', color: 'purple' }],
        metrics: { marketCap: fr(marketCap / 1e9, 1) + ' Md$', volume: fr(bars[N][5] / 1e6, 1) + ' M', evRevenue: fr(evRev, 1) + '×' }, halalStatus: 'unknown' },
      verdict: { score: 52, conviction: 'Moderate', bias: 'Neutral',
        confidence: 'Score éditorial non prédictif. Les chiffres d’entreprise viennent des dépôts SEC et des données XBRL officielles ; les niveaux, du close certifié du 25 septembre.',
        summary: 'Reddit est la plateforme de communautés en ligne la plus rentable du web social. Au deuxième trimestre, ses revenus ont bondi de 61 %, à 805 M$, portés par la publicité (+64 %), avec une marge brute de 91 % et un résultat net de 253 M$ ; la société dégage un flux de trésorerie libre positif, n’a aucune dette et rachète ses actions. Rien à redire au dossier d’entreprise. Le problème est double. D’abord le prix : à ' + fr(evRev, 1) + ' fois ses revenus des douze derniers mois, Reddit se paie plus cher que Meta (' + fr(metaRev, 1) + '×) et qu’Alphabet (' + fr(googlRev, 1) + '×) — les géants mêmes de la publicité — et plusieurs fois le multiple des autres réseaux sociaux. Ensuite le trafic : une part importante des visiteurs arrive par la recherche Google, et la montée des réponses générées par IA menace ce robinet. Le trimestre de juillet l’a rappelé : malgré la hausse de 61 % des revenus, la croissance des utilisateurs quotidiens est retombée à 18 %, et le titre a perdu ' + fr(Math.abs(pct(d0731[4], d0730[4])), 0) + ' % en une séance. Depuis, il évolue dans un couloir, sous ses moyennes. À ' + usd(close) + ', il n’y a pas d’entrée : on surveille un repli vers le bas du couloir.',
        whyBuy: [
          'Croissance de 61 % au deuxième trimestre, huitième trimestre consécutif au-dessus de 60 %, avec une marge brute de 91 % : très peu de sociétés cumulent cette croissance et cette rentabilité.',
          'Résultat net de 253 M$, flux de trésorerie libre positif de 261 M$ sur le trimestre : Reddit est rentable en normes comptables, pas seulement en mesures ajustées.',
          'Bilan sans dette, 2,8 Md$ de trésorerie et de placements, et un programme de rachat d’actions de 1,0 Md$ autorisé en février : le capital revient aux actionnaires.',
          'Reddit détient une donnée rare — des conversations humaines structurées par sujet — que les moteurs et les modèles d’IA paient pour entraîner leurs systèmes.'],
        whyAvoid: [
          'À ' + fr(evRev, 1) + ' fois les revenus, Reddit est plus cher que Meta (' + fr(metaRev, 1) + '×) et Alphabet (' + fr(googlRev, 1) + '×), et loin devant Pinterest (' + fr(pinsRev, 1) + '×) ou Roblox (' + fr(rblxRev, 1) + '×) : la moindre déception se paie cher.',
          'La croissance des utilisateurs quotidiens est retombée à 18 %, contre plus de 40 % un an plus tôt : c’est cette décélération, pas les revenus, qui a fait chuter le titre en juillet.',
          'Une part du trafic vient de la recherche Google ; la généralisation des réponses par IA peut réduire les clics vers Reddit, ce qui toucherait à la fois l’audience et les impressions publicitaires.',
          'Le titre est sous ses moyennes à vingt, cinquante et deux cents séances depuis le repli de juillet : la tendance de fond reste baissière.'],
        controlChecklist: [
          { label: 'Historique de cours', status: 'pass', statusLabel: 'Trois cents séances continues', evidence: 'Série quotidienne certifiée au close du 25 septembre.', action: 'Niveaux et moyennes calculés sur cette seule série.' },
          { label: 'Structure du capital', status: 'pass', statusLabel: 'Sans dette, trois classes', evidence: '10-Q du 30 juin : 146 103 200 actions Class A et 46 293 310 Class B, aucune dette ; la Class B porte dix voix par titre selon le 10-K.', action: 'Raisonner sur 192 millions d’actions ; contrôle concentré chez les fondateurs.' },
          { label: 'Point d’entrée', status: 'warn', statusLabel: 'Sous les moyennes', evidence: 'Clôture à ' + usd(close) + ', sous les moyennes à vingt (' + usd(tech.ema20) + '), cinquante (' + usd(tech.ema50) + ') et deux cents séances (' + usd(tech.ema200) + ').', action: 'Aucune entrée au cours actuel ; surveiller un repli vers le support du couloir.' }] },
      business: { theme: 'Communautés en ligne, publicité et licence de contenu',
        overview: '<p>Reddit est un réseau de communautés — les « subreddits » — où des centaines de millions de personnes discutent par centres d’intérêt. La quasi-totalité de ses revenus vient de la publicité affichée dans ces conversations ; une petite partie, en forte croissance, vient de la vente de licences sur ses données et de produits vendus directement aux utilisateurs.</p><p>Au deuxième trimestre 2026, les revenus ont atteint 805 M$, en hausse de 61 %, dont 762 M$ de publicité (+64 %) et 43 M$ d’autres revenus (+24 %). La marge brute est de 91 %, un niveau de logiciel. Le résultat net est positif, à 253 M$, et le flux de trésorerie libre à 261 M$. Les utilisateurs actifs quotidiens atteignent 130,3 millions, en hausse de 18 % — une croissance encore forte, mais nettement ralentie par rapport aux plus de 40 % d’un an plus tôt.</p><p>Le modèle a deux dépendances. La publicité repose sur une base d’annonceurs plus jeune que celle de Meta ou d’Alphabet, en cours de construction. Et l’audience dépend en partie de la recherche : beaucoup d’utilisateurs découvrent une discussion Reddit via Google. La valeur de la donnée Reddit pour entraîner les modèles d’IA est un atout ; la réponse directe de ces mêmes modèles, qui évite le clic vers le site, en est le revers.</p>',
        moat: 'L’avantage de Reddit est le contenu que ses membres créent gratuitement, organisé par sujet et modéré par la communauté : un corpus difficile à reproduire, et devenu une matière première pour les moteurs et les modèles d’IA. Sa fragilité est la même : Reddit ne contrôle pas le canal par lequel une part de son audience arrive, la recherche, ni la façon dont l’IA restitue son contenu sans renvoyer vers lui.',
        segments: [
          { name: 'Publicité', revenue: '762 M$ au T2', pct: '+64 % sur un an', description: 'Publicité affichée dans les communautés ; base d’annonceurs en construction.' },
          { name: 'Autres revenus (licence de contenu, produits)', revenue: '43 M$ au T2', pct: '+24 % sur un an', description: 'Licence de données pour l’entraînement des moteurs et des modèles d’IA, et produits vendus aux utilisateurs.' }],
        sourceRefs: [ref(2), ref(0)],
        coverageMatrix: [
          { facet: 'Cours et historique', status: 'COUVERT', decision: 'Trois cents séances continues, close certifié ; base des niveaux.' },
          { facet: 'Résultats et guidance', status: 'COUVERT — PRIMAIRE', decision: 'Communiqué du deuxième trimestre et 10-Q ; prochaine date entre le 28 octobre et le 2 novembre selon le calendrier, non confirmée par l’émetteur.' },
          { facet: 'Capital', status: 'COUVERT — PRIMAIRE', decision: 'Actions par classe, absence de dette et programme de rachat lus dans le 10-Q et le communiqué de février ; trois classes de vote dans le 10-K.' },
          { facet: 'Agrégats GAAP', status: 'COUVERT — XBRL', decision: 'Douze mois glissants au 30 juin 2026, reconstitués depuis les données XBRL officielles.' },
          { facet: 'Comparables et transmission', status: 'COUVERT — LOCAL', decision: 'Corrélations recalculées sur barres certifiées ; groupes définis par le lien économique publicité-attention-donnée.' },
          { facet: 'Initiés', status: 'PARTIEL', decision: 'Snapshot de positions vendeuses relevé ; couverture officielle des formulaires 4 incomplète, aucun solde net affirmé.' },
          { facet: 'Options', status: 'NON EXPLOITABLE', decision: 'Chaîne relevée marché fermé, sans prix ni intérêt ouvert utilisables ; non rattachée à la clôture de référence.' },
          { facet: 'Sentiment et tendances de recherche', status: 'INDISPONIBLE', decision: 'Aucune mesure qualifiée à la collecte ; non utilisé.' }] },
      news: [
        { date: '2026-02-05', title: 'Exercice 2025 : revenus +69 %, programme de rachat de 1 Md$', impact: 'positive', detail: 'Reddit clôture 2025 sur 2,2 Md$ de revenus (+69 %) et 530 M$ de résultat net, et annonce un programme de rachat d’actions de 1,0 Md$. Le marché salue un premier exercice complet largement bénéficiaire.', source: 'Reddit — SEC', sourceUrl: docs[3].url },
        { date: '2026-07-30', title: 'Deuxième trimestre au-dessus des attentes sur les revenus', impact: 'positive', detail: 'Revenus de 805 M$ (+61 %), résultat net de 253 M$, EBITDA ajusté de 343 M$ et prévision du troisième trimestre relevée à 860-870 M$. Sur les chiffres financiers, le trimestre est solide.', source: 'Reddit — SEC', sourceUrl: docs[0].url },
        { date: '2026-07-31', title: 'Chute de ' + fr(Math.abs(pct(d0731[4], d0730[4])), 0) + ' % : la croissance des utilisateurs déçoit', impact: 'negative', detail: 'Ouverture à ' + usd(d0731[1]) + ' contre ' + usd(d0730[4]) + ' la veille, clôture à ' + usd(d0731[4]) + ' (' + sgn(pct(d0731[4], d0730[4]), 1) + ') sur un volume dix fois supérieur à la normale. Malgré la hausse des revenus, la croissance des utilisateurs quotidiens retombée à 18 % et la crainte d’un trafic de recherche menacé par l’IA emportent la séance.', source: 'Barres certifiées', sourceUrl: c.evidenceUrl },
        { date: '2026-09-25', title: 'Le titre dérive dans son couloir, sous ses moyennes', impact: 'neutral', detail: 'Clôture à ' + usd(close) + ' (' + sgn(pct(close, prev), 1) + '), au bas du couloir de septembre. Après ' + sgn(ret(63), 0) + ' en trois mois, le titre reste sous ses moyennes à vingt, cinquante et deux cents séances : consolidation, pas retournement.', source: 'Barres certifiées', sourceUrl: c.evidenceUrl }],
      fundamentals: { rows: [
          { metric: 'Revenus du deuxième trimestre', value: '805 M$', signal: '+61 % sur un an, huitième trimestre au-dessus de 60 %', signalColor: 'green', _src: 0 },
          { metric: 'Revenus publicitaires du trimestre', value: '762 M$', signal: '+64 % sur un an : le moteur de la croissance', signalColor: 'green', _src: 0 },
          { metric: 'Utilisateurs actifs quotidiens (DAUq)', value: '130,3 M', signal: '+18 % sur un an, contre plus de 40 % un an plus tôt : décélération', signalColor: 'amber', _src: 0 },
          { metric: 'Marge brute du trimestre', value: '91,3 %', signal: 'Niveau de logiciel, en légère hausse sur un an', signalColor: 'green', _src: 0 },
          { metric: 'Résultat net du trimestre', value: '253 M$', signal: '31 % des revenus, plus du double sur un an', signalColor: 'green', _src: 0 },
          { metric: 'Flux de trésorerie libre du trimestre', value: '261 M$', signal: 'Positif : la trésorerie entre réellement', signalColor: 'green', _src: 0 },
          { metric: 'Prévision de revenus du troisième trimestre', value: '860 à 870 M$', signal: 'EBITDA ajusté attendu entre 385 et 395 M$', signalColor: 'blue', _src: 0 },
          { metric: 'Revenus GAAP sur douze mois', value: fr(G$.rev / 1e9, 2) + ' Md$', signal: 'Douze mois glissants au 30 juin 2026 (XBRL SEC)', signalColor: 'blue', _src: 'gaap' },
          { metric: 'Résultat opérationnel GAAP sur douze mois', value: fr(G$.ebit / 1e6, 0) + ' M$', signal: 'Marge de ' + fr(opMargin, 0) + ' %, douze mois glissants au 30 juin 2026', signalColor: 'green', _src: 'gaap' },
          { metric: 'Résultat net GAAP sur douze mois', value: fr(G$.ni / 1e6, 0) + ' M$', signal: 'Douze mois glissants ; inclut un produit d’impôt qui le flatte', signalColor: 'blue', _src: 'gaap' },
          { metric: 'Flux de trésorerie libre GAAP sur douze mois', value: fr(G$.fcf / 1e6, 0) + ' M$', signal: 'Flux opérationnel − investissements ; modèle très peu capitalistique', signalColor: 'green', _src: 'gaap' },
          { metric: 'Trésorerie et placements au 30 juin', value: fr(G$.cash / 1e9, 2) + ' Md$', signal: 'Liquidités + titres de placement courants ; aucune dette financière', signalColor: 'green', _src: 'gaap', _also: [1] },
          { metric: 'EV/revenus GAAP', value: fr(evRev, 1) + '×', signal: 'Valeur d’entreprise au close du 2026-09-25, 192 millions d’actions, sur revenus GAAP douze mois au 2026-06-30', signalColor: 'amber', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus Meta à ' + fr(metaRev, 1) + '×, Alphabet à ' + fr(googlRev, 1) + '×, Pinterest à ' + fr(pinsRev, 1) + '× et Roblox à ' + fr(rblxRev, 1) + '× (statistiques courantes du 25 septembre, non point-in-time) : Reddit est plus cher que les géants de la publicité eux-mêmes.', _src: 'market', _peers: ['META', 'GOOGL', 'PINS', 'RBLX'], _peerField: 'enterpriseToRevenue' },
          { metric: 'P/E GAAP sur douze mois', value: fr(pe, 0) + '×', signal: 'Capitalisation au 2026-09-25 sur résultat net GAAP douze mois ; flatté par un produit d’impôt', signalColor: 'amber', source: 'Clôture certifiée et XBRL SEC', comparison: 'À manier avec prudence : le résultat net douze mois bénéficie d’un produit d’impôt non récurrent, donc le multiple est optiquement bas.', _src: 'market' },
          { metric: 'EV/revenus — scénario de re-cotation basse (hypothèse éditoriale)', value: fr(scn.price, 2) + ' $ par action', signal: 'Scénario : multiple ramené à six fois les revenus GAAP douze mois, trésorerie du 30 juin inchangée, soit ' + fr(scn.downside_pct, 0) + ' % sous le close du 2026-09-25', signalColor: 'red', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus AppLovin à ' + fr(appRev, 1) + '× et Roblox à ' + fr(rblxRev, 1) + '× : six fois reste un multiple de plateforme en croissance ; ce que coûterait un retour vers les grandes plateformes publicitaires si la croissance décélérait, pas un objectif.', _src: 'market', _peers: ['APP', 'RBLX'], _peerField: 'enterpriseToRevenue' }],
        sourceRefs: [ref(0), ref(1), market('fondamentaux et statistiques')] },
      earnings: { quarters: [],
        beatNote: 'Deuxième trimestre 2026 (clos le 30 juin) : revenus de 805 M$ (+61 %), résultat net de 253 M$, soit 1,25 $ par action diluée, EBITDA ajusté (non-GAAP) de 343 M$ et flux de trésorerie libre de 261 M$. La guidance du troisième trimestre vise 860 à 870 M$ de revenus et 385 à 395 M$ d’EBITDA ajusté. Sur les chiffres financiers, le trimestre bat les attentes ; c’est la décélération des utilisateurs quotidiens (DAUq +18 %) qui a provoqué la chute du titre. Prochaine publication attendue entre le 28 octobre et le 2 novembre selon le calendrier, non confirmée par l’émetteur.',
        nextEarnings: 'Attendue entre le 28 octobre et le 2 novembre 2026 selon le calendrier collecté ; non confirmée par l’émetteur, hors des quatorze jours de la fenêtre de surveillance.',
        sourceRefs: [ref(0)] },
      capitalStructure: { sharesOutstanding: '146 103 200 actions Class A et 46 293 310 actions Class B au 29 juillet 2026 (page de garde du 10-Q), soit 192 396 510 au total ; aucune action Class C émise',
        sharesAuthorized: 'Actions autorisées non reprises ligne à ligne : non décisionnel pour ce dossier.', dilutionRisk: 'moderate',
        shareHistory: 'Base retenue : 192 396 510 actions, somme des Class A et Class B en circulation au 29 juillet. Les deux classes ont le même poids économique ; la Class B (46,3 millions de titres, détenue par les fondateurs et premiers investisseurs) porte dix voix par action selon le 10-K, d’où un contrôle concentré. Le nombre entièrement dilué approche 207 millions d’actions au 30 juin, écart correspondant aux plans de rémunération en actions. La seule source de dilution est cette rémunération en actions : il n’existe ni obligation convertible, ni bon de souscription, ni programme d’émission sur le marché, ni prospectus de tirage dans la période examinée. À l’inverse, le programme de rachat de 1,0 Md$ autorisé le 4 février 2026 (1 523 502 actions rachetées sur le premier semestre, dont 235 M$ au deuxième trimestre) rend une partie de cette dilution : le nombre d’actions évolue de façon prévisible, sans émission de marché.',
        warrants: [],
        atm: { active: false, authorized: 'Aucun programme d’émission sur le marché ; à l’inverse, programme de rachat de 1,0 Md$ de Class A autorisé le 4 février 2026', used: '1 523 502 actions rachetées au premier semestre 2026', remaining: 'Capacité de rachat restante non détaillée ligne à ligne dans les dépôts retenus' },
        sourceRefs: [ref(1), ref(3)] },
      filingsReview: { summary: 'Quatre dépôts décisionnels ouverts et hachés, sur un inventaire de dix-huit formulaires hors déclarations d’initiés. Ils montrent une croissance réelle et rentable, un bilan sans dette, un programme de rachat actif et, fait rare, aucune émission d’actions de marché. Le point de vigilance n’est pas dans les comptes : c’est la dépendance au trafic de recherche, décrite dans les facteurs de risque du 10-K.',
        filings: docs.map(d => ({ date: d.date, form: d.form, accession: d.accession, finding: d.finding, url: d.url })),
        contrarianRisks: [
          'La croissance des utilisateurs quotidiens a plus que divisé par deux en un an : une part de l’audience dépend de la recherche Google, hors du contrôle de Reddit.',
          'La généralisation des réponses par IA peut restituer le contenu Reddit sans renvoyer vers le site : moins de clics, moins d’impressions publicitaires.',
          'La rémunération en actions dilue chaque année ; l’écart entre l’EBITDA ajusté mis en avant et le résultat GAAP mesure ce coût, seulement en partie compensé par le rachat.',
          'La base d’annonceurs est plus jeune et moins diversifiée que celle de Meta ou d’Alphabet : elle est plus sensible à un ralentissement du marché publicitaire.',
          'Le contrôle par les actions à droit de vote multiple laisse peu de prise aux actionnaires minoritaires sur la gouvernance.'] },
      technicals: { rsi14: +tech.rsi14.toFixed(2), macd: +tech.macd.toFixed(2), macdSignal: +tech.macdSignal.toFixed(2), ema20: +tech.ema20.toFixed(2), ema50: +tech.ema50.toFixed(2), ema200: +tech.ema200.toFixed(2),
        ma50Type: 'EMA', ma200Type: 'EMA', ma50Available: true, ma200Available: true, atr14: +tech.atr14.toFixed(2),
        badges: ['Sous les moyennes à vingt, cinquante et deux cents séances', 'Couloir de consolidation post-résultats 140-166 $', 'Aucune entrée au cours actuel'],
        supports: [lv('s1'), lv('s2'), lv('s3')], resistances: [lv('r1'), lv('r2')],
        setupNote: 'Le titre clôture à ' + usd(close) + ', sous ses moyennes à vingt (' + usd(tech.ema20) + '), cinquante (' + usd(tech.ema50) + ') et deux cents séances (' + usd(tech.ema200) + '), RSI à ' + fr(tech.rsi14, 0) + '. Depuis le gap de résultats du 31 juillet, il évolue dans un couloir borné par le support triple-testé vers ' + dol(entry) + ' et le haut vers ' + usd(lv('r2')) + '. Repli tactique à surveiller : un retour vers le support à ' + dol(entry) + ', avec stop sous le plancher de la base à ' + dol(stop) + ', viserait le mi-haut (' + usd(lv('r1')) + ') puis le haut (' + usd(lv('r2')) + ') du couloir. Ce n’est pas un signal de retournement : la tendance reste baissière tant que les moyennes ne sont pas reprises.',
        wyckoff: 'Phase de consolidation en couloir après le repli de juillet (redistribution ou accumulation à départager) ; non utilisée pour fixer les niveaux.',
        sourceRefs: [market('barres quotidiennes et indicateurs recalculés')] },
      options: { callOI: 'Non exploitable', putOI: 'Non exploitable', cpRatio: 'Non exploitable', maxPain: 'Non exploitable', ivMean: 'Non exploitable', skew: 'Chaîne relevée marché fermé, sans prix ni intérêt ouvert utilisables ; non rattachée à la clôture de référence', unusual: 'Aucune activité inhabituelle qualifiée', sourceRefs: [market('options')] },
      shortInterest: { siPct: fr(st.shortPercentOfFloat * 100, 2) + ' % du flottant', daysToCover: fr(st.shortRatio, 2) + ' jours, date de règlement non précisée par le snapshot', ctb: 'Coût d’emprunt non disponible à la collecte', trend: 'Positions vendeuses non négligeables pour une valeur de cette taille (' + fr(st.shortPercentOfFloat * 100, 0) + ' % du flottant) ; reflètent le débat sur la valorisation et le trafic, pas une thèse de rachat forcé.', squeezeScore: 'Non retenu comme thèse', sourceRefs: [market('positions vendeuses')] },
      insiders: { signal: 'Snapshot de positions vendeuses relevé à la collecte ; la couverture officielle des formulaires 4 est incomplète et aucun solde net d’initiés n’est affirmé. Les fondateurs conservent le contrôle par la Class B à droit de vote multiple.',
        recentTransactions: [],
        sourceRefs: [market('positions vendeuses et couverture partielle des formulaires 4')] },
      macro: { indicators: [{ name: 'Clôture de référence', value: c.REF, signal: usd(close) + ', séance complète' }, { name: 'Rendement cinq séances', value: sgn(ret(5)), signal: 'Descriptif' }, { name: 'Rendement vingt et une séances', value: sgn(ret(21)), signal: 'Descriptif' }],
        regime: 'neutral', impact: 'Reddit dépend du budget publicitaire des annonceurs, sensible au cycle économique, et de la prime de risque accordée aux logiciels de croissance. Sans dette, la société est peu sensible aux taux par son bilan ; sa cote l’est en revanche par son multiple, qui se comprime quand les taux longs montent. Le régime de marché ne remplace pas le test propre au titre : la dépendance au trafic de recherche.' },
      risks: { riskScore: 6, riskProfile: 'High',
        riskSummary: 'Le risque de Reddit n’est pas son bilan, sans dette et riche de 2,8 Md$, ni une dilution de marché, absente. C’est le prix — au-dessus des géants de la publicité — et une double dépendance : à une base d’annonceurs encore jeune, et à un trafic de recherche que la recherche assistée par IA peut détourner. Le bêta supérieur à deux amplifie chaque déception.',
        riskCards: [
          { title: 'Désintermédiation par l’IA', severity: 'high', icon: 'fa-robot', points: ['Une part de l’audience arrive par la recherche Google.', 'Les réponses générées par IA restituent le contenu sans renvoyer vers le site.'], verdict: 'Si le trafic de recherche se tarit, l’audience et les impressions publicitaires baissent ensemble : c’est le cœur de la thèse baissière et la cause probable du décrochage des utilisateurs.' },
          { title: 'Valorisation au-dessus des géants', severity: 'high', icon: 'fa-scale-balanced', points: ['EV/revenus de ' + fr(evRev, 1) + '×, au-dessus de Meta et d’Alphabet.', 'La moindre déception se paie cher à ce multiple.'], verdict: 'Payer une plateforme plus cher que les leaders de son marché suppose que sa croissance reste très supérieure ; la décélération de juillet a montré le coût d’un doute.' },
          { title: 'Décélération des utilisateurs', severity: 'medium', icon: 'fa-arrow-trend-down', points: ['DAUq +18 %, contre plus de 40 % un an plus tôt.', 'Croissance encore réelle, mais la trajectoire compte plus que le niveau.'], verdict: 'La valorisation escompte une croissance durablement élevée : chaque trimestre de décélération rapproche Reddit du multiple des plateformes matures.' },
          { title: 'Concentration et gouvernance', severity: 'medium', icon: 'fa-user-tie', points: ['Base d’annonceurs plus jeune que celle des géants.', 'Contrôle des fondateurs par la Class B à dix voix.'], verdict: 'Le levier publicitaire reste à prouver dans un ralentissement, et les minoritaires ont peu de prise sur la gouvernance.' }],
        pedagogy: 'Reddit illustre le décalage entre un excellent dossier d’entreprise et un point d’entrée. Les comptes sont solides : croissance de 61 %, marge de logiciel, flux de trésorerie libre, aucune dette. Mais le marché paie déjà cette qualité au prix fort — plus cher que Meta ou Alphabet — et il sanctionne toute décélération, comme en juillet. La vraie inconnue n’est pas la rentabilité, c’est le trafic : Reddit dépend en partie de la recherche, et l’IA change la façon dont on cherche. Côté marché, le titre échange environ ' + fr(adv / 1e6, 0) + ' M$ par séance : la liquidité est bonne, mais le bêta supérieur à deux et les gaps post-résultats imposent une taille modeste. Ici, la patience — attendre un repli dans le couloir — vaut mieux que la poursuite.' },
      tradeIdea: { status: 'watch',
        statusNote: 'Surveiller. Aucune entrée au cours actuel (' + usd(close) + ') : le titre est au-dessus du support visé et sous toutes ses moyennes. Plan de repli tactique dans le couloir, non un signal de tendance : entrée sur repli vers ' + usd(entry) + ', le support triple-testé, à ne pas payer au-dessus de ' + usd(cap) + ' pour garder un rapport risque-rendement d’au moins 1,5 vers le premier objectif. Stop sous ' + usd(stop) + ', le plancher de la base ; une clôture en dessous abandonne le scénario.',
        entry, stop, tp1, tp2,
        stopPct: pct(stop, entry).toFixed(1) + '%', tp1Pct: '+' + pct(tp1, entry).toFixed(1) + '%', tp2Pct: '+' + pct(tp2, entry).toFixed(1) + '%',
        rr: '1:' + rr1.toFixed(2) + ' TP1 / 1:' + rr2.toFixed(2) + ' TP2',
        entryNote: 'Aucune entrée au cours actuel. Entrée seulement sur un repli vers le support triple-testé du couloir (' + usd(entry) + ', touché les 20 août, 1er, 2 et 9 septembre), à ne pas payer au-dessus de ' + usd(cap) + ' : au-delà, le R/R vers le premier objectif tomberait sous 1,5 avec le même stop. Stop sous le plancher de la base à ' + usd(stop) + '. Objectifs au mi-haut (' + usd(tp1) + ') et au haut (' + usd(tp2) + ') du couloir de septembre. Trade de couloir, à solder au haut de la fourchette, pas à conserver pour un retournement. Liquidité : environ ' + fr(adv / 1e6, 0) + ' M$ échangés par séance ; ATR de ' + usd(tech.atr14) + '. Exemple de taille, non personnalisé : 100 $ de perte maximale divisés par le risque par action au plafond, soit ' + sizeExample + ' actions.',
        horizon: 'Swing tactique de couloir, quelques semaines ; aucune position au cours actuel',
        thesis: 'Reddit est un excellent dossier d’entreprise à un prix exigeant, dans une tendance de fond baissière. On n’achète pas la poursuite : le titre est sous toutes ses moyennes depuis le repli de juillet. Le seul plan raisonnable au cours actuel est un trade de couloir, tactique : acheter un repli vers le support triple-testé à ' + dol(entry) + ', avec un stop serré sous le plancher de la base à ' + dol(stop) + ', pour viser le haut du couloir. Ce n’est pas un pari sur le retournement ; c’est jouer une fourchette bornée en attendant un signal plus net — soit une reprise franche au-dessus des moyennes, soit une capitulation qui offrirait un meilleur point d’entrée de fond. Tant que le trafic de recherche reste une inconnue, la prudence prime sur la conviction.',
        catalysts: ['Un repli vers le support triple-testé du couloir (' + usd(entry) + ') sans casser le plancher de la base (' + usd(stop) + ').', 'Les résultats du troisième trimestre, attendus fin octobre, face à la prévision de 860 à 870 M$ et surtout à la trajectoire des utilisateurs quotidiens.', 'Tout signal sur l’effet de la recherche assistée par IA sur le trafic de Reddit — le vrai déterminant de la thèse de fond.'],
        invalidation: ['Une clôture sous le plancher de la base (' + usd(stop) + ') abandonne le plan de couloir.', 'Un achat au cours actuel, au-dessus du support et sous les moyennes, contredit ce dossier : pas de poursuite.', 'Une nouvelle décélération marquée des utilisateurs quotidiens invaliderait la thèse de fond, au-delà du seul trade de couloir.'] },
      globalScore: { profile: 'Plateforme sociale rentable et chère, tendance cassée, dépendance au trafic',
        keyTakeawaysPositive: ['Croissance de 61 %, marge brute de 91 %, résultat net et flux libre positifs.', 'Bilan sans dette, 2,8 Md$ de trésorerie, rachat d’actions de 1 Md$.', 'Donnée communautaire rare, recherchée par les moteurs et les modèles d’IA.'],
        keyTakeawaysNegative: ['Valorisation au-dessus de Meta et d’Alphabet : peu de marge d’erreur.', 'Croissance des utilisateurs quotidiens divisée par plus de deux en un an.', 'Dépendance au trafic de recherche que l’IA peut détourner ; titre sous ses moyennes.'],
        mindsetTip: 'Une entreprise formidable et une bonne affaire boursière sont deux choses différentes. Reddit est la première ; au cours actuel, sous ses moyennes et au-dessus des géants de la publicité, elle n’est pas encore la seconde. Attendre un repli ou une base coûte moins cher que poursuivre.' },
      social: { platforms: [], sourceRefs: [market('sentiment non retenu faute de mesure qualifiée')] },
      disclaimer: 'Document de recherche éducatif. Ni conseil financier, ni signal de trading. Statut surveiller : aucun ordre actif au cours actuel ; le plan de couloir n’est pas déclenché.',
    };
  },
  route: (p, { prov, dep, P, Pm, B }) => {
    if (/^news\.0\./.test(p)) return Pm(3);   // 05/02 : communiqué de l'exercice 2025 (rachat, revenus annuels)
    if (/^news\.1\./.test(p)) return Pm(0);   // 30/07 : communiqué du deuxième trimestre
    if (/^news\.[23]\./.test(p)) return prov('bars', B, 'Ouverture et clôture lues sur les barres certifiées ; écart d’ouverture = ouverture / clôture de la veille − 1 ; comparaison avec les pairs sur la même séance.', [dep('comparison', '')]);
    return null;
  },
  groups: [
    { name: 'Leader : plateforme publicitaire', order: 1, transmission: 'Il fixe le prix et le rythme du marché publicitaire numérique ; sa santé conditionne le budget qui arrive jusqu’à Reddit.', rows: [
      ['META', 'leader', 'Premier réseau social publicitaire', 'Référence de valorisation et principal concurrent pour le budget publicitaire ; sa base d’annonceurs mature encadre le multiple qu’un réseau social peut porter.']] },
    { name: 'Amont : recherche, données et infrastructure', order: 1, transmission: 'Reddit dépend d’Alphabet en amont : une part de son trafic vient de la recherche, et Alphabet héberge et achète aussi sa donnée.', rows: [
      ['GOOGL', 'upstream', 'Recherche, source de trafic et acheteur de licence de données', 'Triple lien amont : une part du trafic de Reddit vient de la recherche Google, Alphabet achète sa licence de données et fournit de l’infrastructure ; sa recherche assistée par IA est le principal risque de désintermédiation, et Alphabet est aussi un géant publicitaire concurrent.']] },
    { name: 'Pairs directs : réseaux sociaux et attention', order: 1, transmission: 'Mêmes budgets publicitaires arbitrés entre plateformes qui se disputent le temps et l’attention des utilisateurs.', rows: [
      ['PINS', 'direct_peer', 'Réseau social de découverte', 'Réseau social de taille comparable, monétisé par la publicité ; repère direct de ce que le marché paie pour une plateforme sociale plus mûre.'],
      ['RBLX', 'direct_peer', 'Plateforme communautaire de jeu', 'Autre plateforme d’utilisateurs jeunes monétisée par l’engagement et la publicité ; même débat croissance contre rentabilité.'],
      ['MTCH', 'direct_peer', 'Applications sociales de rencontre', 'Réseau social de niche à monétisation directe ; montre le plancher de valorisation d’un social à croissance faible.']] },
    { name: 'Aval : chaîne publicitaire et mesure', order: 2, transmission: 'Ces sociétés routent, optimisent et mesurent les budgets publicitaires qui alimentent Reddit ; leur activité est un signal avancé de la demande.', rows: [
      ['APP', 'downstream', 'Plateforme publicitaire mobile et IA', 'Moteur publicitaire piloté par IA ; référence de la prime accordée à une plateforme publicitaire en hyper-croissance.'],
      ['MGNI', 'downstream', 'Plateforme côté offre (SSP)', 'Monétise l’inventaire des éditeurs ; sa santé reflète la demande pour l’inventaire publicitaire numérique.'],
      ['DV', 'downstream', 'Mesure et vérification publicitaire', 'Vérifie la qualité des impressions ; son activité suit le volume de publicité numérique.'],
      ['CRTO', 'downstream', 'Reciblage et publicité de performance', 'Publicité de performance sur l’inventaire des éditeurs ; sensible au même cycle de dépenses.']] },
    { name: 'Second ordre : plateformes internet grand public', order: 2, transmission: 'Plateformes à forte audience dont l’attention et les budgets marketing croisent ceux de Reddit, et qui dépendent aussi du trafic de recherche.', rows: [
      ['NFLX', 'second_order', 'Streaming avec palier publicitaire', 'Concurrent pour le temps d’écran ; son palier financé par la publicité lit la demande du budget vidéo en ligne.'],
      ['ZG', 'second_order', 'Place de marché immobilière en ligne', 'Plateforme internet grand public monétisée par la publicité et les contacts, elle aussi dépendante du trafic de recherche : même sensibilité à la désintermédiation.']] },
    { name: 'Contrôles sectoriels', order: 2, transmission: 'Paniers de référence pour séparer le mouvement du titre de celui de son secteur.', rows: [
      ['XLC', 'sector_proxy', 'Secteur services de communication du S&P', 'Contient les grandes plateformes de médias et de communication ; un mouvement commun n’a rien de propre à Reddit.'],
      ['SOCL', 'sector_proxy', 'Panier de médias sociaux', 'Panier ciblé sur les réseaux sociaux ; montre si le segment social monte ou baisse dans son ensemble.']] },
  ],
  eventDefault: { leader: 'Aucune publication dans les quatorze jours collectés ; ses résultats donnent le ton du marché publicitaire', upstream: 'Aucune publication dans les quatorze jours collectés ; ses évolutions de recherche et de licence de données restent le signal amont à suivre', direct_peer: 'Aucune publication dans les quatorze jours collectés ; ses tendances d’utilisateurs et de monétisation valent pour le segment', downstream: 'Aucune publication dans les quatorze jours collectés ; son activité est un signal avancé de la demande publicitaire', second_order: 'Aucune publication dans les quatorze jours collectés ; ses budgets marketing et sa régie restent à suivre', sector_proxy: 'Panier sans publication propre ; exposé aux résultats de ses grandes pondérations' },
  eventRisk: {},
  blastDoc: 0,
  scenarios: c => [
    { scenario: 'bullish', trigger: 'Le troisième trimestre confirme une ré-accélération des utilisateurs et le marché publicitaire reste porteur.', firstOrder: 'Le titre reprend ses moyennes et sort du couloir par le haut, au-dessus de ' + c.usd(c.lv('r2')) + '.', secondOrder: 'Les pairs sociaux et la chaîne publicitaire suivent ; la prime de Reddit se justifie de nouveau.', confirmation: 'Une clôture au-dessus de ' + c.usd(c.lv('r2')) + ' avec un volume soutenu et une croissance des utilisateurs stabilisée.', contradiction: 'Une sortie par le haut du couloir pendant que le panier SOCL et la chaîne publicitaire reculent.' },
    { scenario: 'mixed', trigger: 'Les revenus tiennent mais la croissance des utilisateurs reste molle, sans nouvelle sur l’effet de l’IA.', firstOrder: 'Le titre poursuit sa consolidation dans le couloir 140-166 $, sous ses moyennes.', secondOrder: 'L’écart de performance avec les grandes plateformes reste faible, sans information propre.', confirmation: 'Des clôtures bornées entre ' + c.usd(c.lv('s1')) + ' et ' + c.usd(c.lv('r2')) + ' pendant plusieurs semaines.', contradiction: 'Une sortie franche d’un côté ou de l’autre du couloir.' },
    { scenario: 'bearish', trigger: 'La recherche assistée par IA pèse visiblement sur le trafic, ou la croissance des utilisateurs déçoit encore.', firstOrder: 'Le titre casse le plancher de la base sous ' + c.usd(c.lv('s2')) + ', puis vise le plus bas du gap de juillet (' + c.usd(c.lv('s3')) + ').', secondOrder: 'Le multiple se comprime vers celui des plateformes matures ; les pairs sociaux les plus chers reculent davantage.', confirmation: 'Une clôture sous ' + c.usd(c.lv('s2')) + ' avec un trafic ou des utilisateurs en baisse confirmés au trimestre suivant.', contradiction: 'Un repli du secteur que Reddit ne suit pas, ou une stabilisation nette du trafic.' }],
  contradictions: c => ['Les revenus battent les attentes mais le titre a chuté après publication : la corrélation avec les pairs ne suffit pas à expliquer le mouvement, dû à la décélération des utilisateurs propre au titre.', 'Une corrélation élevée avec un pair publicitaire ne prouve pas un lien commercial ; seul Alphabet est à la fois concurrent et source documentée de trafic et de licence de données.'],
  missingData: c => ['Aucun client final n’est nommé au-delà de la mention d’Alphabet comme source de trafic et acheteur de licence de données : aucun client coté n’entre dans les comparables comme client documenté.', 'Chaîne d’options relevée marché fermé, inexploitable ; sentiment social et tendances de recherche indisponibles à la collecte ; coût d’emprunt indisponible.', 'Couverture officielle des formulaires 4 incomplète : aucun solde net d’initiés affirmé.', 'Fondamentaux, statistiques et corrélations relevés en instantané le 25 septembre, non reconstitués à la clôture de référence.'],
  limitations: ['Fondamentaux et statistiques du fournisseur relevés en instantané, non point-in-time.', 'Options inexploitables (chaîne relevée marché fermé) ; sentiment et tendances de recherche indisponibles ; coût d’emprunt indisponible.', 'Prochaine date de résultats non confirmée par l’émetteur ; produit d’impôt qui flatte le résultat net et le P/E douze mois.'],
});
