'use strict';
// Dossier ZS v3 au close du 2026-09-23 (lot R03). Aucun plan actif : le titre a pris plus de 30 % en onze
// séances et bute sur les résistances de janvier ; les niveaux du 27 août restent affichés comme référence
// archivée. Calculs, provenance et preuves délégués au gabarit commun tools/lib/analysis-v3-r03.cjs.
const R = require('../../../../tools/lib/analysis-v3-r03.cjs');
const GEN = 'analyses/ZS/_runs/20260924/build-zs.cjs';

R.build({
  ticker: 'ZS', shortName: 'Zscaler', cik: 1713683, generator: GEN, mode: 'archived',
  xbrl: { ttm: { rev: ['RevenueFromContractWithCustomerExcludingAssessedTax'], ebit: ['OperatingIncomeLoss'], ni: ['NetIncomeLoss'], da: ['DepreciationDepletionAndAmortization'], ocf: ['NetCashProvidedByUsedInOperatingActivities'] },
    instant: { notes: ['ConvertibleLongTermNotesPayable'], cashEq: ['CashAndCashEquivalentsAtCarryingValue'], stInv: ['DebtSecuritiesAvailableForSaleExcludingAccruedInterestCurrent'] }, da: ['da'], debt: ['notes'], cash: ['cashEq', 'stInv'] },
  scenarioBasis: 'revenue', scenarioMultiple: 7,
  valuationBasis: 'GAAP de l’exercice clos le 2026-07-31 (XBRL SEC) ; obligations 2028 à leur valeur comptable dans la dette ; trésorerie = liquidités et placements à court terme ; multiple de sept fois les revenus = hypothèse éditoriale',
  levels: { s1: { d: '2026-09-23', c: 3 }, s2: { d: '2026-09-22', c: 3 }, s3: { d: '2026-09-18', c: 3 }, r1: { d: '2026-09-23', c: 2 }, r2: { d: '2026-01-27', c: 2 }, r3: { d: '2026-01-07', c: 2 } },
  supports: ['s1', 's2', 's3'], resistances: ['r1', 'r2', 'r3'],
  inventory: 11,
  reviewScope: 'Dépôts EDGAR de Zscaler du 1er janvier au 23 septembre 2026 (11 formulaires hors formulaires 3, 4, 5 et 144), dont le 10-K de l’exercice 2026. Les 8-K de gouvernance (items 5.02 et 5.07) et les déclarations 13G sont écartés comme non décisionnels ; les deux 10-Q de l’exercice sont couverts par le 10-K. Aucun prospectus d’émission d’actions n’est relevé ; le S-8 du 3 septembre enregistre l’augmentation annuelle des plans de rémunération.',
  docs: [
    ['2026-09-03', '10-K', '0001713683-26-000157', 'zs-20260731.htm', 'fy26-10k__zs-20260731.htm',
      'Rapport annuel de l’exercice clos le 31 juillet 2026 : aucun client à 10 % des revenus, partenaires de distribution à 85 % des ventes. Obligations 2028 de 1 725 M$ convertibles à 439,52 $ par action. 163,1 millions d’actions au 27 août, contre 158,3 millions un an plus tôt. Red Canary racheté 651,4 M$ en numéraire.'],
    ['2026-09-03', '8-K / Exhibit 99.1', '0001713683-26-000156', 'zs-07312026_991.htm', 'q4fy26-8k__zs-07312026_991.htm',
      'Communiqué du quatrième trimestre : revenus de 898,2 M$ (+25 %), revenus récurrents annualisés de 3 771 M$ (+25 %, +20 % hors Red Canary), flux libre du trimestre ramené à 60,8 M$ par 218,5 M$ d’investissements. Prévision 2027 : 3,908 à 3,938 Md$ de revenus, +16,6 à 17,5 %.'],
    ['2026-09-03', '8-K', '0001713683-26-000156', 'zs-20260901.htm', 'q4fy26-8k__zs-20260901.htm',
      'Plan de restructuration décidé le 1er septembre : environ 3 % des effectifs mondiaux, pour 30,0 à 33,0 M$ de charges non récurrentes, surtout au premier semestre de l’exercice 2027.'],
    ['2026-09-03', 'S-8', '0001713683-26-000158', 'zs_s-8xfy2026.htm', 'sep03-s8__zs_s-8xfy2026.htm',
      'Enregistrement de l’augmentation annuelle des actions réservées aux plans de rémunération et d’achat d’actions des salariés : réserve de plan, pas une levée de fonds.'],
  ],
  needles: {
    annual: [0, ['163,054,698', 'No customer accounted for 10% or more of total revenue during the periods presented', 'one channel partner accounted for 13 %', 'Channel partners $ 2,835,257 85 %', 'remaining performance obligations was $ 7,365.4 million. We expect to recognize 45 %', 'over 200 public data centers globally', 'top-tier internet interconnection hubs', 'sole or limited sourced hardware']],
    capital: [0, ['Notes 2.2752 $ 439.52 3,925', 'we issued $1,725 million in aggregate principal amount of our 0.0% Convertible Senior Notes due 2028', '163,055 and 158,301 shares issued and outstanding', 'for total cash consideration of $651.4 million', 'Short-term investments 2,545,797', 'Convertible senior notes 1,696,355']],
    q4: [1, ['Grew 25% year over year to $898.2 million', 'Grew 25% year over year to $3,771 million', 'ARR grew 20% to $3,630 million', 'Grew 25% year over year to $3,353 million', 'Revenue grew 20% to $3,209 million', 'GAAP loss from operations was $133.3 million', 'GAAP net loss was $63.2 million', 'Free cash flow was $779.1 million', 'Free cash flow was $60.8 million', 'capex and internal use software of $218.5 million', 'Revenue of $935 million to $939 million', 'Revenue of approximately $3.908 billion to $3.938 billion, growth of 16.6% to 17.5%', 'ARR of $4.396 billion to $4.426 billion', 'assuming approximately 173 million fully diluted shares outstanding']],
    restructuring: [2, ['reduce our worldwide headcount by approximately 3%', 'approximately $30.0 million to $33.0 million']],
    espp: [3, ['registers additional shares of common stock of Zscaler, Inc.']],
  },
  sectionDocs: { verdict: [1, 0], business: [0, 1], news: [1, 2], earnings: [1], capitalStructure: [0, 3], filingsReview: [0, 1, 2], risks: [1, 0], globalScore: [1], meta: [1], disclaimer: [1], macro: [1], options: [1], social: [1], header: [0] },
  score: { business: 22, technical: 2, capital: 0, calendar: 0, dilution: -1, risk: 30 },
  peers: true,
  shares: { value: 163054698, doc: 0 },
  route: (p, { prov, dep, B }) => /^news\.[01]\./.test(p) ? prov('bars', B, 'Ouverture et clôture lues sur les barres certifiées ; écart d’ouverture = ouverture / clôture de la veille − 1 ; comparaison avec CIBR sur la même séance.', [dep('comparison', '')]) : null,
  riskScoreReason: 'Jugement qualitatif sur dix : ralentissement annoncé de la croissance, titre étiré après onze séances de hausse et résistances proches.',
  compose: c => {
    const { fr, usd, pct, sgn, close, prev, bars, N, tech, st, M, adv, ret, G$, g, marketCap, ev, scn, lv, entry, stop, tp1, tp2, rr1, rr2, ref, market, docs, raw, peerStat, archive } = c;
    const cibr21 = M.CIBR.return21d, own21 = ret(21), evRev = ev / G$.rev, evFwd = ev / 3.923e9;
    const net = peerStat('NET', 'enterpriseToRevenue'), crwd = peerStat('CRWD', 'enterpriseToRevenue'), ftnt = peerStat('FTNT', 'enterpriseToRevenue');
    const bar = d => bars.find(b => b[0] === d), prevOf = d => bars[bars.findIndex(b => b[0] === d) - 1];
    const d0904 = bar('2026-09-04'), p0904 = prevOf('2026-09-04'), d0914 = bar('2026-09-14'), p0914 = prevOf('2026-09-14');
    const low0908 = bar('2026-09-08')[4], run = pct(close, low0908), ext20 = pct(close, tech.ema20), extAtr = (close - tech.ema20) / tech.atr14;
    // Test d'un achat sur cassure du plus haut du 23 septembre, stop sous le bas du 22, objectif la résistance de janvier.
    const bo = { e: lv('r1'), s: lv('s2'), t: lv('r2') }; bo.rr = (bo.t - bo.e) / (bo.e - bo.s);
    return {
      meta: { lang: 'fr', dir: 'ltr', level: 'intermediate', tags: ['us', 'equities', 'ai-chain', 'software', 'technology'], grade: 'B-', date: '2026-09-24', dateDisplay: '24 septembre 2026', version: 3, status: 'no-trade', assetType: 'stock', levelsCloseDate: c.REF,
        description: 'Zscaler : un rebond de plus de 30 % en onze séances face à une prévision qui ralentit. Dossier au close du 23 septembre 2026, aucun plan actif.',
        ogDescription: 'Zscaler : revenus +25 % mais prévision 2027 à +17 %, titre remonté de 162 à 214 $ ; pas d’entrée au cours actuel.',
        lastMcpRefresh: raw.status.captured_at, levelsVerifiedAt: raw.status.captured_at,
        statusHistory: [{ at: raw.status.captured_at, from: 'wait', to: 'no-trade', note: 'refonte v3 du 24 septembre : aucun plan au cours actuel, clôture de référence du 2026-09-23', close }] },
      header: { ticker: 'ZS', name: 'Zscaler, Inc.', exchange: 'NASDAQ', sector: 'Cybersécurité en nuage : accès sécurisé et protection des données', price: close, changePct: pct(close, prev),
        badges: [{ text: 'AUCUN PLAN — TITRE ÉTIRÉ', color: 'amber' }, { text: 'Chaîne IA — sécurité des accès', color: 'purple' }],
        metrics: { marketCap: fr(marketCap / 1e9, 1) + ' Md$', volume: fr(bars[N][5] / 1e6, 2) + ' M', evRevenue: fr(evRev, 1) + '×' }, halalStatus: 'unknown' },
      verdict: { score: 53, conviction: 'Low', bias: 'Neutral',
        confidence: 'Score éditorial non prédictif. Les chiffres d’entreprise viennent des dépôts SEC et des données XBRL officielles ; les niveaux, du close certifié du 23 septembre.',
        summary: 'Zscaler a clos son exercice avec 3,35 Md$ de revenus (+25 %), mais la croissance hors Red Canary n’est que de 20 %, et la société prévoit 16,6 à 17,5 % pour 2027. La première séance après le communiqué a coûté ' + fr(Math.abs(pct(d0904[4], p0904[4])), 2) + ' %. Depuis le 8 septembre, le titre est pourtant remonté de ' + usd(low0908) + ' à ' + usd(close) + ', soit ' + sgn(run, 1) + ' en onze séances. Il clôture ' + fr(ext20, 1) + ' % au-dessus de sa moyenne à vingt séances et se rapproche des plus hauts de janvier, 229,00 et 231,48 $. À ' + fr(evRev, 1) + ' fois les revenus, il reste bien moins cher que CrowdStrike (' + fr(crwd, 1) + '×), mais un achat sur cassure du plus haut du 23 septembre ne viserait que 229,00 $ pour un risque équivalent : R/R de ' + fr(bo.rr, 2) + '. Aucun plan au cours actuel.',
        whyBuy: [
          'Revenus récurrents annualisés de 3 771 M$ au 31 juillet (+25 %), dont 3 630 M$ hors Red Canary (+20 %).',
          'À ' + fr(evRev, 1) + ' fois les revenus de l’exercice, Zscaler se paie bien moins que CrowdStrike (' + fr(crwd, 1) + '×) ou Cloudflare (' + fr(net, 1) + '×), et moins que Fortinet (' + fr(ftnt, 1) + '×), statistiques courantes du 24 septembre.',
          'Flux de trésorerie opérationnel de 1 130 M$ sur l’exercice, soit 34 % des revenus.',
          'Aucun client ne dépasse 10 % des revenus ; 7 365 M$ de contrats restent à exécuter, dont 45 % sur douze mois.'],
        whyAvoid: [
          'La prévision 2027 vise 16,6 à 17,5 % de croissance, contre 25 % publiés et 20 % hors rachat : le ralentissement est annoncé par la société.',
          'Le flux libre du quatrième trimestre tombe à 60,8 M$, contre 171,9 M$ un an plus tôt, sous 218,5 M$ d’investissements.',
          'Le titre clôture ' + fr(ext20, 1) + ' % au-dessus de sa moyenne à vingt séances, soit ' + fr(extAtr, 1) + ' ATR : acheter ici, c’est payer le rebond déjà fait.',
          'Résultat opérationnel GAAP négatif de 133,3 M$ sur l’exercice, malgré une marge ajustée de 23 %.'],
        controlChecklist: [
          { label: 'Historique de cours', status: 'pass', statusLabel: 'Trois cents séances continues', evidence: 'Série quotidienne certifiée au close du 23 septembre, source de repli documentée.', action: 'Supports et résistances lus sur cette seule série.' },
          { label: 'Extension du titre', status: 'fail', statusLabel: sgn(run, 1) + ' en onze séances', evidence: 'Clôture à ' + usd(close) + ', ' + fr(ext20, 1) + ' % au-dessus de la moyenne à vingt séances ; RSI à ' + fr(tech.rsi14, 1) + '.', action: 'Pas d’entrée tant que le titre n’a pas consolidé.' },
          { label: 'Calendrier', status: 'pass', statusLabel: 'Aucune publication dans l’horizon', evidence: 'Aucune date de résultats de Zscaler ni d’un comparable dans les quatorze jours du calendrier collecté ; la société n’a pas annoncé la date du premier trimestre.', action: 'Vérifier la date avant de construire un nouveau plan.' }] },
      business: { theme: 'Accès sécurisé en nuage, protection des données et opérations de sécurité',
        overview: '<p>Zscaler fait passer le trafic des salariés, des sites et désormais des agents d’IA par son propre nuage, réparti sur plus de 200 centres de données publics, au lieu de le faire transiter par le réseau de l’entreprise. La sécurité s’applique à la connexion elle-même, selon l’identité de l’utilisateur et la règle métier, ce qui rend inutiles une partie des pare-feu et des réseaux privés virtuels.</p><p>L’exercice clos le 31 juillet 2026 a apporté 3,35 Md$ de revenus, en hausse de 25 %. Le rachat de Red Canary, 651,4 M$ en numéraire en août 2025, a ajouté un service de détection et de réponse : hors cette acquisition, la croissance tombe à 20 %, et les revenus récurrents annualisés à 3 630 M$. La prévision de l’exercice 2027, 16,6 à 17,5 %, confirme un ralentissement que la société ne cache pas.</p><p>Les ventes passent à 85 % par des partenaires de distribution ; un seul d’entre eux porte 13 % des créances. Aucun client ne pèse 10 % des revenus. En parallèle, la société a lancé le 1er septembre une réduction d’environ 3 % des effectifs pour réaffecter des moyens vers l’IA, et ses investissements du quatrième trimestre ont triplé.</p>',
        moat: 'L’avantage tient à la taille du réseau : plus de 200 centres de données reliés aux grands points d’échange d’internet, et un volume de transactions qui nourrit les modèles de détection. Il résiste bien aux petits concurrents, moins bien aux plateformes qui vendent l’accès sécurisé avec le pare-feu et l’identité dans le même contrat.',
        segments: [
          { name: 'Accès sécurisé des utilisateurs', revenue: 'Majorité des revenus', pct: 'Non ventilé', description: 'Cœur historique, vendu au nombre d’utilisateurs.' },
          { name: 'Données, opérations de sécurité et IA', revenue: 'Part croissante', pct: 'Non ventilé', description: 'Produits hors facturation par utilisateur, dont Red Canary.' }],
        sourceRefs: [ref(0), ref(1)],
        coverageMatrix: [
          { facet: 'Cours et historique', status: 'COUVERT', decision: 'Trois cents séances continues, close certifié ; base des supports et résistances.' },
          { facet: 'Résultats et guidance', status: 'COUVERT — PRIMAIRE', decision: 'Communiqué du 3 septembre et 10-K ; prochaine date non annoncée.' },
          { facet: 'Capital et dette', status: 'COUVERT — PRIMAIRE', decision: 'Obligations 2028 loin de leur prix de conversion ; plans salariés séparés.' },
          { facet: 'Agrégats GAAP', status: 'COUVERT — XBRL', decision: 'Exercice clos le 31 juillet 2026 lu dans les données XBRL officielles.' },
          { facet: 'Comparables et transmission', status: 'COUVERT — LOCAL', decision: 'Corrélations recalculées sur barres certifiées depuis la fin mars.' },
          { facet: 'Initiés', status: 'PARTIEL', decision: 'Ventes de dirigeants en septembre ; couverture officielle incomplète.' },
          { facet: 'Options', status: 'NON EXPLOITABLE', decision: 'Chaîne relevée en séance le 24 septembre, non rattachée à la clôture de référence.' }] },
      news: [
        { date: '2026-09-04', title: 'Première séance après le communiqué : ' + fr(pct(d0904[4], p0904[4]), 1) + ' %', impact: 'negative', detail: 'Ouverture à ' + usd(d0904[1]) + ', ' + fr(Math.abs(pct(d0904[1], p0904[4])), 2) + ' % sous la clôture de la veille, clôture à ' + usd(d0904[4]) + '. CIBR a perdu 0,77 % le même jour : environ ' + fr(Math.abs(pct(d0904[4], p0904[4])) - 0.77, 1) + ' points du repli reviennent au titre, après une prévision 2027 à +17 %.', source: 'Barres certifiées', sourceUrl: c.evidenceUrl },
        { date: '2026-09-14', title: 'Rebond de ' + fr(pct(d0914[4], p0914[4]), 1) + ' % avec tout le secteur', impact: 'positive', detail: 'Ouverture à ' + usd(d0914[1]) + ' (+' + fr(pct(d0914[1], p0914[4]), 2) + ' %), clôture à ' + usd(d0914[4]) + '. CIBR a pris 5,99 % la même séance ; aucun dépôt ouvert ici n’explique le mouvement, commun à tout le panier de cybersécurité.', source: 'Barres certifiées', sourceUrl: c.evidenceUrl },
        { date: '2026-09-03', title: 'Réduction d’environ 3 % des effectifs', impact: 'neutral', detail: '30,0 à 33,0 M$ de charges, surtout au premier semestre de l’exercice 2027, pour réaffecter des moyens vers l’IA.', source: 'Zscaler — SEC', sourceUrl: docs[2].url }],
      fundamentals: { rows: [
          { metric: 'Revenus du quatrième trimestre', value: '898,2 M$', signal: '+25 % sur un an, communiqué du 3 septembre', signalColor: 'green', _src: 1 },
          { metric: 'Revenus récurrents annualisés', value: '3 771 M$', signal: '+25 % ; 3 630 M$ et +20 % hors Red Canary', signalColor: 'green', _src: 1 },
          { metric: 'Prévision de revenus de l’exercice 2027', value: '3,908 à 3,938 Md$', signal: '+16,6 à 17,5 % ; premier trimestre attendu entre 935 et 939 M$', signalColor: 'amber', _src: 1 },
          { metric: 'Flux libre du quatrième trimestre', value: '60,8 M$', signal: 'Contre 171,9 M$ un an plus tôt ; 218,5 M$ d’investissements', signalColor: 'red', _src: 1 },
          { metric: 'Contrats restant à exécuter', value: '7 365 M$', signal: '45 % à reconnaître sur douze mois, au 31 juillet 2026', signalColor: 'green', _src: 0 },
          { metric: 'Revenus GAAP de l’exercice', value: fr(G$.rev / 1e9, 2) + ' Md$', signal: 'Exercice clos le 31 juillet 2026 (XBRL SEC)', signalColor: 'blue', _src: 'gaap' },
          { metric: 'Résultat opérationnel GAAP de l’exercice', value: fr(G$.ebit / 1e6, 1) + ' M$', signal: 'Perte, contre 128,5 M$ un an plus tôt', signalColor: 'red', _src: 'gaap' },
          { metric: 'Résultat net GAAP de l’exercice', value: fr(G$.ni / 1e6, 1) + ' M$', signal: 'Perte nette de l’exercice clos le 31 juillet 2026', signalColor: 'red', _src: 'gaap' },
          { metric: 'Flux de trésorerie opérationnel de l’exercice', value: fr(G$.ocf / 1e9, 2) + ' Md$', signal: '34 % des revenus ; flux libre publié de 779,1 M$', signalColor: 'green', _src: 'gaap' },
          { metric: 'Obligations 2028 au 31 juillet 2026', value: fr(g.notes.value / 1e9, 2) + ' Md$', signal: 'Valeur comptable pour 1 725 M$ de nominal, incluse dans la valeur d’entreprise', signalColor: 'amber', _src: 'gaap' },
          { metric: 'Liquidités et placements au 31 juillet 2026', value: fr(G$.cash / 1e9, 2) + ' Md$', signal: 'Trésorerie et placements à court terme', signalColor: 'blue', _src: 'gaap' },
          { metric: 'EV/revenus GAAP', value: fr(evRev, 1) + '×', signal: 'Valeur d’entreprise au close du 2026-09-23 sur revenus GAAP de l’exercice clos le 2026-07-31', signalColor: 'amber', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus CrowdStrike à ' + fr(crwd, 1) + '×, Cloudflare à ' + fr(net, 1) + '× et Fortinet à ' + fr(ftnt, 1) + '× (statistiques courantes du 24 septembre, non point-in-time) : le marché fait déjà payer le ralentissement.', _src: 'market', _peers: ['CRWD', 'NET', 'FTNT'], _peerField: 'enterpriseToRevenue' },
          { metric: 'EV sur revenus prévus pour 2027', value: fr(evFwd, 1) + '×', signal: 'Valeur d’entreprise au close du 2026-09-23 sur le milieu de la prévision de la société (3,923 Md$)', signalColor: 'blue', source: 'Clôture certifiée, XBRL SEC et communiqué du 3 septembre', comparison: 'Versus le multiple courant : la prévision tenue ramènerait le titre sous neuf fois ses revenus.', _src: 'market' },
          { metric: 'EV/revenus — scénario de compression (hypothèse éditoriale)', value: fr(scn.price, 2) + ' $ par action', signal: 'Scénario : multiple ramené à sept fois les revenus GAAP de l’exercice par hypothèse, obligations et liquidités du 2026-07-31 inchangées, soit ' + fr(scn.downside_pct, 0) + ' % sous le close du 2026-09-23', signalColor: 'red', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus le close : sept fois les revenus, c’est à peu près là où cotait le titre début septembre, avant le rebond ; ce que coûterait un retour, pas un objectif.', _src: 'market' }],
        sourceRefs: [ref(0), ref(1), market('fondamentaux et statistiques')] },
      earnings: { quarters: [],
        beatNote: 'Quatrième trimestre de l’exercice 2026 : revenus de 898,2 M$ (+25 %), perte opérationnelle GAAP de 15,5 M$ et résultat opérationnel ajusté record de 218,4 M$, 24 % des revenus. Le bénéfice ajusté atteint 1,19 $ par action. La guidance de l’exercice 2027 vise 3,908 à 3,938 Md$ de revenus (+16,6 à 17,5 %), des revenus récurrents de 4,396 à 4,426 Md$ et un bénéfice ajusté de 4,86 à 4,90 $ par action sur environ 173 millions d’actions diluées. La date du premier trimestre reste non annoncée par la société.',
        nextEarnings: 'Date non annoncée par l’émetteur ; aucune publication dans les quatorze jours du calendrier collecté.',
        sourceRefs: [ref(1)] },
      capitalStructure: { sharesOutstanding: '163 054 698 actions au 27 août 2026 (page de garde du 10-K)',
        sharesAuthorized: 'Actions autorisées non reprises : non décisionnel pour ce dossier.', dilutionRisk: 'low',
        shareHistory: 'Base retenue : actions émises et en circulation au bilan. Elles passent de 158,3 millions au 31 juillet 2025 à 163,1 millions un an plus tard, soit 3,0 % de plus, sous l’effet de la rémunération en actions ; les rachats de 2026 (Red Canary, Symmetry Systems) ont été payés en numéraire, avec quelques milliers d’actions différées pour des salariés clés. Passage au nombre dilué : la guidance retient environ 173 millions d’actions diluées pour l’exercice 2027. Les obligations 2028, 1 725 M$ de nominal, ne se convertissent qu’à 439,52 $ par action, plus du double du cours ; les 3,9 millions d’actions potentielles restent hors du nombre dilué tant que le titre en est aussi loin. Aucun programme d’émission sur le marché n’est relevé.',
        warrants: [], atm: { active: false, authorized: 'Aucun programme d’émission d’actions sur le marché relevé', used: 'Sans objet', remaining: 'Sans objet' },
        sourceRefs: [ref(0), ref(3)] },
      filingsReview: { summary: 'Quatre dépôts décisionnels ouverts et hachés, tous datés du 3 septembre. Ils décrivent une société rentable en trésorerie, sans dilution notable, dont la croissance ralentit et dont les investissements augmentent au moment même où elle réduit ses effectifs.',
        filings: docs.map(d => ({ date: d.date, form: d.form, accession: d.accession, finding: d.finding, url: d.url })),
        contrarianRisks: [
          'La prévision 2027 à +17 % inclut déjà une année pleine d’acquisitions : la croissance interne pourrait être plus proche de 15 %.',
          'Le triplement des investissements du quatrième trimestre réduit le flux libre au moment où la croissance ralentit.',
          'Les plateformes qui vendent pare-feu, accès sécurisé et identité ensemble peuvent casser les prix de l’accès sécurisé seul.',
          'Le rebond de septembre suit le secteur ; un repli du panier le reprendrait sans nouvelle propre.'] },
      technicals: { rsi14: +tech.rsi14.toFixed(2), macd: +tech.macd.toFixed(2), macdSignal: +tech.macdSignal.toFixed(2), ema20: +tech.ema20.toFixed(2), ema50: +tech.ema50.toFixed(2), ema200: +tech.ema200.toFixed(2),
        ma50Type: 'EMA', ma200Type: 'EMA', ma50Available: true, ma200Available: true, atr14: +tech.atr14.toFixed(2),
        badges: [sgn(run, 0) + ' depuis le 8 septembre', fr(ext20, 0) + ' % au-dessus de la moyenne à vingt séances', 'Résistances de janvier à 229 et 231 $'],
        supports: [lv('s1'), lv('s2'), lv('s3')], resistances: [lv('r1'), lv('r2'), lv('r3')],
        setupNote: 'Le titre clôture à ' + usd(close) + ', au-dessus de ses moyennes à vingt, cinquante et deux cents séances, avec un RSI à ' + fr(tech.rsi14, 1) + '. Supports : ' + usd(lv('s1')) + ', bas du 23 septembre, ' + usd(lv('s2')) + ', bas du 22, et ' + usd(lv('s3')) + ', bas du 18. Résistances : ' + usd(lv('r1')) + ', puis ' + usd(lv('r2')) + ', plus haut du 27 janvier, et ' + usd(lv('r3')) + ', plus haut du 7 janvier. Un achat sur cassure de ' + usd(bo.e) + ' avec un stop sous ' + usd(bo.s) + ' ne viserait que ' + usd(bo.t) + ' : R/R de ' + fr(bo.rr, 2) + ', insuffisant. Ce stop sous le bas du 22 septembre est à ' + fr((bo.e - bo.s) / tech.atr14, 2) + ' ATR du déclencheur ; un stop sous le bas du 23, ' + usd(lv('s1')) + ', donnerait un R/R de ' + fr((bo.t - bo.e) / (bo.e - lv('s1')), 2) + ' mais à ' + fr((bo.e - lv('s1')) / tech.atr14, 2) + ' ATR seulement, dans le bruit d’une séance ordinaire : le plus proche des stops à plus d’un ATR ne suffit pas. Le plan archivé du 27 août n’est plus pertinent : tous ses niveaux sont sous le cours.',
        wyckoff: 'Non utilisé : le profil de volume n’est pas exploité dans ce dossier.',
        sourceRefs: [market('barres quotidiennes et indicateurs recalculés')] },
      options: { callOI: 'Non exploitable', putOI: 'Non exploitable', cpRatio: 'Non exploitable', maxPain: 'Non exploitable', ivMean: 'Non exploitable', skew: 'Chaîne relevée en séance le 24 septembre, non rattachée à la clôture de référence', unusual: 'Aucune activité inhabituelle qualifiée', sourceRefs: [market('options')] },
      shortInterest: { siPct: fr(st.shortPercentOfFloat * 100, 2) + ' % du flottant', daysToCover: fr(st.shortRatio, 2) + ' jours, date de règlement non précisée par le snapshot', ctb: 'Coût d’emprunt non retenu comme signal', trend: 'Positions vendeuses modérées ; elles ont pu nourrir le rebond, sans mesure qui le prouve.', squeezeScore: 'Non pertinent', sourceRefs: [market('positions vendeuses')] },
      insiders: { signal: 'Ventes uniquement dans la fenêtre relevée, du 16 au 21 septembre, aucun achat. Le 16 septembre, le directeur général, le directeur financier, le directeur commercial, le directeur des produits et le directeur juridique ont vendu au même prix, 192,76 $, le lendemain d’attributions d’actions : un schéma compatible avec des ventes destinées à couvrir l’impôt, que les déclarations relevées ne qualifient pas. Couverture officielle partielle : aucun solde net publié.',
        recentTransactions: [],
        sourceRefs: [market('formulaires 4')] },
      macro: { indicators: [{ name: 'Clôture de référence', value: c.REF, signal: usd(close) + ', séance complète' }, { name: 'Rendement cinq séances', value: sgn(ret(5)), signal: 'Descriptif' }, { name: 'Rendement vingt et une séances', value: sgn(ret(21)), signal: 'Descriptif' }],
        regime: 'neutral', impact: 'Les budgets de sécurité tiennent mieux que le reste du logiciel en ralentissement, mais Zscaler a surtout profité d’un retour des acheteurs sur tout le secteur en septembre. Son sort à court terme dépend plus du panier de cybersécurité que de l’économie.' },
      risks: { riskScore: 6, riskProfile: 'High',
        riskSummary: 'Le risque de Zscaler au cours actuel n’est pas sa survie ni sa trésorerie : c’est d’acheter un rebond de ' + sgn(run, 0) + ' en onze séances, construit sur le mouvement du secteur, alors que la société annonce elle-même une croissance ramenée à 17 %. Les résistances de janvier sont proches ; les supports solides sont loin.',
        riskCards: [
          { title: 'Croissance en ralentissement', severity: 'high', icon: 'fa-arrow-trend-down', points: ['Prévision 2027 de +16,6 à 17,5 %.', 'Croissance hors Red Canary de 20 % sur l’exercice.'], verdict: 'Chaque trimestre sera jugé sur la pente de ce ralentissement, pas sur le niveau absolu des revenus.' },
          { title: 'Titre étiré à court terme', severity: 'high', icon: 'fa-gauge-high', points: [fr(ext20, 1) + ' % au-dessus de la moyenne à vingt séances.', 'RSI à ' + fr(tech.rsi14, 1) + '.'], verdict: 'Un simple retour vers la moyenne à vingt séances coûterait plus de dix pour cent à un acheteur du jour.' },
          { title: 'Flux libre sous pression', severity: 'medium', icon: 'fa-money-bill-wave', points: ['60,8 M$ au quatrième trimestre, contre 171,9 M$.', '218,5 M$ d’investissements au trimestre.'], verdict: 'Si les investissements restent à ce niveau, la marge de flux libre de 23 % visée pour 2027 devient exigeante.' },
          { title: 'Concurrence des plateformes', severity: 'medium', icon: 'fa-layer-group', points: ['Palo Alto Networks vend l’accès sécurisé avec pare-feu et identité.', 'Aucun client à 10 % : pas de dépendance, mais pas d’ancrage non plus.'], verdict: 'La pression sur les prix viendra des offres groupées, plus que des petits spécialistes du même segment.' }],
        pedagogy: 'Quand un titre reprend 30 % en deux semaines, la question n’est pas de savoir s’il est « bon marché » face à ses pairs, mais où se trouvent le prochain vendeur et le prochain acheteur. Ici, les vendeurs de janvier attendent vers 229 et 231 $ ; les acheteurs du 14 septembre sont plus bas, vers 192 $. Acheter au milieu, c’est prendre le risque le plus long pour le gain le plus court. Un gap à l’ouverture, ce saut de cours d’une séance à l’autre, peut effacer en une fois le gain espéré, comme le 4 septembre ; le slippage, l’écart entre prix voulu et prix obtenu, reste faible sur un titre aussi liquide. Si une position existe déjà, sa taille doit supposer un retour vers la moyenne à vingt séances. Attendre n’est pas une perte : c’est refuser un mauvais rapport entre les deux.' },
      tradeIdea: { status: 'no-trade', archiveReferenceClose: archive.meta.levelsCloseDate,
        statusNote: 'Aucun plan. Les niveaux affichés sont ceux, archivés, du dossier du 27 août, neutralisés par la publication du 3 septembre : ils n’ont jamais été activés et aucun ordre n’y est attaché. Un nouveau plan ne sera construit que sur un repli tenu vers ' + usd(lv('s3')) + '–' + usd(lv('s2')) + ' ou sur une clôture au-dessus de ' + usd(lv('r3')) + '.',
        entry, stop, tp1, tp2,
        stopPct: pct(stop, entry).toFixed(1) + '%', tp1Pct: '+' + pct(tp1, entry).toFixed(1) + '%', tp2Pct: '+' + pct(tp2, entry).toFixed(1) + '%',
        rr: '1:' + rr1.toFixed(2) + ' TP1 / 1:' + rr2.toFixed(2) + ' TP2',
        entryNote: 'Niveaux historiques affichés pour mémoire, non exécutables : le cours actuel est au-dessus de tous. Un achat sur cassure du plus haut du 23 septembre, ' + usd(bo.e) + ', avec un stop sous ' + usd(bo.s) + ', risquerait ' + usd(bo.e - bo.s) + ' pour viser la résistance de ' + usd(bo.t) + ' : R/R de ' + fr(bo.rr, 2) + ', sous le minimum de 1,5. Liquidité : environ ' + fr(adv / 1e6, 0) + ' M$ échangés par séance, médiane des vingt dernières.',
        horizon: 'Aucun horizon : pas de plan au cours actuel',
        thesis: 'Le marché a vendu la prévision 2027 puis racheté tout le secteur de la cybersécurité : Zscaler a suivi, plus fort que CIBR, sans nouvelle propre depuis le 3 septembre. La valorisation n’est pas excessive face aux pairs, mais le point d’entrée l’est : le titre est étiré et la première résistance est à portée. Aucun ordre : attendre un repli qui tienne au-dessus du bas du 18 septembre, ou une sortie au-dessus des plus hauts de janvier, puis reconstruire des niveaux.',
        catalysts: ['Un repli vers ' + usd(lv('s3')) + '–' + usd(lv('s2')) + ' qui tienne en clôture, avec un volume en baisse.', 'Une clôture au-dessus de ' + usd(lv('r3')) + ', plus haut du 7 janvier, qui dégagerait la résistance.', 'Aucune publication de la société ni d’un comparable dans les quatorze jours du calendrier collecté : le risque de gap vient du secteur, comme le 14 septembre.'],
        invalidation: ['Toute entrée au cours actuel contredit ce dossier.', 'Une clôture sous ' + usd(lv('s3')) + ' effacerait le rebond du 14 septembre et repousserait tout plan.', 'Une nouvelle acquisition payée en actions changerait la lecture de la dilution.'] },
      globalScore: { profile: 'Leader de l’accès sécurisé en ralentissement, titre étiré',
        keyTakeawaysPositive: ['Revenus récurrents de 3 771 M$, +25 %.', 'Flux opérationnel de 34 % des revenus.', 'Moins cher que ses grands pairs en multiple de revenus.'],
        keyTakeawaysNegative: ['Prévision 2027 à +17 %.', 'Titre à plus de 13 % au-dessus de sa moyenne à vingt séances.', 'Flux libre du trimestre écrasé par les investissements.'],
        mindsetTip: 'Un bon dossier et un bon point d’entrée sont deux choses différentes : la première se juge sur les comptes, la seconde sur la distance au prochain support.' },
      social: { platforms: [], sourceRefs: [market('sentiment non retenu faute de mesure qualifiée')] },
      disclaimer: 'Document de recherche éducatif. Ni conseil financier, ni signal de trading. Aucun plan actif : les niveaux affichés sont historiques.',
    };
  },
  groups: [
    { name: 'Référence du secteur', order: 1, transmission: 'Plateforme concurrente qui vend l’accès sécurisé avec le pare-feu et l’identité.', rows: [
      ['PANW', 'leader', 'Plateforme de sécurité la plus large', 'Son offre groupée d’accès sécurisé concurrence frontalement Zscaler ; ses prévisions donnent le ton du secteur.']] },
    { name: 'Pairs directs de la cybersécurité', order: 1, transmission: 'Même budget de sécurité des entreprises.', rows: [
      ['CRWD', 'direct_peer', 'Protection des postes et plateforme cloud', 'Concurrent sur les opérations de sécurité, terrain de Red Canary ; le titre le plus suivi du secteur.'],
      ['FTNT', 'direct_peer', 'Pare-feu et réseau sécurisé', 'Défend le pare-feu physique que Zscaler cherche à remplacer ; son cycle matériel mesure cette résistance.'],
      ['NET', 'direct_peer', 'Réseau et sécurité en périphérie', 'Seul autre grand réseau mondial de sécurité en nuage : concurrent le plus proche de l’architecture de Zscaler.'],
      ['OKTA', 'direct_peer', 'Gestion des identités en nuage', 'Partenaire fréquent sur l’identité, dont la santé conditionne l’accès fondé sur l’utilisateur.'],
      ['S', 'direct_peer', 'Protection des postes de travail', 'Concurrent plus petit en opérations de sécurité ; sa croissance montre la pression sur les prix.'],
      ['CHKP', 'direct_peer', 'Pare-feu d’entreprise rentable', 'Pair rentable et bien moins cher : l’écart de multiple mesure la prime de croissance restante.'],
      ['CSCO', 'direct_peer', 'Réseau et sécurité d’entreprise', 'Concurrent sur l’accès sécurisé intégré au réseau des sites et des campus.']] },
    { name: 'Amont : infrastructure du nuage de sécurité', order: 1, transmission: 'Catégories de fournisseurs décrites par le 10-K sans nom : points d’interconnexion, équipements de centres de données, grands clouds.', rows: [
      ['EQIX', 'upstream', 'Exploitant de points d’interconnexion', 'Catégorie de fournisseur décrite par le 10-K, qui place ses centres dans les grands points d’échange ; Equinix n’y est pas nommé.'],
      ['ANET', 'upstream', 'Commutateurs de centres de données', 'Catégorie d’équipement que Zscaler achète sur commande, selon le 10-K ; Arista n’y est pas nommé comme fournisseur.'],
      ['MSFT', 'upstream', 'Cloud Azure et suite de sécurité', 'Le 10-K cite les fournisseurs de cloud public parmi les concurrents potentiels ; Microsoft vend aussi son propre accès sécurisé.'],
      ['AMZN', 'upstream', 'Cloud AWS et outils de sécurité natifs', 'Fournisseur de cloud public relié aux centres de Zscaler et concurrent potentiel cité comme catégorie par le 10-K.'],
      ['GOOGL', 'upstream', 'Google Cloud et sécurité intégrée', 'Même rôle de fournisseur de cloud public et de concurrent potentiel, catégorie citée par le 10-K.']] },
    { name: 'Segments voisins', order: 2, transmission: 'Budgets adjacents que la plateforme cherche à élargir.', rows: [
      ['TENB', 'second_order', 'Gestion des vulnérabilités et expositions', 'Segment voisin ; ses prévisions mesurent l’appétit des entreprises pour la gestion d’exposition.'],
      ['RBRK', 'second_order', 'Protection et restauration des données', 'Budget de cyber-résilience adjacent, arbitré dans les mêmes comités d’achat que la sécurité des données.'],
      ['QLYS', 'second_order', 'Analyse des vulnérabilités en nuage', 'Pair rentable d’un segment voisin, dont la croissance lente montre le sort d’un produit isolé.'],
      ['DDOG', 'second_order', 'Plateforme d’observabilité cloud', 'Les données de sécurité et d’observabilité se rapprochent ; ses prévisions mesurent les budgets cloud des entreprises.'],
      ['NOW', 'second_order', 'Automatisation des processus d’entreprise', 'Concurrent sur l’automatisation des opérations, terrain des agents d’IA que Zscaler veut sécuriser.']] },
    { name: 'Contrôles sectoriels', order: 2, transmission: 'Paniers de référence pour isoler ce qui est propre à Zscaler.', rows: [
      ['CIBR', 'sector_proxy', 'Panier de cybersécurité pondéré', 'Un écart de performance avec ce panier isole ce qui est propre à Zscaler, en septembre comme sur l’année.'],
      ['HACK', 'sector_proxy', 'Panier de cybersécurité plus équipondéré', 'Montre si le secteur monte sans les géants, donc si la hausse est large ou concentrée.'],
      ['IGV', 'sector_proxy', 'Panier de logiciels américains', 'Contrôle large du logiciel : un mouvement commun avec ce panier n’a rien de spécifique au titre.']] },
  ],
  eventDefault: { leader: 'Aucune publication dans les quatorze jours collectés ; sa prochaine prévision donnera le ton du secteur', direct_peer: 'Aucune publication dans les quatorze jours collectés ; ses annonces de prix ou de produits peuvent déplacer les parts de marché', upstream: 'Aucune publication dans les quatorze jours collectés ; ses offres de sécurité intégrée restent à suivre', second_order: 'Aucune publication dans les quatorze jours collectés ; ses prévisions éclairent un segment voisin', sector_proxy: 'Panier sans publication propre ; exposé aux résultats de ses grandes pondérations' },
  eventRisk: {},
  blastDoc: 0,
  scenarios: c => [
    { scenario: 'bullish', trigger: 'Le secteur prolonge sa hausse et la société relève sa prévision au premier trimestre.', firstOrder: 'Le titre franchit les plus hauts de janvier et sort de sa zone de résistance.', secondOrder: 'Cloudflare et Palo Alto Networks suivent ; CIBR confirme.', confirmation: 'Une clôture au-dessus de ' + c.usd(c.lv('r3')) + ' avec CIBR en hausse la même séance.', contradiction: 'Un franchissement pendant que CIBR recule.' },
    { scenario: 'mixed', trigger: 'Le secteur marque une pause après son rebond de septembre.', firstOrder: 'Le titre consolide entre le bas du 18 septembre et les résistances de janvier.', secondOrder: 'L’écart de performance avec CIBR se referme et les pairs les plus chers reprennent la main.', confirmation: 'Des clôtures entre ' + c.usd(c.lv('s3')) + ' et ' + c.usd(c.lv('r2')) + ' pendant plusieurs séances.', contradiction: 'Une sortie franche d’un côté ou de l’autre.' },
    { scenario: 'bearish', trigger: 'Rotation hors des logiciels ou pression tarifaire des plateformes groupées.', firstOrder: 'Le titre repasse sous le bas du 18 septembre et efface le rebond du 14.', secondOrder: 'Les pairs les plus chers reculent davantage ; CIBR suit.', confirmation: 'Une clôture sous ' + c.usd(c.lv('s3')) + ' avec CIBR en baisse.', contradiction: 'Un repli du secteur que le titre ne suit pas.' }],
  contradictions: c => ['La société annonce un ralentissement, mais le titre a pris ' + c.fr(c.ret(21) - c.M.CIBR.return21d, 1) + ' points de plus que CIBR sur vingt et une séances : tout se passe comme si le marché jugeait la prévision prudente.', 'Une corrélation élevée avec un pair ne prouve pas un lien commercial ; les fournisseurs d’infrastructure ne sont pas nommés.'],
  missingData: c => ['Aucun client ne dépasse 10 % des revenus et les partenaires de distribution ne sont pas nommés : aucun client coté n’entre dans les comparables comme client documenté.', 'Fournisseurs d’infrastructure décrits par catégorie, sans nom : Equinix et Arista illustrent ces catégories sans être des fournisseurs documentés.', 'Chaîne d’options relevée en séance, non rattachée à la clôture ; sentiment non retenu.', 'Barres d’une source de repli pour toutes les séries.'],
  limitations: ['Barres d’une source de repli (Webull).', 'Options non rattachées à la clôture de référence.', 'Fournisseurs d’infrastructure non nommés.'],
});
