const fs = require('fs');
const path = require('path');

const root = __dirname;
const data = JSON.parse(fs.readFileSync(path.join(root, '_data/summary.json'), 'utf8'));
const json = JSON.stringify(data).replace(/</g, '\\u003c');

const html = `<!doctype html>
<html lang="fr" data-tags="us,tech,software,volume,formation" data-tab="daily">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>${data.title} | DailyTickers</title>
  <meta name="description" content="Étude du volume de ServiceNow : régime long, participation récente, réactions aux résultats et comparaison aux pairs du logiciel.">
  <link rel="icon" href="/favicon.ico">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
  <link rel="stylesheet" href="/assets/report.css">
  <script src="https://cdn.jsdelivr.net/npm/echarts@5.4.3/dist/echarts.min.js"></script>
  <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f)})(window,document,'script','dataLayer','GTM-T5Z595CW');</script>
  <style>
    :root{--ink:#101828;--muted:#526174;--line:#d9e1ea;--blue:#1667c5;--green:#087a55;--amber:#a15c00;--red:#b42318;--surface:#fff;--soft:#f5f7fa}
    body{background:#f7f8fa;color:var(--ink)}
    .hero-section{padding:48px 20px 34px;background:#fff;border-bottom:1px solid var(--line)}
    .hero-section .container,.report-shell{max-width:1120px;margin:0 auto}
    .hero-date{font-size:.78rem;font-weight:800;color:var(--blue);text-transform:uppercase;margin-bottom:12px}
    .hero-title{max-width:920px;margin:0;font-size:clamp(2rem,4vw,3.4rem);line-height:1.04;letter-spacing:0}
    .hero-subtitle{max-width:820px;margin:18px 0 0;color:var(--muted);font-size:1.05rem;line-height:1.65}
    .hero-badges{display:flex;gap:8px;flex-wrap:wrap;margin-top:20px}
    .hero-badge{padding:6px 10px;border:1px solid var(--line);border-radius:6px;background:#fff;font-size:.78rem;font-weight:750}
    .report-shell{padding:28px 20px 72px}
    .decision-strip{display:grid;grid-template-columns:1.5fr repeat(4,minmax(0,1fr));border:1px solid var(--line);background:#fff;border-radius:8px;overflow:hidden}
    .decision-main,.decision-cell{padding:18px;border-right:1px solid var(--line)}
    .decision-cell:last-child{border-right:0}.eyebrow{font-size:.68rem;font-weight:800;color:#667085;text-transform:uppercase;margin-bottom:7px}
    .decision-main strong{font-size:1.1rem}.decision-main p{margin:8px 0 0;color:var(--muted);line-height:1.45;font-size:.9rem}
    .state{display:block;font-weight:850}.state.good{color:var(--green)}.state.warn{color:var(--amber)}.state.bad{color:var(--red)}
    .section{margin-top:30px;padding:28px;background:#fff;border:1px solid var(--line);border-radius:8px}
    .section h2{margin:0 0 8px;font-size:1.55rem;letter-spacing:0}.section-lead{margin:0 0 22px;color:var(--muted);line-height:1.6;max-width:900px}
    .kpi-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}
    .kpi{padding:16px;background:var(--soft);border-left:3px solid var(--blue)}.kpi strong{display:block;font-size:1.45rem}.kpi span{display:block;color:var(--muted);font-size:.78rem;margin-top:5px;line-height:1.35}
    .chart-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:18px}.chart-panel{border:1px solid var(--line);border-radius:7px;padding:16px;min-width:0}.chart-panel h3{font-size:.95rem;margin:0 0 4px}.chart-note{font-size:.76rem;color:var(--muted);margin:0 0 10px}.chart{height:350px;width:100%}
    .full-chart{margin-top:18px}.full-chart .chart{height:330px}
    .read-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.read{padding:18px;border-top:3px solid var(--blue);background:var(--soft)}.read h3{margin:0 0 10px;font-size:1rem}.read p{margin:0;color:var(--muted);line-height:1.55;font-size:.9rem}
    .split-evidence{display:grid;grid-template-columns:minmax(0,1.2fr) minmax(280px,.8fr);gap:18px;align-items:start}.evidence-list{display:grid;gap:10px}.evidence-row{padding:14px 16px;border-left:3px solid #94a3b8;background:var(--soft)}.evidence-row.good{border-color:var(--green)}.evidence-row.warn{border-color:var(--amber)}.evidence-row.bad{border-color:var(--red)}.evidence-row strong{display:block;font-size:.9rem}.evidence-row p{margin:5px 0 0;color:var(--muted);font-size:.82rem;line-height:1.45}
    .checklist{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.check{display:grid;grid-template-columns:24px 1fr;gap:10px;padding:14px;border:1px solid var(--line);border-radius:6px}.check i{margin-top:2px}.check strong{display:block;font-size:.9rem}.check p{margin:4px 0 0;color:var(--muted);font-size:.82rem;line-height:1.45}
    .source-list{margin:0;padding-left:20px;color:var(--muted);line-height:1.65;font-size:.84rem}.source-list strong{color:var(--ink)}
    .fnav-menu{max-height:70vh;overflow:auto}
    @media(max-width:900px){.decision-strip{grid-template-columns:1fr 1fr}.decision-main{grid-column:1/-1}.decision-main,.decision-cell{border-bottom:1px solid var(--line)}.chart-grid,.split-evidence{grid-template-columns:1fr}.read-grid{grid-template-columns:1fr}.chart{height:310px}}
    @media(max-width:640px){.hero-section{padding:34px 16px 26px}.hero-title{font-size:2rem}.report-shell{padding:18px 12px 60px}.section{padding:20px 14px}.decision-strip,.kpi-grid,.checklist{grid-template-columns:1fr}.decision-main{grid-column:auto}.decision-main,.decision-cell{border-right:0}.kpi-grid{gap:8px}.chart-panel{padding:12px}.chart{height:290px}.full-chart .chart{height:300px}}
  </style>
</head>
<body>
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-T5Z595CW" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<nav class="brand-bar"><div class="brand-bar-inner"><a href="/" class="brand-logo"><img src="/logo.svg" alt="" width="36" height="36"><span class="brand-title">DailyTickers</span></a><div class="brand-nav"><a href="/?tab=weekly">Hebdo</a><a href="/?tab=daily">Daily</a><a href="/?tab=analyses">Analyses</a><a href="/?tab=scanner">Scanner</a><a href="/?tab=radar">Radar</a><a href="/?tab=series">Séries</a></div><div class="brand-actions"><a href="/" class="brand-home-btn" title="Accueil"><i class="fas fa-house"></i></a></div></div></nav>
<header class="hero-section"><div class="container"><div class="hero-date">Étude spéciale · clôture du 28 août 2026</div><h1 class="hero-title">NOW : le volume confirme le rebond, pas encore une accumulation régulière</h1><p class="hero-subtitle">ServiceNow gagne 30,1 % en vingt séances. La dernière hausse est soutenue par les échanges, mais le volume moyen reste en contraction et la confirmation sectorielle est inégale.</p><div class="hero-badges"><span class="hero-badge">Données daily complètes</span><span class="hero-badge">RVOL 1,64x</span><span class="hero-badge">RSI 72,7</span><span class="hero-badge">8 réactions post-résultats auditées</span></div><div id="article-clickable-tags" class="card-tags"></div></div></header>
<main class="report-shell">
  <section class="decision-strip" id="executive-summary" data-quality="high" aria-label="Synthèse des contrôles">
    <div class="decision-main"><div class="eyebrow">Conclusion prioritaire</div><strong>Participation réelle, poursuite non encore prouvée</strong><p>Le prix et l'OBV progressent ensemble, mais la moyenne de volume recule. Le signal est un rebond concentré, pas une accumulation régulière.</p></div>
    <div class="decision-cell"><div class="eyebrow">Fraîcheur</div><span class="state good">VALIDÉE</span><small>Clôture complète du 28/08</small></div>
    <div class="decision-cell"><div class="eyebrow">Séance récente</div><span class="state good">CONFIRMÉE</span><small>RVOL 1,64x</small></div>
    <div class="decision-cell"><div class="eyebrow">Tendance volume</div><span class="state warn">EN BAISSE</span><small>-25,5 % vs 20j précédents</small></div>
    <div class="decision-cell"><div class="eyebrow">Timing</div><span class="state bad">ÉTENDU</span><small>RSI 72,7</small></div>
  </section>

  <section class="section" id="dashboard"><h2>Le diagnostic en quatre chiffres</h2><p class="section-lead">Ces mesures répondent à quatre questions distinctes : le dernier mouvement est-il participé, la liquidité progresse-t-elle dans la durée, les hausses dominent-elles les baisses et le prix surperforme-t-il son univers ?</p><div class="kpi-grid"><div class="kpi"><strong>1,64x</strong><span>Volume du 28 août / moyenne des 20 séances précédentes</span></div><div class="kpi"><strong>-25,5 %</strong><span>Moyenne 20 jours contre les 20 jours précédents</span></div><div class="kpi"><strong>2,29x</strong><span>Volume des séances haussières / baissières sur 20 jours</span></div><div class="kpi"><strong>+30,1 %</strong><span>Performance NOW sur 20 séances, contre +15,8 % pour IGV</span></div></div></section>

  <section class="section" id="regime"><h2>Le volume 2026 change de régime, puis ralentit</h2><p class="section-lead">Le volume moyen mensuel a presque triplé par rapport à 2024. Il a toutefois culminé en mai-juin 2026 et retombe à 18,2 millions en août. Le niveau structurel reste élevé, l'accélération récente n'est pas continue.</p><div class="chart-grid"><div class="chart-panel"><h3>Volume moyen mensuel</h3><p class="chart-note">Millions de titres par séance, septembre 2024 à août 2026.</p><div id="monthlyChart" class="chart"></div></div><div class="chart-panel"><h3>Prix et volume moyen des pairs</h3><p class="chart-note">À droite : meilleure performance 20j. En haut : accélération du volume moyen.</p><div id="peerChart" class="chart"></div></div></div><div class="chart-panel full-chart"><h3>Les plus fortes séances de volume sur un an</h3><p class="chart-note">La couleur indique le rendement de la séance. Les trois réactions de résultats 2026 ont été baissières.</p><div id="eventChart" class="chart"></div></div></section>

  <section class="section" id="performance"><h2>Huit mois de rupture, pas une tendance linéaire</h2><p class="section-lead">La hausse d'août intervient après une alternance de rallyes et de chutes très larges. Le volume élevé de 2026 accompagne donc un régime de repricing permanent : il augmente la conviction sur l'intensité des mouvements, pas leur stabilité.</p><div class="split-evidence"><div class="chart-panel"><h3>Rendements mensuels de NOW en 2026</h3><p class="chart-note">Variation de clôture à clôture, en pourcentage.</p><div id="returnChart" class="chart"></div></div><div class="evidence-list"><div class="evidence-row bad"><strong>Avril : -16,1 %</strong><p>Le plus gros mois de volume ne protège pas contre une baisse. L'intensité et la direction restent deux variables séparées.</p></div><div class="evidence-row good"><strong>Mai : +36,8 %</strong><p>La reprise s'accompagne du pic de volume mensuel à 30,8 millions de titres par séance.</p></div><div class="evidence-row warn"><strong>Août : +26,4 %</strong><p>Le prix accélère tandis que le volume moyen retombe à 18,2 millions. Le mouvement est puissant, mais moins largement alimenté qu'en mai.</p></div></div></div></section>

  <section class="section" id="interpretation"><h2>Ce que le volume dit, et ce qu'il ne dit pas</h2><div class="read-grid"><article class="read"><h3>1. Le rebond est crédible</h3><p>Le 28 août affiche 28,9 millions de titres, soit 1,64 fois la norme récente. Le ratio up/down de 2,29 et l'OBV calculé en hausse de 118 millions de titres confirment une demande nette sur vingt séances.</p></article><article class="read"><h3>2. L'accumulation n'est pas régulière</h3><p>La moyenne 20 jours baisse de 25,5 % et la moyenne 60 jours de 14,4 %. Une poignée de grosses séances explique une part importante du signal. Une vraie expansion durable demanderait plusieurs semaines de participation croissante.</p></article><article class="read"><h3>3. Le secteur confirme partiellement</h3><p>CRM et WDAY combinent hausse du prix et expansion du volume. ORCL, ADBE, MSFT, IGV et QQQ progressent avec un volume moyen en retrait. NOW surperforme, mais ne bénéficie pas d'une validation uniforme du logiciel.</p></article></div></section>

  <section class="section" id="earnings"><h2>Les résultats concentrent le risque</h2><p class="section-lead">Sur huit publications datées par les 8-K SEC, le mouvement absolu médian est de 10,7 %. Les trois réactions de 2026 ont été négatives et accompagnées d'un volume de 2,47 à 4,66 fois la normale. Un volume élevé après les résultats mesure la violence du repricing, pas sa direction.</p><div class="checklist"><div class="check"><i class="fas fa-circle-check" style="color:var(--green)"></i><div><strong>Qualité fondamentale</strong><p>Croissance du chiffre d’affaires 24 %, marge brute 74,8 % et consensus analystes Strong Buy.</p></div></div><div class="check"><i class="fas fa-triangle-exclamation" style="color:var(--amber)"></i><div><strong>Prix déjà exigeant</strong><p>Le cours 144,71 dépasse l'objectif moyen 142,23 et le RSI atteint 72,7.</p></div></div><div class="check"><i class="fas fa-circle-check" style="color:var(--green)"></i><div><strong>Structure reprise</strong><p>Le cours est au-dessus des EMA20 125,45, EMA50 116,67 et EMA200 127,40.</p></div></div><div class="check"><i class="fas fa-circle-xmark" style="color:var(--red)"></i><div><strong>Chasse interdite par la méthode</strong><p>Une extension de prix sans nouvelle expansion du volume dégrade le rendement/risque du point d'entrée.</p></div></div></div></section>

  <section class="section" id="contrarian"><h2>Verdict contrarien : trois erreurs à éviter</h2><p class="section-lead">La lecture haussière possède des preuves, mais elle devient fragile si l'on confond le rebond du prix, le niveau structurel de liquidité et la confirmation sectorielle.</p><div class="read-grid"><article class="read"><h3>« Le volume monte »</h3><p>Faux sur la fenêtre courte : le volume de la dernière séance est élevé, mais la moyenne 20 jours recule de 25,5 %. Le bon constat est « impulsion récente participée dans une tendance de volume encore décroissante ».</p></article><article class="read"><h3>« Les pairs confirment »</h3><p>Partiel seulement. CRM et WDAY montrent une expansion, tandis que l'ETF IGV affiche un ratio up/down inférieur à 1. La diffusion du rallye ne suffit pas à valider une accumulation sectorielle.</p></article><article class="read"><h3>« Le beat protège »</h3><p>Non. NOW a dépassé les estimations de BPA sur les quatre trimestres disponibles, mais ses trois réactions post-résultats 2026 ont baissé. La guidance et le prix payé dominent le simple beat.</p></article></div></section>

  <section class="section" id="trade"><h2>Cadre actionnable pour les prochaines séances</h2><div class="read-grid"><article class="read"><h3>Confirmation</h3><p>Conserver un biais constructif seulement si les replis restent au-dessus de l'EMA20 et si une nouvelle impulsion imprime un RVOL supérieur à 1,2 avec une clôture dans la moitié haute de la séance.</p></article><article class="read"><h3>Alerte</h3><p>Une hausse avec RVOL inférieur à 1,0, un ratio up/down qui repasse sous 1 ou un OBV qui diverge indiqueraient que la demande marginale s'épuise.</p></article><article class="read"><h3>Invalidation</h3><p>Une perte confirmée de l'EMA20 après une séance de distribution invaliderait la lecture de reprise. Ce seuil évolue et doit être recalculé, pas transformé en ordre statique.</p></article></div></section>

  <section class="section" id="sources"><h2>Sources, méthode et limites</h2><ul class="source-list"><li><strong>Marché :</strong> données DailyTickers, barres daily Yahoo complètes au 28 août 2026, qualité élevée, mode actuel.</li><li><strong>Résultats :</strong> réactions datées par les 8-K SEC Item 2.02 ; l’heure exacte de publication n'est pas déduite du filing.</li><li><strong>Calculs :</strong> moyennes, RVOL, ratio up/down et OBV recalculés localement à partir des barres, sans utiliser les facettes nulles.</li><li><strong>Limite :</strong> la facette intraday 15 minutes a échoué ; cette étude ne conclut rien sur VWAP, opening range ou microstructure.</li><li><strong>Interprétation :</strong> le volume confirme la participation, jamais la causalité ni la direction future.</li></ul></section>
</main>
<div class="fnav" id="floatingNav"><div class="fnav-menu" id="fnavMenu"><a href="#dashboard" class="fnav-item"><i class="fas fa-gauge"></i><span>Diagnostic</span></a><a href="#regime" class="fnav-item"><i class="fas fa-chart-column"></i><span>Régime</span></a><a href="#performance" class="fnav-item"><i class="fas fa-chart-line"></i><span>Performance</span></a><a href="#interpretation" class="fnav-item"><i class="fas fa-magnifying-glass-chart"></i><span>Lecture</span></a><a href="#earnings" class="fnav-item"><i class="fas fa-calendar-check"></i><span>Résultats</span></a><a href="#contrarian" class="fnav-item"><i class="fas fa-scale-balanced"></i><span>Contrarien</span></a><a href="#trade" class="fnav-item"><i class="fas fa-list-check"></i><span>Cadre</span></a><a href="#sources" class="fnav-item"><i class="fas fa-database"></i><span>Sources</span></a></div><button class="fnav-btn" id="fnavBtn" type="button" aria-label="Navigation"><i class="fas fa-bars" id="fnavIcon"></i><span class="fnav-btn-label" id="fnavLabel">Menu</span></button></div>
<footer class="article-footer">&copy; 2026 DailyTickers. Données de marché DailyTickers. Information générale, pas un conseil financier.<br><a href="https://dailytickers.substack.com" target="_blank" rel="noopener">Recevoir les publications sur Substack</a></footer>
<script id="studyData" type="application/json">${json}</script>
<script>
const D=JSON.parse(document.getElementById('studyData').textContent);const charts=[];const axis={axisLine:{lineStyle:{color:'#b9c3cf'}},axisLabel:{color:'#526174'},splitLine:{lineStyle:{color:'#e8edf2'}}};
function init(id,opt){const c=echarts.init(document.getElementById(id));c.setOption(opt);charts.push(c);return c}
init('monthlyChart',{tooltip:{trigger:'axis',valueFormatter:v=>(v/1e6).toFixed(1)+' M'},grid:{left:54,right:18,top:30,bottom:62},xAxis:{type:'category',data:D.monthly_volume.map(x=>x.month),axisLabel:{rotate:45,color:'#526174'},axisLine:axis.axisLine},yAxis:{type:'value',name:'Millions',axisLabel:{formatter:v=>(v/1e6).toFixed(0)+' M',color:'#526174'},splitLine:axis.splitLine},series:[{type:'bar',data:D.monthly_volume.map(x=>({value:x.avg,itemStyle:{color:x.month.startsWith('2026')?'#1667c5':'#9eb7d1'}})),barMaxWidth:28,markLine:{symbol:'none',label:{formatter:'Moy. août 2026'},lineStyle:{color:'#a15c00',type:'dashed'},data:[{yAxis:18166502}]}}]});
init('peerChart',{tooltip:{formatter:p=>p.data[3]+'<br>Prix 20j : '+p.value[0].toFixed(1)+' %<br>Volume moyen : '+p.value[1].toFixed(1)+' %<br>RVOL : '+p.data[2].toFixed(2)+'x'},grid:{left:54,right:18,top:28,bottom:46},xAxis:{type:'value',name:'Prix 20j',axisLabel:{formatter:'{value} %',color:'#526174'},splitLine:axis.splitLine},yAxis:{type:'value',name:'Volume',axisLabel:{formatter:'{value} %',color:'#526174'},splitLine:axis.splitLine},series:[{type:'scatter',symbolSize:d=>12+d[2]*8,data:D.peers.map(x=>[x.price_20_pct,x.avg_volume_change_pct,x.rvol,x.symbol]),label:{show:true,position:'top',formatter:p=>p.data[3],color:'#101828',fontWeight:700},itemStyle:{color:p=>p.data[3]==='NOW'?'#b42318':'#1667c5',opacity:.85},markLine:{silent:true,symbol:'none',lineStyle:{color:'#b9c3cf',type:'dashed'},data:[{xAxis:0},{yAxis:0}]}}]});
init('eventChart',{tooltip:{trigger:'axis',axisPointer:{type:'shadow'},formatter:p=>{const x=D.event_days[p[0].dataIndex];return x.date+' · '+x.label+'<br>Volume : '+(x.volume/1e6).toFixed(1)+' M<br>RVOL : '+x.rvol.toFixed(2)+'x<br>Séance : '+x.return_pct.toFixed(2)+' %'}},grid:{left:56,right:18,top:20,bottom:66},xAxis:{type:'category',data:D.event_days.map(x=>x.date.slice(5)),axisLabel:{rotate:35,color:'#526174'},axisLine:axis.axisLine},yAxis:{type:'value',axisLabel:{formatter:v=>(v/1e6).toFixed(0)+' M',color:'#526174'},splitLine:axis.splitLine},series:[{type:'bar',barMaxWidth:44,data:D.event_days.map(x=>({value:x.volume,itemStyle:{color:x.return_pct>=0?'#087a55':'#b42318'}})),label:{show:true,position:'top',formatter:p=>D.event_days[p.dataIndex].rvol.toFixed(1)+'x',color:'#526174',fontSize:11}}]});
init('returnChart',{tooltip:{trigger:'axis',valueFormatter:v=>v.toFixed(1)+' %'},grid:{left:50,right:16,top:20,bottom:40},xAxis:{type:'category',data:D.monthly_returns_2026.map(x=>x.month),axisLabel:{color:'#526174'},axisLine:axis.axisLine},yAxis:{type:'value',axisLabel:{formatter:'{value} %',color:'#526174'},splitLine:axis.splitLine},series:[{type:'bar',barMaxWidth:34,data:D.monthly_returns_2026.map(x=>({value:x.return_pct,itemStyle:{color:x.return_pct>=0?'#087a55':'#b42318'}})),label:{show:true,position:p=>p.value>=0?'top':'bottom',formatter:'{c} %',color:'#526174',fontSize:10}}]});
addEventListener('resize',()=>charts.forEach(c=>c.resize()));
</script>
<script src="/assets/core.js"></script><script src="/assets/tag-renderer.js"></script>
</body></html>`;

fs.writeFileSync(path.join(root, 'index.html'), html);
console.log(`Built ${path.join(root, 'index.html')}`);
