'use strict';
// Dossier PURR v3 au close du 2026-09-25 (lot R07). Cas particulier : Hyperliquid Strategies Inc n'est PAS
// une société d'exploitation mais un VÉHICULE DE TRÉSORERIE D'ACTIFS NUMÉRIQUES (digital-asset treasury).
// Actif principal : le token HYPE du réseau Hyperliquid (29 275 085 unités au 30/06/2026). Revenus limités
// au staking/commission de validateur. La valorisation pertinente n'est donc pas un multiple d'EBITDA ou de
// revenus (aucun sens ici) mais la VALEUR NETTE D'INVENTAIRE (VNI) : juste valeur du HYPE + trésorerie −
// passifs, rapportée au nombre d'actions, comparée au cours (prime/décote).
//
// Les agrégats financiers sont fournis par cfg.manualFinancials (aucun companyfacts us-gaap glissant n'est
// pertinent pour ce véhicule ; les valeurs sont lues dans le 10-K de l'exercice clos le 30/06/2026, liées par
// accession/formulaire/pointeur de document). Le scénario de valorisation enregistré est cfg.valuationScenario
// (statut non_applicable, EBITDA fournisseur nul observé) ; la VNI est présentée dans le corps de la fiche.
// Émetteur récemment coté (fusion SPAC déc. 2025) : historique certifié de 204 séances → cfg.minBars=200.
// Comparables : 17 véhicules crypto-treasury / plateformes / mineurs / ETF propres (calendrier us_equity ;
// aucun actif au calendrier crypto_24_7). Aucune clôture HYPE certifiée point-in-time au 25/09 : la VNI
// gouvernante est la juste valeur auditée du 30/06/2026 ; le prix HYPE implicite au cours actuel est un
// scénario explicitement borné.
const R = require('../../../../tools/lib/analysis-v3-r07.cjs');
const GEN = 'analyses/PURR/_runs/20260927/build-purr.cjs';

// --- Agrégats du 10-K (exercice clos le 30/06/2026), en milliers de dollars sauf indication ------------
const HYPE_FV = 1904052, HYPE_UNITS = 29275085, HYPE_COST = 1363333, CASH = 137917;
const TA = 2060008, TL = 187137, DTL = 183475;
const REV = 9460, NI = 305542, UNREAL = 709875, LOSSCTB = 169156, OPEX = 13951;
const COMMON0630 = 200550458, PREFCONV = 26587647, WARR = 27394800, PREF = 166173;
// --- 424B3 du 23/09/2026 (structure au 8 septembre 2026) -----------------------------------------------
const COMMON0908 = 237919288, HYPE0908 = 33.2e6, SOLD0908 = 112952100, REGISTERED = 160000000;
const CAP_REMAIN = 1.4e9, CAP_TOTAL = 2.5e9, CHEF_PRICE = 0.975, MIN_PRICE = 12.02, EXCH_CAP = 42641847;

const ACC_10K = '0001193125-26-370281', ACC_CHEF1 = '0001193125-26-378589', ACC_CHEF3 = '0001193125-26-391090',
      ACC_PRE14A = '0001193125-26-392149', ACC_B3 = '0001193125-26-399511', ACC_PR = '0001193125-26-369668';

R.build({
  ticker: 'PURR', shortName: 'Hyperliquid Strategies', cik: 2078856, generator: GEN, mode: 'breakout', minBars: 200,
  xbrl: { ttm: {}, instant: {}, da: ['da'], debt: ['debt'], cash: ['cash'] },
  manualFinancials: { figures: {
    rev:  { value: REV * 1000,  form: '10-K', accn: ACC_10K, start: '2025-07-01', end: '2026-06-30', doc: 0 },
    ebit: { value: (REV - OPEX) * 1000, form: '10-K', accn: ACC_10K, start: '2025-07-01', end: '2026-06-30', doc: 0 },
    ni:   { value: NI * 1000,   form: '10-K', accn: ACC_10K, start: '2025-07-01', end: '2026-06-30', doc: 0 },
    da:   { value: 0,           form: '10-K', accn: ACC_10K, start: '2025-07-01', end: '2026-06-30', doc: 0 },
    debt: { value: 0,           form: '10-K', accn: ACC_10K, end: '2026-06-30', doc: 0 },
    cash: { value: CASH * 1000, form: '10-K', accn: ACC_10K, end: '2026-06-30', doc: 0 },
  } },
  // Scénario de valorisation : multiple d'EBITDA/revenus non applicable à un véhicule de trésorerie. La base
  // est l'EBITDA fournisseur observé (nul) ; la grille retenue et publiée est la valeur nette d'inventaire.
  scenarioBasis: 'revenue', scenarioMultiple: 1,
  valuationBasis: 'Véhicule de trésorerie d’actifs numériques : valorisation par la valeur nette d’inventaire (VNI), non par un multiple.',
  valuationScenario: c => ({
    status: 'non_applicable', reason_code: 'NON_POSITIVE_EBITDA',
    reason: 'Hyperliquid Strategies est un véhicule de trésorerie d’actifs numériques sans exploitation significative (revenus de staking de 9,46 M$ sur l’exercice, EBITDA fournisseur nul) : aucun multiple d’EBITDA ou de revenus n’a de sens. La grille de valorisation retenue et publiée dans la fiche est l’actif net (valeur nette d’inventaire) — juste valeur du HYPE + trésorerie − passifs, rapporté au nombre d’actions, comparé au cours (prime/décote).',
    basis: { input_path: 'analyses/PURR/_data/fundamentals.json', input_sha256: c.K.sha(c.K.bytes('analyses/PURR/_data/fundamentals.json')), source_pointer: '/data/items/0/results/1/data/0/ebitda' },
  }),
  levels: { trigger: { d: '2026-09-24', c: 2 }, stop: { d: '2026-09-25', c: 3 }, abandon: { d: '2026-09-11', c: 3 }, s1: { d: '2026-09-25', c: 3 }, s2: { d: '2026-09-11', c: 3 }, s3: { d: '2026-09-10', c: 3 }, r1: { d: '2026-09-23', c: 2 }, r2: { d: '2026-09-21', c: 2 } },
  supports: ['s1', 's2', 's3'], resistances: ['r1', 'r2', 'trigger'],
  targets: ({ entry, abandon }) => { const range = entry - abandon; return { tp1: entry + range, tp2: entry + 1.5 * range, range }; },
  levelsMethod: 'Déclencheur = plus haut du 24 septembre (reprise du sommet d’avant le repli) ; stop = plus bas du 25 septembre ; plancher du couloir = plus bas du 11 septembre ; TP1 = déclencheur + hauteur du couloir ; TP2 = déclencheur + 1,5 × hauteur ; plafond d’achat = (TP1 + 1,5 × stop) / 2,5 arrondi au cent inférieur ; pourcentages depuis l’entrée ; R/R = gain / risque. Niveaux lus sur les barres certifiées.',
  inventory: 24,
  reviewScope: 'Dépôts EDGAR de Hyperliquid Strategies Inc (CIK 0002078856) revus jusqu’au 25 septembre 2026 : le 10-K de l’exercice clos le 30 juin 2026 (actif net, trésorerie en HYPE, absence de dette, impôt différé, structure du capital), les amendements 1 et 3 de l’accord d’émission d’actions avec Chardan (ChEF), le prospectus 424B3 du 23 septembre 2026 (structure au 8 septembre : actions, HYPE, capacité restante de la facilité), la circulaire préliminaire PRE 14A du vote du 4 novembre, et le communiqué de résultats du 27 août. La cession de l’activité biotechnologique héritée de Sonnet (31 mars 2026) est reprise du 10-K.',
  docs: [
    ['2026-08-27', '10-K', ACC_10K, 'purr-20260630.htm', '10k_20260630.htm',
      'Rapport annuel de l’exercice clos le 30 juin 2026 : 29 275 085 unités HYPE à une juste valeur de 1 904,1 M$ (coût 1 363,3 M$), trésorerie de 137,9 M$, actif total de 2 060,0 M$, passifs de 187,1 M$ dont 183,5 M$ d’impôt différé, aucune dette financière ; revenus de staking et de commission de validateur de 9,46 M$ ; résultat net de 305,5 M$ (dont 709,9 M$ de plus-value latente sur HYPE et −169,2 M$ de perte sur engagement de contribution) ; 200 550 458 actions ordinaires, 166 173 actions préférentielles convertibles en 26 587 647 ordinaires, 27 394 800 bons de souscription.', 2078856],
    ['2026-09-01', '8-K', ACC_CHEF1, 'purr-20260901.htm', '8k_20260901.htm',
      'Amendement n°1 de l’accord d’émission d’actions (ChEF) avec Chardan : engagement porté de 1,0 à 2,5 Md$ ; plafond de 42 641 847 actions (19,99 % du capital) pour les ventes sous 12,02 $ tant que l’assemblée n’a pas approuvé le dépassement.', 2078856],
    ['2026-09-15', '8-K', ACC_CHEF3, 'purr-20260914.htm', '8k_20260915.htm',
      'Amendement n°3 de l’accord ChEF : prix de vente à 98,5 % du cours moyen pondéré (VWAP) en séance et 97,0 % hors séance uniquement au-delà des 160 premiers millions d’actions ; aujourd’hui 97,5 % / 95,0 %.', 2078856],
    ['2026-09-15', 'PRE 14A', ACC_PRE14A, 'd290166dpre14a.htm', 'pre14a_20260915.htm',
      'Circulaire préliminaire : proposition n°2 (proposition Nasdaq) autorisant l’émission d’actions au-delà de 19,99 % dans le cadre de la facilité Chardan. Assemblée prévue le 4 novembre 2026 ; date d’enregistrement le 30 septembre 2026.', 2078856],
    ['2026-09-23', '424B3', ACC_B3, 'd168095d424b3.htm', '424b3_20260923.htm',
      'Prospectus de revente couvrant jusqu’à 160 000 000 d’actions : au 8 septembre 2026, 112 952 100 actions vendues via la facilité pour environ 1,1 Md$ de produit brut, environ 1,4 Md$ de capacité restante, 237 919 288 actions en circulation et environ 33,2 millions d’unités HYPE détenues ; prix Chardan à 97,5 % du VWAP, plafond de 42 641 847 actions sous 12,02 $.', 2078856],
    ['2026-08-27', '8-K', ACC_PR, 'purr-20260827.htm', 'ex99_1_20260827.htm',
      'Communiqué de résultats (annexe 99.1) : trésorerie en HYPE portée de 12,5 à 29,3 millions d’unités sur l’exercice, 647 M$ de capitaux levés via la facilité, 149,9 M$ de liquidités et aucune dette.', 2078856],
  ],
  needles: {
    nav: [0, ['29,275,085', '1,904,052', '1,363,333', '137,917', '2,060,008', '187,137', '183,475']],
    income: [0, ['9,460', '305,542', '709,875', '169,156', '13,951']],
    capital0630: [0, ['200,550,458', '166,173', '26,587,647', '27,394,800']],
    chefcap: [1, ['from $1.0 billion to $2.5 billion', '42,641,847']],
    pricing: [2, ['98.5', 'VWAP']],
    vote: [3, ['November 4, 2026', 'September 30, 2026']],
    facility: [4, ['237,919,288', '112,952,100', '160,000,000', '33.2 million HYPE', '97.5%', '$12.02', '1.4 billion', '1.1 billion']],
    pr: [5, ['29.3 million', '$149.9 million', '647 million', 'no debt']],
  },
  sectionDocs: { verdict: [0, 4, 1], business: [0, 5], news: [0, 4], earnings: [0], capitalStructure: [0, 4, 1], filingsReview: [0, 1, 2, 3, 4, 5], risks: [0, 4, 1], globalScore: [0], meta: [0], disclaimer: [0], macro: [0], options: [0], social: [0], header: [0], shortInterest: [0], insiders: [0] },
  score: { business: 16, technical: 3, capital: 9, calendar: -4, dilution: -14, risk: 24 },
  peers: false,
  shares: { value: COMMON0908, doc: 4 },
  route: (p, { prov, dep, B }) => /^news\.[03]\./.test(p) ? prov('bars', B, 'Ouverture et clôture lues sur les barres certifiées ; variations de clôture à clôture ; comparaison avec les comparables sur la même séance.', [dep('comparison', '')]) : null,
  riskScoreReason: 'Jugement qualitatif sur dix : véhicule de trésorerie dont la valeur suit un seul actif volatil (le token HYPE), dilution active massive (facilité d’émission de 2,5 Md$ avec ~1,4 Md$ de capacité restante, soit près de la moitié du capital, vote du 4 novembre pour lever le plafond de 19,99 %), cours proche de la valeur nette d’inventaire du 30 juin (0,95×), résultat net dominé par des plus-values latentes non réalisées, impôt différé de 183,5 M$ sur ces gains, et repli propre de 8,8 % le 25 septembre bien supérieur à celui du complexe crypto.',
  compose: c => {
    const { fr, usd, pct, sgn, close, prev, bars, N, tech, M, adv, ret, docs, raw, ref, market, lv, entry, stop, tp1, tp2, abandon, cap, rr1, rr2, riskAtr, sizeExample } = c;
    const cmp = raw.comparison_bars.data.items[0].results[0].data;
    const dr = (sym, d) => { const b = cmp.find(x => x.symbol === sym).bars, i = b.findIndex(x => x[0] === d); return pct(b[i][4], b[i - 1][4]); };
    const bar = d => bars.find(b => b[0] === d);
    // Valeur nette d'inventaire (VNI) — 10-K au 30/06/2026, en dollars
    const equity = (TA - TL) * 1000;                        // actif net = actif total − passifs
    const shares0630 = COMMON0630 + PREFCONV;               // ordinaires + préférentielles converties
    const navPs0630 = equity / shares0630;                  // VNI par action au 30/06
    const close0630 = bar('2026-06-30')[4];                 // clôture du 30/06 (barre certifiée)
    const pnav0630 = close0630 / navPs0630;                 // cours / VNI au 30/06
    const discount0630 = (1 - pnav0630) * 100;
    const hypePx0630 = HYPE_FV * 1000 / HYPE_UNITS;         // prix HYPE implicite au bilan du 30/06
    const otherK = TA - HYPE_FV - CASH;                     // autres actifs (hors HYPE et trésorerie)
    const nonHypeNetK = CASH + otherK - TL;                 // actif net hors HYPE au 30/06
    const shares0908pd = COMMON0908 + PREFCONV;             // actions au 8/09 (préférentielles converties)
    const impliedHype = (close * shares0908pd - nonHypeNetK * 1000) / HYPE0908; // prix HYPE implicite au cours
    const fullyDiluted = COMMON0908 + PREFCONV + WARR;
    const mktCap = c.marketCap;                             // close × actions ordinaires au 8/09
    const dilAtClose = CAP_REMAIN / (close * CHEF_PRICE), dilAtClosePct = dilAtClose / COMMON0908 * 100;
    const dilAtMin = CAP_REMAIN / (MIN_PRICE * CHEF_PRICE), dilAtMinPct = dilAtMin / COMMON0908 * 100;
    // repères de cours
    const win = bars.slice(Math.max(0, N - 251), N + 1); let hi = -1, lo = 1e9, hiD, loD;
    for (const b of win) { if (b[2] > hi) { hi = b[2]; hiD = b[0]; } if (b[3] < lo) { lo = b[3]; loD = b[0]; } }
    const ext20 = pct(close, tech.ema20);
    const d0925 = bar('2026-09-25'), d0924 = bar('2026-09-24'), d0921 = bar('2026-09-21');
    return {
      meta: { lang: 'fr', dir: 'ltr', level: 'intermediate', tags: ['us', 'crypto', 'financials', 'speculative', 'small-cap'], grade: 'C-', date: '2026-09-25', dateDisplay: '25 septembre 2026', version: 3, status: 'watch', assetType: 'stock', levelsCloseDate: c.REF,
        description: 'Hyperliquid Strategies (PURR) : véhicule de trésorerie en token HYPE (~33 M d’unités), financé par une facilité d’émission d’actions de 2,5 Md$. Valorisation par la valeur nette d’inventaire (0,95× au 30 juin). Cours du 25 septembre 12,85 $ (−8,8 %), statut surveiller.',
        ogDescription: 'PURR : une trésorerie en HYPE valorisée par sa valeur nette d’inventaire (0,95× au 30 juin), payée en dilution. Cours 12,85 $, statut surveiller.',
        lastMcpRefresh: raw.status.captured_at, levelsVerifiedAt: raw.status.captured_at,
        statusHistory: [...(c.archive.meta.statusHistory || []), { at: raw.status.captured_at, from: c.archive.meta.status || 'watch', to: 'watch', note: 'refonte v3 harnachée du 25 septembre : véhicule de trésorerie HYPE valorisé par la valeur nette d’inventaire (0,95× au 30 juin), 17 comparables crypto propres, statut surveiller après un repli propre de 8,8 %', close }] },
      header: { ticker: 'PURR', name: 'Hyperliquid Strategies Inc', exchange: 'NASDAQ', sector: 'Trésorerie d’actifs numériques (token HYPE)', price: close, changePct: pct(close, prev),
        badges: [{ text: 'SURVEILLER — VÉHICULE DE TRÉSORERIE HYPE', color: 'blue' }, { text: 'Valorisation par la valeur nette d’inventaire', color: 'purple' }],
        metrics: { marketCap: fr(mktCap / 1e6, 0) + ' M$', volume: fr(bars[N][5] / 1e6, 2) + ' M', navSpot: fr(pnav0630, 2) + '× VNI (30/06)' }, halalStatus: 'unknown' },
      verdict: { score: 34, conviction: 'Low', bias: 'Neutral',
        confidence: 'Score éditorial non prédictif. Les chiffres d’entreprise sont lus dans le 10-K de l’exercice clos le 30 juin 2026 et le prospectus 424B3 du 23 septembre ; les niveaux, sur le close certifié du 25 septembre.',
        summary: 'Hyperliquid Strategies n’est pas une entreprise ordinaire : c’est un coffre. Son actif, ce sont des jetons HYPE du réseau Hyperliquid — ' + fr(HYPE_UNITS / 1e6, 1) + ' millions d’unités valorisées ' + fr(HYPE_FV / 1e3, 1) + ' M$ au 30 juin, plus ' + fr(CASH / 1e3, 1) + ' M$ de trésorerie, aucune dette. La bonne question n’est pas « combien vaut le business » (le staking ne rapporte que ' + fr(REV / 1e3, 2) + ' M$) mais « le cours paie-t-il une prime ou une décote sur cet actif net ». Au 30 juin, la valeur nette d’inventaire ressort à ' + usd(navPs0630) + ' par action, le cours à ' + usd(close0630) + ' : ' + fr(pnav0630, 2) + ' fois l’actif net, une décote de ' + fr(discount0630, 1) + ' %. Depuis, le HYPE a monté et le titre avec lui, jusqu’à ' + usd(hi) + ' le 21 septembre. Au close du 25 septembre, ' + usd(close) + ' (' + sgn(pct(close, prev), 1) + '), le marché price le HYPE autour de ' + usd(impliedHype) + ' l’unité, contre ' + usd(hypePx0630) + ' à la juste valeur auditée du 30 juin. Le vrai risque n’est pas le business, c’est la dilution : une facilité d’émission de ' + fr(CAP_TOTAL / 1e9, 1) + ' Md$ avec Chardan, environ ' + fr(CAP_REMAIN / 1e9, 1) + ' Md$ disponibles, un vote le 4 novembre pour lever le plafond de 19,99 %. Statut surveiller : pas d’entrée actionnable au comptant.',
        whyBuy: [
          'Un actif net tangible et liquide : ' + fr(HYPE_UNITS / 1e6, 1) + ' millions d’unités HYPE à ' + fr(HYPE_FV / 1e3, 1) + ' M$ de juste valeur au 30 juin, ' + fr(CASH / 1e3, 1) + ' M$ de trésorerie et aucune dette financière.',
          'Une exposition cotée au token HYPE et à la croissance du réseau Hyperliquid, difficile à obtenir autrement sur un marché actions américain.',
          'Au 30 juin, le titre se payait ' + fr(pnav0630, 2) + ' fois son actif net (décote de ' + fr(discount0630, 1) + ' %) : l’enveloppe n’était pas survalorisée par rapport à son contenu.',
          'Trésorerie renforcée en continu : ' + fr(SOLD0908 / 1e6, 1) + ' millions d’actions déjà vendues via la facilité pour environ 1,1 Md$, réinvestis en HYPE.'],
        whyAvoid: [
          'La valeur suit un seul actif très volatil : si le HYPE baisse, l’actif net et le cours baissent d’autant — aucune diversification, aucun amortisseur d’exploitation.',
          'Dilution active et massive : facilité de ' + fr(CAP_TOTAL / 1e9, 1) + ' Md$, environ ' + fr(CAP_REMAIN / 1e9, 1) + ' Md$ restants ≈ ' + fr(dilAtClosePct, 0) + ' % d’actions nouvelles au cours actuel ; vote du 4 novembre pour dépasser 19,99 %.',
          'Le résultat net de ' + fr(NI / 1e3, 1) + ' M$ est un mirage comptable : ' + fr(UNREAL / 1e3, 1) + ' M$ de plus-values latentes non réalisées sur le HYPE, symétriques à la baisse ; l’exploitation, elle, perd de l’argent.',
          'Un impôt différé de ' + fr(DTL / 1e3, 1) + ' M$ (98 % des passifs) pèse sur ces gains latents et grandit avec le HYPE ; le repli propre de ' + fr(Math.abs(pct(close, prev)), 1) + ' % du 25 septembre rappelle la nervosité du dossier.'],
        controlChecklist: [
          { label: 'Historique de cours', status: 'warn', statusLabel: '204 séances depuis décembre 2025', evidence: 'Société cotée par fusion fin 2025 : série certifiée de 204 séances, plus courte que le standard de 250 ; la moyenne à 200 séances est à peine amorcée.', action: 'Lire les repères longs avec prudence ; privilégier la structure récente.' },
          { label: 'Valorisation', status: 'warn', statusLabel: 'Valeur nette d’inventaire, pas un multiple', evidence: 'Aucun multiple d’EBITDA ou de revenus n’a de sens pour un coffre à jetons : la grille est l’actif net (' + usd(navPs0630) + ' par action au 30 juin). Aucune clôture HYPE certifiée point-in-time au 25 septembre.', action: 'Suivre le prix du HYPE et le nombre d’actions ; la VNI par action bouge avec les deux.' },
          { label: 'Dilution', status: 'fail', statusLabel: 'Facilité de ' + fr(CAP_TOTAL / 1e9, 1) + ' Md$ active', evidence: 'Environ ' + fr(CAP_REMAIN / 1e9, 1) + ' Md$ de capacité d’émission restante, vote du 4 novembre pour lever le plafond de 19,99 %. L’émission dilue la VNI par action si elle se fait sous l’actif net.', action: 'Ne pas ignorer l’offre de titres à venir dans le calcul de rendement.' }] },
      business: { theme: 'Véhicule de trésorerie détenant le token HYPE du réseau Hyperliquid',
        overview: '<p>Hyperliquid Strategies Inc n’exploite pas une activité classique : c’est un véhicule de trésorerie d’actifs numériques (<i>digital-asset treasury</i>). Née de la coquille cotée Sonnet BioTherapeutics — dont l’activité biotechnologique a été cédée à Guidant Biotherapeutics le 31 mars 2026 —, la société a une seule mission : accumuler et détenir le token HYPE du réseau Hyperliquid, une plateforme d’échange de produits dérivés décentralisée.</p><p>Au 30 juin 2026, elle détenait ' + fr(HYPE_UNITS / 1e6, 2) + ' millions d’unités HYPE, portées à une juste valeur de ' + fr(HYPE_FV / 1e3, 1) + ' M$ (pour un coût d’acquisition de ' + fr(HYPE_COST / 1e3, 1) + ' M$), auxquelles s’ajoutent ' + fr(CASH / 1e3, 1) + ' M$ de trésorerie. Elle n’a aucune dette financière. Ses seuls revenus — ' + fr(REV / 1e3, 2) + ' M$ sur l’exercice — proviennent du staking et des commissions de validateur perçues en mettant ses jetons au service du réseau.</p><p>Le modèle est simple et brutal : la société émet des actions, avec ce produit elle achète du HYPE, et la valeur de l’action suit celle du token, à la dilution près. Le financement passe par un accord d’émission d’actions au fil de l’eau (facilité « ChEF ») avec Chardan, porté à ' + fr(CAP_TOTAL / 1e9, 1) + ' Md$. Au 8 septembre, la société détenait environ ' + fr(HYPE0908 / 1e6, 1) + ' millions d’unités HYPE et comptait ' + fr(COMMON0908 / 1e6, 1) + ' millions d’actions en circulation.</p>',
        moat: 'Il n’y a pas d’avantage concurrentiel au sens classique : n’importe qui peut acheter du HYPE, et d’autres véhicules cotés visent le même jeton. Le seul atout est l’accès : offrir sur un marché actions américain une exposition liquide et cotée au HYPE, avec des revenus de staking, pour un investisseur qui ne veut pas détenir le token en direct. Cet accès se paie en dilution et se compare sans cesse à la simple détention du jeton.',
        segments: [
          { name: 'Trésorerie en HYPE (cœur)', revenue: fr(HYPE_FV / 1e3, 1) + ' M$ de juste valeur au 30/06', pct: 'Quasi-totalité de l’actif', description: fr(HYPE_UNITS / 1e6, 2) + ' millions d’unités HYPE détenues, portées de 12,5 à 29,3 millions sur l’exercice ; la valeur du titre suit celle du jeton.' },
          { name: 'Staking et commission de validateur', revenue: fr(REV / 1e3, 2) + ' M$ sur l’exercice', pct: 'Seuls revenus', description: 'Rémunération perçue en mettant les jetons au service du réseau Hyperliquid ; marginale au regard de la valeur de l’actif.' }],
        sourceRefs: [ref(0), ref(4), ref(5)],
        coverageMatrix: [
          { facet: 'Cours et historique', status: 'COUVERT — COURT', decision: '204 séances certifiées depuis la cotation par fusion de décembre 2025 ; base des niveaux et des repères récents.' },
          { facet: 'Actif net et bilan', status: 'COUVERT — PRIMAIRE', decision: 'Juste valeur du HYPE, trésorerie, passifs et impôt différé lus dans le 10-K au 30 juin 2026 ; base de la valeur nette d’inventaire.' },
          { facet: 'Structure du capital et dilution', status: 'COUVERT — PRIMAIRE', decision: 'Facilité Chardan de 2,5 Md$, plafond de 19,99 %, capacité restante et prix de vente lus dans les 8-K et le 424B3 ; vote du 4 novembre dans la PRE 14A.' },
          { facet: 'Comparables et transmission', status: 'COUVERT — LOCAL', decision: 'Corrélations recalculées sur barres certifiées ; 17 comparables crypto propres (véhicules de trésorerie, plateformes, mineurs, ETF), tous au calendrier actions américain.' },
          { facet: 'Prix HYPE point-in-time', status: 'NON EXPLOITABLE', decision: 'Aucune clôture HYPE certifiée au 25 septembre : la VNI gouvernante est la juste valeur auditée du 30 juin ; le prix HYPE implicite au cours actuel est un scénario borné.' },
          { facet: 'Options, coût d’emprunt, sentiment', status: 'NON EXPLOITABLE', decision: 'Chaîne d’options non servie (statut 429), coût d’emprunt indisponible (statut 444), ni Reddit ni Google Trends pour ce titre.' },
          { facet: 'Position vendeuse et statistiques', status: 'NON EXPLOITABLE', decision: 'Le fournisseur ne renvoie ni position vendeuse, ni flottant, ni bêta pour ce titre récemment coté ; aucune valeur inférée.' }] },
      news: [
        { date: '2026-09-25', title: 'Repli propre de ' + fr(Math.abs(pct(close, prev)), 1) + ' % à ' + usd(close) + ', bien au-delà du complexe crypto', impact: 'negative', detail: 'Après un rebond à ' + usd(d0924[4]) + ' le 24, le titre ouvre à ' + usd(d0925[1]) + ' et clôture à ' + usd(close) + ' (' + sgn(pct(close, prev), 2) + '). Le même jour, la plateforme de référence COIN fait ' + sgn(dr('COIN', '2026-09-25'), 2) + ', l’ETF bitcoin IBIT ' + sgn(dr('IBIT', '2026-09-25'), 2) + ' et la trésorerie Ethereum BMNR ' + sgn(dr('BMNR', '2026-09-25'), 2) + ' : le repli est très largement propre au titre, cohérent avec le prospectus de revente de 160 M d’actions et le vote de dilution à venir.', source: 'Barres certifiées', sourceUrl: c.evidenceUrl },
        { date: '2026-08-27', title: 'Résultats de l’exercice : ' + fr(HYPE_UNITS / 1e6, 1) + ' M d’unités HYPE, actif net de ' + fr((TA - TL) / 1e3, 1) + ' M$, aucune dette', impact: 'positive', detail: 'Le 10-K de l’exercice clos le 30 juin présente ' + fr(HYPE_UNITS / 1e6, 2) + ' millions d’unités HYPE à ' + fr(HYPE_FV / 1e3, 1) + ' M$ de juste valeur, ' + fr(CASH / 1e3, 1) + ' M$ de trésorerie et aucune dette. Le résultat net de ' + fr(NI / 1e3, 1) + ' M$ est presque entièrement une plus-value latente non réalisée (' + fr(UNREAL / 1e3, 1) + ' M$), pas un flux d’exploitation : les revenus de staking ne pèsent que ' + fr(REV / 1e3, 2) + ' M$.', source: 'Hyperliquid Strategies — SEC', sourceUrl: docs[0].url },
        { date: '2026-09-01', title: 'Facilité d’émission d’actions portée de 1,0 à ' + fr(CAP_TOTAL / 1e9, 1) + ' Md$', impact: 'negative', detail: 'L’amendement n°1 de l’accord ChEF avec Chardan porte l’engagement de 1,0 à 2,5 Md$. Tant que l’assemblée n’a pas approuvé, les ventes sous 12,02 $ sont plafonnées à 42 641 847 actions (19,99 % du capital). Le moteur de valeur du titre — acheter du HYPE — est aussi son moteur de dilution.', source: 'Hyperliquid Strategies — SEC', sourceUrl: docs[1].url },
        { date: '2026-09-15', title: 'Vote des actionnaires le 4 novembre pour dépasser le plafond de 19,99 %', impact: 'neutral', detail: 'La circulaire préliminaire fixe l’assemblée au 4 novembre 2026 (date d’enregistrement le 30 septembre) : la proposition n°2 autoriserait l’émission d’actions au-delà de 19,99 % dans le cadre de la facilité Chardan. Un feu vert lèverait le dernier frein mécanique à la dilution.', source: 'Hyperliquid Strategies — SEC', sourceUrl: docs[3].url }],
      fundamentals: { rows: [
          { metric: 'Valeur nette d’inventaire (NAV / VNI) — actif net au 30/06/2026', value: fr((TA - TL) / 1e3, 1) + ' M$', signal: 'Actif total ' + fr(TA / 1e3, 1) + ' M$ − passifs ' + fr(TL / 1e3, 1) + ' M$ (dont impôt différé ' + fr(DTL / 1e3, 1) + ' M$), 10-K au 30 juin 2026', signalColor: 'green', source: 'Dépôt primaire 10-K', _src: 0 },
          { metric: 'NAV / VNI par action au 30/06/2026', value: usd(navPs0630), signal: 'Actif net ÷ ' + fr(shares0630 / 1e6, 1) + ' M d’actions (ordinaires + préférentielles converties), 10-K au 30 juin 2026', signalColor: 'blue', source: 'Dépôt primaire 10-K', comparison: 'Cours du 30 juin ' + usd(close0630) + ' = ' + fr(pnav0630, 2) + '× la NAV, soit une décote de ' + fr(discount0630, 1) + ' % ; le cours actuel se lit comme une prime/décote (scenario vs actif net)', _src: 0 },
          { metric: 'Juste valeur du HYPE au 30/06/2026', value: fr(HYPE_FV / 1e3, 1) + ' M$', signal: fr(HYPE_UNITS / 1e6, 2) + ' M d’unités ; coût d’acquisition ' + fr(HYPE_COST / 1e3, 1) + ' M$ ; prix implicite au bilan ' + usd(hypePx0630) + '/unité (10-K, 30 juin 2026)', signalColor: 'blue', _src: 0 },
          { metric: 'Prix du HYPE implicite au cours du 25/09/2026 (scénario)', value: '≈ ' + usd(impliedHype) + '/unité', signal: 'Cours ' + usd(close) + ' × ' + fr(shares0908pd / 1e6, 1) + ' M d’actions − actif net hors HYPE du 30 juin, ÷ ' + fr(HYPE0908 / 1e6, 1) + ' M d’unités (8 sept.)', signalColor: 'amber', source: 'Clôture certifiée et dépôts primaires', comparison: 'Contre ' + usd(hypePx0630) + '/unité à la juste valeur auditée du 30 juin : le marché escompte une nette appréciation du token ; scénario, faute de clôture HYPE certifiée', _src: 'market' },
          { metric: 'Trésorerie au 30/06/2026', value: fr(CASH / 1e3, 1) + ' M$', signal: 'Trésorerie et équivalents au bilan ; aucune dette financière', signalColor: 'green', _src: 0 },
          { metric: 'Impôt différé passif au 30/06/2026', value: fr(DTL / 1e3, 1) + ' M$', signal: '98 % des passifs ; impôt latent sur les plus-values non réalisées de HYPE ; grandit avec le token', signalColor: 'amber', _src: 0 },
          { metric: 'Revenus de staking et commission (exercice)', value: fr(REV / 1e3, 2) + ' M$', signal: 'Seuls revenus opérationnels ; marginaux au regard de l’actif de ' + fr(HYPE_FV / 1e3, 1) + ' M$', signalColor: 'amber', _src: 0 },
          { metric: 'Résultat net (exercice)', value: fr(NI / 1e3, 1) + ' M$', signal: 'Dominé par ' + fr(UNREAL / 1e3, 1) + ' M$ de plus-value latente non réalisée sur HYPE et −' + fr(LOSSCTB / 1e3, 1) + ' M$ de perte sur engagement de contribution ; charge d’exploitation de ' + fr(OPEX / 1e3, 2) + ' M$ ; non un flux de trésorerie', signalColor: 'amber', _src: 0 },
          { metric: 'Actions ordinaires en circulation', value: fr(COMMON0908 / 1e6, 1) + ' M (8 sept. 2026)', signal: 'Contre ' + fr(COMMON0630 / 1e6, 1) + ' M au 30 juin ; pleinement dilué ' + fr(fullyDiluted / 1e6, 1) + ' M avec préférentielles et bons', signalColor: 'red', _src: 4 },
          { metric: 'Capacité d’émission restante (facilité Chardan)', value: '≈ ' + fr(CAP_REMAIN / 1e9, 1) + ' Md$', signal: 'Sur une facilité de ' + fr(CAP_TOTAL / 1e9, 1) + ' Md$ ; environ ' + fr(dilAtClosePct, 0) + ' % d’actions nouvelles au cours du 25 sept., ' + fr(dilAtMinPct, 0) + ' % au plancher de 12,02 $ (424B3, 8 sept. 2026)', signalColor: 'red', source: 'Dépôt primaire 424B3', comparison: 'Plafond de 42 641 847 actions (19,99 %) sous 12,02 $ jusqu’au vote du 4 novembre', _src: 4 },
          { metric: 'Capitalisation boursière au 25/09/2026', value: fr(mktCap / 1e6, 0) + ' M$', signal: 'Cours ' + usd(close) + ' × ' + fr(COMMON0908 / 1e6, 1) + ' M d’actions ordinaires (8 sept.)', signalColor: 'blue', _src: 'market' },
          { metric: 'Coût d’acquisition du HYPE au 30/06/2026', value: fr(HYPE_COST / 1e3, 1) + ' M$', signal: 'Contre une juste valeur de ' + fr(HYPE_FV / 1e3, 1) + ' M$ : plus-value latente de ' + fr((HYPE_FV - HYPE_COST) / 1e3, 1) + ' M$ (10-K, 30 juin 2026)', signalColor: 'blue', _src: 0 },
          { metric: 'Plus-value latente non réalisée sur HYPE (exercice)', value: fr(UNREAL / 1e3, 1) + ' M$', signal: 'Principale composante du résultat net ; non réalisée, symétrique à la baisse (10-K)', signalColor: 'amber', _src: 0 },
          { metric: 'Actions vendues via la facilité au 8 sept. 2026', value: fr(SOLD0908 / 1e6, 1) + ' M actions', signal: '≈ 1,1 Md$ de produit brut, réinvestis en HYPE ; sur ' + fr(REGISTERED / 1e6, 0) + ' M enregistrées (424B3)', signalColor: 'red', _src: 4 },
          { metric: 'Structure diluée au 8 sept. 2026', value: '≈ ' + fr(fullyDiluted / 1e6, 1) + ' M actions', signal: '237,9 M ordinaires + 26 587 647 issues des préférentielles + 27 394 800 bons de souscription (10-K / 424B3)', signalColor: 'red', _src: 4 }],
        sourceRefs: [ref(0), ref(4), market('agrégats de bilan et calcul de la valeur nette d’inventaire')] },
      earnings: { quarters: [],
        beatNote: 'Exercice clos le 30 juin 2026 (10-K du 27 août) : revenus de staking et de commission de validateur de ' + fr(REV / 1e3, 2) + ' M$, résultat net de ' + fr(NI / 1e3, 1) + ' M$ dominé par ' + fr(UNREAL / 1e3, 1) + ' M$ de plus-value latente non réalisée sur le HYPE. Véhicule de trésorerie : pas de guidance chiffrée d’exploitation ; la trajectoire dépend du prix du HYPE et du rythme d’émission d’actions. Aucune date de prochaine publication n’est confirmée par l’émetteur.',
        nextEarnings: 'Date non confirmée par l’émetteur ; aucun événement de résultats n’est signalé dans l’horizon du plan par le calendrier collecté.',
        sourceRefs: [ref(0)] },
      capitalStructure: { sharesOutstanding: fr(COMMON0908 / 1e6, 1) + ' millions d’actions ordinaires au 8 septembre 2026 (424B3), contre ' + fr(COMMON0630 / 1e6, 1) + ' millions au 30 juin (10-K) ; 166 173 actions préférentielles convertibles en 26 587 647 ordinaires et 27 394 800 bons de souscription.',
        sharesAuthorized: 'Facilité d’émission d’actions (ChEF) avec Chardan portée à 2,5 Md$ ; environ 1,4 Md$ de capacité restante au 8 septembre.', dilutionRisk: 'critical',
        shareHistory: 'Le nombre d’actions ordinaires est passé de ' + fr(COMMON0630 / 1e6, 1) + ' millions au 30 juin 2026 à ' + fr(COMMON0908 / 1e6, 1) + ' millions au 8 septembre : au 8 septembre, ' + fr(SOLD0908 / 1e6, 1) + ' millions d’actions avaient déjà été vendues via la facilité Chardan pour environ 1,1 Md$ de produit brut, réinvestis en HYPE. Le prospectus de revente couvre jusqu’à ' + fr(REGISTERED / 1e6, 0) + ' millions d’actions. Passage au pleinement dilué : aux ' + fr(COMMON0908 / 1e6, 1) + ' millions d’actions ordinaires s’ajoutent 26 587 647 actions issues de la conversion des préférentielles et 27 394 800 bons de souscription (strikes de 9,375 $, 12,50 $ et 18,75 $), soit un total pleinement dilué d’environ ' + fr(fullyDiluted / 1e6, 1) + ' millions. La facilité conserve environ ' + fr(CAP_REMAIN / 1e9, 1) + ' Md$ de capacité, à 97,5 % du cours moyen pondéré : au cours du 25 septembre, cela représenterait environ ' + fr(dilAtClosePct, 0) + ' % d’actions nouvelles. Le risque de dilution est critique et c’est le cœur du dossier : chaque action émise sert à acheter du HYPE, mais dilue la valeur nette d’inventaire par action dès qu’elle est vendue sous l’actif net.',
        warrants: [],
        atm: { active: true, authorized: 'Facilité ChEF avec Chardan jusqu’à 2,5 Md$ (accord d’émission d’actions au fil de l’eau)', used: 'Environ 1,1 Md$ de produit brut au 8 septembre (112 952 100 actions)', remaining: 'Environ 1,4 Md$ de capacité restante' },
        sourceRefs: [ref(0), ref(4), ref(1)] },
      filingsReview: { summary: 'Six dépôts décisionnels ouverts et hachés : le 10-K de l’exercice clos le 30 juin 2026 (actif net, HYPE, absence de dette, impôt différé, capital), les amendements 1 et 3 de la facilité Chardan, la circulaire du vote du 4 novembre, le prospectus de revente 424B3 du 23 septembre et le communiqué du 27 août. Ils dessinent un véhicule de trésorerie sans dette, valorisé par son actif net, dont le financement — et la dilution — passent par une facilité d’émission d’actions de 2,5 Md$.',
        filings: docs.map(d => ({ date: d.date, form: d.form, accession: d.accession, finding: d.finding, url: d.url })),
        contrarianRisks: [
          'La valeur du titre suit un seul token volatil : une baisse du HYPE réduit l’actif net et le cours d’autant, sans amortisseur.',
          'La dilution est structurelle : la facilité de 2,5 Md$ existe précisément pour émettre des actions ; le vote du 4 novembre lèverait le plafond de 19,99 %.',
          'Le résultat net positif est un artefact comptable de plus-values latentes non réalisées : il s’inverse mécaniquement si le HYPE recule.',
          'L’impôt différé de 183,5 M$ sur les gains latents est une dette qui grandit avec le token et pèsera si les positions sont un jour vendues.'] },
      technicals: { rsi14: +tech.rsi14.toFixed(2), macd: +tech.macd.toFixed(2), macdSignal: +tech.macdSignal.toFixed(2), ema20: +tech.ema20.toFixed(2), ema50: +tech.ema50.toFixed(2), ema200: +tech.ema200.toFixed(2),
        ma50Type: 'EMA', ma200Type: 'EMA', ma50Available: true, ma200Available: false, atr14: +tech.atr14.toFixed(2),
        badges: [fr(Math.abs(pct(close, hi)), 1) + ' % sous le sommet du 21 septembre', 'ATR de ' + usd(tech.atr14), 'Historique court : moyenne à 200 séances non fiable'],
        supports: [lv('s1'), lv('s2'), lv('s3')], resistances: [lv('r1'), lv('r2'), entry],
        setupNote: 'Le titre clôture à ' + usd(close) + ', ' + fr(ext20, 1) + ' % par rapport à sa moyenne à vingt séances, après un repli de ' + fr(Math.abs(pct(close, prev)), 1) + ' % le 25 septembre depuis ' + usd(d0924[4]) + '. Il reste ' + fr(Math.abs(pct(close, hi)), 1) + ' % sous son sommet du 21 septembre (' + usd(hi) + ') et loin au-dessus de son plus bas de la période (' + usd(lo) + '). L’historique certifié ne couvre que 204 séances : la moyenne à deux cents séances est à peine amorcée et n’est pas retenue. Supports : ' + usd(lv('s1')) + ', ' + usd(lv('s2')) + ' et ' + usd(lv('s3')) + '. Résistances : ' + usd(lv('r1')) + ', ' + usd(lv('r2')) + ' et le déclencheur ' + usd(entry) + '. Une clôture sous ' + usd(abandon) + ' romprait la structure de septembre. Repères du plan : déclencheur $' + entry.toFixed(2) + ', stop sous $' + stop.toFixed(2) + '.',
        wyckoff: 'Non utilisé : historique trop court et profil de volume non exploité dans ce dossier.',
        sourceRefs: [market('barres quotidiennes et indicateurs recalculés')] },
      options: { callOI: 'Non exploitable', putOI: 'Non exploitable', cpRatio: 'Non exploitable', maxPain: 'Non exploitable', ivMean: 'Non exploitable', skew: 'Chaîne d’options non servie à la collecte (fournisseur en échec)', unusual: 'Aucune activité inhabituelle qualifiée', sourceRefs: [market('options non servies à la collecte')] },
      shortInterest: { siPct: 'Indisponible à la collecte', daysToCover: 'Indisponible à la collecte', ctb: 'Coût d’emprunt indisponible (fournisseur en échec, statut 444)', trend: 'Le fournisseur ne renvoie ni position vendeuse ni flottant pour ce titre récemment coté ; aucune thèse de rachat forcé n’est établie ici.', squeezeScore: 'Non quantifié faute de données', sourceRefs: [market('positions vendeuses non renvoyées')] },
      insiders: { signal: 'Aucun solde net d’initiés affirmé : la couverture officielle des transactions d’initiés est partielle pour cette entité récemment issue d’une fusion. Le fait capitalistique marquant n’est pas une transaction d’initié classique mais l’émission continue d’actions via la facilité Chardan, réinvestie en HYPE.',
        recentTransactions: [],
        sourceRefs: [market('transactions d’initiés — couverture partielle')] },
      macro: { indicators: [{ name: 'Clôture de référence', value: c.REF, signal: usd(close) + ', séance complète' }, { name: 'Rendement cinq séances', value: sgn(ret(5)), signal: 'Descriptif' }, { name: 'Rendement vingt et une séances', value: sgn(ret(21)), signal: 'Descriptif' }],
        regime: 'neutral', impact: 'Le titre vit du prix du HYPE et de l’appétit du marché pour les actifs numériques. Une baisse du token, une hausse du coût du capital ou un resserrement du financement en actions frapperaient directement un véhicule dont la valeur est l’actif détenu et dont le carburant est l’émission d’actions. Le repli de ' + fr(Math.abs(pct(close, prev)), 1) + ' % du 25 septembre, propre au titre, illustre cette sensibilité.' },
      risks: { riskScore: 8, riskProfile: 'Very High',
        riskSummary: 'Le risque de PURR n’est pas l’exploitation, quasi inexistante, mais la concentration sur un seul token volatil et une dilution active massive. Le titre se paie près de sa valeur nette d’inventaire du 30 juin (' + fr(pnav0630, 2) + '×), mais l’enveloppe grossit sans cesse par émission d’actions, et le vote du 4 novembre lèverait le dernier plafond. Le résultat net est un mirage de plus-values latentes ; l’impôt différé sur ces gains est bien réel.',
        riskCards: [
          { title: 'Concentration sur un seul actif', severity: 'critical', icon: 'fa-microchip', points: ['La quasi-totalité de l’actif est en HYPE (' + fr(HYPE_FV / 1e3, 1) + ' M$ au 30 juin).', 'Aucune diversification, aucun amortisseur d’exploitation.'], verdict: 'Une baisse du HYPE se répercute presque intégralement sur l’actif net et le cours : c’est un pari à effet direct sur un seul token.' },
          { title: 'Dilution active et vote de novembre', severity: 'critical', icon: 'fa-money-bill-trend-up', points: ['Facilité Chardan de ' + fr(CAP_TOTAL / 1e9, 1) + ' Md$, ≈ ' + fr(CAP_REMAIN / 1e9, 1) + ' Md$ restants (≈ ' + fr(dilAtClosePct, 0) + ' % du capital).', 'Vote du 4 novembre pour dépasser le plafond de 19,99 %.'], verdict: 'Chaque action émise achète du HYPE mais dilue la valeur nette d’inventaire par action si elle est vendue sous l’actif net : le rythme d’émission est le premier facteur à suivre.' },
          { title: 'Résultat net trompeur', severity: 'high', icon: 'fa-scale-balanced', points: ['Résultat net de ' + fr(NI / 1e3, 1) + ' M$ dont ' + fr(UNREAL / 1e3, 1) + ' M$ de plus-value latente non réalisée.', 'Revenus d’exploitation de seulement ' + fr(REV / 1e3, 2) + ' M$.'], verdict: 'Le bénéfice affiché est une réévaluation comptable symétrique : il s’inverse si le HYPE recule, et ne dit rien de la génération de trésorerie.' },
          { title: 'Impôt différé et volatilité', severity: 'high', icon: 'fa-arrow-down-up-across-line', points: ['Impôt différé de ' + fr(DTL / 1e3, 1) + ' M$ sur les gains latents (98 % des passifs).', 'Repli propre de ' + fr(Math.abs(pct(close, prev)), 1) + ' % le 25 septembre, ATR de ' + usd(tech.atr14) + '.'], verdict: 'La dette fiscale latente grandit avec le token et pèserait à la vente ; l’amplitude quotidienne rend les écarts brutaux la norme.' }],
        pedagogy: 'Pour un véhicule de trésorerie, la bonne grille n’est ni le résultat net ni un multiple de revenus : c’est la valeur nette d’inventaire — ce que valent les jetons et la trésorerie, moins les dettes, par action. Au 30 juin, cette valeur ressort à ' + usd(navPs0630) + ' et le cours à ' + usd(close0630) + ', soit ' + fr(pnav0630, 2) + '× (décote de ' + fr(discount0630, 1) + ' %). Depuis, le HYPE et le titre ont monté ; au cours du 25 septembre, le marché price le token autour de ' + usd(impliedHype) + ', bien au-dessus de la juste valeur auditée du 30 juin (' + usd(hypePx0630) + '). Deux forces s’opposent : la hausse du HYPE, qui gonfle l’actif net, et l’émission continue d’actions, qui le dilue. Dimensionner comme un pari sur un token volatil, pas comme une action d’entreprise. Sur un titre dont l’amplitude quotidienne dépasse ' + usd(tech.atr14) + ', les écarts d’ouverture (gap) sont fréquents et le slippage peut être réel les jours de faible liquidité. Ne pas courir après le titre : attendre une décote nette sur la valeur nette d’inventaire, ou la levée de l’incertitude du vote du 4 novembre.' },
      tradeIdea: { status: 'watch', statusNote: 'Surveiller. Pas d’entrée actionnable au comptant à ' + usd(close) + ' : le titre se paie près de son actif net, sous l’ombre du vote de dilution du 4 novembre et d’un prospectus de revente de 160 M d’actions. Avant toute reprise, une clôture sous ' + usd(abandon) + ' romprait la structure de septembre. Activation seulement sur une clôture au-dessus de ' + usd(entry) + ', puis achat à l’ouverture suivante sous ' + usd(cap) + '. Le repli du 25 septembre laisse le titre sous le déclencheur : le plan n’est pas activé.',
        entry, stop, tp1, tp2,
        stopPct: pct(stop, entry).toFixed(1) + '%', tp1Pct: '+' + pct(tp1, entry).toFixed(1) + '%', tp2Pct: '+' + pct(tp2, entry).toFixed(1) + '%',
        rr: '1:' + rr1.toFixed(2) + ' TP1 / 1:' + rr2.toFixed(2) + ' TP2',
        entryNote: 'Aucune entrée tant que le titre n’a pas repris ' + usd(entry) + ' en clôture. En cas d’activation, achat à l’ouverture suivante uniquement sous ' + usd(cap) + ' : au-delà, le R/R vers TP1 tomberait sous 1,5 avec le même stop. Le stop se place sous ' + usd(stop) + ', le plus bas du 25 septembre, soit ' + fr(riskAtr, 2) + ' ATR sous le déclencheur. Exemple de taille, non personnalisé : avec un budget de perte de 100 $, le risque au plafond (' + usd(cap - stop) + ' par action) donne ' + sizeExample + ' action' + (sizeExample > 1 ? 's' : '') + '. Liquidité : environ ' + fr(adv / 1e6, 0) + ' M$ échangés par séance (médiane vingt séances). Ce plan est conditionnel : sur un véhicule dont l’actif net est dilué en continu, la reprise doit s’accompagner d’une clarification du rythme d’émission après le vote du 4 novembre.',
        horizon: 'Dix séances après activation',
        thesis: 'PURR est un coffre à jetons HYPE, pas une entreprise : sa valeur suit le token, à la dilution près. Au 30 juin, il se payait ' + fr(pnav0630, 2) + '× son actif net (décote de ' + fr(discount0630, 1) + ' %) ; depuis, le HYPE a monté et le titre avec lui. Le dossier n’est pas actionnable à l’achat au comptant : le cours est proche de l’actif net, la facilité de 2,5 Md$ dilue en continu, et le vote du 4 novembre pèse. Une clôture au-dessus de ' + usd(entry) + ' montrerait que les acheteurs reprennent la main après le repli du 25 septembre ; une clôture sous ' + usd(abandon) + ' romprait la structure. Après activation, le stop sous ' + usd(stop) + ' limite le coût d’une fausse sortie. TP1 à ' + usd(tp1) + ', TP2 à ' + usd(tp2) + '. Repères chiffrés du plan : entrée $' + entry.toFixed(2) + ', stop $' + stop.toFixed(2) + '.',
        catalysts: ['Le vote du 4 novembre : un feu vert lèverait le plafond de 19,99 % et accélérerait la dilution ; un refus la brimerait.', 'Le prix du HYPE : moteur direct de l’actif net et donc du cours.', 'Le rythme de tirage de la facilité Chardan, à suivre dans les dépôts : émission sous l’actif net = destruction de valeur par action.'],
        invalidation: ['Avant activation : une clôture sous ' + usd(abandon) + ' rompt la structure de septembre et repousse tout scénario de reprise.', 'Après activation : une clôture sous ' + usd(stop) + ' invalide le trade.', 'Une baisse marquée du HYPE, ou une émission d’actions d’ampleur inattendue après le vote, change l’équation de la valeur nette d’inventaire et annule la thèse.'] },
      globalScore: { profile: 'Véhicule de trésorerie HYPE — valeur nette d’inventaire, dilution critique',
        keyTakeawaysPositive: ['Actif net tangible : ' + fr(HYPE_UNITS / 1e6, 1) + ' M d’unités HYPE, ' + fr(CASH / 1e3, 1) + ' M$ de trésorerie, aucune dette.', 'Au 30 juin, cours à ' + fr(pnav0630, 2) + '× l’actif net (décote de ' + fr(discount0630, 1) + ' %).', 'Exposition cotée rare au token HYPE et au réseau Hyperliquid.'],
        keyTakeawaysNegative: ['Concentration totale sur un seul token volatil, sans amortisseur.', 'Dilution active de ' + fr(CAP_TOTAL / 1e9, 1) + ' Md$, vote du 4 novembre pour lever le plafond.', 'Résultat net gonflé par des plus-values latentes ; impôt différé de ' + fr(DTL / 1e3, 1) + ' M$.'],
        mindsetTip: 'Sur un coffre à jetons, la seule question qui compte est : « le cours paie-t-il une prime ou une décote sur l’actif net, et à quelle vitesse cet actif est-il dilué ? ». Le résultat net comptable ne dit rien d’utile.' },
      social: { platforms: [], sourceRefs: [market('sentiment non retenu faute de mesure qualifiée')] },
      disclaimer: 'Document de recherche éducatif. Ni conseil financier, ni signal de trading. Statut surveiller : aucun ordre actif.',
    };
  },
  groups: [
    { name: 'Bellwether coté du complexe crypto', order: 1, transmission: 'La plateforme d’échange cotée de référence : ses volumes et son cours mènent l’appétit du marché pour les actifs numériques, dont le HYPE que détient PURR.', rows: [
      ['COIN', 'leader', 'Plateforme d’échange crypto de référence', 'Bellwether coté du complexe crypto : ses volumes mesurent l’appétit du marché pour les tokens et donnent le ton à l’ensemble des valeurs liées, PURR compris.']] },
    { name: 'Trésorerie crypto concurrente', order: 1, transmission: 'Autre véhicule coté dont la valeur suit un token détenu au bilan : même modèle d’enveloppe cotée, même moteur de dilution que PURR.', rows: [
      ['BMNR', 'direct_peer', 'Trésorerie Ethereum cotée', 'Même modèle exact que PURR sur un autre token : émettre des actions pour accumuler de l’ETH ; sa décote/prime sur actif net est le miroir le plus proche de celle de PURR.']] },
    { name: 'Exposition directe aux actifs numériques', order: 1, transmission: 'Fonds qui suivent directement le prix des jetons sous-jacents : ils isolent la part « prix de l’actif » du mouvement de PURR.', rows: [
      ['IBIT', 'upstream', 'Fonds coté bitcoin au comptant', 'Exposition pure au bitcoin, actif qui mène tout le complexe : sépare le mouvement du token de l’effet enveloppe/dilution propre aux véhicules de trésorerie.'],
      ['ETHA', 'upstream', 'Fonds coté Ethereum au comptant', 'Exposition pure à l’ETH : référence du prix de l’actif pour les trésoreries d’altcoins comme PURR.']] },
    { name: 'Plateformes et infrastructures crypto', order: 2, transmission: 'Sociétés dont les revenus dépendent de l’activité et de l’appétit pour les actifs numériques : baromètre de la demande qui porte aussi le HYPE.', rows: [
      ['CRCL', 'downstream', 'Émetteur de stablecoin', 'Infrastructure de règlement crypto ; sa santé reflète l’activité on-chain qui alimente les réseaux comme Hyperliquid.'],
      ['GLXY', 'downstream', 'Services financiers crypto', 'Acteur diversifié des services crypto ; exposé au même cycle de demande et de prix des tokens que PURR.']] },
    { name: 'Mineurs — bêta crypto opérationnel', order: 2, transmission: 'Sociétés d’exploitation fortement corrélées au prix des cryptomonnaies : même bêta au cycle crypto, avec un moteur opérationnel distinct de l’enveloppe de trésorerie.', rows: [
      ['MARA', 'second_order', 'Minage de bitcoin', 'Grand mineur coté ; référence du bêta bitcoin des valeurs d’exploitation, à distinguer de l’enveloppe de trésorerie.'],
      ['RIOT', 'second_order', 'Minage de bitcoin', 'Mineur coté majeur ; complète la lecture du bêta crypto opérationnel.'],
      ['IREN', 'second_order', 'Minage et calcul', 'Exposé au cycle crypto et à l’infrastructure de calcul ; contrôle du bêta sectoriel.'],
      ['CIFR', 'second_order', 'Minage de bitcoin', 'Autre mineur coté ; mesure la sensibilité au prix du bitcoin d’un modèle d’exploitation.'],
      ['WULF', 'second_order', 'Minage et centres de données', 'Mineur exposé au cycle crypto et au calcul ; complète le panel du bêta opérationnel.']] },
    { name: 'Référence de la classe d’actifs numériques', order: 1, transmission: 'Fonds de référence de la classe d’actifs crypto : neutralise le mouvement commun pour isoler ce qui est propre à PURR.', rows: [
      ['GBTC', 'sector_proxy', 'Fonds bitcoin de référence', 'Référence de la classe d’actifs numériques : un mouvement commun avec ce fonds n’a rien de spécifique au titre ; un écart isole ce qui est propre à PURR.']] },
  ],
  eventDefault: { leader: 'Aucune publication propre dans les quatorze jours collectés ; ses volumes et son cours restent le signal à suivre', direct_peer: 'Aucune publication dans les quatorze jours collectés ; sa décote/prime sur actif net reste le signal à suivre', upstream: 'Fonds sans publication propre ; suit directement le prix du token sous-jacent', downstream: 'Aucune publication dans les quatorze jours collectés ; son activité mesure la demande crypto', second_order: 'Aucune publication dans les quatorze jours collectés ; bêta crypto à suivre', sector_proxy: 'Fonds sans publication propre ; exposé au mouvement commun de la classe d’actifs crypto' },
  eventRisk: {},
  blastDoc: 0,
  scenarios: c => [
    { scenario: 'bullish', trigger: 'Le HYPE poursuit sa hausse et le vote du 4 novembre est perçu comme accréditant, pas seulement dilutif.', firstOrder: 'Le titre reprend le déclencheur du 24 septembre et vise la zone du sommet du 21.', secondOrder: 'La trésorerie Ethereum BMNR et la plateforme COIN accompagnent le mouvement.', confirmation: 'Une clôture au-dessus de ' + c.usd(c.entry) + ' avec BMNR et COIN en hausse le même jour.', contradiction: 'Une hausse du titre pendant que BMNR et le complexe crypto reculent.' },
    { scenario: 'mixed', trigger: 'Le HYPE se stabilise ; le marché digère la dilution et attend le vote.', firstOrder: 'Le titre oscille entre le plancher du 11 septembre et le déclencheur du 24.', secondOrder: 'L’écart avec BMNR et le complexe crypto reste faible.', confirmation: 'Des clôtures entre ' + c.usd(c.abandon) + ' et ' + c.usd(c.entry) + ' pendant plusieurs séances.', contradiction: 'Une sortie franche du couloir d’un côté ou de l’autre.' },
    { scenario: 'bearish', trigger: 'Le HYPE recule, ou l’émission d’actions s’accélère et est mal reçue après le vote.', firstOrder: 'Le titre repasse sous le plancher du 11 septembre et se rapproche de son actif net, voire d’une décote.', secondOrder: 'Les trésoreries crypto et les mineurs reculent de concert ; BMNR suit.', confirmation: 'Une clôture sous ' + c.usd(c.abandon) + ' avec BMNR et COIN en baisse.', contradiction: 'Un repli du secteur crypto que PURR ne suit pas.' }],
  contradictions: c => ['Le résultat net de ' + c.fr(NI / 1e3, 1) + ' M$ est positif alors que l’exploitation est marginale (' + c.fr(REV / 1e3, 2) + ' M$ de revenus) : il vient de ' + c.fr(UNREAL / 1e3, 1) + ' M$ de plus-values latentes non réalisées, pas du métier, et s’inverserait si le HYPE recule.', 'Le titre se paie près de son actif net du 30 juin (' + c.fr(0.95, 2) + '×), mais l’émission continue d’actions dilue la valeur nette d’inventaire par action dès qu’elle se fait sous l’actif net.', 'Une corrélation avec une trésorerie Ethereum comme BMNR ne prouve pas l’identité des risques : PURR suit le HYPE, un token bien plus jeune et moins liquide que le bitcoin ou l’ether.'],
  missingData: c => ['Aucune clôture HYPE certifiée point-in-time au 25 septembre : la valeur nette d’inventaire gouvernante est la juste valeur auditée du 30 juin ; le prix HYPE implicite au cours actuel est un scénario borné.', 'Bilan daté du 30 juin 2026 : la trésorerie, le nombre d’actions et les unités HYPE ont évolué depuis (émission continue) ; la structure du 8 septembre est reprise du 424B3.', 'Comparables limités aux véhicules crypto cotés à continuité de barres certifiée : les trésoreries MSTR, SBET, ASST et la trésorerie HYPE concurrente HYPD ont été élaguées faute de continuité de séances dans la fenêtre servie ; douze comparables propres conservés sur six groupes.', 'Chaîne d’options non servie (statut 429), coût d’emprunt indisponible (statut 444), position vendeuse, flottant et bêta non renvoyés pour ce titre récemment coté ; ni Reddit ni Google Trends.', 'Historique certifié limité à environ 200 séances (cotation par fusion de décembre 2025) : la moyenne à deux cents séances n’est pas fiable et n’est pas retenue.'],
  limitations: ['Véhicule de trésorerie : valorisation par la valeur nette d’inventaire (actif net par action), non par un multiple d’EBITDA ou de revenus (aucun sens ici).', 'Agrégats lus dans le 10-K au 30 juin 2026 et le 424B3 au 8 septembre ; le prix HYPE implicite au cours du 25 septembre est un scénario, faute de clôture HYPE certifiée.', 'Options, coût d’emprunt, position vendeuse et sentiment non exploitables à la collecte.', 'Historique de cours court (204 séances) : moyenne à 200 séances non retenue.'],
});
