export const meta = {
  name: 'senior-review',
  description: 'Senior multi-persona QA harness — runs a panel of senior reviewers (QA / Quant / Trader / Risk-Compliance / Editor / AI-Forensics anti-slop) over each artifact, applies fixes, and gates PASS/FIX/BLOCK before publish. The AI-Forensics reviewer adversarially detects AI-generated feel (per EDITORIAL_STYLE.md) and BLOCKs slop. Reusable across all DailyTickers processes.',
  phases: [
    { title: 'Panel', detail: 'senior personas review each artifact (type-aware), fix in place' },
    { title: 'Gate', detail: 'release-gate synthesis per artifact: PASS / FIXED / BLOCK' },
  ],
}

// args = { artifacts: [{ path, type, label? }], applyFixes?: true }
// type ∈ analyses | daily | weekly | retro | scanner | series | tech | landing | generic
let _A = args
if (typeof _A === 'string') { try { _A = JSON.parse(_A) } catch (e) { _A = {} } }
const ARTIFACTS = (_A && _A.artifacts) || []
const APPLY = !_A || _A.applyFixes !== false  // default: reviewers FIX in place

// ---- Senior personas (each may EDIT the file to fix issues, then report) ----
const P = {
  qa: { label:'QA Senior (front-end / release)', mandate:`Audit HTML/release conventions and FIX in place: GTM-T5Z595CW present; brand-bar + brand-nav (Hebdo/Daily/Analyses/Scanner/Radar/Séries); correct data-tab; <link> /assets/report.css (no local assets/, no report-dark.css); Font Awesome 6.4.0; footer.article-footer (never report-footer/site-footer); FAB present where required; ECharts containers all have a matching echarts.init with unique ids and a resize handler (no orphan/empty charts); core.js + tag-renderer.js before </body>; #article-clickable-tags present; no broken internal links (no /index.html, no 404 to non-existent sibling parts); no inline <style> overriding global classes; mobile-responsive (auto-fit/minmax, no fixed grids); ticker-header uses .tm-value/.tm-label (value before label); NO template placeholder bugs (no "N/A"/"Negative"/"Loss" in data tables, no "22/10" risk gauge, no "74.00%" yields); French accents UTF-8 direct where lang=fr.` },
  quant: { label:'Quant Senior (data integrity)', mandate:`Verify EVERY hard number against fresh ground truth and FIX wrong ones. ToolSearch "select:mcp__claude_ai_marketdata__QueryData,mcp__claude_ai_marketdata__Jobs" (Jobs = canonical replacement for the retired CheckJobStatus/ListJobs, used to poll any async QueryData/RunScreener call) and re-fetch the relevant data (quote, technicals, earnings_quarterly, stats, financials, bars_daily) for any ticker/figure cited. Check: prices/levels, market cap, P/E, EV/EBITDA, PEG, beta, margins, EPS beats (actual vs estimate), index/sector/commodity moves, and all computed ratios (R/R, %, win rate, profit factor) recompute correctly. Flag and correct any fabricated, stale, or internally-inconsistent number. For performance reporting (retro/scanner), confirm headline stats reconcile with the underlying table — never let a phantom win/return stand.` },
  trader: { label:'Trader Senior (setup / actionability)', mandate:`Judge tradeability. For analyses/scanner setups: entry/stop/TP coherent vs price + EMAs + ATR; R/R = (TP1-entry)/(entry-stop) >= 1.5 AT AN ACTIONABLE ENTRY within ~3% of the live price (NOT a far un-triggered pullback — that is the fatal "fictional R/R" defect); stop technically placed; not chasing an extended name (>~5-8% above EMA20); invalidation sensible; earnings/event proximity flagged; position-sizing sane for the beta/ATR. For daily/weekly: directional calls and "trade of the week" must be defensible and risk-framed. FIX the trade levels if R/R is fictional; downgrade the call if it is a chase.` },
  risk: { label:'Risk & Compliance Senior', mandate:`Stress risk + compliance and FIX. Dilution/flags: verify via SEC EDGAR (WebSearch) there is no active ATM / S-3 equity / M&A stock deal / mandatory convertible / heavy SBC misrepresented as "clean" — correct the disclosure honestly. Confirm the disclaimer / "not financial advice" block is present. No over-claiming, no invented geopolitical/macro events (we are June 2026 — verify), balanced bull AND bear, prudent language on manipulation/sentiment. Catalyst must not be macro-inverted (e.g. oil shock vs an airline). Flag concentration/correlation issues for any basket.
SIZING CHECK (deterministic, idea #4 — module tools/lib/vol-corr-sizing.js): when the artifact asserts or implies a position SIZE / weight for a single name (a basket line item, a "X% of book", a scanner pick weight), sanity-check it against the vol-adjusted + correlation-aware ceiling. ZERO HALLUCINATION: fetch the name's realized/annualized vol and its correlation to the other basket names from the MCP (ToolSearch "select:mcp__claude_ai_marketdata__PortfolioRisk" — PortfolioRisk exposes correlation + VaR; QueryData/GetSymbolSignals expose realized vol/ATR); if the MCP is down or returns stale/incoherent numbers → MCP HARD STOP (do NOT fabricate vol/corr, report insufficient data). Write {"volAnnualized":<decimal>,"correlation":<|max corr to other names|>,"nlv":<book NLV>,"cash":<cash>} to a temp file and run \`node tools/lib/vol-corr-sizing.js --in <file>\` (Bash). It returns the deterministic combined_pct ceiling (base 20% × vol multiplier × correlation multiplier, clamped 5–25%) + max_size = min(remaining_limit, cash). FLAG over-sizing: a name carried ABOVE its combined_pct ceiling (e.g. a 30% weight on a >50%-vol name whose ceiling is ~10%, or a full-size add to a >0.80-correlated cluster the grid haircuts ×0.70) is a concentration defect — quote the exact vol/corr and the computed ceiling in your notes (like the other numeric personas). CONSULTATIVE by default; escalate to blocking[] only when a HARD stated size clearly breaches the deterministic ceiling AND the piece frames the book as risk-controlled/diversified. If the artifact asserts no per-name size, this check is N/A.` },
  strategist: { label:'Macro/PM Strategist (portfolio coherence)', mandate:`Judge the artifact as ONE VIEW at the PORTFOLIO level — the check per-trade review structurally misses. Do NOT re-validate individual levels; ask whether the book HANGS TOGETHER with its own stated thesis. Concretely: (1) THESIS↔BOOK CONSISTENCY — if the piece declares a regime posture (risk-off / reduce size / defensive / "don't get hurt if the event surprises"), does the basket's AGGREGATE factor tilt actually express it? A "risk-off, half-size before CPI" note paired with a book of high-beta growth/momentum longs is a CONTRADICTION and a BLOCK — the stated posture and the implicit factor bet disagree. (2) IMPLICIT FACTOR BIAS — collapse the basket to its dominant factors (net beta, growth-vs-value, rate-sensitivity/duration, cyclical-vs-defensive, sector/geo concentration). Flag when the "diversified" list is secretly ONE bet (all long-growth, all-momentum, all-rate-sensitive, all-oil-beta). (3) EVENT POSITIONING — is the book long the EXACT factor the named upcoming catalyst (CPI, Fed, oil/Hormuz, jobs) threatens? If the declared main risk is a hot CPI → rates → multiple compression, a growth-heavy book is mispositioned; say so. (4) NARRATIVE↔RISK MATCH — does the stated "what breaks the trade" match the book's ACTUAL dominant risk, or is the real risk elsewhere? FIX by reweighting/trimming/cutting the names that contradict the posture (or by correcting the narrative to match the book) so the thesis and the positions AGREE — one of the two must move. severity=critical + BLOCK when the book contradicts its own stated regime/event posture. This is the "a good analyst dismantles it in 30 seconds" gate.` },
  editor: { label:'Editor Senior (FT/Economist desk)', mandate:`Edit for clarity, structure and credibility, FIX in place: headline/title accurate to the content; sections coherent and in the right order; at least one inline .source-ref per content section (add where missing using verified URLs — Yahoo/Finviz/SEC/IEA/Goldman patterns); tone = serious retail, FT/Economist + terminal precision (no hype, no crypto-bro, no filler); French accents correct; no contradictions; cross-links valid. Do NOT invent facts to fill gaps — flag instead.` },
  board: { label:'Value/Quality Board (5 deterministic investor personas)', mandate:`You embed the DETERMINISTIC "Value/Quality Board" — 5 investor personas (Buffett/Quality, Graham/Deep-value, Lynch/GARP, Munger/Moat, Burry/Contrarian) that are NUMBERED THRESHOLD GRIDS, NOT LLM judgment. You RECALCULATE from fresh fundamentals, you do NOT re-read the article's prose. Ported from virattt/ai-hedge-fund's quant grids (see docs/research/ai-hedge-fund-ideas.md §4) via the module tools/lib/value-quality-board.js.
STEP 1 — identify each real, tradable single-stock ticker the artifact asserts a fundamental/quality/value claim about (skip indices/ETFs/thematics). STEP 2 — for each, ToolSearch "select:mcp__claude_ai_marketdata__QueryData" then fetch QueryData(types="financials,stats,quote", symbols=<TICKER>). ZERO HALLUCINATION: use ONLY the returned numbers; a ratio absent from the MCP surface (FCF, current ratio, ROIC are NOT exposed) stays a FAIL-CLOSED "insufficient data" gap — never invent it. If the MCP is down or returns stale/incoherent data → MCP HARD STOP (do not fabricate a vote; report insufficient data). STEP 3 — write {"ticker":T,"financials":{...},"stats":{...},"quote":{...}} to a temp file and run \`node tools/lib/value-quality-board.js --in <file>\` (Bash). The module returns the 5 pivot-schema votes {signal,confidence,reasoning} + a confidence-weighted board verdict — all deterministic (same input → same output), all auditable. STEP 4 — FLAG contradictions between the article's CLAIMS and the board's chiffres: e.g. the piece calls a name "Buffett-quality" / "compounder" but the Buffett persona is bearish (ROE 9% < 15% threshold, D/E 0.9 > 0.5); calls it "deep value" / "cheap" but Graham & Burry are bearish (P/B 7.7, P/E 30, price >> Graham#); calls it "GARP" but Lynch is bearish (PEG 5). Quote the exact number and threshold in your notes (like the other numeric personas). You are CONSULTATIVE by default — surface the board verdict + per-persona votes so the desk sees who votes what and why, and add fixes/flags. Escalate to blocking[] ONLY on a CLEAR eliminatory contradiction: the artifact makes a HARD, headline fundamental claim (labels a name "Buffett-quality"/"deep value"/"GARP"/"undervalued on fundamentals") that the corresponding persona flatly contradicts with high confidence (>=70) — that is a factual error, correct the claim or BLOCK. Do NOT block merely because personas disagree with a momentum/technical setup — value/quality is one lens, not the whole thesis. If the artifact makes NO fundamental claim about any single stock, return score 100, severity none, notes "no fundamental claim to verify — board N/A". Report score = min persona-agreement quality for the claims checked; put the board summary (e.g. "JNJ: 2 bull/3 bear, BEARISH conf 74") in notes.` },
  slop: { label:'AI-Forensics Senior (anti-slop / undetectability)', mandate:`You are a HOSTILE AI-content DETECTOR, not a friendly editor. Assume the text is AI-written and hunt for proof it is. Read EDITORIAL_STYLE.md (all 3 layers) first, then run \`node tools/check-ai-tells.js <path>\` (Bash) for layer-1 tells. Judge on three axes: (L1 STYLE) signposting/clichés, forced explainer analogies ("picture musical chairs"), em-dash overload, perfect repeated tricolons, aphoristic "closer" flourishes ("X told you nothing, Y told you everything"), cute pairs ("gold and passports"), punch metaphors, uniformly smooth same-length paragraphs. (L2 FINGERPRINT) is there info only someone who actually dug would write — a PRECISE verified catalyst, real institutional flow, a non-consensus asymmetry, a falsifiable thesis — or a generic consensus read a one-line prompt ("write a plain-English newsletter on today's rotation") would reproduce? (L3 SKELETON) does it follow the default template hook→one idea→simple→mental image→a few levels→2-3 invalidations→memorable closer, and does it read like the same machine as prior posts? Score = probability a knowledgeable reader/detector rates it HUMAN (0-100; 100 = indistinguishable from a specific named analyst). severity=critical and add a BLOCK item if score < 75 or any hard tell survives. ALSO BLOCK for three systemic tells even if the prose is clean (L4): (RECURRENCE) if the thesis/structure rehashes a recent post — if given prior posts, compare; a same-day rewrite "simpler and shorter" of the same thesis is a hard tell, demand a genuinely new angle/data/counter-argument or DO NOT SHIP; (DENSITY) if the whole piece reduces to <=3 sentences of real non-obvious info wrapped in padding, BLOCK — prose padding is where LLMs hide, the value must be the data not the wrapping; (REFLEXIVE DEFINITIONS) inline glosses like "a call option is a bet that…" that a regular analyst would not rewrite each time. Note explicitly that for a data-driven publication the higher-value format is data-forward (chart + flow table + tracked levels), prose minimal. FIX in place surgically (kill flourishes, vary structure, de-signpost, cut padding/definitions) WITHOUT breaking verified numbers or the required register (concise, actionable, verifiable, plain enough for a smart 10-year-old); flag anything that genuinely needs a human's own voice. Never approve your own comfort — your reputation is catching AI, not shipping it.` },
}
// Which personas run per artifact type
const MATRIX = {
  analyses: ['qa','quant','trader','risk','strategist','board','editor','slop'],
  scanner:  ['qa','quant','trader','risk','strategist','board','editor','slop'],
  retro:    ['qa','quant','trader','editor','slop'],
  daily:    ['qa','quant','trader','risk','strategist','editor','slop'],
  weekly:   ['qa','quant','trader','risk','strategist','editor','slop'],
  basket:   ['quant','trader','risk','strategist','board','slop'],
  series:   ['qa','quant','risk','editor','slop'],
  tech:     ['qa','quant','editor','slop'],
  substack: ['editor','quant','slop'],
  landing:  ['qa','editor'],
  generic:  ['qa','quant','editor','slop'],
}

const REVIEW_SCHEMA = { type:'object', required:['persona','score','severity','fixed'], properties:{
  persona:{type:'string'}, score:{type:'number'}, severity:{type:'string', enum:['none','minor','major','critical']},
  fixed:{type:'array', items:{type:'string'}}, blocking:{type:'array', items:{type:'string'}}, notes:{type:'string'} } }
const GATE_SCHEMA = { type:'object', required:['path','decision','composite'], properties:{
  path:{type:'string'}, label:{type:'string'}, decision:{type:'string', enum:['PASS','FIXED','BLOCK']},
  composite:{type:'number'}, blocking:{type:'array', items:{type:'string'}}, summary:{type:'string'} } }

function reviewPrompt(a, pk){
  const p = P[pk]
  return `SENIOR REVIEW — you are the **${p.label}** reviewing the DailyTickers ${a.type} artifact at ${a.path}. Read it in full. Be rigorous and senior-level: your job is to catch what a junior missed and to PROTECT the brand and the reader.
${p.mandate}
${APPLY ? 'You MAY edit the file directly to FIX issues you can fix cleanly (Edit/Write). Do not rewrite wholesale; make surgical corrections.' : 'Do NOT edit; report only.'}
Return JSON: persona:"${pk}", score (0-100, your quality score for your dimension), severity (worst issue: none/minor/major/critical), fixed (array of fixes you applied), blocking (array of issues that should BLOCK publish if unfixed), notes (1-2 lines).`
}
function gatePrompt(a, reviews){
  return `You are the RELEASE GATE for ${a.path} (${a.type}${a.label?', '+a.label:''}). The senior panel returned: ${JSON.stringify(reviews,null,0)}.
Decide: composite (0-100, the weakest critical dimension caps it), and decision = "BLOCK" if any unresolved critical/blocking issue remains, "FIXED" if issues existed but were fixed in place (clean to publish), "PASS" if it was already clean. List any remaining blocking[] items and a one-line summary. Be willing to BLOCK — a senior desk does not ship broken or unverifiable work.`
}

phase('Panel')
const results = await pipeline(
  ARTIFACTS,
  async (a) => {
    const personas = MATRIX[a.type] || MATRIX.generic
    const reviews = await parallel(personas.map(pk => () =>
      agent(reviewPrompt(a, pk), { label:`rev:${a.label||a.path.split('/').slice(-2)[0]}:${pk}`, phase:'Panel', schema:REVIEW_SCHEMA })
    ))
    return { a, reviews: reviews.filter(Boolean) }
  },
  (panel) => agent(gatePrompt(panel.a, panel.reviews), { label:`gate:${panel.a.label||panel.a.path.split('/').slice(-2)[0]}`, phase:'Gate', schema:GATE_SCHEMA })
)
const gates = results.filter(Boolean)
const blocked = gates.filter(g=>g.decision==='BLOCK')
log(`Senior review done. PASS:${gates.filter(g=>g.decision==='PASS').length} FIXED:${gates.filter(g=>g.decision==='FIXED').length} BLOCK:${gates.filter(g=>g.decision==='BLOCK').length}${blocked.length?' -> '+blocked.map(g=>g.path).join(','):''}`)
return { gates, blocked }
