'use strict';
// Local-only AAOI revision. It never writes data/analyses-data or analyses/AAOI/index.html.
const fs=require('fs'), path=require('path'), crypto=require('crypto');
const root=path.resolve(__dirname,'../../..');
const run='analyses/AAOI/_runs/20260919-update', data=run+'/data', revision=run+'/revision', primaryDir=run+'/primary';
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const write=(p,v)=>fs.writeFileSync(path.join(root,p),JSON.stringify(v,null,2)+'\n');
const esc=s=>String(s).replace(/~/g,'~0').replace(/\//g,'~1');
function findType(v,type,p='') { if(v&&typeof v==='object'){if(v.type===type)return {value:v,path:p||''}; for(const [k,x] of Object.entries(v)){const r=findType(x,type,p+'/'+esc(k));if(r)return r;}} }
function pearson(a,b){const n=a.length,ma=a.reduce((s,x)=>s+x,0)/n,mb=b.reduce((s,x)=>s+x,0)/n;let xy=0,xx=0,yy=0;for(let i=0;i<n;i++){const x=a[i]-ma,y=b[i]-mb;xy+=x*y;xx+=x*x;yy+=y*y;}return xy/Math.sqrt(xx*yy);}
function beta(a,b){const ma=a.reduce((s,x)=>s+x,0)/a.length,mb=b.reduce((s,x)=>s+x,0)/b.length;let xy=0,xx=0;for(let i=0;i<a.length;i++){xy+=(a[i]-ma)*(b[i]-mb);xx+=(a[i]-ma)**2;}return xy/xx;}
function pct(a,b){return 100*(a/b-1);}
const raw={bars:read(data+'/bars.json'),comparison:read(data+'/comparison_bars.json'),fund:read(data+'/fundamentals.json'),tech:read(data+'/technicals.json'),short:read(data+'/short_squeeze.json'),status:read(data+'/status.json')};
const aaoi=raw.bars.results[0].data[0], ownBars=aaoi.bars, close=ownBars.at(-1)[4], previous=ownBars.at(-2)[4], volume=ownBars.at(-1)[5];
if(ownBars.length!==300||aaoi.served_completed_end!=='2026-09-18')throw Error('AAOI repaired 300-session input is not present');
const financial=findType(raw.fund,'instrument_comprehensive_financial'), stats=findType(raw.fund,'instrument_comprehensive_stats'), tech=findType(raw.tech,'instrument_technicals'), vwap=findType(raw.tech,'instrument_vwap'), calendar=findType(raw.fund,'instrument_calendar'), shortSeries=findType(raw.short,'instrument_short_interest_series');
if(!financial||!stats||!tech||!vwap||!calendar||!shortSeries)throw Error('A required AAOI facet is absent');
const compItems=raw.comparison.data.items[0].results[0].data;
const labels={LITE:'Leader optique',COHR:'Pair optique direct',CIEN:'Réseau et transport',VIAV:'Test et optique',GLW:'Fibre et verre spécial',AXTI:'Substrats amont',CRDO:'DSP/connectivité',MRVL:'Silicium de connectivité',CSCO:'Équipement réseau',ANET:'Réseau data center',MSFT:'Client cloud indirect',AMZN:'Client cloud indirect',META:'Client cloud indirect',NVDA:'Demande IA indirecte',SMH:'ETF semi-conducteurs',SOXX:'ETF semi-conducteurs',QQQ:'ETF croissance',SPY:'Marché large'};
const groups={LITE:'Leader et pair direct',COHR:'Leader et pair direct',CIEN:'Optique/réseau',VIAV:'Optique/réseau',GLW:'Amont',AXTI:'Amont',CRDO:'Connectivité',MRVL:'Connectivité',CSCO:'Aval réseau',ANET:'Aval réseau',MSFT:'Demande cloud indirecte',AMZN:'Demande cloud indirecte',META:'Demande cloud indirecte',NVDA:'Demande IA indirecte',SMH:'ETF / contrôle',SOXX:'ETF / contrôle',QQQ:'ETF / contrôle',SPY:'ETF / contrôle'};
const byDate=new Map(ownBars.map(b=>[b[0],b]));
const comparisons=compItems.map((c,i)=>{const common=c.bars.filter(b=>byDate.has(b[0]));const x=[],y=[];for(let j=1;j<common.length;j++){x.push(Math.log(common[j][4]/common[j-1][4]));const d0=byDate.get(common[j-1][0]),d1=byDate.get(common[j][0]);y.push(Math.log(d1[4]/d0[4]));}const corr=pearson(x,y),ret5=pct(common.at(-1)[4],common.at(-6)[4]),ret21=pct(common.at(-1)[4],common.at(-22)[4]);return {ticker:c.symbol,name:labels[c.symbol]||c.symbol,group:groups[c.symbol]||'Comparaison',order:i+1,correlation:Number(corr.toFixed(4)),beta:Number(beta(x,y).toFixed(4)),rSquared:Number((corr*corr).toFixed(4)),observations:x.length,return5d:Number(ret5.toFixed(2)),return21d:Number(ret21.toFixed(2)),windowStart:common[0][0],windowEnd:common.at(-1)[0]};});
if(comparisons.length<12||comparisons.some(x=>x.observations!==124))throw Error('Comparable window must contain at least 12 aligned 124-return comparisons');
const own5=pct(close,ownBars.at(-6)[4]), own21=pct(close,ownBars.at(-22)[4]);
const f=financial.value,s=stats.value,t=tech.value,v=vwap.value, ss=shortSeries.value.points.at(-1);
const marketCap=close*s.sharesOutstanding, netDebt=f.totalDebt-f.totalCash, ev=marketCap+netDebt;
const primary=[
 ['2026-08-06','10-Q','0001437749-26-026278','AAOI-2026Q2-10Q.htm','https://www.sec.gov/Archives/edgar/data/1158114/000143774926026278/aaoi20260630_10q.htm','Résultats Q2, concentration clients, besoins de capacité et risques.'],
 ['2026-08-21','424B5','0001104659-26-099685','AAOI-20260821-424B5-ATM.htm','https://www.sec.gov/Archives/edgar/data/1158114/000110465926099685/tm2623389-1_424b5.htm','Supplément ATM jusqu’à 600 M$, usages et limites du dénominateur.'],
 ['2026-09-01','8-K','0001683168-26-006862','AAOI-20260901-8K-Texas.htm','https://www.sec.gov/Archives/edgar/data/1158114/000168316826006862/aaoi_8k.htm','Baux Texas, engagements et option d’achat.'],
 ['2026-09-10','8-K','0001683168-26-007057','AAOI-20260910-8K-Houston.htm','https://www.sec.gov/Archives/edgar/data/1158114/000168316826007057/aaoi_8k.htm','Acquisition cash du bâtiment Houston 3.'],
 ['2026-09-15','8-K','0001683168-26-007160','AAOI-20260915-8K-Ningbo.htm','https://www.sec.gov/Archives/edgar/data/1158114/000168316826007160/aaoi_8k.htm','Bail d’usine Ningbo et obligation financière.']
].map(([date,form,accession,file,url,finding])=>({date,form,accession,path:primaryDir+'/'+file,url,sha256:sha(fs.readFileSync(path.join(root,primaryDir,file))),finding,claim_extracts:[]}));
// The excerpts below are exact, reviewable locators in the hashed local SEC files.  They let a
// rendered number point to the document and paragraph that actually supports it.
primary[0].claim_extracts=[
 {key:'amazon_warrant',line:3706,needle:'purchase up to an aggregate of 7,945,399 shares',shares:7945399,strike:23.6956,vested_at_issuance:1324233,unvested_conditional:6621166,purchase_condition_usd:4000000000,term_years:10},
 {key:'q2_revenue',line:879,needle:'191,922',revenue_usd:191922000,period_end:'2026-06-30'},
 {key:'top_ten_customer_concentration',line:5794,needle:'99%',pct:99,period_end:'2026-06-30'}
];
primary[1].claim_extracts=[
 {key:'atm_capacity',line:31,needle:'aggregate offering price of up to $600,000,000',capacity_usd:600000000},
 {key:'prospectus_share_base',line:588,needle:'84,906,289 shares',shares:84906289,as_of:'2026-08-20'},
 {key:'rsu_excluded',line:619,needle:'1,090,055 shares of common stock issuable upon vesting',shares:1090055,as_of:'2026-08-20'},
 {key:'psu_excluded',line:623,needle:'629,463 shares of common stock issuable upon the satisfaction',shares:629463,as_of:'2026-08-20'},
 {key:'atm_illustration',line:660,needle:'4,647,561 shares of our common stock at a price of $129.10',illustrative_shares:4647561,illustrative_price:129.10,illustrative_proceeds_usd:600000000,as_of:'2026-08-20'}
];
const manifest={kind:'primary_sec_manifest_v1',ticker:'AAOI',as_of:'2026-09-19',inventory_count:5,inventory_screened_count:5,opened_count:5,reviewed_count:5,decision_relevant_count:5,local_primary_count:5,review_scope:'Cinq dépôts décisionnels AAOI ouverts et archivés. Inventaire ciblé : ce n’est pas une réconciliation exhaustive de tous titres dilutifs.',documents:primary,semantic_findings:{capital_and_capacity:{source_path:'.agent/analyses-refresh-20260919/aaoi-revision/primary-findings.md',source_sha256:'PENDING',source_needles:['ATM jusqu’à 600 M$','1 090 055 RSU et 629 463 PSU','warrant Amazon : 7 945 399 actions','engagements Texas, Houston et Ningbo']}}};
const findings='# AAOI — constats des primaires archivés\n\n- Le supplément 424B5 du 21 août décrit un ATM jusqu’à 600 M$; sa capacité reste traitée comme ouverte en l’absence d’un dépôt émetteur qui l’épuise. Son illustration au 20 août est une hypothèse de prospectus, non un dénominateur courant.\n- À la même date, le prospectus affiche 84 906 289 actions et exclut 1 090 055 RSU et 629 463 PSU; ce ne sont pas des ajouts au total courant.\n- Le 10-Q décrit le warrant Amazon : 7 945 399 actions au strike de 23,6956 $, dont 1 324 233 exerçables à l’émission et 6 621 166 conditionnelles à 4 Md$ d’achats sur dix ans.\n- Les dépôts de septembre documentent des engagements Texas, Houston et Ningbo : ils signalent un besoin de capacité/cash, sans prouver utilisation, demande ou émission nouvelle.\n';
fs.writeFileSync(path.join(root,'.agent/analyses-refresh-20260919/aaoi-revision/primary-findings.md'),findings);manifest.semantic_findings.capital_and_capacity.source_sha256=sha(fs.readFileSync(path.join(root,'.agent/analyses-refresh-20260919/aaoi-revision/primary-findings.md')));write(revision+'/primary-manifest.json',manifest);
const archive=read(revision+'/AAOI-archive-snapshot-20260828.json');
const a={
 meta:{lang:'fr',dir:'ltr',level:'intermediate',tags:['us','equities','ai-chain','optics','technology'],grade:'C+',date:'2026-09-19',dateDisplay:'19 septembre 2026',version:3,status:'no-trade',assetType:'stock',levelsCloseDate:'2026-09-18',description:'AAOI : optique de data center, capacité et dilution. Révision locale au dernier close certifié, sans ordre actif.',ogDescription:'AAOI : demande optique, capacité, ATM et risque par action. Aucun ordre actif.'},
 header:{ticker:'AAOI',name:'Applied Optoelectronics, Inc.',exchange:'NASDAQ',sector:'Équipements de communication',price:Number(close.toFixed(2)),changePct:Number(pct(close,previous).toFixed(4)),badges:[{text:'AUCUN ORDRE ACTIF',color:'amber'},{text:'Optique data center',color:'blue'}],metrics:{marketCap:(marketCap/1e9).toFixed(2)+' Md$',volume:(volume/1e6).toFixed(2)+' M',evEbitda:'N/M (EBITDA négatif)'},halalStatus:'unknown'},
 verdict:{score:38,conviction:'Low',bias:'Neutral',confidence:'Score éditorial non prédictif : les gates de sources et la réconciliation du capital restent insuffisants.',summary:'La demande optique doit encore se traduire en marges, cash et valeur par action. La capacité ATM et les engagements industriels maintiennent une incertitude sur le dénominateur. Le contrat historique est expiré et non revalidé. RankBeta et le calendrier CIEN restent bloqués : le dossier est NO TRADE.',whyBuy:['Les modules optiques exposent AAOI aux besoins de connectivité des data centers; la croissance dépend toutefois des commandes et de leur rentabilité.','Les qualifications clients et l’intégration de composants peuvent soutenir la position concurrentielle si les rampes se confirment.','Les nouvelles capacités peuvent augmenter les volumes livrables, à condition que la demande absorbe les engagements de cash.'],whyAvoid:['L’EBITDA fournisseur est négatif : aucun scénario de multiple n’est publié.','La capacité ATM est potentielle; le total pleinement dilué actuel n’est pas réconcilié.','Une concentration élevée des clients expose les volumes et les marges aux reports de programme.','RankBeta est indisponible et le calendrier CIEN est incomplet : le blast radius reste descriptif.'],controlChecklist:[{label:'Source obligatoire',status:'blocked',statusLabel:'RankBeta indisponible',evidence:'Échec fournisseur documenté dans les limites du run.',action:'Ne pas certifier la transmission ni publier.'},{label:'Calendrier comparable',status:'blocked',statusLabel:'CIEN indisponible',evidence:'La cellule calendrier CIEN est indisponible.',action:'Ne pas déclarer un calendrier exhaustif.'},{label:'Contrat historique',status:'blocked',statusLabel:'Expiré et non revalidé',evidence:'Le prédicat historique est documenté dans le snapshot, mais pas rejoué sur cette fenêtre.',action:'Aucun ordre, aucun stop testé.'}]},
 business:{theme:'Capacité optique pour data centers et réseaux',overview:'<p>AAOI fabrique des composants et modules fibre optique pour data centers, réseaux câble et accès. Une hausse des déploiements peut soutenir les volumes, mais elle doit passer par les calendriers clients, les prix et l’utilisation réelle des capacités.</p><p>Le rapport trimestriel décrit une concentration élevée : une modification de programme chez un grand client peut dominer le signal sectoriel. Le dossier sépare donc la demande IA indirecte de la preuve de commande et de marge propre à AAOI.</p><p>Les baux et l’achat immobilier de septembre matérialisent une option de capacité et une consommation de cash. Ils ne prouvent ni une demande sécurisée ni un bénéfice par action.</p>',moat:'L’intégration des composants optiques et les qualifications clients peuvent réduire les frictions, mais ne neutralisent ni la concentration, ni la concurrence, ni le risque de financement.',segments:[{name:'Data center',description:'Modules et composants pour liaisons à haut débit; moteur de demande, dépendant des rampes clients.'},{name:'CATV et accès',description:'Produits fibre et câble; cycle et marges distincts.'}],sourceRefs:primary.slice(0,2).map(x=>({name:'AAOI '+x.form,url:x.url,date:x.date})),coverageMatrix:[{facet:'Cours et barres quotidiennes',status:'COUVERT — 300 SÉANCES',decision:'Close du 18 septembre certifié; continuité réparée, calculs déterministes.'},{facet:'Comparables',status:'CALCUL LOCAL / GATE BLOQUÉ',decision:'18 comparables et 124 rendements communs; RankBeta échoue HTTP 403.'},{facet:'Calendrier',status:'PARTIEL / BLOQUÉ',decision:'AAOI fourni, CIEN indisponible.'},{facet:'Fondamentaux',status:'INSTANTANÉ FOURNISSEUR',decision:'Période comptable non inférée; EBITDA négatif.'},{facet:'Capital / SEC',status:'PRIMAIRES ARCHIVÉES',decision:'ATM et engagements documentés, dilution totalement diluée non réconciliée.'},{facet:'Options / flux',status:'INSTANTANÉ',decision:'Aucune direction ou probabilité inférée.'},{facet:'Insiders',status:'INSUFFISANT',decision:'Couverture SEC officielle incomplète; aucune absence d’achat/vente ne peut être déclarée.'}]},
 news:[{date:'2026-08-21',title:'ATM AAOI jusqu’à 600 M$',impact:'negative',detail:'Mécanisme de vente d’actions et usages possibles; capacité traitée comme ouverte.',source:'SEC',sourceUrl:primary[1].url},{date:'2026-09-01',title:'Engagements de baux Texas',impact:'neutral',detail:'Capacité et engagements financiers; ni demande ni utilisation ne sont prouvées.',source:'SEC',sourceUrl:primary[2].url},{date:'2026-09-15',title:'Bail Ningbo',impact:'neutral',detail:'Obligation financière et capacité industrielle à suivre.',source:'SEC',sourceUrl:primary[4].url}],
 fundamentals:{rows:[{metric:'Revenus Q2 2026',value:'191,9 M$',signal:'Primaire, trimestre clos le 30 juin',signalColor:'blue',note:'10-Q : période identifiée.'},{metric:'EBITDA fournisseur',value:(f.ebitda/1e6).toFixed(1)+' M$',signal:'Période fournisseur non identifiée',signalColor:'amber',note:'Aucun multiple ni scénario de valorisation.'},{metric:'Trésorerie fournisseur',value:(f.totalCash/1e6).toFixed(1)+' M$',signal:'Période fournisseur non identifiée',signalColor:'amber'},{metric:'Dette fournisseur',value:(f.totalDebt/1e6).toFixed(1)+' M$',signal:'Période fournisseur non identifiée',signalColor:'amber'}],sourceRefs:[{name:'AAOI 10-Q',url:primary[0].url,date:primary[0].date}]},
 earnings:{quarters:[],nextEarnings:'Calendrier fournisseur : à confirmer par l’émetteur',beatNote:'Le 10-Q établit des résultats trimestriels au 30 juin. Aucune guidance non vérifiée ni surprise fournisseur n’est traitée comme réalisée.',sourceRefs:[{name:'AAOI 10-Q',url:primary[0].url,date:primary[0].date}]},
 capitalStructure:{sharesOutstanding:'84,906,289 au 20 août (prospectus)',dilutionRisk:'critical',warrants:[{series:'Amazon customer warrant',type:'Warrant client',strike:23.6956,shares:'7,945,399 maximum',expiration:'Dix ans depuis l’émission',note:'1,324,233 exerçables à l’émission; 6,621,166 conditionnelles à 4 Md$ d’achats.',status:'ITM'},{series:'RSU exclues du prospectus',type:'RSU',shares:'1,090,055 au 20 août',expiration:'Vesting à confirmer',note:'Exclues de la base du prospectus; non ajoutées au total courant.'},{series:'PSU exclues du prospectus',type:'PSU',shares:'629,463 au 20 août',expiration:'Vesting de performance',note:'Exclues de la base du prospectus; condition de performance.'}],atm:{active:true,authorized:'Jusqu’à 600 M$ (capacité)',used:'Non réconcilié',remaining:'Non certifié'},shareHistory:'Matrice primaire : le prospectus exclut 1,090,055 RSU et 629,463 PSU au 20 août. Le warrant Amazon est décrit séparément. L’illustration ATM de 4,647,561 actions à 129,10 $ est une hypothèse historique du prospectus, pas une émission ni un total courant. Aucun pont fully diluted au 18 septembre n’est inventé.',sourceRefs:primary.slice(0,2).map(x=>({name:x.form+' '+x.date,url:x.url,date:x.date}))},
 filingsReview:{summary:'Cinq dépôts SEC primaires archivés. Le corpus est ciblé et ne permet pas une conclusion exhaustive sur toute émission future.',filings:primary.map(x=>({date:x.date,form:x.form,accession:x.accession,finding:x.finding,url:x.url})),contrarianRisks:['La capacité industrielle ne prouve ni utilisation ni demande.', 'Une capacité ATM n’est pas une émission réalisée.', 'Les instruments et conditions connus ne constituent pas un total fully diluted courant.']},
 insiders:{recentTransactions:[],signal:'La couverture fournisseur est incomplète; aucune direction agrégée ni absence d’achat/vente n’est déclarée.',sourceRefs:[]},
 shortInterest:{siPct:ss.short_pct_float.toFixed(2)+' %',daysToCover:ss.days_to_cover.toFixed(2),trend:'Short interest FINRA au règlement du '+ss.settlement_date+'; observation décalée du close de référence.',sourceRefs:[]},
 options:{maturity:'Snapshot options fournisseur',maxPain:'103',cpRatio:'1,78',unusual:'Instantané seulement : aucune direction ni probabilité inférée.',sourceRefs:[]},
 technicals:{ema20:Number(t.ema20.toFixed(2)),ema50:Number(t.ema50.toFixed(2)),ema200:Number(t.ema200.toFixed(2)),rsi14:Number(t.rsi.toFixed(2)),macd:Number(t.macd.toFixed(2)),macdSignal:Number(t.signal.toFixed(2)),atr14:Number(t.atr.toFixed(2)),ma50Type:'EMA',ma200Type:'EMA',ma50Available:true,ma200Available:true,badges:['Contexte descriptif','Aucun déclencheur'],supports:[],resistances:[],setupNote:'Indicateurs fournis dans un snapshot fournisseur. Les 300 séances réparent la continuité du close, mais la construction EMA/RSI/ATR fournisseur n’est pas recalculée ici; aucun déclencheur, entrée ou stop n’en découle.',sourceRefs:[]},
 performance:{windowReturns:{label:'Rendement de prix sur 21 séances, dividendes non réinvestis',startDate:ownBars.at(-22)[0],endDate:ownBars.at(-1)[0],rows:[{ticker:'AAOI',returnPct:Number(own21.toFixed(2))},...comparisons.map(x=>({ticker:x.ticker,returnPct:x.return21d}))]},sourceRefs:[]},
 blastRadius:{asOf:'2026-09-18',observationTime:raw.status.captured_at,window:'Du 23 mars au 18 septembre 2026',methodology:'124 rendements logarithmiques journaliers communs. Corrélation de Pearson; β AAOI vs pair = cov(r_AAOI,r_pair) / var(r_pair); R² = corrélation². Rendements de prix 5/21 séances; pas de dividendes réinvestis. Calcul descriptif local : RankBeta reste indisponible.',groups:Object.entries({ 'Leader / pairs directs':['LITE','COHR'],'Optique et réseau':['CIEN','VIAV','GLW','CRDO','MRVL'],'Amont / aval':['AXTI','CSCO','ANET'],'Demande cloud et IA':['MSFT','AMZN','META','NVDA'],'Contrôles ETF':['SMH','SOXX','QQQ','SPY']}).map(([name,tickers],i)=>({name,order:i<3?1:2,transmission:'Lien économique contextuel; la corrélation ne prouve ni client, ni contrat, ni causalité.',symbols:comparisons.filter(x=>tickers.includes(x.ticker)).map(x=>({ticker:x.ticker,role:x.name,relationClass:x.ticker==='LITE'||x.ticker==='COHR'?'direct_peer':(['SMH','SOXX','QQQ','SPY'].includes(x.ticker)?'sector_proxy':'second_order'),correlation:x.correlation,beta:x.beta,r2:x.rSquared,observations:x.observations,return5d:x.return5d,return21d:x.return21d,readThrough:'Mesure de co-mouvement historique; transmission économique à confirmer.',confidence:'low',eventRisk:x.ticker==='CIEN'?'Calendrier CIEN indisponible.':'Calendrier fournisseur à confirmer.'}))})),scenarios:[{scenario:'bullish',trigger:'La demande et la capacité se traduisent en marges et cash par action.',firstOrder:'Utilisation et prix soutiennent les modules optiques.',secondOrder:'Les comparables suivent seulement si leurs propres moteurs confirment.',confirmation:'Résultats émetteur et dénominateur réconciliés.',contradiction:'ATM ou concentration absorbent le bénéfice par action.'},{scenario:'mixed',trigger:'La demande existe mais financement et capacité avancent plus vite.',firstOrder:'Volumes sans amélioration correspondante de marge.',secondOrder:'Co-mouvements hétérogènes.',confirmation:'Cash ou marge ne suivent pas les revenus.',contradiction:'Amélioration durable marge/cash par action.'},{scenario:'bearish',trigger:'Retards clients, pression prix ou sous-utilisation.',firstOrder:'Marge et besoin de financement se dégradent.',secondOrder:'Les comparables peuvent diverger.',confirmation:'Guidance, marge ou cash déçoivent.',contradiction:'Commandes et cash par action dépassent les attentes.'}],contradictions:['Une corrélation élevée ne démontre pas une causalité.', 'Les prix et les calendriers des comparables sont des contrôles, non des preuves client.', 'RankBeta et le calendrier CIEN bloquent toute certification de transmission.'],missingData:['RankBeta : source obligatoire indisponible côté fournisseur.', 'Calendrier CIEN indisponible.', 'Aucun classement large ni causalité n’est inféré.'],sourceRefs:[]},
 
 risks:{riskScore:8,riskProfile:'High',riskSummary:'Risque élevé de dilution et de financement; forte dépendance aux calendriers clients et à la rentabilisation des capacités.',riskCards:[{title:'Dilution et dénominateur',severity:'critical',points:['ATM jusqu’à 600 M$ ouvert faute de preuve d’épuisement.','RSU, PSU, convertibles et warrant exigent une réconciliation entièrement diluée.']},{title:'Exécution de capacité',severity:'high',points:['Texas, Houston et Ningbo créent des engagements.','La capacité n’établit pas l’utilisation ni la demande.']},{title:'Concentration et marge',severity:'high',points:['Les grands clients peuvent décaler les déploiements.','La croissance ne suffit pas sans marge et cash par action.']},{title:'Sources bloquées',severity:'high',points:['RankBeta HTTP 403.','Calendrier CIEN UNAVAILABLE.']}]},
 
 tradeIdea:{archiveReferenceClose:archive.meta.levelsCloseDate,entry:archive.tradeIdea.entry,stop:archive.tradeIdea.stop,tp1:archive.tradeIdea.tp1,tp2:archive.tradeIdea.tp2,stopPct:archive.tradeIdea.stopPct,tp1Pct:archive.tradeIdea.tp1Pct,tp2Pct:archive.tradeIdea.tp2Pct,rr:archive.tradeIdea.rr,status:'no-trade',statusNote:'Archive conservée : son prédicat historique est documenté mais expiré et non revalidé sur la fenêtre actuelle; aucun niveau ne constitue un ordre, un stop actif ou une cible.',thesis:'Un nouveau contrat exigerait de rejouer le prédicat historique, restaurer les sources, réconcilier dilution/capital et contrôler les événements.',catalysts:['Nouvelle opening range RTH collectée et prédicat historique rejoué.', 'Spread, slippage, risque portefeuille et événements revalidés.', 'Sources RankBeta et calendrier CIEN restaurées.'],invalidation:['Les anciens niveaux sont informatifs seulement; aucun transfert vers une exécution actuelle.']},
 globalScore:{keyTakeawaysPositive:['Exposition aux liaisons optiques data center.','Qualifications clients et intégration des composants optiques.','Capacité supplémentaire disponible sous réserve de demande rentable.'],keyTakeawaysNegative:['EBITDA et marge opérationnelle négatifs.','ATM et fully diluted shares non réconciliés.','RankBeta et calendrier CIEN bloquent la validation.']},
 disclaimer:'Révision locale de recherche au close certifié. Pas une recommandation, pas une attestation AQ finale, pas un ordre. Les données ou gates indisponibles restent bloquants.'
};
const judgments={ticker:'AAOI',score_components:{business:12,technical:8,capital:-10,source_gate:-12,dilution:-10,risk:50},judgments:{'meta.version':{value:3,reason:'Identifiant de révision locale, distinct de toute donnée de marché.'},'meta.date':{value:'2026-09-19',reason:'Date de finalisation du dossier local, distincte de la clôture.'},'meta.dateDisplay':{value:'19 septembre 2026',reason:'Format français de la date éditoriale locale.'},'verdict.score':{value:38,reason:'Score éditorial additif : points de business et technique, pénalités capital/source/dilution et risque explicitement séparé.'},'risks.riskScore':{value:8,reason:'Jugement qualitatif sur dix : dilution, capacités, concentration et gates de source; pas une probabilité.'}}};
a.blastRadius.groups.forEach((g,i)=>judgments.judgments['blastRadius.groups.'+i+'.order']={value:g.order,reason:'Classement éditorial du mécanisme économique, non une mesure de causalité.'});
write(revision+'/editorial-judgments.json',judgments);
write(revision+'/calculations.json',{kind:'aaoi_calculations_v2',ticker:'AAOI',reference_close:'2026-09-18',close,returns:{aaoi5:Number(own5.toFixed(8)),aaoi21:Number(own21.toFixed(8))},comparisons,beta_definition:'β AAOI vs pair = cov(r_AAOI,r_pair) / var(r_pair), sur les rendements logarithmiques journaliers communs.',technicalInputs:{rsi:t.rsi,ema20:t.ema20,ema50:t.ema50,ema200:t.ema200,macd:t.macd,signal:t.signal,atr:t.atr,vwap:v.vwap},valuationScenario:{status:'non_applicable',reason_code:'NON_POSITIVE_EBITDA',reason:'EBITDA fournisseur négatif : aucun multiple, prix conditionnel, EV, equity value ou downside n’est calculé.',basis:{input_path:data+'/fundamentals.json',input_sha256:sha(fs.readFileSync(path.join(root,data+'/fundamentals.json'),'utf8')),source_pointer:financial.path+'/ebitda'}},limitations:['RankBeta required source failed upstream HTTP 403.','CIEN calendar is UNAVAILABLE.','No fully diluted share reconciliation.','Historic activation predicate is expired and was not rerun.','No active trade levels.']});
write(revision+'/AAOI.json',a);
const inputs=[];function input(name,p,kind){const row={name,path:p,sha256:sha(fs.readFileSync(path.join(root,p),'utf8'))};if(kind)row.kind=kind;inputs.push(row);return row;}
const ist=input('status',data+'/status.json'),ib=input('bars',data+'/bars.json'),ic=input('comparison',data+'/comparison_bars.json'),iff=input('fundamentals',data+'/fundamentals.json'),it=input('technicals',data+'/technicals.json'),is=input('short',data+'/short_squeeze.json'),io=input('options',data+'/options.json'),ip=input('primary',revision+'/primary-manifest.json','primary_sec_manifest_v1'),ia=input('archive',revision+'/AAOI-archive-snapshot-20260828.json','archived_analysis'),ij=input('judgments',revision+'/editorial-judgments.json','editorial_judgment');
const row=n=>inputs.find(x=>x.name===n), prov=(name,pointer,method,additional_inputs=[])=>({input_name:name,input_path:row(name).path,input_sha256:row(name).sha256,source_pointer:pointer,method,...(additional_inputs.length?{additional_inputs}: {})}),dep=(name,pointer)=>({input_path:row(name).path,input_sha256:row(name).sha256,source_pointer:pointer});
const B='/results/0/data/0/bars',F=financial.path,S=stats.path,T=tech.path,V=vwap.path,SH=shortSeries.path;
const compPointer=ticker=>{const i=compItems.findIndex(x=>x.symbol===ticker);if(i<0)throw Error('Missing comparable '+ticker);return '/data/items/0/results/0/data/'+i+'/bars';};
const get=(o,p)=>p.split('.').reduce((x,k)=>x?.[k],o),claims={},methods={},strings={};
function docForUrl(url){const i=primary.findIndex(x=>x.url===url);if(i<0)throw Error('Primary missing '+url);return i;}
function primaryExtract(doc,key){const n=primary[doc].claim_extracts.findIndex(x=>x.key===key);if(n<0)throw Error('Primary extract missing '+doc+'/'+key);return '/documents/'+doc+'/claim_extracts/'+n;}
function sourceFor(p){
 if(judgments.judgments[p])return prov('judgments','/judgments/'+esc(p)+'/value',judgments.judgments[p].reason);
 if(p==='tradeIdea.archiveReferenceClose')return prov('archive','/meta/levelsCloseDate','Clôture de référence du snapshot historique, jamais le cours actuel.');
 if(/^tradeIdea\.(entry|stop|tp1|tp2)$/.test(p))return prov('archive','/'+p.replaceAll('.','/'),'Niveau exact conservé depuis le snapshot historique et explicitement non exécutable.');
 if(/^tradeIdea\.(stopPct|tp1Pct|tp2Pct|rr)$/.test(p))return {...prov('archive','/tradeIdea','Géométrie recalculable à partir des niveaux historiques conservés.'),derivation:'archived_trade_geometry'};
 if(p==='meta.levelsCloseDate')return prov('bars',B+'/299/0','Date du dernier close quotidien certifié.');
 if(p==='header.price')return prov('bars',B+'/299/4','Dernier close quotidien certifié.');
 if(p==='header.changePct')return prov('bars',B+'/299/4','100*(close final/close précédent−1).',[dep('bars',B+'/298/4')]);
 if(p==='header.metrics.marketCap')return prov('bars',B+'/299/4','Close × actions fournisseur; indicatif, pas fully diluted.',[dep('fundamentals',S+'/sharesOutstanding')]);
 if(p==='header.metrics.volume')return prov('bars',B+'/299/5','Volume de la dernière séance, affiché en millions.');
 if(p.startsWith('technicals.'))return prov('technicals',T,'Indicateur du snapshot fournisseur; les 300 séances servent uniquement à certifier le close et les rendements locaux. Aucun signal d’exécution.',[dep('bars',B)]);
 if(p.startsWith('fundamentals.rows.0.'))return prov('primary',primaryExtract(0,'q2_revenue'),'Revenu primaire du trimestre clos le 30 juin 2026, affiché en millions.');
 if(/^fundamentals\.rows\.[123]\./.test(p)){const key={1:'ebitda',2:'totalCash',3:'totalDebt'}[Number(p.split('.')[2])];return prov('fundamentals',F+'/'+key,'Valeur fournisseur affichée en millions; période comptable non inférée.');}
 if(p==='earnings.nextEarnings')return prov('fundamentals',calendar.path+'/nextEarningsDate','Date calendrier fournisseur explicitement qualifiée, non confirmée par l’émetteur.');
 if(p.startsWith('earnings.'))return prov('primary',primaryExtract(0,'q2_revenue'),'Résultats trimestriels et qualification du calendrier à partir du 10-Q primaire.');
 if(/^capitalStructure\.warrants\.\d+\./.test(p)){const i=Number(p.split('.')[2]);return prov('primary',i===0?primaryExtract(0,'amazon_warrant'):primaryExtract(1,i===1?'rsu_excluded':'psu_excluded'),i===0?'Extrait 10-Q du warrant Amazon : volume, strike, durée et conditions.':'Extrait 424B5 des instruments exclus du prospectus, sans ajout au total courant.');}
 if(p.startsWith('capitalStructure.atm.'))return prov('primary',primaryExtract(1,'atm_capacity'),'Capacité maximale du supplément 424B5; ni émission réalisée ni capacité restante certifiée.');
 if(p==='capitalStructure.sharesOutstanding')return prov('primary',primaryExtract(1,'prospectus_share_base'),'Base d’actions du prospectus au 20 août, pas le total fully diluted de référence.');
 if(p==='capitalStructure.shareHistory')return prov('primary',primaryExtract(1,'rsu_excluded'),'RSU et PSU exclus du prospectus, plus illustration ATM historique.',[dep('primary',primaryExtract(1,'psu_excluded')),dep('primary',primaryExtract(1,'atm_illustration')),dep('primary',primaryExtract(0,'amazon_warrant'))]);
 const ref=p.match(/^(.*)\.sourceRefs\.(\d+)\.(date|url|name)$/);if(ref){const x=get(a,ref[1]+'.sourceRefs.'+ref[2]),i=docForUrl(x.url);return prov('primary','/documents/'+i,'Métadonnée bibliographique du document primaire ouvert.');}
 if(/^news\.\d+\.(date|sourceUrl|title)$/.test(p)){const i=docForUrl(a.news[Number(p.split('.')[1])].sourceUrl);return prov('primary','/documents/'+i,'Date, URL ou titre associés au document primaire exact.');}
 if(/^filingsReview\.filings\.\d+\./.test(p)){const i=Number(p.split('.')[2]);return prov('primary','/documents/'+i,'Métadonnée ou constat du dépôt primaire exact.');}
 if(p.startsWith('shortInterest.'))return prov('short',SH,'Dernier point FINRA disponible; affichage retardé explicitement.');
 if(p.startsWith('options.'))return prov('options','/data/items/0/results/0/data/0','Snapshot options fournisseur; aucune inférence directionnelle.');
 if(p.startsWith('performance.windowReturns.')){const m=p.match(/rows\.(\d+)/),ticker=m?a.performance.windowReturns.rows[Number(m[1])].ticker:'AAOI';return prov(ticker==='AAOI'?'bars':'comparison',ticker==='AAOI'?B:compPointer(ticker),'100*(dernier close / close 21 séances auparavant−1), prix seulement.');}
 if(p==='blastRadius.asOf')return prov('bars',B+'/299/0','Date du dernier close quotidien certifié.');
 if(p==='blastRadius.observationTime')return prov('status','/captured_at','Horodatage exact de la collecte gouvernée, distinct du close.');
 if(p==='blastRadius.window'||p==='blastRadius.methodology')return prov('comparison',compPointer('LITE'),'Fenêtre commune et formule de comparaison, à partir de séries alignées.',[dep('bars',B)]);
 if(/^blastRadius\.groups\.\d+\.order$/.test(p))return prov('judgments','/judgments/'+esc(p)+'/value',judgments.judgments[p].reason);
 const bm=p.match(/^blastRadius\.groups\.(\d+)\.symbols\.(\d+)\.(.+)$/);if(bm){const x=a.blastRadius.groups[Number(bm[1])].symbols[Number(bm[2])],field=bm[3];return prov('comparison',compPointer(x.ticker),field==='eventRisk'&&x.ticker==='CIEN'?'Calendrier CIEN indisponible, qualifié comme tel.':'Série exacte du ticker; corrélation, β AAOI vs pair, R², observations et rendements sont déterministes.',[dep('bars',B)]);}
 if(p.startsWith('business.coverageMatrix.0.'))return prov('bars',B,'300 séances quotidiennes continues et dernier close certifié.');
 if(p.startsWith('business.coverageMatrix.1.'))return prov('comparison',compPointer('LITE'),'Univers et fenêtre commune; limite RankBeta explicitement séparée.',[dep('bars',B)]);
 if(p.startsWith('business.coverageMatrix.'))return prov('primary','/documents/0','État de couverture décrit avec limites explicites.');
 if(p==='verdict.summary'||p.startsWith('verdict.')||p.startsWith('risks.')||p.startsWith('disclaimer'))return prov('primary',primaryExtract(1,'atm_capacity'),'Constat éditorial de capacité/dilution avec limitations explicites.',[dep('archive','/tradeIdea'),dep('bars',B),dep('fundamentals',F)]);
 throw Error('No exact provenance mapping: '+p);
}
function walk(x,p=''){if(typeof x==='number'||typeof x==='string'&&/\d/.test(x)){claims[p]=sourceFor(p);methods[p]=claims[p].method;if(typeof x==='string')strings[p]=x;}else if(x&&typeof x==='object')for(const[k,vv]of Object.entries(x))walk(vv,p?p+'.'+k:k);}walk(a);
const analysisSha=sha(fs.readFileSync(path.join(root,revision+'/AAOI.json')));
const calc={kind:'deterministic_analysis_calculation_v1',ticker:'AAOI',reference_close:'2026-09-18',analysis_sha256:analysisSha,generator_path:'.agent/analyses-refresh-20260919/aaoi-revision/build-aaoi.cjs',generator_sha256:sha(fs.readFileSync(__filename)),inputs,score_components:judgments.score_components,valuation_scenario:{status:'non_applicable',reason_code:'NON_POSITIVE_EBITDA',reason:'EBITDA fournisseur négatif : aucun multiple, prix conditionnel, EV, equity value ou downside n’est calculé.',basis:{input_path:iff.path,input_sha256:iff.sha256,source_pointer:F+'/ebitda'}},valuation_status:'non_applicable — aucun scénario économique AAOI, EBITDA fournisseur négatif.',values:a,string_numeric_claims:strings,methods,claim_provenance:claims,limitations:['RankBeta HTTP 403 bloque la source obligatoire.','Calendrier CIEN UNAVAILABLE.','La révision reste NO TRADE et sans attestation AQ finale.','Aucun scénario de valorisation AAOI n’est produit.']};
write(revision+'/numeric-evidence.json',calc);const calcSha=sha(fs.readFileSync(path.join(root,revision+'/numeric-evidence.json')));
write(revision+'/evidence.json',{ticker:'AAOI',reference_close:'2026-09-18',analysis_path:revision+'/AAOI.json',analysis_sha256:analysisSha,claims:Object.keys(claims).map(p=>({path:p,value:get(a,p),as_of:'2026-09-18',source_artifact:revision+'/numeric-evidence.json',source_sha256:calcSha,source_pointer:typeof get(a,p)==='number'?'/values/'+p.split('.').map(esc).join('/'):'/string_numeric_claims/'+esc(p)}))});
const {render,validate,SCHEMA}=require(path.join(root,'tools/render-analysis.js'));const schemaErrors=validate(a,SCHEMA);if(schemaErrors.length)throw Error('Official renderer schema: '+schemaErrors.join('; '));fs.writeFileSync(path.join(root,revision,'index.html'),render(a));
console.log(`AAOI revision generated: ${comparisons.length} comparable symbols / ${comparisons[0].observations} common returns; ${Object.keys(claims).length} semantic mappings; NO TRADE.`);
