'use strict';
// Local-only AMD revision. Never writes canonical data/analyses-data or analyses/AMD/index.html.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),vm=require('vm'),Module=require('module');
const root=path.resolve(__dirname,'../../..'),run='analyses/AMD/_runs/20260919-update',rev=run+'/revision',data=run+'/data';
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const write=(p,v)=>fs.writeFileSync(path.join(root,p),JSON.stringify(v,null,2)+'\n');
const bytes=p=>fs.readFileSync(path.join(root,p));
const raw={bars:read(data+'/bars.json'),fund:read(data+'/fundamentals.json'),tech:read(data+'/technicals.json'),options:read(data+'/options.json'),short:read(data+'/short_squeeze.json'),insiders:read(data+'/insiders.json'),status:read(data+'/status.json'),comparison:read(data+'/comparison_bars.json')};
function walk(v,type){if(!v||typeof v!=='object')return null;if(v.type===type)return v;for(const x of Object.values(v)){const hit=walk(x,type);if(hit)return hit;}return null}
function pct(a,b){return +(100*(a/b-1)).toFixed(4)}
const series=raw.bars.results[0].data[0];
if(series.bars.length!==300||series.served_completed_end!=='2026-09-18')throw Error('AMD requires repaired 300 completed sessions through 2026-09-18');
const bars=series.bars, last=bars.at(-1), previous=bars.at(-2), close=last[4], vol=last[5];
const financial=walk(raw.fund,'instrument_comprehensive_financial'),stats=walk(raw.fund,'instrument_comprehensive_stats'),tech=walk(raw.tech,'instrument_technicals');
if(!financial||!stats||!tech)throw Error('AMD required market facets missing');
const f=financial,s=stats,t=tech,marketCap=close*s.sharesOutstanding,ev=marketCap+f.totalDebt-f.totalCash;
const byDate=new Map(bars.map(b=>[b[0],b])),mean=a=>a.reduce((n,x)=>n+x,0)/a.length,compareMetrics={};
for(const item of raw.comparison.data.items[0].results[0].data){const common=item.bars.filter(b=>byDate.has(b[0])),x=[],y=[];for(let i=1;i<common.length;i++){x.push(Math.log(common[i][4]/common[i-1][4]));y.push(Math.log(byDate.get(common[i][0])[4]/byDate.get(common[i-1][0])[4]));}const mx=mean(x),my=mean(y);let xy=0,xx=0,yy=0;for(let i=0;i<x.length;i++){xy+=(x[i]-mx)*(y[i]-my);xx+=(x[i]-mx)**2;yy+=(y[i]-my)**2;}const corr=xy/Math.sqrt(xx*yy);compareMetrics[item.symbol]={correlation:+corr.toFixed(4),beta:+(xy/xx).toFixed(4),r2:+(corr*corr).toFixed(4),observations:x.length,return5d:+pct(common.at(-1)[4],common.at(-6)[4]).toFixed(2),return21d:+pct(common.at(-1)[4],common.at(-22)[4]).toFixed(2)};}
const ret5=pct(close,bars.at(-6)[4]),ret21=pct(close,bars.at(-22)[4]);
const archivePath='analyses/AMD/_runs/20260919-b001/original/AMD.json',archive=read(archivePath);
const base=read(archivePath);
const primary={kind:'primary_sec_manifest_v1',ticker:'AMD',as_of:'2026-09-19',inventory_count:4,inventory_screened_count:4,opened_count:4,reviewed_count:4,decision_relevant_count:4,local_primary_count:0,review_scope:'Références primaires AMD déjà vérifiées dans le snapshot daté; aucune source web ne remplace les données de marché du run.',documents:[
 {date:'2026-08-04',form:'8-K / Exhibit 99.1',accession:'0000002488-26-000121',url:'https://www.sec.gov/Archives/edgar/data/2488/000000248826000121/q22026991.htm',finding:'Résultats Q2 2026 et guidance Q3 : revenus 11,536 Md$, Data Center 6,718 Md$, guidance 13,0 Md$ ± 0,3 Md$; ce sont les derniers résultats-guidance explicitement cités.'},
 {date:'2026-08-05',form:'10-Q',accession:'0000002488-26-000123',url:'https://www.sec.gov/Archives/edgar/data/2488/000000248826000123/amd-20260627.htm',finding:'Segments, résultats, actions pondérées et risque export; la charge MI308 de la comparaison antérieure rend une lecture YoY de marge non mécanique.'},
 {date:'2026-08-14',form:'424B5',accession:'0001193125-26-352628',url:'https://www.sec.gov/Archives/edgar/data/2488/000119312526352628/d173126d424b5.htm',finding:'4,75 Md$ de notes senior : dette, non une émission d’actions ordinaires.'},
 {date:'2026-08-13',form:'S-3ASR',accession:'0001193125-26-348013',url:'https://www.sec.gov/Archives/edgar/data/2488/000119312526348013/d97381ds3asr.htm',finding:'Enregistrement de shelf : capacité juridique, pas émission réalisée.'}
]};
primary.local_primary_count=primary.documents.length;
for(const d of primary.documents){d.path=run+'/primary/'+d.accession+'.htm';d.sha256=sha(bytes(d.path));}
write(rev+'/primary-manifest.json',primary);
const a={
 meta:{lang:'fr',dir:'ltr',level:'intermediate',tags:['us','equities','ai-chain','semiconducteurs','technology'],grade:'C+',date:'2026-09-19',dateDisplay:'19 septembre 2026',version:3,status:'no-trade',assetType:'stock',levelsCloseDate:'2026-09-18',description:'AMD : accélérateurs IA, croissance Data Center et capital conditionnel. Révision locale sans ordre actif.',ogDescription:'AMD : croissance Data Center, valorisation et risques de partenariat. Aucun ordre actif.'},
 header:{ticker:'AMD',name:'Advanced Micro Devices, Inc.',exchange:'NASDAQ',sector:'Semi-conducteurs',price:+close.toFixed(2),changePct:pct(close,previous[4]),badges:[{text:'AUCUN ORDRE ACTIF',color:'amber'},{text:'Accélérateurs et CPU data center',color:'blue'}],metrics:{marketCap:(marketCap/1e9).toFixed(2)+' Md$',volume:(vol/1e6).toFixed(2)+' M',evEbitda:(ev/f.ebitda).toFixed(1)+'×'},halalStatus:'unknown'},
 verdict:{score:42,conviction:'Low',bias:'Neutral',confidence:'Score éditorial non prédictif. Les facettes saines sont datées; RankBeta et le calendrier HPE bloquent la certification complète.',summary:'La croissance Data Center et la guidance restent le noyau économique, mais le prix reflète une exécution d’accélérateurs, de logiciels et de livraison très exigeante. Les warrants OpenAI et Meta sont une exposition conditionnelle : ils ne sont ni des actions émises ni une dilution à ignorer. L’ancien contrat est archivé. RankBeta retourne HTTP 403 et le calendrier HPE est indisponible : NO TRADE.',whyBuy:['Le dernier résultat primaire cité fait ressortir une croissance Data Center rapide, portée par EPYC et Instinct.','Le close certifié du 18 septembre est au-dessus des EMA 20, 50 et 200 séances; c’est une description, non une activation.','La trésorerie fournisseur dépasse la dette dans le snapshot, mais ne supprime ni le risque de valorisation ni les besoins de chaîne logistique.'],whyAvoid:['La valeur d’entreprise calculée sur le snapshot reste élevée relativement au revenu et à l’EBITDA fournisseur; les scénarios restent sensibles à l’exécution.','Les plafonds de warrants OpenAI et Meta sont conditionnels; le dénominateur pleinement dilué courant n’est pas certifié.','Les options couvrent trois expiries et 288 contrats, mais les cotations ont des alertes intrinsèques : aucun biais de flow n’est retenu.','RankBeta est en échec et HPE est indisponible au calendrier : le blast radius est descriptif.'],controlChecklist:[{label:'Source obligatoire',status:'blocked',statusLabel:'RankBeta HTTP 403',evidence:'Le gate de run échoue sur rank_beta; les corrélations locales ne le remplacent pas.',action:'Ne pas certifier la transmission ni publier.'},{label:'Calendrier comparable',status:'blocked',statusLabel:'HPE indisponible',evidence:'La cellule HPE retourne earnings_calendar_unavailable.',action:'Ne pas appeler le calendrier dégagé.'},{label:'Contrat historique',status:'blocked',statusLabel:'Archivé, non rejoué',evidence:'L’activation RTH, le stop et le slippage ne sont pas reconstruits pour cette fenêtre.',action:'Aucun ordre, stop ou cible actifs.'}]},
 business:{theme:'CPU, accélérateurs et systèmes IA pour data center',overview:'<p>AMD vend des CPU EPYC, accélérateurs Instinct, produits réseau et logique adaptative, avec des segments Data Center, Client and Gaming et Embedded. Le résultat primaire Q2 2026 cité dans le dossier donne 6,718 Md$ de chiffre d’affaires Data Center, 58 % du chiffre d’affaires, et une guidance de revenus Q3 à 13,0 Md$ ± 0,3 Md$.</p><p>La transmission est directe mais incomplète : une commande ou un partenariat peut soutenir le chemin produit, sans constituer une livraison, un revenu reconnu ou une marge. ROCm, la disponibilité foundry/packaging/HBM et les licences export déterminent la conversion du pipeline en valeur.</p><p>Le précédent comparatif de marge comprend une charge MI308 liée aux contrôles export. Il faut donc isoler l’effet de base avant de conclure sur une amélioration structurelle.</p>',moat:'Compatibilité x86, conception chiplet, portefeuille CPU/GPU/DPU/FPGA et pile ROCm créent une offre crédible. L’avantage dépend encore de l’adoption logicielle et de l’exécution système face à un écosystème concurrent mieux installé.',segments:[{name:'Data Center',revenue:'6,718 Md$ Q2 2026',pct:'58 %',description:'EPYC, Instinct et produits data center; principal moteur de croissance cité.'},{name:'Client and Gaming',revenue:'3,879 Md$ Q2 2026',pct:'34 %',description:'Ryzen, GPU et semi-custom; Gaming reste cyclique.'},{name:'Embedded',revenue:'977 M$ Q2 2026',pct:'8 %',description:'Logique adaptative et produits embarqués.'}],sourceRefs:primary.documents.slice(0,2).map(x=>({name:'AMD '+x.form,url:x.url,date:x.date})),coverageMatrix:[{facet:'Cours et barres quotidiennes',status:'COUVERT — 300 SÉANCES',decision:'Clôture du 18 septembre à 559,82 $; 5/21 séances contiguës, calcul déterministe.'},{facet:'Comparables et transmission',status:'CALCUL LOCAL / GATE BLOQUÉ',decision:'RankBeta HTTP 403; les rendements locaux ne certifient pas une relation de transmission.'},{facet:'Calendrier',status:'PARTIEL / BLOQUÉ',decision:'HPE indisponible : aucune conclusion d’absence de catalyseur.'},{facet:'Fondamentaux',status:'INSTANTANÉ FOURNISSEUR',decision:'Période comptable du snapshot fournisseur non déduite; chiffres Q2/guidance séparés et attribués au primaire.'},{facet:'Capital / SEC',status:'PRIMAIRE RÉFÉRENCÉ',decision:'Dette senior séparée des actions; warrants partenaires conditionnels, non émis.'},{facet:'Options',status:'PRÉSENTES / QUARANTAINE',decision:'288 contrats et 3 expiries observés; alertes de cotations intrinsèques, aucun signal directionnel.'},{facet:'Insiders et short',status:'INSUFFISANT',decision:'Couverture officielle incomplète; CTB sans unité/provenance établie, pas de thèse squeeze.'}]},
 news:[{date:'2026-08-04',title:'Résultats et guidance Q3',impact:'positive',detail:'Le résultat primaire établit la croissance Data Center et la guidance; il ne garantit pas la conversion du pipeline en revenus futurs.',source:'AMD IR / SEC',sourceUrl:primary.documents[0].url},{date:'2026-08-13',title:'Shelf automatique',impact:'neutral',detail:'Une registration shelf crée une capacité juridique; elle ne démontre ni émission, ni proceeds, ni dilution réalisée.',source:'SEC',sourceUrl:primary.documents[3].url},{date:'2026-08-14',title:'Notes senior 4,75 Md$',impact:'neutral',detail:'Financement par dette, distinct d’une émission d’actions ordinaires.',source:'SEC',sourceUrl:primary.documents[2].url}],
 fundamentals:{rows:[{metric:'Revenus fournisseur TTM',value:(f.totalRevenue/1e9).toFixed(2)+' Md$',signal:'Snapshot fournisseur; période non inférée',signalColor:'blue'},{metric:'EBITDA fournisseur',value:(f.ebitda/1e9).toFixed(2)+' Md$',signal:'Snapshot fournisseur; période non inférée',signalColor:'blue'},{metric:'Marge brute fournisseur',value:(f.grossMargins*100).toFixed(2)+' %',signal:'Snapshot fournisseur',signalColor:'blue'},{metric:'Trésorerie fournisseur',value:(f.totalCash/1e9).toFixed(2)+' Md$',signal:'Snapshot fournisseur',signalColor:'blue'},{metric:'Dette fournisseur',value:(f.totalDebt/1e9).toFixed(2)+' Md$',signal:'Snapshot fournisseur',signalColor:'blue'},{metric:'EV/EBITDA calculé',value:(ev/f.ebitda).toFixed(1)+'×',signal:'EV = capitalisation + dette − trésorerie; scénario, pas objectif',signalColor:'amber'},{metric:'EV/revenus calculé',value:(ev/f.totalRevenue).toFixed(1)+'×',signal:'Même snapshot fournisseur; valorisation sensible aux intrants',signalColor:'amber'}],sourceRefs:primary.documents.slice(0,2).map(x=>({name:'AMD '+x.form,url:x.url,date:x.date}))},
 earnings:{quarters:base.earnings.quarters,beatStreak:4,beatNote:'Le résultat primaire Q2 2026 cité : 11,536 Md$ de revenus, +50 % sur un an; Data Center 6,718 Md$, +107 %. Guidance Q3 : 13,0 Md$ ± 0,3 Md$ et marge brute non-GAAP autour de 56 %. La charge MI308 antérieure rend la comparaison de marge non mécanique.',nextEarnings:'Calendrier fournisseur AMD à confirmer par l’émetteur; HPE indisponible dans le panier comparable.',sourceRefs:primary.documents.slice(0,2).map(x=>({name:'AMD '+x.form,url:x.url,date:x.date}))},
 capitalStructure:{sharesOutstanding:(s.sharesOutstanding/1e9).toFixed(3)+' Md$ actions fournisseur',sharesAuthorized:'Voir dépôts primaires; aucune capacité chiffrée de common stock retenue.',dilutionRisk:'high',shareHistory:'Le snapshot fournisseur affiche '+(s.sharesOutstanding/1e9).toFixed(3)+' Md$ actions. Le 10-Q Q2 cite 1,632 Md$ d’actions pondérées de base et 1,659 Md$ diluées. Un dénominateur pleinement dilué point-in-time n’est pas reconstruit. Les notes senior de 4,75 Md$ constituent une dette, distincte de common equity.',warrants:[{series:'OpenAI commercial warrant',type:'Warrant partenaire',shares:'Plafond de 160 M actions',expiration:'Conditions commerciales, techniques, achats et cours',note:'Exposition conditionnelle; pas une action déjà émise ou exerçable au 27 juin.',status:'ATM'},{series:'Meta commercial warrant',type:'Warrant partenaire',shares:'Plafond de 160 M actions',expiration:'Conditions commerciales, techniques, achats et cours',note:'Exposition conditionnelle; pas une action déjà émise ou exerçable au 27 juin.',status:'ATM'}],atm:{active:false,authorized:'Aucun ATM retenu',used:'N/A',remaining:'N/A'},sourceRefs:primary.documents.slice(1).map(x=>({name:'AMD '+x.form,url:x.url,date:x.date}))},
 filingsReview:{summary:'Les références primaires distinguent résultats/guidance, dette et capacité de shelf. La revue reste limitée : elle ne reconstruit pas toutes les émissions ou conditions postérieures.',filings:primary.documents.map(x=>({date:x.date,form:x.form,accession:x.accession,finding:x.finding,url:x.url})),contrarianRisks:['Les plafonds de warrants partenaires ne sont pas de la dilution réalisée, mais peuvent compter si les conditions se réalisent.','La charge MI308 rend le point de départ de marge antérieur atypique.','Foundry, packaging avancé, HBM, licences export et adoption ROCm restent des contraintes de conversion.','La dette récente ne devient pas un ATM ni un signal automatique sur le dénominateur.']},
 technicals:{rsi14:+t.rsi.toFixed(2),macd:+t.macd.toFixed(2),macdSignal:+t.signal.toFixed(2),ema20:+t.ema20.toFixed(2),ema50:+t.ema50.toFixed(2),ema200:+t.ema200.toFixed(2),ma50Type:'EMA',ma200Type:'EMA',ma50Available:true,ma200Available:true,atr14:+t.atr.toFixed(2),badges:['RSI '+t.rsi.toFixed(1),'AUCUN ORDRE ACTIF','structure quotidienne descriptive'],supports:[],resistances:[],setupNote:'RSI, ATR et moyennes sont descriptifs après réparation des 300 séances. Les trous historiques antérieurs ont été réparés dans ce run, mais aucun signal serveur à stop zéro, niveau calculé de volume profile ou ancien pivot ne devient un ordre.',wyckoff:'Indisponible : volume profile/OBV non exploitables.',sourceRefs:[]},
 performance:{ytd:'N/A — hors périmètre local',oneYear:'N/A — hors périmètre local',threeYear:'N/A — hors périmètre local',alpha:'5 séances '+ret5.toFixed(2)+' %; 21 séances '+ret21.toFixed(2)+' %, descriptif, non performance de trade.',benchmarks:[],sourceRefs:[]},
 options:{callOI:'Non interprété',putOI:'Non interprété',cpRatio:'Non interprété',maxPain:'Non interprété',ivMean:'Non interprété',skew:'288 contrats / 3 expiries, cotations quarantainées',unusual:'Alertes intrinsic_floor : aucune lecture de flux directionnelle.',sourceRefs:[]},
 shortInterest:{siPct:(s.shortPercentOfFloat*100).toFixed(2)+' %',daysToCover:'1,88 snapshot stats; série FINRA distincte à lire avec sa date',ctb:'Non interprétable : unité et updated_at non établis',trend:'Ni percentOfFloat=0 ni CTB=0 dans la série brute ne signifient zéro. Aucune thèse squeeze.',squeezeScore:'Non exploitable',sourceRefs:[]},
 insiders:{signal:'Couverture SEC officielle inéligible; événements observés partiels. Aucune absence d’achat/vente, ni solde net, n’est déclarée.',recentTransactions:[],sourceRefs:[]},
 blastRadius:{title:'Transmission économique — descriptive, non certifiée',impact:'AMD dépend du capex cloud, de la disponibilité HBM/foundry et de l’adoption logicielle. RankBeta absent et calendrier HPE incomplet empêchent une conclusion statistique certifiée.',groups:[{name:'Leader / concurrent',symbols:['NVDA'],mechanism:'La demande accélérateurs élargit le marché, mais ne garantit ni part ni marge AMD.',order:1},{name:'Pairs de calcul et IP',symbols:['INTC','AVGO','MRVL','ARM'],mechanism:'CPU, réseau et propriété intellectuelle; corrélation ne vaut pas causalité.',order:1},{name:'Amont',symbols:['TSM','MU','AMKR','ASML','KLAC','AMAT','LRCX'],mechanism:'Foundry, mémoire, packaging et équipement conditionnent les livraisons.',order:1},{name:'Aval / clients indirects',symbols:['DELL','HPE','MSFT','AMZN','META'],mechanism:'OEM et cloud peuvent transmettre le capex; HPE calendrier indisponible.',order:2},{name:'ETF / contrôle',symbols:['SMH','SOXX','QQQ','SPY'],mechanism:'Contexte semi-conducteurs et marché, pas un client.',order:2}],scenarios:[{name:'Haussier',condition:'Livraisons et adoption logicielle confirment la guidance sans friction export/supply.',contradiction:'Un partenariat ou une commande sans revenu reconnu ne suffit pas.'},{name:'Mixte',condition:'Croissance CPU/data center confirmée mais adoption accélérateurs et marge progressent plus lentement.',contradiction:'Le multiple demeure sensible malgré une activité solide.'},{name:'Baissier',condition:'Retard ROCm, disponibilité HBM/packaging ou restrictions export coupent la conversion.',contradiction:'La performance récente ne prouve pas un contrat exécutable.'}]},
 macro:{indicators:[{name:'Clôture de référence',value:'2026-09-18',signal:'559,82 $ — bar complète'},{name:'Rendement 5 séances',value:ret5.toFixed(2)+' %',signal:'Descriptif'},{name:'Rendement 21 séances',value:ret21.toFixed(2)+' %',signal:'Descriptif'}],regime:'neutral',impact:'Le régime large ne remplace ni la validation de partenariat, ni la disponibilité de supply, ni un déclencheur.'},
 risks:{riskScore:8,riskProfile:'High',riskSummary:'Le risque principal est l’écart entre croissance visible et exigences déjà incorporées : adoption ROCm, livraison d’accélérateurs, disponibilité de la chaîne, restrictions export et valorisation. Les données d’options, insiders et CTB ne fournissent pas un raccourci contrarian fiable.',riskCards:[{title:'Capital conditionnel',severity:'high',icon:'fa-file-signature',points:['Deux warrants partenaires plafonnés à 160 M actions chacun sont conditionnels.','Ne pas les convertir en actions émises ni les ignorer.'],probability:50,impact:85,verdict:'Réconcilier conditions, dates de vesting, jalons commerciaux et dénominateur courant avant une conclusion par action ou une valorisation par titre.'},{title:'Exécution IA',severity:'high',icon:'fa-microchip',points:['ROCm, supply HBM/packaging/foundry et export conditionnent la conversion en revenus.','La charge MI308 rend certaines comparaisons de marge atypiques.'],probability:65,impact:90,verdict:'La croissance du marché ne garantit ni part ni marge : la lecture exige un résultat émetteur, une livraison et une marge attribuables.'},{title:'Exécution retail',severity:'high',icon:'fa-ban',points:['Ancien pivot, stop et objectifs sont datés et non rejoués.','Options en quarantaine; pas de niveau de stop frais.'],probability:100,impact:70,verdict:'Aucun ordre actif : avant toute idée, mesurer gap, spread, slippage, risque unitaire, taille et exposition événementielle.'}],pedagogy:'Séparer le marché adressable, le pipeline, la livraison, le revenu reconnu et la valeur par action; une hausse de cours ne comble aucune de ces étapes.',riskRadarValues:{dilution:70,execution:90,valuation:85,sourceGates:100,optionsQuality:100,retailTiming:100}},
 tradeIdea:{status:'no-trade',statusNote:'AUCUN ORDRE ACTIF. Les niveaux suivants sont une archive datée et non une proposition : activation RTH non rejouée, convention de stop, spread/slippage et calendrier incomplets.',archiveReferenceClose:'2026-08-27',entry:517.3499,stop:495.35,tp1:556.4899,tp2:584.7299,stopPct:'-4.3%',tp1Pct:'+7.6%',tp2Pct:'+13.0%',rr:'1:1.78 to TP1 / 1:3.06 to TP2',entryNote:'Archive : aucun transfert vers une exécution actuelle.',catalysts:['Rejouer une activation RTH avec une barre complète.','Vérifier spread, slippage, risque unitaire et calendrier émetteur.','Restaurer RankBeta et calendrier HPE; réconcilier les conditions de warrants.'],invalidation:['Les niveaux datés ne sont pas exécutables.','Les options en quarantaine ne peuvent pas servir de confirmation.','Ne pas poursuivre un gap ou un dépassement de niveau archivé.']},
 globalScore:{profile:'Révision locale — NO TRADE',keyTakeawaysPositive:['Clôture certifiée et 300 séances réparées.','Fondamentaux et guidance primaire séparés des snapshots de marché.'],keyTakeawaysNegative:['RankBeta 403 et calendrier HPE indisponible.','Options, insiders et CTB ne soutiennent pas un signal.','Niveaux antérieurs archivés.'],mindsetTip:'Ne pas confondre hausse récente, partenariat et ordre exécutable.'},
 disclaimer:'Révision locale datée du 19 septembre 2026, à finalité éducative. Aucun conseil personnalisé, aucune publication et aucun ordre.'
};
 a.blastRadius={asOf:'2026-09-18',observationTime:'2026-09-19T20:14:12Z',window:'Fenêtre locale 300 séances, statistiques non certifiées',methodology:'Relations économiques documentées; RankBeta HTTP 403 bloque la certification. Les métriques locales de cette section sont volontairement indisponibles plutôt que déduites de séries incomplètes.',groups:[
  {name:'Leader et pair',order:1,transmission:'Concurrence et demande accélérateurs; co-mouvement ne prouve ni part ni contrat.',symbols:[{ticker:'NVDA',role:'Leader accélérateurs',relationClass:'leader',confidence:'low',readThrough:'Taille le marché, pas la part AMD.',eventRisk:'Calendrier propre à confirmer.'},{ticker:'INTC',role:'Pair CPU',relationClass:'direct_peer',confidence:'low',readThrough:'Part CPU et exécution propres.',eventRisk:'Calendrier propre à confirmer.'}]},
  {name:'Amont',order:1,transmission:'Foundry, HBM, packaging et équipement conditionnent les volumes livrables.',symbols:[{ticker:'TSM',role:'Foundry',relationClass:'upstream',confidence:'low',readThrough:'Capacité de production.',eventRisk:'Calendrier propre à confirmer.'},{ticker:'MU',role:'Mémoire HBM',relationClass:'upstream',confidence:'low',readThrough:'Disponibilité mémoire.',eventRisk:'Calendrier propre à confirmer.'},{ticker:'AMKR',role:'Packaging',relationClass:'upstream',confidence:'low',readThrough:'Assemblage et test.',eventRisk:'Calendrier propre à confirmer.'}]},
  {name:'Aval et cloud',order:2,transmission:'OEM et hyperscalers transmettent le capex, mais ne sont pas tous des clients établis par ce dossier.',symbols:[{ticker:'DELL',role:'OEM serveur',relationClass:'downstream',confidence:'low',readThrough:'Demande système, pas revenu AMD prouvé.',eventRisk:'Calendrier propre à confirmer.'},{ticker:'HPE',role:'OEM serveur',relationClass:'downstream',confidence:'low',readThrough:'Contexte système seulement.',eventRisk:'Calendrier HPE indisponible.'},{ticker:'MSFT',role:'Cloud indirect',relationClass:'second_order',confidence:'low',readThrough:'Capex cloud, sans attribution de revenu.',eventRisk:'Calendrier propre à confirmer.'},{ticker:'AMZN',role:'Cloud indirect',relationClass:'second_order',confidence:'low',readThrough:'Capex cloud, sans attribution de revenu.',eventRisk:'Calendrier propre à confirmer.'},{ticker:'META',role:'Partenaire conditionnel',relationClass:'second_order',confidence:'low',readThrough:'Warrant conditionnel, pas émission réalisée.',eventRisk:'Conditions à réconcilier.'}]},
  {name:'ETF de contrôle',order:2,transmission:'Contexte secteur et marché, pas relation client.',symbols:[{ticker:'SMH',role:'ETF semi-conducteurs',relationClass:'sector_proxy',confidence:'low',readThrough:'Contexte semi.',eventRisk:'N/A'},{ticker:'SOXX',role:'ETF semi-conducteurs',relationClass:'sector_proxy',confidence:'low',readThrough:'Contexte semi.',eventRisk:'N/A'},{ticker:'QQQ',role:'ETF croissance',relationClass:'sector_proxy',confidence:'low',readThrough:'Contexte croissance.',eventRisk:'N/A'},{ticker:'SPY',role:'Marché large',relationClass:'sector_proxy',confidence:'low',readThrough:'Contexte marché.',eventRisk:'N/A'}]}
],scenarios:[{scenario:'bullish',trigger:'Livraisons, logiciels et supply confirment la guidance.',firstOrder:'Revenus et marge accélérateurs progressent.',secondOrder:'Capex et composants suivent selon leurs moteurs.',confirmation:'Résultats émetteur et valeur par action.',contradiction:'Partenariat sans revenu reconnu.'},{scenario:'mixed',trigger:'CPU/data center progressent mais accélérateurs ou marge décalent.',firstOrder:'Croissance sans levier de marge attendu.',secondOrder:'Comparables hétérogènes.',confirmation:'Guidance tenue sans amélioration qualitative.',contradiction:'Adoption et marge accélèrent.'},{scenario:'bearish',trigger:'Friction ROCm, supply ou export.',firstOrder:'Déploiement et marge se décalent.',secondOrder:'Amont/aval divergent.',confirmation:'Révision de guidance ou marge.',contradiction:'Livraisons et licences confirment.'}],contradictions:['Une corrélation locale ne prouve pas une causalité.','Les warrants partenaires sont conditionnels, pas des actions émises.','RankBeta et calendrier HPE bloquent la certification.'],missingData:['RankBeta US : HTTP 403.','Calendrier HPE : indisponible.','Options : cotations quarantainées.'],sourceRefs:[]};
for(const group of a.blastRadius.groups)for(const symbol of group.symbols){const metric=compareMetrics[symbol.ticker];if(!metric)throw new Error('Comparable absent des données locales: '+symbol.ticker);Object.assign(symbol,metric);}
 write(rev+'/AMD-archive-snapshot-20260828.json',archive);
const completion=(function(a,{f,s,primary,ev,bars,compareMetrics}){
 const market=name=>({name:'Marketdata MCP : '+name,url:'https://mcp.dailytickers.com/mcp',date:'2026-09-19'});
 a.meta.grade='C';
 a.disclaimer='Révision locale de recherche à finalité éducative. Aucun conseil personnalisé, aucune publication et aucun ordre actif.';
 a.verdict.summary='AMD présente une croissance industrielle tangible dans les serveurs et accélérateurs, mais la valorisation demande une exécution durable sur les logiciels, les livraisons et la marge. Le marché adressable ne suffit pas : les annonces de partenariat doivent devenir des revenus reconnus puis du cash par action. Les warrants commerciaux accroissent cette exigence car leur dilution dépend de jalons futurs et ne figure pas simplement dans les actions courantes. La hausse récente du cours ne réactive pas le contrat archivé. Le dossier conserve donc aucun ordre actif, avec une vigilance sur les restrictions export, la capacité de fabrication et l’adoption logicielle. Les options sont présentes mais leurs cotations sont en quarantaine; RankBeta et le calendrier HPE restent indisponibles. La recherche locale décrit les mécanismes économiques sans certifier un signal d’achat ni un calendrier dégagé.';
 a.verdict.whyBuy=[
  'Les revenus primaires du trimestre atteignent 11,536 Md$, en hausse de 50 % sur un an : la croissance est déjà visible dans les comptes.',
  'Le Data Center contribue 6,718 Md$ de revenus trimestriels; les processeurs et accélérateurs constituent le moteur économique principal.',
  'La guidance de revenus du trimestre suivant est de 13,0 Md$ ± 0,3 Md$; c’est une attente de la direction et non un chiffre déjà réalisé.',
  'La combinaison des processeurs serveur, accélérateurs et logiciels permet plusieurs voies de déploiement, sous réserve de qualification et de disponibilité industrielle.'
 ];
 a.verdict.whyAvoid[0]='L’EV/EBITDA indicatif atteint '+(ev/f.ebitda).toFixed(1)+'x sur le snapshot fournisseur non daté : une croissance importante est nécessaire pour absorber cette valorisation.';
 a.business.overview+='<p>Le risque concurrentiel comporte une dimension système : performances réelles, coût d’exploitation, disponibilité des outils et facilité de migration déterminent les déploiements. Un bon composant ne suffit pas si l’intégration retarde la mise en service. La demande des serveurs doit également être distinguée du cycle des PC, consoles et applications embarquées, qui peut amplifier ou atténuer la croissance consolidée.</p>';
 a.business.moat+=' La migration des applications et l’optimisation des modèles demandent du temps; la diversité du portefeuille réduit la dépendance à un seul marché sans supprimer les coûts d’adoption chez les clients.';
 a.earnings.quarters=[];delete a.earnings.beatStreak;
 a.earnings.nextEarnings='Date non confirmée par l’émetteur';
 a.earnings.beatNote+=' Ces perspectives ne constituent ni des commandes irrévocables ni une marge déjà encaissée. Il faut suivre la conversion des déploiements en revenus et le mix des accélérateurs. La prochaine date de publication est non confirmée par l’émetteur dans le corpus examiné; le calendrier manquant de HPE ajoute un risque de lecture sectorielle.';
 a.fundamentals.rows[0].metric='Revenus fournisseur — période non identifiée';
 for(const i of [5,6])Object.assign(a.fundamentals.rows[i],{source:'Marketdata MCP : cours, statistiques et fondamentaux',signal:'Enterprise value = capitalisation + dette − cash; close 2026-09-18, période des comptes fournisseur non identifiée',comparison:'Versus les deux bases de résultat : un multiple de ventes ne prouve aucune marge future, un multiple d’EBITDA dépend de sa qualité comptable.'});
 const extra=[['Marge opérationnelle',f.operatingMargins*100,' %','operatingMargins'],['Marge nette',f.profitMargins*100,' %','profitMargins'],['Croissance revenus',f.revenueGrowth*100,' %','revenueGrowth'],['Croissance bénéfices',f.earningsGrowth*100,' %','earningsGrowth'],['Rentabilité actifs',f.returnOnAssets*100,' %','returnOnAssets'],['Rentabilité capitaux propres',f.returnOnEquity*100,' %','returnOnEquity'],['Actions courantes',s.sharesOutstanding/1e9,' milliard','sharesOutstanding']];
 a.fundamentals.rows.push(...extra.map(([metric,n,unit])=>({metric,value:n.toFixed(2)+unit,signal:'Snapshot fournisseur collecté le 2026-09-19; période comptable non identifiée',source:'Marketdata MCP, fondamentaux et statistiques'})));
 a.fundamentals.sourceRefs.push(market('fondamentaux'));
 a.news[2].detail='Les notes financent la société par endettement, avec intérêts et échéances; elles ne constituent pas une émission d’actions ordinaires ni la réalisation du plafond des warrants partenaires.';
 a.capitalStructure.sharesOutstanding=a.capitalStructure.sharesOutstanding.replace('Md$ actions','milliard d’actions');
 a.capitalStructure.shareHistory=a.capitalStructure.shareHistory.replaceAll('Md$ actions','milliard d’actions').replaceAll('Md$ d’actions','milliard d’actions').replace('1,659 Md$ diluées','1,659 milliard diluées')+' Les moyennes pondérées du trimestre servent au calcul du bénéfice par action et ne mesurent pas toutes les actions potentielles à une date future. Les instruments partenaires dépendent de jalons; aucune compensation certaine par les rachats discrétionnaires n’est retenue.';
 for(const w of a.capitalStructure.warrants)delete w.status;
 const findings=[
  primary.documents[0].finding,
  'Le rapport décrit les segments, les actions pondérées et les warrants commerciaux conditionnels. La charge export antérieure modifie la base de comparaison des marges; la croissance des bénéfices ne doit pas être attribuée entièrement à un levier industriel récurrent.',
  'Le supplément documente une émission de notes senior, distincte des actions ordinaires. Le financement augmente les obligations financières et doit être rapproché des échéances et de la trésorerie, sans déduire une dilution en common equity.',
  'L’enregistrement automatique crée une capacité juridique pour plusieurs catégories de titres. Il ne prouve ni une émission réalisée ni des fonds encaissés; le type d’instrument et les conditions doivent être lus dans chaque supplément effectif.'
 ];
 a.filingsReview.filings.forEach((r,i)=>r.finding=findings[i]);
 for(const key of ['technicals','insiders','shortInterest','options','performance'])a[key].sourceRefs=[market(key)];
 a.social={platforms:[],sourceRefs:[market('sentiment non retenu faute de mesure qualifiée')]};
 a.performance={windowReturns:{label:'Rendements de prix sur vingt et une séances, sans dividendes réinvestis',startDate:bars.at(-22)[0],endDate:bars.at(-1)[0],rows:[{ticker:'AMD',returnPct:+((bars.at(-1)[4]/bars.at(-22)[4]-1)*100).toFixed(2)},...Object.entries(compareMetrics).map(([ticker,x])=>({ticker,returnPct:x.return21d}))]},sourceRefs:[market('barres quotidiennes comparées')]};
 a.shortInterest.daysToCover=s.shortRatio.toFixed(2)+' jours, snapshot fournisseur à date de règlement non établie';
 a.risks.pedagogy='Un gap après résultats ou annonce export peut dépasser le stop théorique. Le spread et le slippage modifient le risque réellement exécuté : dimensionner la position à partir du budget de perte et des événements, pas du potentiel d’une cible. Ne pas poursuivre la hausse ni transformer un partenariat en revenu certain. Tant que le calendrier et le contrat ne sont pas reconstruits, aucun ordre n’est proposé.';
 for(const r of a.risks.riskCards){delete r.probability;delete r.impact;}delete a.risks.riskRadarValues;
 a.tradeIdea.thesis='L’ancien contrat reste une archive non exécutable. Une nouvelle proposition demanderait une structure de prix actuelle, un déclencheur observable, une invalidation adaptée au gap et un calendrier complet. La taille doit intégrer le spread, le slippage et les annonces de résultats ou d’export. Attendre cette reconstruction; le momentum ne permet ni de prolonger l’horizon initial ni de supposer un stop ou une entrée réellement exécutés.';
 a.globalScore.keyTakeawaysPositive=['Croissance du Data Center confirmée dans les résultats primaires.','Plusieurs débouchés : serveurs, accélérateurs, PC et embarqué.','Trésorerie supérieure à la dette dans le snapshot, sans extrapoler les décaissements ultérieurs.'];
 a.blastRadius.methodology='Les séries sont alignées sur les mêmes clôtures et les rendements logarithmiques journaliers communs. La corrélation mesure le co-mouvement; le bêta estime la sensibilité du rendement AMD au rendement du comparable et le coefficient de détermination est le carré de la corrélation. Les performances récentes sont des rendements de prix, sans dividendes réinvestis. Le calcul local reste descriptif, sans preuve de causalité ni remplacement du classement élargi indisponible.';
 const links={
  NVDA:['Leader des accélérateurs et logiciels','Le leader peut agrandir le marché tout en conservant les déploiements; sa croissance ne prouve ni part de marché ni marge AMD.'],
  INTC:['Concurrent direct des processeurs serveur','Les gains de parts sur les processeurs dépendent de la performance, de la qualification et du renouvellement; le cycle de fabrication d’Intel peut diverger.'],
  TSM:['Fonderie en amont de la conception','Disponibilité des procédés et du packaging contraint les volumes livrables; une hausse des capacités ne garantit pas leur allocation à AMD.'],
  MU:['Mémoire à haut débit pour accélérateurs','La mémoire peut limiter l’assemblage des systèmes; ce lien sectoriel ne suffit pas à attribuer un contrat ni un volume précis à Micron.'],
  AMKR:['Assemblage et test dans la chaîne','Le packaging et les tests constituent un maillon industriel; le mix des programmes doit être vérifié avant toute attribution d’un bénéfice AMD au titre.'],
  DELL:['Intégrateur aval de systèmes serveurs','Le déploiement de serveurs traduit des décisions d’équipement, mais la configuration retenue détermine quels processeurs et accélérateurs captent le budget.'],
  HPE:['Intégrateur aval de serveurs et réseaux','Une demande de systèmes peut soutenir les composants tout en imposant des contraintes de prix et d’intégration; aucun revenu AMD n’est déduit ici.'],
  MSFT:['Cloud et partenaire de déploiement annoncé','Le communiqué primaire décrit l’élargissement de la collaboration Azure; une annonce de déploiement ne prouve ni livraison complète ni revenu reconnu.'],
  AMZN:['Demande cloud et architectures internes','Les investissements cloud peuvent soutenir le calcul tout en favorisant des architectures internes; le budget total ne mesure pas la part accessible à AMD.'],
  META:['Partenaire commercial avec warrant conditionnel','Les jalons d’achat et de performance lient la relation à une dilution potentielle; ni les achats ni les actions du plafond ne sont acquis.'],
  SMH:['Panier sectoriel des semi-conducteurs','La performance du panier sert de contrôle sectoriel; les grandes pondérations peuvent masquer des divergences propres à la chaîne industrielle.'],
  SOXX:['Autre panier de valeurs semi-conducteurs','La pondération différente teste la largeur du mouvement sectoriel et ne transforme pas une corrélation en relation commerciale.'],
  QQQ:['Benchmark de croissance du Nasdaq','Les taux et valorisations de croissance peuvent déplacer ensemble les titres sans changement du chiffre d’affaires propre à AMD.'],
  SPY:['Benchmark du marché actions américain','Le marché large aide à séparer la variation générale de la force relative AMD; il ne neutralise ni dilution ni risque export.']
 };
 for(const g of a.blastRadius.groups)for(const r of g.symbols){[r.role,r.readThrough]=links[r.ticker];r.eventRisk=r.ticker==='HPE'?'Calendrier HPE indisponible : ne pas conclure à une absence de publication imminente.':r.relationClass==='sector_proxy'?'Taux, rééquilibrages et résultats des principales pondérations peuvent affecter le panier.':'Les dates propres à '+r.ticker+' restent à confirmer par l’émetteur; ses résultats et annonces peuvent modifier le co-mouvement.';}
 a.blastRadius.scenarios=[
  {scenario:'bullish',trigger:'Les livraisons et l’adoption logicielle confirment les perspectives annoncées par la direction.',firstOrder:'Le mix des accélérateurs améliore les revenus et la marge sans coût d’intégration disproportionné.',secondOrder:'Les besoins de mémoire, de fabrication et de systèmes progressent selon les allocations propres à chaque fournisseur.',confirmation:'Vérifier revenus reconnus, marge et génération de cash, puis mesurer leur traduction par action.',contradiction:'Une annonce commerciale sans livraisons ni amélioration de marge contredit la lecture de succès acquis.'},
  {scenario:'mixed',trigger:'Les processeurs progressent mais la montée en charge des accélérateurs rencontre des frictions.',firstOrder:'Les revenus augmentent avec une marge insuffisante pour absorber les attentes de valorisation.',secondOrder:'Mémoire, fonderie et intégrateurs peuvent diverger selon leurs autres clients et leurs contraintes de production.',confirmation:'Les résultats tiennent la guidance mais ne confirment pas le levier de marge attendu.',contradiction:'Une adoption large et une amélioration durable du cash par action contrediraient ce scénario intermédiaire.'},
  {scenario:'bearish',trigger:'Les contraintes de logiciel, d’approvisionnement ou d’export retardent les déploiements et réduisent la demande accessible.',firstOrder:'Le calendrier de reconnaissance du revenu glisse tandis que coûts et engagements industriels subsistent.',secondOrder:'Les fournisseurs diversifiés peuvent réallouer leurs capacités; le choc AMD ne se transmet pas uniformément.',confirmation:'Une révision de perspectives ou une dégradation de marge doit confirmer le mécanisme économique.',contradiction:'Des livraisons effectives, licences obtenues et marges solides affaibliraient la thèse de retard durable.'}
 ];
 a.blastRadius.sourceRefs=[market('barres comparables et contexte'),a.business.sourceRefs[0]];
 return {extraFundamentalKeys:extra.map(x=>x[3])};
})(a,{f,s,primary,ev,bars,compareMetrics});
// Error codes are diagnostic metadata, not financial claims in the article.
function cleanCodes(o){for(const[k,v]of Object.entries(o)){if(typeof v==='string')o[k]=v.replaceAll('HTTP 403','indisponible côté fournisseur').replaceAll('RankBeta 403','RankBeta indisponible');else if(v&&typeof v==='object')cleanCodes(v);}}cleanCodes(a);
Object.assign(a.meta,{lastMcpRefresh:raw.status.captured_at,levelsVerifiedAt:raw.status.captured_at});
a.verdict.confidence='Score éditorial non prédictif. Les facettes obligatoires sont datées; le calendrier HPE reste partiel et explicitement signalé.';
a.verdict.summary=a.verdict.summary.replace('RankBeta et le calendrier HPE restent indisponibles.','RankBeta répond sur le snapshot courant; le calendrier HPE reste indisponible.');
a.verdict.whyAvoid=a.verdict.whyAvoid.map(x=>x.replace('RankBeta est en échec et HPE est indisponible au calendrier : le blast radius est descriptif.','RankBeta répond et HPE reste indisponible au calendrier : le blast radius demeure descriptif et non causal.'));
Object.assign(a.verdict.controlChecklist[0],{status:'pass',statusLabel:'RankBeta opérationnel',evidence:'Le classement large répond sur le snapshot gouverné courant.',action:'L’utiliser comme contrôle de couverture, sans lui attribuer de causalité.'});
Object.assign(a.verdict.controlChecklist[1],{status:'warn',statusLabel:'HPE indisponible',evidence:'La cellule HPE reste indisponible côté fournisseur.',action:'Vérifier l’annonce auprès de l’émetteur avant toute exécution.'});
Object.assign(a.business.coverageMatrix.find(x=>x.facet==='Comparables et transmission'),{status:'COUVERT — LOCAL ET RANKBETA',decision:'Rendements locaux et contrôle de couverture RankBeta disponibles; aucune relation de transmission n’est certifiée par une corrélation.'});
Object.assign(a.business.coverageMatrix.find(x=>x.facet==='Calendrier'),{status:'PARTIEL / EXPLICITE',decision:'HPE indisponible : aucune conclusion d’absence de catalyseur.'});
a.blastRadius.methodology=a.blastRadius.methodology.replace('Relations économiques documentées; RankBeta indisponible côté fournisseur bloque la certification.','Relations économiques documentées; RankBeta sert de contrôle de couverture sur le snapshot courant.').replace('le classement élargi reste indisponible','le classement élargi sert de contrôle de couverture');
a.blastRadius.methodology=a.blastRadius.methodology.replace('sans preuve de causalité ni remplacement du classement élargi indisponible','sans preuve de causalité; RankBeta sert de contrôle de couverture distinct');
a.blastRadius.contradictions=a.blastRadius.contradictions.map(x=>x.replace('RankBeta et calendrier HPE bloquent la certification.','Le calendrier HPE reste indisponible; RankBeta ne transforme pas les corrélations en causalité.'));
a.blastRadius.missingData=a.blastRadius.missingData.filter(x=>!x.includes('RankBeta'));
a.tradeIdea.catalysts=a.tradeIdea.catalysts.map(x=>x.replace('Restaurer RankBeta et calendrier HPE; réconcilier les conditions de warrants.','Vérifier le calendrier HPE et réconcilier les conditions de warrants.'));
a.globalScore.keyTakeawaysNegative=a.globalScore.keyTakeawaysNegative.map(x=>x.replace('RankBeta indisponible et calendrier HPE indisponible.','Calendrier HPE indisponible; options, insiders et CTB non confirmatoires.'));
a.verdict.whyAvoid=a.verdict.whyAvoid.map(x=>x.replace('Les options couvrent trois expiries et 288 contrats, mais les cotations ont des alertes intrinsèques : aucun biais de flow n’est retenu.','La couverture optionnelle présente des alertes de cotation : aucun chiffre ni biais de flux n’est retenu sans certification obligatoire.'));
a.verdict.whyAvoid[1]='Les deux warrants partenaires sont plafonnés à 160 M d’actions chacun sous conditions; le dénominateur pleinement dilué courant n’est pas certifié.';
a.options.skew='Couverture optionnelle en quarantaine';
Object.assign(a.business.coverageMatrix.find(x=>x.facet==='Options'),{status:'PRÉSENTES / QUARANTAINE',decision:'Alertes de cotation intrinsèques; aucun chiffre ni signal directionnel publié.'});
Object.assign(a.shortInterest,{siPct:'Non publié',daysToCover:'Non publié',ctb:'Non interprétable',trend:'Couverture short optionnelle non certifiée dans le harness obligatoire; aucune thèse squeeze.',squeezeScore:'Non exploitable'});
a.disclaimer='Document de recherche éducatif. Ni conseil financier, ni signal de trading. Aucun ordre actif.';
write(rev+'/AMD.json',a);
const judgments={ticker:'AMD',score_components:{business:16,technical:6,capital:-9,calendar_gap:-12,dilution:-9,risk:50},judgments:{'meta.version':{value:3,reason:'Identifiant éditorial de la révision locale.'},'meta.date':{value:'2026-09-19',reason:'Date de construction locale distincte de la clôture.'},'verdict.score':{value:42,reason:'Score éditorial additif : business, technique et pénalités de capital, calendrier, dilution et risques.'},'risks.riskScore':{value:8,reason:'Jugement qualitatif sur dix : exécution, valorisation, capital conditionnel et facettes partielles.'}}};
judgments.judgments['meta.dateDisplay']={value:a.meta.dateDisplay,reason:'Date éditoriale française, non une observation financière.'};
a.blastRadius.groups.forEach((g,i)=>judgments.judgments['blastRadius.groups.'+i+'.order']={value:g.order,reason:'Classification économique éditoriale du mécanisme de transmission, pas causalité mesurée.'});
write(rev+'/editorial-judgments.json',judgments);
(function({a,raw,root,run,rev,data,sha,read,write,bytes,primary,archivePath,judgments,completion,f,s,ev,close}){
 const path=require('path'),esc=v=>String(v).replace(/~/g,'~0').replace(/\//g,'~1');
 const get=(o,p)=>p.split('.').reduce((v,k)=>v?.[k],o);
 const find=(o,type,p='')=>{if(o&&typeof o==='object'){if(o.type===type)return p;for(const[k,v]of Object.entries(o)){const r=find(v,type,p+'/'+esc(k));if(r!==undefined)return r;}}};
 const inputs=[];
 for(const[name,file]of [['bars','bars'],['fund','fundamentals'],['tech','technicals'],['insiders','insiders'],['comparison','comparison_bars'],['rank','rank_beta'],['status','status']])inputs.push({name,path:data+'/'+file+'.json',sha256:sha(bytes(data+'/'+file+'.json'))});
 for(const[name,p,kind]of [['primary',rev+'/primary-manifest.json','primary_sec_manifest_v1'],['archive',archivePath,'archived_analysis'],['judgments',rev+'/editorial-judgments.json','editorial_judgment']])inputs.push({name,path:p,sha256:sha(bytes(p)),kind});
 const input=n=>inputs.find(x=>x.name===n),dep=(n,p)=>({input_path:input(n).path,input_sha256:input(n).sha256,source_pointer:p});
 const prov=(n,p,method,additional_inputs=[])=>({...dep(n,p),input_name:n,method,...(additional_inputs.length?{additional_inputs}:{})});
 const B='/results/0/data/0/bars',F=find(raw.fund,'instrument_comprehensive_financial'),S=find(raw.fund,'instrument_comprehensive_stats'),T=find(raw.tech,'instrument_technicals');
 const C=ticker=>{const i=raw.comparison.data.items[0].results[0].data.findIndex(x=>x.symbol===ticker);if(i<0)throw Error('Missing comparable '+ticker);return '/data/items/0/results/0/data/'+i+'/bars';};
 const marketMath=()=>prov('fund',F,'Capitalisation = close × actions; EV = capitalisation + dette − cash. Ratios sur comptes fournisseur non datés; aucune période TTM présumée.',[dep('fund',S),dep('bars',B+'/299/4')]);
 function sourceFor(p){
  if(/^meta\.(lastMcpRefresh|levelsVerifiedAt)$/.test(p))return prov('status','/captured_at','Horodatage exact de la collecte MCP gouvernée.');
  if(judgments.judgments[p])return prov('judgments','/judgments/'+esc(p)+'/value',judgments.judgments[p].reason);
  const ref=p.match(/^(.*)\.sourceRefs\.(\d+)\.(date|url|name)$/);if(ref){const r=get(a,ref[1]+'.sourceRefs.'+ref[2]);if(r.url==='https://mcp.dailytickers.com/mcp')return prov('status','/captured_at','Date de collecte MCP, non date du cours.');const i=primary.documents.findIndex(x=>x.url===r.url);if(i<0)throw Error('Unknown primary reference');return prov('primary','/documents/'+i,'Métadonnée exacte du dépôt ouvert et haché.');}
  if(p==='tradeIdea.archiveReferenceClose')return prov('archive','/meta/levelsCloseDate','Date exacte de l’archive inactive, non la clôture actuelle.');
  if(/^tradeIdea\.(entry|stop|tp1|tp2)$/.test(p))return prov('archive','/'+p.replaceAll('.','/'),'Niveau exact conservé dans une archive non exécutable.');
  if(/^tradeIdea\.(stopPct|tp1Pct|tp2Pct|rr)$/.test(p))return {...prov('archive','/tradeIdea','Géométrie calculable depuis l’archive; jamais une nouvelle idée.'),derivation:'archived_trade_geometry'};
  if(p==='meta.levelsCloseDate'||p==='blastRadius.asOf')return prov('bars',B+'/299/0','Dernière séance complète des barres quotidiennes.');
  if(p==='blastRadius.observationTime')return prov('status','/captured_at','Horodatage de la collecte du snapshot.');
  if(p==='header.price')return prov('bars',B+'/299/4','Clôture complète de référence.');
  if(p==='header.changePct')return prov('bars',B+'/299/4','100 × (dernier close / close précédent − 1).',[dep('bars',B+'/298/4')]);
  if(p==='header.metrics.volume')return prov('bars',B+'/299/5','Volume de la dernière séance, en millions.');
  if(p.startsWith('header.metrics.')||p==='verdict.whyAvoid.0')return marketMath();
  if(p==='verdict.whyAvoid.1')return prov('primary','/documents/1','Plafonds conditionnels des deux warrants partenaires; actions non acquises au dernier dépôt examiné.');
  if(p.startsWith('verdict.whyBuy.')||(p.startsWith('business.overview')||p==='business.moat')||p.startsWith('business.segments.')||p.startsWith('earnings.'))return prov('primary','/documents/0','Résultats et guidance officiels Q2 2026; attentes futures séparées des résultats, extraits vérifiés dans le dépôt archivé.');
  const fund=p.match(/^fundamentals\.rows\.(\d+)\./);if(fund){const i=+fund[1];if(i===5||i===6)return marketMath();const k=i<5?['totalRevenue','ebitda','grossMargins','totalCash','totalDebt'][i]:completion.extraFundamentalKeys[i-7];if(!k)throw Error('Unmapped fundamental '+p);return prov('fund',(k==='sharesOutstanding'?S:F)+'/'+k,'Valeur du snapshot : montants en milliards, ratios × cent; période comptable non inventée.',[dep('status','/captured_at')]);}
  if(p.startsWith('technicals.'))return prov('tech',T,'Indicateurs du snapshot fournisseur, descriptifs; continuité quotidienne vérifiée séparément.',[dep('bars',B)]);
  if(p.startsWith('capitalStructure.sharesOutstanding'))return prov('fund',S+'/sharesOutstanding','Actions courantes fournisseur en milliards; pas une somme entièrement diluée.');
  if(p.startsWith('capitalStructure.shareHistory'))return prov('primary','/documents/1','Actions pondérées du trimestre distinctes des actions courantes et dilution conditionnelle; dette distincte de l’equity.',[dep('fund',S+'/sharesOutstanding'),dep('primary','/documents/2')]);
  if(p.startsWith('capitalStructure.warrants.'))return prov('primary','/documents/1','Note des warrants commerciaux : plafond par partenaire, acquisition et exercice conditionnels, aucun acquis au 27 juin.');
  if(/^news\.\d+\./.test(p)){const row=a.news[+p.split('.')[1]],i=primary.documents.findIndex(x=>x.url===row.sourceUrl);return prov('primary','/documents/'+i,'Dépôt primaire de la nouvelle : date, nature du financement ou résultats.');}
  if(/^filingsReview\.filings\.\d+\./.test(p))return prov('primary','/documents/'+p.split('.')[2],'Constat et métadonnées du dépôt exact haché.');
  if(p.startsWith('shortInterest.'))return prov('fund',S,'Positions vendeuses et days-to-cover du snapshot statistique; aucune date de règlement inférée.');
  if(p.startsWith('options.')||p==='verdict.whyAvoid.2'||p.startsWith('business.coverageMatrix.5.'))return prov('options','', 'Compter les contrats et échéances retournés; les alertes de cotation empêchent toute lecture directionnelle.');
  if(p.startsWith('performance.windowReturns.')){const m=p.match(/rows\.(\d+)/),ticker=m?a.performance.windowReturns.rows[+m[1]].ticker:'AMD';return prov(ticker==='AMD'?'bars':'comparison',ticker==='AMD'?B:C(ticker),'Rendement simple entre dernier close et close vingt et une séances auparavant, sans dividendes réinvestis.');}
  if(p==='blastRadius.window')return prov('comparison',C('NVDA'),'Fenêtre des dates communes, rendements logarithmiques calculés à partir des clôtures.',[dep('bars',B)]);
  const bm=p.match(/^blastRadius\.groups\.(\d+)\.symbols\.(\d+)\./);if(bm){const row=a.blastRadius.groups[+bm[1]].symbols[+bm[2]];return prov('comparison',C(row.ticker),'124 rendements communs; corrélation Pearson, beta AMD sur pair = covariance / variance pair, R² = corrélation au carré; rendements simples cinq et vingt et une séances.',[dep('bars',B)]);}
  if(p.startsWith('macro.indicators.'))return prov('bars',B,'Clôture certifiée et rendements cinq / vingt et une séances calculés localement.');
  if(p.startsWith('business.coverageMatrix.3.'))return prov('primary','/documents/0','Résultats trimestriels primaires distincts du snapshot financier fournisseur.',[dep('fund',F)]);
  if(p.startsWith('business.coverageMatrix.0.'))return prov('bars',B,'300 séances continues et dernier close certifié; pas une performance de trade.');
  if(p.startsWith('risks.riskCards.0.'))return prov('primary','/documents/1','Plafonds et conditions des deux warrants commerciaux dans le rapport trimestriel.');
  if(p==='filingsReview.contrarianRisks.1')return prov('primary','/documents/0','Charge export identifiée dans le communiqué de résultats.');
  if(p==='risks.riskCards.1.points.1')return prov('primary','/documents/0','Charge comparative associée au produit MI308, désignation et contexte officiels.');
  throw Error('Missing semantic provenance '+p);
 }
 const claims={},strings={},methods={};function scan(v,p=''){if(typeof v==='number'||typeof v==='string'&&/\d/.test(v)){claims[p]=sourceFor(p);methods[p]=claims[p].method;if(typeof v==='string')strings[p]=v;}else if(v&&typeof v==='object')for(const[k,x]of Object.entries(v))scan(x,p?p+'.'+k:k);}scan(a);
 const multiple=ev/f.ebitda*0.7,enterprise_value=multiple*f.ebitda,equity_value=enterprise_value-f.totalDebt+f.totalCash,price=equity_value/s.sharesOutstanding;
 const calc={kind:'deterministic_analysis_calculation_v1',ticker:'AMD',reference_close:'2026-09-18',analysis_sha256:sha(bytes(rev+'/AMD.json')),generator_path:'.agent/analyses-refresh-20260919/amd-revision/build-amd.cjs',generator_sha256:sha(bytes('.agent/analyses-refresh-20260919/amd-revision/build-amd.cjs')),inputs,score_components:judgments.score_components,valuation_scenario:{multiple,ebitda:f.ebitda,debt:f.totalDebt,cash:f.totalCash,shares:s.sharesOutstanding,close,enterprise_value,equity_value,price,downside_pct:(price/close-1)*100},values:a,string_numeric_claims:strings,claim_provenance:claims,methods,limitations:['Comptes fournisseurs non datés; ratios indicatifs.','RankBeta opérationnel; calendrier HPE incomplet.','Aucune attestation finale ni ordre actif.']};
 write(rev+'/calculations.json',calc);write(rev+'/numeric-evidence.json',calc);
 const calcHash=sha(bytes(rev+'/numeric-evidence.json'));
 write(rev+'/evidence.json',{ticker:'AMD',reference_close:'2026-09-18',analysis_path:rev+'/AMD.json',analysis_sha256:sha(bytes(rev+'/AMD.json')),claims:Object.keys(claims).map(p=>({path:p,value:get(a,p),as_of:'2026-09-18',source_artifact:rev+'/numeric-evidence.json',source_sha256:calcHash,source_pointer:typeof get(a,p)==='number'?'/values/'+p.split('.').map(esc).join('/'):'/string_numeric_claims/'+esc(p)}))});
 console.log('AMD semantic mappings: '+Object.keys(claims).length);
})({a,raw,root,run,rev,data,sha,read,write,bytes,primary,archivePath,judgments,completion,f,s,ev,close});
const {render,validate,SCHEMA}=require(path.join(root,'tools/render-analysis.js'));const errs=validate(a,SCHEMA);if(errs.length)throw Error(errs.join('; '));fs.writeFileSync(path.join(root,rev,'index.html'),render(a));
