'use strict';
// Dossier HOOD v3 au close du 2026-09-25 (lot R07). Émetteur domestique US (10-K/10-Q/8-K, us-gaap) :
// builder r07 STANDARD, companyfacts SEC, aucune donnée manuelle. Contenu éditorial et niveaux propres au
// titre ; calculs, provenance et preuves délégués au gabarit commun tools/lib/analysis-v3-r07.cjs.
// Comparables : 16 symboles propres, géométrie et continuité pré-vérifiées barre par barre sur le serveur
// stabilisé ; crypto (BTC/ETH/SOL) écartés des comparables (calendrier 24/7 et absence d'earnings incompatibles
// avec le contrat de clôture actions) — l'exposition crypto reste captée par COIN. peerFicheSha vide : les
// multiples des pairs sont lus dans comparison_context (peerStat courant), pas dans des fiches sœurs.
// Robinhood n'a pas de ligne d'exploitation us-gaap : le résultat avant impôts sert de proxy opérationnel
// (« EBITDA » = résultat avant impôts + amortissements), choix documenté dans valuationBasis.
const R = require('../../../../tools/lib/analysis-v3-r07.cjs');
const GEN = 'analyses/HOOD/_runs/20260927/build-hood.cjs';

R.build({
  ticker: 'HOOD', shortName: 'Robinhood Markets', cik: 1783879, generator: GEN, mode: 'breakout',
  xbrl: { ttm: { rev: ['Revenues'], ebit: ['IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest'], ni: ['NetIncomeLoss'], da: ['DepreciationDepletionAndAmortization'], ocf: ['NetCashProvidedByUsedInOperatingActivities'] },
    instant: { cashEq: ['CashAndCashEquivalentsAtCarryingValue'], conv: ['ConvertibleDebtNoncurrent'] }, da: ['da'], debt: ['conv'], cash: ['cashEq'] },
  scenarioBasis: 'ebitda', scenarioMultiple: 25,
  valuationBasis: 'GAAP douze mois glissants au 2026-06-30 (données XBRL officielles SEC) ; Robinhood ne publie pas de ligne de résultat opérationnel us-gaap : « EBITDA » = résultat avant impôts (proxy du résultat opérationnel pour un courtier) + amortissements ; dette = billets convertibles de 2,17 Md$, seule dette portant intérêt (les dépôts et le cash des clients ne sont pas de la dette du groupe) ; trésorerie = liquidités et équivalents du 30 juin ; 899 082 273 actions A et B au 23 juillet 2026 ; multiple de vingt-cinq fois l’EBITDA = hypothèse éditoriale de re-notation, pas un objectif',
  levels: { trigger: { d: '2026-09-23', c: 2 }, stop: { d: '2026-09-25', c: 3 }, abandon: { d: '2026-09-16', c: 3 }, s1: { d: '2026-09-24', c: 3 }, s2: { d: '2026-09-10', c: 3 }, r1: { d: '2026-09-21', c: 2 }, r2: { d: '2026-09-08', c: 2 } },
  supports: ['s1', 'stop', 's2'], resistances: ['r1', 'r2', 'trigger'],
  targets: ({ entry, abandon }) => { const range = entry - abandon; return { tp1: entry + range, tp2: entry + 1.5 * range, range }; },
  levelsMethod: 'Déclencheur = plus haut du 23 septembre, sommet de la série récente ; bas du couloir = plus bas du 16 septembre ; stop = plus bas du 25 septembre ; TP1 = déclencheur + hauteur du couloir (déclencheur − bas du 16) ; TP2 = déclencheur + 1,5 × hauteur ; plafond = (TP1 + 1,5 × stop) / 2,5 arrondi au cent inférieur ; pourcentages depuis l’entrée ; R/R = gain / risque.',
  inventory: 25,
  reviewScope: 'Dépôts EDGAR de Robinhood Markets du 1er février au 25 septembre 2026 (25 formulaires hors formulaires 3, 4, 5, 144 et leurs amendements), dont le 10-K de l’exercice clos le 31 décembre 2025, deux 10-Q, dix 8-K, une déclaration de procuration DEF 14A, deux Schedule 13G d’investisseurs passifs et un S-8. Trois dépôts décisionnels sont ouverts et hachés : le 10-Q du deuxième trimestre 2026, le 8-K de résultats et son exhibit 99.1, et le 10-K annuel. Les 8-K de gouvernance, la procuration, les Schedule 13G (détention passive, sans intention d’influence), le S-8 (plan d’actionnariat salarié) et les formulaires de fonds fermé (40-6B, 40-APP) sont écartés, non décisionnels pour la structure de capital et la valorisation.',
  docs: [
    ['2026-07-30', '10-Q', '0001783879-26-000114', 'hood-20260630.htm', 'q2-10q__hood-20260630.htm',
      'Rapport trimestriel au 30 juin 2026 : 790 630 234 actions A et 108 452 039 actions B au 23 juillet, soit 899 082 273 titres ; billets convertibles potentiellement convertibles en 12,6 millions d’actions A ; bons de souscription pour 8,74 millions d’actions A au prix d’exercice de 26,60 $, échéance février 2031, exerçables par règlement net ; 2 millions d’actions A non acquises émises pour l’acquisition de TradePMR ; rachats d’actions en cours.'],
    ['2026-07-29', '8-K / Exhibit 99.1', '0001783879-26-000113', 'q22026robinhoodexhibit991.htm', 'q2-8k__q22026robinhoodexhibit991.htm',
      'Communiqué du deuxième trimestre 2026 : revenus nets totaux de 1,308 Md$ (+32 %), revenus de transaction de 776 M$ (+44 %, dont contrats événementiels 156 M$, ×10, options 342 M$, actions 129 M$, crypto 100 M$, −38 %), revenus d’intérêt nets de 389 M$ (+9 %), bénéfice net de 573 M$ (dont 129 M$ de gains de déconsolidation), BPA dilué de 0,62 $, EBITDA ajusté non-GAAP de 741 M$, 28,4 millions de comptes financés, dépôts nets record de 22 Md$, 4,8 millions d’abonnés Gold.'],
    ['2026-02-18', '10-K', '0001783879-26-000023', 'hood-20251231.htm', 'fy25-10k__hood-20251231.htm',
      'Rapport annuel de l’exercice clos le 31 décembre 2025 : structure à deux classes d’actions — action A à une voix, action B à dix voix, action C sans droit de vote ; les fondateurs et leurs affiliés détiennent la totalité des actions B et gardent le contrôle des votes. Modèle de courtier de détail : revenus de transaction dont le paiement pour flux d’ordres (PFOF), revenus d’intérêt nets et abonnements.'],
  ],
  needles: {
    q10q: [0, ['Class A and Class B common stock outstanding were 790,630,234 and 108,452,039',
      'the Convertible Notes are potentially convertible into 12.6 million shares of Class A common stock',
      'strike price of $ 26.60 that can be exercised to purchase 8.74 million shares of Class A common stock',
      'The warrants expire on February 12, 2031',
      'acquisition of TradePMR, we issued approximately 2 million unvested shares of Class A common stock',
      'Includes 2,743,000 shares of Class A common stock repurchased']],
    q2: [1, ['Total net revenues 989 1,308 32 %',
      'Net income increased 48% year-over-year to $573 million',
      'Net income included $129 million of gains',
      'Diluted EPS up 48% year-over-year to $0.62',
      'Net Deposits were a record $22 billion, and Robinhood Gold Subscribers reached a record 4.8 million',
      'Transaction-based revenues increased 44% year-over-year to $776 million',
      'event contracts revenue of $156 million, up over 10x',
      'Net interest revenues increased 9% year-over-year to $389 million',
      'cryptocurrencies revenue of $100 million, down 38%',
      'Adjusted EBITDA (non-GAAP) increased 35% year-over-year to $741 million',
      'Funded Customers increased by 1.9 million, or 7%, year-over-year to 28.4 million']],
    annual: [2, ['Class A common stock has one vote per share, our Class B common stock has 10 votes per share, and our Class C common stock has no voting rights',
      'Our founders and Founder Affiliates together hold all of the issued']],
  },
  sectionDocs: { verdict: [1, 0, 2], business: [1, 2, 0], news: [1], earnings: [1], capitalStructure: [0, 2], filingsReview: [0, 1, 2], risks: [0, 1, 2], globalScore: [1], meta: [1], disclaimer: [1], macro: [0], options: [1], shortInterest: [0], insiders: [0], social: [1], technicals: [0], header: [0], performance: [0] },
  score: { business: 34, technical: 8, capital: 2, calendar: 0, dilution: 0, risk: 20 },
  peers: true,
  peerFicheSha: {},
  shares: { value: 899082273, doc: 0 },
  route: (p, { prov, dep, B }) => /^news\.\d+\./.test(p) ? prov('bars', B, 'Ouverture et clôture lues sur les barres certifiées ; écart d’ouverture = ouverture / clôture de la veille − 1 ; comparaison avec les pairs sur la même séance.', [dep('comparison', '')]) : null,
  riskScoreReason: 'Jugement qualitatif sur dix : valorisation très élevée (plus de cinquante fois le bénéfice), profits liés au cycle du trading et de la crypto, ventes régulières des dirigeants et des fondateurs, contre un bilan sans dette nette et une trésorerie abondante.',
  compose: c => {
    const { fr, usd, pct, sgn, close, prev, bars, N, tech, st, adv, ret, G$, marketCap, ev, scn, lv, entry, stop, tp1, tp2, abandon, cap, rr1, rr2, riskAtr, sizeExample, ref, market, docs, raw, peerStat } = c;
    const gs = c.gapStats(cap - entry), bufAtr = (cap - entry) / tech.atr14, blocked = gs.up / gs.total * 100;
    const bufPct = (cap / entry - 1) * 100, bk = c.breakoutStats(bufPct), rt = c.retestStats(bufPct, (1 - stop / entry) * 100);
    const cmp = raw.comparison_bars.data.items[0].results[0].data;
    const dr = (sym, d) => { const b = cmp.find(x => x.symbol === sym).bars, i = b.findIndex(x => x[0] === d); return pct(b[i][4], b[i - 1][4]); };
    const bar = d => bars.find(b => b[0] === d), prevOf = d => bars[bars.findIndex(b => b[0] === d) - 1];
    const d0903 = bar('2026-09-03'), p0903 = prevOf('2026-09-03'), d0916 = bar('2026-09-16'), d0918 = bar('2026-09-18'), p0918 = prevOf('2026-09-18'), d0925 = bar('2026-09-25'), d0921 = bar('2026-09-21');
    const low0916 = bar('2026-09-16'), high0923 = bar('2026-09-23'), low0731 = bar('2026-07-31');
    const run = close / low0731[3];
    const evEbitda = ev / G$.ebitda, evRev = ev / G$.rev, pe = marketCap / G$.ni, pb = close / st.bookValue;
    const coinEb = peerStat('COIN'), ndaqEb = peerStat('NDAQ'), mcoEb = peerStat('MCO'), spgiEb = peerStat('SPGI'), cmeEb = peerStat('CME');
    const ext20 = pct(close, tech.ema20);
    const bufOpen = bk.n ? bk.buyable / bk.n : 0;
    const big = Math.floor(1000 / (cap - stop));
    return {
      meta: { lang: 'fr', dir: 'ltr', level: 'intermediate', tags: ['us', 'equities', 'financials', 'fintech', 'crypto'], grade: 'B', date: '2026-09-25', dateDisplay: '25 septembre 2026', version: 3, status: 'watch', assetType: 'stock', levelsCloseDate: c.REF,
        description: 'Robinhood Markets : revenus du deuxième trimestre de 1,308 Md$ (+32 %), bénéfice net de 573 M$, 28,4 millions de comptes financés. Titre payé plus de cinquante fois le bénéfice, en consolidation sous son sommet du 23 septembre. Dossier au close du 25 septembre 2026, statut surveiller.',
        ogDescription: 'Robinhood : revenus +32 %, contrats événementiels ×10 ; titre à 119,40 $, environ 6 % sous son sommet du 23 septembre, payé plus de cinquante fois le bénéfice ; niveaux à surveiller.',
        lastMcpRefresh: raw.status.captured_at, levelsVerifiedAt: raw.status.captured_at,
        statusHistory: [...(c.archive.meta.statusHistory || []), { at: raw.status.captured_at, from: 'watch', to: 'watch', note: 'refonte v3 du 25 septembre : clôture de référence 2026-09-25, consolidation sous le sommet du 23 septembre, seize comparables propres pré-vérifiés', close }] },
      header: { ticker: 'HOOD', name: 'Robinhood Markets, Inc.', exchange: 'NASDAQ', sector: 'Courtage de détail, crypto et services financiers', price: close, changePct: pct(close, prev),
        badges: [{ text: 'SURVEILLER — ACTIVATION AU-DESSUS DU SOMMET DU 23 SEPTEMBRE', color: 'blue' }, { text: 'Courtier retail — trading, crypto et intérêts', color: 'purple' }],
        metrics: { marketCap: fr(marketCap / 1e9, 0) + ' Md$', volume: fr(bars[N][5] / 1e6, 2) + ' M', evEbitda: fr(evEbitda, 1) + '×' }, halalStatus: 'unknown' },
      verdict: { score: 64, conviction: 'Moderate', bias: 'Neutral',
        confidence: 'Score éditorial non prédictif. Les chiffres d’entreprise viennent des dépôts SEC et des données XBRL officielles ; les niveaux, du close certifié du 25 septembre.',
        summary: 'Robinhood a publié le 29 juillet un deuxième trimestre de 1,308 Md$ de revenus nets (+32 %), 573 M$ de bénéfice net et 0,62 $ de bénéfice dilué par action, pour un EBITDA ajusté non-GAAP de 741 M$. Le moteur est le trading : 776 M$ de revenus de transaction (+44 %), tirés par les contrats événementiels, multipliés par dix à 156 M$, et les options à 342 M$ ; la crypto recule de 38 %, à 100 M$. Les revenus d’intérêt nets ajoutent 389 M$, les comptes financés atteignent 28,4 millions et les dépôts nets un record de 22 Md$. Le titre a clôturé à ' + usd(close) + ' le 25 septembre, ' + fr(pct(close, prev), 1) + ' % sur la séance, après un sommet à ' + usd(high0923[2]) + ' le 23, qu’il reste environ ' + fr(Math.abs(pct(close, entry)), 1) + ' % sous. À ' + fr(evEbitda, 1) + ' fois l’EBITDA GAAP, ' + fr(pe, 0) + ' fois le bénéfice et ' + fr(pb, 1) + ' fois les capitaux propres, Robinhood se paie au-dessus des bourses cotées (Nasdaq à ' + fr(ndaqEb, 1) + '×, Moody’s à ' + fr(mcoEb, 1) + '×) et sous Coinbase (' + fr(coinEb, 1) + '×) : le marché price une croissance qui suppose que les volumes tiennent. Rothschild vise 85 $, sous le cours, avec une opinion vendeuse. Le plan est en attente : signal utile, une clôture au-dessus de ' + usd(entry) + '.',
        whyBuy: [
          'Revenus nets du deuxième trimestre de 1,308 Md$ (+32 %) et bénéfice net de 573 M$, dont 129 M$ de gains de déconsolidation.',
          'Diversification des revenus de transaction : contrats événementiels ×10 à 156 M$, options 342 M$ (+29 %), actions 129 M$ (+95 %), qui compensent une crypto en repli.',
          '28,4 millions de comptes financés, 4,8 millions d’abonnés Gold et 22 Md$ de dépôts nets record : la base de clients et d’actifs continue de grossir.',
          'Bilan sans dette nette : 5,36 Md$ de liquidités contre 2,17 Md$ de billets convertibles, et un programme de rachat d’actions actif.'],
        whyAvoid: [
          'Le titre se paie ' + fr(pe, 0) + ' fois le bénéfice et ' + fr(evEbitda, 1) + ' fois l’EBITDA : une bonne partie de la croissance est déjà dans le prix.',
          'Les profits dépendent du cycle : le trading d’options et de crypto et les revenus d’intérêt reculent quand l’appétit du retail ou les taux baissent.',
          'Ventes d’initiés continues : zéro achat et trente-cinq ventes sur quatre-vingt-dix jours, dont le directeur général et un cofondateur en septembre.',
          'Un analyste (Rothschild) vise 85 $, soit environ ' + fr(Math.abs(pct(85, close)), 0) + ' % sous le cours : le consensus n’est pas unanimement acheteur.'],
        controlChecklist: [
          { label: 'Historique de cours', status: 'pass', statusLabel: 'Trois cents séances continues', evidence: 'Série quotidienne certifiée au close du 25 septembre, géométrie et continuité vérifiées barre par barre.', action: 'Niveaux et indicateurs recalculés sur cette seule série.' },
          { label: 'Calendrier', status: 'pass', statusLabel: 'Résultats hors horizon', evidence: 'Le deuxième trimestre a été publié le 29 juillet ; le calendrier de marché place le troisième trimestre vers le 4 novembre, non confirmé ici par l’émetteur, au-delà de l’horizon du plan.', action: 'Aucun risque de publication à porter sur les dix séances suivant une activation.' },
          { label: 'Valorisation', status: 'warn', statusLabel: fr(pe, 0) + '× le bénéfice', evidence: 'À ' + fr(evEbitda, 1) + '× l’EBITDA et ' + fr(pe, 0) + '× le bénéfice, la marge d’erreur est faible : tout ralentissement des volumes se paie cher.', action: 'Traiter le titre comme une valeur de momentum chère, pas comme une valeur de rendement.' }] },
      business: { theme: 'Courtage de détail, crypto, contrats événementiels et revenus d’intérêt',
        overview: '<p>Robinhood est un courtier de détail qui gagne de l’argent de trois façons. Les revenus de transaction, 776 M$ au deuxième trimestre (+44 %), viennent du routage rémunéré des ordres — le paiement pour flux d’ordres, ou PFOF — sur les options (342 M$), les actions (129 M$), la crypto (100 M$) et, désormais, les contrats événementiels (156 M$, multipliés par dix). Les revenus d’intérêt nets, 389 M$ (+9 %), proviennent des soldes de trésorerie des clients, des prêts sur marge et du prêt de titres. Les autres revenus, dont les abonnements Robinhood Gold, complètent le total net de 1,308 Md$.</p><p>Le deuxième trimestre a porté le bénéfice net à 573 M$ et le bénéfice dilué à 0,62 $, avec un EBITDA ajusté non-GAAP de 741 M$. Le bénéfice inclut 129 M$ de gains liés à la déconsolidation de Robinhood Ventures. Sur douze mois glissants, les revenus GAAP atteignent ' + fr(G$.rev / 1e9, 2) + ' Md$ et le bénéfice net ' + fr(G$.ni / 1e9, 2) + ' Md$.</p><p>Le nombre de comptes financés atteint 28,4 millions (+7 %), les abonnés Gold 4,8 millions et les dépôts nets un record de 22 Md$ sur le trimestre. Le modèle est cyclique : quand les marchés montent et que les particuliers tradent, les trois moteurs tournent ensemble ; quand l’appétit retombe, les revenus de transaction et d’intérêt baissent de concert. La gouvernance est verrouillée par une structure à deux classes d’actions : l’action B porte dix voix, et les fondateurs et leurs affiliés en détiennent la totalité, gardant le contrôle des votes.</p>',
        moat: 'L’avantage tient à la marque, à la simplicité de l’application et à une base de près de vingt-huit millions de clients acquis à faible coût, que Robinhood cherche à monétiser au-delà du trading (Gold, cartes, gestion de patrimoine, contrats événementiels). Il est réel côté acquisition, mais le cœur du revenu — le PFOF et le trading — reste sensible à la réglementation et à la concurrence de courtiers plus gros (Schwab, Interactive Brokers) et de plateformes crypto (Coinbase).',
        segments: [
          { name: 'Revenus de transaction', revenue: '776 M$ au deuxième trimestre', pct: '59 % des revenus nets', description: 'Options 342 M$, contrats événementiels 156 M$ (×10), actions 129 M$, crypto 100 M$ (−38 %).' },
          { name: 'Revenus d’intérêt nets', revenue: '389 M$ au deuxième trimestre', pct: '30 % des revenus nets', description: 'Soldes de trésorerie clients, marge et prêt de titres ; sensibles aux taux courts.' },
          { name: 'Autres revenus', revenue: 'Solde vers 1,308 Md$', pct: '11 % des revenus nets', description: 'Abonnements Robinhood Gold et services complémentaires.' }],
        sourceRefs: [ref(1), ref(2), ref(0)],
        coverageMatrix: [
          { facet: 'Cours et historique', status: 'COUVERT', decision: 'Trois cents séances continues, close certifié ; base des niveaux et des indicateurs.' },
          { facet: 'Résultats et guidance', status: 'COUVERT — PRIMAIRE', decision: 'Communiqué du 29 juillet et 10-Q du deuxième trimestre ; date du troisième trimestre non annoncée par l’émetteur.' },
          { facet: 'Capital et dilution', status: 'COUVERT — PRIMAIRE', decision: 'Actions A et B, billets convertibles, bons de souscription et rachats lus dans le 10-Q ; aucun dépôt de dilution récent.' },
          { facet: 'Agrégats GAAP', status: 'COUVERT — XBRL', decision: 'Douze mois glissants au 30 juin 2026, reconstitués depuis les données XBRL officielles.' },
          { facet: 'Comparables et transmission', status: 'COUVERT — LOCAL', decision: 'Corrélations recalculées sur barres certifiées depuis janvier, sur seize comparables propres pré-vérifiés.' },
          { facet: 'Initiés', status: 'COUVERT', decision: 'Zéro achat, trente-cinq ventes sur quatre-vingt-dix jours ; conversions et ventes du directeur général en septembre.' },
          { facet: 'Options', status: 'PARTIEL', decision: 'Chaîne relevée le 28 septembre, échéance courte, non rattachée à la clôture de référence ; positionnement indicatif seulement.' },
          { facet: 'Sentiment social', status: 'NON EXPLOITABLE', decision: 'Flux Reddit et Google Trends indisponibles à la collecte ; non retenus faute de mesure qualifiée.' }] },
      news: [
        { date: '2026-09-03', title: 'Bond de ' + fr(pct(d0903[4], p0903[4]), 1) + ' % en une séance', impact: 'positive', detail: 'Le 3 septembre, le titre ouvre à ' + usd(d0903[1]) + ', ' + fr(pct(d0903[1], p0903[4]), 1) + ' % au-dessus de la clôture de la veille, ' + usd(p0903[4]) + ', et clôture à ' + usd(d0903[4]) + ' (' + sgn(pct(d0903[4], p0903[4]), 2) + ') sur un volume de ' + fr(d0903[5] / 1e6, 0) + ' millions de titres, le plus fort de la fenêtre. Coinbase fait ' + sgn(dr('COIN', '2026-09-03'), 2) + ' et le panier de courtiers IAI ' + sgn(dr('IAI', '2026-09-03'), 2) + ' la même séance : le mouvement est en grande partie propre à Robinhood ; aucun dépôt ouvert ici n’en donne la cause précise.', source: 'Barres certifiées', sourceUrl: c.evidenceUrl },
        { date: '2026-09-16', title: 'Repli à ' + usd(low0916[3]) + ' puis rebond', impact: 'neutral', detail: 'Le 16 septembre, le titre enfonce un plus bas à ' + usd(low0916[3]) + ' avant de clôturer à ' + usd(d0916[4]) + ', point bas de la consolidation en cours. Coinbase recule de ' + fr(Math.abs(dr('COIN', '2026-09-16')), 1) + ' % le même jour : la faiblesse est partagée avec la crypto. Ce plancher sert de bas du couloir et d’invalidation du scénario.', source: 'Barres certifiées', sourceUrl: c.evidenceUrl },
        { date: '2026-09-18', title: 'Rebond de ' + fr(pct(d0918[4], p0918[4]), 1) + ' % après les propos du dirigeant', impact: 'positive', detail: 'Le 18 septembre, le titre gagne ' + fr(pct(d0918[4], p0918[4]), 1) + ' %, à ' + usd(d0918[4]) + '. Le même jour, le directeur général Vlad Tenev décrit, sur CNBC, une stratégie d’usage du trading comme canal d’acquisition vers la gestion de patrimoine (Insider Monkey). Le titre remonte ensuite vers son sommet du 23.', source: 'Barres certifiées et Insider Monkey', sourceUrl: c.evidenceUrl },
        { date: '2026-09-28', title: 'Rothschild maintient une opinion vendeuse, objectif relevé à 85 $', impact: 'negative', detail: 'Le 28 septembre, Rothschild & Co Redburn relève son objectif de 80 à 85 $ tout en gardant une recommandation « vendre » (MT Newswires) — soit environ ' + fr(Math.abs(pct(85, close)), 0) + ' % sous la clôture du 25. Le même flux relaie une note constructive de Morgan Stanley avant le « September Summit » de Robinhood et un dossier de valorisation prudent (TIKR). Le consensus reste partagé.', source: 'Barres certifiées, MT Newswires et TIKR', sourceUrl: c.evidenceUrl }],
      fundamentals: { rows: [
          { metric: 'Revenus nets du deuxième trimestre 2026', value: '1,308 Md$', signal: '+32 % sur un an, communiqué du 29 juillet', signalColor: 'green', _src: 1 },
          { metric: 'Comptes financés', value: '28,4 millions', signal: '+7 % sur un an ; 4,8 millions d’abonnés Gold, 22 Md$ de dépôts nets record', signalColor: 'green', _src: 1 },
          { metric: 'Revenus GAAP sur douze mois', value: fr(G$.rev / 1e9, 2) + ' Md$', signal: 'Douze mois glissants au 30 juin 2026 (XBRL SEC)', signalColor: 'blue', _src: 'gaap' },
          { metric: 'Bénéfice net du deuxième trimestre 2026', value: '573 M$', signal: '+48 % sur un an, dont 129 M$ de gains de déconsolidation ; BPA dilué 0,62 $', signalColor: 'green', _src: 1 },
          { metric: 'Bénéfice net GAAP sur douze mois', value: fr(G$.ni / 1e9, 2) + ' Md$', signal: 'Douze mois glissants au 30 juin 2026 ; marge nette de ' + fr(G$.ni / G$.rev * 100, 0) + ' %', signalColor: 'green', _src: 'gaap' },
          { metric: 'Résultat avant impôts GAAP sur douze mois', value: fr(G$.ebit / 1e9, 2) + ' Md$', signal: 'Proxy du résultat opérationnel (pas de ligne d’exploitation us-gaap pour un courtier), douze mois au 30 juin 2026', signalColor: 'green', _src: 'gaap' },
          { metric: 'EBITDA ajusté (non-GAAP, société)', value: '741 M$', signal: '+35 % sur un an au deuxième trimestre ; mesure de la société, non GAAP', signalColor: 'blue', _src: 1 },
          { metric: 'Liquidités au 30 juin 2026', value: fr(G$.cash / 1e9, 2) + ' Md$', signal: 'Trésorerie et équivalents du groupe (hors cash des clients)', signalColor: 'blue', _src: 'gaap' },
          { metric: 'Billets convertibles au 30 juin 2026', value: fr(G$.debt / 1e9, 2) + ' Md$', signal: 'Seule dette portant intérêt ; convertibles en 12,6 millions d’actions A', signalColor: 'amber', _src: 'gaap', _also: [0] },
          { metric: 'EV/EBITDA GAAP', value: fr(evEbitda, 1) + '×', signal: 'Valeur d’entreprise au close du 2026-09-25 (899,08 M d’actions, convertibles inclus, cash déduit) sur EBITDA GAAP douze mois (résultat avant impôts + amortissements)', signalColor: 'amber', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus Nasdaq à ' + fr(ndaqEb, 1) + '×, Moody’s à ' + fr(mcoEb, 1) + '×, S&P Global à ' + fr(spgiEb, 1) + '× et CME à ' + fr(cmeEb, 1) + '× (statistiques courantes du 24 septembre, non point-in-time) : Robinhood se paie au-dessus des bourses et sous Coinbase (' + fr(coinEb, 1) + '×).', _src: 'market', _peers: ['NDAQ', 'MCO', 'SPGI', 'CME'], _peerField: 'enterpriseToEbitda' },
          { metric: 'EV/revenus GAAP', value: fr(evRev, 1) + '×', signal: 'Valeur d’entreprise au close du 2026-09-25 sur revenus GAAP douze mois au 30 juin 2026', signalColor: 'amber', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus la marge nette de ' + fr(G$.ni / G$.rev * 100, 0) + ' % : un multiple de croissance, pas de rendement.', _src: 'market' },
          { metric: 'P/E GAAP sur douze mois', value: fr(pe, 0) + '×', signal: 'Capitalisation au 2026-09-25 sur bénéfice net GAAP douze mois au 30 juin 2026', signalColor: 'red', source: 'Clôture certifiée et XBRL SEC', comparison: 'Plus de cinquante fois le bénéfice : le marché paie une poursuite de la croissance des volumes.', _src: 'market' },
          { metric: 'Cours / capitaux propres', value: fr(pb, 1) + '×', signal: 'Close du 2026-09-25 sur ' + usd(st.bookValue) + ' de capitaux propres par action', signalColor: 'amber', source: 'Clôture certifiée et snapshot statistique', comparison: 'Onze fois les fonds propres comptables : la valeur est dans la marque et la croissance, pas dans le bilan.', _src: 'market' },
          { metric: 'EV/EBITDA — scénario de re-notation (hypothèse éditoriale)', value: fr(scn.price, 2) + ' $ par action', signal: 'Scénario : multiple ramené à vingt-cinq fois l’EBITDA GAAP douze mois par hypothèse, bilan du 30 juin, soit ' + fr(scn.downside_pct, 0) + ' % sous le close du 2026-09-25', signalColor: 'red', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus Moody’s à ' + fr(mcoEb, 1) + '× et CME à ' + fr(cmeEb, 1) + '× : vingt-cinq fois reste au-dessus des bourses cotées ; ce que coûterait un alignement partiel, pas un objectif.', _src: 'market', _peers: ['MCO', 'CME'], _peerField: 'enterpriseToEbitda' }],
        sourceRefs: [ref(1), ref(0), market('fondamentaux et statistiques')] },
      earnings: { quarters: [],
        beatNote: 'Deuxième trimestre 2026 : revenus nets de 1,308 Md$ (+32 %), bénéfice net de 573 M$ (+48 %, dont 129 M$ de gains de déconsolidation), bénéfice dilué de 0,62 $ (+48 %), EBITDA ajusté non-GAAP de 741 M$ (+35 %). Moteur : les revenus de transaction (+44 %, à 776 M$), portés par les contrats événementiels (156 M$, ×10) et les options (342 M$, +29 %), tandis que la crypto recule de 38 %, à 100 M$. Robinhood ne publie pas de guidance chiffrée de revenus. La date du troisième trimestre, non annoncée par l’émetteur dans les dépôts ouverts, est placée vers le 4 novembre par le calendrier de marché.',
        nextEarnings: 'Date non confirmée par l’émetteur ; le calendrier de marché indique le 4 novembre 2026, au-delà de l’horizon du plan.',
        sourceRefs: [ref(1)] },
      capitalStructure: { sharesOutstanding: '899 082 273 actions au 23 juillet 2026 : 790 630 234 actions A et 108 452 039 actions B (page de garde du 10-Q). L’action B porte dix voix contre une pour l’action A ; les fondateurs et leurs affiliés détiennent la totalité des actions B et gardent le contrôle des votes.',
        sharesAuthorized: 'Actions C autorisées mais non émises ; non décisionnel pour ce dossier.', dilutionRisk: 'low',
        shareHistory: 'La dilution structurelle est modérée et documentée. Les billets convertibles, 2,17 Md$ au 30 juin, sont potentiellement convertibles en 12,6 millions d’actions A, soit environ ' + fr(12.6e6 / 899082273 * 100, 1) + ' % du capital ; aucune action n’a été émise par conversion au trimestre. Des bons de souscription portent sur 8,74 millions d’actions A au prix d’exercice de 26,60 $, échéance le 12 février 2031, exerçables par règlement net — très en dedans de la monnaie au cours actuel, mais leur règlement net limite le nombre d’actions réellement créées, et aucun n’a été exercé au trimestre. L’acquisition de TradePMR a donné lieu à l’émission d’environ 2 millions d’actions A non acquises, valorisées près de 100 M$. Passage au nombre dilué : au deuxième trimestre, 912 millions d’actions diluées en moyenne contre 899 millions de base, l’écart d’environ 1,4 % venant des attributions salariales non acquises et de l’effet des convertibles. En face, un programme de rachat d’actions est actif : 2 743 000 actions A ont été rachetées le 25 juin à 105,71 $. Aucun dépôt de dilution (S-3, 424B, ATM, nouvelle émission) n’apparaît dans la fenêtre de collecte, et le serveur ne relève aucun prospectus de mise sur le marché depuis l’introduction en Bourse de 2021. Le risque de dilution reste faible : rémunération en actions et convertibles d’un côté, rachats de l’autre.',
        warrants: [{ series: 'Bons liés aux convertibles', type: 'Private', strike: 26.6, shares: '8 740 000 actions A', issued: '—', expiration: '2031-02-12', dilutionPct: fr(8.74e6 / 899082273 * 100, 1) + ' %', status: 'ITM', cashless: true, note: 'Réglés en net, très en dedans de la monnaie ; dilution réelle limitée' }],
        atm: { active: false, authorized: 'Aucun programme de mise sur le marché (ATM) relevé', used: 'Sans objet', remaining: 'Sans objet' },
        sourceRefs: [ref(0), ref(2)] },
      filingsReview: { summary: 'Trois dépôts décisionnels ouverts et hachés sur vingt-cinq formulaires screenés. Ils montrent un courtier en forte croissance et rentable, une structure de capital sans dette nette mais à gouvernance verrouillée par les fondateurs, une dilution structurelle modérée compensée par des rachats, et des ventes régulières d’initiés. Aucun dépôt de dilution ni de détresse.',
        filings: docs.map(d => ({ date: d.date, form: d.form, accession: d.accession, finding: d.finding, url: d.url })),
        contrarianRisks: [
          'La valorisation suppose que les volumes de trading et de crypto tiennent : un retour de l’appétit du retail à la moyenne compresserait plusieurs moteurs à la fois.',
          'Le PFOF, cœur des revenus de transaction, reste exposé au risque réglementaire cité dans le 10-K.',
          'La structure à deux classes prive les actionnaires ordinaires du contrôle des votes : les décisions dépendent des fondateurs.',
          'Les 129 M$ de gains de déconsolidation gonflent le bénéfice du trimestre : la qualité récurrente du résultat est un peu plus basse que le chiffre affiché.'] },
      technicals: { rsi14: +tech.rsi14.toFixed(2), macd: +tech.macd.toFixed(2), macdSignal: +tech.macdSignal.toFixed(2), ema20: +tech.ema20.toFixed(2), ema50: +tech.ema50.toFixed(2), ema200: +tech.ema200.toFixed(2),
        ma50Type: 'EMA', ma200Type: 'EMA', ma50Available: true, ma200Available: true, atr14: +tech.atr14.toFixed(2),
        badges: ['Au-dessus des moyennes à vingt, cinquante et deux cents séances', fr(Math.abs(pct(close, entry)), 1) + ' % sous le sommet du 23 septembre', 'ATR de ' + usd(tech.atr14)],
        supports: [lv('s1'), stop, lv('s2')], resistances: [lv('r1'), lv('r2'), entry],
        setupNote: 'Le titre clôture à ' + usd(close) + ', ' + fr(ext20, 1) + ' % au-dessus de sa moyenne à vingt séances et ' + fr(Math.abs(pct(close, entry)), 1) + ' % sous le sommet du 23 septembre, ' + usd(entry) + '. Le repli du 24-25 s’est arrêté vers ' + usd(lv('s1')) + '-' + usd(stop) + '. Avant activation, aucune entrée ; une clôture sous ' + usd(abandon) + ', le plus bas du 16 septembre, abandonne le scénario. Activation sur une clôture au-dessus de $' + entry.toFixed(2) + '. Après activation, stop sous $' + stop.toFixed(2) + ', le plus bas du 25 septembre, soit ' + fr(riskAtr, 2) + ' ATR sous le déclencheur. Supports : ' + usd(lv('s1')) + ', ' + usd(stop) + ' et ' + usd(lv('s2')) + '. Résistances : ' + usd(lv('r1')) + ', ' + usd(lv('r2')) + ' et ' + usd(entry) + ' ; au-dessus du sommet, les objectifs sont des projections de la hauteur du couloir.',
        wyckoff: 'Non utilisé : le profil de volume n’est pas exploité dans ce dossier.',
        sourceRefs: [market('barres quotidiennes et indicateurs recalculés')] },
      options: { callOI: '92 055 contrats', putOI: '54 905 contrats', cpRatio: fr(92055 / 54905, 2), maxPain: usd(116) + ' (échéance du 2 octobre)', ivMean: 'Non exploitable', skew: 'Positionnement légèrement acheteur (plus de calls que de puts)', unusual: 'Chaîne relevée le 28 septembre, échéance courte, non rattachée à la clôture de référence ; positionnement indicatif seulement', sourceRefs: [market('options relevées le 28 septembre')] },
      shortInterest: { siPct: fr(st.shortPercentOfFloat * 100, 2) + ' % du flottant', daysToCover: fr(st.shortRatio, 2) + ' jours (règlement du 15 septembre)', ctb: 'Coût d’emprunt non disponible à la collecte (fournisseur indisponible)', trend: 'Positions vendeuses modérées et en repli : de 6,7 % du flottant fin septembre 2025 à 4,6 % à la mi-septembre 2026 ; ' + fr(st.shortRatio, 1) + ' jour de couverture, aucune thèse de rachat forcé.', squeezeScore: 'Non pertinent', sourceRefs: [market('positions vendeuses FINRA')] },
      insiders: { signal: 'Ventes uniquement, aucun achat : zéro achat et trente-cinq ventes sur quatre-vingt-dix jours. Le directeur général Vlad Tenev a converti puis vendu des titres les 21 et 22 septembre, autour de 125-126 $ (environ 248 000 et 240 000 actions), en plus de ventes du directeur financier Shiv Verma, du directeur juridique Daniel Gallagher, du directeur du courtage Steven Quirk et du cofondateur Baiju Bhatt plus tôt dans le mois. Ces ventes accompagnent souvent des plans programmés ; elles n’en restent pas moins un flux vendeur régulier, sans achat en face.',
        recentTransactions: [],
        sourceRefs: [market('formulaires 4')] },
      macro: { indicators: [{ name: 'Clôture de référence', value: c.REF, signal: usd(close) + ', séance complète' }, { name: 'Rendement cinq séances', value: sgn(ret(5)), signal: 'Descriptif' }, { name: 'Rendement vingt et une séances', value: sgn(ret(21)), signal: 'Descriptif' }],
        regime: 'neutral', impact: 'Robinhood est un pari sur l’appétit du particulier pour le risque : ses trois moteurs — trading, crypto et intérêts — montent ensemble quand les marchés grimpent et que les taux tiennent, et reculent ensemble dans le cas inverse. Une baisse des taux courts pèserait sur les revenus d’intérêt nets ; un refroidissement de la crypto et des options, sur les revenus de transaction. Le titre bat ses pairs sur vingt et une séances (+' + fr(ret(21), 0) + ' %) mais reste très corrélé à Coinbase.' },
      risks: { riskScore: 6, riskProfile: 'High',
        riskSummary: 'Le risque de Robinhood n’est pas le bilan, solide, mais le prix payé pour une croissance cyclique. Le titre se paie plus de cinquante fois le bénéfice et environ quarante fois l’EBITDA, alors que ses profits dépendent de volumes de trading, de crypto et de taux qu’il ne contrôle pas. Les fondateurs gardent le contrôle des votes et les dirigeants vendent régulièrement. À l’inverse, il n’y a ni dette nette, ni dilution imminente, ni tension sur les positions vendeuses.',
        riskCards: [
          { title: 'Valorisation extrême', severity: 'high', icon: 'fa-scale-balanced', points: [fr(pe, 0) + ' fois le bénéfice, ' + fr(evEbitda, 1) + ' fois l’EBITDA.', 'Au-dessus des bourses cotées, sous Coinbase.'], verdict: 'À ce prix, la marge d’erreur est mince : un trimestre de volumes plus faibles se paie cher.' },
          { title: 'Profits cycliques', severity: 'high', icon: 'fa-arrows-spin', points: ['Trading, crypto et intérêts montent et baissent ensemble.', 'Crypto déjà en repli de 38 % au deuxième trimestre.'], verdict: 'Une baisse de l’appétit du retail ou des taux courts toucherait plusieurs moteurs à la fois.' },
          { title: 'Ventes d’initiés et contrôle des fondateurs', severity: 'medium', icon: 'fa-user-tie', points: ['Zéro achat, trente-cinq ventes sur quatre-vingt-dix jours.', 'Action B à dix voix, contrôle des fondateurs.'], verdict: 'Le flux vendeur des dirigeants est régulier ; les actionnaires ordinaires ne pèsent pas sur les votes.' },
          { title: 'Réglementation du PFOF', severity: 'medium', icon: 'fa-file-shield', points: ['Le paiement pour flux d’ordres est le cœur des revenus de transaction.', 'Risque de nouvelle réglementation cité dans le 10-K.'], verdict: 'Un durcissement du PFOF frapperait directement la première source de revenus de transaction.' }],
        pedagogy: 'Le prix d’une action de croissance intègre déjà beaucoup de bonnes nouvelles. À plus de cinquante fois le bénéfice, Robinhood doit continuer de faire croître ses volumes pour justifier son cours ; c’est le sens du scénario de re-notation, qui montre ce que coûterait un simple alignement partiel sur les multiples des bourses cotées. Sur un titre dont l’amplitude journalière moyenne dépasse ' + usd(tech.atr14) + ', les écarts d’ouverture — les gaps — de plusieurs pour cent sont fréquents : le stop peut être franchi d’un coup. Les prochains résultats, publiés vers le 4 novembre, tombent hors de l’horizon du plan. Le slippage, l’écart entre prix voulu et prix obtenu, reste faible sur plus de ' + fr(adv / 1e9, 1) + ' Md$ échangés par séance. Dimensionner la position sur la distance au stop, ' + usd(entry - stop) + ' par action après activation, et traiter le titre comme une valeur de momentum chère, pas comme une valeur de rendement.' },
      tradeIdea: { status: 'watch', statusNote: 'Surveiller. Avant activation : aucune entrée ; une clôture sous ' + usd(abandon) + ' abandonne le scénario. Activation : clôture au-dessus de ' + usd(entry) + ', puis achat à l’ouverture suivante seulement sous ' + usd(cap) + ', ou par ordre limité à ce plafond pendant trois séances, annulé après une clôture sous ' + usd(entry) + ' et jamais laissé actif sur une ouverture sous ' + usd(stop) + '. Après activation : stop sous ' + usd(stop) + '. Le titre clôture sous le déclencheur : le plan n’est pas activé.',
        entry, stop, tp1, tp2,
        stopPct: pct(stop, entry).toFixed(1) + '%', tp1Pct: '+' + pct(tp1, entry).toFixed(1) + '%', tp2Pct: '+' + pct(tp2, entry).toFixed(1) + '%',
        rr: '1:' + rr1.toFixed(2) + ' TP1 / 1:' + rr2.toFixed(2) + ' TP2',
        entryNote: 'Déclencheur sur clôture au-dessus du plus haut du 23 septembre, pas sur un franchissement en séance. Entrée à l’ouverture suivante uniquement sous ' + usd(cap) + ' : au-delà, le R/R vers TP1 tomberait sous 1,5 avec le même stop. Ce plafond est à ' + usd(cap - entry) + ' au-dessus du déclencheur, soit ' + fr(bufAtr, 2) + ' ATR. Mesure : sur les ' + gs.total + ' dernières séances, ' + gs.up + ' ouvertures ont dépassé la clôture de la veille de plus de ' + usd(cap - entry) + ', soit environ ' + fr(blocked, 0) + ' % ; l’écart d’ouverture médian, dans un sens ou dans l’autre, vaut ' + usd(gs.medAbs) + '. Sur la série, ' + bk.n + ' clôtures ont cassé un plus haut de vingt séances : ' + bk.inBand + ' ont fini à moins de ' + fr(bufPct, 2) + ' % au-dessus du niveau cassé, l’écart relatif du plafond, et ' + bk.buyable + ' ont ensuite ouvert sous ce seuil, soit environ ' + fr(bufOpen * 100, 0) + ' % des cassures' + (bufOpen < 0.25 ? ' : l’entrée à l’ouverture est souvent inexécutable.' : ' : l’entrée à l’ouverture reste possible, mais moins d’une fois sur deux.') + ' Plan de repli : si l’ouverture dépasse le plafond, un ordre à cours limité à ' + usd(cap) + ', valable trois séances, garde le même R/R et le même stop. Bornes : il est annulé après toute clôture sous le déclencheur, ' + usd(entry) + ' ; il n’est pas laissé actif à l’ouverture d’une séance qui ouvre sous le stop, ' + usd(stop) + ', ni si le stop est touché avant exécution. Rejouées avec ces bornes sur les ' + rt.miss + ' cassures non achetables à l’ouverture, l’ordre aurait été exécuté ' + rt.back + ' fois' + (rt.stopSame ? ', dont ' + rt.stopSame + ' avec le stop touché la même séance' : ', sans que le stop soit touché la même séance') + (rt.gapUnder ? ' ; ' + rt.gapUnder + ' fois retiré sur une ouverture sous le stop' : ' ; aucun retrait sur ouverture sous le stop') + (rt.fillCloseUnder ? ' ; ' + rt.fillCloseUnder + ' de ces exécutions ont fini la séance sous le niveau cassé.' : ' ; aucune exécution n’a fini la séance sous le niveau cassé.') + ' Objectifs : TP1 à une hauteur de couloir au-dessus du déclencheur, TP2 à une fois et demie ; ce sont des projections d’amplitude, pas des cibles de valorisation. Liquidité : environ ' + fr(adv / 1e9, 1) + ' Md$ échangés par séance, médiane des vingt dernières. Exemple de taille, non personnalisé : avec un budget de perte de 1 000 $, le risque au plafond, ' + usd(cap - stop) + ' par action, donne ' + big + ' actions ; à titre indicatif, ' + sizeExample + ' action' + (sizeExample > 1 ? 's' : '') + ' pour un budget de 100 $.',
        horizon: 'Dix séances après activation',
        thesis: 'Le marché a acheté la diversification des revenus de transaction et la croissance des comptes, puis a marqué une pause sous le sommet du 23 septembre. Une clôture au-dessus de $' + entry.toFixed(2) + ' montrerait que les acheteurs passent outre une valorisation déjà tendue. Avant activation, une clôture sous ' + usd(abandon) + ' abandonne le dossier. Après activation, le stop sous $' + stop.toFixed(2) + ' limite le coût d’une fausse sortie. TP1 à ' + usd(tp1) + ' et TP2 à ' + usd(tp2) + ' sont des projections d’amplitude. Ne pas anticiper le déclencheur, ne pas acheter un écart au-dessus du plafond, et garder à l’esprit que le titre est cher.',
        catalysts: ['Une clôture au-dessus du plus haut du 23 septembre, sur un volume au moins égal à la médiane récente.', 'La tenue des volumes de trading (options, contrats événementiels) et de la crypto, qui font les revenus de transaction.', 'Le niveau des taux courts, qui pilote les revenus d’intérêt nets.'],
        invalidation: ['Avant activation : une clôture sous ' + usd(abandon) + ', bas du couloir, abandonne le scénario.', 'Après activation : une clôture sous ' + usd(stop) + ' invalide le trade.', 'Ouverture au-dessus de ' + usd(cap) + ' après la clôture de déclenchement : pas d’achat à l’ouverture ; seul l’ordre limité à ' + usd(cap) + ' reste valable trois séances.', 'Ordre limité de repli annulé après une clôture sous ' + usd(entry) + ', retiré avant toute ouverture sous le stop à ' + usd(stop) + ' et si le stop est touché avant exécution.', 'Un durcissement réglementaire du PFOF ou un décrochage marqué de la crypto avant activation annule la thèse.'] },
      globalScore: { profile: 'Croissance cyclique du courtage retail, valorisation tendue',
        keyTakeawaysPositive: ['Revenus +32 %, contrats événementiels ×10.', 'Bilan sans dette nette, rachats actifs.', '28,4 millions de comptes financés.'],
        keyTakeawaysNegative: ['Plus de cinquante fois le bénéfice.', 'Profits cycliques (trading, crypto, taux).', 'Ventes d’initiés régulières.'],
        mindsetTip: 'Une croissance record ne rend pas un titre bon marché. La question utile n’est pas « Robinhood grandit-il ? » mais « à quel prix est-ce déjà payé, et que se passe-t-il si les volumes ralentissent ? ».' },
      social: { platforms: [], sourceRefs: [market('sentiment non retenu faute de mesure qualifiée')] },
      disclaimer: 'Document de recherche éducatif. Ni conseil financier, ni signal de trading. Statut surveiller : aucun ordre actif.',
    };
  },
  groups: [
    { name: 'Courtiers en ligne et fintech de détail', order: 1, transmission: 'Mêmes clients particuliers, mêmes revenus de transaction et d’intérêt sur les soldes clients ; co-mouvement le plus fort avec Robinhood.', rows: [
      ['COIN', 'leader', 'Bourse crypto de détail', 'Corrélation la plus forte avec Robinhood depuis janvier ; partage l’exposition au volume de trading crypto et à l’appétit du retail.'],
      ['SOFI', 'direct_peer', 'Néobanque et courtage fintech', 'Même clientèle jeune et mêmes revenus d’intérêt sur les soldes clients.'],
      ['IBKR', 'direct_peer', 'Courtier électronique mondial', 'Concurrent sur les traders actifs ; sensibilité aux commissions et au cash client.'],
      ['SCHW', 'direct_peer', 'Courtier de détail à grande échelle', 'Référence des revenus d’intérêt nets et des soldes de trésorerie clients.'],
      ['TIGR', 'direct_peer', 'Courtier de détail', 'Même bêta retail que Robinhood, avec une taille et une liquidité nettement moindres.']] },
    { name: 'Amont : structure de marché et exécution', order: 1, transmission: 'Robinhood route ses ordres à des teneurs de marché et exécute sur des bourses cotées : leurs volumes et leurs prix d’exécution sont en amont de ses revenus de transaction.', rows: [
      ['VIRT', 'upstream', 'Teneur de marché coté', 'Reçoit une partie du flux d’ordres rémunéré (PFOF) de Robinhood ; maillon amont coté le plus direct de l’exécution.'],
      ['NDAQ', 'upstream', 'Bourse de cotation et d’exécution', 'Bourse de cotation de Robinhood ; capte les volumes d’actions et d’options.'],
      ['ICE', 'upstream', 'Bourses et compensation', 'NYSE et compensation : infrastructure d’exécution et de clearing.'],
      ['CME', 'upstream', 'Bourse de dérivés', 'Futures et options ; exposée au même cycle de volume mais pilotée par les taux — corrélation faible, sert de contrôle.']] },
    { name: 'Second ordre : données et notation de marché', order: 2, transmission: 'Même cycle de marché, sans lien commercial direct : sert à situer les multiples et à isoler ce qui est propre à Robinhood.', rows: [
      ['MCO', 'second_order', 'Notation et données de crédit', 'Multiple d’une franchise de données de marché mûre, référence de valorisation.'],
      ['SPGI', 'second_order', 'Indices, notation et données', 'Franchise d’indices et de données ; multiple de référence du secteur.']] },
    { name: 'Second ordre : banques universelles', order: 2, transmission: 'Concurrence sur le cash des clients et les revenus d’intérêt ; exposées au même cycle de taux.', rows: [
      ['JPM', 'second_order', 'Banque universelle diversifiée', 'Concurrence sur les dépôts et le cash client ; référence de la sensibilité aux taux.'],
      ['BAC', 'second_order', 'Banque de détail', 'Dépôts de détail et revenus d’intérêt, autre bord du même cycle.'],
      ['WFC', 'second_order', 'Banque de détail', 'Franchise de dépôts de détail, contrôle bancaire large.']] },
    { name: 'Contrôles sectoriels', order: 2, transmission: 'Paniers de référence pour isoler ce qui est propre à Robinhood.', rows: [
      ['IAI', 'sector_proxy', 'Panier courtiers-négociants et bourses', 'Panier des courtiers et des bourses : un écart avec ce panier isole ce qui est propre à Robinhood.'],
      ['XLF', 'sector_proxy', 'Panier financier du S&P 500', 'Contrôle financier large ; un mouvement commun n’a rien de spécifique au titre.']] },
  ],
  eventDefault: { leader: 'Aucune publication dans les quatorze jours collectés ; ses volumes crypto restent le signal à suivre', direct_peer: 'Aucune publication dans les quatorze jours collectés ; ses revenus d’intérêt et de commissions peuvent déplacer la lecture du secteur', upstream: 'Aucune publication dans les quatorze jours collectés ; volumes et prix d’exécution à suivre', second_order: 'Aucune publication dans les quatorze jours collectés ; sert de référence de multiple et de cycle', sector_proxy: 'Panier sans publication propre ; exposé aux résultats de ses grandes pondérations' },
  eventRisk: {},
  blastDoc: 2,
  scenarios: c => [
    { scenario: 'bullish', trigger: 'Les volumes de trading et de crypto restent élevés et les taux tiennent, portant les trois moteurs de revenus.', firstOrder: 'Le titre clôture au-dessus du sommet du 23 septembre.', secondOrder: 'Coinbase et le panier de courtiers IAI suivent.', confirmation: 'Une clôture au-dessus de ' + c.usd(c.entry) + ' avec Coinbase en hausse.', contradiction: 'Un dépassement du sommet pendant que Coinbase recule.' },
    { scenario: 'mixed', trigger: 'Pas de catalyseur propre ; les volumes se normalisent sans décrocher.', firstOrder: 'Le titre oscille entre le plus bas du 16 septembre et le sommet du 23.', secondOrder: 'L’écart avec Coinbase reste faible, sans information propre au titre.', confirmation: 'Des clôtures entre ' + c.usd(c.abandon) + ' et ' + c.usd(c.entry) + ' pendant plusieurs séances.', contradiction: 'Une sortie franche d’un côté ou de l’autre.' },
    { scenario: 'bearish', trigger: 'La crypto et les options refroidissent, ou les taux courts baissent, ou le PFOF est durci.', firstOrder: 'Le titre repasse sous le plus bas du 16 septembre.', secondOrder: 'Les courtiers et Coinbase reculent plus que les bourses cotées.', confirmation: 'Une clôture sous ' + c.usd(c.abandon) + ' avec Coinbase en baisse.', contradiction: 'Un repli des pairs que Robinhood ne suit pas.' }],
  contradictions: c => ['Les revenus battent des records, mais la crypto recule de 38 % : la croissance vient désormais des options et des contrats événementiels, plus jeunes et plus volatils.', 'Une corrélation élevée avec Coinbase ne prouve pas un lien commercial : les deux partagent surtout le bêta du retail et de la crypto.', 'Le bilan est sans dette nette, mais le titre se paie onze fois les capitaux propres : la valeur est presque entièrement dans la croissance attendue.'],
  missingData: c => ['Chaîne d’options relevée le 28 septembre, échéance courte, non rattachée à la clôture de référence ; coût d’emprunt, sentiment Reddit et Google Trends indisponibles à la collecte.', 'Répartition détaillée des revenus d’intérêt par source (marge, prêt de titres, trésorerie) non isolée ici.', 'Crypto (BTC, ETH, SOL) écartée des comparables : calendrier 24/7 et absence d’earnings incompatibles avec le contrat de clôture actions ; l’exposition crypto est captée par Coinbase.', 'Seize comparables propres conservés, couvrant cinq groupes économiques ; aucune barre fabriquée.'],
  limitations: ['Options relevées le 28 septembre, non rattachées à la clôture de référence.', 'Résultat avant impôts utilisé comme proxy opérationnel : Robinhood ne publie pas de ligne d’exploitation us-gaap.', 'Coût d’emprunt, sentiment Reddit et Google Trends indisponibles à la collecte.', 'Crypto écartée des comparables (contrat de clôture actions) ; exposition crypto captée par Coinbase.'],
});
