'use strict';
// Dossier Lumentum (LITE) v3 au close du 2026-09-25. Nouvelle fiche (la v1 anglaise du 21 juin, trade clôturé
// à TP2, est archivée). Contenu éditorial et niveaux propres au titre ; calculs, provenance et preuves délégués
// au gabarit tools/lib/analysis-v3-r07.cjs (clôture de référence 2026-09-25, run 20260927).
// Agrégats GAAP lus dans les données XBRL officielles de la SEC (companyfacts) : l'exercice s'est clos le
// 27 juin 2026 et le 10-K a été déposé le 17 août ; à la clôture de référence, les douze mois glissants sont
// donc l'exercice 2026 complet (aucun 10-Q postérieur à la clôture annuelle). Bilan = valeurs au 27 juin 2026.
// Dette = portion courante (1 596,9 M$) + non courante (40,5 M$) des emprunts, essentiellement les obligations
// convertibles restantes. Actions = 89,7 millions d'actions ordinaires en circulation au 14 août (page de garde
// du 10-K) ; s'y ajoute, hors base ordinaire, la préférence convertible Série A détenue par NVIDIA.
const R = require('../../../../tools/lib/analysis-v3-r07.cjs');
const GEN = 'analyses/LITE/_runs/20260927/build-lite.cjs';
const SHARES = 89700000; // page de garde du 10-K FY2026 : « 89.7 million shares of common stock outstanding » au 14 août 2026

R.build({
  ticker: 'LITE', shortName: 'Lumentum', cik: 1633978, generator: GEN, mode: 'archived',
  xbrl: {
    ttm: { rev: ['RevenueFromContractWithCustomerExcludingAssessedTax'], ebit: ['OperatingIncomeLoss'], ni: ['NetIncomeLoss'],
      dep: ['Depreciation'], amort: ['AmortizationOfIntangibleAssets'],
      ocf: ['NetCashProvidedByUsedInOperatingActivities'], capex: ['PaymentsToAcquirePropertyPlantAndEquipment'] },
    instant: { cashEq: ['CashAndCashEquivalentsAtCarryingValue'], sti: ['ShortTermInvestments'],
      ltDebtC: ['LongTermDebtCurrent'], ltDebtNC: ['LongTermDebtNoncurrent'] },
    da: ['dep', 'amort'], debt: ['ltDebtC', 'ltDebtNC'], cash: ['cashEq', 'sti'] },
  scenarioBasis: 'revenue', scenarioMultiple: 15,
  valuationBasis: 'GAAP douze mois au 2026-06-27 (exercice 2026 complet, données XBRL SEC) ; EBITDA GAAP positif = résultat opérationnel + amortissements ; dette = portion courante et non courante des emprunts (obligations convertibles pour l’essentiel) ; trésorerie = liquidités et placements court terme au 27 juin ; 89 700 000 actions ordinaires (page de garde du 10-K) ; le multiple de quinze fois les revenus est une hypothèse éditoriale de normalisation vers le haut de la fourchette des composants optiques, pas un objectif',
  shares: { value: SHARES, doc: 0 },
  levels: { r1: { d: '2026-09-09', c: 2 }, r2: { d: '2026-05-12', c: 2 }, s1: { d: '2026-09-03', c: 3 }, s2: { d: '2026-08-03', c: 3 }, s3: { d: '2026-07-29', c: 3 } },
  supports: ['s1', 's2', 's3'], resistances: ['r1', 'r2'],
  levelsMethod: 'Repères actuels lus sur les barres certifiées : plus hauts et plus bas de balancier de septembre, d’août et de juillet, et plus haut de cinquante-deux semaines du 12 mai.',
  inventory: 27,
  reviewScope: 'Dépôts EDGAR de Lumentum du 25 septembre 2025 au 25 septembre 2026 (hors formulaires 3, 4, 5 et 144), dont le 10-K de l’exercice clos le 27 juin 2026 (déposé le 17 août) et l’annexe 99.1 du 8-K de résultats du quatrième trimestre et de l’exercice 2026 (11 août). Les 8-K de gouvernance et de calendrier, les procurations, les Schedule 13G des gestionnaires passifs et les S-8 des plans salariés sont écartés comme non décisionnels. Deux dépôts décisionnels sont ouverts, hachés et cités ; aucun prospectus de tirage (S-3/424B) ni programme d’émission sur le marché ne figure dans la période. La structure de dette est dominée par des obligations convertibles (échéances 2026, 2028, 2029 et 2032) et une préférence convertible Série A émise à NVIDIA en mars 2026.',
  docs: [
    ['2026-08-17', '10-K', '0001628280-26-057358', 'lite-20260627.htm', 'fy26-10k__lite-20260627.htm',
      'Rapport annuel de l’exercice clos le 27 juin 2026 : 89,7 millions d’actions ordinaires au 14 août ; deux clients finaux au-delà de 10 % du chiffre d’affaires (Client A 26,6 %, Client B 15,0 %), non nommés ; entreprise réorganisée en un seul segment intégré depuis le premier trimestre 2026 ; obligations convertibles 2026, 2028, 2029 et 2032, 1 554,3 M$ de principal, toutes dans la monnaie ; environ 2,9 millions d’actions de préférence convertible Série A vendues à NVIDIA à 695,31 $ pour 2,0 Md$.'],
    ['2026-08-11', '8-K / Exhibit 99.1', '0001628280-26-055726', 'lite_ex991xq4fy26.htm', 'q4-8k-ex991__lite_ex991xq4fy26.htm',
      'Résultats du quatrième trimestre et de l’exercice 2026 : chiffre d’affaires de 1,01 Md$ au trimestre et de 3,01 Md$ sur l’exercice ; marge brute GAAP de 47,4 %, marge opérationnelle GAAP de 27,8 % au trimestre ; perte nette GAAP de 6,9 Md$ sur l’exercice, entièrement due à une perte non monétaire de 7,8 Md$ sur l’extinction de dette liée à l’equitisation des convertibles ; résultat net non-GAAP de 782,3 M$, soit 8,67 $ par action diluée ; prévision du premier trimestre 2027 : 1,225 à 1,275 Md$ de revenus.'],
  ],
  needles: {
    shares: [0, ['As of August 14, 2026, the Registrant had 89.7 million shares of common stock outstanding', 'single, integrated enterprise']],
    customers: [0, ['single end customer which represented 10% or more of our total net revenue', 'Customer A 26.6', 'Customer B 15.0']],
    nvidia: [0, ['2.9 million shares of our Series A Convertible Preferred Stock', 'NVIDIA Corporation', 'sold at a price of $ 695.31 per share for an aggregate purchase price of $ 2.0 billion']],
    notes: [0, ['1,554.3 million in aggregate principal amount of debt outstanding', '0.50% Convertible Senior Notes due 2026']],
    results: [1, ['Net revenue for fiscal year 2026 was $3.01 billion', 'Net revenue of $1.01 billion', 'GAAP operating margin of 27.8%', 'one-time, non-cash loss on debt extinguishment of $7.8 billion', 'Non-GAAP net income for fiscal year 2026 was $782.3 million, or $8.67 per diluted share']],
    guidance: [1, ['Forecasting first quarter of fiscal year 2027 revenue of $1.225 billion to $1.275 billion']],
  },
  sectionDocs: { verdict: [1, 0], business: [0, 1], news: [1], earnings: [1], capitalStructure: [0], filingsReview: [0, 1], risks: [0, 1], globalScore: [1], meta: [1], disclaimer: [1], macro: [1], options: [1], social: [1], header: [0] },
  score: { business: 25, technical: 9, capital: 7, calendar: 0, dilution: -4, risk: 18 },
  peers: true,
  peerFicheSha: {},
  route: (p, { prov, dep, B }) => {
    if (/^news\.[0-2]\./.test(p)) return prov('bars', B, 'Ouverture et clôture lues sur les barres certifiées ; écart d’ouverture = ouverture / clôture de la veille − 1 ; comparaison avec les pairs optiques sur la même séance.', [dep('comparison', '')]);
    return null;
  },
  riskScoreReason: 'Jugement qualitatif sur dix : bilan désendetté et 2,7 Md$ de trésorerie, croissance explosive et adossement stratégique de NVIDIA, mais valorisation à 27,7 fois les revenus contre 8 fois pour les pairs optiques directs, perte GAAP massive d’origine comptable, obligations convertibles toutes dans la monnaie qui diluent, titre volatil et sans point d’entrée propre au cours actuel.',
  compose: c => {
    const { fr, usd, pct, sgn, close, prev, bars, N, tech, st, M, adv, ret, G$, marketCap, ev, scn, entry, stop, tp1, tp2, rr1, rr2, ref, market, docs, raw, peerStat, lv } = c;
    const bar = d => bars.find(b => b[0] === d), prevOf = d => bars[bars.findIndex(b => b[0] === d) - 1];
    const cmp = raw.comparison_bars.data.items[0].results[0].data;
    const dr = (sym, d) => { const b = cmp.find(x => x.symbol === sym).bars, i = b.findIndex(x => x[0] === d); return pct(b[i][4], b[i - 1][4]); };
    const evRev = ev / G$.rev, evEbitda = ev / G$.ebitda, opMargin = G$.ebit / G$.rev * 100, fcfMargin = G$.fcf / G$.rev * 100;
    const hi52 = lv('r2');
    const cohrRev = peerStat('COHR', 'enterpriseToRevenue'), cienRev = peerStat('CIEN', 'enterpriseToRevenue'), cscoRev = peerStat('CSCO', 'enterpriseToRevenue'),
      crdoRev = peerStat('CRDO', 'enterpriseToRevenue'), mrvlRev = peerStat('MRVL', 'enterpriseToRevenue'), fnRev = peerStat('FN', 'enterpriseToRevenue'),
      nvdaRev = peerStat('NVDA', 'enterpriseToRevenue'), avgoRev = peerStat('AVGO', 'enterpriseToRevenue');
    const d0908 = bar('2026-09-08'), p0908 = prevOf('2026-09-08'), d0512 = bar('2026-05-12');
    return {
      meta: { lang: 'fr', dir: 'ltr', level: 'intermediate', tags: ['us', 'semis', 'ai-chain', 'hardware', 'technology'], grade: 'B-', date: '2026-09-25', dateDisplay: '25 septembre 2026', version: 3, status: 'no-trade', assetType: 'stock', levelsCloseDate: c.REF,
        description: 'Lumentum : l’optique qui relie les puces d’IA dans les centres de données, chiffre d’affaires quasi doublé à 3,01 Md$ et adossé à 2,0 Md$ de NVIDIA. Mais 27× les revenus contre 8× pour les pairs optiques, perte GAAP comptable, convertibles dilutives. Close du 25 septembre 2026, aucun ordre.',
        ogDescription: 'Lumentum : revenus +83 % à 3,01 Md$, EBITDA 789 M$, NVIDIA investit 2,0 Md$ ; mais EV/revenus 27,7× contre 8× pour les pairs, perte GAAP comptable ; aucun ordre.',
        lastMcpRefresh: raw.status.captured_at, levelsVerifiedAt: raw.status.captured_at,
        statusHistory: [...(c.archive.meta.statusHistory || []), { at: raw.status.captured_at, from: 'tp2-hit', to: 'no-trade', note: 'refonte v3 du 25 septembre : le plan de juin a atteint son second objectif et est clos ; nouvelle fiche au close du 2026-09-25, titre en consolidation sous son plus haut, valorisation tendue, aucun ordre au cours actuel', close }] },
      header: { ticker: 'LITE', name: 'Lumentum Holdings Inc.', exchange: 'NASDAQ', sector: 'Optique pour centres de données et télécoms : transcepteurs, lasers et composants photoniques', price: close, changePct: pct(close, prev),
        badges: [{ text: 'AUCUN ORDRE — VALORISATION TENDUE', color: 'amber' }, { text: 'Chaîne IA — interconnexion optique', color: 'purple' }],
        metrics: { marketCap: fr(marketCap / 1e9, 1) + ' Md$', volume: fr(bars[N][5] / 1e6, 1) + ' M', evRevenue: fr(evRev, 1) + '×' }, halalStatus: 'unknown' },
      verdict: { score: 55, conviction: 'Moderate', bias: 'Neutral',
        confidence: 'Score éditorial non prédictif. Les chiffres d’entreprise viennent des dépôts SEC et des données XBRL officielles ; les niveaux, du close certifié du 25 septembre.',
        summary: 'Lumentum fabrique les composants optiques — transcepteurs, lasers, modules — qui transportent les données entre les puces des centres de données d’intelligence artificielle. La demande a explosé : le chiffre d’affaires de l’exercice 2026 a atteint 3,01 Md$, contre 1,65 Md$ un an plus tôt, et la société prévoit 1,225 à 1,275 Md$ pour le seul premier trimestre 2027, soit un rythme annuel supérieur à 5 Md$. Le résultat opérationnel GAAP est de 525 M$, l’EBITDA de 789 M$, le résultat net non-GAAP de 782 M$, soit 8,67 $ par action. NVIDIA a investi 2,0 Md$ dans une préférence convertible en mars, un adossement rare. La perte nette GAAP de 6,9 Md$ n’est pas opérationnelle : c’est une charge non monétaire unique de 7,8 Md$ liée à la conversion en actions de la dette convertible. Le problème est le prix : à ' + fr(evRev, 1) + ' fois ses revenus, Lumentum se paie plus de trois fois le multiple de ses pairs optiques directs — Coherent à ' + fr(cohrRev, 1) + '×, Ciena à ' + fr(cienRev, 1) + '×. Le titre clôture à ' + usd(close) + ', en consolidation nerveuse sous son plus haut de ' + usd(hi52) + '. Bon dossier, prix exigeant, aucun point d’entrée propre : aucun ordre au cours actuel.',
        whyBuy: [
          'Croissance rare : chiffre d’affaires de l’exercice 2026 à 3,01 Md$, contre 1,65 Md$ un an plus tôt, et prévision du premier trimestre 2027 de 1,225 à 1,275 Md$, soit un rythme annuel de plus de 5 Md$.',
          'Rentabilité réelle sous la perte comptable : résultat opérationnel GAAP de ' + fr(G$.ebit / 1e6, 0) + ' M$, EBITDA de ' + fr(G$.ebitda / 1e6, 0) + ' M$, résultat net non-GAAP de 782 M$ (8,67 $ par action), flux de trésorerie libre de ' + fr(G$.fcf / 1e6, 0) + ' M$.',
          'Adossement stratégique : NVIDIA a investi 2,0 Md$ dans une préférence convertible Série A en mars 2026, alignant le fournisseur d’optique sur le principal moteur de la demande.',
          'Bilan assaini : la dette est retombée à 1,6 Md$ après conversion des obligations en actions, pour 2,7 Md$ de trésorerie et placements.'],
        whyAvoid: [
          'Valorisation tendue : ' + fr(evRev, 1) + ' fois les revenus des douze derniers mois, contre ' + fr(cohrRev, 1) + '× pour Coherent et ' + fr(cienRev, 1) + '× pour Ciena, les pairs optiques directs — plus de trois fois leur multiple.',
          'Perte nette GAAP de ' + fr(Math.abs(G$.ni) / 1e9, 1) + ' Md$ sur l’exercice : d’origine comptable, mais elle rappelle qu’une part de la croissance a été financée par de la dette convertible désormais transformée en actions.',
          'Dilution : les obligations convertibles restantes, 1 554 M$ de principal, sont toutes dans la monnaie ; le nombre d’actions est déjà passé de 69,8 à 89,7 millions en un an et continuera de monter à mesure des conversions.',
          'Titre volatil et sans setup : ' + usd(close) + ' au milieu d’un couloir de septembre allant de ' + usd(lv('s1')) + ' à ' + usd(lv('r1')) + ', sous le plus haut de ' + usd(hi52) + ' ; aucun point d’entrée à rapport risque-rendement défini au cours actuel.'],
        controlChecklist: [
          { label: 'Historique de cours', status: 'pass', statusLabel: 'Trois cents séances continues', evidence: 'Série quotidienne certifiée au close du 25 septembre.', action: 'Repères et indicateurs recalculés sur cette seule série.' },
          { label: 'Structure du capital', status: 'warn', statusLabel: 'Convertibles dans la monnaie', evidence: '10-K : 89,7 millions d’actions ordinaires ; 1 554 M$ d’obligations convertibles 2026-2032 toutes dans la monnaie ; préférence Série A de 2,0 Md$ détenue par NVIDIA.', action: 'Intégrer la dilution des conversions et la préférence dans le raisonnement de valorisation.' },
          { label: 'Point d’entrée', status: 'warn', statusLabel: 'Consolidation sans setup', evidence: 'Clôture à ' + usd(close) + ', dans un couloir ' + usd(lv('s1')) + '–' + usd(lv('r1')) + ', sous le plus haut de ' + usd(hi52) + '.', action: 'Aucun ordre ; attendre un repli vers la base du couloir ou une cassure confirmée du plus haut.' }] },
      business: { theme: 'Optique pour l’intelligence artificielle : transcepteurs, lasers et modules d’interconnexion',
        overview: '<p>Lumentum fabrique les composants qui transportent la lumière — et donc les données — dans les réseaux. Ses transcepteurs optiques, ses lasers et ses modules relient les serveurs et les puces à l’intérieur des centres de données, ainsi que les villes entre elles dans les réseaux télécoms. Une seconde activité vend des lasers pour l’industrie et la détection tridimensionnelle. Le moteur du moment est l’intelligence artificielle : à mesure que les calculs s’accélèrent, les architectes des centres de données remplacent les liaisons en cuivre par de l’optique, ce qui élargit le marché de Lumentum.</p><p>Sur l’exercice clos le 27 juin 2026, le chiffre d’affaires a atteint 3,01 Md$, en hausse de 83 % sur un an, avec un quatrième trimestre à 1,01 Md$. La marge brute GAAP du trimestre est de 47,4 %, la marge opérationnelle de 27,8 %. Sur l’exercice, le résultat opérationnel GAAP est de 525 M$ et l’EBITDA de 789 M$. La société met en avant un résultat non-GAAP de 782 M$, soit 8,67 $ par action.</p><p>Deux clients finaux dépassent chacun 10 % du chiffre d’affaires — 26,6 % et 15,0 % sur l’exercice 2026 — mais ne sont pas nommés dans le rapport annuel. Depuis le premier trimestre 2026, Lumentum est gérée comme une seule entreprise intégrée, sans segments distincts. NVIDIA a pris une participation en préférence convertible de 2,0 Md$ en mars, signe de l’importance stratégique du fournisseur d’optique dans la chaîne de l’IA.</p>',
        moat: 'L’avantage tient à une intégration verticale rare : Lumentum conçoit et fabrique ses propres lasers, jusqu’aux puces en phosphure d’indium, ce que peu de concurrents savent faire à l’échelle. Cela compte quand la demande de débit explose plus vite que l’offre. Mais la place reste disputée : Coherent est plus gros, Marvell et Broadcom poussent le silicium optique, et les grands acheteurs cherchent à diversifier leurs fournisseurs. La menace de fond est l’optique co-packagée, qui pourrait un jour déplacer la valeur vers les fabricants de commutateurs.',
        segments: [
          { name: 'Cloud et réseaux', revenue: 'Cœur de la croissance', pct: 'Optique pour centres de données IA', description: 'Transcepteurs et modules à haut débit — la montée vers le 1,6 térabit — plus l’optique de commutation et les lasers de forte puissance.' },
          { name: 'Technologies industrielles', revenue: 'Activité plus mûre', pct: 'Lasers industriels et détection 3D', description: 'Lasers pour la fabrication et composants de détection ; croissance plus lente, sensible au cycle industriel.' }],
        sourceRefs: [ref(0), ref(1)],
        coverageMatrix: [
          { facet: 'Cours et historique', status: 'COUVERT', decision: 'Trois cents séances continues, close certifié ; base des repères et des indicateurs.' },
          { facet: 'Résultats et guidance', status: 'COUVERT — PRIMAIRE', decision: 'Annexe 99.1 du 8-K de résultats et 10-K ; prévision du premier trimestre 2027 publiée, date de publication non annoncée.' },
          { facet: 'Capital et dette', status: 'COUVERT — PRIMAIRE', decision: 'Actions, obligations convertibles et préférence NVIDIA lues dans le 10-K ; dette et trésorerie de bilan.' },
          { facet: 'Agrégats GAAP', status: 'COUVERT — XBRL', decision: 'Exercice 2026 complet reconstitué depuis les données XBRL officielles au 27 juin 2026.' },
          { facet: 'Comparables et transmission', status: 'COUVERT — LOCAL', decision: 'Corrélations et bêtas recalculés sur barres certifiées depuis fin septembre 2025.' },
          { facet: 'Clients cotés documentés', status: 'NON APPLICABLE', decision: 'Deux clients finaux au-delà de 10 % du chiffre d’affaires, non nommés dans le 10-K : aucune entité cotée identifiable comme client documenté.' },
          { facet: 'Initiés', status: 'PARTIEL', decision: 'Formulaires relevés ; couverture officielle incomplète, aucun solde net affirmé.' },
          { facet: 'Options', status: 'NON EXPLOITABLE', decision: 'Surface d’options non rattachée à la clôture de référence.' }] },
      news: [
        { date: '2026-08-11', title: 'Chiffre d’affaires annuel de 3,01 Md$ et prévision relevée', impact: 'positive', detail: 'Lumentum publie un exercice 2026 à 3,01 Md$, contre 1,65 Md$ un an plus tôt, un quatrième trimestre à 1,01 Md$, et prévoit 1,225 à 1,275 Md$ pour le premier trimestre 2027. Le marché retient la trajectoire portée par l’optique des centres de données d’IA.', source: 'Lumentum — SEC', sourceUrl: docs[1].url },
        { date: '2026-09-08', title: 'Bond de ' + sgn(pct(d0908[4], p0908[4]), 1) + ' avec le secteur optique', impact: 'positive', detail: 'Ouverture à ' + usd(d0908[1]) + ' contre ' + usd(p0908[4]) + ', clôture à ' + usd(d0908[4]) + ' (' + sgn(pct(d0908[4], p0908[4]), 2) + '). Coherent fait ' + sgn(dr('COHR', '2026-09-08'), 2) + ' et Credo ' + sgn(dr('CRDO', '2026-09-08'), 2) + ' la même séance : la hausse est sectorielle, portée par la demande d’interconnexion optique pour l’IA.', source: 'Barres certifiées', sourceUrl: c.evidenceUrl },
        { date: '2026-09-25', title: 'Clôture à ' + usd(close) + ', consolidation sous le plus haut', impact: 'neutral', detail: 'Le titre referme à ' + usd(close) + ' (' + sgn(pct(close, prev), 2) + '), au milieu d’un couloir de septembre allant de ' + usd(lv('s1')) + ' à ' + usd(lv('r1')) + ', sous le plus haut de cinquante-deux semaines de ' + usd(hi52) + ' inscrit le 12 mai. Après ' + sgn(ret(21), 1) + ' sur vingt et une séances, le mouvement reste nerveux et sans direction nette.', source: 'Barres certifiées', sourceUrl: c.evidenceUrl }],
      fundamentals: { rows: [
          { metric: 'Chiffre d’affaires de l’exercice 2026', value: '3 014 M$', signal: 'Contre 1 645 M$ un an plus tôt, +83 %', signalColor: 'green', _src: 1 },
          { metric: 'Chiffre d’affaires du quatrième trimestre', value: '1 006 M$', signal: '+109 % sur un an : accélération portée par l’IA', signalColor: 'green', _src: 1 },
          { metric: 'Prévision du premier trimestre 2027', value: '1 225 à 1 275 M$', signal: 'Rythme annuel supérieur à 5 Md$', signalColor: 'blue', _src: 1 },
          { metric: 'Marge opérationnelle GAAP du quatrième trimestre', value: '27,8 %', signal: 'Contre une perte un an plus tôt : levier opérationnel réel', signalColor: 'green', _src: 1 },
          { metric: 'Résultat net non-GAAP de l’exercice', value: '782 M$ (8,67 $/action)', signal: 'Rentabilité sous-jacente, hors charge d’extinction de dette', signalColor: 'green', _src: 1 },
          { metric: 'Revenus GAAP sur douze mois', value: fr(G$.rev / 1e6, 0) + ' M$', signal: 'Exercice 2026 complet au 27 juin 2026 (XBRL SEC)', signalColor: 'blue', _src: 'gaap' },
          { metric: 'Résultat opérationnel GAAP sur douze mois', value: fr(G$.ebit / 1e6, 1) + ' M$', signal: 'Marge de ' + fr(opMargin, 1) + ' % : la société est bénéficiaire au niveau opérationnel', signalColor: 'green', _src: 'gaap' },
          { metric: 'Résultat net GAAP sur douze mois', value: fr(G$.ni / 1e9, 2) + ' Md$', signal: 'Négatif à cause d’une charge non monétaire de 7,8 Md$ sur l’extinction des convertibles', signalColor: 'red', _src: 'gaap' },
          { metric: 'EBITDA GAAP sur douze mois', value: fr(G$.ebitda / 1e6, 1) + ' M$', signal: 'Résultat opérationnel plus amortissements : nettement positif', signalColor: 'green', _src: 'gaap' },
          { metric: 'Flux de trésorerie opérationnel sur douze mois', value: fr(G$.ocf / 1e6, 1) + ' M$', signal: 'La trésorerie entre réellement, malgré la perte comptable', signalColor: 'green', _src: 'gaap' },
          { metric: 'Flux de trésorerie libre sur douze mois', value: fr(G$.fcf / 1e6, 1) + ' M$', signal: 'Marge de ' + fr(fcfMargin, 1) + ' % après 451 M$ d’investissements : montée en capacité', signalColor: 'green', _src: 'gaap' },
          { metric: 'Trésorerie et placements au 27 juin 2026', value: fr(G$.cash / 1e6, 0) + ' M$', signal: 'Liquidités et placements court terme', signalColor: 'green', _src: 'gaap' },
          { metric: 'Dette au 27 juin 2026', value: fr(G$.debt / 1e6, 0) + ' M$', signal: 'Portion courante et non courante, obligations convertibles pour l’essentiel', signalColor: 'amber', _src: 'gaap' },
          { metric: 'EV/revenus GAAP', value: fr(evRev, 1) + '×', signal: 'Valeur d’entreprise au close du 2026-09-25, 89,7 millions d’actions, sur revenus GAAP de l’exercice 2026', signalColor: 'red', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus Coherent à ' + fr(cohrRev, 1) + '×, Ciena à ' + fr(cienRev, 1) + '× et Cisco à ' + fr(cscoRev, 1) + '× (statistiques courantes du 25 septembre, non point-in-time) : plus de trois fois le multiple des pairs optiques directs.', _src: 'market', _peers: ['COHR', 'CIEN', 'CSCO'], _peerField: 'enterpriseToRevenue' },
          { metric: 'EV/EBITDA GAAP', value: fr(evEbitda, 0) + '×', signal: 'Sur EBITDA GAAP douze mois au 2026-06-27 : multiple élevé, typique d’une valeur de croissance', signalColor: 'red', source: 'Clôture certifiée et XBRL SEC', _src: 'market' },
          { metric: 'EV/revenus — scénario de normalisation basse (hypothèse éditoriale)', value: fr(scn.price, 0) + ' $ par action', signal: 'Scénario : multiple ramené par hypothèse à quinze fois les revenus GAAP, soit ' + fr(scn.downside_pct, 0) + ' % sous le close du 2026-09-25', signalColor: 'red', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus Credo à ' + fr(crdoRev, 1) + '× et Marvell à ' + fr(mrvlRev, 1) + '× : quinze fois reste au-dessus des pairs optiques et proche des noms de silicium à forte croissance ; ce que coûterait une normalisation du multiple, pas un objectif.', _src: 'market', _peers: ['CRDO', 'MRVL'], _peerField: 'enterpriseToRevenue' }],
        sourceRefs: [ref(1), ref(0), market('fondamentaux et statistiques')] },
      earnings: { quarters: [],
        beatNote: 'Quatrième trimestre et exercice clos le 27 juin 2026 : chiffre d’affaires de 1 006 M$ au trimestre (+109 % sur un an) et de 3 014 M$ sur l’exercice (+83 %). Marge brute GAAP de 47,4 %, marge opérationnelle GAAP de 27,8 % au trimestre. Perte nette GAAP de 6,9 Md$ sur l’exercice, entièrement due à une charge non monétaire de 7,8 Md$ sur l’extinction de dette convertible ; hors cette charge, la société est bénéficiaire, avec un résultat net non-GAAP de 782 M$, soit 8,67 $ par action. L’outlook du premier trimestre 2027 vise 1,225 à 1,275 Md$ de revenus. Prochaine publication : date non annoncée par l’émetteur.',
        nextEarnings: 'Date non annoncée par l’émetteur ; aucune publication dans les quatorze jours du calendrier collecté.',
        sourceRefs: [ref(1)] },
      capitalStructure: { sharesOutstanding: '89,7 millions d’actions ordinaires en circulation au 14 août 2026 (page de garde du 10-K), contre 69,8 millions un an plus tôt ; s’y ajoute, hors base ordinaire, la préférence convertible Série A détenue par NVIDIA (environ 2,9 millions de titres, participant sur une base convertie).',
        sharesAuthorized: '990 millions d’actions ordinaires autorisées : la marge d’émission n’est pas la contrainte ; la dilution vient des conversions.', dilutionRisk: 'moderate',
        shareHistory: 'Base retenue : 89,7 millions d’actions ordinaires, chiffre de la page de garde du 10-K. Le nombre d’actions a augmenté de 69,8 à 89,7 millions en un an, en grande partie par la conversion en actions d’obligations convertibles au quatrième trimestre — l’opération qui a produit la charge comptable non monétaire de 7,8 Md$. Il reste 1 554 M$ de principal d’obligations convertibles (échéances 2026, 2028, 2029 et 2032), toutes dans la monnaie au cours actuel ; leurs conversions continueront de créer des actions. NVIDIA détient par ailleurs une préférence convertible Série A de 2,0 Md$, émise à 695,31 $ le titre en mars 2026, qui participe aux résultats sur une base convertie. Aucun prospectus de tirage ni programme d’émission sur le marché n’apparaît dans la période. Le passage du nombre d’actions de base au nombre dilué ajoute les actions issues des obligations convertibles dans la monnaie et de la préférence Série A convertie ; ce nombre dilué n’est pas figé et s’accroît à chaque conversion.',
        warrants: [],
        atm: { active: false, authorized: 'Aucun programme d’émission sur le marché relevé', used: 'Sans objet', remaining: 'Sans objet' },
        sourceRefs: [ref(0)] },
      filingsReview: { summary: 'Deux dépôts décisionnels ouverts et hachés : le 10-K de l’exercice 2026 et l’annexe de résultats du quatrième trimestre. Ils montrent une croissance explosive portée par l’optique des centres de données, une rentabilité opérationnelle réelle masquée par une charge comptable unique, un bilan désendetté par conversion des convertibles, et un adossement de NVIDIA.',
        filings: docs.map(d => ({ date: d.date, form: d.form, accession: d.accession, finding: d.finding, url: d.url })),
        contrarianRisks: [
          'La valorisation à 27,7 fois les revenus suppose que la croissance actuelle se prolonge des années ; toute décélération de la demande d’optique pour l’IA rapprocherait le multiple de celui des pairs, à 8 fois.',
          'Une part de la croissance a été financée par de la dette convertible transformée en actions : la dilution est réelle et continuera avec les convertibles restantes, toutes dans la monnaie.',
          'Deux clients pèsent chacun plus de 10 % du chiffre d’affaires, 26,6 % et 15,0 % : une commande décalée par l’un d’eux se voit immédiatement dans les résultats.',
          'L’optique co-packagée, qui rapproche l’optique du silicium de commutation, pourrait à terme déplacer une partie de la valeur vers les fabricants de puces et de commutateurs.'] },
      technicals: { rsi14: +tech.rsi14.toFixed(2), macd: +tech.macd.toFixed(2), macdSignal: +tech.macdSignal.toFixed(2), ema20: +tech.ema20.toFixed(2), ema50: +tech.ema50.toFixed(2), ema200: +tech.ema200.toFixed(2),
        ma50Type: 'EMA', ma200Type: 'EMA', ma50Available: true, ma200Available: true, atr14: +tech.atr14.toFixed(2),
        badges: ['En consolidation sous le plus haut de 52 semaines', 'Couloir de septembre large et volatil', 'ATR élevé : mouvements amples'],
        supports: [lv('s1'), lv('s2'), lv('s3')], resistances: [lv('r1'), lv('r2')],
        setupNote: 'Le titre clôture à ' + usd(close) + ', au milieu d’un couloir de septembre allant de ' + usd(lv('s1')) + ' à ' + usd(lv('r1')) + ', sous le plus haut de cinquante-deux semaines de ' + usd(hi52) + ' du 12 mai. RSI à ' + fr(tech.rsi14, 0) + ', ATR de ' + usd(tech.atr14) + ' — la volatilité est forte. Aucun ordre : les niveaux du plan précédent, entrée ' + usd(entry) + ' et stop ' + usd(stop) + ', sont archivés et inactifs. Repères actuels : supports à ' + usd(lv('s1')) + ', ' + usd(lv('s2')) + ' et ' + usd(lv('s3')) + ', résistances à ' + usd(lv('r1')) + ' et ' + usd(lv('r2')) + '.',
        wyckoff: 'Phase de range large après le plus haut de mai ; non utilisée pour fixer les niveaux.',
        sourceRefs: [market('barres quotidiennes et indicateurs recalculés')] },
      options: { callOI: 'Non exploitable', putOI: 'Non exploitable', cpRatio: 'Non exploitable', maxPain: 'Non exploitable', ivMean: 'Non exploitable', skew: 'Surface d’options non rattachée à la clôture de référence', unusual: 'Aucune activité inhabituelle qualifiée', sourceRefs: [market('options')] },
      shortInterest: { siPct: fr(st.shortPercentOfFloat * 100, 2) + ' % du flottant', daysToCover: fr(st.shortRatio, 2) + ' jours, date de règlement non précisée par la source', ctb: 'Coût d’emprunt non disponible à la collecte', trend: 'Positions vendeuses présentes sur un titre volatil ; aucune thèse de rachat forcé retenue.', squeezeScore: 'Non retenu comme thèse', sourceRefs: [market('positions vendeuses')] },
      insiders: { signal: 'Couverture officielle partielle à la collecte : aucun solde net d’initié n’est affirmé. Les mouvements de dirigeants ne sont pas retenus comme signal directionnel pour ce dossier.',
        recentTransactions: [],
        sourceRefs: [market('formulaires d’initiés')] },
      macro: { indicators: [{ name: 'Clôture de référence', value: c.REF, signal: usd(close) + ', séance complète' }, { name: 'Rendement cinq séances', value: sgn(ret(5)), signal: 'Descriptif' }, { name: 'Rendement vingt et une séances', value: sgn(ret(21)), signal: 'Descriptif' }],
        regime: 'risk-on', impact: 'Lumentum suit deux forces : les dépenses d’investissement des géants du cloud dans l’IA, très dynamiques, et l’appétit du marché pour les valeurs de croissance chères. En régime favorable au risque, le secteur optique monte ensemble, comme début septembre. Le titre est peu sensible aux taux depuis son désendettement, mais très sensible au sentiment sur la dépense d’IA : un doute sur le rythme des commandes des hyperscalers pèserait vite.' },
      risks: { riskScore: 6, riskProfile: 'Moderate',
        riskSummary: 'Le risque de Lumentum n’est pas le bilan, désendetté et riche de 2,7 Md$, ni la demande, en pleine expansion. C’est le prix : à 27,7 fois les revenus, le titre est calibré pour une croissance qui ne faiblit pas. S’y ajoutent la dilution des convertibles, la dépendance à deux gros clients et une volatilité forte, sans point d’entrée propre au cours actuel.',
        riskCards: [
          { title: 'Valorisation exigeante', severity: 'high', icon: 'fa-scale-balanced', points: ['EV/revenus de ' + fr(evRev, 1) + '×, contre ' + fr(cohrRev, 1) + '× pour Coherent et ' + fr(cienRev, 1) + '× pour Ciena.', 'EV/EBITDA de ' + fr(evEbitda, 0) + '× : tout repli du multiple fait mal.'], verdict: 'Le prix suppose une croissance durablement élevée ; une simple normalisation du multiple, sans mauvaise nouvelle, suffirait à effacer une large part du cours.' },
          { title: 'Dilution des convertibles', severity: 'medium', icon: 'fa-money-bill-trend-up', points: ['1 554 M$ d’obligations convertibles restantes, toutes dans la monnaie.', 'Actions passées de 69,8 à 89,7 millions en un an ; préférence NVIDIA de 2,0 Md$ en sus.'], verdict: 'Chaque conversion crée des actions ; la charge comptable de 7,8 Md$ mesure l’ampleur de l’opération déjà réalisée, la dilution restante se poursuivra.' },
          { title: 'Concentration client', severity: 'medium', icon: 'fa-building', points: ['Deux clients finaux à 26,6 % et 15,0 % du chiffre d’affaires.', 'Clients non nommés dans le rapport annuel.'], verdict: 'Une commande décalée par l’un des deux se verrait immédiatement dans les résultats et le cours.' },
          { title: 'Perte GAAP d’origine comptable', severity: 'low', icon: 'fa-circle-info', points: ['Perte nette GAAP de 6,9 Md$ sur l’exercice.', 'Entièrement due à la charge non monétaire de 7,8 Md$ sur l’extinction de dette.'], verdict: 'La perte n’est pas opérationnelle : l’activité dégage un résultat opérationnel et un flux de trésorerie libre positifs ; il faut savoir lire au-delà du chiffre GAAP.' }],
        pedagogy: 'Lumentum illustre deux pièges de lecture. D’abord la perte GAAP de 6,9 Md$ : elle effraie, mais elle vient d’une conversion de dette en actions, une écriture comptable sans sortie de trésorerie ; l’entreprise gagne réellement de l’argent au niveau opérationnel. Ensuite le prix : un excellent dossier de croissance peut rester un mauvais achat s’il est déjà payé plus de trois fois le multiple de ses pairs. Côté marché, le titre échange environ ' + fr(adv / 1e6, 0) + ' M$ par séance : la liquidité est bonne, mais l’ATR de ' + usd(tech.atr14) + ' dit des mouvements amples, et un gap après résultats peut sauter un stop. Au milieu d’un large couloir, la taille de position doit rester modeste et progressive, et mieux vaut ne pas courir après le titre.' },
      tradeIdea: { status: 'no-trade', archiveReferenceClose: c.archive.meta.levelsCloseDate,
        statusNote: 'Aucun ordre actif. Les niveaux affichés — entrée ' + usd(entry) + ', stop ' + usd(stop) + ', TP1 ' + usd(tp1) + ', TP2 ' + usd(tp2) + ' — sont ceux, archivés, du plan de juin, désormais clos : le second objectif a été atteint. Ils sont informatifs et non exécutables. Le titre a depuis inscrit un plus haut de ' + usd(hi52) + ' en mai puis reflué ; il clôture à ' + usd(close) + ', au milieu d’un couloir de septembre, sans setup à rapport risque-rendement défini. Aucun nouvel ordre au cours actuel.',
        entry, stop, tp1, tp2,
        stopPct: pct(stop, entry).toFixed(1) + '%', tp1Pct: '+' + pct(tp1, entry).toFixed(1) + '%', tp2Pct: '+' + pct(tp2, entry).toFixed(1) + '%',
        rr: '1:' + rr1.toFixed(2) + ' TP1 / 1:' + rr2.toFixed(2) + ' TP2',
        entryNote: 'Aucune entrée. Les niveaux ci-dessus sont archivés et non exécutables. Conditions de réexamen, sans ordre : un repli vers la base du couloir, autour de ' + usd(lv('s1')) + ', voire vers ' + usd(lv('s2')) + ', qui rétablirait un rapport risque-rendement favorable ; ou une cassure confirmée au-dessus de ' + usd(lv('r1')) + ', puis du plus haut de ' + usd(hi52) + ', validée par le secteur. Liquidité : environ ' + fr(adv / 1e6, 0) + ' M$ échangés par séance ; ATR de ' + usd(tech.atr14) + '.',
        horizon: 'Aucune position au cours actuel',
        thesis: 'Lumentum est un excellent dossier de croissance au mauvais prix d’entrée. La demande d’optique pour l’IA est réelle, la rentabilité opérationnelle aussi, et l’adossement de NVIDIA rare. Mais on ne paie pas ' + fr(evRev, 1) + ' fois les revenus, plus de trois fois le multiple de Coherent ou Ciena, sans marge de sécurité, au milieu d’un couloir volatil. Le plan de juin a atteint son objectif et est clos ; le prochain achat se construira sur un repli vers la base du range ou sur une cassure confirmée, pas au cours actuel.',
        catalysts: ['Un repli vers la base du couloir, autour de ' + usd(lv('s1')) + ', qui rétablirait un point d’entrée à rapport risque-rendement favorable.', 'La publication du premier trimestre 2027, date non annoncée, face à la prévision de 1,225 à 1,275 Md$.', 'Une cassure confirmée au-dessus de ' + usd(lv('r1')) + ' puis du plus haut de ' + usd(hi52) + ', validée par le secteur optique.'],
        invalidation: ['Les niveaux affichés sont archivés et informatifs : aucun transfert vers une exécution actuelle.', 'Un achat au cours actuel, au multiple plein et sans setup, contredit ce dossier.', 'Une décélération de la demande d’optique pour l’IA, ou une perte de part chez un gros client, changerait la thèse de valorisation.'] },
      globalScore: { profile: 'Fournisseur d’optique pour l’IA, en hypercroissance, adossé à NVIDIA, mais cher',
        keyTakeawaysPositive: ['Chiffre d’affaires +83 % à 3,01 Md$ ; prévision annuelle supérieure à 5 Md$.', 'Rentabilité opérationnelle réelle : EBITDA de ' + fr(G$.ebitda / 1e6, 0) + ' M$, flux de trésorerie libre positif.', 'NVIDIA investit 2,0 Md$ ; bilan désendetté, 2,7 Md$ de trésorerie.'],
        keyTakeawaysNegative: ['EV/revenus de ' + fr(evRev, 1) + '×, plus de trois fois le multiple des pairs optiques directs.', 'Dilution continue des obligations convertibles, toutes dans la monnaie.', 'Perte GAAP comptable, concentration client, titre volatil sans setup.'],
        mindsetTip: 'Un dossier de qualité et un bon point d’entrée sont deux choses différentes. La croissance de Lumentum est réelle, mais l’acheter au multiple plein, au milieu d’un range volatil, c’est payer d’avance plusieurs années de perfection. La patience d’attendre un repli ou une cassure confirmée est ici l’avantage.' },
      social: { platforms: [], sourceRefs: [market('sentiment non retenu faute de mesure qualifiée')] },
      disclaimer: 'Document de recherche éducatif. Ni conseil financier, ni signal de trading. Aucun ordre actif : les niveaux affichés sont ceux, archivés, d’un plan clos.',
    };
  },
  groups: [
    { name: 'Référence du segment', order: 1, transmission: 'Le plus gros fabricant coté de composants optiques, celui qui co-évolue le plus avec Lumentum.', rows: [
      ['COHR', 'leader', 'Composants et systèmes optiques, lasers, matériaux', 'Concurrent frontal et plus gros pair de l’optique ; référence de valorisation et corrélation la plus forte parmi les grandes plateformes optiques.']] },
    { name: 'Pairs directs : optique et connectivité', order: 1, transmission: 'Mêmes budgets d’interconnexion des centres de données, arbitrés entre fournisseurs d’optique et de silicium optique.', rows: [
      ['CRDO', 'direct_peer', 'Câbles actifs et DSP optiques', 'Vend la connectivité concurrente et complémentaire des modules ; pair de croissance et de valorisation le plus proche.'],
      ['AAOI', 'direct_peer', 'Transcepteurs optiques pour centres de données', 'Concurrent direct sur les modules pour centres de données ; plus petit et plus volatil.'],
      ['MTSI', 'direct_peer', 'Composants radiofréquence et optiques', 'Fournit lasers et amplificateurs pour modules optiques ; pair et fournisseur partiel.'],
      ['POET', 'direct_peer', 'Intégration photonique sur silicium', 'Pari spéculatif sur l’intégration optique ; montre l’extrême de valorisation du thème.'],
      ['ALAB', 'direct_peer', 'Connectivité pour l’IA', 'Interconnexion des accélérateurs d’IA ; pair de croissance très valorisé, débouché voisin.']] },
    { name: 'Amont : silicium optique et fonderie', order: 2, transmission: 'Le silicium qui pilote les modules optiques et la fonderie qui le grave conditionnent l’offre de Lumentum.', rows: [
      ['MRVL', 'upstream', 'DSP et silicium optique', 'Fournit les processeurs de signal des modules ; à la fois fournisseur et concurrent sur l’électro-optique.'],
      ['AVGO', 'second_order', 'Silicium de commutation et optique', 'Pousse l’optique co-packagée, principale menace de fond, et lit la demande d’interconnexion.'],
      ['TSM', 'upstream', 'Fonderie de semi-conducteurs', 'Grave les puces de silicium optique ; baromètre amont de la capacité disponible.']] },
    { name: 'Aval : systèmes réseau et clients', order: 2, transmission: 'Les fabricants de systèmes et de commutateurs achètent l’optique de Lumentum et en fixent la demande.', rows: [
      ['CIEN', 'downstream', 'Systèmes de transport optique', 'Achète des composants et vend des systèmes ; à la fois client et concurrent sur la cohérence optique.'],
      ['ANET', 'downstream', 'Commutateurs pour centres de données', 'Gros consommateur de transcepteurs optiques ; lecture directe de la demande.'],
      ['CSCO', 'downstream', 'Réseau d’entreprise et optique', 'Client historique de l’optique télécom et de centres de données.'],
      ['FN', 'upstream', 'Assemblage de modules optiques', 'Assemble à façon les modules de la filière optique ; baromètre du volume et des carnets.']] },
    { name: 'Second ordre : demande d’IA et investisseur stratégique', order: 2, transmission: 'La dépense d’investissement en IA détermine le volume d’optique ; NVIDIA en est le moteur et un actionnaire.', rows: [
      ['NVDA', 'second_order', 'Accélérateurs d’IA, actionnaire de préférence', 'Ses plateformes de calcul dictent la demande d’interconnexion optique ; détient par ailleurs une préférence convertible de 2,0 Md$ dans Lumentum.'],
      ['AMZN', 'second_order', 'Cloud AWS, acheteur d’infrastructure', 'Sa dépense de centres de données conditionne le volume d’optique commandé à la filière.']] },
    { name: 'Contrôles sectoriels', order: 2, transmission: 'Paniers de référence pour isoler ce qui est propre à Lumentum.', rows: [
      ['SMH', 'sector_proxy', 'Panier de semi-conducteurs', 'Un écart avec ce panier isole ce qui est propre à Lumentum plutôt qu’au secteur.'],
      ['SOXX', 'sector_proxy', 'Panier de semi-conducteurs équipondéré', 'Second contrôle semi-conducteurs, moins concentré sur les géants.'],
      ['XLK', 'sector_proxy', 'Panier de technologie américaine', 'Contrôle large : un mouvement commun n’a rien de spécifique au titre.']] },
  ],
  eventDefault: { leader: 'Aucune publication dans les quatorze jours collectés ; ses résultats donnent le ton de la filière optique', direct_peer: 'Aucune publication dans les quatorze jours collectés ; ses annonces de produits peuvent déplacer les parts de marché', upstream: 'Aucune publication dans les quatorze jours collectés ; ses tarifs et sa capacité restent à suivre', downstream: 'Aucune publication dans les quatorze jours collectés ; ses carnets de commandes restent le signal à suivre', second_order: 'Aucune publication dans les quatorze jours collectés ; sa dépense d’investissement reste le signal à suivre', sector_proxy: 'Panier sans publication propre ; exposé aux résultats de ses grandes pondérations' },
  eventRisk: {},
  blastDoc: 1,
  scenarios: c => [
    { scenario: 'bullish', trigger: 'La demande d’optique pour l’IA s’accélère et le premier trimestre 2027 dépasse la prévision.', firstOrder: 'Le titre casse le haut du couloir à ' + c.usd(c.lv('r1')) + ' et vise le plus haut de ' + c.usd(c.lv('r2')) + '.', secondOrder: 'Coherent et les pairs optiques suivent ; le multiple de Lumentum reste élevé mais justifié par la croissance.', confirmation: 'Une clôture au-dessus de ' + c.usd(c.lv('r1')) + ' avec Coherent en hausse la même séance.', contradiction: 'Un nouveau plus haut pendant que Coherent et le panier semi-conducteurs reculent.' },
    { scenario: 'mixed', trigger: 'Le secteur consolide sans nouvelle propre au titre.', firstOrder: 'Le titre oscille dans le couloir ' + c.usd(c.lv('s1')) + '–' + c.usd(c.lv('r1')) + '.', secondOrder: 'L’écart de performance avec Coherent reste faible, sans information propre.', confirmation: 'Des clôtures entre ' + c.usd(c.lv('s1')) + ' et ' + c.usd(c.lv('r1')) + ' pendant plusieurs séances.', contradiction: 'Une sortie franche d’un côté ou de l’autre du couloir.' },
    { scenario: 'bearish', trigger: 'La dépense d’IA marque une pause, ou un gros client décale ses commandes, ou le multiple se normalise.', firstOrder: 'Le titre casse ' + c.usd(c.lv('s1')) + ' et revient vers ' + c.usd(c.lv('s2')) + ', voire ' + c.usd(c.lv('s3')) + '.', secondOrder: 'Les valeurs optiques les plus chères reculent plus que les pairs rentables ; la décote paraît méritée.', confirmation: 'Une clôture sous ' + c.usd(c.lv('s1')) + ' avec Coherent en baisse.', contradiction: 'Un repli du secteur que Lumentum ne suit pas.' }],
  contradictions: c => ['La société affiche une perte nette GAAP de plusieurs milliards, mais un résultat opérationnel et un flux de trésorerie libre positifs : la charge d’extinction de dette non monétaire sépare les deux mesures.', 'Une corrélation élevée avec Coherent ne prouve aucun lien commercial : c’est un concurrent, pas un client, et le co-mouvement est sectoriel.', 'NVIDIA est à la fois le moteur de la demande et un actionnaire de préférence, mais n’est pas identifié comme l’un des clients à plus de 10 % nommés dans le rapport annuel.'],
  missingData: c => ['Les deux clients à plus de 10 % du chiffre d’affaires ne sont pas nommés dans le 10-K : aucun client coté n’entre dans les comparables comme client documenté.', 'Date de publication du premier trimestre 2027 non annoncée par l’émetteur.', 'Surface d’options non rattachée à la clôture de référence ; sentiment non retenu ; Reddit et Google Trends indisponibles.', 'Fondamentaux, statistiques et corrélations relevés en instantané le 25 septembre, non reconstitués à la clôture de référence.'],
  limitations: ['Fondamentaux et statistiques du fournisseur relevés en instantané, non point-in-time.', 'Options non exploitables à la clôture de référence.', 'Court terme et cible de consensus décrits qualitativement ; aucun chiffre d’analyste écrit comme gouvernant.', 'La préférence convertible Série A de NVIDIA n’est pas incluse dans la base d’actions ordinaires servant à la capitalisation ; elle est signalée à part dans la structure du capital.'],
});
