'use strict';
// Dossier EQX v3 au close du 2026-09-25 (lot R07). Equinox Gold Corp. : émetteur privé étranger canadien
// (dépôts 40-F/6-K, taxonomie IFRS, ZÉRO tag us-gaap dans companyfacts). Devise de PRÉSENTATION et devise
// fonctionnelle = dollar américain (confirmé dans la note « Presentation currency » du 40-F 2025 et du 6-K du
// 5 août 2026) : aucune conversion. Les agrégats financiers sont donc fournis par cfg.manualFinancials — chaque
// valeur est lue dans l'état financier IFRS du dépôt primaire, liée par accession/formulaire/pointeur de document.
// Base des flux : douze mois glissants au 30 juin 2026, activités POURSUIVIES (le Brésil est reclassé en activités
// abandonnées dans les deux dépôts) = exercice 2025 (40-F) + premier semestre 2026 (6-K) − premier semestre 2025.
// Bilan au 30 juin 2026. Scénario en EV/EBITDA (producteur rentable). Comparables : 13 symboles aurifères/argent
// propres (géométrie ET continuité certifiées au 25/09 ; dix pairs élagués pour barres corrompues : AU, EGO, FNV,
// GFI, GOLD, HMY, KGC, OR, PAAS, WPM). peerFicheSha vide, _peers via comparison_context (peerStat courant).
const R = require('../../../../tools/lib/analysis-v3-r07.cjs');
const GEN = 'analyses/EQX/_runs/20260927/build-eqx.cjs';

// Agrégats IFRS lus dans les dépôts primaires (USD, milliers → dollars). Flux = douze mois glissants au 30/06/2026,
// activités poursuivies. D&D = dotation aux amortissements et à l'épuisement de l'état de résultat (poursuivies),
// même base que le résultat opérationnel, pour un EBITDA cohérent.
const REV_TTM  = 2897063000;  // 1 817 195 + 1 631 389 − 551 521 (milliers $) — 40-F 2025 + S1 2026 − S1 2025
const EBIT_TTM = 1040790000;  // 432 339 + 637 610 − 29 159
const DA_TTM   = 474596000;   // 339 694 + 238 406 − 103 504 (D&D de l'état de résultat, activités poursuivies)
const NI_TTM   = 493836000;   // (18 861) + 405 768 − (106 929) — activités poursuivies
const DEBT     = 583000000;   // prêts et emprunts au 30/06/2026 : 29 054 (courant) + 553 946 (non courant)
const CASH     = 317783000;   // trésorerie et équivalents au 30/06/2026

const ACC_40F = '0001628280-26-022120', ACC_6K = '0001756607-26-000004';

R.build({
  ticker: 'EQX', shortName: 'Equinox Gold', cik: 1756607, generator: GEN, mode: 'breakout',
  xbrl: { ttm: {}, instant: {}, da: ['da'], debt: ['debt'], cash: ['cash'] },
  manualFinancials: { figures: {
    rev:  { value: REV_TTM,  form: '6-K', accn: ACC_6K, start: '2025-07-01', end: '2026-06-30', doc: 1 },
    ebit: { value: EBIT_TTM, form: '6-K', accn: ACC_6K, start: '2025-07-01', end: '2026-06-30', doc: 1 },
    ni:   { value: NI_TTM,   form: '6-K', accn: ACC_6K, start: '2025-07-01', end: '2026-06-30', doc: 1 },
    da:   { value: DA_TTM,   form: '6-K', accn: ACC_6K, start: '2025-07-01', end: '2026-06-30', doc: 1 },
    debt: { value: DEBT,     form: '6-K', accn: ACC_6K, end: '2026-06-30', doc: 1 },
    cash: { value: CASH,     form: '6-K', accn: ACC_6K, end: '2026-06-30', doc: 1 },
  } },
  scenarioBasis: 'ebitda', scenarioMultiple: 7,
  valuationBasis: 'Agrégats IFRS lus dans les dépôts primaires d’Equinox Gold (émetteur privé étranger canadien, 40-F/6-K, devise de présentation et devise fonctionnelle USD confirmée par la note « Presentation currency » ; aucun companyfacts us-gaap). Flux = douze mois glissants au 30 juin 2026, activités poursuivies (Brésil reclassé en activités abandonnées), reconstitués de l’exercice 2025 (40-F) + premier semestre 2026 (6-K du 5 août 2026) − premier semestre 2025 : revenus 2 897,1 M$, résultat opérationnel 1 040,8 M$, amortissements et épuisement 474,6 M$, soit un EBITDA de 1 515,4 M$. Bilan au 30 juin 2026 : trésorerie 317,8 M$ ; prêts et emprunts 583,0 M$. 1 167 459 822 actions ordinaires en circulation à la date du rapport de gestion du deuxième trimestre (après la clôture de l’acquisition d’Orla le 31 juillet 2026). Multiple de sept fois l’EBITDA = hypothèse éditoriale (niveau de Newmont, milieu de la fourchette sectorielle). Réserve : les actions incluent Orla alors que l’EBITDA douze mois est antérieur à cette acquisition ; sur base pro forma incluant Orla, le multiple serait inférieur.',
  levels: { trigger: { d: '2026-09-08', c: 2 }, stop: { d: '2026-09-18', c: 3 }, abandon: { d: '2026-09-16', c: 3 }, t1: { d: '2026-08-25', c: 2 }, s1: { d: '2026-09-24', c: 3 }, s2: { d: '2026-09-16', c: 3 }, r1: { d: '2026-09-18', c: 2 }, r2: { d: '2026-09-09', c: 2 } },
  supports: ['s1', 'stop', 's2'], resistances: ['r1', 'r2', 'trigger'],
  targets: ({ lv, entry }) => { const tp1 = lv('t1'); const range = tp1 - entry; return { tp1, tp2: tp1 + range, range }; },
  levelsMethod: 'Déclencheur = plus haut du 8 septembre, sommet de la zone de résistance testée en séance début et fin septembre ; stop = plus bas du 18 septembre, dans le couloir de consolidation ; plancher d’abandon = plus bas du 16 septembre, bas du couloir ; TP1 = plus haut du 25 août (sommet du rebond d’août) ; TP2 = TP1 + hauteur (TP1 − déclencheur) ; plafond d’achat = (TP1 + 1,5 × stop) / 2,5 arrondi au cent inférieur, ajusté pour garder un R/R ≥ 1,5 vers TP1 ; pourcentages depuis l’entrée ; R/R = gain / risque.',
  inventory: 53,
  reviewScope: 'Dépôts EDGAR d’Equinox Gold Corp. (CIK 1756607) revus jusqu’au 25 septembre 2026 : le 40-F de l’exercice clos le 31 décembre 2025 (états financiers consolidés audités IFRS et rapport de gestion annuel), le 6-K du 5 août 2026 (états financiers intermédiaires condensés et rapport de gestion des trois et six mois clos le 30 juin 2026 et 2025), et le 6-K parallèle du 5 août 2026 (communiqué). Les opérations capitalistiques marquantes — fusion avec Calibre Mining (17 juin 2025, toute en actions), acquisition d’Orla Mining (clôturée le 31 juillet 2026) et cession des actifs brésiliens (activités abandonnées) — sont lues dans les notes de ces dépôts. Les Schedule 13D/13G des grands actionnaires et les formulaires de gouvernance sont écartés du décompte décisionnel.',
  docs: [
    ['2026-03-31', '40-F', ACC_40F, 'eqx-20251231.htm', '40F_financials.htm',
      'États financiers consolidés audités de l’exercice clos le 31 décembre 2025 (IFRS, USD) : revenus des activités poursuivies de 1 817,2 M$ (contre 912,8 M$ en 2024), résultat opérationnel de 432,3 M$, amortissements et épuisement de 339,7 M$, perte nette des activités poursuivies de 18,9 M$, prêts et emprunts totaux de 1 554,7 M$ et trésorerie de 407,4 M$ au 31 décembre 2025 ; 785 632 450 actions en circulation. Notes sur la fusion Calibre (302,8 M d’actions émises), les billets convertibles (172,5 M$ à 6,30 $, échéance 2028 ; C$49,7 M à C$12,14, échéance 2030) et les bons de souscription (4 271 060 à C$10,43).', 1756607],
    ['2026-08-05', '6-K', ACC_6K, 'eqx-20260630financialstate.htm', 'Q2_financials.htm',
      'États financiers intermédiaires condensés non audités des trois et six mois clos le 30 juin 2026 et 2025 (IFRS, USD) : revenus du semestre des activités poursuivies de 1 631,4 M$ (contre 551,5 M$), amortissements et épuisement de 238,4 M$, résultat opérationnel de 637,6 M$, résultat net des activités poursuivies de 405,8 M$ ; au 30 juin 2026, trésorerie de 317,8 M$ et prêts et emprunts de 583,0 M$ (courant 29,1 M$, non courant 553,9 M$), après remboursements liés à la cession du Brésil.', 1756607],
    ['2026-08-05', '6-K', ACC_6K, 'eqx-20260630mda.htm', 'Q2_mda.htm',
      'Rapport de gestion du deuxième trimestre 2026 : mines en exploitation au 30 juin 2026 — Greenstone et Valentine (Canada), Mesquite (États-Unis), La Libertad et El Limon (Nicaragua) ; événement postérieur — clôture de l’acquisition d’Orla Mining le 31 juillet 2026, portant le nombre d’actions ordinaires en circulation à 1 167 459 822 à la date du rapport.', 1756607],
    ['2026-03-31', '40-F', ACC_40F, 'eqx-20251231mda.htm', '40F_mda.htm',
      'Rapport de gestion annuel 2025 : commentaire sur la production aurifère, les coûts tout compris (AISC), la fusion avec Calibre, l’offre au marché de 100 M$ (échue en décembre 2024) et le programme de rachat d’actions dans le cours normal.', 1756607],
    ['2026-03-31', '40-F', ACC_40F, 'eqx-20251231_d2.htm', '40F_cover.htm',
      'Page de garde du 40-F de l’exercice 2025 : elle atteste de 785 632 450 actions ordinaires en circulation au 31 décembre 2025, avant l’acquisition d’Orla, et sert de point de référence pour mesurer la dilution intervenue depuis, le nombre d’actions ayant été porté à 1 167 459 822 à la date du rapport de gestion du deuxième trimestre 2026.', 1756607],
  ],
  needles: {
    rev: [1, ['1,631,389', '551,521']],
    ebit: [1, ['637,610', '29,159']],
    ni: [1, ['405,768', '106,929']],
    da: [1, ['238,406', '103,504']],
    bal: [1, ['317,783', '583,000', '29,054', '553,946']],
    shares: [2, ['1,167,459,822']],
    annual: [0, ['1,817,195', '432,339', '339,694', '18,861', '1,554,680', '407,355', '785,632,450']],
    dilution: [0, ['172.5', '6.30', '4,271,060', '10.43', '302.8', '12.14']],
  },
  sectionDocs: { verdict: [1, 0, 2], business: [2, 0, 1], news: [1, 2], earnings: [1, 0], capitalStructure: [2, 0, 3], filingsReview: [0, 1, 2, 3, 4], risks: [0, 1, 2], globalScore: [1], meta: [1], disclaimer: [1], macro: [1], options: [1], social: [1], header: [1], shortInterest: [1], insiders: [1] },
  score: { business: 32, technical: 5, capital: 6, calendar: 0, dilution: -8, risk: 22 },
  peers: true,
  peerFicheSha: {},
  shares: { value: 1167459822, doc: 2 },
  route: (p, { prov, dep, B, TXP }) => {
    if (/^news\.[23]\./.test(p)) return prov('bars', B, 'Ouverture et clôture lues sur les barres certifiées ; variations calculées de clôture à clôture ; comparaison avec les pairs sur la même séance.', [dep('comparison', '')]);
    if (p.startsWith('insiders.')) return prov('insiders', TXP == null ? '' : TXP, 'Statistiques d’initiés du snapshot (achats, ventes, activité nette) ; couverture officielle partielle pour un émetteur étranger canadien qui déclare d’abord au Canada (SEDI).', [dep('sec', '')]);
    return null;
  },
  riskScoreReason: 'Jugement qualitatif sur dix : producteur d’or rentable et désendetté (dette nette proche de 0,2 fois l’EBITDA après la cession du Brésil), mais à bêta 2,5 sur le prix de l’or, en pleine intégration de deux fusions (Calibre en 2025, Orla en 2026) et de la montée en puissance de Greenstone, le nombre d’actions ayant plus que doublé en quinze mois ; valorisation de milieu de peloton, sans instrument de financement toxique.',
  compose: c => {
    const { fr, usd, pct, sgn, close, prev, bars, N, tech, st, M, adv, ret, G$, marketCap, ev, scn, lv, entry, stop, tp1, tp2, abandon, cap, rr1, rr2, riskAtr, sizeExample, ref, market, docs, raw, peerStat } = c;
    const gs = c.gapStats(cap - entry), bufAtr = (cap - entry) / tech.atr14, blocked = gs.up / gs.total * 100;
    const bufPct = (cap / entry - 1) * 100, bk = c.breakoutStats(bufPct), rt = c.retestStats(bufPct, (1 - stop / entry) * 100);
    const cmp = raw.comparison_bars.data.items[0].results[0].data;
    const dr = (sym, d) => { const b = cmp.find(x => x.symbol === sym).bars, i = b.findIndex(x => x[0] === d); return pct(b[i][4], b[i - 1][4]); };
    const bar = d => bars.find(b => b[0] === d);
    const d0925 = bar('2026-09-25'), d0924 = bar('2026-09-24'), d0908 = bar('2026-09-08');
    const win = bars.slice(Math.max(0, N - 251), N + 1); let hi = -1, lo = 1e9, hiD, loD;
    for (const b of win) { if (b[2] > hi) { hi = b[2]; hiD = b[0]; } if (b[3] < lo) { lo = b[3]; loD = b[0]; } }
    const run = close / lo;
    const y0 = bars.find(b => b[0] >= '2026-01-02'), ytd = pct(close, y0[4]);
    const evRev = ev / G$.rev, evEbitda = ev / G$.ebitda, opMargin = G$.ebit / G$.rev * 100, pe = marketCap / G$.ni;
    const netDebt = G$.debt - G$.cash, ndToEbitda = netDebt / G$.ebitda;
    const nemEv = peerStat('NEM'), aemEv = peerStat('AEM'), agiEv = peerStat('AGI'), btgEv = peerStat('BTG'), iagEv = peerStat('IAG'), rgldEv = peerStat('RGLD');
    const ext20 = pct(close, tech.ema20), ext50 = pct(close, tech.ema50), ext200 = pct(close, tech.ema200);
    const big = Math.floor(1000 / (cap - stop));
    return {
      meta: { lang: 'fr', dir: 'ltr', level: 'intermediate', tags: ['us', 'gold', 'mining', 'commodity', 'trade-idea'], grade: 'B', date: '2026-09-25', dateDisplay: '25 septembre 2026', version: 3, status: 'watch', assetType: 'stock', levelsCloseDate: c.REF,
        description: 'Equinox Gold : producteur d’or intermédiaire (émetteur étranger, IFRS, USD). Revenus douze mois de 2,9 Md$, marge de 36 %, dette nette quasi nulle après la cession du Brésil, mais bêta 2,5 sur l’or et capital doublé en quinze mois. Close du 25 septembre 2026, statut surveiller.',
        ogDescription: 'Equinox Gold (EQX) : revenus du S1 2026 de 1,63 Md$ contre 0,55 Md$, dette ramenée à 583 M$, EV/EBITDA d’environ 9× ; titre à 11,92 $, sous son sommet du 8 septembre. Niveaux à surveiller.',
        lastMcpRefresh: raw.status.captured_at, levelsVerifiedAt: raw.status.captured_at,
        statusHistory: [...(c.archive.meta.statusHistory || []), { at: raw.status.captured_at, from: c.archive.meta.status || 'wait', to: 'watch', note: 'refonte v3 harnachée du 25 septembre : émetteur étranger IFRS (40-F/6-K, USD) via agrégats de dépôt primaire, base douze mois glissants au 30 juin 2026 (activités poursuivies), comparables aurifères propres à treize symboles', close }] },
      header: { ticker: 'EQX', name: 'Equinox Gold Corp.', exchange: 'NYSE American', sector: 'Or — producteur intermédiaire (Amériques)', price: close, changePct: pct(close, prev),
        badges: [{ text: 'SURVEILLER — ACTIVATION AU-DESSUS DU SOMMET DU 8 SEPTEMBRE', color: 'blue' }, { text: 'Or — producteur intermédiaire', color: 'purple' }],
        metrics: { marketCap: fr(marketCap / 1e9, 1) + ' Md$', volume: fr(bars[N][5] / 1e6, 2) + ' M', evEbitda: fr(evEbitda, 1) + '×' }, halalStatus: 'unknown' },
      verdict: { score: 57, conviction: 'Moderate', bias: 'Neutral',
        confidence: 'Score éditorial non prédictif. Les chiffres d’entreprise sont lus dans les états financiers IFRS des dépôts primaires (40-F 2025 et 6-K du 5 août 2026) ; les niveaux, sur le close certifié du 25 septembre.',
        summary: 'Equinox Gold produit de l’or dans les Amériques — Greenstone et Valentine au Canada, Mesquite aux États-Unis, La Libertad et El Limon au Nicaragua — après avoir fusionné avec Calibre en 2025, acquis Orla en juillet 2026 et cédé ses actifs brésiliens. Le semestre est solide : au premier semestre 2026, les revenus des activités poursuivies atteignent ' + fr(1631.4, 1) + ' M$ contre ' + fr(551.5, 1) + ' M$ un an plus tôt, pour une marge opérationnelle de ' + fr(opMargin, 0) + ' % sur douze mois. Surtout, la cession du Brésil a ramené la dette de ' + fr(1554.7, 1) + ' M$ fin 2025 à ' + fr(583.0, 1) + ' M$ : la dette nette ne pèse plus que ' + fr(ndToEbitda, 2) + ' fois l’EBITDA. Au close du 25 septembre, ' + usd(close) + ' (' + sgn(pct(close, prev), 1) + '), le titre capitalise environ ' + fr(marketCap / 1e9, 0) + ' Md$, soit ' + fr(evEbitda, 1) + ' fois son EBITDA douze mois — au niveau des intermédiaires de qualité (Alamos ' + fr(agiEv, 1) + '×), au-dessus de Newmont (' + fr(nemEv, 1) + '×) mais loin des décotes de B2Gold (' + fr(btgEv, 1) + '×) et IAMGOLD (' + fr(iagEv, 1) + '×). Le vrai risque n’est pas le prix : c’est un bêta de ' + fr(st.beta, 1) + ' sur l’or, l’intégration de deux fusions et une montée en puissance de Greenstone, le tout financé par un nombre d’actions plus que doublé en quinze mois. Signal utile : une clôture au-dessus de ' + usd(entry) + '. Statut surveiller : le titre reste sous ce niveau, ' + fr(Math.abs(pct(close, entry)), 1) + ' % en dessous.',
        whyBuy: [
          'Rentabilité réelle : marge opérationnelle de ' + fr(opMargin, 0) + ' % et résultat opérationnel de ' + fr(G$.ebit / 1e6, 0) + ' M$ sur douze mois, portés par un prix de l’or élevé.',
          'Bilan assaini : dette ramenée de ' + fr(1554.7, 1) + ' M$ à ' + fr(583.0, 1) + ' M$ après la cession du Brésil ; dette nette de seulement ' + fr(ndToEbitda, 2) + ' fois l’EBITDA.',
          'Valorisation de milieu de peloton (' + fr(evEbitda, 1) + '× l’EBITDA), pas une prime : au niveau d’Alamos (' + fr(agiEv, 1) + '×), sous Agnico (' + fr(aemEv, 1) + '×) et les redevances Royal Gold (' + fr(rgldEv, 1) + '×) ; sur base pro forma incluant Orla, le multiple serait plus bas encore.',
          'Portefeuille recentré sur les Amériques après trois opérations (Calibre, Orla, sortie du Brésil), avec Greenstone en montée en puissance.'],
        whyAvoid: [
          'Bêta de ' + fr(st.beta, 1) + ' sur le prix de l’or : le titre amplifie les mouvements du métal dans les deux sens ; une correction de l’or ferait plus mal qu’à la moyenne du secteur.',
          'Dilution massive : le nombre d’actions est passé d’environ ' + fr(477.7, 0) + ' M (moyenne du premier semestre 2025) à ' + fr(785.6, 0) + ' M fin 2025, puis à ' + fr(1167.5, 0) + ' M après Orla — plus du double en quinze mois.',
          'Risque d’exécution : intégrer Calibre puis Orla et faire monter Greenstone en régime en même temps laisse peu de marge à l’erreur opérationnelle.',
          'Court terme faible : le titre clôture ' + fr(Math.abs(ext20), 1) + ' % sous sa moyenne à vingt séances, dans un repli de ' + fr(Math.abs(ret(21)), 0) + ' % sur un mois ; aucune entrée avant reprise du déclencheur.'],
        controlChecklist: [
          { label: 'Historique de cours', status: 'pass', statusLabel: 'Trois cents séances continues', evidence: 'Série quotidienne certifiée au close du 25 septembre.', action: 'Niveaux et indicateurs recalculés sur cette seule série.' },
          { label: 'Comptes', status: 'warn', statusLabel: 'Émetteur étranger, IFRS', evidence: 'Equinox dépose 40-F/6-K, pas de 10-K/10-Q ; aucun agrégat us-gaap XBRL. Chiffres lus dans les états IFRS (USD confirmé), base douze mois glissants au 30 juin 2026, activités poursuivies.', action: 'Lire les agrégats comme des reconstitutions de dépôt, non comme un flux XBRL standardisé.' },
          { label: 'Périmètre', status: 'warn', statusLabel: 'Orla hors EBITDA douze mois', evidence: 'Les actions incluent l’acquisition d’Orla (clôturée le 31 juillet 2026) ; l’EBITDA douze mois lui est antérieur. Le multiple affiché est donc conservateur : pro forma, il serait plus bas.', action: 'Traiter ' + fr(evEbitda, 1) + '× comme un plafond, non comme la valorisation pro forma.' }] },
      business: { theme: 'Production d’or intermédiaire dans les Amériques',
        overview: '<p>Equinox Gold exploite des mines d’or dans les Amériques. Au 30 juin 2026, ses mines en production étaient Greenstone et Valentine au Canada, Mesquite aux États-Unis, et La Libertad et El Limon au Nicaragua. La société est un émetteur privé étranger canadien : elle publie ses comptes en normes IFRS et en dollars américains, via des formulaires 40-F annuels et 6-K intermédiaires, et non les 10-K/10-Q américains.</p><p>Le profil a changé de dimension en quinze mois. La fusion toute en actions avec Calibre Mining, en juin 2025, a ajouté les actifs du Nicaragua et du Nevada et émis ' + fr(302.8, 1) + ' millions d’actions. L’acquisition d’Orla Mining, clôturée le 31 juillet 2026, a encore porté le nombre d’actions à ' + fr(1167.5, 1) + ' millions. En parallèle, Equinox a vendu ses actifs brésiliens, désormais présentés en activités abandonnées : les chiffres d’exploitation ci-dessous portent sur les seules activités poursuivies.</p><p>Le résultat est un producteur recentré et rentable : ' + fr(G$.rev / 1e9, 2) + ' Md$ de revenus sur douze mois, une marge opérationnelle de ' + fr(opMargin, 0) + ' %, et une dette ramenée à ' + fr(G$.debt / 1e6, 0) + ' M$. Le revers est la sensibilité : le résultat d’un mineur dépend d’abord du prix de l’or et de ses coûts tout compris, deux variables qu’il ne contrôle pas.</p>',
        moat: 'Un producteur d’or n’a pas de véritable rempart concurrentiel : il vend une matière première au prix mondial. Son avantage tient à la qualité de ses gisements, à ses coûts tout compris et à la discipline d’allocation du capital. Greenstone, mine à long horizon et à coûts compétitifs, est la pièce maîtresse ; l’enjeu est de la faire monter en régime tout en digérant Calibre et Orla sans dérive de coûts.',
        segments: [
          { name: 'Mines en production (Amériques)', revenue: '1 631,4 M$ au premier semestre 2026', pct: 'Totalité des revenus poursuivis', description: 'Greenstone et Valentine (Canada), Mesquite (États-Unis), La Libertad et El Limon (Nicaragua) ; production vendue au prix spot de l’or.' },
          { name: 'Projets et intégration', revenue: 'Non générateur de revenus courants', pct: 'Investissement', description: 'Montée en puissance de Greenstone, intégration de Calibre et d’Orla (Camino Rojo, Musselwhite), après la sortie du Brésil.' }],
        sourceRefs: [ref(2), ref(0), ref(1)],
        coverageMatrix: [
          { facet: 'Cours et historique', status: 'COUVERT', decision: 'Trois cents séances continues, close certifié ; base des niveaux et des indicateurs.' },
          { facet: 'Comptes et agrégats', status: 'COUVERT — PRIMAIRE IFRS', decision: 'Agrégats lus dans le 40-F 2025 et le 6-K du 5 août 2026 ; douze mois glissants au 30 juin 2026, activités poursuivies ; aucun companyfacts us-gaap n’existe pour cet émetteur.' },
          { facet: 'Capital et dette', status: 'COUVERT — PRIMAIRE', decision: 'Fusion Calibre (302,8 M d’actions), acquisition Orla (actions portées à 1 167,5 M), billets convertibles et bons de souscription lus dans les notes ; dette ramenée à 583,0 M$.' },
          { facet: 'Comparables et transmission', status: 'COUVERT — LOCAL', decision: 'Corrélations recalculées sur barres certifiées ; treize comparables aurifères/argent propres, dix pairs élagués pour barres corrompues.' },
          { facet: 'Position vendeuse', status: 'PARTIEL — SNAPSHOT', decision: 'Ratio de couverture d’environ ' + fr(st.shortRatio, 2) + ' jours ; pourcentage du flottant non renseigné par le snapshot ; aucune thèse de rachat forcé.' },
          { facet: 'Coût d’emprunt et dark pool', status: 'NON EXPLOITABLE', decision: 'Coût d’emprunt indisponible à la collecte (fournisseur en échec) ; aucun flux directionnel inféré.' },
          { facet: 'Options et sentiment social', status: 'NON EXPLOITABLE', decision: 'Chaîne d’options non retenue dans ce dossier ; ni Reddit ni Google Trends servis pour ce titre.' }] },
      news: [
        { date: '2026-08-05', title: 'Résultats du premier semestre 2026 : revenus de ' + fr(1631.4, 1) + ' M$ et désendettement', impact: 'positive', detail: 'Le 6-K du 5 août présente des revenus semestriels des activités poursuivies de ' + fr(1631.4, 1) + ' M$ (contre ' + fr(551.5, 1) + ' M$ un an plus tôt) et un résultat opérationnel de ' + fr(637.6, 1) + ' M$. La cession du Brésil a permis de ramener les prêts et emprunts de ' + fr(1554.7, 1) + ' M$ fin 2025 à ' + fr(583.0, 1) + ' M$ au 30 juin : le bilan est nettement assaini.', source: 'Equinox Gold — SEC', sourceUrl: docs[1].url },
        { date: '2026-07-31', title: 'Clôture de l’acquisition d’Orla Mining : actions portées à ' + fr(1167.5, 1) + ' millions', impact: 'neutral', detail: 'Le rapport de gestion du deuxième trimestre indique, en événement postérieur, la clôture de l’acquisition d’Orla Mining le 31 juillet 2026, portant le nombre d’actions ordinaires en circulation à ' + fr(1167.5, 1) + ' millions. L’opération ajoute des actifs (Camino Rojo, Musselwhite) mais dilue fortement, après la fusion Calibre de 2025.', source: 'Equinox Gold — SEC', sourceUrl: docs[2].url },
        { date: '2026-09-08', title: 'Rejet sur la résistance de ' + usd(entry) + ', puis repli', impact: 'neutral', detail: 'Le titre bute sur ' + usd(entry) + ' le 8 septembre (clôture ' + usd(d0908[4]) + '), sommet de la zone testée à plusieurs reprises, avant de refluer. Le panier des mineurs d’or GDX fait ' + sgn(dr('GDX', '2026-09-08'), 2) + ' et Newmont ' + sgn(dr('NEM', '2026-09-08'), 2) + ' la même séance : le mouvement accompagne le secteur.', source: 'Barres certifiées', sourceUrl: c.evidenceUrl },
        { date: '2026-09-25', title: 'Clôture à ' + usd(close) + ' (' + sgn(pct(close, prev), 1) + '), sous le déclencheur', impact: 'neutral', detail: 'Après un plus bas à ' + usd(d0924[3]) + ' le 24, le titre ouvre à ' + usd(d0925[1]) + ' et clôture à ' + usd(close) + ' (' + sgn(pct(close, prev), 2) + '), toujours sous son sommet du 8 septembre. GDX fait ' + sgn(dr('GDX', '2026-09-25'), 2) + ' et Alamos ' + sgn(dr('AGI', '2026-09-25'), 2) + ' la même séance ; le repli suit le secteur.', source: 'Barres certifiées', sourceUrl: c.evidenceUrl }],
      fundamentals: { rows: [
          { metric: 'Revenus du premier semestre 2026 (activités poursuivies)', value: '1 631,4 M$', signal: '+196 % sur un an (551,5 M$ au premier semestre 2025)', signalColor: 'green', _src: 1 },
          { metric: 'Revenus de l’exercice 2025 (activités poursuivies)', value: '1 817,2 M$', signal: 'Contre 912,8 M$ en 2024 ; effet de la fusion Calibre et du prix de l’or', signalColor: 'green', _src: 0 },
          { metric: 'Revenus sur douze mois glissants', value: fr(G$.rev / 1e9, 2) + ' Md$', signal: 'Exercice 2025 + premier semestre 2026 − premier semestre 2025, au 30 juin 2026', signalColor: 'blue', _src: 'gaap' },
          { metric: 'Résultat opérationnel sur douze mois', value: fr(G$.ebit / 1e6, 0) + ' M$', signal: 'Marge opérationnelle de ' + fr(opMargin, 0) + ' %, douze mois au 30 juin 2026', signalColor: 'green', _src: 'gaap' },
          { metric: 'EBITDA sur douze mois', value: fr(G$.ebitda / 1e9, 2) + ' Md$', signal: 'Résultat opérationnel + amortissements et épuisement (' + fr(G$.da / 1e6, 0) + ' M$), activités poursuivies', signalColor: 'green', _src: 'gaap' },
          { metric: 'Résultat net sur douze mois (activités poursuivies)', value: fr(G$.ni / 1e6, 0) + ' M$', signal: 'Positif ; PER d’environ ' + fr(pe, 0) + ' fois sur cette base', signalColor: 'blue', _src: 'gaap' },
          { metric: 'Trésorerie au 30 juin 2026', value: fr(G$.cash / 1e6, 0) + ' M$', signal: 'Contre 407,4 M$ au 31 décembre 2025', signalColor: 'blue', _src: 'gaap' },
          { metric: 'Prêts et emprunts au 30 juin 2026', value: fr(G$.debt / 1e6, 0) + ' M$', signal: 'Contre 1 554,7 M$ fin 2025 ; désendettement via la cession du Brésil', signalColor: 'green', _src: 'gaap' },
          { metric: 'Dette nette / EBITDA', value: fr(ndToEbitda, 2) + '×', signal: 'Dette nette de ' + fr(netDebt / 1e6, 0) + ' M$ ; bilan solide pour un producteur d’or', signalColor: 'green', _src: 'gaap' },
          { metric: 'EV/EBITDA douze mois glissants', value: fr(evEbitda, 1) + '×', signal: 'Valeur d’entreprise (enterprise value) au close du 2026-09-25 (1 167,5 M d’actions, dette et trésorerie du 30 juin) sur EBITDA douze mois glissants (trailing) au 30 juin 2026, activités poursuivies', signalColor: 'amber', source: 'Clôture certifiée et dépôts primaires', comparison: 'Versus Newmont à ' + fr(nemEv, 1) + '×, Agnico à ' + fr(aemEv, 1) + '×, Alamos à ' + fr(agiEv, 1) + '×, B2Gold à ' + fr(btgEv, 1) + '× et IAMGOLD à ' + fr(iagEv, 1) + '× (statistiques courantes, non point-in-time) : Equinox se paie en milieu de peloton, sous les intermédiaires premium et loin des décotes. Les actions incluent Orla, l’EBITDA non : pro forma, le multiple serait inférieur.', _src: 'market', _peers: ['NEM', 'AEM', 'AGI', 'BTG', 'IAG'], _peerField: 'enterpriseToEbitda' },
          { metric: 'EV/EBITDA — scénario de compression (hypothèse éditoriale)', value: fr(scn.price, 2) + ' $ par action', signal: 'Scénario : multiple ramené par hypothèse à sept fois l’EBITDA douze mois, bilan du 30 juin, soit ' + fr(scn.downside_pct, 0) + ' % sous le close du 2026-09-25', signalColor: 'amber', source: 'Clôture certifiée et dépôts primaires', comparison: 'Sept fois = le niveau de Newmont (' + fr(nemEv, 1) + '×) et le milieu de la fourchette sectorielle ; ce que coûterait un retour au multiple du senior, pas un objectif. Sur base pro forma incluant Orla, ce plancher serait moins sévère.', _src: 'market', _peers: ['NEM'], _peerField: 'enterpriseToEbitda' },
          { metric: 'EV/revenus douze mois glissants', value: fr(evRev, 1) + '×', signal: 'Repère secondaire ; revenus douze mois glissants (trailing) au 30 juin 2026, activités poursuivies ; cohérent avec un producteur à forte marge', signalColor: 'blue', source: 'Clôture certifiée et dépôts primaires', comparison: 'Versus Newmont à ' + fr(peerStat('NEM', 'enterpriseToRevenue'), 1) + '× et Alamos à ' + fr(peerStat('AGI', 'enterpriseToRevenue'), 1) + '× (statistiques courantes, non point-in-time) : cohérent avec un producteur d’or à forte marge.', _src: 'market', _peers: ['NEM', 'AGI'], _peerField: 'enterpriseToRevenue' },
          { metric: 'Actions ordinaires en circulation', value: '1 167 459 822', signal: 'À la date du rapport du deuxième trimestre, après Orla ; contre 785 632 450 fin 2025', signalColor: 'amber', _src: 2 },
          { metric: 'Billets convertibles 2023', value: '172,5 M$', signal: 'Coupon 4,75 %, échéance octobre 2028, prix de conversion 6,30 $ ; potentiellement dilutifs', signalColor: 'amber', _src: 0 },
          { metric: 'Bêta sur le marché', value: fr(st.beta, 2), signal: 'Sensibilité élevée : le titre amplifie les mouvements du prix de l’or', signalColor: 'amber', _src: 'market' }],
        sourceRefs: [ref(0), ref(1), market('agrégats et statistiques comparables')] },
      earnings: { quarters: [],
        beatNote: 'Premier semestre 2026 (6-K du 5 août) : revenus des activités poursuivies de 1 631,4 M$ (contre 551,5 M$), résultat opérationnel de 637,6 M$, résultat net des activités poursuivies de 405,8 M$. L’exercice 2025 (40-F) affichait 1 817,2 M$ de revenus, 432,3 M$ de résultat opérationnel et une perte nette des activités poursuivies de 18,9 M$ (grevée par des charges financières et fiscales). Émetteur étranger : publication semestrielle et trimestrielle par 6-K, sans guidance chiffrée standardisée dans les états condensés ouverts. Aucune date de prochaine publication n’est confirmée par l’émetteur.',
        nextEarnings: 'Date non confirmée par l’émetteur ; cadence de publication trimestrielle et semestrielle (6-K). Aucun événement de résultats n’est signalé dans l’horizon du plan par le calendrier collecté.',
        sourceRefs: [ref(1)] },
      capitalStructure: { sharesOutstanding: '1 167 459 822 actions ordinaires en circulation à la date du rapport de gestion du deuxième trimestre 2026 (après la clôture de l’acquisition d’Orla le 31 juillet 2026)',
        sharesAuthorized: 'Programme de rachat d’actions dans le cours normal (jusqu’à environ 39,4 millions d’actions) ; aucun programme d’émission au marché actif.', dilutionRisk: 'moderate',
        shareHistory: 'La dilution est le prix d’une croissance par acquisitions, non celui d’un financement toxique. Le nombre d’actions est passé d’environ 477,7 millions (moyenne pondérée du premier semestre 2025) à 785 632 450 au 31 décembre 2025 — la fusion toute en actions avec Calibre a émis 302,8 millions d’actions en juin 2025 — puis à 1 167 459 822 à la date du rapport du deuxième trimestre 2026, après l’acquisition d’Orla clôturée le 31 juillet. En quinze mois, le capital a plus que doublé. À côté des actions, les instruments dilutifs restent modestes : des billets convertibles 2023 de 172,5 M$ (prix de conversion 6,30 $, échéance octobre 2028) et des billets 2025 repris de Calibre de C$49,7 M (conversion C$12,14, échéance 2030), plus 4 271 060 bons de souscription au prix moyen de C$10,43 ; les convertibles 2020 ont été entièrement converties en août 2025. L’offre au marché de 100 M$ est échue depuis décembre 2024 et aucun nouveau programme n’a été ouvert. En face, la trésorerie est de 317,8 M$ et la dette, ramenée à 583,0 M$, est en grande partie une facilité de crédit et de petits convertibles : le risque de dilution est réel mais lié aux acquisitions passées, non à une machine à émettre des actions au fil de l’eau. Passage au nombre pleinement dilué : le compte d’actions pleinement diluées intégrant la conversion des billets et l’exercice des bons de souscription n’est pas isolé dans les états condensés ouverts (non disponible ici) ; il serait supérieur aux 1 167 459 822 actions ordinaires de base.',
        warrants: [], atm: { active: false, authorized: 'Offre au marché de 100 M$ échue en décembre 2024', used: 'Programme antérieur pleinement utilisé puis expiré', remaining: 'Aucun programme d’émission au marché actif' },
        sourceRefs: [ref(2), ref(0), ref(3)] },
      filingsReview: { summary: 'Cinq dépôts décisionnels ouverts et hachés : les états financiers et le rapport de gestion du 40-F 2025, les états financiers et le rapport de gestion du 6-K du 5 août 2026, et la page de garde du 40-F. Ils montrent un producteur rentable et désendetté, mais dont le capital a plus que doublé en quinze mois par fusions successives (Calibre, Orla) et cession du Brésil.',
        filings: docs.map(d => ({ date: d.date, form: d.form, accession: d.accession, finding: d.finding, url: d.url })),
        contrarianRisks: [
          'Le résultat dépend d’abord du prix de l’or : une correction du métal compresserait la marge et l’EBITDA, base de la valorisation.',
          'L’intégration simultanée de Calibre et d’Orla et la montée en puissance de Greenstone peuvent déraper sur les coûts ou les délais.',
          'La conversion des billets et l’exercice des bons ajouteraient des actions, au-delà de la dilution déjà encaissée par les fusions.',
          'Le résultat net 2025 des activités poursuivies était négatif malgré un résultat opérationnel positif : les charges financières et fiscales pèsent lourd.'] },
      technicals: { rsi14: +tech.rsi14.toFixed(2), macd: +tech.macd.toFixed(2), macdSignal: +tech.macdSignal.toFixed(2), ema20: +tech.ema20.toFixed(2), ema50: +tech.ema50.toFixed(2), ema200: +tech.ema200.toFixed(2),
        ma50Type: 'EMA', ma200Type: 'EMA', ma50Available: true, ma200Available: true, atr14: +tech.atr14.toFixed(2),
        badges: [fr(Math.abs(ext20), 1) + ' % sous la moyenne à vingt séances', 'Sur les moyennes à cinquante et deux cents séances', 'ATR de ' + usd(tech.atr14)],
        supports: [lv('s1'), stop, lv('s2')], resistances: [lv('r1'), lv('r2'), entry],
        setupNote: 'Le titre clôture à ' + usd(close) + ', ' + fr(ext20, 1) + ' % par rapport à sa moyenne à vingt séances et ' + fr(Math.abs(pct(close, entry)), 1) + ' % sous le sommet du 8 septembre, ' + usd(entry) + '. Il a gagné ' + fr((run - 1) * 100, 0) + ' % depuis son plus bas de juillet (' + usd(lo) + ') mais reste ' + fr(Math.abs(pct(close, hi)), 0) + ' % sous son sommet de février (' + usd(hi) + '). RSI à ' + fr(tech.rsi14, 0) + ', neutre. Avant activation, aucune entrée ; une clôture sous ' + usd(abandon) + ', le bas du 16 septembre, abandonne le scénario. Activation sur une clôture au-dessus de $' + entry.toFixed(2) + '. Après activation, stop sous $' + stop.toFixed(2) + ', le plus bas du 18 septembre, soit ' + fr(riskAtr, 2) + ' ATR sous le déclencheur. Supports : ' + usd(lv('s1')) + ', ' + usd(stop) + ' et ' + usd(lv('s2')) + '. Résistances : ' + usd(lv('r1')) + ', ' + usd(lv('r2')) + ' et ' + usd(entry) + ' ; au-delà, la zone du sommet d’août, ' + usd(tp1) + '.',
        wyckoff: 'Non utilisé : le profil de volume n’est pas exploité dans ce dossier.',
        sourceRefs: [market('barres quotidiennes et indicateurs recalculés')] },
      options: { callOI: 'Non exploitable', putOI: 'Non exploitable', cpRatio: 'Non exploitable', maxPain: 'Non exploitable', ivMean: 'Non exploitable', skew: 'Chaîne d’options non retenue dans ce dossier', unusual: 'Aucune activité inhabituelle qualifiée', sourceRefs: [market('options')] },
      shortInterest: { siPct: 'Non renseigné par le snapshot', daysToCover: fr(st.shortRatio, 2) + ' jours, date de règlement non précisée par le snapshot', ctb: 'Coût d’emprunt indisponible à la collecte (fournisseur en échec)', trend: 'Le pourcentage du flottant vendu à découvert n’est pas renseigné par le snapshot ; le seul ratio de couverture, d’environ ' + fr(st.shortRatio, 1) + ' jours, ne soutient aucune thèse de rachat forcé.', squeezeScore: 'Non quantifié faute de données de position vendeuse et de coût d’emprunt', sourceRefs: [market('positions vendeuses')] },
      insiders: { signal: 'Aucun solde net d’initiés affirmé : la couverture officielle des transactions d’initiés est partielle pour un émetteur étranger canadien, dont les dirigeants déclarent d’abord au Canada (SEDI) et pas systématiquement par formulaire 4. Aucune transaction d’initié décisive n’est établie ici ; le fait capitalistique du semestre est l’acquisition d’Orla, réglée en actions.',
        recentTransactions: [],
        sourceRefs: [market('transactions d’initiés — couverture partielle')] },
      macro: { indicators: [{ name: 'Clôture de référence', value: c.REF, signal: usd(close) + ', séance complète' }, { name: 'Rendement cinq séances', value: sgn(ret(5)), signal: 'Descriptif' }, { name: 'Rendement vingt et une séances', value: sgn(ret(21)), signal: 'Descriptif' }],
        regime: 'neutral', impact: 'Equinox vit du prix de l’or et de ses coûts tout compris. Une hausse durable du métal dope directement la marge et l’EBITDA, base de la valorisation ; une correction, ou une remontée des taux réels et du dollar qui pèserait sur l’or, ferait l’inverse, amplifiée par un bêta de ' + fr(st.beta, 1) + '. Le coût du capital et l’inflation des coûts miniers (énergie, main-d’œuvre) sont les autres variables clés.' },
      risks: { riskScore: 6, riskProfile: 'High',
        riskSummary: 'Le risque d’Equinox n’est pas le bilan, désormais solide, ni la valorisation, de milieu de peloton : c’est la sensibilité au prix de l’or (bêta ' + fr(st.beta, 1) + ') et l’exécution. Le groupe intègre deux fusions et fait monter Greenstone en régime, après avoir plus que doublé son nombre d’actions. Le titre, en repli de ' + fr(Math.abs(ret(21)), 0) + ' % sur un mois, reste sous son déclencheur.',
        riskCards: [
          { title: 'Dépendance au prix de l’or', severity: 'high', icon: 'fa-arrows-spin', points: ['Bêta de ' + fr(st.beta, 1) + ' : le titre amplifie les mouvements du métal.', 'La valorisation repose sur un EBITDA lui-même fonction du prix de l’or.'], verdict: 'Une correction de l’or frapperait la marge et le multiple en même temps.' },
          { title: 'Exécution et intégration', severity: 'high', icon: 'fa-user-tie', points: ['Intégration simultanée de Calibre (2025) et d’Orla (2026).', 'Montée en puissance de Greenstone à mener sans dérive de coûts.'], verdict: 'Beaucoup de chantiers en parallèle : peu de marge à l’erreur opérationnelle.' },
          { title: 'Dilution par acquisitions', severity: 'medium', icon: 'fa-money-bill-trend-up', points: ['Nombre d’actions plus que doublé en quinze mois (Calibre + Orla).', 'Billets convertibles et bons de souscription encore en circulation.'], verdict: 'Dilution liée aux fusions, non à un financement toxique, mais bien réelle par action.' },
          { title: 'Volatilité de court terme', severity: 'medium', icon: 'fa-chart-line', points: ['ATR de ' + usd(tech.atr14) + ' ; repli de ' + fr(Math.abs(ret(21)), 0) + ' % sur un mois.', 'Titre sous ses moyennes courtes, sans entrée avant activation.'], verdict: 'Les écarts de plusieurs pour cent sont fréquents : dimensionner sur la distance au stop.' }],
        pedagogy: 'Un producteur d’or est un pari sur le métal avec un levier opérationnel : quand l’or monte, la marge grimpe plus vite que le chiffre d’affaires ; quand il baisse, l’inverse. Ici, le bilan assaini (dette nette de ' + fr(ndToEbitda, 2) + ' fois l’EBITDA) réduit le risque financier, mais pas le risque de marché, porté par un bêta de ' + fr(st.beta, 1) + '. La liquidité est ample — environ ' + fr(adv / 1e6, 0) + ' M$ échangés par séance — donc le slippage reste faible. La question centrale n’est pas la qualité des mines mais le prix de l’or et l’exécution des intégrations ; dimensionner sur la distance au stop, ' + usd(entry - stop) + ' par action, pas sur la conviction. Aucune publication de résultats n’est programmée dans l’horizon du plan : le catalyseur est technique (reprise du déclencheur) et macro (prix de l’or), pas un événement de calendrier daté.' },
      tradeIdea: { status: 'watch', statusNote: 'Surveiller. Avant activation : aucune entrée ; une clôture sous ' + usd(abandon) + ' abandonne le scénario. Activation : clôture au-dessus de ' + usd(entry) + ', puis achat à l’ouverture suivante seulement sous ' + usd(cap) + ', ou par ordre limité à ce plafond pendant trois séances, annulé après une clôture sous ' + usd(entry) + ' et jamais laissé actif sur une ouverture sous ' + usd(stop) + '. Après activation : stop sous ' + usd(stop) + '. Le repli laisse le titre sous le déclencheur : le plan n’est pas activé.',
        entry, stop, tp1, tp2,
        stopPct: pct(stop, entry).toFixed(1) + '%', tp1Pct: '+' + pct(tp1, entry).toFixed(1) + '%', tp2Pct: '+' + pct(tp2, entry).toFixed(1) + '%',
        rr: '1:' + rr1.toFixed(2) + ' TP1 / 1:' + rr2.toFixed(2) + ' TP2',
        entryNote: 'Déclencheur sur clôture au-dessus du plus haut du 8 septembre, pas sur un franchissement en séance. Entrée à l’ouverture suivante uniquement sous ' + usd(cap) + ' : au-delà, le R/R vers TP1 tomberait sous 1,5 avec le même stop. Ce plafond n’est qu’à ' + usd(cap - entry) + ' au-dessus du déclencheur, soit ' + fr(bufAtr, 2) + ' ATR. Mesure : sur les ' + gs.total + ' dernières séances, ' + gs.up + ' ouvertures ont dépassé la clôture de la veille de plus de ' + usd(cap - entry) + ', soit environ ' + fr(blocked, 0) + ' % ; l’écart d’ouverture médian, dans un sens ou dans l’autre, vaut ' + usd(gs.medAbs) + '. Sur la série, ' + bk.n + ' clôtures ont cassé un plus haut de vingt séances : ' + bk.inBand + ' ont fini à moins de ' + fr(bufPct, 2) + ' % au-dessus du niveau cassé, l’écart relatif du plafond, et ' + bk.buyable + ' ont ensuite ouvert sous ce seuil. Plan de repli : si l’ouverture dépasse le plafond, un ordre à cours limité à ' + usd(cap) + ', valable trois séances, garde le même R/R et le même stop ; il est annulé après toute clôture sous le déclencheur, ' + usd(entry) + ', n’est pas laissé actif à l’ouverture d’une séance sous le stop, ' + usd(stop) + ', ni si le stop est touché avant exécution. Rejoué avec ces bornes sur les ' + rt.miss + ' cassures non achetables à l’ouverture, l’ordre aurait été exécuté ' + rt.back + ' fois' + (rt.stopSame ? ', dont ' + rt.stopSame + ' avec le stop touché la même séance' : ', sans que le stop soit touché la même séance') + (rt.gapUnder ? ' ; ' + rt.gapUnder + ' fois retiré sur une ouverture sous le stop' : ' ; aucun retrait sur ouverture sous le stop') + '. Objectifs : TP1 au sommet du rebond d’août, TP2 à une hauteur de couloir au-dessus. Liquidité : environ ' + fr(adv / 1e6, 0) + ' M$ échangés par séance, médiane des vingt dernières. Exemple de taille, non personnalisé : avec un budget de perte de 100 $, le risque au plafond, ' + usd(cap - stop) + ' par action, donne ' + sizeExample + ' action' + (sizeExample > 1 ? 's' : '') + ' ; avec 1 000 $, ' + big + ' actions.',
        horizon: 'Dix à vingt séances après activation',
        thesis: 'Equinox est un producteur d’or rentable, désendetté après la cession du Brésil, et valorisé en milieu de peloton — pas une aubaine, pas une bulle. Le dossier se joue sur deux variables : le prix de l’or, amplifié par un bêta de ' + fr(st.beta, 1) + ', et l’exécution des intégrations de Calibre et d’Orla. Une clôture au-dessus de $' + entry.toFixed(2) + ' montrerait que les acheteurs reprennent la main après le repli de septembre. Avant activation, une clôture sous ' + usd(abandon) + ' abandonne le dossier. Après activation, le stop sous $' + stop.toFixed(2) + ' limite le coût d’une fausse sortie. TP1 à ' + usd(tp1) + ', TP2 à ' + usd(tp2) + '. Ne pas anticiper le déclencheur, ne pas acheter un gap au-dessus du plafond.',
        catalysts: ['Une clôture au-dessus du plus haut du 8 septembre, sur un volume au moins égal à la médiane récente.', 'La tenue du prix de l’or et toute avancée sur la montée en puissance de Greenstone ou l’intégration d’Orla.', 'Le rythme de désendettement et la génération de trésorerie disponible, à suivre dans les prochains 6-K.'],
        invalidation: ['Avant activation : une clôture sous ' + usd(abandon) + ', bas du couloir, abandonne le scénario.', 'Après activation : une clôture sous ' + usd(stop) + ' invalide le trade.', 'Ouverture au-dessus de ' + usd(cap) + ' après la clôture de déclenchement : pas d’achat à l’ouverture ; seul l’ordre limité à ' + usd(cap) + ' reste valable trois séances.', 'Une correction marquée du prix de l’or avant activation change l’équation et annule la thèse.'] },
      globalScore: { profile: 'Producteur d’or rentable et désendetté, à fort bêta et en pleine intégration',
        keyTakeawaysPositive: ['Rentable : marge opérationnelle de ' + fr(opMargin, 0) + ' %, EBITDA de ' + fr(G$.ebitda / 1e9, 1) + ' Md$.', 'Bilan assaini : dette nette de ' + fr(ndToEbitda, 2) + ' fois l’EBITDA.', 'Valorisation de milieu de peloton, pas une prime.'],
        keyTakeawaysNegative: ['Bêta de ' + fr(st.beta, 1) + ' sur le prix de l’or.', 'Nombre d’actions plus que doublé en quinze mois.', 'Intégration de deux fusions et montée en puissance de Greenstone à réussir.'],
        mindsetTip: 'Un bon mineur ne protège pas d’un mauvais prix de l’or. La question utile n’est pas « Equinox est-il bien géré ? » mais « suis-je prêt à porter un pari sur l’or à effet de levier, avec un bêta de deux et demi ? ».' },
      social: { platforms: [], sourceRefs: [market('sentiment non retenu faute de mesure qualifiée')] },
      disclaimer: 'Document de recherche éducatif. Ni conseil financier, ni signal de trading. Statut surveiller : aucun ordre actif.',
    };
  },
  groups: [
    { name: 'Références seniors de l’or', order: 1, transmission: 'Les deux plus grands producteurs d’or : ils fixent le ton du secteur et servent de référence de valorisation et de coûts.', rows: [
      ['NEM', 'leader', 'Premier producteur d’or mondial', 'Bellwether du secteur ; son multiple et ses coûts servent de référence à tout le complexe aurifère, Equinox compris.'],
      ['AEM', 'direct_peer', 'Producteur d’or senior de qualité', 'Intermédiaire premium à faibles coûts ; son multiple élevé borne le haut de la fourchette de valorisation.']] },
    { name: 'Pairs producteurs — intermédiaires', order: 1, transmission: 'Autres producteurs d’or de taille comparable : même métier, même moteur (prix de l’or moins coûts), lecture directe des multiples.', rows: [
      ['AGI', 'direct_peer', 'Producteur d’or intermédiaire', 'Pair le plus comparable par la taille et la qualité ; son multiple éclaire directement celui d’Equinox.'],
      ['BTG', 'direct_peer', 'Producteur d’or intermédiaire', 'Pair décoté : son multiple bas marque le bas de la fourchette et le risque géographique du segment.'],
      ['IAG', 'direct_peer', 'Producteur d’or intermédiaire', 'Autre intermédiaire décoté ; utile pour situer Equinox entre les premium et les décotes.'],
      ['HL', 'direct_peer', 'Producteur d’or et d’argent', 'Producteur nord-américain à double exposition or-argent ; multiple élevé, sensible au levier opérationnel.'],
      ['GAU', 'direct_peer', 'Petit producteur d’or', 'Petit producteur : son multiple bas rappelle la décote appliquée à la taille et à la concentration d’actifs.']] },
    { name: 'Redevances et streaming', order: 2, transmission: 'Modèle sans risque opérationnel minier : suit le prix de l’or et le sentiment du secteur, mais avec une prime de multiple structurelle.', rows: [
      ['RGLD', 'second_order', 'Redevances et streaming aurifères', 'Multiple élevé (modèle de redevances) ; sert de référence de sentiment, pas de pair opérationnel.']] },
    { name: 'Sous-jacent — prix de l’or', order: 1, transmission: 'Le prix du métal est le premier moteur du chiffre d’affaires et de la marge d’un producteur.', rows: [
      ['SGOL', 'upstream', 'Or physique (ETF)', 'Le métal lui-même : sa trajectoire commande directement les revenus et l’EBITDA d’Equinox.']] },
    { name: 'Paniers de mineurs d’or', order: 2, transmission: 'Paniers sectoriels : un mouvement commun avec eux n’a rien de propre au titre.', rows: [
      ['GDX', 'sector_proxy', 'Panier des grands mineurs d’or', 'Mesure la performance du secteur ; un écart isole ce qui est propre à Equinox.'],
      ['GDXJ', 'sector_proxy', 'Panier des mineurs d’or juniors', 'Segment plus risqué et plus volatil ; repère du degré de prise de risque du marché.']] },
    { name: 'Complexe argent', order: 2, transmission: 'L’argent accompagne souvent l’or mais avec plus d’amplitude ; contrôle de la corrélation métaux précieux.', rows: [
      ['SIL', 'sector_proxy', 'Panier des mineurs d’argent', 'Contrôle du complexe argent ; corrélé à l’or mais avec un bêta plus élevé.'],
      ['SLV', 'sector_proxy', 'Argent physique (ETF)', 'Le métal argent : contrôle de la corrélation des métaux précieux.']] },
  ],
  eventDefault: { leader: 'Aucune publication dans les quatorze jours collectés ; ses résultats et le prix de l’or restent le signal à suivre', direct_peer: 'Aucune publication dans les quatorze jours collectés ; ses coûts et son multiple restent le signal à suivre', upstream: 'Panier de matière première sans publication propre ; suit le prix de l’or', second_order: 'Aucune publication dans les quatorze jours collectés ; sentiment du secteur à suivre', sector_proxy: 'Panier sans publication propre ; exposé au prix des métaux et à ses grandes pondérations' },
  eventRisk: {},
  blastDoc: 0,
  scenarios: c => [
    { scenario: 'bullish', trigger: 'Le prix de l’or tient ou progresse et Equinox montre l’exécution de Greenstone et d’Orla.', firstOrder: 'Le titre clôture au-dessus du sommet du 8 septembre et vise la zone du sommet d’août.', secondOrder: 'GDX et Newmont accompagnent ; le complexe aurifère confirme.', confirmation: 'Une clôture au-dessus de ' + c.usd(c.entry) + ' avec GDX en hausse.', contradiction: 'Un dépassement du seuil pendant que GDX recule.' },
    { scenario: 'mixed', trigger: 'Pas de nouvelle propre ; l’or et le secteur consolident.', firstOrder: 'Le titre oscille entre le bas du 16 septembre et le sommet du 8.', secondOrder: 'L’écart avec Alamos et GDX reste faible.', confirmation: 'Des clôtures entre ' + c.usd(c.abandon) + ' et ' + c.usd(c.entry) + ' pendant plusieurs séances.', contradiction: 'Une sortie franche d’un côté ou de l’autre.' },
    { scenario: 'bearish', trigger: 'Correction du prix de l’or, remontée des taux réels et du dollar, ou dérapage de coûts sur l’intégration.', firstOrder: 'Le titre repasse sous le bas du 16 septembre, amplifié par son bêta de ' + c.fr(c.st.beta, 1) + '.', secondOrder: 'Les producteurs reculent plus que l’or physique ; GDX sous-performe SGOL.', confirmation: 'Une clôture sous ' + c.usd(c.abandon) + ' avec GDX en baisse.', contradiction: 'Un repli du secteur qu’Equinox ne suit pas.' }],
  contradictions: c => ['Les revenus doublent sur un an, mais le résultat net 2025 des activités poursuivies était négatif : charges financières et fiscales absorbaient alors le résultat opérationnel.', 'Le bilan est solide (dette nette de ' + c.fr((c.G$.debt - c.G$.cash) / c.G$.ebitda, 2) + ' fois l’EBITDA), mais le capital a plus que doublé en quinze mois : la dette a baissé, le nombre d’actions a explosé.', 'Un multiple de milieu de peloton peut sembler prudent, mais il est calculé sur des actions post-Orla et un EBITDA pré-Orla : la lecture pro forma est différente.'],
  missingData: c => ['Aucun companyfacts us-gaap n’existe pour cet émetteur étranger : les agrégats sont lus dans les états IFRS des dépôts primaires (USD confirmé), en douze mois glissants au 30 juin 2026, activités poursuivies.', 'Le multiple EV/EBITDA rapporte des actions post-Orla (acquisition clôturée le 31 juillet 2026) à un EBITDA douze mois qui lui est antérieur : sur base pro forma, il serait inférieur.', 'Coût d’emprunt indisponible à la collecte (fournisseur en échec) ; pourcentage du flottant vendu à découvert non renseigné ; chaîne d’options et sentiment social non retenus.', 'Couverture officielle des transactions d’initiés partielle pour un émetteur étranger canadien (déclarations SEDI) ; aucun solde net affirmé.', 'Dix comparables aurifères élagués du set pour barres corrompues au 25 septembre (AU, EGO, FNV, GFI, GOLD, HMY, KGC, OR, PAAS, WPM) : treize comparables propres conservés, couvrant six groupes économiques.'],
  limitations: ['Émetteur étranger IFRS : agrégats reconstitués depuis les dépôts primaires (USD), non depuis un flux XBRL standardisé.', 'Base de flux en douze mois glissants au 30 juin 2026, activités poursuivies (Brésil en activités abandonnées).', 'EV/EBITDA sur actions post-Orla et EBITDA pré-Orla : à lire comme un plafond, non comme la valorisation pro forma.', 'Coût d’emprunt, position vendeuse détaillée, options et sentiment social non exploitables à la collecte.'],
});
