'use strict';
// Dossier IREN v3 au close du 2026-10-08. Refonte de la v2 du 28 août (statut « attendre », niveaux dormants
// jamais rendus exécutables). Contenu éditorial et repères propres au titre ; calculs, provenance et preuves
// délégués au gabarit tools/lib/analysis-v3-r08.cjs (REF=2026-10-08, run 20261009).
// Agrégats GAAP lus dans les données XBRL officielles de la SEC (companyfacts, 10-K de l'exercice clos le
// 30 juin 2026 inclus) : douze mois glissants = exercice 2026 complet (aucun 10-Q postérieur). EBITDA GAAP négatif
// (dépréciation de 638,8 M$ du matériel de minage), donc multiple de scénario appliqué aux revenus.
// Dette = dette à long terme courante et non courante + passifs de location-financement au 30 juin.
// Trésorerie = liquidités et équivalents au 30 juin, hors trésorerie soumise à restriction (1,72 Md$, adossée
// aux financements de GPU). Actions = 394 058 648 au 14 août 2026 (10-K).
// Révision du 9 octobre après revues indépendantes (contrarian, senior QA, retail) : NVIDIA client et détenteur
// de droits, six séries de convertibles, offre de décembre 2025, dilution chiffrée, garantie exacte, gaps chiffrés.
// Comparables : HUT, CLSK et BTDR refusés par le contrat de clôture (séances incomplètes) ; Microsoft, client
// documenté, collecté en série client séparée.
const R = require('../../../../tools/lib/analysis-v3-r08.cjs');
const GEN = 'analyses/IREN/_runs/20261009/build-iren.cjs';
const SHARES = 394058648;

R.build({
  ticker: 'IREN', shortName: 'IREN', cik: 1878848, generator: GEN, mode: 'archived', clientBars: true, peers: true,
  extraInputs: [{ name: 'signals', path: 'analyses/IREN/_data/symbol_signals.json' }, { name: 'instrument', path: 'analyses/IREN/_data/instrument.json' }],
  ref: '2026-10-08', run: '20261009', asOf: '2026-10-09',
  xbrl: {
    ttm: {
      rev: ['Revenues'],
      ebit: ['OperatingIncomeLoss'],
      ni: ['NetIncomeLoss'],
      da: ['DepreciationDepletionAndAmortization'],
      ocf: ['NetCashProvidedByUsedInOperatingActivities'],
      capex: ['PaymentsToAcquirePropertyPlantAndEquipment'],
    },
    instant: {
      debtCur: ['LongTermDebtCurrent'],
      debtNon: ['LongTermDebtNoncurrent'],
      flCur: ['FinanceLeaseLiabilityCurrent'],
      flNon: ['FinanceLeaseLiabilityNoncurrent'],
      cashEq: ['CashAndCashEquivalentsAtCarryingValue'],
    },
    da: ['da'], debt: ['debtCur', 'debtNon', 'flCur', 'flNon'], cash: ['cashEq'],
  },
  scenarioBasis: 'revenue', scenarioMultiple: 12,
  valuationBasis: 'GAAP douze mois au 2026-06-30 (XBRL SEC) = exercice 2026 complet ; EBITDA GAAP négatif après 638,8 M$ de dépréciations, donc multiple appliqué aux revenus GAAP ; revenus GAAP à 82 % issus du minage en démantèlement (578,2 M$ sur 707,0 M$) ; dette = dette à long terme courante et non courante + passifs de location-financement au 30 juin (convertibles 2029 et 2030, dans la monnaie, comptés à leur valeur comptable et non à leur valeur de conversion) ; trésorerie = liquidités et équivalents au 30 juin, hors trésorerie soumise à restriction ; 394 058 648 actions au 14 août (actions d’août, bilan de juin) ; douze fois les revenus = hypothèse éditoriale de stress, nettement sous les ~22× implicites au close',
  shares: { value: SHARES, doc: 0 },
  levels: {
    s1: { d: '2026-10-08', c: 3 }, // 35,24 — plus bas de la séance de référence
    s2: { d: '2026-08-28', c: 3 }, // 34,81 — plus bas du lendemain des résultats annuels
    s3: { d: '2026-07-29', c: 3 }, // 28,93 — plus bas sur un an (capitulation de fin juillet)
    r1: { d: '2026-10-06', c: 2 }, // 42,178 — dernier sommet décroissant
    r2: { d: '2026-10-02', c: 2 }, // 43,91 — plus haut du rebond du 2 octobre
    r3: { d: '2026-09-23', c: 2 }, // 49,3699 — sommet de septembre
  },
  supports: ['s1', 's2', 's3'], resistances: ['r1', 'r2', 'r3'],
  levelsMethod: 'Niveaux du plan du 28 août conservés à l’identique (archivés, jamais rendus exécutables) ; supports et résistances actuels lus sur les barres certifiées.',
  inventory: 44,
  reviewScope: 'Dépôts EDGAR d’IREN du 9 octobre 2025 au 8 octobre 2026 (51 dépôts au total, 44 hors formulaires 3, 4, 5 et 144 de déclaration de détention). Treize pièces décisionnelles ouvertes et hachées : le 10-K de l’exercice clos le 30 juin 2026 (dont les notes sur la dette, les capitaux propres et les droits d’investissement NVIDIA), le communiqué de résultats annuels du 27 août, le contrat Microsoft de novembre 2025, la livraison d’Horizon 1 du 13 août, l’émission convertible de 3 Md$ de mai (communiqué et 8-K), le financement de GPU de juin, l’accord d’achat Dell de mai, l’annonce des 150 000 GPU et du programme « at-the-market » de mars (communiqué et 8-K des achats Dell), l’acquisition de Mirantis d’août (communiqué et 8-K du prospectus de revente), et le 8-K de décembre 2025 (convertibles 2032 et 2033, offre directe enregistrée, rachat des convertibles 2029 et 2030). Les 8-K de gouvernance, les Schedule 13G et les prospectus de tirage sont écartés comme non décisionnels ou redondants avec ces pièces.',
  docs: [
    ['2026-08-27', '10-K', '0001878848-26-000052', 'iren-20260630.htm', 'fy26-10k.htm',
      'Rapport annuel de l’exercice clos le 30 juin 2026 : chiffre d’affaires de 707,0 M$, perte opérationnelle de 1 046,7 M$ après 638,8 M$ de dépréciations du matériel de minage, perte nette de 702,6 M$. Actions : 258 103 209 au 30 juin 2025, 380 193 608 au 30 juin 2026, 394 058 648 au 14 août. Programme « at-the-market » : supplément de prospectus du 4 mars 2026 pour jusqu’à 6,0 Md$, 47,2 millions d’actions vendues pour 2 492,1 M$ bruts ; sur l’exercice, 70,2 millions d’actions vendues par l’« at-the-market » (3 058,0 M$ nets) et 39,7 millions par offre directe enregistrée (1 631,5 M$ nets). Six séries de convertibles (prix de conversion initiaux de 13,64 $ à 85,63 $), réglables en numéraire, en actions ou en combinaison au choix d’IREN ; seuil de conversion atteint au 30 juin pour les séries 2029 et 2030. Droits d’investissement accordés à NVIDIA le 7 mai 2026 : jusqu’à 30 millions d’actions à 70,00 $, acquis par tranches selon le volume de GPU livrés, échéance 7 mai 2031. 7 976,0 M$ de dette en principal : 7 705,6 M$ de dette (6 767,6 M$ avec recours, 938,0 M$ sans recours) et 270,4 M$ de location-financement. Contrats Microsoft (9,7 Md$) et NVIDIA (3,4 Md$) = « substantial majority » du revenu contracté. Contrôle interne jugé efficace et opinion sans réserve de l’auditeur ; faiblesse matérielle de l’exercice 2024 remédiée au 30 juin 2025.'],
    ['2026-08-27', '8-K / Exhibit 99.1', '0001878848-26-000051', 'irenreportsfy26results.htm', 'fy26-earnings.htm',
      'Communiqué des résultats annuels : revenus cloud IA de 128,8 M$ (contre 16,4 M$), revenus de minage de 578,2 M$, chiffre d’affaires total de 707,0 M$ ; EBITDA ajusté de 245,7 M$ sur l’exercice et de 19,2 M$ au quatrième trimestre. 4 Md$ de revenu annualisé contracté pour la capacité 2026, 1 Md$ en exploitation au 26 août ; nouveau contrat avec un laboratoire d’IA de pointe ; 2,8 Md$ de nouveaux financements de GPU, dont 2,4 Md$ menés par Blue Owl à 9,0 %.'],
    ['2025-11-03', '8-K / Exhibit 99.1', '0001140361-25-040072', 'ef20058139_ex99-1.htm', 'nov25-msft-pr.htm',
      'Contrat de services cloud GPU de cinq ans avec Microsoft, d’une valeur totale d’environ 9,7 Md$, prépaiement de 20 % compris ; achat corrélatif de GPU et d’équipements à Dell pour environ 5,8 Md$, déployés en 2026 sur le campus de Childress (Horizons 1 à 4, 200 MW de charge informatique).'],
    ['2026-08-13', '8-K / Exhibit 99.1', '0001140361-26-032638', 'ef20080141_ex99-1.htm', 'aug26-13-pr.htm',
      'Horizon 1, premier des quatre déploiements de 50 MW pour Microsoft à Childress, livré et accepté ; statut NVIDIA Exemplar Cloud sur GB300 NVL72. Horizons 2 à 4 attendus plus tard en 2026.'],
    ['2026-05-14', '8-K / Exhibit 99.1', '0001140361-26-021285', 'ef20073507_ex99-1.htm', 'may26-pr-notes.htm',
      'Clôture d’une émission de 3,0 Md$ d’obligations convertibles à 1,00 % échéance 2033, prime de conversion de 32,5 % sur un cours de référence de 55,15 $, achat d’options plafonnées (« capped call ») à 110,30 $ pour 201,3 M$ ; produit net d’environ 2,96 Md$.'],
    ['2026-06-01', '8-K', '0001140361-26-023427', 'ef20075181_8k.htm', 'jun26-8k-financing.htm',
      'Financement de GPU dédié au contrat Microsoft, porté par une filiale : prêt à tirage différé au taux SOFR + 2,25 % et 2,1 Md$ d’obligations garanties à 5,96 % échéance 31 décembre 2031, adossés aux GPU et aux flux du contrat ; ratio de couverture du service de la dette d’au moins 1,05. Garantie de la société mère limitée : si Microsoft résilie valablement une tranche financée sans client de remplacement, la société mère garantit la dette de cette tranche, nette du produit de revente des GPU, plus tout montant initial dû à Microsoft.'],
    ['2026-05-26', '8-K / Exhibit 99.1', '0001878848-26-000030', 'irentrgts44bninarrwithbl.htm', 'may26-pr-arr.htm',
      'Achat à Dell de systèmes Blackwell refroidis par air pour environ 1,6 Md$, destinés à un contrat de services gérés de 3,4 Md$ sur cinq ans (NVIDIA, contrepartie nommée par le 10-K) ; mise en service visée début 2027, revenu annualisé visé porté de 3,7 Md$ à 4,4 Md$, non entièrement contracté.'],
    ['2026-03-04', '8-K / Exhibit 99.1', '0001140361-26-007905', 'ny20064909x3_ex99-1.htm', 'mar26-pr.htm',
      'Commande de plus de 50 000 GPU NVIDIA B300 portant la flotte visée à 150 000 GPU, environ 3,5 Md$ d’investissements supplémentaires attendus au second semestre 2026 ; mise en place d’un programme « at-the-market » d’émission d’actions.'],
    ['2026-08-04', '8-K / Exhibit 99.1', '0001140361-26-031053', 'ny20079234x2_ex99-1.htm', 'aug26-pr.htm',
      'Acquisition de Mirantis (logiciel d’orchestration cloud) réalisée par l’émission d’environ 12,6 millions d’actions ordinaires, plus environ 40 M$ en numéraire, unités d’actions restreintes et autres contreparties.'],
    ['2025-12-08', '8-K', '0001140361-25-044888', 'ef20060782_8k.htm', 'dec25-8k-notes.htm',
      'Émission de 1,15 Md$ de convertibles à 0,25 % échéance 2032 et de 1,15 Md$ à 1,00 % échéance 2033 (produit net d’environ 2 270,0 M$), options plafonnées à 82,24 $ pour 201,0 M$ ; offre directe enregistrée de 39 699 102 actions à 41,12 $ ; rachat d’environ 227,7 M$ de nominal des convertibles 2030 pour environ 608,2 M$ et d’environ 316,6 M$ des convertibles 2029 pour environ 1 024,2 M$. Le 10-K comptabilise ce rachat en conversion induite, avec une charge de 111,8 M$.'],
    ['2026-03-04', '8-K', '0001140361-26-007905', 'ny20064909x3_8k.htm', 'mar26-8k.htm',
      'Accords d’achat de GPU et d’équipements avec Dell Canada (environ 2,3 Md$) et Dell USA (environ 1,2 Md$), livrés au second semestre 2026 et payables dans les trente jours de chaque expédition ; IREN garantit sans condition les obligations de ses filiales acheteuses.'],
    ['2026-08-04', '8-K', '0001140361-26-031053', 'ny20079234x2_8k.htm', 'aug26-8k.htm',
      'Supplément de prospectus de revente de jusqu’à 11 981 668 actions par les anciens actionnaires de Mirantis : revente secondaire d’actions déjà émises pour l’acquisition, sans nouvelle émission.'],
    ['2026-05-14', '8-K', '0001140361-26-021285', 'ef20073507_8k.htm', 'may26-8k-notes.htm',
      'Acte d’émission des convertibles de 3,0 Md$ à 1,00 % échéance 2033 : obligations senior non garanties, prix de conversion initial de 73,07 $ selon le 10-K, options plafonnées pour 201,3 M$.'],
  ],
  needles: {
    shares: [0, ['394,058,648 Ordinary shares outstanding']],
    atm: [0, ['up to $6 billion in Ordinary shares', '47,165,838 Ordinary shares under the Sales Agreement for aggregate gross proceeds of $2,492.1 million']],
    debt: [0, ['$7,976.0 million principal amount of outstanding indebtedness']],
    horizon10k: [0, ['Horizon 1 was delivered to, and accepted by, Microsoft in August 2026']],
    concentration: [0, ['significant customer concentration']],
    mining: [0, ['installed Bitcoin mining capacity was approximately 23.2 EH/s']],
    results: [1, ['$128.8m', '$4bn contracted ARR for 2026 capacity', '$1bn ARR operating today', 'recognized revenue may be materially lower']],
    blueowl: [1, ['$2.4bn financing led by Blue Owl']],
    msft: [2, ['total contract value of approximately $9.7 billion, including a 20% prepayment', 'approximately $5.8 billion']],
    horizon: [3, ['Horizon 1 has been delivered to and accepted by Microsoft']],
    notes: [4, ['1.00% convertible senior notes due 2033', '32.5% conversion premium', '$110.30 per share']],
    gpufin: [5, ['5.96% senior notes due December 31, 2031', 'term SOFR plus a margin of 2.25%']],
    dell: [6, ['approximately $1.6bn', 'from $3.7bn to $4.4bn']],
    fleet: [7, ['over 50,000 NVIDIA B300 GPUs', 'at-the-market equity program']],
    mirantis: [8, ['approximately 12.6m ordinary shares']],
    nvclient: [0, ['five-year cloud services contract with NVIDIA', 'substantial majority of our contracted revenue']],
    nvrights: [0, ['up to 30,000,000 of the Company’s Ordinary shares at an exercise price of $ 70.00 per share', 'expire on May 7, 2031']],
    eqoffer: [0, ['39,699,102 Ordinary shares in a registered direct offering at a price of $ 41.12 per share', 'Equity Offering, net of issuance costs 39,699,102 1,631,451']],
    atmfy: [0, ['at-the-market offering, net of issuance costs 70,206,940 3,058,036', 'up to $6.0 billion of its Ordinary shares']],
    repurchase: [0, ['$544.3 million aggregate principal amount', '$1,632.4 million', 'inducement expense of $ 111.8 million']],
    convprices: [0, ['Initial conversion price $ 16.81 $ 13.64 $ 85.63 $ 51.40 $ 51.40 $ 73.07', 'Carrying value as of June 30, 2026 $ 207,621 $ 228,343']],
    convcaps: [0, ['Short strike price $ 120.18 $ 82.24 $ 82.24 $ 110.30']],
    settle: [0, ['cash, ordinary shares, or a combination thereof', 'share price trigger under the conversion conditions for our 2030 Convertible Notes and 2029 Convertible Notes was met']],
    sharehist: [0, ['380,193,608 and 258,103,209 shares issued and outstanding']],
    antidil: [0, ['Stock options 5,504,194', 'Restricted stock units 23,250,808']],
    recourse: [0, ['Total recourse debt $ 6,767,649', 'Total non-recourse debt $ 938,000']],
    gpufin10k: [0, ['$ 1,545 million senior secured delayed draw term loan', 'DDTL Facility December 31, 2031 7.12 % $ 413,000']],
    guarantee: [0, ['net of any disposition proceeds realized from the sale of the GPUs', 'any upfront amount owed to Microsoft on termination']],
    icfr: [0, ['maintained, in all material respects, effective internal control over financial reporting as of June 30, 2026', 'subsequently remediated as of June 30, 2025']],
    dep5: [0, ['straight-line basis over an estimated useful life of 5 years', 'residual value of our deployed equipment may be shorter or lower']],
    sga: [0, ['$449.1 million and $136.5 million']],
    headcount: [0, ['we had 685 employees globally', 'approximately 580 personnel through the Mirant']],
    gpuleases: [0, ['approximately $102 million under a 36-month lease', 'approximately $96 million under a 24-month lease', 'approximately $200 million to finance a portion of the Group’s GPU orders under a 24-month lease']],
    dscr: [5, ['at least 1.05:1.00']],
    dec: [9, ['39,699,102 ordinary shares in a registered direct offering at a price of $41.12 per share', '$82.24 per share', '$201.0 million']],
    dellmar: [10, ['approximately $2.3 billion', 'approximately $1.2 billion', 'unconditionally guarantee']],
    resale: [11, ['11,981,668']],
    maynotes: [12, ['1.00% Convertible Senior Notes due 2033']],
  },
  score: { business: 22, technical: -10, capital: -8, calendar: -6, dilution: -12, risk: 60 },
  riskScoreReason: 'Jugement qualitatif sur dix : contrat Microsoft de 9,7 Md$ et revenu annualisé contracté de 4 Md$, mais exécution de quatre déploiements à livrer d’ici le début 2027, 8,0 Md$ de dette en principal, flux de trésorerie libre négatif, programme « at-the-market » de 6 Md$ déjà tiré à 2,5 Md$, bêta supérieur à quatre, positions vendeuses au-dessus de vingt pour cent du flottant et résultats attendus le 5 novembre.',
  compose: c => {
    const { fr, usd, pct, sgn, close, prev, bars, N, tech, st, adv, ret, G$, marketCap, ev, scn, entry, stop, tp1, tp2, rr1, rr2, ref, market, docs, raw, lv, nb, peerStat, extra } = c;
    const bar = d => bars.find(b => b[0] === d);
    const d0828 = bar('2026-08-28'), d0908 = bar('2026-09-08');
    const nbisEvRev = peerStat('NBIS', 'enterpriseToRevenue'), crwvEvRev = peerStat('CRWV', 'enterpriseToRevenue'), cifrEvRev = peerStat('CIFR', 'enterpriseToRevenue'), wulfEvRev = peerStat('WULF', 'enterpriseToRevenue');
    const finraSi = extra.instrument.data.items.find(x => x.type === 'instrument_short_interest');
    const ctb = extra.signals.results[0].squeeze.components.find(x => x.name === 'ctb').value;
    const gaps = (() => { const g = []; for (let i = N - 249; i <= N; i++) g.push(Math.abs(bars[i][1] / bars[i - 1][4] - 1)); return { n: g.length, g5: g.filter(x => x >= 0.05).length, g10: g.filter(x => x >= 0.1).length, max: Math.max(...g) * 100 }; })();
    const vols = bars.slice(N - 19, N + 1).map(b => b[5]).sort((x, y) => x - y), medVol = (vols[9] + vols[10]) / 2;
    const d0827 = bar('2026-08-27'), gap0828 = pct(d0828[1], d0827[4]);
    const evRev = ev / G$.rev;
    const netDebt = G$.debt - G$.cash;
    const twoDay = pct(close, bars[N - 2][4]);
    return {
      meta: { lang: 'fr', dir: 'ltr', level: 'intermediate', tags: ['us', 'equities', 'ai-chain', 'ai', 'speculative'], grade: 'C', date: '2026-10-09', dateDisplay: '9 octobre 2026', version: 3, status: 'no-trade', assetType: 'stock', levelsCloseDate: c.REF,
        description: 'IREN : ancien mineur de bitcoin devenu fournisseur de cloud IA, contrat Microsoft de 9,7 Md$ et 4 Md$ de revenu annualisé contracté, mais 8 Md$ de dette, dilution continue et perte nette de 703 M$. Close du 8 octobre, aucun ordre.',
        ogDescription: 'IREN : 4 Md$ de revenu annualisé contracté et Microsoft comme client, mais 8 Md$ de dette, ATM de 6 Md$ et titre sous toutes ses moyennes. Aucun ordre.',
        lastMcpRefresh: raw.status.captured_at, levelsVerifiedAt: raw.status.captured_at,
        statusHistory: [...(c.archive.meta.statusHistory || []), { at: raw.status.captured_at, from: 'wait', to: 'no-trade', note: 'refonte v3 du 9 octobre au close du 8 : le plan du 28 août, en attente, n’a jamais été rendu exécutable ; titre à ' + usd(close) + ' après une baisse de deux séances commune aux neoclouds, sous ses moyennes à vingt, cinquante et deux cents séances, résultats attendus le 5 novembre ; aucun ordre', close }] },
      header: { ticker: 'IREN', name: 'IREN Limited', exchange: 'NASDAQ', sector: 'Cloud IA et centres de données (ancien mineur de bitcoin)', price: close, changePct: pct(close, prev),
        badges: [{ text: 'AUCUN ORDRE — SOUS TOUTES LES MOYENNES', color: 'amber' }, { text: 'Chaîne IA — fournisseur de capacité GPU', color: 'purple' }],
        metrics: { marketCap: fr(marketCap / 1e9, 2) + ' Md$', volume: fr(bars[N][5] / 1e6, 1) + ' M', evRevenue: fr(evRev, 1) + '×' }, halalStatus: 'unknown' },
      verdict: { score: 46, conviction: 'Low', bias: 'Neutral',
        confidence: 'Note C (score additif de 46 sur 100) : elle reflète la grille v3, qui crédite des contrats signés et une exécution vérifiée (Horizon 1 accepté, contrôle interne efficace) mais retranche technique, dilution et calendrier ; elle ne traduit aucune amélioration des comptes depuis la version D+ du 28 août, établie avec l’ancienne grille. Score éditorial non prédictif. Les chiffres d’entreprise viennent des dépôts SEC et des données XBRL officielles ; les niveaux, du close certifié du 8 octobre.',
        summary: 'IREN a cessé d’être un mineur de bitcoin qui loue un peu de calcul : c’est désormais un fournisseur de cloud IA dont deux clients, Microsoft (9,7 Md$ sur cinq ans) et NVIDIA (3,4 Md$ sur cinq ans), pèsent l’essentiel du revenu contracté. NVIDIA est aussi son fournisseur de GPU et détient des droits sur 30 millions d’actions à 70 $. Le premier des quatre déploiements Microsoft a été livré en août, et la société revendique 4 Md$ de revenu annualisé contracté pour 2026. Les comptes ne suivent pas encore : 707 M$ de chiffre d’affaires sur l’exercice, dont seulement 129 M$ de cloud IA, une perte nette de 703 M$ après la dépréciation du matériel de minage, et une construction financée par 8 Md$ de dette, six séries de convertibles et des émissions d’actions qui ont porté le capital de 258 à 394 millions d’actions en quatorze mois. À ' + usd(close) + ', après ' + sgn(twoDay, 1) + ' en deux séances — un repli partagé par Nebius, CoreWeave et Cipher —, le titre est sous ses moyennes à vingt, cinquante et deux cents séances, à moins d’un mois des résultats du 5 novembre. Aucun ordre : le contrat est réel, mais la conversion du revenu annualisé en revenu comptable reste à démontrer.',
        whyBuy: [
          'Microsoft et NVIDIA sont clients : contrats de cinq ans d’environ 9,7 Md$ (prépaiement de 20 % compris) et 3,4 Md$ ; Horizon 1, premier des quatre déploiements de 50 MW à Childress, a été livré et accepté en août 2026.',
          'La société revendique 4 Md$ de revenu annualisé contracté pour sa capacité 2026 et 1 Md$ déjà en exploitation au 26 août, avec une capacité 2026 « largement vendue ».',
          'Les revenus cloud IA ont été multipliés par près de huit sur l’exercice, de 16,4 M$ à 128,8 M$, et ont plus que doublé d’un trimestre à l’autre à 70,5 M$ au quatrième trimestre.',
          'Le financement des GPU de Microsoft passe par une filiale dédiée : 2,1 Md$ d’obligations garanties à 5,96 % et un prêt à tirage différé, adossés aux GPU et aux flux du contrat, avec une garantie de la société mère limitée.'],
        whyAvoid: [
          'La perte nette atteint 702,6 M$ sur l’exercice et la perte opérationnelle 1 046,7 M$, après 638,8 M$ de dépréciations du matériel de minage mis hors service.',
          'La dette atteint 7 976,0 M$ en principal au 30 juin ; convertibles, financements de GPU et location-financement se cumulent pendant que la construction consomme la trésorerie.',
          'Le capital est passé de 258,1 millions d’actions au 30 juin 2025 à 394,1 millions au 14 août 2026 (+52,7 %), et environ 186 millions d’actions supplémentaires restent potentiellement émissibles (convertibles, droits NVIDIA, unités et options).',
          'La base de coûts précède les revenus : frais commerciaux et administratifs de 449,1 M$ contre 136,5 M$ un an plus tôt, 685 salariés au 30 juin 2026 plus environ 580 apportés par Mirantis en août, EBITDA ajusté du quatrième trimestre réduit à 19,2 M$.',
          'Le revenu annualisé n’est pas du chiffre d’affaires : la société écrit elle-même que le revenu comptabilisé peut être sensiblement inférieur, et trois déploiements Microsoft restent à livrer d’ici le début 2027.'],
        controlChecklist: [
          { label: 'Historique de cours', status: 'pass', statusLabel: 'Trois cents séances continues', evidence: 'Série quotidienne certifiée au close du 8 octobre.', action: 'Niveaux et moyennes calculés sur cette seule série.' },
          { label: 'Structure du capital', status: 'warn', statusLabel: 'Dette lourde et dilution active', evidence: '7 976,0 M$ de dette en principal, six séries de convertibles, droits NVIDIA sur 30 millions d’actions, supplément « at-the-market » de 6 Md$ tiré à 2,49 Md$, lus dans le 10-K et les 8-K.', action: 'Relire chaque nouveau dépôt de financement avant toute entrée ; raisonner en actions pleinement diluées.' },
          { label: 'Point d’entrée', status: 'warn', statusLabel: 'Sous les moyennes, repli sectoriel en cours', evidence: 'Clôture à ' + usd(close) + ', sous les moyennes à vingt, cinquante et deux cents séances, après ' + sgn(twoDay, 1) + ' en deux séances ; résultats attendus le 5 novembre.', action: 'Aucun ordre au cours actuel ; attendre une base et le point d’étape des résultats.' }] },
      business: { theme: 'Fournisseur de cloud IA verticalement intégré, issu du minage de bitcoin',
        overview: '<p>IREN, ex-Iris Energy, possède ses terrains, ses raccordements électriques et ses centres de données en Amérique du Nord, avec des projets en Australie et en Espagne. Pendant des années, ces mégawatts ont servi à miner du bitcoin. Depuis 2025, la société les réaffecte au calcul pour l’intelligence artificielle : elle achète des GPU NVIDIA, les installe dans ses propres bâtiments et vend des heures de calcul à des clients, du bare-metal pour un hyperscaler jusqu’au service géré pour une jeune pousse. L’acquisition de Mirantis en août ajoute une couche logicielle d’orchestration.</p><p>Le tournant est le contrat signé avec Microsoft en novembre 2025 : environ 9,7 Md$ sur cinq ans, avec 20 % de prépaiement, servis par quatre déploiements de 50 MW refroidis par liquide sur le campus de Childress, au Texas. Le premier, Horizon 1, a été livré et accepté en août 2026 ; les trois suivants sont attendus au quatrième trimestre, avec des délais de grâce jusqu’au début du deuxième trimestre 2027. S’y ajoute, depuis mai 2026, un contrat de services cloud de cinq ans d’environ 3,4 Md$ avec NVIDIA pour ses propres charges d’IA et de recherche. Selon le 10-K, ces deux contrats représentent « la majorité substantielle » du revenu contracté : Cohere, Perplexity ou Figure AI élargissent la clientèle mais ne changent pas cette concentration. NVIDIA occupe ainsi trois positions à la fois — fournisseur des GPU, client et futur actionnaire potentiel, avec des droits sur 30 millions d’actions à 70 $ acquis au rythme des GPU livrés. La direction revendique 4 Md$ de revenu annualisé contracté pour 2026 et 1 Md$ déjà en exploitation.</p><p>Le revers est double. D’abord comptable : le revenu annualisé est un indicateur de gestion, pas du chiffre d’affaires, et l’exercice clos le 30 juin n’a produit que 128,8 M$ de revenus cloud IA contre 578,2 M$ de minage, avec une perte nette de 702,6 M$ due à la mise au rebut des machines de minage. Ensuite financier : chaque mégawatt converti exige des GPU payés d’avance ou presque. Sur l’exercice, la société a levé 6,3 Md$ de convertibles, des financements de GPU de plusieurs milliards et 4,7 Md$ d’actions (programme « at-the-market » et offre directe enregistrée de décembre 2025). La thèse se joue donc sur un calendrier : livrer à temps, faire accepter chaque tranche, et laisser les loyers rattraper la dette.</p>',
        moat: 'L’avantage tient à ce qui ne se construit pas vite : des sites déjà raccordés à une électricité abondante et renouvelable, des bâtiments conçus en interne et une équipe capable de livrer un déploiement de 50 MW refroidi par liquide accepté par Microsoft. Il reste fragile : le GPU est une marchandise qui se déprécie vite, les clients peuvent arbitrer entre fournisseurs, et la société dépend des marchés de capitaux pour financer chaque nouvelle vague de matériel.',
        segments: [
          { name: 'Services cloud IA', revenue: '128,8 M$ sur l’exercice 2026', pct: 'Moteur de la thèse', description: 'Location de grappes de GPU à Microsoft, à NVIDIA, à un laboratoire d’IA de pointe et à des entreprises ; 70,5 M$ au seul quatrième trimestre.' },
          { name: 'Minage de bitcoin', revenue: '578,2 M$ sur l’exercice 2026', pct: 'En démantèlement', description: 'Capacité installée d’environ 23,2 EH/s au 30 juin, progressivement mise hors service pour libérer puissance et bâtiments.' },
          { name: 'Logiciel (Mirantis)', revenue: 'Consolidé depuis août 2026', pct: 'Complément', description: 'Orchestration de charges IA et services gérés, acquis contre environ 12,6 millions d’actions.' }],
        sourceRefs: [ref(0), ref(1), ref(2)],
        coverageMatrix: [
          { facet: 'Cours et historique', status: 'COUVERT', decision: 'Trois cents séances continues, close certifié ; base des niveaux.' },
          { facet: 'Résultats et guidance', status: 'COUVERT — PRIMAIRE', decision: 'Communiqué du 27 août et 10-K ; prochaine publication au 5 novembre, source calendaire unique, non confirmée par l’émetteur.' },
          { facet: 'Agrégats GAAP', status: 'COUVERT — XBRL', decision: 'Exercice 2026 complet clos le 30 juin 2026, lu dans les données XBRL officielles.' },
          { facet: 'Capital et dilution', status: 'COUVERT — PRIMAIRE', decision: 'Dette, convertibles, financements de GPU et programme « at-the-market » lus dans le 10-K et les 8-K ; dette et capitaux propres séparés.' },
          { facet: 'Comparables et transmission', status: 'COUVERT — LOCAL', decision: 'Corrélations recalculées sur barres certifiées ; Hut 8, CleanSpark et Bitdeer écartés faute de séances complètes.' },
          { facet: 'Initiés', status: 'COUVERT', decision: 'Uniquement des attributions d’actions au 1er juillet ; aucun achat ni vente de marché relevé sur douze mois.' },
          { facet: 'Options', status: 'INDISPONIBLE', decision: 'Chaîne d’options non disponible à la collecte ; non utilisée.' },
          { facet: 'Positions vendeuses et coût d’emprunt', status: 'PARTIEL', decision: 'Positions vendeuses datées au règlement FINRA du 15 septembre 2026 ; coût d’emprunt relevé par le seul composite de signaux.' },
          { facet: 'Sentiment et tendances de recherche', status: 'INDISPONIBLE', decision: 'Aucune mesure qualifiée à la collecte ; non utilisé.' }] },
      news: [
        { date: '2025-11-03', title: 'Contrat de 9,7 Md$ avec Microsoft', impact: 'positive', detail: 'Contrat de services cloud GPU de cinq ans, prépaiement de 20 % compris, servi par quatre déploiements de 50 MW à Childress ; achat corrélatif de GPU et d’équipements à Dell pour environ 5,8 Md$.', source: 'IREN — SEC', sourceUrl: docs[2].url },
        { date: '2025-12-08', title: 'Offre directe de 39,7 millions d’actions et rachat de convertibles', impact: 'negative', detail: 'Émission de 2,3 Md$ de convertibles 2032 et 2033 et vente de 39 699 102 actions à 41,12 $ pour racheter une partie des convertibles 2029 et 2030 pour environ 1 632,4 M$ ; le 10-K comptabilise une charge de conversion induite de 111,8 M$.', source: 'IREN — SEC', sourceUrl: docs[9].url },
        { date: '2026-08-13', title: 'Horizon 1 livré et accepté par Microsoft', impact: 'positive', detail: 'Premier des quatre déploiements de 50 MW accepté par Microsoft, statut NVIDIA Exemplar Cloud sur GB300 NVL72 ; les trois suivants sont attendus d’ici la fin de 2026.', source: 'IREN — SEC', sourceUrl: docs[3].url },
        { date: '2026-08-27', title: 'Résultats annuels : 4 Md$ de revenu annualisé contracté, perte nette de 703 M$', impact: 'negative', detail: 'Revenus cloud IA de 128,8 M$ sur l’exercice, revenus de minage de 578,2 M$, perte nette de 702,6 M$ après 638,8 M$ de dépréciations ; EBITDA ajusté du quatrième trimestre à 19,2 M$. Le titre a ouvert en baisse de ' + fr(Math.abs(gap0828), 1) + ' % le lendemain et clôturé en baisse de 12,5 %.', source: 'IREN — SEC', sourceUrl: docs[1].url },
        { date: '2026-10-08', title: 'Les neoclouds décrochent ensemble', impact: 'negative', detail: 'IREN clôture à ' + usd(close) + ' après ' + sgn(twoDay, 1) + ' en deux séances, dans un repli commun à Nebius, CoreWeave et Cipher Mining ; le titre repasse sous ses moyennes à vingt (' + usd(tech.ema20) + '), cinquante (' + usd(tech.ema50) + ') et deux cents séances (' + usd(tech.ema200) + ').', source: 'Barres certifiées', sourceUrl: c.evidenceUrl }],
      fundamentals: { rows: [
          { metric: 'Revenus cloud IA de l’exercice 2026', value: '128,8 M$', signal: 'Contre 16,4 M$ un an plus tôt, communiqué du 27 août', signalColor: 'green', _src: 1 },
          { metric: 'Revenus cloud IA du 4e trimestre', value: '70,5 M$', signal: 'Contre 33,6 M$ au trimestre précédent', signalColor: 'green', _src: 1 },
          { metric: 'EBITDA ajusté du 4e trimestre', value: '19,2 M$', signal: 'Mesure non-GAAP publiée, en recul face à 59,5 M$ au trimestre précédent', signalColor: 'amber', _src: 1 },
          { metric: 'Chiffre d’affaires GAAP sur l’exercice 2026', value: fr(G$.rev / 1e6, 1) + ' M$', signal: 'Exercice clos le 30 juin 2026 (XBRL SEC), minage encore majoritaire', signalColor: 'blue', _src: 'gaap' },
          { metric: 'Résultat opérationnel GAAP sur l’exercice', value: fr(G$.ebit / 1e6, 1) + ' M$', signal: 'Perte après dépréciations du matériel de minage, exercice clos le 30 juin 2026', signalColor: 'red', _src: 'gaap' },
          { metric: 'Résultat net GAAP sur l’exercice', value: fr(G$.ni / 1e6, 1) + ' M$', signal: 'Exercice clos le 30 juin 2026, contre un bénéfice de 86,9 M$ un an plus tôt', signalColor: 'red', _src: 'gaap' },
          { metric: 'EBITDA GAAP sur l’exercice', value: fr(G$.ebitda / 1e6, 1) + ' M$', signal: 'Négatif : aucun multiple d’EBITDA GAAP n’est significatif', signalColor: 'red', _src: 'gaap' },
          { metric: 'Flux de trésorerie opérationnel sur l’exercice', value: fr(G$.ocf / 1e9, 2) + ' Md$', signal: 'Gonflé par les prépaiements de clients, exercice clos le 30 juin 2026', signalColor: 'amber', _src: 'gaap' },
          { metric: 'Investissements (capex) sur l’exercice', value: fr(G$.capex / 1e9, 2) + ' Md$', signal: 'GPU et centres de données, exercice clos le 30 juin 2026', signalColor: 'red', _src: 'gaap' },
          { metric: 'Flux de trésorerie libre sur l’exercice', value: fr(G$.fcf / 1e6, 1) + ' M$', signal: 'Flux opérationnel − investissements, malgré les prépaiements', signalColor: 'red', _src: 'gaap' },
          { metric: 'Dette au 30 juin (dette + location-financement)', value: fr(G$.debt / 1e9, 2) + ' Md$', signal: 'Valeur comptable au bilan du 10-K ; 7,98 Md$ en principal', signalColor: 'red', _src: 'gaap' },
          { metric: 'Trésorerie et équivalents au 30 juin', value: fr(G$.cash / 1e9, 2) + ' Md$', signal: 'Hors 1,72 Md$ de trésorerie soumise à restriction, bilan du 10-K', signalColor: 'blue', _src: 'gaap' },
          { metric: 'EV/revenus GAAP', value: fr(evRev, 1) + '×', signal: 'Valeur d’entreprise au close du 2026-10-08, 394,1 M actions, sur revenus GAAP de l’exercice 2026', signalColor: 'amber', source: 'Clôture certifiée et XBRL SEC', comparison: 'Le dénominateur est à 82 % du minage en démantèlement : ce multiple surestime ce que paie le marché pour l’activité cloud. Repères pairs : Nebius à ' + fr(nbisEvRev, 1) + '× et CoreWeave à ' + fr(crwvEvRev, 1) + '× leurs revenus (statistiques courantes, non point-in-time). Versus les 4 Md$ de revenu annualisé contracté revendiqués, la valeur d’entreprise en représente environ ' + fr(ev / 4e9, 1) + ' fois. La valeur d’entreprise combine les actions du 14 août et le bilan du 30 juin ; les financements engagés non tirés au 30 juin (environ 2,7 Md$ sur le prêt et les obligations du contrat Microsoft) l’alourdiraient une fois tirés.', _src: 'market', _peers: ['NBIS', 'CRWV'], _peerField: 'enterpriseToRevenue' },
          { metric: 'EV/revenus — scénario de re-cotation basse (hypothèse éditoriale)', value: fr(scn.price, 2) + ' $ par action', signal: 'Scénario : multiple ramené à douze fois les revenus GAAP de l’exercice 2026, dette et trésorerie du 30 juin inchangées, soit ' + fr(scn.downside_pct, 0) + ' % sous le close du 2026-10-08', signalColor: 'red', source: 'Clôture certifiée et XBRL SEC', comparison: 'Hypothèse d’un marché qui cesserait de payer le revenu annualisé futur et ne retiendrait que les revenus comptabilisés, dont l’essentiel vient d’un minage en démantèlement : ce n’est pas un objectif, mais la mesure de ce qui reste à prouver. Versus CoreWeave à ' + fr(crwvEvRev, 1) + '× ses revenus, douze fois se situe juste sous le multiple de CoreWeave, le bas de la fourchette ; les pairs directs issus du minage se paient bien plus cher, Cipher à ' + fr(cifrEvRev, 1) + '× et TeraWulf à ' + fr(wulfEvRev, 1) + '× (mêmes statistiques non point-in-time).', _src: 'market', _peers: ['CRWV', 'CIFR', 'WULF'], _peerField: 'enterpriseToRevenue' }],
        sourceRefs: [ref(0), ref(1), market('fondamentaux et statistiques')] },
      earnings: { quarters: [],
        beatNote: 'Exercice 2026 clos le 30 juin : chiffre d’affaires de 707,0 M$, dont 128,8 M$ de cloud IA (contre 16,4 M$) et 578,2 M$ de minage ; perte nette de 702,6 M$ après 638,8 M$ de dépréciations ; EBITDA ajusté de 245,7 M$ sur l’exercice mais de 19,2 M$ seulement au quatrième trimestre, la société recrutant avant la montée des revenus. La société ne donne pas de guidance de chiffre d’affaires classique : son indicateur de visibilité est le revenu annualisé, 4 Md$ contractés pour la capacité 2026 et 1 Md$ en exploitation au 26 août, avec une capacité 2026 largement vendue et des discussions avancées pour 2027. Aucune date de prochaine publication n’est confirmée par l’émetteur ; le 5 novembre provient d’une source calendaire unique.',
        nextEarnings: 'Publication du premier trimestre de l’exercice 2027 attendue le 5 novembre 2026 après la clôture (16 h, heure de New York) selon une source calendaire unique, non confirmée par l’émetteur ; séance exposée au gap : le 6 novembre.',
        sourceRefs: [ref(1)] },
      capitalStructure: { sharesOutstanding: '394 058 648 actions ordinaires au 14 août 2026, contre 380 193 608 au 30 juin 2026 et 258 103 209 au 30 juin 2025, soit +52,7 % en quatorze mois (10-K)',
        sharesAuthorized: 'Aucun plafond d’actions autorisées : le 10-K précise que le droit australien ne connaît ni capital autorisé limité ni valeur nominale ; la capacité de dilution matérielle passe par le programme « at-the-market », les convertibles et les émissions d’acquisition décrits ci-dessous.',
        dilutionRisk: 'high',
        shareHistory: 'Le capital est passé de 258,1 millions d’actions au 30 juin 2025 à 380,2 millions au 30 juin 2026, puis 394,1 millions au 14 août. La dilution vient de cinq sources. Un : le programme « at-the-market », qui a vendu 70,2 millions d’actions sur l’exercice (3 058,0 M$ nets) ; le supplément de prospectus du 4 mars 2026 autorise 6,0 Md$, dont 2 492,1 M$ bruts déjà utilisés, soit environ 3,5 Md$ restants par différence, plafond que le conseil peut relever. Deux : l’offre directe enregistrée de décembre 2025, 39 699 102 actions à 41,12 $ (1 631,5 M$ nets), qui a servi à racheter 544,3 M$ de nominal des convertibles 2029 et 2030 pour 1 632,4 M$, avec une charge de conversion induite de 111,8 M$. Trois : six séries de convertibles, réglables en numéraire, en actions ou en combinaison au choix d’IREN — 2029 (3,50 %, conversion à 13,64 $, environ 233,4 M$ restants), 2030 (3,25 %, 16,81 $, environ 212,3 M$), 2031 (0 %, 85,63 $, 1,0 Md$), 2032 (0,25 %, 51,40 $, 1,15 Md$), échéance juin 2033, émise en décembre 2025 (1,00 %, 51,40 $, 1,15 Md$) et échéance décembre 2033, émise en mai 2026 (1,00 %, 73,07 $, 3,0 Md$). Les options plafonnées ne couvrent que l’écart entre conversion et plafond (82,24 $ pour les échéances 2032 et juin 2033, 110,30 $ pour l’échéance décembre 2033, 120,18 $ pour 2031). Quatre : les droits NVIDIA sur 30 millions d’actions à 70,00 $. Cinq : les actions de rémunération (23,3 millions d’unités et 5,5 millions d’options exclues du résultat dilué) et d’acquisition (environ 12,6 millions pour Mirantis, dont 11 981 668 enregistrées pour revente). Aux prix de conversion initiaux, les convertibles représentent environ 127 millions d’actions ; avec les droits NVIDIA, les unités et les options, environ 186 millions, soit environ 47 % des 394,1 millions en circulation. À ' + usd(close) + ', seules les séries 2029 et 2030 (environ 29,7 millions d’actions, seuil de conversion atteint au 30 juin) sont dans la monnaie ; IREN peut toutefois les régler en numéraire.',
        warrants: [{ series: 'Droits d’investissement NVIDIA', type: 'Fournisseur', strike: 70, shares: '30 000 000 actions', issued: '2026-05-07', expiration: '2031-05-07', dilutionPct: fr(30e6 / (394058648 + 30e6) * 100, 1) + ' % du capital après exercice', status: 'OTM', cashless: false, note: 'Acquis par tranches selon le volume de GPU livrés par NVIDIA ; juste valeur à l’octroi de 793,4 M$' }],
        atm: { active: true, authorized: 'Jusqu’à 6 Md$ d’actions ordinaires (prospectus en vigueur, 10-K)', used: '47 165 838 actions vendues pour 2 492,1 M$ bruts au 14 août 2026', remaining: 'Environ 3,5 Md$ par différence (6,0 Md$ − 2,49 Md$) sous le supplément du 4 mars 2026, plafond que le conseil peut relever' },
        sourceRefs: [ref(0), ref(9), ref(4), ref(11)] },
      filingsReview: { summary: 'Treize pièces décisionnelles ouvertes et hachées, sur un inventaire de 44 formulaires hors déclarations d’initiés. Le 10-K conclut à un contrôle interne efficace au 30 juin 2026, avec une opinion sans réserve de l’auditeur et sans paragraphe de continuité d’exploitation ; la faiblesse matérielle de l’exercice 2024 a été remédiée au 30 juin 2025. Ils séparent trois réalités : le carnet commercial, réel mais concentré (Microsoft et NVIDIA, laboratoire d’IA de pointe) ; le financement, massif et continu (convertibles, financements de GPU, « at-the-market ») ; et la sortie du minage, coûteuse en dépréciations. Aucun rapport de vendeur à découvert activiste ni fonds hostile identifié dans la période ; les Schedule 13G relevés sont passifs.',
        filings: docs.map(d => ({ date: d.date, form: d.form, accession: d.accession, finding: d.finding, url: d.url })),
        contrarianRisks: [
          'Le revenu annualisé de 4 Md$ est un indicateur de gestion calculé sur des GPU sous contrat ; la société précise elle-même que le revenu comptabilisé peut être sensiblement inférieur.',
          'La garantie de la société mère sur le financement Microsoft est limitée : si Microsoft résilie valablement une tranche financée sans repreneur, la société mère garantit la dette de cette tranche, nette de la revente des GPU, plus tout montant initial dû à Microsoft ; un retard de livraison remonte ainsi jusqu’à l’actionnaire.',
          'Les GPU achetés aujourd’hui se déprécient vite : un contrat de cinq ans adossé à du matériel dont la valeur s’érode laisse peu de marge si les prix de l’heure de calcul baissent.',
          'Microsoft et NVIDIA représentent la majorité substantielle du revenu contracté ; NVIDIA est en même temps fournisseur, client et titulaire de droits sur 30 millions d’actions acquis au volume de GPU achetés : la relation est circulaire.',
          'Sur 7 976,0 M$ de dette en principal, 6 767,6 M$ sont avec recours sur la société mère, 938,0 M$ (financement Microsoft) sans recours, plus 270,4 M$ de passif de location-financement comptabilisé au 30 juin. S’y rattachent en partie des financements de GPU par location signés en août et novembre 2025 (environ 102 M$ sur 36 mois, environ 96 M$ et environ 200 M$ sur 24 mois), qui n’avaient pas tous démarré au 30 juin.',
          'Le programme « at-the-market » peut être activé à tout moment : 70,2 millions d’actions vendues sur l’exercice, environ 3,5 Md$ de capacité restante.'] },
      technicals: { rsi14: +tech.rsi14.toFixed(2), macd: +tech.macd.toFixed(2), macdSignal: +tech.macdSignal.toFixed(2), ema20: +tech.ema20.toFixed(2), ema50: +tech.ema50.toFixed(2), ema200: +tech.ema200.toFixed(2),
        ma50Type: 'EMA', ma200Type: 'EMA', ma50Available: true, ma200Available: true, atr14: +tech.atr14.toFixed(2),
        badges: ['Sous les moyennes à vingt, cinquante et deux cents séances', 'RSI proche de la survente, MACD sous sa ligne de signal', 'Repli sectoriel des neoclouds'],
        supports: [lv('s1'), lv('s2'), lv('s3')], resistances: [lv('r1'), lv('r2'), lv('r3')],
        setupNote: 'Le titre clôture à ' + usd(close) + ', sous ses moyennes à vingt (' + usd(tech.ema20) + '), cinquante (' + usd(tech.ema50) + ') et deux cents séances (' + usd(tech.ema200) + '), RSI à ' + fr(tech.rsi14, 0) + ', MACD sous zéro et sous sa ligne de signal. Les sommets se font de plus en plus bas depuis le 23 septembre (' + usd(lv('r3')) + '), puis ' + usd(lv('r2')) + ' le 2 octobre et ' + usd(lv('r1')) + ' le 6. Le plus bas du jour, ' + usd(lv('s1')) + ', revient au niveau du lendemain des résultats annuels (' + usd(lv('s2')) + ') ; sous ce niveau, le plus bas sur un an est à ' + usd(lv('s3')) + '. Aucun ordre : les niveaux du plan du 28 août, entrée ' + usd(entry) + ' et stop ' + usd(stop) + ', sont archivés et inactifs. ATR de ' + usd(tech.atr14) + ', soit environ ' + fr(tech.atr14 / close * 100, 1) + ' % du cours par séance.',
        wyckoff: 'Distribution possible depuis le sommet de septembre ; non utilisée pour fixer les niveaux.',
        sourceRefs: [market('barres quotidiennes et indicateurs recalculés')] },
      options: { callOI: 'Non disponible', putOI: 'Non disponible', cpRatio: 'Non disponible', maxPain: 'Non disponible', ivMean: 'Chaîne indisponible à la collecte', skew: 'Non mesuré', unusual: 'Aucune lecture d’options retenue faute de chaîne collectée', sourceRefs: [market('options indisponibles à la collecte')] },
      shortInterest: { siPct: fr(st.shortPercentOfFloat, 2) + ' % du flottant (statistique courante) ; ' + nb(finraSi.shortInterest) + ' actions à la date de règlement FINRA du 15 septembre 2026', daysToCover: fr(finraSi.daysToCover, 2) + ' jours (FINRA, 15 septembre 2026) ; le fournisseur affiche par ailleurs ' + fr(st.shortRatio, 2) + ' jours, autre statistique non datée', ctb: fr(ctb, 2) + ' % annualisé selon le composite de signaux collecté le 9 octobre : emprunt bon marché, aucune tension de prêt', trend: 'Positions vendeuses élevées : plus de vingt pour cent du flottant, environ ' + fr(st.sharesShort / 1e6, 0) + ' millions d’actions. Un rachat forcé après une bonne nouvelle reste possible, mais ce n’est pas une thèse en soi.', squeezeScore: 'Élevé mécaniquement, subordonné à un catalyseur ; non retenu comme thèse principale', sourceRefs: [market('positions vendeuses et coût d’emprunt')] },
      insiders: { signal: 'Aucun achat ni vente de marché par un dirigeant sur douze mois : les seules transactions relevées sont des attributions d’actions au 1er juillet 2026 aux cofondateurs, au directeur financier et aux administrateurs. Les cofondateurs Daniel et William Roberts restent les principaux détenteurs déclarés parmi les initiés.',
        recentTransactions: [],
        sourceRefs: [market('formulaires 4'), ref(0)] },
      macro: { indicators: [{ name: 'Clôture de référence', value: c.REF, signal: usd(close) + ', séance complète' }, { name: 'Rendement cinq séances', value: sgn(ret(5)), signal: 'Descriptif' }, { name: 'Rendement vingt et une séances', value: sgn(ret(21)), signal: 'Descriptif' }],
        regime: 'neutral', impact: 'IREN est sensible à trois facteurs extérieurs : l’appétit du marché pour les fournisseurs de calcul IA, qui fait bouger ensemble Nebius, CoreWeave et les anciens mineurs ; le coût du crédit, qui finance les GPU ; et, de moins en moins, le cours du bitcoin, qui pèse encore sur la part de minage restante. Un doute sur la demande de calcul ou un durcissement du crédit le toucherait plus que la moyenne : le fournisseur de données affiche un bêta de ' + fr(st.beta, 2) + ' (méthodologie non précisée).' },
      risks: { riskScore: 8, riskProfile: 'Very High',
        riskSummary: 'Le risque d’IREN n’est pas la demande — Microsoft et NVIDIA la démontrent — mais l’exécution, la concentration et le financement. Le capital est passé de 258 à 394 millions d’actions en quatorze mois. Trois déploiements Microsoft restent à livrer, chaque vague de GPU exige des milliards avant le premier loyer, et la société finance ce rythme par de la dette, des convertibles et des émissions d’actions. Un retard, une baisse des prix du calcul ou une fermeture du marché du crédit suffisent à faire décrocher un titre déjà très volatil.',
        riskCards: [
          { title: 'Dette et financement', severity: 'critical', icon: 'fa-sack-dollar', points: ['7 976,0 M$ de dette en principal au 30 juin, convertibles et financements de GPU compris.', 'Flux de trésorerie libre négatif sur l’exercice malgré les prépaiements des clients.'], verdict: 'Chaque nouvelle vague de GPU suppose un nouveau financement ; le service de la dette précède les loyers.' },
          { title: 'Dilution structurelle', severity: 'critical', icon: 'fa-money-bill-trend-up', points: ['258,1 millions d’actions au 30 juin 2025, 394,1 millions au 14 août 2026 (+52,7 %).', 'Environ 186 millions d’actions potentielles : six séries de convertibles, droits NVIDIA, unités et options.', '« At-the-market » : environ 3,5 Md$ de capacité restante sous le supplément de mars.'], verdict: 'L’actionnaire existant est dilué en continu ; la vitesse de l’« at-the-market » et le mode de règlement des convertibles sont les variables à suivre.' },
          { title: 'Dépendance à NVIDIA', severity: 'high', icon: 'fa-microchip', points: ['Fournisseur des GPU GB300 et B300 ; ses délais de livraison ont déjà retardé des équipements d’Horizon 1.', 'Client d’un contrat cloud de cinq ans d’environ 3,4 Md$.', 'Titulaire de droits sur 30 millions d’actions à 70,00 $, acquis au volume de GPU livrés, échéance 2031.'], verdict: 'Une renégociation, un retard de livraison ou un changement de stratégie de NVIDIA toucherait à la fois les coûts, les revenus et le capital d’IREN.' },
          { title: 'Exécution et concentration', severity: 'high', icon: 'fa-flask', points: ['Horizons 2 à 4 à livrer d’ici le début du deuxième trimestre 2027, délais de grâce compris.', 'Microsoft et NVIDIA forment la majorité substantielle du revenu contracté (10-K).', 'GPU du contrat Microsoft amortis linéairement sur cinq ans ; le 10-K prévient que leur durée de vie économique et leur valeur résiduelle peuvent être inférieures aux attentes.'], verdict: 'Un retard décale les revenus sans décaler la dette ; si Microsoft résilie une tranche financée sans repreneur, la société mère garantit la dette de la tranche, nette de la revente des GPU.' },
          { title: 'Risque de marché et de séance', severity: 'high', icon: 'fa-rocket', points: ['Bêta de ' + fr(st.beta, 2) + ' selon le fournisseur ; positions vendeuses au-dessus de vingt pour cent du flottant.', 'Sur 250 séances, ' + gaps.g5 + ' ouvertures ont décalé de 5 % ou plus et ' + gaps.g10 + ' de 10 % ou plus, maximum ' + fr(gaps.max, 1) + ' % ; ATR d’environ ' + fr(tech.atr14 / close * 100, 1) + ' % du cours par séance.'], verdict: 'Une position doit rester petite : un écart à l’ouverture peut sauter un stop d’un coup.' }],
        pedagogy: 'IREN illustre l’écart entre un revenu annualisé et un compte de résultat. Le premier — 4 Md$ contractés pour 2026 — multiplie des heures de GPU sous contrat par le nombre d’heures d’une année ; le second n’a enregistré que 128,8 M$ de revenus cloud IA sur l’exercice clos en juin. Le passage de l’un à l’autre dépend de la livraison de chaque déploiement, de son acceptation par le client et du taux d’utilisation. D’ici là, la société finance ses GPU par de la dette et de nouvelles actions. Côté marché, le montant médian échangé atteint ' + nb(adv / 1e6) + ' M$ par séance sur les vingt dernières séances : la liquidité est excellente, mais le gap ne l’est pas. Sur 250 séances, ' + gaps.g5 + ' ouvertures ont décalé de 5 % ou plus (' + fr(gaps.g5 / gaps.n * 100, 0) + ' %), ' + gaps.g10 + ' de 10 % ou plus, avec un maximum de ' + fr(gaps.max, 1) + ' % ; le lendemain des résultats du 27 août, le titre a ouvert à ' + sgn(gap0828, 1) + '. Un stop peut donc être exécuté nettement sous son niveau : la perte réelle se calcule avec ce glissement, pas avec la seule distance au stop, et la taille se fixe à partir d’un budget de perte décidé d’avance, jamais à partir de l’objectif. Ici, la bonne décision est d’attendre une base et les résultats du 5 novembre.' },
      tradeIdea: { status: 'no-trade', archiveReferenceClose: c.archive.meta.levelsCloseDate,
        statusNote: 'Aucun ordre actif. Les niveaux affichés — entrée ' + usd(entry) + ', stop ' + usd(stop) + ', TP1 ' + usd(tp1) + ', TP2 ' + usd(tp2) + ' — sont ceux, archivés, du plan rédigé le 28 août sur la clôture du 27 août, resté en attente et jamais rendu exécutable : inactifs et non exécutables. Pour mémoire, le titre est passé sous la référence de stop dès le 28 août (plus bas à ' + usd(d0828[3]) + ') avant de remonter jusqu’à ' + usd(d0908[2]) + ' le 8 septembre. Aucun nouvel ordre au cours actuel, sous toutes les moyennes et dans un repli sectoriel.',
        entry, stop, tp1, tp2,
        stopPct: pct(stop, entry).toFixed(1) + '%', tp1Pct: '+' + pct(tp1, entry).toFixed(1) + '%', tp2Pct: '+' + pct(tp2, entry).toFixed(1) + '%',
        rr: '1:' + rr1.toFixed(2) + ' TP1 / 1:' + rr2.toFixed(2) + ' TP2',
        entryNote: 'Aucune entrée. Les niveaux du tableau sont archivés et non exécutables. Aucun réexamen avant la publication du 5 novembre. Ensuite, conditions de réexamen, sans ordre : au moins cinq clôtures consécutives au-dessus de ' + usd(lv('s2')) + ', comptées à partir de la séance qui suit la publication du 5 novembre ; une clôture au-dessus de ' + usd(lv('r1')) + ' (dernier sommet décroissant) avec un volume supérieur à la médiane de vingt séances (' + fr(medVol / 1e6, 1) + ' millions d’actions au 8 octobre) ; la livraison d’Horizon 2 confirmée ; aucun nouveau dépôt de financement dilutif d’ampleur. Ne pas acheter une ouverture en gap à plus d’un ATR (' + usd(tech.atr14) + ') au-dessus de ' + usd(lv('r1')) + ', soit ' + usd(lv('r1') + tech.atr14) + '. Liquidité : montant médian échangé de ' + nb(adv / 1e6) + ' M$ par séance sur vingt séances. Toute position devrait rester réduite compte tenu du bêta et du glissement possible à l’ouverture.',
        horizon: 'Aucune position au cours actuel',
        thesis: 'IREN est une histoire de contrats contre bilan. Les contrats — Microsoft pour 9,7 Md$, 4 Md$ de revenu annualisé contracté — sont solides ; le bilan — 8 Md$ de dette, un programme d’actions de 6 Md$ déjà tiré à 2,5 Md$, une perte nette de 703 M$ — l’est beaucoup moins. On n’achète pas ce titre à ' + usd(close) + ', sous toutes ses moyennes et au milieu d’un repli de tout le secteur des neoclouds. Le plan du 28 août n’a jamais été activé ; le prochain se construira, s’il se construit, sur une base au-dessus de ' + usd(lv('s2')) + ', une reprise de ' + usd(lv('r1')) + ' et la preuve que les déploiements Microsoft se transforment en revenus comptabilisés.',
        catalysts: ['Les résultats du 5 novembre après la clôture (séance du 6 exposée au gap) : premier trimestre avec Horizon 1 en revenus et premier point sur la conversion du revenu annualisé.', 'La livraison et l’acceptation d’Horizons 2 à 4 par Microsoft d’ici la fin de 2026.', 'Un financement de GPU par dette de projet plutôt que par l’« at-the-market », qui réduirait la pression dilutive.'],
        invalidation: ['Les niveaux affichés sont archivés et informatifs : aucun transfert vers une exécution actuelle.', 'Un achat au cours actuel, sous toutes les moyennes et dans un repli sectoriel, contredit ce dossier.', 'Une clôture sous ' + usd(lv('s3')) + ', plus bas sur un an, ou une émission d’actions de grande taille aggraverait le diagnostic.'] },
      globalScore: { profile: 'Fournisseur de cloud IA : contrats solides, bilan à crédit',
        keyTakeawaysPositive: ['Contrat Microsoft d’environ 9,7 Md$ sur cinq ans, premier déploiement accepté en août 2026.', '4 Md$ de revenu annualisé contracté pour 2026, 1 Md$ en exploitation au 26 août.', 'Revenus cloud IA multipliés par près de huit sur l’exercice, à 128,8 M$.'],
        keyTakeawaysNegative: ['Perte nette de 702,6 M$ et flux de trésorerie libre négatif sur l’exercice.', '7 976,0 M$ de dette en principal et programme « at-the-market » de 6 Md$ tiré à 2,49 Md$.', 'Titre sous toutes ses moyennes, bêta supérieur à quatre, résultats le 5 novembre.'],
        mindsetTip: 'Un revenu annualisé se lit comme une promesse, pas comme un chiffre d’affaires. Avant de se laisser porter par un grand nom de client, regarder qui paie les GPU — dette et dilution — et attendre que les revenus comptabilisés rattrapent le récit.' },
      social: { platforms: [], sourceRefs: [market('sentiment non retenu faute de mesure qualifiée')] },
      disclaimer: 'Document de recherche éducatif. Ni conseil financier, ni signal de trading. Statut aucun ordre : le plan affiché est archivé et n’a jamais été exécutable.',
    };
  },
  groups: [
    { name: 'Leaders — neoclouds cotés', order: 1, transmission: 'Même métier de location de calcul GPU financé par capitaux externes ; leurs valorisations et leurs conditions de financement fixent la référence du secteur.', rows: [
      ['NBIS', 'leader', 'Neocloud IA coté de grande taille', 'Référence de valorisation des fournisseurs de calcul GPU : un repli de Nebius se transmet aussitôt aux pairs plus petits.'],
      ['CRWV', 'leader', 'Premier neocloud coté par la taille', 'Ses contrats avec les hyperscalers et son coût de financement servent d’étalon à tout le secteur du cloud GPU.']] },
    { name: 'Pairs directs — anciens mineurs passés au calcul IA', order: 1, transmission: 'Même bascule : des sites de minage raccordés réaffectés au calcul haute performance, financés par convertibles et actions.', rows: [
      ['CIFR', 'direct_peer', 'Mineur en conversion vers l’hébergement HPC', 'Même stratégie de conversion des sites électriques ; ses baux avec des hyperscalers et ses émissions éclairent celles d’IREN.'],
      ['WULF', 'direct_peer', 'Hébergeur HPC issu du minage', 'Convertit ses centres vers l’hébergement IA pour de grands locataires ; même dépendance au marché du crédit.'],
      ['CORZ', 'direct_peer', 'Mineur reconverti en hébergeur', 'Hébergement de calcul IA sur d’anciens sites de minage ; baromètre de la valeur accordée aux mégawatts raccordés.'],
      ['APLD', 'direct_peer', 'Bailleur de centres de données IA', 'Construit des campus loués à des hyperscalers et financés à crédit ; même risque de calendrier de mise en service.']] },
    { name: 'Amont — puces, serveurs, alimentation', order: 1, transmission: 'Fournisseurs du matériel qu’IREN achète par milliards : leurs livraisons conditionnent le calendrier des déploiements.', rows: [
      ['NVDA', 'upstream', 'Fournisseur des GPU, client (3,4 Md$) et titulaire de droits sur 30 M d’actions', 'Les GB300 et B300 d’IREN viennent de NVIDIA, qui est aussi client d’un contrat cloud de 3,4 Md$ et titulaire de droits à 70 $ : la relation est circulaire.'],
      ['DELL', 'upstream', 'Intégrateur des systèmes GPU achetés', 'Fournit les systèmes du contrat Microsoft pour environ 5,8 Md$ et ceux du contrat de services gérés pour environ 1,6 Md$.'],
      ['VRT', 'upstream', 'Alimentation et refroidissement', 'Équipements électriques et thermiques des déploiements refroidis par liquide ; goulot de mise en service des centres.']] },
    { name: 'Demande — client documenté et cloud', order: 1, transmission: 'Côté demande : Microsoft est le client nommé du contrat de 9,7 Md$, et les grands clouds fixent le prix de l’heure de calcul.', rows: [
      ['MSFT', 'downstream', 'Client documenté, contrat de 9,7 Md$', 'Client du contrat de cinq ans servi à Childress ; son acceptation de chaque tranche déclenche les revenus et conditionne le financement dédié.'],
      ['ORCL', 'downstream', 'Grand acheteur de capacité IA', 'Contracte de grandes capacités de calcul ; son capex et ses tarifs disent si la demande de location de GPU tient.']] },
    { name: 'Second ordre — actifs numériques', order: 2, transmission: 'Héritage du minage : le bitcoin et les paniers de mineurs bougent encore avec IREN, de moins en moins par l’activité, davantage par le profil des actionnaires.', rows: [
      ['GLXY', 'second_order', 'Actifs numériques et centres de données', 'Acteur des actifs numériques qui investit aussi dans les centres de données IA ; cousin financé sur les mêmes marchés.'],
      ['IBIT', 'sector_proxy', 'Fonds indiciel adossé au bitcoin', 'Contrôle de la part de minage restante : si le bitcoin monte et IREN baisse, la cause est ailleurs que dans le minage.'],
      ['WGMI', 'sector_proxy', 'Panier de mineurs de cryptoactifs', 'Panier des mineurs, dont beaucoup pivotent vers le calcul IA : contrôle du sous-secteur d’origine d’IREN.']] },
    { name: 'Contrôle sectoriel', order: 2, transmission: 'Panier de référence pour séparer le mouvement d’IREN de celui des semi-conducteurs.', rows: [
      ['SMH', 'sector_proxy', 'Panier de semi-conducteurs', 'Contrôle de l’amont : si les puces tiennent et IREN décroche, le repli vient de la couche des fournisseurs de calcul.']] },
  ],
  eventDefault: { leader: 'Aucune publication dans les quatorze jours collectés ; ses financements et contrats restent le signal à suivre', direct_peer: 'Aucune publication dans les quatorze jours collectés ; ses baux et émissions encadrent ceux d’IREN', upstream: 'Aucune publication dans les quatorze jours collectés ; ses livraisons précèdent les déploiements', downstream: 'Aucune publication dans les quatorze jours collectés ; ses investissements fixent la demande de calcul', second_order: 'Aucune publication dans les quatorze jours collectés ; son accès au capital reste à suivre', sector_proxy: 'Panier sans publication propre ; exposé aux résultats de ses grandes pondérations' },
  eventRisk: {},
  blastDoc: 1,
  scenarios: c => [
    { scenario: 'bullish', trigger: 'Horizon 2 est livré et accepté, et les résultats du 5 novembre montrent des revenus cloud IA en forte hausse sans nouvelle émission d’actions d’ampleur.', firstOrder: 'Le titre reprend ' + c.usd(c.lv('r1')) + ' puis ' + c.usd(c.lv('r2')) + ' ; le revenu annualisé commence à apparaître dans le chiffre d’affaires.', secondOrder: 'Les anciens mineurs en conversion se refinancent plus facilement ; Dell et NVIDIA gardent leurs carnets.', confirmation: 'Une clôture au-dessus de ' + c.usd(c.lv('r1')) + ' sur volume, avec Nebius et CoreWeave orientés à la hausse.', contradiction: 'Une hausse d’IREN accompagnée d’une forte vente d’actions par l’« at-the-market ».' },
    { scenario: 'mixed', trigger: 'Les livraisons avancent, mais les revenus comptabilisés restent loin du revenu annualisé et l’« at-the-market » continue.', firstOrder: 'Le titre oscille entre ' + c.usd(c.lv('s2')) + ' et ' + c.usd(c.lv('r2')) + ', au gré de l’appétit pour les neoclouds.', secondOrder: 'L’écart avec l’amont se maintient : les fournisseurs encaissent, IREN attend ses revenus.', confirmation: 'Des clôtures dans ce couloir pendant plusieurs séances, dilution au rythme habituel.', contradiction: 'Une sortie franche du couloir, d’un côté ou de l’autre.' },
    { scenario: 'bearish', trigger: 'Un retard de livraison chez Microsoft, une baisse des prix de l’heure de calcul ou une émission dilutive de grande taille.', firstOrder: 'Le titre casse ' + c.usd(c.lv('s2')) + ' et revient vers le plus bas sur un an, ' + c.usd(c.lv('s3')) + '.', secondOrder: 'Les pairs financés à crédit décrochent davantage ; l’amont révise ses calendriers de livraison.', confirmation: 'Une clôture sous ' + c.usd(c.lv('s2')) + ' ou un dépôt de financement fortement dilutif.', contradiction: 'Une acceptation d’Horizons 2 à 4 dans les délais malgré la baisse du titre.' }],
  contradictions: c => ['Le carnet de contrats n’a jamais été aussi solide, mais le titre a perdu plus de la moitié de son plus haut de novembre 2025 : le marché paie le coût de financement et le risque d’exécution, pas seulement les contrats.', 'Le repli des 7 et 8 octobre est commun à Nebius, CoreWeave et Cipher Mining : il ne prouve rien de propre à IREN, et une corrélation élevée avec ces pairs ne signifie pas un lien commercial.', 'NVIDIA est classée en amont, mais elle est aussi client et actionnaire potentiel : sa corrélation avec IREN mélange un effet de coût, de revenu et de capital.'],
  missingData: c => ['Hut 8, CleanSpark et Bitdeer, pairs directs économiquement pertinents, sont écartés du blast radius certifié : leurs séries quotidiennes ont été refusées pour séances incomplètes.', 'Prochaine date de résultats (5 novembre) issue d’une source calendaire unique, non confirmée par l’émetteur.', 'Chaîne d’options indisponible à la collecte ; coût d’emprunt issu du seul composite de signaux ; sentiment Reddit et Google Trends indisponibles.', 'Fondamentaux et statistiques du fournisseur relevés en instantané, non reconstitués à la clôture de référence.'],
  limitations: ['Hut 8, CleanSpark et Bitdeer écartés du calcul de corrélation faute de séances complètes.', 'EBITDA GAAP négatif : la valorisation relative repose sur les revenus, pas sur l’EBITDA ; le revenu annualisé n’est pas une mesure GAAP.', 'Fondamentaux et statistiques du fournisseur relevés en instantané, non point-in-time ; aucun objectif d’analyste écrit comme gouvernant.'],
});
