'use strict';
// Dossier ANET v3 au close du 2026-09-23 (lot R02). Scénario de sortie par le haut du plus haut du 5 août,
// jour de la publication du deuxième trimestre ; calculs et preuves délégués au gabarit commun.
const R = require('../../../../tools/lib/analysis-v3-r02.cjs');
const GEN = 'analyses/ANET/_runs/20260924/build-anet.cjs';

R.build({
  ticker: 'ANET', shortName: 'Arista', cik: 1596532, generator: GEN, mode: 'breakout',
  xbrl: { ttm: { rev: ['RevenueFromContractWithCustomerExcludingAssessedTax'], ebit: ['OperatingIncomeLoss'], ni: ['NetIncomeLoss'], da: ['DepreciationDepletionAndAmortization'], ocf: ['NetCashProvidedByUsedInOperatingActivities'] },
    instant: { cashEq: ['CashAndCashEquivalentsAtCarryingValue'], afsCur: ['AvailableForSaleSecuritiesDebtSecuritiesCurrent'] },
    da: ['da'], debt: [], cash: ['cashEq', 'afsCur'] },
  scenarioMultiple: 25, valuationBasis: 'GAAP douze mois au 2026-06-30 (XBRL SEC) ; multiple de vingt-cinq fois l’EBITDA = hypothèse éditoriale ; aucune dette financière',
  levels: { trigger: { d: '2026-08-05', c: 2 }, stop: { d: '2026-09-23', c: 3 }, abandon: { d: '2026-09-03', c: 3 },
    s1: { d: '2026-09-17', c: 3 }, r1: { d: '2026-09-22', c: 2 }, r2: { d: '2026-08-12', c: 2 } },
  supports: ['stop', 's1', 'abandon'], resistances: ['r1', 'r2', 'trigger'],
  targets: ({ entry, abandon }) => { const range = entry - abandon; return { tp1: entry + 0.75 * range, tp2: entry + range, range }; },
  levelsMethod: 'Déclencheur = plus haut du 5 août ; bas du couloir = plus bas du 3 septembre ; stop = plus bas du 23 septembre ; TP1 = déclencheur + 0,75 × hauteur du couloir ; TP2 = déclencheur + hauteur ; plafond = (TP1 + 1,5 × stop) / 2,5 ; pourcentages depuis l’entrée ; R/R = gain / risque.',
  inventory: 13,
  reviewScope: 'Dépôts EDGAR d’Arista du 1er janvier au 23 septembre 2026 (13 formulaires hors formulaires 3, 4, 5 et 144), dont le 10-K de l’exercice 2025 déposé le 17 février. Le 8-K de l’assemblée générale, le formulaire SD, les déclarations 13G et les procurations sont écartés comme non décisionnels. Aucun prospectus d’émission ni enregistrement de titres n’est relevé.',
  docs: [
    ['2026-08-04', '8-K / Exhibit 99.1', '0001596532-26-000174', 'ex991q226-earningsrelease.htm', 'q2-8k__ex991q226-earningsrelease.htm',
      'Communiqué du deuxième trimestre 2026 : premier trimestre au-dessus de 3 Md$, à 3,036 Md$ (+37,7 % sur un an), marge opérationnelle GAAP de 45,4 %, mais marge brute GAAP en recul à 62,9 % contre 65,2 %. Prévision du troisième trimestre à environ 3,3 Md$ de revenus.'],
    ['2026-08-05', '10-Q', '0001596532-26-000175', 'anet-20260630.htm', 'q2-10q__anet-20260630.htm',
      'Rapport trimestriel au 30 juin 2026 : revenus différés de 6,87 Md$ contre 5,37 Md$ fin 2025, 9,7 Md$ d’engagements d’achat non annulables, aucun rachat d’actions au premier semestre et 817,9 M$ restant sur le programme de 1,5 Md$.'],
    ['2026-08-27', '8-K / Exhibit 99.1 (Marvell)', '0001835632-26-000022', 'q227_8kx812026ex-991.htm', 'mrvl-q2fy27-8k__q227_8kx812026ex-991.htm',
      'Communiqué de Marvell, fournisseur de puces optiques et d’interconnexion des réseaux de clusters : la société annonce une journée investisseurs le 6 octobre 2026 pour présenter sa stratégie de long terme dans l’infrastructure de l’IA.', 1835632],
    ['2026-02-17', '10-K', '0001596532-26-000013', 'anet-20251231.htm', 'fy25-10k__anet-20251231.htm',
      'Rapport annuel de l’exercice 2025 : deux clients finaux, non nommés, ont représenté 26 % et 16 % du chiffre d’affaires, et les deux premiers revendeurs 52 % des créances au 31 décembre 2025. Plus de 40 % des ventes dépendent donc de deux acheteurs.'],
  ],
  needles: {
    q2: [0, ['Revenue of $3.036 billion', 'an increase of 37.7% from the second quarter of 2025', 'GAAP and non-GAAP operating margin of 45.4% and 49.9%', 'GAAP gross margin 62.9 % 65.2 %', 'Revenue of approximately $3.3 billion', 'Non-GAAP diluted net income per share between $1.06 and $1.08', 'GAAP and non-GAAP diluted earnings per share of $0.95 and $1.02']],
    balance: [1, ['Deferred revenue 5,100.7 4,002.6', 'Deferred revenue, non-current 1,765.2 1,369.8', 'non-cancellable purchase commitments not recorded on our balance sheet of $ 9.7 billion', 'We did not repurchase any shares during the six months ended June 30, 2026', '$ 817.9 million', 'Purchases of property and equipment ( 84.2 )', '1,261,224,648']],
    mrvl: [2, ['at our Investor Day on October 6 th , 2026']],
    concentration: [3, ['Sales to these two customers represented 26% and 16% of our total revenue for the year ended December 31, 2025', 'our top two resellers accounted for 52 %']],
  },
  sectionDocs: { verdict: [0, 1, 3], business: [0, 3], news: [0], earnings: [0], capitalStructure: [1], filingsReview: [0, 1, 2, 3], risks: [3, 0, 1], globalScore: [0, 1], meta: [0], disclaimer: [0], macro: [0], options: [0], social: [0], header: [0] },
  score: { business: 30, technical: 4, capital: 6, calendar: 0, dilution: 0, risk: 22 },
  extraInputs: [{ name: 'mu', path: 'analyses/MU/_data/earnings_risk.json' }],
  route: (p, { prov, dep }) => /^(tradeIdea\.catalysts\.1|blastRadius\.groups\.2\.symbols\.1\.eventRisk)$/.test(p) ? prov('mu', '/events/0/report_date', 'Date de publication de Micron lue dans deux calendriers de données, non confirmée par Micron ; journée investisseurs de Marvell datée par son communiqué du 27 août 2026.', [dep('primary', '/documents/2')]) : null,
  riskScoreReason: 'Jugement qualitatif sur dix : deux clients à plus de 40 % des ventes, marge brute en recul et ventes soutenues d’un grand actionnaire.',
  compose: c => {
    const { nb, fr, usd, pct, sgn, dfr, close, prev, bars, N, tech, st, M, adv, ret, G$, marketCap, ev, scn, lv, entry, stop, tp1, tp2, abandon, cap, rr1, rr2, riskAtr, sizeExample, ref, market, docs, raw, tx } = c;
    const t5 = bars.find(b => b[0] === '2026-08-05'), t4 = bars.find(b => b[0] === '2026-08-04');
    const sold = n => tx.transactions.filter(x => x.insider_name === n && x.type_code === 'S');
    const sum = (a, k) => a.reduce((s, x) => s + x[k], 0);
    const bech = sold('BECHTOLSHEIM ANDREAS'), duda = sold('Duda Kenneth');
    const bechV = sum(bech, 'value_usd'), bechS = sum(bech, 'shares'), dudaV = sum(duda, 'value_usd'), dudaS = sum(duda, 'shares');
    const smh21 = M.SMH.return21d, gs = c.gapStats(cap - entry);
    return {
      meta: { lang: 'fr', dir: 'ltr', level: 'intermediate', tags: ['us', 'equities', 'ai-chain', 'tech', 'technology'], grade: 'B', date: '2026-09-24', dateDisplay: '24 septembre 2026', version: 3, status: 'watch', assetType: 'stock', levelsCloseDate: c.REF,
        description: 'Arista : le réseau des clusters d’IA croît de 38 %, mais le titre bute sur le plus haut du jour de ses résultats. Dossier au close du 23 septembre 2026, statut surveiller.',
        ogDescription: 'Arista : 3,04 Md$ de revenus, 6,9 Md$ de revenus différés, deux clients à 42 % des ventes ; niveaux à surveiller.',
        lastMcpRefresh: raw.status.captured_at, levelsVerifiedAt: raw.status.captured_at,
        statusHistory: [{ at: raw.status.captured_at, from: 'rejected', to: 'watch', note: 'refonte v3 du 24 septembre : nouveau scénario, clôture de référence du 2026-09-23', close }] },
      header: { ticker: 'ANET', name: 'Arista Networks, Inc.', exchange: 'NYSE', sector: 'Commutateurs Ethernet pour centres de données et clusters d’IA', price: close, changePct: pct(close, prev),
        badges: [{ text: 'SURVEILLER — PAS D’ENTRÉE AU COURS ACTUEL', color: 'blue' }, { text: 'Chaîne IA — réseau', color: 'purple' }],
        metrics: { marketCap: fr(marketCap / 1e9, 0) + ' Md$', volume: fr(bars[N][5] / 1e6, 1) + ' M', evEbitda: fr(ev / G$.ebitda, 1) + '×' }, halalStatus: 'unknown' },
      verdict: { score: 62, conviction: 'Moderate', bias: 'Neutral',
        confidence: 'Score éditorial non prédictif. Les chiffres d’entreprise viennent des dépôts SEC et des données XBRL officielles ; les niveaux, du close certifié du 23 septembre.',
        summary: 'Arista vend les commutateurs qui relient entre eux les processeurs des clusters d’IA. Le deuxième trimestre a dépassé 3 Md$ de revenus pour la première fois, en hausse de 37,7 %, et les revenus différés atteignent 6,87 Md$, soit plus de deux trimestres de ventes déjà facturés ou encaissés. Le titre, lui, n’a jamais repris le plus haut du 5 août : ce jour-là, au lendemain de la publication, il a touché ' + usd(t5[2]) + ' avant de clôturer à ' + usd(t5[4]) + '. Trois faits freinent. Deux clients non nommés pèsent 42 % des ventes de 2025, et la marge brute GAAP recule à 62,9 %. Andreas Bechtolsheim, cofondateur, a vendu ' + nb(bechS) + ' actions en trois semaines. Pas d’entrée au cours actuel ; le signal serait une clôture au-dessus de ' + usd(entry) + '.',
        whyBuy: [
          'Le chiffre d’affaires du deuxième trimestre atteint 3,036 Md$, en hausse de 37,7 % sur un an et de 12,1 % sur trois mois.',
          'Les revenus différés passent de 5,37 à 6,87 Md$ en six mois : des ventes déjà contractées attendent d’être reconnues.',
          'La prévision du troisième trimestre vise environ 3,3 Md$, avec une marge opérationnelle ajustée de 48 à 49 %.',
          'Aucune dette financière et ' + fr(G$.cash / 1e9, 1) + ' Md$ de trésorerie et placements à court terme fin juin.'],
        whyAvoid: [
          'Deux clients finaux non nommés ont pesé 26 % et 16 % du chiffre d’affaires de 2025 : plus de 40 % des ventes dépendent de deux budgets.',
          'La marge brute GAAP recule à 62,9 %, contre 65,2 % un an plus tôt : la croissance vient des grands clouds, qui négocient les prix.',
          'Andreas Bechtolsheim, détenteur de plus de 10 %, a vendu ' + nb(bechS) + ' actions pour ' + fr(bechV / 1e6, 1) + ' M$ entre le 27 août et le 17 septembre.',
          'Au close du 23 septembre, la valeur d’entreprise représente ' + fr(ev / G$.ebitda, 1) + ' fois l’EBITDA GAAP des douze mois clos le 30 juin.'],
        controlChecklist: [
          { label: 'Historique de cours', status: 'pass', statusLabel: 'Trois cents séances continues', evidence: 'Série quotidienne certifiée au close du 23 septembre, source de repli documentée.', action: 'Niveaux et indicateurs recalculés sur cette seule série.' },
          { label: 'Concentration client', status: 'warn', statusLabel: 'Deux clients à 42 %', evidence: 'Parts publiées dans le 10-K de l’exercice 2025, clients non nommés.', action: 'Surveiller les annonces de capex des grands clouds.' },
          { label: 'Ventes d’initiés', status: 'warn', statusLabel: 'Cofondateur vendeur', evidence: 'Dix-neuf ventes déclarées par Andreas Bechtolsheim entre le 27 août et le 17 septembre.', action: 'Lire les prochains formulaires 4 avant toute activation.' }] },
      business: { theme: 'Réseau Ethernet des centres de données et des clusters d’IA',
        overview: '<p>Arista conçoit des commutateurs et des routeurs Ethernet, pilotés par un système d’exploitation unique, EOS. Ses clients historiques sont les grands clouds, qui l’utilisent pour relier leurs serveurs. Avec l’IA, ces mêmes commutateurs relient désormais des milliers de processeurs graphiques dans un même cluster, et la plateforme 1,6 térabit présentée au deuxième trimestre vise ces réseaux.</p><p>Le deuxième trimestre 2026 a atteint 3,036 Md$ de revenus, dont 2,605 Md$ de produits et 430 M$ de services, pour un résultat net de 1,21 Md$. La marge opérationnelle GAAP s’établit à 45,4 %. Les revenus différés, 6,87 Md$ fin juin, et les 9,7 Md$ d’engagements d’achat auprès des sous-traitants montrent une entreprise qui prépare des livraisons importantes.</p><p>La dépendance est forte. Deux clients finaux, que la société ne nomme pas, ont représenté 26 % et 16 % du chiffre d’affaires de 2025, et les deux premiers revendeurs 52 % des créances. Leur marge brute pèse sur celle d’Arista, passée de 65,2 % à 62,9 % en un an.</p>',
        moat: 'L’avantage d’Arista tient à EOS, un logiciel unique sur toute la gamme, et à la confiance des plus grands opérateurs de centres de données. Il est solide techniquement, mais le pouvoir de négociation reste chez deux clients qui pèsent plus de 40 % des ventes.',
        segments: [
          { name: 'Produits', revenue: '2,605 Md$ au trimestre', pct: '86 %', description: 'Commutateurs, routeurs et applications réseau.' },
          { name: 'Services', revenue: '430,5 M$ au trimestre', pct: '14 %', description: 'Contrats de support et renouvellements.' }],
        sourceRefs: [ref(0), ref(3)],
        coverageMatrix: [
          { facet: 'Cours et historique', status: 'COUVERT', decision: 'Trois cents séances continues, close certifié ; base des niveaux et des indicateurs.' },
          { facet: 'Résultats et guidance', status: 'COUVERT — PRIMAIRE', decision: 'Communiqué du 4 août et 10-Q ; prochaine date non confirmée.' },
          { facet: 'Capital et trésorerie', status: 'COUVERT — PRIMAIRE', decision: 'Aucune dette, rachats suspendus au premier semestre, programme restant publié.' },
          { facet: 'Agrégats GAAP', status: 'COUVERT — XBRL', decision: 'Douze mois glissants reconstitués depuis les données XBRL officielles.' },
          { facet: 'Comparables et transmission', status: 'COUVERT — LOCAL', decision: 'Corrélations recalculées sur barres certifiées depuis la fin mars.' },
          { facet: 'Initiés', status: 'COUVERT — PARTIEL', decision: 'Ventes du cofondateur et du directeur technique relevées ; aucun solde net officiel.' },
          { facet: 'Options', status: 'NON EXPLOITABLE', decision: 'Chaîne relevée marché fermé, sans intérêt ouvert utilisable.' }] },
      news: [
        { date: '2026-08-04', title: 'Premier trimestre au-dessus de 3 Md$', impact: 'positive', detail: 'Le lendemain, le titre a ouvert à ' + usd(t5[1]) + ' et touché ' + usd(t5[2]) + ' avant de clôturer à ' + usd(t5[4]) + ' : le marché a vendu la hausse dans la séance.', source: 'Arista — SEC', sourceUrl: docs[0].url },
        { date: '2026-08-05', title: 'Le 10-Q affiche 6,87 Md$ de revenus différés', impact: 'positive', detail: 'Des ventes déjà contractées qui soutiennent les prochains trimestres, avec 9,7 Md$ d’achats engagés auprès des sous-traitants.', source: 'Arista — SEC', sourceUrl: docs[1].url },
        { date: '2026-08-05', title: 'Aucun rachat d’actions au premier semestre', impact: 'neutral', detail: 'La société garde sa trésorerie malgré un programme restant de 817,9 M$, alors que les initiés vendent.', source: 'Arista — SEC', sourceUrl: docs[1].url }],
      fundamentals: { rows: [
          { metric: 'Chiffre d’affaires du trimestre', value: '3,036 Md$', signal: '+37,7 % sur un an, communiqué du 4 août', signalColor: 'green', _src: 0 },
          { metric: 'Marge brute GAAP du trimestre', value: '62,9 %', signal: 'Contre 65,2 % un an plus tôt', signalColor: 'amber', _src: 0 },
          { metric: 'Marge opérationnelle GAAP du trimestre', value: '45,4 %', signal: '49,9 % en données ajustées', signalColor: 'green', _src: 0 },
          { metric: 'Prévision du troisième trimestre', value: 'Environ 3,3 Md$', signal: 'Marge opérationnelle ajustée de 48 à 49 %', signalColor: 'blue', _src: 0 },
          { metric: 'Revenus différés au 30 juin 2026', value: '6,87 Md$', signal: 'Contre 5,37 Md$ au 31 décembre 2025', signalColor: 'green', _src: 1 },
          { metric: 'Engagements d’achat non annulables', value: '9,7 Md$', signal: 'Dont 9,4 Md$ à moins de douze mois', signalColor: 'amber', _src: 1 },
          { metric: 'Part des deux premiers clients (2025)', value: '26 % et 16 %', signal: 'Clients finaux non nommés, 10-K', signalColor: 'amber', _src: 3 },
          { metric: 'Revenus GAAP sur douze mois', value: fr(G$.rev / 1e9, 2) + ' Md$', signal: 'Douze mois glissants au 30 juin 2026 (XBRL SEC)', signalColor: 'blue', _src: 'gaap' },
          { metric: 'EBITDA GAAP sur douze mois', value: fr(G$.ebitda / 1e9, 2) + ' Md$', signal: 'Résultat opérationnel + amortissements, douze mois au 30 juin 2026', signalColor: 'blue', _src: 'gaap' },
          { metric: 'Résultat net GAAP sur douze mois', value: fr(G$.ni / 1e9, 2) + ' Md$', signal: 'Douze mois glissants au 30 juin 2026', signalColor: 'green', _src: 'gaap' },
          { metric: 'Trésorerie et placements à court terme', value: fr(G$.cash / 1e9, 1) + ' Md$', signal: 'Liquidités et titres de dette courants au 30 juin 2026, aucune dette financière', signalColor: 'green', _src: 'gaap' },
          { metric: 'EV/EBITDA GAAP', value: fr(ev / G$.ebitda, 1) + '×', signal: 'Valeur d’entreprise au close du 2026-09-23 sur EBITDA GAAP douze mois au 2026-06-30', signalColor: 'amber', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus le scénario de compression ci-dessous : l’écart mesure la prime accordée à la durée de la croissance.', _src: 'market' },
          { metric: 'P/E GAAP sur douze mois', value: fr(marketCap / G$.ni, 1) + '×', signal: 'Douze mois glissants : capitalisation au 2026-09-23 sur résultat net GAAP douze mois au 2026-06-30', signalColor: 'amber', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus une croissance de 37,7 % au dernier trimestre : le marché paie plusieurs années de croissance.', _src: 'market' },
          { metric: 'EV/EBITDA — scénario de compression (hypothèse éditoriale)', value: fr(scn.price, 2) + ' $ par action', signal: 'Scénario : multiple ramené à vingt-cinq fois l’EBITDA GAAP par hypothèse, trésorerie du 2026-06-30 inchangée, soit ' + fr(scn.downside_pct, 0) + ' % sous le close du 2026-09-23', signalColor: 'red', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus le close : ce que coûterait un ralentissement ramenant le multiple à celui d’un équipementier mature ; ce n’est pas un objectif.', _src: 'market' }],
        sourceRefs: [ref(0), ref(1), market('fondamentaux et statistiques')] },
      earnings: { quarters: [],
        beatNote: 'Deuxième trimestre 2026 : bénéfice par action GAAP de 0,95 $ et ajusté de 1,02 $, contre 0,70 $ et 0,73 $ un an plus tôt. La guidance du troisième trimestre vise environ 3,3 Md$ de revenus, une marge opérationnelle ajustée de 48 à 49 % et un bénéfice ajusté de 1,06 à 1,08 $ par action. Le recul de la marge brute GAAP, de 65,2 % à 62,9 %, reste le point à suivre. Aucune date de prochaine publication n’est confirmée par l’émetteur à ce jour.',
        nextEarnings: 'Date non confirmée par l’émetteur ; aucune publication dans les quatorze jours du calendrier collecté.',
        sourceRefs: [ref(0)] },
      capitalStructure: { sharesOutstanding: '1 261 224 648 actions au 30 juillet 2026 (page de garde du 10-Q)',
        sharesAuthorized: '4 milliards d’actions ordinaires autorisées ; aucune action préférentielle émise.', dilutionRisk: 'low',
        shareHistory: 'Le nombre moyen d’actions diluées passe de 1,271 à 1,276 milliard entre les deuxièmes trimestres 2025 et 2026, soit environ 0,4 % de dilution annuelle par la rémunération en actions. Aucun rachat au premier semestre 2026, contre un programme dont il reste 817,9 M$ ; aucune émission d’actions, aucun convertible et aucune dette financière ne figurent dans les dépôts.',
        warrants: [], atm: { active: false, authorized: 'Aucun programme d’émission d’actions relevé', used: 'Sans objet', remaining: 'Sans objet' },
        sourceRefs: [ref(1), ref(0)] },
      filingsReview: { summary: 'Trois dépôts décisionnels ouverts et hachés. La croissance et le carnet sont solides ; la marge brute recule et la concentration sur deux clients reste la contrepartie de ce carnet.',
        filings: docs.map(d => ({ date: d.date, form: d.form, accession: d.accession, finding: d.finding, url: d.url })),
        contrarianRisks: [
          'Deux clients à 42 % des ventes : une pause de capex chez l’un d’eux se lirait immédiatement dans les revenus.',
          'La marge brute recule depuis un an : la croissance vient des clients qui négocient le plus durement.',
          'Nvidia vend son propre réseau Ethernet avec ses processeurs : chaque cluster livré clé en main est un marché de moins pour Arista.',
          'Les ventes d’un cofondateur détenteur de plus de 10 %, sans rachat de la société en face, pèsent sur l’offre de titres.'] },
      technicals: { rsi14: +tech.rsi14.toFixed(2), macd: +tech.macd.toFixed(2), macdSignal: +tech.macdSignal.toFixed(2), ema20: +tech.ema20.toFixed(2), ema50: +tech.ema50.toFixed(2), ema200: +tech.ema200.toFixed(2),
        ma50Type: 'EMA', ma200Type: 'EMA', ma50Available: true, ma200Available: true, atr14: +tech.atr14.toFixed(2),
        badges: ['Au-dessus des moyennes à vingt, cinquante et deux cents séances', 'Sous le plus haut du 5 août', 'Pas d’entrée au cours actuel'],
        supports: [stop, lv('s1'), abandon], resistances: [lv('r1'), lv('r2'), entry],
        setupNote: 'Le titre clôture à ' + usd(close) + ', au-dessus de ses moyennes à vingt, cinquante et deux cents séances, mais sous le plus haut du 5 août. Avant activation, aucune entrée ; une clôture sous ' + usd(abandon) + ', plus bas du 3 septembre, abandonne le scénario. Activation sur une clôture au-dessus de $' + entry.toFixed(2) + ', le plus haut de la séance qui a suivi les résultats. Après activation, stop sous $' + stop.toFixed(2) + ', plus bas du 23 septembre, soit ' + fr(riskAtr, 1) + ' ATR sous le déclencheur. Supports : ' + usd(stop) + ', ' + usd(lv('s1')) + ' et ' + usd(abandon) + '. Résistances : ' + usd(lv('r1')) + ', ' + usd(lv('r2')) + ' et ' + usd(entry) + '.',
        wyckoff: 'Non utilisé : le profil de volume n’est pas exploité dans ce dossier.',
        sourceRefs: [market('barres quotidiennes et indicateurs recalculés')] },
      options: { callOI: 'Non exploitable', putOI: 'Non exploitable', cpRatio: 'Non exploitable', maxPain: 'Non exploitable', ivMean: 'Non exploitable', skew: 'Chaîne relevée marché fermé, sans intérêt ouvert utilisable', unusual: 'Aucune activité inhabituelle qualifiée', sourceRefs: [market('options')] },
      shortInterest: { siPct: fr(st.shortPercentOfFloat * 100, 2) + ' % du flottant', daysToCover: fr(st.shortRatio, 2) + ' jours, date de règlement non précisée par le snapshot', ctb: 'Coût d’emprunt bas, sans tension', trend: 'Positions vendeuses faibles ; aucune thèse de rachat forcé des vendeurs.', squeezeScore: 'Non pertinent', sourceRefs: [market('positions vendeuses')] },
      insiders: { signal: 'Vendeurs nets. Andreas Bechtolsheim, cofondateur et détenteur de plus de 10 %, a déclaré ' + bech.length + ' ventes pour ' + nb(bechS) + ' actions, environ ' + fr(bechV / 1e6, 1) + ' M$, du 27 août au 17 septembre. Kenneth Duda, président et directeur technique, a vendu ' + nb(dudaS) + ' actions, environ ' + fr(dudaV / 1e6, 1) + ' M$, le 21 septembre après exercice d’options ; ses autres mouvements déclarés sont des transferts sans prix. Couverture officielle partielle : aucun solde net publié.',
        recentTransactions: [
          { date: '2026-09-17', insider: 'Andreas Bechtolsheim — détenteur de plus de 10 %', type: 'sell', shares: nb(bechS), value: fr(bechV / 1e6, 1) + ' M$' },
          { date: '2026-09-21', insider: 'Kenneth Duda — président et directeur technique', type: 'sell', shares: nb(dudaS), value: fr(dudaV / 1e6, 1) + ' M$' }],
        sourceRefs: [market('formulaires 4')] },
      macro: { indicators: [{ name: 'Clôture de référence', value: c.REF, signal: usd(close) + ', séance complète' }, { name: 'Rendement cinq séances', value: sgn(ret(5)), signal: 'Descriptif' }, { name: 'Rendement vingt et une séances', value: sgn(ret(21)), signal: 'Descriptif' }],
        regime: 'neutral', impact: 'Le réseau suit le capex des grands clouds plus que les taux. Le 10 ans américain à 5,11 % le 23 septembre, plus haut depuis juillet 2007, pèse néanmoins sur un multiple de croissance élevé.' },
      risks: { riskScore: 6, riskProfile: 'High',
        riskSummary: 'Le risque d’Arista est commercial avant d’être technique : deux clients pèsent plus de 40 % des ventes et leur poids se lit déjà dans la marge brute. Ajoutez un cofondateur vendeur et un titre qui n’a pas repris le plus haut de sa dernière publication : la croissance est réelle, le prix l’a en partie escomptée.',
        riskCards: [
          { title: 'Deux clients dominants', severity: 'high', icon: 'fa-user-tie', points: ['26 % et 16 % du chiffre d’affaires de 2025, clients non nommés.', 'Deux revendeurs à 52 % des créances.'], verdict: 'Une révision de capex d’un seul grand cloud suffirait à décaler la croissance d’un trimestre.' },
          { title: 'Marge brute en recul', severity: 'medium', icon: 'fa-scale-balanced', points: ['62,9 % au deuxième trimestre contre 65,2 % un an plus tôt.', 'Croissance tirée par les plus gros acheteurs.'], verdict: 'Si la marge continue de glisser, la croissance des revenus se transmettra moins au bénéfice.' },
          { title: 'Réseau intégré des concurrents', severity: 'medium', icon: 'fa-building', points: ['Nvidia vend des clusters avec leur réseau.', 'Les clouds peuvent diversifier leurs fournisseurs de commutateurs.'], verdict: 'La part d’Arista dans les clusters d’IA se rejoue à chaque génération de réseau.' },
          { title: 'Offre de titres des initiés', severity: 'medium', icon: 'fa-money-bill-trend-up', points: ['Environ ' + fr(bechV / 1e6, 0) + ' M$ vendus par le cofondateur en trois semaines.', 'Aucun rachat de la société au premier semestre.'], verdict: 'Des ventes régulières d’un grand actionnaire freinent les sorties par le haut.' }],
        pedagogy: 'Le 5 août, le titre a ouvert en hausse après la publication puis a été vendu toute la séance : un plus haut de réaction non repris devient une résistance. Au-dessus, la liquidité reste bonne, mais un gap à l’ouverture peut faire payer plus que le plafond ; le slippage compte sur une entrée aussi serrée. Fixer la taille de position à partir de la distance au stop et d’un budget de perte, pas de l’objectif. Ne pas anticiper : attendre la clôture au-dessus du déclencheur.' },
      tradeIdea: { status: 'watch', statusNote: 'Surveiller. Avant activation : aucune entrée ; une clôture sous ' + usd(abandon) + ' abandonne le scénario. Activation : clôture au-dessus de ' + usd(entry) + ', puis achat à l’ouverture suivante seulement sous ' + usd(cap) + '. Après activation : stop sous ' + usd(stop) + '. Le plan rejeté du 28 août n’est pas repris.',
        entry, stop, tp1, tp2,
        stopPct: pct(stop, entry).toFixed(1) + '%', tp1Pct: '+' + pct(tp1, entry).toFixed(1) + '%', tp2Pct: '+' + pct(tp2, entry).toFixed(1) + '%',
        rr: '1:' + rr1.toFixed(2) + ' TP1 / 1:' + rr2.toFixed(2) + ' TP2',
        entryNote: 'Déclencheur sur clôture au-dessus du plus haut du 5 août, pas sur un franchissement en séance. Entrée à l’ouverture suivante uniquement sous ' + usd(cap) + ' : au-delà, le R/R vers TP1 tomberait sous 1,5 avec le même stop. Le plafond n’est qu’à ' + usd(cap - entry) + ' au-dessus du déclencheur : un écart d’ouverture plus large annule l’entrée, il ne se rattrape pas. Sur les ' + gs.total + ' dernières séances, ' + gs.up + ' ouvertures ont dépassé la clôture de la veille de plus de ' + usd(cap - entry) + ', soit environ ' + fr(gs.up / gs.total * 100, 0) + ' % ; l’écart d’ouverture médian, dans un sens ou dans l’autre, vaut ' + usd(gs.medAbs) + '. Objectifs : TP1 aux trois quarts de la hauteur du couloir au-dessus du déclencheur, TP2 à sa hauteur entière. Liquidité : environ ' + fr(adv / 1e6, 0) + ' M$ échangés par séance, médiane des vingt dernières. Exemple de taille, non personnalisé : avec un budget de perte de 100 $, le risque au plafond, ' + usd(cap - stop) + ' par action, donne ' + sizeExample + ' actions.',
        horizon: 'Dix séances après activation',
        thesis: 'Le marché doute qu’Arista garde sa marge face à des clients qui pèsent 42 % des ventes et à un concurrent qui livre ses clusters avec leur réseau ; il l’a montré en vendant le plus haut du 5 août. Avant activation, surveillance seulement, et une clôture sous ' + usd(abandon) + ' abandonne le scénario. Une clôture au-dessus de $' + entry.toFixed(2) + ' signalerait que ce doute est absorbé ; l’achat n’a lieu qu’à l’ouverture suivante et sous ' + usd(cap) + '. Après activation, le stop sous $' + stop.toFixed(2) + ' coupe une fausse sortie. TP1 à ' + usd(tp1) + ', TP2 à ' + usd(tp2) + '. Ne pas acheter un gap au-dessus du plafond.',
        catalysts: ['Une clôture au-dessus du plus haut du 5 août, sur un volume au moins égal à la médiane récente.', 'Deux dates dans l’horizon : les résultats de Micron le ' + dfr(c.extra.mu.events[0].report_date) + ' après la clôture, selon deux calendriers de données, et la journée investisseurs de Marvell le 6 octobre ; chacune peut ouvrir un gap sur les valeurs de l’infrastructure d’IA.', 'La fin des ventes déclarées du cofondateur, visible dans les prochains formulaires 4.'],
        invalidation: ['Avant activation : une clôture sous ' + usd(abandon) + ', bas du couloir, abandonne le scénario.', 'Après activation : une clôture sous ' + usd(stop) + ' invalide le trade.', 'Ouverture au-dessus de ' + usd(cap) + ' après la clôture de déclenchement : pas d’achat, le R/R deviendrait insuffisant.', 'Une baisse du capex annoncée par un grand cloud annule la thèse avant activation.'] },
      globalScore: { profile: 'Croissance du réseau de l’IA, concentrée sur deux clients',
        keyTakeawaysPositive: ['Revenus en hausse de 37,7 %, premier trimestre au-dessus de 3 Md$.', 'Revenus différés de 6,87 Md$, en hausse de 28 % en six mois.', 'Aucune dette et une trésorerie de plus de 13 Md$.'],
        keyTakeawaysNegative: ['Deux clients à 42 % des ventes de 2025.', 'Marge brute GAAP en recul à 62,9 %.', 'Ventes régulières d’un cofondateur, sans rachat en face.'],
        mindsetTip: 'Un plus haut de publication vendu dans la séance est une information : le prix a dit « pas encore ». Attendre qu’il dise oui.' },
      social: { platforms: [], sourceRefs: [market('sentiment non retenu faute de mesure qualifiée')] },
      disclaimer: 'Document de recherche éducatif. Ni conseil financier, ni signal de trading. Statut surveiller : aucun ordre actif.',
    };
  },
  groups: [
    { name: 'Grands clouds acheteurs de réseau', order: 1, transmission: 'Leur capex de centres de données fixe la demande de commutateurs.', rows: [
      ['MSFT', 'leader', 'Premier acheteur de calcul et cloud Azure', 'Son capex de centres de données se traduit directement en commandes de commutateurs.'],
      ['META', 'leader', 'Grand acheteur de calcul pour ses modèles', 'Ses révisions de capex se lisent dans la demande de réseau des clusters.'],
      ['GOOGL', 'leader', 'Cloud et réseau conçu en interne', 'Son réseau maison limite la part des fournisseurs extérieurs dans ses centres.'],
      ['AMZN', 'leader', 'Premier cloud public', 'Ses choix de réseau entre maison et fournisseurs déplacent des volumes importants.'],
      ['ORCL', 'leader', 'Cloud d’infrastructure pour l’IA', 'Ses nouveaux centres de données ajoutent un acheteur de réseau de grande taille.'],
      ['CRWV', 'leader', 'Néo-cloud spécialisé dans l’IA', 'Ses clusters loués aux laboratoires d’IA consomment du réseau à haut débit.']] },
    { name: 'Pairs directs : réseau', order: 1, transmission: 'Même budget de réseau, parts de marché disputées.', rows: [
      ['CSCO', 'direct_peer', 'Réseau d’entreprise et de centres de données', 'Concurrent historique : ses commandes de centres de données mesurent la pression sur les prix.'],
      ['NVDA', 'direct_peer', 'Processeurs graphiques et réseau intégré', 'Son réseau livré avec les clusters concurrence directement les commutateurs d’Arista.'],
      ['HPE', 'direct_peer', 'Serveurs et réseau d’entreprise', 'Son activité réseau concurrence Arista sur le campus et les centres d’entreprise.']] },
    { name: 'Amont : puces et optique', order: 1, transmission: 'Les puces de commutation et l’optique conditionnent coût et délais de livraison.', rows: [
      ['AVGO', 'upstream', 'Fournisseur des puces de commutation', 'Ses puces Ethernet équipent les commutateurs : ses délais et prix pèsent sur la marge d’Arista.'],
      ['MRVL', 'upstream', 'Puces optiques et d’interconnexion', 'Ses composants optiques suivent le débit des nouveaux réseaux de clusters.'],
      ['COHR', 'upstream', 'Modules optiques à haut débit', 'Ses modules à 1,6 térabit conditionnent le passage des clusters à la nouvelle génération.'],
      ['LITE', 'upstream', 'Lasers et modules optiques', 'Ses capacités de production limitent le rythme de déploiement des réseaux optiques.'],
      ['AAOI', 'upstream', 'Modules optiques pour centres de données', 'Petit fournisseur très dépendant des clouds : un signal avancé de la demande optique.'],
      ['CRDO', 'upstream', 'Câbles et puces de connexion à haut débit', 'Ses câbles actifs relient serveurs et commutateurs dans les baies d’IA.']] },
    { name: 'Aval et second ordre : serveurs, optique longue distance et énergie', order: 2, transmission: 'Ils livrent le reste de la baie ou relient les sites entre eux.', rows: [
      ['DELL', 'downstream', 'Intégrateur de serveurs d’IA', 'Ses baies livrées hors grands clouds embarquent aussi du réseau : un débouché d’entreprise.'],
      ['SMCI', 'downstream', 'Intégrateur de serveurs d’IA', 'Ses livraisons de baies disent combien de clusters arrivent chez les néo-clouds.'],
      ['CIEN', 'second_order', 'Réseau optique longue distance', 'Les liaisons entre centres de données suivent le nombre de clusters construits.'],
      ['VRT', 'second_order', 'Alimentation et refroidissement', 'Ses délais de livraison fixent la date de mise en service des sites.']] },
    { name: 'Contrôles sectoriels', order: 2, transmission: 'Paniers de référence pour isoler ce qui est propre à Arista.', rows: [
      ['SMH', 'sector_proxy', 'Panier de semi-conducteurs', 'Contrôle de la demande de matériel d’IA dans son ensemble.'],
      ['IGV', 'sector_proxy', 'Panier de logiciels', 'Contrôle du style croissance technologique, hors matériel : isole l’effet de mode sur les valeurs de croissance.'],
      ['QQQ', 'sector_proxy', 'Grandes valeurs du Nasdaq', 'Contrôle large : un mouvement commun n’a rien de spécifique.']] },
  ],
  eventDefault: { leader: 'Aucune publication dans les quatorze jours collectés ; ses annonces de capex restent le signal à suivre', direct_peer: 'Aucune publication dans les quatorze jours collectés ; ses lancements de produits peuvent déplacer les parts', upstream: 'Aucune publication dans les quatorze jours collectés ; ses délais et prix pèsent sur les marges du réseau', downstream: 'Aucune publication dans les quatorze jours collectés ; ses livraisons de baies sont le signal à suivre', second_order: 'Aucune publication dans les quatorze jours collectés ; ses délais fixent les mises en service', sector_proxy: 'Panier sans publication propre ; exposé aux résultats de ses grandes pondérations' },
  eventRisk: { MRVL: 'Journée investisseurs le 6 octobre selon son communiqué du 27 août ; ses perspectives optiques se liront sur Arista' },
  blastDoc: 3,
  scenarios: c => [
    { scenario: 'bullish', trigger: 'Les grands clouds relèvent leur capex 2027 et la marge brute se stabilise au troisième trimestre.', firstOrder: 'Le titre reprend le plus haut du 5 août et sort de son couloir par le haut.', secondOrder: 'Les fournisseurs optiques et de puces de commutation suivent sur des volumes plus élevés.', confirmation: 'Une clôture au-dessus de 214,89 $ avec COHR et AVGO dans le même sens.', contradiction: 'Un grand cloud qui annonce passer au réseau intégré de Nvidia pour ses prochains clusters.' },
    { scenario: 'mixed', trigger: 'La croissance tient mais la marge continue de glisser.', firstOrder: 'Le titre reste dans son couloir entre le plus bas du 3 septembre et le plus haut du 5 août.', secondOrder: 'Les fournisseurs optiques progressent plus vite qu’Arista.', confirmation: 'Des clôtures qui butent sous 208 $ pendant que SMH progresse.', contradiction: 'Des revenus différés en forte hausse au prochain trimestre.' },
    { scenario: 'bearish', trigger: 'Un grand cloud ralentit ses commandes de réseau ou change de fournisseur.', firstOrder: 'La prévision déçoit et le titre casse le bas de son couloir.', secondOrder: 'Les fournisseurs optiques très dépendants des clouds, comme AAOI, baissent plus fort.', confirmation: 'Une clôture sous le plus bas du 3 septembre.', contradiction: 'Des engagements d’achat qui continuent de monter au 10-Q suivant.' }],
  contradictions: c => ['Le titre corrèle avec les paniers de semi-conducteurs, mais ses clients principaux sont des clouds dont la corrélation mesurée ne dit pas le poids commercial.', 'Nvidia apparaît à la fois comme moteur de la demande et comme concurrent direct ; la corrélation ne tranche pas entre ces deux effets.'],
  missingData: c => ['Les deux clients à 26 % et 16 % des ventes ne sont pas nommés : aucun client coté n’entre dans les comparables comme client documenté.', 'Chaîne d’options relevée marché fermé, inexploitable ; sentiment non retenu.', 'Flux de trésorerie libre sur douze mois non reconstitué : les investissements ne sont publiés au trimestre que sous une étiquette différente de l’annuel.'],
  limitations: ['Barres d’une source de repli (Webull).', 'Options inexploitables, marché fermé.', 'Clients dominants non nommés.'],
});
