'use strict';
// Dossier NBIS v3 au close du 2026-09-25 (lot R07). Émetteur privé étranger (Nebius Group N.V.) :
// dépôts 20-F/6-K, taxonomie IFRS, ZÉRO tag us-gaap dans companyfacts, devise fonctionnelle USD.
// Les agrégats financiers sont donc fournis par cfg.manualFinancials — chaque valeur est lue dans l'état
// financier du dépôt primaire (20-F 2025 + 6-K du 12 août 2026), liée par accession/formulaire/pointeur de
// document ; aucune valeur n'est dérivée ni estimée par le générateur. Base : douze mois glissants au
// 30 juin 2026 (exercice 2025 + premier semestre 2026 − premier semestre 2025) pour les flux ; bilan au
// 30 juin 2026. Scénario en EV/revenus (croissance forte, résultat opérationnel négatif : un multiple
// d'EBITDA n'a pas de sens). Comparables : 16 symboles IA-infra propres (CRWV élagué : 3 séances
// manquantes dans la fenêtre servie, corruption tournante non transitoire). peerFicheSha vide, aucune
// référence de fiche pair : les multiples des pairs sont lus dans comparison_context (peerStat courant).
const R = require('../../../../tools/lib/analysis-v3-r07.cjs');
const GEN = 'analyses/NBIS/_runs/20260927/build-nbis.cjs';

// Agrégats IFRS lus dans les dépôts primaires (USD). Flux = douze mois glissants au 30/06/2026.
const REV_TTM = 1355100000;   // 529.8 + 981.3 − 156.0 (M$) — 20-F 2025 + S1 2026 − S1 2025
const EBIT_TTM = -684100000;  // −611.7 + (−303.9) − (−231.5)
const DA_TTM = 765300000;     // 417.9 + 471.7 − 124.3
const NI_TTM = 42400000;      // 9.8 + 430.8 − 398.2 (activités poursuivies ; gonflé par produits financiers)
const DEBT = 8545700000;      // 8 499.0 (obligations convertibles) + 46.7 (dette courante) au 30/06/2026
const CASH = 8042100000;      // trésorerie et équivalents au 30/06/2026

const ACC_20F = '0001104659-26-052948', ACC_6K = '0001104659-26-094844', ACC_ATM = '0001104659-25-110025';

R.build({
  ticker: 'NBIS', shortName: 'Nebius', cik: 1513845, generator: GEN, mode: 'breakout',
  xbrl: { ttm: {}, instant: {}, da: ['da'], debt: ['debt'], cash: ['cash'] },
  manualFinancials: { figures: {
    rev:  { value: REV_TTM,  form: '6-K', accn: ACC_6K, start: '2025-07-01', end: '2026-06-30', doc: 1 },
    ebit: { value: EBIT_TTM, form: '6-K', accn: ACC_6K, start: '2025-07-01', end: '2026-06-30', doc: 1 },
    ni:   { value: NI_TTM,   form: '6-K', accn: ACC_6K, start: '2025-07-01', end: '2026-06-30', doc: 1 },
    da:   { value: DA_TTM,   form: '6-K', accn: ACC_6K, start: '2025-07-01', end: '2026-06-30', doc: 1 },
    debt: { value: DEBT,     form: '6-K', accn: ACC_6K, end: '2026-06-30', doc: 1 },
    cash: { value: CASH,     form: '6-K', accn: ACC_6K, end: '2026-06-30', doc: 1 },
  } },
  scenarioBasis: 'revenue', scenarioMultiple: 25,
  valuationBasis: 'Agrégats IFRS lus dans les dépôts primaires de Nebius (émetteur privé étranger, 20-F/6-K, devise fonctionnelle USD, aucun companyfacts us-gaap). Flux = douze mois glissants au 30 juin 2026, reconstitués de l’exercice 2025 (20-F) + premier semestre 2026 (6-K du 12 août 2026) − premier semestre 2025 : revenus 1 355,1 M$, perte opérationnelle 684,1 M$, amortissements 765,3 M$. Bilan au 30 juin 2026 : trésorerie 8 042,1 M$ ; dette financière 8 545,7 M$ (obligations convertibles, hors 1 625,3 M$ de dettes de location) ; 271 855 218 actions ordinaires en circulation, toutes classes comprises. Multiple de vingt-cinq fois les revenus = hypothèse éditoriale.',
  levels: { trigger: { d: '2026-09-08', c: 2 }, stop: { d: '2026-09-23', c: 3 }, abandon: { d: '2026-09-14', c: 3 }, s1: { d: '2026-09-25', c: 3 }, s2: { d: '2026-09-11', c: 3 }, r1: { d: '2026-09-22', c: 2 }, r2: { d: '2026-09-24', c: 2 } },
  supports: ['s1', 'stop', 's2'], resistances: ['r1', 'r2', 'trigger'],
  targets: ({ entry, abandon }) => { const range = entry - abandon; return { tp1: entry + range, tp2: entry + 1.5 * range, range }; },
  levelsMethod: 'Déclencheur = plus haut du 8 septembre, sommet du rebond de septembre ; bas du couloir = plus bas du 14 septembre ; stop = plus bas du 23 septembre ; TP1 = déclencheur + hauteur du couloir ; TP2 = déclencheur + 1,5 × hauteur ; plafond = (TP1 + 1,5 × stop) / 2,5 arrondi au cent inférieur ; pourcentages depuis l’entrée ; R/R = gain / risque.',
  inventory: 34,
  reviewScope: 'Dépôts EDGAR de Nebius Group N.V. (CIK 1513845) revus jusqu’au 25 septembre 2026 : le 20-F de l’exercice clos le 31 décembre 2025, le 6-K du 12 août 2026 (résultats et états financiers condensés des trois et six mois clos le 30 juin 2026 et le 30 juin 2025), le 6-K du 20 mai 2026 (premier trimestre) et le prospectus 424B5 du 12 novembre 2025 (programme d’émission d’actions sur le marché). Les levées historiques (offre secondaire de 1,0 Md$ en septembre 2025, notes convertibles) sont reprises par la note 12 et l’état des capitaux propres du 6-K du 12 août ; les formulaires de gouvernance et les Schedule 13G des grands actionnaires sont écartés du décompte décisionnel.',
  docs: [
    ['2026-04-30', '20-F', ACC_20F, 'nbis-20251231x20f.htm', 'fy25-20f__nbis-20251231x20f.htm',
      'Rapport annuel de l’exercice clos le 31 décembre 2025 (IFRS, USD) : revenus des activités poursuivies de 529,8 M$ (contre 91,5 M$), perte opérationnelle de 611,7 M$, amortissements de 417,9 M$, trésorerie de 3 678,1 M$ et dette non courante de 4 103,2 M$ au 31 décembre 2025.', 1513845],
    ['2026-08-12', '6-K', ACC_6K, 'nbis-20260812xex99d2.htm', 'q2-6k-fs__nbis-20260812xex99d2.htm',
      'États financiers condensés non audités des trois et six mois clos le 30 juin 2026 et 2025 : revenus du semestre de 981,3 M$ (contre 156,0 M$), perte opérationnelle de 303,9 M$, amortissements de 471,7 M$ ; au 30 juin 2026, trésorerie de 8 042,1 M$, dette financière de 8 545,7 M$ (obligations convertibles, principal de 10 041,8 M$), 271 855 218 actions ordinaires en circulation, émission de bons de souscription préfinancés de 2 000,0 M$ à Nvidia et cession de titres autodétenus pour 2 846,7 M$.', 1513845],
    ['2026-08-12', '6-K / communiqué', ACC_6K, 'nbis-20260812xex99d1.htm', 'q2-6k-pr__nbis-20260812xex99d1.htm',
      'Communiqué du deuxième trimestre 2026 : revenus trimestriels de 582,3 M$ (contre 105,1 M$), croissance portée par la location de capacité de calcul GPU aux entreprises et laboratoires d’IA ; commentaire de la direction sur l’expansion des centres de données et le carnet de commandes.', 1513845],
    ['2026-08-12', '6-K / page de garde', ACC_6K, 'nbis-20260812x6k.htm', 'q2-6k__nbis-20260812x6k.htm',
      'Page de garde du dépôt 6-K du 12 août 2026 renvoyant aux états financiers condensés (annexe 99.2) et au communiqué (annexe 99.1) des trois et six mois clos le 30 juin 2026 et 2025.', 1513845],
    ['2025-11-12', '424B5', ACC_ATM, 'tm2530771-1_424b5.htm', 'nov25-424b5-atm__tm2530771-1_424b5.htm',
      'Prospectus complémentaire d’un programme d’émission d’actions sur le marché portant sur un maximum de 25 000 000 d’actions ordinaires de catégorie A, via un accord de distribution avec Goldman Sachs, Morgan Stanley et d’autres agents : dilution potentielle à la main de la société, au fil de l’eau.', 1513845],
  ],
  needles: {
    rev: [1, ['Revenues', 'Total revenues', '981.3', '156.0']],
    ni: [1, ['Net income / (loss) from continuing operations', '430.8', '398.2']],
    ebit: [1, ['Loss from operations', '(303.9)', '(231.5)']],
    da: [1, ['Depreciation and amortization', '471.7', '124.3']],
    bal: [1, ['Cash and cash equivalents', '8,042.1', 'Debt, non-current', '8,499.0', 'Debt, current', '46.7', 'Total convertible debt', '10,041.8']],
    shares: [1, ['271,855,218', '238,400,165', '33,455,053']],
    capital: [1, ['Issuance of pre-funded warrants', '2,000.0', 'Proceeds from sale of treasury shares', '2,846.7']],
    annual: [0, ['529.8', '(611.7)', '417.9', '3,678.1', '4,103.2']],
    atm: [4, ['25,000,000', 'at-the-market', 'Class A ordinary shares']],
  },
  sectionDocs: { verdict: [1, 2, 0], business: [1, 2, 0], news: [1, 2], earnings: [1, 2], capitalStructure: [1, 4, 0], filingsReview: [0, 1, 2, 3, 4], risks: [1, 4, 0], globalScore: [1], meta: [1], disclaimer: [1], macro: [0], options: [1], social: [1], header: [1], shortInterest: [1], insiders: [1] },
  score: { business: 30, technical: 6, capital: -2, calendar: 0, dilution: -8, risk: 20 },
  peers: true,
  peerFicheSha: {},
  shares: { value: 271855218, doc: 1 },
  route: (p, { prov, dep, B }) => /^news\.[13]\./.test(p) ? prov('bars', B, 'Ouverture et clôture lues sur les barres certifiées ; variations calculées de clôture à clôture ; comparaison avec les pairs sur la même séance.', [dep('comparison', '')]) : null,
  riskScoreReason: 'Jugement qualitatif sur dix : titre à environ quarante-huit fois ses revenus des douze derniers mois, perte opérationnelle et investissements massifs financés par obligations convertibles, dilution active (programme d’émission d’actions, bons préfinancés, cession de titres autodétenus), position vendeuse proche de 20 % du flottant et amplitude journalière moyenne de plus de 16 $.',
  compose: c => {
    const { fr, usd, pct, sgn, close, prev, bars, N, tech, st, M, adv, ret, G$, marketCap, ev, scn, lv, entry, stop, tp1, tp2, abandon, cap, rr1, rr2, riskAtr, sizeExample, ref, market, docs, raw, peerStat } = c;
    const gs = c.gapStats(cap - entry), bufAtr = (cap - entry) / tech.atr14, blocked = gs.up / gs.total * 100;
    const bufPct = (cap / entry - 1) * 100, bk = c.breakoutStats(bufPct), rt = c.retestStats(bufPct, (1 - stop / entry) * 100);
    const cmp = raw.comparison_bars.data.items[0].results[0].data;
    const dr = (sym, d) => { const b = cmp.find(x => x.symbol === sym).bars, i = b.findIndex(x => x[0] === d); return pct(b[i][4], b[i - 1][4]); };
    const bar = d => bars.find(b => b[0] === d), prevOf = d => bars[bars.findIndex(b => b[0] === d) - 1];
    const d0908 = bar('2026-09-08'), d0925 = bar('2026-09-25'), d0924 = bar('2026-09-24');
    // plus bas et plus haut sur 252 séances
    const win = bars.slice(Math.max(0, N - 251), N + 1); let hi = -1, lo = 1e9, hiD, loD;
    for (const b of win) { if (b[2] > hi) { hi = b[2]; hiD = b[0]; } if (b[3] < lo) { lo = b[3]; loD = b[0]; } }
    const run = close / lo;
    const y0 = bars.find(b => b[0] >= '2026-01-02'), ytd = pct(close, y0[4]);
    const evRev = ev / G$.rev, opMargin = G$.ebit / G$.rev * 100, ebitda = G$.ebitda;
    const aplxEv = peerStat('APLD', 'enterpriseToRevenue'), nvdaEv = peerStat('NVDA', 'enterpriseToRevenue'), amdEv = peerStat('AMD', 'enterpriseToRevenue'), msftEv = peerStat('MSFT', 'enterpriseToRevenue'), orclEv = peerStat('ORCL', 'enterpriseToRevenue'), anetEv = peerStat('ANET', 'enterpriseToRevenue');
    const ext20 = pct(close, tech.ema20);
    const big = Math.floor(1000 / (cap - stop));
    const siPct = st.shortPercentOfFloat * 100;
    return {
      meta: { lang: 'fr', dir: 'ltr', level: 'intermediate', tags: ['us', 'equities', 'ai-chain', 'infrastructure', 'communication-services'], grade: 'C+', date: '2026-09-25', dateDisplay: '25 septembre 2026', version: 3, status: 'watch', assetType: 'stock', levelsCloseDate: c.REF,
        description: 'Nebius Group : loueur de calcul GPU coté au Nasdaq (émetteur étranger, IFRS). Revenus multipliés par plus de six sur un an, 8,0 Md$ de trésorerie et Nvidia au capital, mais exploitation déficitaire et valorisation proche de 48 fois les revenus. Close du 25 septembre 2026, statut surveiller.',
        ogDescription: 'Nebius (NBIS) : revenus du S1 2026 de 981 M$ contre 156 M$, 8,0 Md$ de trésorerie ; titre à 237,33 $, environ 6 % sous son sommet du 8 septembre. Niveaux à surveiller.',
        lastMcpRefresh: raw.status.captured_at, levelsVerifiedAt: raw.status.captured_at,
        statusHistory: [...(c.archive.meta.statusHistory || []), { at: raw.status.captured_at, from: c.archive.meta.status || 'rejected', to: 'watch', note: 'refonte v3 harnachée du 25 septembre : émetteur étranger IFRS (20-F/6-K) via agrégats de dépôt primaire, base douze mois glissants au 30 juin 2026, comparables IA-infra propres à seize symboles', close }] },
      header: { ticker: 'NBIS', name: 'Nebius Group N.V.', exchange: 'NASDAQ', sector: 'Infrastructure de calcul GPU pour l’IA (cloud)', price: close, changePct: pct(close, prev),
        badges: [{ text: 'SURVEILLER — ACTIVATION AU-DESSUS DU SOMMET DU 8 SEPTEMBRE', color: 'blue' }, { text: 'Chaîne IA — loueur de calcul GPU', color: 'purple' }],
        metrics: { marketCap: fr(marketCap / 1e9, 1) + ' Md$', volume: fr(bars[N][5] / 1e6, 2) + ' M', evRevenue: fr(evRev, 1) + '×' }, halalStatus: 'unknown' },
      verdict: { score: 46, conviction: 'Moderate', bias: 'Neutral',
        confidence: 'Score éditorial non prédictif. Les chiffres d’entreprise sont lus dans les états financiers IFRS des dépôts primaires (20-F 2025 et 6-K du 12 août 2026) ; les niveaux, sur le close certifié du 25 septembre.',
        summary: 'Nebius loue de la capacité de calcul GPU à des entreprises et des laboratoires d’IA. La croissance est spectaculaire : au premier semestre 2026, les revenus atteignent ' + fr(981.3, 1) + ' M$ contre ' + fr(156.0, 1) + ' M$ un an plus tôt. Mais elle se paie : la perte opérationnelle des douze derniers mois est de ' + fr(-G$.ebit / 1e6, 0) + ' M$, les amortissements du parc GPU pèsent ' + fr(G$.da / 1e6, 0) + ' M$, et l’expansion, chiffrée en milliards, est financée par obligations convertibles (principal de 10 041,8 M$ au 30 juin) et cession de titres autodétenus. Au close du 25 septembre, ' + usd(close) + ' (' + sgn(pct(close, prev), 1) + '), le titre capitalise environ ' + fr(marketCap / 1e9, 0) + ' Md$, soit ' + fr(evRev, 0) + ' fois ses revenus des douze derniers mois — bien au-dessus de son pair direct Applied Digital (' + fr(aplxEv, 0) + '×) et de Nvidia (' + fr(nvdaEv, 0) + '×). Il a triplé depuis son plus bas de février (' + usd(lo) + ') et gagné ' + fr(ytd, 0) + ' % depuis janvier, mais reste ' + fr(Math.abs(pct(close, hi)), 0) + ' % sous son sommet de juin (' + usd(hi) + ') et ' + fr(Math.abs(pct(close, entry)), 1) + ' % sous celui du 8 septembre (' + usd(entry) + '). Deux atouts rares : ' + fr(G$.cash / 1e9, 1) + ' Md$ de trésorerie et Nvidia au capital, avec une participation et 2,0 Md$ de bons préfinancés. Signal utile : une clôture au-dessus de ' + usd(entry) + '. Statut surveiller : le titre n’a pas repris ce niveau.',
        whyBuy: [
          'Revenus multipliés par plus de six sur un an : ' + fr(981.3, 1) + ' M$ au premier semestre 2026 contre ' + fr(156.0, 1) + ' M$ un an plus tôt.',
          fr(G$.cash / 1e9, 1) + ' Md$ de trésorerie au 30 juin, de quoi financer l’expansion sans dépendre à court terme du marché.',
          'Nvidia au capital, avec une participation déclarée et 2,0 Md$ de bons de souscription préfinancés : une validation stratégique rare pour un loueur de calcul.',
          'Titre au-dessus de ses moyennes à vingt, cinquante et deux cents séances, dans une tendance de fond haussière (' + sgn(ytd, 0) + ' % depuis janvier).'],
        whyAvoid: [
          'Valorisation de ' + fr(evRev, 0) + ' fois les revenus, plus du double du pair direct Applied Digital (' + fr(aplxEv, 0) + '×) : la croissance est déjà largement dans le prix.',
          'Perte opérationnelle de ' + fr(-G$.ebit / 1e6, 0) + ' M$ sur douze mois et investissements de plusieurs milliards financés par obligations convertibles.',
          'Dilution active : programme d’émission d’actions sur le marché (jusqu’à 25 millions d’actions A), bons préfinancés et cession de titres autodétenus.',
          'Position vendeuse d’environ ' + fr(siPct, 0) + ' % du flottant et amplitude journalière moyenne de ' + usd(tech.atr14) + ' : les écarts brutaux sont la norme.'],
        controlChecklist: [
          { label: 'Historique de cours', status: 'pass', statusLabel: 'Trois cents séances continues', evidence: 'Série quotidienne certifiée au close du 25 septembre.', action: 'Niveaux et indicateurs recalculés sur cette seule série.' },
          { label: 'Comptes', status: 'warn', statusLabel: 'Émetteur étranger, IFRS', evidence: 'Nebius dépose 20-F/6-K, pas de 10-K/10-Q ; aucun agrégat us-gaap XBRL. Les chiffres sont lus dans les états IFRS des dépôts primaires, base douze mois glissants au 30 juin 2026.', action: 'Lire les agrégats comme des reconstitutions de dépôt, non comme un flux XBRL standardisé.' },
          { label: 'Entrée', status: 'warn', statusLabel: 'Plafond à ' + fr(bufAtr, 2) + ' ATR', evidence: 'Le plafond d’achat n’est qu’à ' + usd(cap - entry) + ' au-dessus du déclencheur, pour une amplitude journalière moyenne de ' + usd(tech.atr14) + '.', action: 'Accepter de rater le mouvement plutôt que d’acheter au-dessus du plafond.' }] },
      business: { theme: 'Location de capacité de calcul GPU pour l’intelligence artificielle',
        overview: '<p>Nebius Group construit et exploite des centres de données remplis de processeurs graphiques qu’elle loue à des entreprises et des laboratoires d’intelligence artificielle. Née de la scission des actifs internationaux de Yandex en 2024, la société est un émetteur privé étranger coté au Nasdaq : elle publie ses comptes en normes IFRS et en dollars, via des formulaires 20-F annuels et 6-K intermédiaires, et non les 10-K/10-Q américains.</p><p>La croissance est le fait marquant. Les revenus des activités poursuivies sont passés de ' + fr(91.5, 1) + ' M$ en 2024 à ' + fr(529.8, 1) + ' M$ en 2025, puis à ' + fr(981.3, 1) + ' M$ pour le seul premier semestre 2026, contre ' + fr(156.0, 1) + ' M$ un an plus tôt. Le cœur du métier — l’infrastructure de calcul — est complété par des participations dans plusieurs activités liées à l’IA (données d’entraînement, conduite autonome, formation).</p><p>Le revers est dans le compte de résultat et les flux : l’exploitation reste déficitaire (perte opérationnelle de ' + fr(-G$.ebit / 1e6, 0) + ' M$ sur douze mois), les amortissements du parc GPU sont lourds (' + fr(G$.da / 1e6, 0) + ' M$) et les achats d’équipements se comptent en milliards. Ce modèle exige un capital constant : Nebius l’a levé par obligations convertibles, par un programme d’émission d’actions et par la cession de titres autodétenus, et compte Nvidia à son capital.</p>',
        moat: 'L’avantage tient à l’accès aux processeurs graphiques, au capital et à la vitesse de construction. Disposer d’allocations de GPU et pouvoir financer des centres de données entiers distingue Nebius d’un simple hébergeur ; la présence de Nvidia au capital renforce cet accès. Mais l’avantage est fragile : la valeur d’un serveur d’IA est captée surtout par le fournisseur de puces, les grands clouds louent la même capacité, et un client peut mettre plusieurs loueurs en concurrence.',
        segments: [
          { name: 'Infrastructure de calcul (cœur)', revenue: '981,3 M$ au premier semestre 2026', pct: 'Quasi-totalité des revenus', description: 'Location de capacité de calcul GPU à des entreprises et laboratoires d’IA ; revenus multipliés par plus de six sur un an.' },
          { name: 'Participations liées à l’IA', revenue: 'Non détaillé par les états condensés', pct: 'Appoint', description: 'Activités de données d’entraînement, de conduite autonome et de formation, portées en participations plutôt qu’en revenus consolidés.' }],
        sourceRefs: [ref(1), ref(2), ref(0)],
        coverageMatrix: [
          { facet: 'Cours et historique', status: 'COUVERT', decision: 'Trois cents séances continues, close certifié ; base des niveaux et des indicateurs.' },
          { facet: 'Comptes et agrégats', status: 'COUVERT — PRIMAIRE IFRS', decision: 'Agrégats lus dans le 20-F 2025 et le 6-K du 12 août 2026 ; douze mois glissants au 30 juin 2026 ; aucun companyfacts us-gaap n’existe pour cet émetteur.' },
          { facet: 'Capital et dette', status: 'COUVERT — PRIMAIRE', decision: 'Obligations convertibles, bons préfinancés Nvidia, cession de titres autodétenus et programme d’émission d’actions séparés.' },
          { facet: 'Comparables et transmission', status: 'COUVERT — LOCAL', decision: 'Corrélations recalculées sur barres certifiées, seize comparables IA-infra propres (CoreWeave élagué pour trous de barres).' },
          { facet: 'Position vendeuse', status: 'COUVERT — SNAPSHOT', decision: 'Environ 20 % du flottant, 2,76 jours de couverture ; date de règlement non précisée par le snapshot.' },
          { facet: 'Coût d’emprunt et dark pool', status: 'NON EXPLOITABLE', decision: 'Coût d’emprunt indisponible à la collecte (fournisseur en échec) ; aucun flux directionnel inféré.' },
          { facet: 'Options et sentiment social', status: 'NON EXPLOITABLE', decision: 'Chaîne d’options non servie à la collecte ; ni Reddit ni Google Trends pour ce titre.' }] },
      news: [
        { date: '2026-08-12', title: 'Résultats du premier semestre 2026 : revenus de ' + fr(981.3, 1) + ' M$, contre ' + fr(156.0, 1) + ' M$ un an plus tôt', impact: 'positive', detail: 'Le 6-K du 12 août présente des revenus semestriels de ' + fr(981.3, 1) + ' M$ (' + fr(582.3, 1) + ' M$ pour le seul deuxième trimestre), soit plus de six fois le semestre précédent, portés par la location de calcul GPU. La perte opérationnelle du semestre reste de ' + fr(303.9, 1) + ' M$ : la demande dépasse largement l’offre, mais l’exploitation n’est pas encore rentable.', source: 'Nebius — SEC', sourceUrl: docs[1].url },
        { date: '2026-09-08', title: 'Sommet du rebond de septembre à ' + usd(entry) + ', puis consolidation', impact: 'neutral', detail: 'Le titre touche ' + usd(entry) + ' en séance le 8 septembre (clôture ' + usd(d0908[4]) + '), sommet du rebond, avant de refluer. SMH fait ' + sgn(dr('SMH', '2026-09-08'), 2) + ' et Nvidia ' + sgn(dr('NVDA', '2026-09-08'), 2) + ' la même séance : le mouvement accompagne le secteur des semi-conducteurs sans lui être étranger.', source: 'Barres certifiées', sourceUrl: c.evidenceUrl },
        { date: '2026-08-12', title: 'Nvidia au capital et bons de souscription préfinancés de 2,0 Md$', impact: 'positive', detail: 'L’état des capitaux propres du 6-K enregistre l’émission de 2,0 Md$ de bons de souscription préfinancés à Nvidia et la cession de titres autodétenus pour ' + fr(2846.7, 1) + ' M$. Nvidia est à la fois fournisseur de puces, actionnaire et détenteur de bons : une validation stratégique, mais aussi une source de titres à venir.', source: 'Nebius — SEC', sourceUrl: docs[1].url },
        { date: '2026-09-25', title: 'Clôture en repli de ' + fr(Math.abs(pct(close, prev)), 1) + ' % à ' + usd(close), impact: 'neutral', detail: 'Après un rebond à ' + usd(d0924[4]) + ' le 24, le titre ouvre à ' + usd(d0925[1]) + ' et clôture à ' + usd(close) + ' (' + sgn(pct(close, prev), 2) + '), sous son sommet du 8 septembre. SMH fait ' + sgn(dr('SMH', '2026-09-25'), 2) + ' et Applied Digital ' + sgn(dr('APLD', '2026-09-25'), 2) + ' la même séance ; le repli est surtout propre au titre.', source: 'Barres certifiées', sourceUrl: c.evidenceUrl }],
      fundamentals: { rows: [
          { metric: 'Revenus du premier semestre 2026', value: '981,3 M$', signal: '+529 % sur un an (156,0 M$ au premier semestre 2025)', signalColor: 'green', _src: 1 },
          { metric: 'Revenus de l’exercice 2025', value: '529,8 M$', signal: 'Contre 91,5 M$ en 2024 (activités poursuivies, IFRS)', signalColor: 'green', _src: 0 },
          { metric: 'Revenus sur douze mois glissants', value: fr(G$.rev / 1e6, 1) + ' M$', signal: 'Exercice 2025 + premier semestre 2026 − premier semestre 2025, au 30 juin 2026', signalColor: 'blue', _src: 'gaap' },
          { metric: 'Résultat opérationnel sur douze mois', value: fr(G$.ebit / 1e6, 1) + ' M$', signal: 'Perte ; marge opérationnelle de ' + fr(opMargin, 0) + ' %, douze mois au 30 juin 2026', signalColor: 'red', _src: 'gaap' },
          { metric: 'EBITDA sur douze mois', value: fr(ebitda / 1e6, 1) + ' M$', signal: 'À peine positif : les amortissements du parc GPU (' + fr(G$.da / 1e6, 0) + ' M$) absorbent presque toute la marge brute', signalColor: 'amber', _src: 'gaap' },
          { metric: 'Résultat net sur douze mois (activités poursuivies)', value: fr(G$.ni / 1e6, 1) + ' M$', signal: 'Positif mais gonflé par des produits financiers et des réévaluations de titres, pas par l’exploitation', signalColor: 'amber', _src: 'gaap' },
          { metric: 'Trésorerie au 30 juin 2026', value: fr(G$.cash / 1e9, 2) + ' Md$', signal: 'Trésorerie et équivalents ; contre 3,68 Md$ au 31 décembre 2025', signalColor: 'green', _src: 'gaap' },
          { metric: 'Dette financière au 30 juin 2026', value: fr(G$.debt / 1e9, 2) + ' Md$', signal: 'Obligations convertibles (principal 10 041,8 M$) ; hors 1 625,3 M$ de dettes de location', signalColor: 'amber', _src: 'gaap' },
          { metric: 'Investissements du premier semestre 2026', value: '8 130,3 M$', signal: 'Achats d’équipements et d’actifs incorporels ; le modèle exige un capital constant', signalColor: 'red', _src: 1 },
          { metric: 'EV/revenus douze mois glissants', value: fr(evRev, 1) + '×', signal: 'Valeur d’entreprise (enterprise value) au close du 2026-09-25 (271,9 M d’actions, dette convertible comprise) sur revenus douze mois glissants (trailing) au 30 juin 2026', signalColor: 'red', source: 'Clôture certifiée et dépôts primaires', comparison: 'Versus Applied Digital à ' + fr(aplxEv, 1) + '×, Nvidia à ' + fr(nvdaEv, 1) + '×, AMD à ' + fr(amdEv, 1) + '× et Arista à ' + fr(anetEv, 1) + '× (statistiques courantes du 24 septembre, non point-in-time) : Nebius se paie plus cher que tout son voisinage IA-infra.', _src: 'market', _peers: ['APLD', 'NVDA', 'AMD', 'ANET'], _peerField: 'enterpriseToRevenue' },
          { metric: 'EV/revenus — scénario de compression (hypothèse éditoriale)', value: fr(scn.price, 2) + ' $ par action', signal: 'Scenario : multiple ramené par hypothèse à vingt-cinq fois les revenus douze mois, bilan du 30 juin, soit ' + fr(scn.downside_pct, 0) + ' % sous le close du 2026-09-25', signalColor: 'red', source: 'Clôture certifiée et dépôts primaires', comparison: 'Versus Nvidia à ' + fr(nvdaEv, 1) + '× et Microsoft à ' + fr(msftEv, 1) + '× : vingt-cinq fois resterait une prime de croissance, pas un plancher ; ce que coûterait un simple retour vers les multiples des grands noms de l’IA, pas un objectif.', _src: 'market', _peers: ['NVDA', 'MSFT'], _peerField: 'enterpriseToRevenue' },
          { metric: 'Obligations convertibles — principal', value: '10 041,8 M$', signal: 'Principal en circulation au 30 juin 2026 (valeur comptable 8 499,0 M$) ; conversion potentiellement dilutive', signalColor: 'amber', _src: 1 },
          { metric: 'Bons de souscription préfinancés (Nvidia)', value: '2 000,0 M$', signal: 'Émis à Nvidia au premier semestre 2026 ; donneront des actions', signalColor: 'amber', _src: 1 },
          { metric: 'Cession de titres autodétenus (S1 2026)', value: '2 846,7 M$', signal: 'Augmente le nombre d’actions négociables', signalColor: 'amber', _src: 1 },
          { metric: 'Actions ordinaires en circulation', value: '271 855 218', signal: 'Au 30 juin 2026, toutes classes ; contre 253 016 971 au 31 décembre 2025', signalColor: 'blue', _src: 1 },
          { metric: 'Flux de trésorerie d’exploitation (S1 2026)', value: '4 504,1 M$', signal: 'Gonflé par des encaissements clients d’avance, non par le résultat ; à lire avec prudence', signalColor: 'amber', _src: 1 }],
        sourceRefs: [ref(0), ref(1), market('agrégats et statistiques comparables')] },
      earnings: { quarters: [],
        beatNote: 'Premier semestre 2026 (6-K du 12 août) : revenus de 981,3 M$ (contre 156,0 M$), dont 582,3 M$ au deuxième trimestre (contre 105,1 M$) ; perte opérationnelle du semestre de 303,9 M$ (contre 231,5 M$) ; amortissements de 471,7 M$. L’exercice 2025 (20-F) affichait 529,8 M$ de revenus, une perte opérationnelle de 611,7 M$ et 417,9 M$ d’amortissements. Émetteur étranger : publication semestrielle, pas de guidance chiffrée standardisée dans les états condensés ouverts (outlook non chiffré). Aucune date de prochaine publication n’est confirmée par l’émetteur.',
        nextEarnings: 'Date non confirmée par l’émetteur ; cadence de publication semestrielle (6-K). Aucun événement de résultats n’est signalé dans l’horizon du plan par le calendrier collecté.',
        sourceRefs: [ref(1)] },
      capitalStructure: { sharesOutstanding: '271 855 218 actions ordinaires en circulation au 30 juin 2026 : 238 400 165 actions de catégorie A et 33 455 053 de catégorie B (états financiers condensés du 6-K du 12 août)',
        sharesAuthorized: 'Capacité d’émission : programme d’actions sur le marché de 25 millions d’actions A actif.', dilutionRisk: 'high',
        shareHistory: 'Base retenue : actions A et B en circulation, toutes classes comprises, car la valorisation porte sur la société entière. Le financement du modèle passe par plusieurs canaux dilutifs ou quasi-dilutifs. Obligations convertibles d’abord : le principal en circulation atteint 10 041,8 M$ au 30 juin 2026 (valeur comptable 8 499,0 M$), après une émission de 4,34 Md$ en mars 2026 qui s’ajoute aux souches de 2025 ; leur conversion créerait des actions nouvelles. Bons de souscription préfinancés ensuite : 2,0 Md$ émis à Nvidia, comptabilisés dans les capitaux propres, qui donneront des actions. Cession de titres autodétenus enfin : 2 846,7 M$ au premier semestre 2026, qui augmentent le nombre d’actions négociables. À cela s’ajoute un programme d’émission d’actions sur le marché portant sur jusqu’à 25 millions d’actions A (prospectus 424B5 du 12 novembre 2025), à la main de la société. Le nombre d’actions ordinaires en circulation est ainsi passé de 253 016 971 au 31 décembre 2025 à 271 855 218 au 30 juin 2026. Passage au nombre pleinement dilué : le compte d’actions diluées intégrant la conversion des obligations et l’exercice des bons préfinancés n’est pas isolé dans les états condensés ouverts (non disponible ici) ; il serait sensiblement supérieur aux 271 855 218 actions de base. Face à cette dilution, la trésorerie est solide (8,04 Md$) et la dette est convertible plutôt que classique ; il n’en reste pas moins que le risque de dilution est élevé.',
        warrants: [], atm: { active: true, authorized: 'Jusqu’à 25 000 000 d’actions de catégorie A (prospectus 424B5 du 12 novembre 2025)', used: 'Montant utilisé non détaillé dans les dépôts ouverts', remaining: 'Capacité restante non détaillée' },
        sourceRefs: [ref(1), ref(4), ref(0)] },
      filingsReview: { summary: 'Cinq dépôts décisionnels ouverts et hachés : le 20-F 2025, les états financiers et le communiqué du 6-K du 12 août 2026, sa page de garde, et le prospectus 424B5 du programme d’émission d’actions. Ils montrent une croissance des revenus par plus de six, une exploitation encore déficitaire, des investissements de plusieurs milliards, et un financement par obligations convertibles, bons préfinancés Nvidia, cession de titres autodétenus et programme d’actions sur le marché.',
        filings: docs.map(d => ({ date: d.date, form: d.form, accession: d.accession, finding: d.finding, url: d.url })),
        contrarianRisks: [
          'La croissance des revenus peut ralentir si l’allocation de GPU se resserre ou si les grands clouds baissent les prix de la location de calcul.',
          'L’exploitation reste déficitaire : rien ne garantit le passage à la rentabilité au rythme d’investissement actuel.',
          'La conversion des obligations et l’exercice des bons préfinancés créeraient des actions nouvelles, au-delà du programme d’émission déjà actif.',
          'Le résultat net positif des douze derniers mois vient de produits financiers et de réévaluations, pas de l’exploitation : il peut s’inverser.'] },
      technicals: { rsi14: +tech.rsi14.toFixed(2), macd: +tech.macd.toFixed(2), macdSignal: +tech.macdSignal.toFixed(2), ema20: +tech.ema20.toFixed(2), ema50: +tech.ema50.toFixed(2), ema200: +tech.ema200.toFixed(2),
        ma50Type: 'EMA', ma200Type: 'EMA', ma50Available: true, ma200Available: true, atr14: +tech.atr14.toFixed(2),
        badges: ['Au-dessus des moyennes à vingt, cinquante et deux cents séances', fr(Math.abs(pct(close, entry)), 1) + ' % sous le sommet du 8 septembre', 'ATR de ' + usd(tech.atr14)],
        supports: [lv('s1'), stop, lv('s2')], resistances: [lv('r1'), lv('r2'), entry],
        setupNote: 'Le titre clôture à ' + usd(close) + ', ' + fr(ext20, 1) + ' % au-dessus de sa moyenne à vingt séances et ' + fr(Math.abs(pct(close, entry)), 1) + ' % sous le sommet du 8 septembre, ' + usd(entry) + '. Il a triplé depuis son plus bas de février (' + usd(lo) + ') et reste ' + fr(Math.abs(pct(close, hi)), 0) + ' % sous son sommet de juin (' + usd(hi) + '). Avant activation, aucune entrée ; une clôture sous ' + usd(abandon) + ', le bas du 14 septembre, abandonne le scénario. Activation sur une clôture au-dessus de $' + entry.toFixed(2) + '. Après activation, stop sous $' + stop.toFixed(2) + ', le plus bas du 23 septembre, soit ' + fr(riskAtr, 2) + ' ATR sous le déclencheur. Supports : ' + usd(lv('s1')) + ', ' + usd(stop) + ' et ' + usd(lv('s2')) + '. Résistances : ' + usd(lv('r1')) + ', ' + usd(lv('r2')) + ' et ' + usd(entry) + ' ; au-delà, la zone du sommet de juin, ' + usd(hi) + ', est le prochain obstacle.',
        wyckoff: 'Non utilisé : le profil de volume n’est pas exploité dans ce dossier.',
        sourceRefs: [market('barres quotidiennes et indicateurs recalculés')] },
      options: { callOI: 'Non exploitable', putOI: 'Non exploitable', cpRatio: 'Non exploitable', maxPain: 'Non exploitable', ivMean: 'Non exploitable', skew: 'Chaîne d’options non servie à la collecte du 28 septembre', unusual: 'Aucune activité inhabituelle qualifiée', sourceRefs: [market('options')] },
      shortInterest: { siPct: fr(siPct, 2) + ' % du flottant', daysToCover: fr(st.shortRatio, 2) + ' jours, date de règlement non précisée par le snapshot', ctb: 'Coût d’emprunt indisponible à la collecte (fournisseur en échec)', trend: 'Position vendeuse élevée pour une valeur de cette taille : proche de 20 % du flottant. Elle peut amplifier les mouvements dans les deux sens, mais aucune thèse de rachat forcé n’est établie ici.', squeezeScore: 'Non quantifié faute de coût d’emprunt', sourceRefs: [market('positions vendeuses')] },
      insiders: { signal: 'Aucun solde net d’initiés affirmé : la couverture officielle des transactions d’initiés est partielle pour un émetteur étranger, dont les dirigeants ne déposent pas systématiquement de formulaires 4. Le fait capitalistique marquant du semestre n’est pas une transaction d’initié classique mais l’entrée de Nvidia au capital, avec une participation et 2,0 Md$ de bons de souscription préfinancés.',
        recentTransactions: [],
        sourceRefs: [market('transactions d’initiés — couverture partielle')] },
      macro: { indicators: [{ name: 'Clôture de référence', value: c.REF, signal: usd(close) + ', séance complète' }, { name: 'Rendement cinq séances', value: sgn(ret(5)), signal: 'Descriptif' }, { name: 'Rendement vingt et une séances', value: sgn(ret(21)), signal: 'Descriptif' }],
        regime: 'neutral', impact: 'Nebius vit de l’investissement des entreprises et des laboratoires dans l’intelligence artificielle. Un ralentissement des dépenses d’équipement en IA, une hausse du coût du capital ou un resserrement de l’allocation de GPU toucheraient directement un modèle qui investit plusieurs milliards par semestre et se finance sur les marchés.' },
      risks: { riskScore: 7, riskProfile: 'High',
        riskSummary: 'Le risque de Nebius n’est pas la demande, spectaculaire, mais le prix et le financement de sa croissance : environ ' + fr(evRev, 0) + ' fois les revenus, une exploitation déficitaire, des investissements de plusieurs milliards et une dilution active. Le titre, triplé depuis février, reste très volatil, avec une position vendeuse proche de 20 % du flottant. L’entrée proposée laisse peu de marge au-dessus du déclencheur.',
        riskCards: [
          { title: 'Valorisation en prime', severity: 'high', icon: 'fa-scale-balanced', points: ['Environ ' + fr(evRev, 0) + ' fois les revenus des douze derniers mois.', 'Plus du double du pair direct Applied Digital (' + fr(aplxEv, 0) + '×).'], verdict: 'Une déception de croissance ou une compression des multiples du secteur ferait mal, la prime étant intégralement dans le prix.' },
          { title: 'Dilution et financement', severity: 'high', icon: 'fa-money-bill-trend-up', points: ['Convertibles de 10 041,8 M$ de principal ; bons préfinancés de 2,0 Md$.', 'Programme d’émission d’actions de 25 M d’actions A actif ; titres autodétenus cédés pour 2 846,7 M$.'], verdict: 'Le modèle exige un capital constant ; chaque canal de financement ajoute des actions, présentes ou futures.' },
          { title: 'Exploitation déficitaire', severity: 'medium', icon: 'fa-flask', points: ['Perte opérationnelle de ' + fr(-G$.ebit / 1e6, 0) + ' M$ sur douze mois.', 'Investissements de 8 130,3 M$ au seul premier semestre 2026.'], verdict: 'Le passage à la rentabilité n’est pas acquis au rythme d’investissement actuel.' },
          { title: 'Volatilité et position vendeuse', severity: 'high', icon: 'fa-arrow-down-up-across-line', points: ['ATR de ' + usd(tech.atr14) + ' ; position vendeuse d’environ ' + fr(siPct, 0) + ' % du flottant.', 'Plafond d’achat à ' + usd(cap - entry) + ' au-dessus du déclencheur, ' + fr(bufAtr, 2) + ' ATR.'], verdict: 'Les écarts d’ouverture de plusieurs pour cent sont fréquents : le stop peut être franchi d’un coup.' }],
        pedagogy: 'Sur un titre dont l’amplitude journalière moyenne dépasse ' + usd(tech.atr14) + ', un écart d’ouverture de plusieurs dollars est la norme. Le slippage, l’écart entre prix voulu et prix obtenu, reste faible sur environ ' + fr(adv / 1e9, 1) + ' Md$ échangés par séance. La question centrale n’est pas la croissance, réelle, mais son prix : à ' + fr(evRev, 0) + ' fois les revenus, le marché escompte que la trajectoire se poursuive plusieurs années. Dimensionner sur la distance au stop, ' + usd(entry - stop) + ' par action, et ne pas confondre une entreprise de qualité avec un titre bon marché.' },
      tradeIdea: { status: 'watch', statusNote: 'Surveiller. Avant activation : aucune entrée ; une clôture sous ' + usd(abandon) + ' abandonne le scénario. Activation : clôture au-dessus de ' + usd(entry) + ', puis achat à l’ouverture suivante seulement sous ' + usd(cap) + ', ou par ordre limité à ce plafond pendant trois séances, annulé après une clôture sous ' + usd(entry) + ' et jamais laissé actif sur une ouverture sous ' + usd(stop) + '. Après activation : stop sous ' + usd(stop) + '. Le repli du 25 septembre laisse le titre sous le déclencheur : le plan n’est pas activé.',
        entry, stop, tp1, tp2,
        stopPct: pct(stop, entry).toFixed(1) + '%', tp1Pct: '+' + pct(tp1, entry).toFixed(1) + '%', tp2Pct: '+' + pct(tp2, entry).toFixed(1) + '%',
        rr: '1:' + rr1.toFixed(2) + ' TP1 / 1:' + rr2.toFixed(2) + ' TP2',
        entryNote: 'Déclencheur sur clôture au-dessus du plus haut du 8 septembre, pas sur un franchissement en séance. Entrée à l’ouverture suivante uniquement sous ' + usd(cap) + ' : au-delà, le R/R vers TP1 tomberait sous 1,5 avec le même stop. Ce plafond n’est qu’à ' + usd(cap - entry) + ' au-dessus du déclencheur, soit ' + fr(bufAtr, 2) + ' ATR. Mesure : sur les ' + gs.total + ' dernières séances, ' + gs.up + ' ouvertures ont dépassé la clôture de la veille de plus de ' + usd(cap - entry) + ', soit environ ' + fr(blocked, 0) + ' % ; l’écart d’ouverture médian, dans un sens ou dans l’autre, vaut ' + usd(gs.medAbs) + '. Sur la série, ' + bk.n + ' clôtures ont cassé un plus haut de vingt séances : ' + bk.inBand + ' ont fini à moins de ' + fr(bufPct, 2) + ' % au-dessus du niveau cassé, l’écart relatif du plafond, et ' + bk.buyable + ' ont ensuite ouvert sous ce seuil. Plan de repli : si l’ouverture dépasse le plafond, un ordre à cours limité à ' + usd(cap) + ', valable trois séances, garde le même R/R et le même stop ; il est annulé après toute clôture sous le déclencheur, ' + usd(entry) + ', n’est pas laissé actif à l’ouverture d’une séance sous le stop, ' + usd(stop) + ', ni si le stop est touché avant exécution. Rejoué avec ces bornes sur les ' + rt.miss + ' cassures non achetables à l’ouverture, l’ordre aurait été exécuté ' + rt.back + ' fois' + (rt.stopSame ? ', dont ' + rt.stopSame + ' avec le stop touché la même séance' : ', sans que le stop soit touché la même séance') + (rt.gapUnder ? ' ; ' + rt.gapUnder + ' fois retiré sur une ouverture sous le stop' : ' ; aucun retrait sur ouverture sous le stop') + '. Objectifs : TP1 à une hauteur de couloir au-dessus du déclencheur, TP2 à une fois et demie ; la zone du sommet de juin, ' + usd(hi) + ', se situe entre les deux. Liquidité : environ ' + fr(adv / 1e9, 1) + ' Md$ échangés par séance, médiane des vingt dernières. Exemple de taille, non personnalisé : avec un budget de perte de 100 $, le risque au plafond, ' + usd(cap - stop) + ' par action, donne ' + sizeExample + ' action' + (sizeExample > 1 ? 's' : '') + ' ; avec 1 000 $, ' + big + ' actions.',
        horizon: 'Dix séances après activation',
        thesis: 'La croissance de Nebius est réelle et rare, et le titre est soutenu par 8,0 Md$ de trésorerie et la présence de Nvidia au capital. Mais il se paie environ ' + fr(evRev, 0) + ' fois ses revenus et son exploitation perd de l’argent : le dossier est une entreprise de qualité à un prix élevé, pas une aubaine. Une clôture au-dessus de $' + entry.toFixed(2) + ' montrerait que les acheteurs reprennent la main après la consolidation de septembre. Avant activation, une clôture sous ' + usd(abandon) + ' abandonne le dossier. Après activation, le stop sous $' + stop.toFixed(2) + ' limite le coût d’une fausse sortie. TP1 à ' + usd(tp1) + ' et TP2 à ' + usd(tp2) + '. Ne pas anticiper le déclencheur, ne pas acheter un gap au-dessus du plafond.',
        catalysts: ['Une clôture au-dessus du plus haut du 8 septembre, sur un volume au moins égal à la médiane récente.', 'Toute avancée sur le passage à la rentabilité ou sur de nouveaux contrats de location de capacité.', 'Le rythme d’utilisation du programme d’émission d’actions et des bons préfinancés, à suivre dans les dépôts.'],
        invalidation: ['Avant activation : une clôture sous ' + usd(abandon) + ', bas du couloir, abandonne le scénario.', 'Après activation : une clôture sous ' + usd(stop) + ' invalide le trade.', 'Ouverture au-dessus de ' + usd(cap) + ' après la clôture de déclenchement : pas d’achat à l’ouverture ; seul l’ordre limité à ' + usd(cap) + ' reste valable trois séances.', 'Une émission d’actions ou une conversion d’obligations d’ampleur inattendue avant activation change l’équation de dilution et annule la thèse.'] },
      globalScore: { profile: 'Croissance exceptionnelle, valorisation et dilution élevées',
        keyTakeawaysPositive: ['Revenus multipliés par plus de six sur un an.', '8,0 Md$ de trésorerie et Nvidia au capital.', 'Titre au-dessus de toutes ses moyennes mobiles.'],
        keyTakeawaysNegative: ['Environ ' + fr(evRev, 0) + ' fois les revenus, prime au-dessus de tous les pairs.', 'Exploitation déficitaire, investissements financés par la dette.', 'Dilution active et position vendeuse élevée.'],
        mindsetTip: 'Une croissance record rassure sur la demande, pas sur le prix payé. La question utile n’est pas « Nebius grandit-il ? » mais « à combien de fois ses revenus est-il raisonnable de l’acheter ? ».' },
      social: { platforms: [], sourceRefs: [market('sentiment non retenu faute de mesure qualifiée')] },
      disclaimer: 'Document de recherche éducatif. Ni conseil financier, ni signal de trading. Statut surveiller : aucun ordre actif.',
    };
  },
  groups: [
    { name: 'Référence du complexe IA-infra', order: 1, transmission: 'Le titre coté que suit l’ensemble du complexe IA-infra, Nebius compris ; il en est aussi le fournisseur de puces et un actionnaire.', rows: [
      ['NVDA', 'leader', 'Processeurs graphiques d’IA', 'Bellwether du secteur : ses résultats et ses allocations de puces mènent le complexe ; il fournit Nebius et détient une participation et des bons préfinancés.']] },
    { name: 'Pair direct — loueur de calcul GPU', order: 1, transmission: 'Autre exploitant de centres de données loués à la demande de l’IA : même métier, même moteur de demande et de coûts.', rows: [
      ['APLD', 'direct_peer', 'Centres de données et calcul GPU loué', 'Concurrent le plus proche par le métier ; ses contrats de location et ses marges éclairent directement ceux de Nebius.']] },
    { name: 'Amont — processeurs alternatifs', order: 1, transmission: 'Nebius peut acheter du calcul à un fournisseur alternatif : son offre pèse sur les prix et les délais d’équipement.', rows: [
      ['AMD', 'upstream', 'Processeurs et accélérateurs', 'Fournisseur alternatif de calcul ; son offre et ses prix influent sur les coûts d’équipement des loueurs comme Nebius.']] },
    { name: 'Grands clouds — clients et concurrents', order: 2, transmission: 'Ils louent la même capacité de calcul : à la fois débouché possible et concurrents directs du modèle de Nebius.', rows: [
      ['MSFT', 'downstream', 'Cloud Azure et services d’IA', 'Loue de la capacité de calcul à grande échelle ; ses prix et ses investissements fixent la référence du marché.'],
      ['GOOGL', 'downstream', 'Cloud et infrastructure d’IA', 'Grand exploitant de calcul ; concurrent et référence de prix pour la location de GPU.'],
      ['AMZN', 'downstream', 'Cloud AWS d’infrastructure', 'Premier loueur d’infrastructure ; sa politique de prix encadre le marché de la location de calcul.'],
      ['ORCL', 'downstream', 'Cloud d’infrastructure pour l’IA', 'Investit lourdement dans la capacité de calcul louée ; concurrent en forte croissance sur le même créneau.']] },
    { name: 'Assembleurs de serveurs — même vague d’investissement', order: 2, transmission: 'Ils vendent les serveurs qui remplissent les centres de données : leur carnet suit la même demande d’IA.', rows: [
      ['DELL', 'second_order', 'Serveurs d’IA et infrastructure', 'Son carnet de serveurs d’IA mesure la demande d’équipement qui alimente les loueurs comme Nebius.'],
      ['SMCI', 'second_order', 'Assembleur de serveurs d’IA', 'Fournit les baies de serveurs d’IA ; ses marges montrent la pression des prix dans la chaîne.'],
      ['HPE', 'second_order', 'Serveurs et infrastructure d’entreprise', 'Autre assembleur exposé à la même vague d’investissement en centres de données.']] },
    { name: 'Second ordre — alimentation et réseau des centres de données', order: 2, transmission: 'Même vague de construction de centres de données qui accueilleront les serveurs.', rows: [
      ['VRT', 'second_order', 'Alimentation et refroidissement', 'Son carnet suit la construction de centres de données, celle-là même que mène Nebius.'],
      ['ANET', 'second_order', 'Réseau des centres de données', 'Ses commutateurs accompagnent chaque grappe de serveurs d’IA.']] },
    { name: 'Contrôles sectoriels', order: 2, transmission: 'Paniers de référence pour isoler ce qui est propre à Nebius.', rows: [
      ['SMH', 'sector_proxy', 'Panier de semi-conducteurs', 'Mesure le cycle des fournisseurs de puces ; un écart isole ce qui est propre au loueur.'],
      ['IGV', 'sector_proxy', 'Panier de logiciels', 'Contrôle du segment logiciel et cloud, où se situent les clients de Nebius.'],
      ['XLK', 'sector_proxy', 'Panier technologique du S&P 500', 'Contrôle large de la technologie : il neutralise le mouvement de marché commun pour isoler ce qui est propre à Nebius.'],
      ['QQQ', 'sector_proxy', 'Grandes valeurs du Nasdaq', 'Contrôle large : un mouvement commun avec ce panier n’a rien de spécifique au titre.']] },
  ],
  eventDefault: { leader: 'Aucune publication dans les quatorze jours collectés ; ses résultats et ses allocations de puces restent le signal à suivre', direct_peer: 'Aucune publication dans les quatorze jours collectés ; ses contrats de location restent le signal à suivre', upstream: 'Aucune publication dans les quatorze jours collectés ; prix et allocations à suivre', downstream: 'Aucune publication dans les quatorze jours collectés ; ses dépenses d’équipement fixent la demande', second_order: 'Aucune publication dans les quatorze jours collectés ; carnet à suivre', sector_proxy: 'Panier sans publication propre ; exposé aux résultats de ses grandes pondérations' },
  eventRisk: {},
  blastDoc: 1,
  scenarios: c => [
    { scenario: 'bullish', trigger: 'La demande de calcul reste sous-approvisionnée et Nebius signe de nouveaux contrats de location.', firstOrder: 'Le titre clôture au-dessus du sommet du 8 septembre et vise la zone du sommet de juin.', secondOrder: 'Applied Digital et Nvidia accompagnent ; SMH confirme.', confirmation: 'Une clôture au-dessus de ' + c.usd(c.entry) + ' avec SMH en hausse.', contradiction: 'Un dépassement du sommet pendant que SMH recule.' },
    { scenario: 'mixed', trigger: 'Pas de nouvelle propre ; le marché digère la valorisation.', firstOrder: 'Le titre oscille entre le bas du 14 septembre et le sommet du 8.', secondOrder: 'L’écart avec Applied Digital et SMH reste faible.', confirmation: 'Des clôtures entre ' + c.usd(c.abandon) + ' et ' + c.usd(c.entry) + ' pendant plusieurs séances.', contradiction: 'Une sortie franche d’un côté ou de l’autre.' },
    { scenario: 'bearish', trigger: 'Compression des multiples IA-infra, ralentissement de la demande de calcul ou nouvelle levée dilutive mal reçue.', firstOrder: 'Le titre repasse sous le bas du 14 septembre.', secondOrder: 'Les loueurs et assembleurs reculent plus que les fabricants de puces.', confirmation: 'Une clôture sous ' + c.usd(c.abandon) + ' avec Applied Digital en baisse.', contradiction: 'Un repli des fournisseurs que Nebius ne suit pas.' }],
  contradictions: c => ['Les revenus croissent par plus de six, mais l’exploitation perd ' + c.fr(-c.G$.ebit / 1e6, 0) + ' M$ sur douze mois : la croissance consomme du capital.', 'Le résultat net des douze derniers mois est positif alors que l’exploitation est déficitaire : il vient de produits financiers et de réévaluations, pas du métier.', 'Une corrélation élevée avec Nvidia ne prouve pas la symétrie des risques : Nebius achète les puces que Nvidia vend.'],
  missingData: c => ['Aucun companyfacts us-gaap n’existe pour cet émetteur étranger : les agrégats sont lus dans les états IFRS des dépôts primaires, en douze mois glissants au 30 juin 2026.', 'Coût d’emprunt indisponible à la collecte (fournisseur en échec) ; chaîne d’options non servie ; ni Reddit ni Google Trends pour ce titre.', 'Couverture officielle des transactions d’initiés partielle pour un émetteur étranger ; aucun solde net affirmé.', 'CoreWeave (CRWV) élagué du set : trois séances de barres manquantes dans la fenêtre servie ; seize comparables propres conservés, couvrant six groupes économiques.'],
  limitations: ['Émetteur étranger IFRS : agrégats reconstitués depuis les dépôts primaires, non depuis un flux XBRL standardisé.', 'Base de flux en douze mois glissants au 30 juin 2026 ; le résultat net glissant est gonflé par des éléments hors exploitation.', 'Coût d’emprunt, options et sentiment social non exploitables à la collecte.', 'CoreWeave élagué (barres serveur incomplètes) ; le métier de loueur reste couvert par Applied Digital.'],
});
