'use strict';
// Dossier AMKR v3 au close du 2026-09-23 (lot R05). Contenu éditorial et niveaux propres au titre ;
// calculs, provenance et preuves délégués au gabarit tools/lib/analysis-v3-r05.cjs : les données XBRL
// agrégées de la SEC (companyfacts) s'arrêtent au 31 mars 2026 à la collecte, les faits du 10-Q du
// 30 juin sont lus dans l'instance XBRL officielle de ce dépôt, hachée.
// Historique conservé : la transition archivée watch → stopped du 16 septembre est recopiée telle quelle.
const R = require('../../../../tools/lib/analysis-v3-r05.cjs');
const GEN = 'analyses/AMKR/_runs/20260924/build-amkr.cjs';
const SHARES = 248452472;

R.build({
  ticker: 'AMKR', shortName: 'Amkor', cik: 1047127, generator: GEN, mode: 'breakout', clientBars: true,
  xbrlInstance: { local: 'q2-10q__amkr-20260630_htm.xml', accn: '0001047127-26-000046', form: '10-Q', filed: '2026-07-28', url: 'https://www.sec.gov/Archives/edgar/data/1047127/000104712726000046/amkr-20260630_htm.xml' },
  xbrl: { ttm: { rev: ['RevenueFromContractWithCustomerExcludingAssessedTax'], ebit: ['OperatingIncomeLoss'], ni: ['NetIncomeLoss'], da: ['DepreciationDepletionAndAmortization'], ocf: ['NetCashProvidedByUsedInOperatingActivities'], capex: ['PaymentsToAcquirePropertyPlantAndEquipment'] },
    instant: { ltd: ['LongTermDebtNoncurrent'], std: ['DebtCurrent'], cashEq: ['CashAndCashEquivalentsAtCarryingValue'], sti: ['ShortTermInvestments'] }, da: ['da'], debt: ['ltd', 'std'], cash: ['cashEq', 'sti'] },
  scenarioBasis: 'ebitda', scenarioMultiple: 7,
  valuationBasis: 'GAAP douze mois au 2026-06-30 (XBRL SEC, instance du 10-Q pour le dernier trimestre) ; EBITDA = résultat opérationnel + amortissements ; dette = emprunts à court et long terme au 30 juin, dont 1,15 Md$ d’obligations convertibles 2031 comptées comme dette ; trésorerie = liquidités et placements à court terme du 30 juin ; 248,5 millions d’actions au 21 juillet, sans action issue des convertibles, dont le prix de conversion de 106,37 $ est hors de portée ; multiple de sept fois l’EBITDA = hypothèse éditoriale',
  shares: { value: SHARES, doc: 0 },
  levels: { trigger: { d: '2026-09-23', c: 2 }, stop: { d: '2026-09-22', c: 3 }, abandon: { d: '2026-09-21', c: 3 }, s1: { d: '2026-09-23', c: 3 }, r1: { d: '2026-08-07', c: 2 }, r2: { d: '2026-08-17', c: 2 }, r3: { d: '2026-07-27', c: 2 } },
  supports: ['s1', 'stop', 'abandon'], resistances: ['trigger', 'r1', 'r2'],
  targets: ({ lv }) => ({ tp1: lv('r2'), tp2: lv('r3') }),
  levelsMethod: 'Déclencheur = plus haut du 23 septembre ; stop = plus bas du 22 septembre ; seuil d’abandon = plus bas du 21 septembre ; TP1 = plus haut du 17 août ; TP2 = plus haut du 27 juillet, dernière séance avant la publication ; plafond = (TP1 + 1,5 × stop) / 2,5 arrondi au cent inférieur ; pourcentages depuis l’entrée ; R/R = gain / risque.',
  inventory: 27,
  reviewScope: 'Dépôts EDGAR d’Amkor du 1er août 2025 au 23 septembre 2026 (27 formulaires hors formulaires 3, 4, 5 et 144), dont le 10-K de l’exercice 2025. Les 8-K de gouvernance (items 5.02, 5.07), la procuration et son complément, le rapport annuel aux actionnaires, le formulaire SD et les Schedule 13D/A de l’actionnaire de référence sont écartés comme non décisionnels ; les 424B7 de février portent sur des cessions d’actions existantes ; les 8-K de résultats antérieurs et le 10-Q du premier trimestre sont couverts par ceux du deuxième ; les 8-K de septembre 2025 portent sur une dette remplacée.',
  docs: [
    ['2026-07-28', '10-Q', '0001047127-26-000046', 'amkr-20260630.htm', 'q2-10q__amkr-20260630.htm',
      'Rapport trimestriel au 30 juin 2026 : 248 452 472 actions au 21 juillet ; aucune action potentielle issue des obligations convertibles 2031 dans le calcul dilué, le cours moyen n’ayant pas dépassé le prix de conversion ; rachat d’options d’achat plafonnées pour 44,1 M$.'],
    ['2026-07-27', '8-K / Exhibit 99.1', '0001047127-26-000043', 'amkr6302026erex-991.htm', 'q2-8k__amkr6302026erex-991.htm',
      'Communiqué du deuxième trimestre, daté du 27 juillet : ventes de 1,90 Md$ (+26 %), marge brute de 16,8 %, résultat opérationnel de 200 M$, bénéfice de 0,70 $ par action ; produits avancés à 1,557 Md$. Prévision : 1,95 à 2,05 Md$ de ventes et 18,5 à 19,5 % de marge brute au troisième trimestre ; investissements de 2,5 à 3,0 Md$ sur l’année.'],
    ['2026-02-20', '10-K', '0001047127-26-000014', 'amkr-20251231.htm', 'fy25-10k__amkr-20251231.htm',
      'Rapport annuel de l’exercice 2025 : ventes directes à Apple et à Qualcomm à 29,8 % et 11,1 % des ventes ; dix premiers clients à 72 % ; communications à 46 % des ventes, informatique et centres de données à 20 %.'],
    ['2026-05-05', '8-K', '0001047127-26-000029', 'amkr-20260430.htm', 'may05-8k__amkr-20260430.htm',
      'Émission du 5 mai 2026 : 1,15 Md$ d’obligations convertibles à 0,00 % échéance 2031, option des banques de 150 M$ exercée en totalité ; titres de dette garantis par les filiales, remboursables en numéraire et, le cas échéant, en actions.'],
    ['2026-04-30', '8-K / Exhibit 99.1', '0001047127-26-000026', 'amkrapril2026ex991converti.htm', 'apr30-8k__amkrapril2026ex991converti.htm',
      'Communiqué de fixation du prix du 30 avril : conversion initiale de 9,4013 actions pour 1 000 $, soit environ 106,37 $ par action, prime de 52,5 % sur le cours de 69,75 $ du jour ; conversions réglées en numéraire et, au-delà, en actions.'],
  ],
  needles: {
    q2q: [0, ['The number of outstanding shares of the registrant’s Common Stock as of July 21, 2026 was 248,452,472', 'There were no potentially dilutive common shares issuable pursuant to the $ 1.15 billion aggregate principal amount of our 0.00 % convertible senior notes due 2031', 'Capped call transactions related to the issuance of convertible senior notes due 2031 — — ( 44,071 )']],
    q2: [1, ['Net sales $1.90 billion, up 26% year-on-year', 'Gross margin 16.8% 14.2% 12.0%', 'Operating income $200 $100 $92', 'Earnings per diluted share $0.70 $0.33 $0.22', 'Advanced products (1) $ 1,557 $ 1,372 $ 1,228', 'Net sales of $1.95 billion to $2.05 billion', 'Gross margin of 18.5% to 19.5%', 'Full year 2026 capital expenditures of approximately $2.5 billion to $3.0 billion', 'total cash and short-term investments was $2.5 billion, and total debt was $2.5 billion']],
    annual: [2, ['Direct sales to Apple and Qualcomm accounted for 29.8% and 11.1% of our net sales, respectively, for the year ended December 31, 2025', 'Our ten largest customers accounted for 72% of our net sales in 2025']],
    notes: [3, ['issued $1,150,000,000 aggregate principal amount of its 0.00% Convertible Senior Notes due 2031', 'include $150,000,000 aggregate principal amount of Notes issued pursuant to the full exercise by the initial purchasers of such option']],
    conv: [4, ['The initial conversion rate is 9.4013 shares of common stock per $1,000 principal amount of notes, which represents an initial conversion price of approximately $106.37 per share', 'Amkor will settle conversions in cash and, if applicable, shares of its common stock']],
  },
  sectionDocs: { verdict: [1, 0], business: [1, 2, 0], news: [1, 0], earnings: [1], capitalStructure: [0, 3, 4], filingsReview: [0, 1, 2, 3, 4], risks: [1, 2, 3], globalScore: [1], meta: [1], disclaimer: [1], macro: [2], options: [1], social: [1], header: [0] },
  score: { business: 22, technical: 5, capital: -1, calendar: -2, dilution: -1, risk: 22 },
  peers: true,
  peerFicheSha: {},
  route: (p, { prov, dep, B }) => /^news\.[01]\./.test(p) ? prov('bars', B, 'Ouverture et clôture lues sur les barres certifiées ; écart d’ouverture = ouverture / clôture de la veille − 1 ; comparaison avec SMH et les clients documentés sur la même séance.', [dep('comparison', ''), dep('client', '')]) : null,
  riskScoreReason: 'Jugement qualitatif sur dix : chute de 24,7 % au lendemain de la publication de juillet, deux clients à 41 % des ventes 2025, investissements de 2,5 à 3,0 Md$ et plafond d’achat proche du déclencheur.',
  compose: c => {
    const { fr, usd, pct, sgn, close, prev, bars, N, tech, st, M, adv, ret, G$, marketCap, ev, scn, lv, entry, stop, tp1, tp2, abandon, cap, rr1, rr2, riskAtr, sizeExample, ref, market, docs, raw, peerStat, archive } = c;
    const gs = c.gapStats(cap - entry), bufAtr = (cap - entry) / tech.atr14, blocked = gs.up / gs.total * 100;
    const bufPct = (cap / entry - 1) * 100, bk = c.breakoutStats(bufPct), rt = c.retestStats(bufPct, (1 - stop / entry) * 100), bufOpen = bk.buyable / bk.n;
    const cmp = raw.comparison_bars.data.items[0].results[0].data.concat(c.K.read('analyses/AMKR/_data/comparison_client_bars.json').data.items[0].results[0].data);
    const dr = (sym, d) => { const b = cmp.find(x => x.symbol === sym).bars, i = b.findIndex(x => x[0] === d); return pct(b[i][4], b[i - 1][4]); };
    const bar = d => bars.find(b => b[0] === d), prevOf = d => bars[bars.findIndex(b => b[0] === d) - 1];
    const d0728 = bar('2026-07-28'), p0728 = prevOf('2026-07-28'), d0914 = bar('2026-09-14'), p0914 = prevOf('2026-09-14');
    const d0828 = bar('2026-08-28'), d0909 = bar('2026-09-09'), d0911 = bar('2026-09-11'), d0915 = bar('2026-09-15'), d0824 = bar('2026-08-24');
    const hi0616 = bar('2026-06-16'), fromHi = pct(close, hi0616[2]);
    const evRev = ev / G$.rev, evEbitda = ev / G$.ebitda, pe = marketCap / G$.ni;
    const terEb = peerStat('TER'), klacEb = peerStat('KLAC'), entgEb = peerStat('ENTG');
    const ext20 = pct(close, tech.ema20), fcfTxt = fr(G$.fcf / 1e6, 0);
    return {
      meta: { lang: 'fr', dir: 'ltr', level: 'intermediate', tags: ['us', 'equities', 'ai-chain', 'semis', 'technology'], grade: 'C+', date: '2026-09-24', dateDisplay: '24 septembre 2026', version: 3, status: 'watch', assetType: 'stock', levelsCloseDate: c.REF,
        description: 'Amkor : ventes record à +26 %, marge brute en hausse, mais un titre qui a perdu un quart de sa valeur le lendemain de la publication et deux clients à 41 % des ventes. Dossier au close du 23 septembre 2026, statut surveiller.',
        ogDescription: 'AMKR : ventes de 1,90 Md$ (+26 %), prévision en hausse ; titre à 53,32 $, 45 % sous son sommet de juin ; activation au-dessus de 54,89 $ seulement.',
        lastMcpRefresh: raw.status.captured_at, levelsVerifiedAt: raw.status.captured_at,
        statusHistory: [...archive.meta.statusHistory, { at: raw.status.captured_at, from: 'stopped', to: 'watch', note: 'refonte v3 du 24 septembre : nouveau scénario, clôture de référence du 2026-09-23', close }],
        lastEvent: archive.meta.lastEvent },
      header: { ticker: 'AMKR', name: 'Amkor Technology, Inc.', exchange: 'NASDAQ', sector: 'Assemblage, conditionnement et test de puces pour le compte de tiers', price: close, changePct: pct(close, prev),
        badges: [{ text: 'SURVEILLER — ACTIVATION AU-DESSUS DU PLUS HAUT DU 23 SEPTEMBRE', color: 'blue' }, { text: 'Chaîne IA — conditionnement avancé des puces', color: 'purple' }],
        metrics: { marketCap: fr(marketCap / 1e9, 1) + ' Md$', volume: fr(bars[N][5] / 1e6, 2) + ' M', evEbitda: fr(evEbitda, 1) + '×' }, halalStatus: 'unknown' },
      verdict: { score: 45, conviction: 'Low', bias: 'Neutral',
        confidence: 'Score éditorial non prédictif. Les chiffres d’entreprise viennent des dépôts SEC et des données XBRL officielles ; les niveaux, du close certifié du 23 septembre.',
        summary: 'Amkor a publié le 27 juillet un trimestre record : 1,90 Md$ de ventes (+26 %), une marge brute passée de 12,0 à 16,8 %, et une prévision encore plus haute pour le troisième trimestre. Le lendemain, le titre a ouvert ' + fr(Math.abs(pct(d0728[1], p0728[4])), 1) + ' % plus bas et fini à ' + sgn(pct(d0728[4], p0728[4]), 1) + ', alors que SMH faisait ' + sgn(dr('SMH', '2026-07-28'), 1) + ' : le marché a vendu la société, pas le secteur. La même publication annonçait 2,5 à 3,0 Md$ d’investissements sur l’année, l’équivalent d’environ un trimestre et demi de ventes. Le titre clôture le 23 septembre à ' + usd(close) + ', ' + fr(Math.abs(fromHi), 0) + ' % sous son sommet de juin, et vaut ' + fr(evEbitda, 1) + ' fois l’EBITDA GAAP des douze derniers mois. Apple et Qualcomm ont fait 41 % des ventes de l’exercice 2025. Signal utile : une clôture au-dessus de ' + usd(entry) + ', avec un plafond d’achat à ' + usd(cap - entry) + ' seulement au-dessus.',
        whyBuy: [
          'Ventes record de 1,90 Md$ au deuxième trimestre (+26 %) et marge brute de 16,8 %, contre 12,0 % un an plus tôt.',
          'Prévision du troisième trimestre à 1,95 à 2,05 Md$ de ventes et 18,5 à 19,5 % de marge brute.',
          'Produits avancés à 1,557 Md$, 82 % des ventes, porte d’entrée du conditionnement des puces d’IA.',
          'Liquidités de 2,5 Md$ pour une dette de 2,5 Md$ : la trésorerie couvre l’endettement.'],
        whyAvoid: [
          'Chute de ' + fr(Math.abs(pct(d0728[4], p0728[4])), 1) + ' % le lendemain de la publication, sans baisse comparable du secteur.',
          'Investissements prévus de 2,5 à 3,0 Md$ sur l’année : le flux libre des douze derniers mois est déjà négatif, à ' + fcfTxt + ' M$.',
          'Apple à 29,8 % et Qualcomm à 11,1 % des ventes 2025 : deux décisions d’achat ont pesé 41 % du chiffre d’affaires de l’exercice 2025.',
          'Positions vendeuses à ' + fr(st.shortPercentOfFloat * 100, 1) + ' % du flottant.'],
        controlChecklist: [
          { label: 'Historique de cours', status: 'pass', statusLabel: 'Trois cents séances continues', evidence: 'Série quotidienne certifiée au close du 23 septembre, source de repli documentée.', action: 'Niveaux et indicateurs recalculés sur cette seule série.' },
          { label: 'Calendrier', status: 'warn', statusLabel: 'Micron le 30 septembre', evidence: 'Micron publie le 30 septembre après la clôture selon deux calendriers concordants, non confirmé ici par l’émetteur ; Amkor conditionne des mémoires. La date du 26 octobre pour Amkor ne vient que d’un calendrier.', action: 'Réduire une position ouverte avant la publication de Micron.' },
          { label: 'Données comptables', status: 'warn', statusLabel: 'Dernier trimestre lu dans le 10-Q', evidence: 'La base comptable agrégée de la SEC s’arrête au 31 mars ; le trimestre au 30 juin vient directement des données structurées du 10-Q.', action: 'Chiffres de douze mois arrêtés au 30 juin.' }] },
      business: { theme: 'Assemblage, conditionnement avancé et test de puces pour les fabricants de semi-conducteurs',
        overview: '<p>Amkor assemble, met en boîtier et teste des puces pour le compte des fabricants de semi-conducteurs : c’est l’étape après la fonderie, avant la carte électronique. Au deuxième trimestre 2026, ses ventes ont atteint 1,898 Md$ (+26 %), dont 1,557 Md$ de produits avancés et 341 M$ de produits courants. Les communications, surtout les smartphones, pèsent 42 % des ventes du trimestre, l’informatique et les centres de données 22 %.</p><p>La marge brute est montée à 16,8 %, contre 12,0 % un an plus tôt, et le résultat opérationnel à 200 M$. La prévision du troisième trimestre vise 1,95 à 2,05 Md$ de ventes et 18,5 à 19,5 % de marge brute. En face, le groupe prévoit 2,5 à 3,0 Md$ d’investissements sur l’année, dont une nouvelle usine en Arizona.</p><p>Deux clients dominent : Apple, 29,8 % des ventes 2025 en direct, et Qualcomm, 11,1 %. En mai, Amkor a émis 1,15 Md$ d’obligations convertibles à 0 %, convertibles vers 106,37 $, soit le double du cours actuel.</p>',
        moat: 'L’avantage tient à l’échelle et à la présence industrielle hors de Taïwan et de Chine, en Corée, au Vietnam et bientôt en Arizona. Il reste limité : le conditionnement se vend au prix du marché, les grands clients mettent les sous-traitants en concurrence, et la fonderie TSMC fait aussi du conditionnement avancé.',
        segments: [
          { name: 'Produits avancés', revenue: '1,557 Md$ au deuxième trimestre', pct: '82 % des ventes', description: 'Conditionnement en puce retournée, au niveau de la plaquette et en système, dont les puces d’IA.' },
          { name: 'Produits courants', revenue: '341 M$ au deuxième trimestre', pct: '18 % des ventes', description: 'Boîtiers à fils et conditionnements classiques.' }],
        sourceRefs: [ref(1), ref(2), ref(0)],
        coverageMatrix: [
          { facet: 'Cours et historique', status: 'COUVERT', decision: 'Trois cents séances continues, close certifié ; base des niveaux et des indicateurs.' },
          { facet: 'Résultats et guidance', status: 'COUVERT — PRIMAIRE', decision: 'Communiqué du 27 juillet et 10-Q ; date du troisième trimestre non confirmée par l’émetteur.' },
          { facet: 'Capital et dette', status: 'COUVERT — PRIMAIRE', decision: 'Obligations convertibles de mai comptées en dette ; aucune action potentielle au prix actuel.' },
          { facet: 'Agrégats GAAP', status: 'COUVERT — XBRL', decision: 'Douze mois glissants au 30 juin 2026 ; dernier trimestre lu dans les données structurées du 10-Q.' },
          { facet: 'Comparables et transmission', status: 'COUVERT — LOCAL', decision: 'Corrélations recalculées sur barres certifiées, Apple et Qualcomm inclus comme clients documentés.' },
          { facet: 'Initiés', status: 'PARTIEL', decision: 'Vente de 1 000 actions par la directrice financière le 8 septembre ; couverture officielle incomplète.' },
          { facet: 'Options', status: 'NON EXPLOITABLE', decision: 'Chaîne relevée en séance le 24 septembre, non rattachée à la clôture de référence.' }] },
      news: [
        { date: '2026-07-28', title: 'Gap de ' + sgn(pct(d0728[1], p0728[4]), 1) + ', clôture à ' + sgn(pct(d0728[4], p0728[4]), 1), impact: 'negative', detail: 'Le communiqué est daté du 27 juillet ; la première séance qui le reflète est celle du 28. Le titre ouvre à ' + usd(d0728[1]) + ' contre ' + usd(p0728[4]) + ' la veille, descend à ' + usd(d0728[3]) + ' et clôture à ' + usd(d0728[4]) + '. SMH fait ' + sgn(dr('SMH', '2026-07-28'), 2) + ', Apple ' + sgn(dr('AAPL', '2026-07-28'), 2) + ' et Qualcomm ' + sgn(dr('QCOM', '2026-07-28'), 2) + ' le même jour : la baisse est propre à Amkor. Le communiqué ne l’explique pas ; il annonce le même jour 2,5 à 3,0 Md$ d’investissements sur l’année.', source: 'Barres certifiées', sourceUrl: c.evidenceUrl },
        { date: '2026-09-14', title: 'Gap de ' + fr(pct(d0914[1], p0914[4]), 1) + ' % à l’ouverture', impact: 'negative', detail: 'Ouverture à ' + usd(d0914[1]) + ' (' + sgn(pct(d0914[1], p0914[4]), 2) + '), clôture à ' + usd(d0914[4]) + ' (' + sgn(pct(d0914[4], p0914[4]), 2) + '). SMH fait ' + sgn(dr('SMH', '2026-09-14'), 2) + ' et Intel ' + sgn(dr('INTC', '2026-09-14'), 2) + ' la même séance : le repli vient des puces en général, amplifié chez Amkor ; aucun dépôt ouvert ici n’en donne la cause.', source: 'Barres certifiées', sourceUrl: c.evidenceUrl },
        { date: '2026-05-05', title: 'Obligations convertibles de 1,15 Md$', impact: 'neutral', detail: 'Obligations à 0,00 % échéance 2031, convertibles vers 106,37 $ par action, prime de 52,5 % sur le cours de 69,75 $ du 30 avril ; options d’achat plafonnées achetées pour 44,1 M$.', source: 'Amkor — SEC', sourceUrl: docs[3].url }],
      fundamentals: { rows: [
          { metric: 'Ventes du deuxième trimestre', value: '1,90 Md$', signal: '+26 % sur un an, record trimestriel', signalColor: 'green', _src: 1 },
          { metric: 'Marge brute du deuxième trimestre', value: '16,8 %', signal: 'Contre 12,0 % un an plus tôt et 14,2 % au premier trimestre', signalColor: 'green', _src: 1 },
          { metric: 'Prévision du troisième trimestre', value: '1,95 à 2,05 Md$', signal: 'Marge brute de 18,5 à 19,5 %, bénéfice de 0,72 à 0,82 $ par action', signalColor: 'blue', _src: 1 },
          { metric: 'Investissements prévus en 2026', value: '2,5 à 3,0 Md$', signal: 'Prévision annuelle du communiqué du 27 juillet, usine d’Arizona comprise', signalColor: 'amber', _src: 1 },
          { metric: 'Revenus GAAP sur douze mois', value: fr(G$.rev / 1e9, 2) + ' Md$', signal: 'Douze mois glissants au 30 juin 2026 (XBRL SEC)', signalColor: 'blue', _src: 'gaap' },
          { metric: 'Résultat opérationnel GAAP sur douze mois', value: fr(G$.ebit / 1e6, 0) + ' M$', signal: 'Marge de ' + fr(G$.ebit / G$.rev * 100, 1) + ' %, douze mois glissants au 30 juin 2026', signalColor: 'amber', _src: 'gaap' },
          { metric: 'Résultat net GAAP sur douze mois', value: fr(G$.ni / 1e6, 0) + ' M$', signal: 'Douze mois glissants au 30 juin 2026', signalColor: 'blue', _src: 'gaap' },
          { metric: 'Flux de trésorerie opérationnel sur douze mois', value: fr(G$.ocf / 1e9, 2) + ' Md$', signal: 'Douze mois glissants au 30 juin 2026', signalColor: 'green', _src: 'gaap' },
          { metric: 'Flux de trésorerie libre sur douze mois', value: fcfTxt + ' M$', signal: 'Après ' + fr(G$.capex / 1e9, 2) + ' Md$ d’investissements ; la prévision annuelle en annonce 2,5 à 3,0 Md$', signalColor: 'red', _src: 'gaap' },
          { metric: 'Dette au 30 juin 2026', value: fr(G$.debt / 1e9, 2) + ' Md$', signal: 'Dont 1,15 Md$ d’obligations convertibles 2031 à 0 %', signalColor: 'amber', _src: 'gaap', _also: [3] },
          { metric: 'Liquidités au 30 juin 2026', value: fr(G$.cash / 1e9, 2) + ' Md$', signal: 'Trésorerie et placements à court terme', signalColor: 'green', _src: 'gaap' },
          { metric: 'EV/EBITDA GAAP', value: fr(evEbitda, 1) + '×', signal: 'Valeur d’entreprise au close du 2026-09-23, convertibles en dette, sur EBITDA GAAP douze mois au 2026-06-30', signalColor: 'green', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus Teradyne à ' + fr(terEb, 1) + '×, KLA à ' + fr(klacEb, 1) + '× et Entegris à ' + fr(entgEb, 1) + '× (statistiques courantes du 24 septembre, non point-in-time) : les fournisseurs d’équipements et de matériaux se paient trois à quatre fois plus cher que le sous-traitant. ASE, pair direct, n’est pas cité : sa statistique courante mélange dollars et monnaie locale.', _src: 'market', _peers: ['TER', 'KLAC', 'ENTG'] },
          { metric: 'EV/revenus GAAP', value: fr(evRev, 2) + '×', signal: 'Valeur d’entreprise au close du 2026-09-23 sur revenus GAAP douze mois au 2026-06-30', signalColor: 'green', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus une marge opérationnelle GAAP de ' + fr(G$.ebit / G$.rev * 100, 1) + ' % : le prix reflète un métier de sous-traitance aux marges minces.', _src: 'market' },
          { metric: 'P/E GAAP sur douze mois', value: fr(pe, 1) + '×', signal: 'Capitalisation au 2026-09-23 sur résultat net GAAP douze mois au 2026-06-30, sans élément exceptionnel significatif relevé', signalColor: 'blue', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus la prévision du troisième trimestre à 0,72 à 0,82 $ par action : annualisée, elle ramènerait le multiple vers dix-sept fois.', _src: 'market' },
          { metric: 'EV/EBITDA — scénario de compression (hypothèse éditoriale)', value: fr(scn.price, 2) + ' $ par action', signal: 'Scénario : multiple ramené à sept fois l’EBITDA GAAP douze mois au 2026-06-30 par hypothèse, bilan du 30 juin, soit ' + fr(scn.downside_pct, 0) + ' % sous le close du 2026-09-23', signalColor: 'red', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus ' + fr(evEbitda, 1) + '× aujourd’hui : sept fois correspond à un sous-traitant dont les marges retomberaient ; ce que coûterait une commande d’Apple manquée, pas un objectif.', _src: 'market' }],
        sourceRefs: [ref(0), ref(1), market('fondamentaux et statistiques')] },
      earnings: { quarters: [],
        beatNote: 'Deuxième trimestre 2026 : ventes record de 1,898 Md$, marge brute de 16,8 %, résultat opérationnel de 200 M$ et bénéfice de 0,70 $ par action, contre 0,22 $ un an plus tôt. La guidance du troisième trimestre vise 1,95 à 2,05 Md$ de ventes, 18,5 à 19,5 % de marge brute et 0,72 à 0,82 $ par action ; les investissements de l’année sont prévus entre 2,5 et 3,0 Md$. Prochaine publication : 26 octobre selon un seul calendrier collecté, non confirmée par l’émetteur.',
        nextEarnings: '26 octobre 2026 selon un calendrier collecté, date non confirmée par l’émetteur.',
        sourceRefs: [ref(1)] },
      capitalStructure: { sharesOutstanding: '248 452 472 actions ordinaires au 21 juillet 2026 (page de garde du 10-Q)',
        sharesAuthorized: 'Actions autorisées non reprises : non décisionnel pour ce dossier.', dilutionRisk: 'low',
        shareHistory: 'Base retenue : actions ordinaires en circulation au 21 juillet. Passage au nombre dilué : le 10-Q ne retient aucune action potentielle issue des obligations convertibles 2031, le cours moyen étant resté sous le prix de conversion ; les 1,15 Md$ convertibles donneraient au plus environ 10,8 millions d’actions à 106,37 $, 4,4 % de plus, et le nominal se rembourse en numéraire. Des options d’achat plafonnées, achetées 44,1 M$, réduisent encore cette dilution. Les 1,15 Md$ sont comptés en dette dans la valeur d’entreprise. Les attributions salariales ne sont pas ajoutées au dénominateur.',
        warrants: [], atm: { active: false, authorized: 'Aucun programme d’émission d’actions sur le marché relevé', used: 'Sans objet', remaining: 'Sans objet' },
        sourceRefs: [ref(0), ref(3), ref(4)] },
      filingsReview: { summary: 'Cinq dépôts décisionnels ouverts et hachés. Ils montrent un sous-traitant dont les marges remontent vite, qui investit massivement, s’est financé en convertibles à prix de conversion lointain, et dépendait de deux clients pour 41 % de ses ventes en 2025.',
        filings: docs.map(d => ({ date: d.date, form: d.form, accession: d.accession, finding: d.finding, url: d.url })),
        contrarianRisks: [
          'Des investissements de 2,5 à 3,0 Md$ pour un flux libre de ' + fcfTxt + ' M$ sur douze mois : la trésorerie va baisser avant que les usines rapportent.',
          'Apple, premier client, décide seul du volume des smartphones conditionnés ; 42 % des ventes du trimestre viennent encore des communications.',
          'La chute du 28 juillet, malgré une prévision en hausse, montre que le marché doute du retour sur ces investissements.',
          'Le conditionnement avancé des puces d’IA est dominé par TSMC ; Amkor en capte une part encore minoritaire.'] },
      technicals: { rsi14: +tech.rsi14.toFixed(2), macd: +tech.macd.toFixed(2), macdSignal: +tech.macdSignal.toFixed(2), ema20: +tech.ema20.toFixed(2), ema50: +tech.ema50.toFixed(2), ema200: +tech.ema200.toFixed(2),
        ma50Type: 'EMA', ma200Type: 'EMA', ma50Available: true, ma200Available: true, atr14: +tech.atr14.toFixed(2),
        badges: ['Au-dessus des moyennes à vingt et deux cents séances, sous celle à cinquante', fr(Math.abs(fromHi), 0) + ' % sous le sommet du 16 juin', 'Rebond depuis le plus bas du 16 septembre'],
        supports: [lv('s1'), stop, abandon], resistances: [entry, lv('r1'), tp1],
        setupNote: 'Le titre clôture à ' + usd(close) + ', ' + fr(ext20, 1) + ' % au-dessus de sa moyenne à vingt séances, juste sous celle à cinquante, vers ' + usd(tech.ema50) + '. Avant activation, aucune entrée ; une clôture sous ' + usd(abandon) + ', le bas du 21 septembre, abandonne le scénario. Activation sur une clôture au-dessus de $' + entry.toFixed(2) + ', le plus haut du 23 septembre. Après activation, stop sous $' + stop.toFixed(2) + ', le plus bas du 22 septembre, soit ' + fr(riskAtr, 2) + ' ATR sous le déclencheur. Supports : ' + usd(lv('s1')) + ', ' + usd(stop) + ' et ' + usd(abandon) + '. Résistances : ' + usd(entry) + ', ' + usd(lv('r1')) + ' et ' + usd(tp1) + ', plus haut du 17 août.',
        wyckoff: 'Non utilisé : le profil de volume n’est pas exploité dans ce dossier.',
        sourceRefs: [market('barres quotidiennes et indicateurs recalculés')] },
      options: { callOI: 'Non exploitable', putOI: 'Non exploitable', cpRatio: 'Non exploitable', maxPain: 'Non exploitable', ivMean: 'Non exploitable', skew: 'Chaîne relevée en séance le 24 septembre, non rattachée à la clôture de référence', unusual: 'Aucune activité inhabituelle qualifiée', sourceRefs: [market('options')] },
      shortInterest: { siPct: fr(st.shortPercentOfFloat * 100, 2) + ' % du flottant', daysToCover: fr(st.shortRatio, 2) + ' jours, date de règlement non précisée par la source', ctb: 'Coût d’emprunt non disponible à la collecte', trend: 'Positions vendeuses élevées pour une valeur de cette taille ; un rachat des vendeurs peut amplifier une cassure, sans en faire une thèse.', squeezeScore: 'Non retenu comme thèse', sourceRefs: [market('positions vendeuses')] },
      insiders: { signal: 'La directrice financière Megan Faust a vendu 1 000 actions à 49,05 $ le 8 septembre, selon son formulaire 4. Aucun achat relevé. Couverture officielle partielle : aucun solde net publié.',
        recentTransactions: [],
        sourceRefs: [market('formulaires 4')] },
      macro: { indicators: [{ name: 'Clôture de référence', value: c.REF, signal: usd(close) + ', séance complète' }, { name: 'Rendement cinq séances', value: sgn(ret(5)), signal: 'Descriptif' }, { name: 'Rendement vingt et une séances', value: sgn(ret(21)), signal: 'Descriptif' }],
        regime: 'neutral', impact: 'Amkor vit du volume de puces à conditionner : cycle des smartphones, dont Apple, et montée des puces d’IA. Ses usines sont en Corée, au Vietnam, en Chine et au Japon : droits de douane et tensions commerciales touchent directement ses coûts.' },
      risks: { riskScore: 7, riskProfile: 'High',
        riskSummary: 'Le premier risque est la réaction du marché à ses propres publications : −24,7 % au lendemain d’un trimestre record. Le deuxième, la concentration : Apple et Qualcomm ont pesé 41 % des ventes de l’exercice 2025. Le troisième, des investissements qui dépassent le flux de trésorerie et une publication de Micron le 30 septembre, dans l’horizon du plan.',
        riskCards: [
          { title: 'Réaction aux publications', severity: 'high', icon: 'fa-arrows-up-down', points: ['Gap de ' + sgn(pct(d0728[1], p0728[4]), 1) + ' le 28 juillet.', 'Gap de ' + sgn(pct(d0914[1], p0914[4]), 1) + ' le 14 septembre.'], verdict: 'Un stop peut être franchi d’un coup à l’ouverture : dimensionner comme si la perte pouvait dépasser le stop.' },
          { title: 'Concentration des clients', severity: 'high', icon: 'fa-building', points: ['Apple à 29,8 % des ventes 2025.', 'Qualcomm à 11,1 %, dix premiers clients à 72 %.'], verdict: 'Une baisse de commandes d’Apple se lit en quelques semaines sur les ventes d’Amkor.' },
          { title: 'Investissements lourds', severity: 'medium', icon: 'fa-industry', points: ['2,5 à 3,0 Md$ prévus en 2026.', 'Flux libre de ' + fcfTxt + ' M$ sur douze mois.'], verdict: 'Si la demande de conditionnement avancé déçoit, ces usines pèseront sur les marges pendant des années.' },
          { title: 'Exécution de l’entrée', severity: 'medium', icon: 'fa-door-closed', points: ['Plafond à ' + usd(cap - entry) + ' au-dessus du déclencheur, ' + fr(bufAtr, 2) + ' ATR.', 'Environ ' + fr(blocked, 0) + ' % des ouvertures récentes auraient dépassé cet écart.'], verdict: 'Beaucoup de déclenchements ne seront pas achetables au prix prévu : laisser passer plutôt que payer plus haut.' }],
        pedagogy: 'Le 28 juillet montre qu’un bon trimestre ne protège pas d’un gap. La veille finissait à ' + usd(p0728[4]) + ', l’ouverture s’est faite à ' + usd(d0728[1]) + ' : un stop placé entre les deux est exécuté au premier prix disponible. Le slippage, l’écart dans une séance normale, reste modéré avec environ ' + fr(adv / 1e6, 0) + ' M$ échangés par séance. La taille de la position doit donc supposer une ouverture défavorable, pas seulement la distance au stop.' },
      tradeIdea: { status: 'watch', statusNote: 'Surveiller. Avant activation : aucune entrée ; une clôture sous ' + usd(abandon) + ' abandonne le scénario. Activation : clôture au-dessus de ' + usd(entry) + ', puis achat à l’ouverture suivante seulement sous ' + usd(cap) + ', ou par ordre limité à ce plafond pendant trois séances, annulé après une clôture sous ' + usd(entry) + ' et jamais laissé actif sur une ouverture sous ' + usd(stop) + '. Après activation : stop sous ' + usd(stop) + '. Plan du 27 août (entrée 51,49 $, stop 47,04 $, TP1 62,23 $, TP2 67,52 $) : son activation exigeait une clôture de quinze minutes au-dessus de 51,49 $, invérifiable sur barres quotidiennes. Le 28 août, le plus haut certifié, ' + usd(d0828[2]) + ', reste sous ce seuil : pas d’activation ce jour-là. Le seuil est dépassé en séance le 9 septembre (plus haut de ' + usd(d0909[2]) + ') et le 11 (' + usd(d0911[2]) + '). Si l’activation a eu lieu, le stop a été touché le 14 septembre, dans une séance ouverte à ' + usd(d0914[1]) + ' qui descend à ' + usd(d0914[3]) + ' ; aucun objectif n’a été atteint. L’outil de suivi a enregistré un stop sur la clôture du 15 septembre (' + usd(d0915[4]) + '). L’ancien stop reposait sur un plus bas du 24 août à 47,04 $ ; la série de cours retenue aujourd’hui donne ' + usd(d0824[3]) + ' pour ce jour-là.',
        entry, stop, tp1, tp2,
        stopPct: pct(stop, entry).toFixed(1) + '%', tp1Pct: '+' + pct(tp1, entry).toFixed(1) + '%', tp2Pct: '+' + pct(tp2, entry).toFixed(1) + '%',
        rr: '1:' + rr1.toFixed(2) + ' TP1 / 1:' + rr2.toFixed(2) + ' TP2',
        entryNote: 'Déclencheur sur clôture au-dessus du plus haut du 23 septembre, pas sur un franchissement en séance. Entrée à l’ouverture suivante uniquement sous ' + usd(cap) + ' : au-delà, le R/R vers TP1 tomberait sous 1,5 avec le même stop. Ce plafond n’est qu’à ' + usd(cap - entry) + ' au-dessus du déclencheur, soit ' + fr(bufAtr, 2) + ' ATR. Mesure : sur les ' + gs.total + ' dernières séances, ' + gs.up + ' ouvertures ont dépassé la clôture de la veille de plus de ' + usd(cap - entry) + ', soit environ ' + fr(blocked, 0) + ' % ; l’écart d’ouverture médian, dans un sens ou dans l’autre, vaut ' + usd(gs.medAbs) + '. Sur la série, ' + bk.n + ' clôtures ont cassé un plus haut de vingt séances : ' + bk.inBand + ' ont fini à moins de ' + fr(bufPct, 2) + ' % au-dessus du niveau cassé, l’écart relatif du plafond, et ' + bk.buyable + ' ont ensuite ouvert sous ce seuil, soit environ ' + fr(bufOpen * 100, 0) + ' % des cassures' + (bufOpen < 0.25 ? ' : l’entrée à l’ouverture est quasi inexécutable.' : ' : l’entrée à l’ouverture reste possible, mais moins d’une fois sur deux.') + ' Plan de repli : si l’ouverture dépasse le plafond, un ordre à cours limité à ' + usd(cap) + ', valable trois séances, garde le même R/R et le même stop. Bornes de cet ordre : il est annulé après toute clôture sous le déclencheur, ' + usd(entry) + ' ; il n’est pas laissé actif à l’ouverture d’une séance qui ouvre sous le stop, ' + usd(stop) + ', ni si le stop est touché avant exécution. Rejouées avec ces bornes sur les ' + rt.miss + ' cassures non achetables à l’ouverture, l’ordre aurait été exécuté ' + rt.back + ' fois' + (rt.stopSame ? ', dont ' + rt.stopSame + ' avec le stop touché la même séance' : ', sans que le stop soit touché la même séance') + (rt.gapUnder ? ' ; ' + rt.gapUnder + ' fois retiré sur une ouverture sous le stop' : ' ; aucun retrait sur ouverture sous le stop') + (rt.fillCloseUnder ? ' ; ' + rt.fillCloseUnder + ' de ces exécutions ont fini la séance sous le niveau cassé.' : ' ; aucune exécution n’a fini la séance sous le niveau cassé.') + ' La borne de clôture sous le déclencheur n’est pas comptée à part : une telle clôture suppose que le plafond a été touché dans la séance, donc que l’ordre a déjà été exécuté. Définition statistique : une cassure est la première clôture au-dessus du plus haut des vingt séances précédentes, la veille ayant clôturé à ce niveau ou dessous ; le plan, lui, s’active sur toute clôture au-dessus du déclencheur.' + ' Objectifs : TP1 au plus haut du 17 août, TP2 au plus haut du 27 juillet ; résistances intermédiaires vers 56,92 $ et 60,26 $. Liquidité : environ ' + fr(adv / 1e6, 0) + ' M$ échangés par séance, médiane des vingt dernières. Exemple de taille, non personnalisé : avec un budget de perte de 100 $, le risque au plafond, ' + usd(cap - stop) + ' par action, donne ' + sizeExample + ' actions ; un gap comme celui du 14 septembre pourrait alourdir nettement la perte réelle.',
        horizon: 'Dix séances après activation',
        thesis: 'Le marché a puni en juillet un trimestre record, par crainte d’investissements trop lourds. Le titre a reconstruit une base au-dessus de 45 $ et remonte vers sa moyenne à cinquante séances. Une clôture au-dessus de $' + entry.toFixed(2) + ' montrerait que les acheteurs acceptent le plan d’investissement. Avant activation, une clôture sous ' + usd(abandon) + ' abandonne le dossier. Après activation, le stop sous $' + stop.toFixed(2) + ' limite le coût d’une fausse sortie. TP1 à ' + usd(tp1) + ' et TP2 à ' + usd(tp2) + '. Ne pas anticiper le déclencheur, ne pas acheter un gap au-dessus du plafond, réduire avant la publication de Micron.',
        catalysts: ['Une clôture au-dessus du plus haut du 23 septembre, sur un volume au moins égal à la médiane récente.', 'La publication de Micron le 30 septembre, après la clôture selon les deux calendriers : Amkor conditionne des mémoires.', 'Tout signal sur les commandes de smartphones d’Apple pour la fin d’année.'],
        invalidation: ['Avant activation : une clôture sous ' + usd(abandon) + ', bas du 21 septembre, abandonne le scénario.', 'Après activation : une clôture sous ' + usd(stop) + ' invalide le trade.', 'Ouverture au-dessus de ' + usd(cap) + ' après la clôture de déclenchement : pas d’achat à l’ouverture ; seul l’ordre limité à ' + usd(cap) + ' reste valable trois séances.', 'Ordre limité de repli annulé après une clôture sous ' + usd(entry) + ', retiré avant toute ouverture sous le stop à ' + usd(stop) + ' et si le stop est touché avant exécution.', 'Une baisse de prévision d’Apple ou de Qualcomm avant activation annule la thèse.'] },
      globalScore: { profile: 'Sous-traitant en hausse de marges, investissements lourds, clients concentrés',
        keyTakeawaysPositive: ['Ventes record, +26 %.', 'Marge brute de 12,0 à 16,8 % en un an.', 'Trésorerie égale à la dette.'],
        keyTakeawaysNegative: ['−24,7 % au lendemain de la publication.', 'Apple et Qualcomm à 41 % des ventes 2025.', '2,5 à 3,0 Md$ d’investissements en 2026.'],
        mindsetTip: 'Quand un titre chute d’un quart sur un trimestre record, le marché ne juge pas le passé, il juge le prix du futur. Attendre qu’il change d’avis, c’est attendre la clôture qui le prouve.' },
      social: { platforms: [], sourceRefs: [market('sentiment non retenu faute de mesure qualifiée')] },
      disclaimer: 'Document de recherche éducatif. Ni conseil financier, ni signal de trading. Statut surveiller : aucun ordre actif.',
    };
  },
  groups: [
    { name: 'Référence du conditionnement', order: 1, transmission: 'Le premier sous-traitant mondial d’assemblage et de test, concurrent direct et titre coté qui co-évolue le plus avec Amkor parmi ses pairs de métier.', rows: [
      ['ASX', 'leader', 'Premier sous-traitant mondial d’assemblage et de test', 'Même métier, mêmes clients ; ses commandes et ses prix de conditionnement se lisent directement sur ceux d’Amkor.']] },
    { name: 'Pairs directs : conditionnement avancé', order: 1, transmission: 'Concurrents sur le conditionnement avancé des puces d’IA et des processeurs.', rows: [
      ['TSM', 'direct_peer', 'Fonderie qui conditionne aussi ses puces', 'Premier acteur du conditionnement avancé des puces d’IA ; ses capacités fixent la part laissée aux sous-traitants.'],
      ['INTC', 'direct_peer', 'Fonderie et conditionnement avancé pour tiers', 'Propose aussi ses techniques de conditionnement à des clients tiers, concurrent émergent d’Amkor.']] },
    { name: 'Clients documentés et aval', order: 1, transmission: 'Les fabricants de puces confient le conditionnement à Amkor ; leurs volumes font ses ventes.', rows: [
      ['AAPL', 'downstream', 'Client documenté, 29,8 % des ventes 2025', 'Premier client en direct ; le volume de ses smartphones et de ses puces maison fait près d’un tiers des ventes d’Amkor.'],
      ['QCOM', 'downstream', 'Client documenté, 11,1 % des ventes 2025', 'Deuxième client ; ses puces mobiles et automobiles passent par les usines d’Amkor.'],
      ['NVDA', 'downstream', 'Concepteur de processeurs d’IA', 'Ses processeurs d’IA exigent un conditionnement avancé dont Amkor veut une part croissante.'],
      ['AVGO', 'downstream', 'Concepteur de puces sur mesure', 'Ses puces sur mesure pour les grands clouds utilisent le conditionnement avancé.'],
      ['AMD', 'downstream', 'Concepteur de processeurs et d’accélérateurs', 'Ses processeurs à puces multiples reposent sur le conditionnement avancé.'],
      ['MU', 'downstream', 'Fabricant de mémoires', 'Ses mémoires passent en partie par les sous-traitants de conditionnement ; publie le 30 septembre.']] },
    { name: 'Amont : équipements et matériaux', order: 2, transmission: 'Amkor achète machines de test, d’inspection et matériaux : leurs commandes précèdent ses capacités.', rows: [
      ['TER', 'upstream', 'Équipements de test des puces', 'Fournisseur de testeurs ; ses commandes des sous-traitants annoncent les volumes de test d’Amkor.'],
      ['COHU', 'upstream', 'Équipements de manipulation et de test', 'Fournisseur de machines de test et de manipulation pour les usines de conditionnement.'],
      ['ONTO', 'upstream', 'Inspection du conditionnement avancé', 'Fournisseur d’inspection pour le conditionnement avancé, segment où Amkor investit.'],
      ['KLAC', 'upstream', 'Contrôle et inspection des procédés', 'Fournisseur de contrôle de procédés ; son activité de conditionnement suit les capacités des sous-traitants.'],
      ['ENTG', 'upstream', 'Matériaux et consommables des puces', 'Fournisseur de matériaux ; ses volumes suivent l’activité des usines de la chaîne.'],
      ['UCTT', 'upstream', 'Sous-ensembles des équipements', 'Fournisseur des fabricants d’équipements ; signal avancé du cycle d’investissement.']] },
    { name: 'Contrôles sectoriels', order: 2, transmission: 'Paniers de référence pour isoler ce qui est propre à Amkor.', rows: [
      ['SMH', 'sector_proxy', 'Panier de semi-conducteurs', 'Contrôle du secteur : un écart avec ce panier isole ce qui est propre à Amkor.'],
      ['SOXX', 'sector_proxy', 'Second panier de semi-conducteurs', 'Contrôle plus large : confirme ou infirme la lecture tirée de SMH.'],
      ['QQQ', 'sector_proxy', 'Grandes valeurs du Nasdaq', 'Contrôle large : un mouvement commun avec ce panier n’a rien de spécifique au titre.']] },
  ],
  eventDefault: { leader: 'Aucune publication dans les quatorze jours collectés ; ses commandes de conditionnement restent le signal à suivre', direct_peer: 'Aucune publication dans les quatorze jours collectés ; ses capacités de conditionnement sont à suivre', downstream: 'Aucune publication dans les quatorze jours collectés ; ses volumes de puces sont à suivre', upstream: 'Aucune publication dans les quatorze jours collectés ; ses commandes d’équipements sont à suivre', sector_proxy: 'Panier sans publication propre ; exposé aux résultats de ses grandes pondérations' },
  eventRisk: { MU: 'Publication le 30 septembre après la clôture, date donnée par deux calendriers concordants et non confirmée ici par l’émetteur : risque de gap sur les volumes de mémoire, dans l’horizon du plan' },
  blastDoc: 2,
  scenarios: c => [
    { scenario: 'bullish', trigger: 'Micron rassure sur les volumes et le secteur poursuit son rebond.', firstOrder: 'Le titre clôture au-dessus du plus haut du 23 septembre.', secondOrder: 'SMH et ASE confirment ; la moyenne à cinquante séances est reprise.', confirmation: 'Une clôture au-dessus de ' + c.usd(c.entry) + ' avec SMH en hausse.', contradiction: 'Un dépassement du déclencheur pendant que SMH recule.' },
    { scenario: 'mixed', trigger: 'Pas de nouvelle propre avant la publication de Micron.', firstOrder: 'Le titre oscille entre le bas du 21 septembre et le plus haut du 23.', secondOrder: 'L’écart avec SMH reste faible, sans information propre au titre.', confirmation: 'Des clôtures entre ' + c.usd(c.abandon) + ' et ' + c.usd(c.entry) + ' pendant plusieurs séances.', contradiction: 'Une sortie franche d’un côté ou de l’autre.' },
    { scenario: 'bearish', trigger: 'Commandes de smartphones en baisse ou volumes de mémoire décevants chez Micron.', firstOrder: 'Le titre repasse sous le bas du 21 septembre.', secondOrder: 'Apple et Qualcomm reculent ; les équipementiers suivent.', confirmation: 'Une clôture sous ' + c.usd(c.abandon) + ' avec SMH en baisse.', contradiction: 'Un repli d’Amkor que le secteur ne suit pas.' }],
  contradictions: c => ['La prévision relève marge et ventes, mais le titre a perdu un quart de sa valeur le lendemain : le marché ne croit pas au rendement des investissements annoncés.', 'Apple est le premier client, mais sa corrélation avec Amkor est proche de zéro depuis fin mars : le lien commercial ne passe pas par le cours.'],
  missingData: c => ['Base comptable agrégée de la SEC arrêtée au 31 mars : dernier trimestre lu dans les données structurées du 10-Q.', 'Part d’Apple et de Qualcomm publiée pour 2025 seulement ; date de publication du troisième trimestre donnée par un seul calendrier.', 'Chaîne d’options relevée en séance, non rattachée à la clôture ; sentiment non retenu.', 'Barres d’une source de repli pour toutes les séries.'],
  limitations: ['Barres d’une source de repli (Webull).', 'Options non rattachées à la clôture de référence.', 'Dernier trimestre GAAP lu dans les données structurées du 10-Q.'],
});
