'use strict';
// Dossier AVGO v3 au close du 2026-09-23 (lot R02). Contenu éditorial et niveaux propres au titre ;
// calculs, provenance et preuves délégués au gabarit commun tools/lib/analysis-v3-r02.cjs.
const R = require('../../../../tools/lib/analysis-v3-r02.cjs');
const GEN = 'analyses/AVGO/_runs/20260924/build-avgo.cjs';

R.build({
  ticker: 'AVGO', shortName: 'Broadcom', cik: 1730168, generator: GEN, mode: 'breakout',
  xbrl: { ttm: { rev: ['RevenueFromContractWithCustomerExcludingAssessedTax', 'Revenues'], ebit: ['OperatingIncomeLoss'], ni: ['ProfitLoss', 'NetIncomeLoss'], dep: ['Depreciation'], amort: ['AmortizationOfIntangibleAssets'], ocf: ['NetCashProvidedByUsedInOperatingActivities'], capex: ['PaymentsToAcquirePropertyPlantAndEquipment'] },
    instant: { debtTotal: ['LongTermDebt'], cashEq: ['CashAndCashEquivalentsAtCarryingValue'] }, da: ['dep', 'amort'], debt: ['debtTotal'], cash: ['cashEq'] },
  scenarioMultiple: 25, valuationBasis: 'GAAP douze mois au 2026-08-02 (XBRL SEC) ; multiple de vingt-cinq fois l’EBITDA = hypothèse éditoriale',
  levels: { trigger: { d: '2026-08-28', c: 2 }, stop: { d: '2026-09-22', c: 3 }, abandon: { d: '2026-09-16', c: 3 },
    s1: { d: '2026-09-17', c: 3 }, s2: { d: '2026-09-15', c: 3 }, r1: { d: '2026-09-22', c: 2 }, r2: { d: '2026-09-08', c: 2 } },
  supports: ['s1', 's2', 'abandon'], resistances: ['r1', 'r2', 'trigger'],
  targets: ({ entry, abandon }) => { const range = entry - abandon; return { tp1: entry + 0.75 * range, tp2: entry + range, range }; },
  levelsMethod: 'Déclencheur = plus haut du 28 août ; bas du couloir = plus bas du 16 septembre ; stop = plus bas du 22 septembre ; TP1 = déclencheur + 0,75 × hauteur du couloir ; TP2 = déclencheur + hauteur ; plafond = (TP1 + 1,5 × stop) / 2,5 ; pourcentages depuis l’entrée ; R/R = gain / risque.',
  inventory: 32,
  reviewScope: 'Dépôts EDGAR de Broadcom du 1er janvier au 23 septembre 2026 (32 formulaires hors formulaires 3, 4, 5 et 144), plus le 10-K de l’exercice 2025. Les 8-K de gouvernance (items 5.02, 5.07), les avis d’effet, le formulaire SD, les déclarations 13G et les procurations sont écartés comme non décisionnels. Le 424B5, le FWP et le 424B2 de janvier documentent 4,5 Md$ d’obligations à échéance 2031 à 2056, déjà comprises dans la dette du 10-Q ; les S-4 et 424B3 de juin et de septembre enregistrent des échanges d’obligations existantes, sans nouvelle dette.',
  docs: [
    ['2026-09-02', '8-K / Exhibit 99.1', '0001730168-26-000076', 'avgo-08022026x8kxex99.htm', 'q3fy26-8k__avgo-08022026x8kxex99.htm',
      'Communiqué du troisième trimestre de l’exercice 2026 : chiffre d’affaires de 29,6 Md$, en hausse de 86 %, dont 16,7 Md$ de semi-conducteurs pour l’IA (+221 %). Flux de trésorerie libre de 13,7 Md$. Prévision du quatrième trimestre à 34,8 Md$, dont 21,7 Md$ pour l’IA, et dividende trimestriel de 0,65 $.'],
    ['2026-09-10', '10-Q', '0001730168-26-000080', 'avgo-20260802.htm', 'q3fy26-10q__avgo-20260802.htm',
      'Rapport trimestriel au 2 août 2026 : un distributeur non nommé a représenté 50 % des revenus du trimestre et 46 % sur neuf mois, contre 32 % un an plus tôt ; les cinq premiers clients finaux, environ 55 % contre environ 40 %. Dette de 59,4 Md$ : 4,47 Md$ empruntés et 10,53 Md$ remboursés sur neuf mois.'],
    ['2025-12-18', '10-K', '0001730168-25-000121', 'avgo-20251102.htm', 'fy25-10k__avgo-20251102.htm',
      'Rapport annuel de l’exercice 2025 : un client, non nommé, a représenté 32 % du chiffre d’affaires, contre 28 % et 21 % les deux exercices précédents, et 44 % des créances. Le 10-Q publie 32 % au même trimestre de 2025 pour son distributeur principal : c’est vraisemblablement le même compte.'],
    ['2026-09-18', '424B3', '0001193125-26-395593', 'd154803d424b3.htm', 'sep18-424b3__d154803d424b3.htm',
      'Prospectus d’échange de 654 004 000 $ d’obligations à 4,926 % échéance 2037 contre des titres identiques enregistrés : l’opération ne lève aucun fonds et, selon le texte, n’augmente pas l’endettement. Aucune émission d’actions n’est associée.'],
    ['2026-08-27', '8-K / Exhibit 99.1 (Marvell)', '0001835632-26-000022', 'q227_8kx812026ex-991.htm', 'mrvl-q2fy27-8k__q227_8kx812026ex-991.htm',
      'Communiqué de Marvell, seul concurrent direct de Broadcom sur les puces sur mesure : la société annonce une journée investisseurs le 6 octobre 2026 pour présenter sa stratégie de long terme et une accélération de son activité sur mesure au second semestre.', 1835632],
  ],
  needles: {
    q3: [0, ['$29.6 billion', '$16.7 billion', '221%', '$34.8 billion', '$21.7 billion', '$13.7 billion', '$0.65 per share']],
    debt: [1, ['59,419', '61,079', '8,450', '4,773,629,865', 'accounted for 50% and 46% of our net revenue', 'approximately 55% and 50% of our net revenue', 'Balance as of February 1, 2026 4,736', 'Proceeds from long-term borrowings 4,474', 'Payments on debt obligations ( 10,528 )', 'approximately 40% of our net revenue for each of the fiscal quarter', 'which is a distributor']],
    mrvl: [4, ['at our Investor Day on October 6 th , 2026']],
    concentration: [2, ['one customer accounted for 32 %, 28 % and 21 % of our net revenue', 'One customer accounted for 44 % and 18 % of our net accounts receivable']],
    exchange: [3, ['$654,004,000', 'will not result in any increase in our outstanding indebtedness']],
  },
  sectionDocs: { verdict: [0, 1, 2], business: [0, 2], news: [0], earnings: [0], capitalStructure: [1, 3], filingsReview: [1, 2, 3], risks: [2, 1], globalScore: [0], meta: [0], disclaimer: [0], macro: [0], options: [0], social: [0], header: [0] },
  score: { business: 30, technical: -4, capital: 2, calendar: 0, dilution: 0, risk: 30 },
  peers: true, extraInputs: [{ name: 'mu', path: 'analyses/MU/_data/earnings_risk.json' }],
  route: (p, { prov, dep }) => /^(tradeIdea\.catalysts\.1|verdict\.controlChecklist\.2\.|blastRadius\.groups\.1\.symbols\.2\.eventRisk)/.test(p) ? prov('mu', '/events/0/report_date', 'Date de publication de Micron lue dans deux calendriers de données, non confirmée par Micron ; journée investisseurs de Marvell datée par son communiqué du 27 août 2026.', [dep('primary', '/documents/4')]) : null,
  riskScoreReason: 'Jugement qualitatif sur dix : concentration sur quelques clients finaux, tendance baissière du titre et sensibilité aux taux.',
  compose: c => {
    const { fr, usd, pct, sgn, dfr, close, prev, bars, N, tech, st, M, adv, ret, G$, marketCap, ev, scn, lv, entry, stop, tp1, tp2, abandon, cap, rr1, rr2, riskAtr, sizeExample, ref, market, docs, raw } = c;
    const smh21 = M.SMH.return21d, soxx21 = M.SOXX.return21d, gs = c.gapStats(cap - entry);
    const hi = bars.slice(N - 60).reduce((m, b) => b[2] > m.v ? { v: b[2], d: b[0] } : m, { v: 0 });
    return {
      meta: { lang: 'fr', dir: 'ltr', level: 'intermediate', tags: ['us', 'equities', 'ai-chain', 'semis', 'technology'], grade: 'B-', date: '2026-09-24', dateDisplay: '24 septembre 2026', version: 3, status: 'watch', assetType: 'stock', levelsCloseDate: c.REF,
        description: 'Broadcom : des puces d’IA qui triplent, un cours qui recule depuis août. Dossier au close du 23 septembre 2026, statut surveiller.',
        ogDescription: 'Broadcom : croissance IA record, un distributeur à 50 % des revenus du trimestre, titre en retard sur les semi-conducteurs ; niveaux à surveiller.',
        lastMcpRefresh: raw.status.captured_at, levelsVerifiedAt: raw.status.captured_at,
        statusHistory: [{ at: raw.status.captured_at, from: 'wait', to: 'watch', note: 'refonte v3 du 24 septembre : nouveau scénario, clôture de référence du 2026-09-23', close }] },
      header: { ticker: 'AVGO', name: 'Broadcom Inc.', exchange: 'NASDAQ', sector: 'Semi-conducteurs sur mesure, réseau et logiciels d’infrastructure', price: close, changePct: pct(close, prev),
        badges: [{ text: 'SURVEILLER — PAS D’ENTRÉE AU COURS ACTUEL', color: 'blue' }, { text: 'Chaîne IA — puces sur mesure', color: 'purple' }],
        metrics: { marketCap: fr(marketCap / 1e12, 2) + ' T$', volume: fr(bars[N][5] / 1e6, 1) + ' M', evEbitda: fr(ev / G$.ebitda, 1) + '×' }, halalStatus: 'unknown' },
      verdict: { score: 58, conviction: 'Moderate', bias: 'Neutral',
        confidence: 'Score éditorial non prédictif. Les chiffres d’entreprise viennent des dépôts SEC et des données XBRL officielles ; les niveaux, du close certifié du 23 septembre.',
        summary: 'Broadcom vient de publier son meilleur trimestre : 29,6 Md$ de chiffre d’affaires, des puces d’IA en hausse de 221 % et une prévision de 34,8 Md$ pour le trimestre suivant. Le cours, lui, a perdu environ ' + fr(Math.abs(pct(close, hi.v)), 0) + ' % depuis son plus haut du ' + dfr(hi.d) + ' et fait moins bien que les paniers de semi-conducteurs sur vingt et une séances. Deux raisons tiennent la ligne. Un distributeur non nommé a pesé 50 % des revenus du trimestre, contre 32 % un an plus tôt, et les cinq premiers clients finaux environ 55 % : la croissance est puissante mais étroite. Et le titre se paie environ ' + fr(ev / G$.ebitda, 0) + ' fois l’EBITDA GAAP, un multiple qui supporte mal un taux à 10 ans au plus haut depuis 2007. Pas d’entrée au cours actuel. Le signal utile serait une clôture au-dessus du plus haut du 28 août ; une clôture sous le bas du 16 septembre ferait abandonner le scénario.',
        whyBuy: [
          'Le chiffre d’affaires du troisième trimestre atteint 29,6 Md$ (+86 %), dont 16,7 Md$ de semi-conducteurs pour l’IA en hausse de 221 %.',
          'La prévision du quatrième trimestre vise 34,8 Md$, dont 21,7 Md$ pour l’IA : la croissance accélère encore.',
          'Le flux de trésorerie libre du trimestre, 13,7 Md$, représente 46 % des revenus : la société finance seule dividende et rachats.',
          'Aucune émission d’actions n’est relevée en 2026, et la dette nette baisse : 10,53 Md$ remboursés contre 4,47 Md$ empruntés sur neuf mois.'],
        whyAvoid: [
          'Au close du 23 septembre, la valeur d’entreprise représente ' + fr(ev / G$.ebitda, 1) + ' fois l’EBITDA GAAP des douze mois clos le 2 août : la valorisation suppose une croissance longue.',
          'Un distributeur non nommé a pesé 50 % des revenus du trimestre, et les cinq premiers clients finaux environ 55 % : une pause de leurs commandes se verrait immédiatement.',
          'Le titre a fait ' + sgn(ret(21), 1) + ' sur vingt et une séances contre ' + sgn(smh21, 1) + ' pour SMH : le marché vend la publication plutôt qu’il ne l’achète.',
          'La dette totale reste de 59,4 Md$ au 2 août, héritage du rachat de VMware : elle pèse sur la marge de manœuvre si les taux restent hauts.'],
        controlChecklist: [
          { label: 'Historique de cours', status: 'pass', statusLabel: 'Trois cents séances continues', evidence: 'Série quotidienne certifiée au close du 23 septembre, source de repli documentée.', action: 'Niveaux et indicateurs recalculés sur cette seule série.' },
          { label: 'Concentration client', status: 'warn', statusLabel: 'Cinq clients finaux à 55 %', evidence: 'Le 10-Q publie un distributeur à 50 % du trimestre et les cinq premiers clients finaux à environ 55 %, contre environ 40 % un an plus tôt. Aucun nom publié.', action: 'Surveiller tout commentaire sur les commandes des grands clouds.' },
          { label: 'Calendrier', status: 'warn', statusLabel: 'Micron le ' + dfr(c.extra.mu.events[0].report_date) + ', Marvell le 6 octobre', evidence: 'Micron publie le ' + dfr(c.extra.mu.events[0].report_date) + ' après la clôture selon deux calendriers de données, sans confirmation de Micron ; Marvell tient sa journée investisseurs le 6 octobre, selon son communiqué du 27 août.', action: 'Risque de gap les 1er et 7 octobre, dans l’horizon de dix séances.' }] },
      business: { theme: 'Puces sur mesure pour l’IA, réseau Ethernet et logiciels d’infrastructure',
        overview: '<p>Broadcom conçoit des puces sur mesure pour les grands clouds, des accélérateurs d’IA dessinés pour chaque client et fabriqués à façon, ainsi que les commutateurs et puces réseau qui relient ces accélérateurs entre eux. S’y ajoute un pôle de logiciels d’infrastructure issu du rachat de VMware. Au troisième trimestre de l’exercice 2026, clos le 2 août, les semi-conducteurs ont pesé 20,8 Md$ sur 29,6 Md$ de revenus, et le logiciel 8,8 Md$.</p><p>La croissance vient presque entièrement de l’IA : 16,7 Md$ au trimestre, en hausse de 221 % sur un an et de 54 % sur trois mois. La direction attend 21,7 Md$ au trimestre suivant. Les puces sur mesure de Broadcom sont l’alternative principale aux processeurs graphiques de NVIDIA pour les clouds qui veulent maîtriser leur coût de calcul.</p><p>Le revers est la concentration, et elle s’aggrave. Le 10-Q du troisième trimestre indique qu’un distributeur a représenté 50 % des revenus du trimestre, contre 32 % un an plus tôt. Un distributeur n’est pas un client final unique : il revend à plusieurs acheteurs. La mesure utile est donc celle des clients finaux, que Broadcom estime lui-même : les cinq premiers pèsent environ 55 % des revenus du trimestre, contre environ 40 % un an plus tôt. Chaque trimestre record dépend d’un très petit nombre de programmes de puces, dont le calendrier appartient au client.</p>',
        moat: 'L’avantage de Broadcom tient à sa capacité à dessiner des accélérateurs et des puces réseau complexes pour les plus grands acheteurs du monde, avec un logiciel VMware qui génère une trésorerie stable. Il est solide sur le plan technique, plus fragile commercialement tant que cinq clients finaux pèsent plus de la moitié des ventes.',
        segments: [
          { name: 'Semi-conducteurs', revenue: '20,8 Md$ au trimestre', pct: '70 %', description: 'En hausse de 127 % sur un an, portés par l’IA.' },
          { name: 'Logiciels d’infrastructure', revenue: '8,8 Md$ au trimestre', pct: '30 %', description: 'En hausse de 29 % sur un an.' }],
        sourceRefs: [ref(0), ref(2)],
        coverageMatrix: [
          { facet: 'Cours et historique', status: 'COUVERT', decision: 'Trois cents séances continues, close certifié ; base des niveaux et des indicateurs.' },
          { facet: 'Résultats et guidance', status: 'COUVERT — PRIMAIRE', decision: 'Communiqué du 2 septembre et 10-Q ; prochaine date non confirmée.' },
          { facet: 'Capital et dette', status: 'COUVERT — PRIMAIRE', decision: 'Dette, rachats et échange d’obligations séparés ; aucune émission d’actions.' },
          { facet: 'Agrégats GAAP', status: 'COUVERT — XBRL', decision: 'Douze mois glissants reconstitués depuis les données XBRL officielles.' },
          { facet: 'Comparables et transmission', status: 'COUVERT — LOCAL', decision: 'Corrélations recalculées sur barres certifiées depuis la fin mars.' },
          { facet: 'Initiés', status: 'PARTIEL', decision: 'Deux retenues fiscales seulement dans la fenêtre relevée ; aucun solde net affirmé.' },
          { facet: 'Options', status: 'NON EXPLOITABLE', decision: 'Chaîne relevée marché fermé, sans intérêt ouvert utilisable.' }] },
      news: [
        { date: '2026-09-02', title: 'Troisième trimestre : 29,6 Md$ et une IA en hausse de 221 %', impact: 'positive', detail: 'La croissance dépasse ce que visait la société il y a un an, mais le titre a reculé le lendemain : la publication a été vendue plutôt qu’achetée.', source: 'Broadcom — SEC', sourceUrl: docs[0].url },
        { date: '2026-09-10', title: 'Le 10-Q confirme 59,4 Md$ de dette', impact: 'neutral', detail: 'La dette nette baisse : 4,47 Md$ empruntés et 10,53 Md$ remboursés sur neuf mois, financés par la trésorerie dégagée.', source: 'Broadcom — SEC', sourceUrl: docs[1].url },
        { date: '2026-09-18', title: 'Échange de 654 M$ d’obligations 2037', impact: 'neutral', detail: 'Une opération technique qui rend des titres existants négociables ; elle ne lève pas d’argent et ne dilue pas les actionnaires.', source: 'Broadcom — SEC', sourceUrl: docs[3].url }],
      fundamentals: { rows: [
          { metric: 'Chiffre d’affaires du trimestre', value: '29,6 Md$', signal: '+86 % sur un an, communiqué du 2 septembre', signalColor: 'green', _src: 0 },
          { metric: 'Semi-conducteurs pour l’IA du trimestre', value: '16,7 Md$', signal: '+221 % sur un an', signalColor: 'green', _src: 0 },
          { metric: 'Prévision du quatrième trimestre', value: '34,8 Md$', signal: 'Dont 21,7 Md$ pour l’IA', signalColor: 'blue', _src: 0 },
          { metric: 'Flux de trésorerie libre du trimestre', value: '13,7 Md$', signal: '46 % des revenus du trimestre', signalColor: 'green', _src: 0 },
          { metric: 'Rachats d’actions sur neuf mois', value: '8,45 Md$', signal: 'Tableau des flux du 10-Q', signalColor: 'blue', _src: 1 },
          { metric: 'Part des cinq premiers clients finaux (trimestre)', value: 'Environ 55 %', signal: 'Contre environ 40 % au même trimestre de 2025, estimation de Broadcom', signalColor: 'red', _src: 1 },
          { metric: 'Part du premier distributeur (trimestre)', value: '50 %', signal: '46 % sur neuf mois, contre 32 % au même trimestre de 2025 ; un distributeur revend à plusieurs clients', signalColor: 'amber', _src: 1, _also: [2] },
          { metric: 'Revenus GAAP sur douze mois', value: fr(G$.rev / 1e9, 1) + ' Md$', signal: 'Douze mois glissants au 2 août 2026 (XBRL SEC)', signalColor: 'blue', _src: 'gaap' },
          { metric: 'EBITDA GAAP sur douze mois', value: fr(G$.ebitda / 1e9, 1) + ' Md$', signal: 'Résultat opérationnel + amortissements, douze mois au 2 août 2026', signalColor: 'blue', _src: 'gaap' },
          { metric: 'Résultat net GAAP sur douze mois', value: fr(G$.ni / 1e9, 1) + ' Md$', signal: 'Douze mois glissants au 2 août 2026', signalColor: 'green', _src: 'gaap' },
          { metric: 'Dette au 2 août 2026', value: fr(G$.debt / 1e9, 1) + ' Md$', signal: 'Dette totale inscrite au bilan du 10-Q', signalColor: 'amber', _src: 'gaap' },
          { metric: 'Trésorerie au 2 août 2026', value: fr(G$.cash / 1e9, 1) + ' Md$', signal: 'Liquidités et équivalents, bilan du 10-Q', signalColor: 'blue', _src: 'gaap' },
          { metric: 'EV/EBITDA GAAP', value: fr(ev / G$.ebitda, 1) + '×', signal: 'Valeur d’entreprise au close du 2026-09-23 sur EBITDA GAAP douze mois au 2026-08-02', signalColor: 'amber', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus Nvidia à ' + fr(c.peerEv('NVDA'), 1) + '× et Qualcomm à ' + fr(c.peerEv('QCOM'), 1) + '× (statistiques courantes du 24 septembre, non point-in-time) : Broadcom se paie plus cher que Nvidia.', _src: 'market', _peers: ['NVDA', 'QCOM'] },
          { metric: 'EV/revenus GAAP', value: fr(ev / G$.rev, 1) + '×', signal: 'Valeur d’entreprise au close du 2026-09-23 sur revenus GAAP douze mois au 2026-08-02', signalColor: 'amber', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus une croissance de 86 % au dernier trimestre : le multiple suppose que la croissance ralentisse sans s’arrêter.', _src: 'market' },
          { metric: 'P/E GAAP sur douze mois', value: fr(marketCap / G$.ni, 1) + '×', signal: 'Douze mois glissants : capitalisation au 2026-09-23 sur résultat net GAAP douze mois au 2026-08-02', signalColor: 'amber', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus EV/EBITDA : l’amortissement des actifs de VMware réduit le résultat GAAP et gonfle ce multiple.', _src: 'market' },
          { metric: 'EV/EBITDA — scénario de compression (hypothèse éditoriale)', value: fr(scn.price, 2) + ' $ par action', signal: 'Scénario : multiple ramené à vingt-cinq fois l’EBITDA GAAP par hypothèse, dette et trésorerie du 2026-08-02 inchangées, soit ' + fr(scn.downside_pct, 0) + ' % sous le close du 2026-09-23', signalColor: 'red', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus le close : vingt-cinq fois place Broadcom près de Nvidia (' + fr(c.peerEv('NVDA'), 1) + '× le 24 septembre) et au-dessus de Qualcomm (' + fr(c.peerEv('QCOM'), 1) + '×) ; ce que coûterait ce rapprochement, pas un objectif.', _src: 'market', _peers: ['NVDA', 'QCOM'] }],
        sourceRefs: [ref(0), ref(1), market('fondamentaux et statistiques')] },
      earnings: { quarters: [],
        beatNote: 'Troisième trimestre de l’exercice 2026 : bénéfice par action GAAP de 2,68 $ et ajusté de 3,32 $, résultat opérationnel GAAP de 16,0 Md$. La guidance du quatrième trimestre vise 34,8 Md$ de revenus et une marge opérationnelle ajustée d’environ 66 %, dont 21,7 Md$ de semi-conducteurs pour l’IA. L’écart entre GAAP et ajusté vient surtout de l’amortissement des actifs incorporels de VMware et de la rémunération en actions. Aucune date de prochaine publication n’est confirmée par l’émetteur à ce jour.',
        nextEarnings: 'Date non confirmée par l’émetteur ; aucune publication dans les quatorze jours du calendrier collecté.',
        sourceRefs: [ref(0)] },
      capitalStructure: { sharesOutstanding: fr(st.sharesOutstanding / 1e9, 3) + ' milliards d’actions au 28 août 2026 (page de garde du 10-Q)',
        sharesAuthorized: 'Actions autorisées non reprises : non décisionnel pour ce dossier.', dilutionRisk: 'low',
        shareHistory: 'Le nombre d’actions en circulation progresse lentement, de 4,74 milliards début février à 4,77 milliards fin août, sous l’effet de la rémunération en actions ; les rachats, 8,45 Md$ sur neuf mois, compensent une partie de cette dilution. Aucune émission d’actions n’est relevée dans les dépôts de 2026. Le financement passe par la dette, dont l’échange du 18 septembre ne change pas le montant. Un nombre d’actions entièrement dilué n’est pas calculable depuis ces seuls dépôts.',
        warrants: [], atm: { active: false, authorized: 'Aucun programme d’émission d’actions relevé', used: 'Sans objet', remaining: 'Sans objet' },
        sourceRefs: [ref(1), ref(3)] },
      filingsReview: { summary: 'Cinq dépôts décisionnels ouverts et hachés, dont le communiqué de Marvell pour le calendrier. Ils séparent trois choses : des résultats d’IA exceptionnels, une dette élevée mais en baisse nette, et une dépendance forte à quelques clients finaux que la société ne nomme pas.',
        filings: docs.map(d => ({ date: d.date, form: d.form, accession: d.accession, finding: d.finding, url: d.url })),
        contrarianRisks: [
          'Cinq clients finaux à environ 55 % des revenus du trimestre : le programme d’un seul acheteur peut décaler un trimestre entier.',
          'Le marché a vendu une prévision record : si l’IA accélère sans faire monter le cours, c’est que la hausse est déjà dans le prix.',
          'Les grands clouds dessinent de plus en plus leurs propres puces en interne ; un client qui internalise la conception réduirait la part de Broadcom.',
          'La dette de 59,4 Md$ coûte plus cher à refinancer avec un taux à 10 ans au plus haut depuis 2007.'] },
      technicals: { rsi14: +tech.rsi14.toFixed(2), macd: +tech.macd.toFixed(2), macdSignal: +tech.macdSignal.toFixed(2), ema20: +tech.ema20.toFixed(2), ema50: +tech.ema50.toFixed(2), ema200: +tech.ema200.toFixed(2),
        ma50Type: 'EMA', ma200Type: 'EMA', ma50Available: true, ma200Available: true, atr14: +tech.atr14.toFixed(2),
        badges: ['Sous les moyennes à vingt, cinquante et deux cents séances', 'Couloir entre ' + fr(abandon, 0) + ' et ' + fr(entry, 0) + ' $', 'Pas d’entrée au cours actuel'],
        supports: [lv('s1'), lv('s2'), abandon], resistances: [lv('r1'), lv('r2'), entry],
        setupNote: 'Le titre clôture à ' + usd(close) + ', sous ses moyennes à vingt, cinquante et deux cents séances, dans un couloir entre ' + usd(abandon) + ' et ' + usd(entry) + '. Avant activation, aucune entrée ; une clôture sous ' + usd(abandon) + ', le bas du 16 septembre, abandonne le scénario. Activation sur une clôture au-dessus de $' + entry.toFixed(2) + ', le plus haut du 28 août, qui ramènerait le titre au-dessus de sa moyenne à cinquante séances. Après activation, stop sous $' + stop.toFixed(2) + ', le plus bas du 22 septembre, soit ' + fr(riskAtr, 1) + ' ATR sous le déclencheur. Supports : ' + usd(lv('s1')) + ', ' + usd(lv('s2')) + ' et ' + usd(abandon) + '. Résistances : ' + usd(lv('r1')) + ', ' + usd(lv('r2')) + ' et ' + usd(entry) + '.',
        wyckoff: 'Non utilisé : le profil de volume n’est pas exploité dans ce dossier.',
        sourceRefs: [market('barres quotidiennes et indicateurs recalculés')] },
      options: { callOI: 'Non exploitable', putOI: 'Non exploitable', cpRatio: 'Non exploitable', maxPain: 'Non exploitable', ivMean: 'Non exploitable', skew: 'Chaîne relevée marché fermé, sans intérêt ouvert utilisable', unusual: 'Aucune activité inhabituelle qualifiée', sourceRefs: [market('options')] },
      shortInterest: { siPct: fr(st.shortPercentOfFloat * 100, 2) + ' % du flottant', daysToCover: fr(st.shortRatio, 2) + ' jours, date de règlement non précisée par le snapshot', ctb: 'Coût d’emprunt bas, sans tension', trend: 'Positions vendeuses faibles ; aucune thèse de rachat forcé des vendeurs.', squeezeScore: 'Non pertinent', sourceRefs: [market('positions vendeuses')] },
      insiders: { signal: 'Aucun achat ni vente de marché dans la fenêtre relevée : seules deux retenues fiscales à l’acquisition d’actions attribuées, le 15 septembre, par le directeur juridique et la directrice financière. Couverture officielle partielle : aucun solde net publié.',
        recentTransactions: [],
        sourceRefs: [market('formulaires 4')] },
      macro: { indicators: [{ name: 'Clôture de référence', value: c.REF, signal: usd(close) + ', séance complète' }, { name: 'Rendement cinq séances', value: sgn(ret(5)), signal: 'Descriptif' }, { name: 'Rendement vingt et une séances', value: sgn(ret(21)), signal: 'Descriptif' }],
        regime: 'neutral', impact: 'Un titre valorisé sur la durée du cycle de l’IA est sensible aux taux longs : le 10 ans américain a clôturé à 5,11 % le 23 septembre, plus haut depuis juillet 2007, selon la courbe officielle du Trésor. Une hausse des taux réduit ce que le marché accepte de payer pour des bénéfices lointains.' },
      risks: { riskScore: 6, riskProfile: 'High',
        riskSummary: 'Le risque de Broadcom n’est pas la demande d’IA, qui accélère : c’est sa concentration. Un distributeur a pesé 50 % des revenus du trimestre, cinq clients finaux environ 55 %, et la croissance de l’IA dépend de quelques programmes de puces. Tant qu’ils avancent, tout se tient ; un décalage chez un seul client se lirait dans un trimestre entier.',
        riskCards: [
          { title: 'Clients finaux concentrés', severity: 'high', icon: 'fa-user-tie', points: ['Un distributeur non nommé à 50 % des revenus du trimestre, 46 % sur neuf mois.', 'Cinq clients finaux à environ 55 % ; un client à 44 % des créances fin 2025.'], verdict: 'Tout signal de ralentissement des commandes d’un grand cloud pèsera sur le titre avant d’apparaître dans les comptes.' },
          { title: 'Puces maison des clients', severity: 'medium', icon: 'fa-microchip', points: ['Les clouds conçoivent de plus en plus leurs accélérateurs en interne.', 'Le passage d’une génération de puce à l’autre peut changer de fournisseur.'], verdict: 'La part de Broadcom se joue à chaque nouvelle génération de puce, pas une fois pour toutes.' },
          { title: 'Tendance du titre', severity: 'medium', icon: 'fa-chart-line', points: ['Cours sous ses trois moyennes de référence.', 'Retard de performance sur SMH et SOXX sur vingt et une séances.'], verdict: 'Tant que le titre reste sous sa moyenne à cinquante séances, les rebonds restent des rebonds dans une tendance baissière.' },
          { title: 'Taux et valorisation', severity: 'medium', icon: 'fa-percent', points: ['Taux à 10 ans au plus haut depuis 2007.', 'Multiple d’EBITDA élevé et dette de 59,4 Md$.'], verdict: 'La hausse des taux peut comprimer le multiple même si les résultats restent bons.' }],
        pedagogy: 'Le titre a baissé le lendemain de la publication d’un trimestre record : acheter une bonne nouvelle déjà connue, c’est souvent payer le haut de la réaction. Un gap à l’ouverture, c’est le cours qui saute un niveau d’une séance à l’autre : il peut dépasser le plafond et annuler l’achat. Le slippage, l’écart entre le prix voulu et le prix obtenu, reste faible sur une valeur aussi liquide. Dimensionner la position à partir de la distance au stop et d’un budget de perte fixé d’avance, jamais à partir de l’objectif. Ne pas anticiper le déclencheur : attendre la clôture.' },
      tradeIdea: { status: 'watch', statusNote: 'Surveiller. Avant activation : aucune entrée ; une clôture sous ' + usd(abandon) + ' abandonne le scénario. Activation : clôture au-dessus de ' + usd(entry) + ', puis achat à l’ouverture suivante seulement sous ' + usd(cap) + '. Après activation : stop sous ' + usd(stop) + '. L’ancien plan d’attente du 30 août n’a jamais été activé.',
        entry, stop, tp1, tp2,
        stopPct: pct(stop, entry).toFixed(1) + '%', tp1Pct: '+' + pct(tp1, entry).toFixed(1) + '%', tp2Pct: '+' + pct(tp2, entry).toFixed(1) + '%',
        rr: '1:' + rr1.toFixed(2) + ' TP1 / 1:' + rr2.toFixed(2) + ' TP2',
        entryNote: 'Déclencheur sur clôture au-dessus du plus haut du 28 août, pas sur un franchissement en séance. Entrée à l’ouverture suivante uniquement sous ' + usd(cap) + ' : au-delà, le R/R vers TP1 tomberait sous 1,5 avec le même stop. Le plafond n’est qu’à ' + usd(cap - entry) + ' au-dessus du déclencheur : un écart d’ouverture plus large annule l’entrée, il ne se rattrape pas. Sur les ' + gs.total + ' dernières séances, ' + gs.up + ' ouvertures ont dépassé la clôture de la veille de plus de ' + usd(cap - entry) + ' ; l’écart d’ouverture médian, dans un sens ou dans l’autre, vaut ' + usd(gs.medAbs) + '. Environ ' + fr(gs.up / gs.total * 100, 0) + ' % des déclenchements risquent donc de ne pas être achetables. Objectifs : TP1 aux trois quarts de la hauteur du couloir au-dessus du déclencheur, TP2 à sa hauteur entière. Liquidité : environ ' + fr(adv / 1e9, 1) + ' Md$ échangés par séance, médiane des vingt dernières. Exemple de taille, non personnalisé : avec un budget de perte de 100 $, le risque au plafond, ' + usd(cap - stop) + ' par action, donne ' + sizeExample + ' actions.',
        horizon: 'Dix séances après activation',
        thesis: 'Le marché a vendu Broadcom après un trimestre record : il escompte la dépendance à quelques clients finaux et un multiple élevé face à des taux en hausse. Avant activation, le dossier reste en surveillance et une clôture sous ' + usd(abandon) + ' l’abandonne. Une clôture au-dessus de $' + entry.toFixed(2) + ' ramènerait le titre au-dessus de sa moyenne à cinquante séances ; l’entrée n’a lieu qu’à l’ouverture suivante et sous ' + usd(cap) + '. Après activation, le stop sous $' + stop.toFixed(2) + ' limite le risque à une fausse reprise. TP1 à ' + usd(tp1) + ' et TP2 à ' + usd(tp2) + '. Ne pas anticiper le déclencheur, ne pas acheter un gap au-dessus du plafond.',
        catalysts: ['Une clôture au-dessus du plus haut du 28 août, sur un volume au moins égal à la médiane récente.', 'Deux dates dans l’horizon : les résultats de Micron le ' + dfr(c.extra.mu.events[0].report_date) + ' après la clôture, selon deux calendriers de données, et la journée investisseurs de Marvell le 6 octobre ; chacune peut ouvrir un gap.', 'Tout commentaire d’un grand cloud sur ses programmes de puces sur mesure.'],
        invalidation: ['Avant activation : une clôture sous ' + usd(abandon) + ', bas du couloir, abandonne le scénario.', 'Après activation : une clôture sous ' + usd(stop) + ' invalide le trade.', 'Ouverture au-dessus de ' + usd(cap) + ' après la clôture de déclenchement : pas d’achat, le R/R deviendrait insuffisant.', 'Une annonce de perte ou de report d’un programme de puces d’un grand client annule la thèse avant activation.'] },
      globalScore: { profile: 'Croissance d’IA record, concentrée sur peu de clients',
        keyTakeawaysPositive: ['Revenus d’IA triplés en un an, prévision encore en hausse.', 'Flux de trésorerie libre proche de la moitié des revenus.', 'Pas d’émission d’actions pour financer la croissance.'],
        keyTakeawaysNegative: ['Un distributeur à 50 % des revenus du trimestre.', 'Titre sous ses moyennes, en retard sur les semi-conducteurs.', 'Multiple élevé face à des taux au plus haut depuis 2007.'],
        mindsetTip: 'Quand un résultat record fait baisser le cours, la question n’est plus « la société va-t-elle bien ? » mais « qu’est-ce que le prix supposait déjà ? ».' },
      social: { platforms: [], sourceRefs: [market('sentiment non retenu faute de mesure qualifiée')] },
      disclaimer: 'Document de recherche éducatif. Ni conseil financier, ni signal de trading. Statut surveiller : aucun ordre actif.',
    };
  },
  groups: [
    { name: 'Grands clients de puces sur mesure', order: 1, transmission: 'Leur capex et leurs programmes de puces maison fixent la demande de Broadcom.', rows: [
      ['GOOGL', 'leader', 'Cloud et puces d’IA dessinées sur mesure', 'Ses générations d’accélérateurs maison passent en partie par Broadcom ; un changement de fournisseur toucherait directement le chiffre d’affaires.'],
      ['META', 'leader', 'Grand acheteur de calcul pour ses modèles', 'Ses accélérateurs sur mesure et son capex déterminent une partie de la demande de puces et de réseau.'],
      ['MSFT', 'leader', 'Premier acheteur de calcul et cloud Azure', 'Son capex et ses puces maison arbitrent entre GPU, puces sur mesure et réseau Ethernet.'],
      ['AMZN', 'leader', 'Premier cloud public et puces maison', 'Ses propres accélérateurs concurrencent les puces sur mesure ; ses commandes réseau restent une source de revenus.']] },
    { name: 'Pairs directs', order: 1, transmission: 'Accélérateurs concurrents et puces réseau : ils se disputent le même budget de calcul.', rows: [
      ['NVDA', 'direct_peer', 'Processeurs graphiques et réseau', 'Principal concurrent des puces sur mesure : sa part de GPU mesure l’espace laissé à Broadcom.'],
      ['AMD', 'direct_peer', 'Seconde source de GPU', 'Ses gains chez les grands clouds réduisent la part disponible pour les accélérateurs sur mesure.'],
      ['MRVL', 'direct_peer', 'Puces sur mesure et optique', 'Seul concurrent direct sur les puces sur mesure ; sa croissance signale la diversification des clouds.'],
      ['QCOM', 'direct_peer', 'Puces mobiles et centres de données', 'Concurrent sur le Wi-Fi et la connectivité, candidat aux accélérateurs d’inférence.']] },
    { name: 'Amont : fonderie et assemblage', order: 1, transmission: 'Broadcom conçoit ; ces fournisseurs fabriquent et limitent le volume livrable.', rows: [
      ['TSM', 'upstream', 'Fondeur des puces de Broadcom', 'Sa capacité en gravure avancée et en assemblage fixe le rythme des livraisons de puces sur mesure.'],
      ['AMKR', 'upstream', 'Assemblage et test de puces', 'L’assemblage avancé est un goulot : ses délais conditionnent les livraisons.'],
      ['KLAC', 'upstream', 'Contrôle de procédé des fondeurs', 'Ses ventes suivent les investissements des fondeurs pour produire les puces avancées.'],
      ['LRCX', 'upstream', 'Équipement de gravure et de dépôt', 'Ses commandes précèdent la capacité disponible chez les fondeurs.']] },
    { name: 'Aval : serveurs et réseau des centres de données', order: 2, transmission: 'Ils intègrent les puces réseau et les accélérateurs de Broadcom dans les centres de données.', rows: [
      ['ANET', 'downstream', 'Commutateurs Ethernet des clusters d’IA', 'Utilise les puces de commutation de Broadcom : ses commandes précèdent celles de Broadcom en réseau.'],
      ['CSCO', 'downstream', 'Réseau d’entreprise et de centres de données', 'Concurrent et client sur le réseau ; ses commandes signalent l’investissement des entreprises.'],
      ['DELL', 'downstream', 'Intégrateur de serveurs d’IA', 'Son carnet de serveurs d’IA reflète la demande hors grands clouds.'],
      ['SMCI', 'downstream', 'Intégrateur de serveurs d’IA', 'Assemble des baies pour les clouds et néo-clouds ; ses marges disent si le matériel reste rare.'],
      ['ORCL', 'downstream', 'Cloud d’infrastructure pour l’IA', 'Acheteur de capacité de calcul ; son financement illustre le coût de la demande.']] },
    { name: 'Second ordre : optique et énergie', order: 2, transmission: 'Contraintes physiques de la mise en service des clusters.', rows: [
      ['CIEN', 'second_order', 'Réseau optique longue distance', 'Les liaisons entre centres de données suivent le nombre de clusters construits.'],
      ['COHR', 'second_order', 'Optique des centres de données', 'Les interconnexions optiques suivent le nombre de baies installées.'],
      ['VRT', 'second_order', 'Alimentation et refroidissement', 'Ses délais de livraison fixent le calendrier de mise en service.']] },
    { name: 'Contrôles sectoriels', order: 2, transmission: 'Paniers de référence pour isoler ce qui est propre à Broadcom.', rows: [
      ['SMH', 'sector_proxy', 'Panier de semi-conducteurs', 'Broadcom y pèse lourd : un écart de performance avec ce panier isole ce qui est propre au titre.'],
      ['SOXX', 'sector_proxy', 'Panier de semi-conducteurs moins concentré', 'Moins pondéré sur les géants : il montre si le secteur monte sans Broadcom.'],
      ['QQQ', 'sector_proxy', 'Grandes valeurs du Nasdaq', 'Contrôle large de la technologie : un mouvement commun n’a rien de spécifique.']] },
  ],
  eventDefault: { leader: 'Aucune publication dans les quatorze jours collectés ; ses annonces de capex restent le signal à suivre', direct_peer: 'Aucune publication dans les quatorze jours collectés ; ses annonces de produits peuvent déplacer les parts de marché', upstream: 'Aucune publication dans les quatorze jours collectés ; ses commentaires de capacité précèdent les livraisons', downstream: 'Aucune publication dans les quatorze jours collectés ; ses commandes de réseau et de serveurs sont le signal à suivre', second_order: 'Aucune publication dans les quatorze jours collectés ; ses délais d’équipement fixent les mises en service', sector_proxy: 'Panier sans publication propre ; exposé aux résultats de ses grandes pondérations' },
  eventRisk: {
    GOOGL: 'Aucune publication dans les quatorze jours collectés ; toute annonce de puce maison change la part de Broadcom',
    META: 'Aucune publication dans les quatorze jours collectés ; une révision de capex changerait la demande de puces',
    MSFT: 'Aucune publication dans les quatorze jours collectés ; ses commentaires sur Azure restent le signal à suivre',
    AMZN: 'Aucune publication dans les quatorze jours collectés ; ses accélérateurs maison arbitrent la demande',
    NVDA: 'Aucune publication dans les quatorze jours collectés ; ses lancements de plateformes fixent la barre concurrentielle',
    AMD: 'Aucune publication dans les quatorze jours collectés ; ses contrats avec les clouds pèsent sur les parts',
    MRVL: 'Journée investisseurs le 6 octobre selon son communiqué du 27 août ; elle peut rebattre les cartes du sur-mesure',
    QCOM: 'Aucune publication dans les quatorze jours collectés ; ses ambitions en centres de données restent à prouver',
    TSM: 'Aucune publication dans les quatorze jours collectés ; ses ventes mensuelles donnent un indicateur avancé',
    AMKR: 'Aucune publication dans les quatorze jours collectés ; ses délais d’assemblage avancé sont un goulot à suivre',
    KLAC: 'Aucune publication dans les quatorze jours collectés ; ses commandes suivent le capex des fondeurs',
    LRCX: 'Aucune publication dans les quatorze jours collectés ; ses commandes précèdent la capacité',
    ANET: 'Aucune publication dans les quatorze jours collectés ; ses commandes de commutateurs précèdent celles de Broadcom',
    CSCO: 'Aucune publication dans les quatorze jours collectés ; ses commandes d’entreprise mesurent l’investissement hors cloud',
    DELL: 'Aucune publication dans les quatorze jours collectés ; son carnet de serveurs d’IA est le signal à suivre',
    SMCI: 'Aucune publication dans les quatorze jours collectés ; ses marges sur serveurs disent si le matériel reste rare',
    ORCL: 'Aucune publication dans les quatorze jours collectés ; ses dépôts de financement éclairent le coût de la demande',
    CIEN: 'Aucune publication dans les quatorze jours collectés ; ses commandes optiques suivent les liaisons entre sites',
    COHR: 'Aucune publication dans les quatorze jours collectés ; ses volumes optiques suivent les installations',
    VRT: 'Aucune publication dans les quatorze jours collectés ; son carnet mesure la file d’attente des sites',
    SMH: 'Panier sans publication propre ; exposé aux résultats de ses grandes pondérations',
    SOXX: 'Panier sans publication propre ; plus sensible aux valeurs moyennes du secteur',
    QQQ: 'Panier sans publication propre ; dominé par les grandes pondérations technologiques' },
  blastDoc: 2,
  scenarios: c => [
    { scenario: 'bullish', trigger: 'Les programmes de puces sur mesure tiennent leur calendrier et la prévision de 34,8 Md$ est dépassée.', firstOrder: 'Le titre repasse au-dessus de sa moyenne à cinquante séances et sort de son couloir par le haut.', secondOrder: 'La fonderie, l’assemblage et le réseau Ethernet gardent leur carnet ; ANET suit.', confirmation: 'Une clôture au-dessus du plus haut du 28 août, avec SMH et ANET qui confirment dans la même séance.', contradiction: 'Un grand cloud qui annonce l’internalisation complète de sa prochaine puce.' },
    { scenario: 'mixed', trigger: 'Les résultats tiennent mais la hausse des taux comprime les multiples de croissance.', firstOrder: 'Le titre reste dans son couloir pendant que les autres semi-conducteurs progressent.', secondOrder: 'L’écart de performance avec SMH et SOXX continue de se creuser.', confirmation: 'Un titre bloqué sous 376 $ pendant que les paniers de semi-conducteurs montent.', contradiction: 'Une détente des taux longs qui relancerait les valeurs de croissance.' },
    { scenario: 'bearish', trigger: 'Un grand client final décale un programme ou un concurrent remporte une génération de puce.', firstOrder: 'La prévision du trimestre suivant déçoit et le multiple se comprime.', secondOrder: 'Les fournisseurs d’assemblage et les intégrateurs révisent leurs volumes.', confirmation: 'Une clôture sous le bas du 16 septembre et un recul des commandes réseau.', contradiction: 'Une prévision relevée malgré le décalage d’un programme.' }],
  contradictions: c => ['Les résultats sont records mais le titre fait moins bien que les paniers de semi-conducteurs sur vingt et une séances : la corrélation avec le secteur n’explique pas l’écart.', 'Une corrélation élevée avec un fournisseur ou un client ne prouve pas un lien commercial ; le client dominant n’est pas nommé.'],
  missingData: c => ['Ni le distributeur à 50 % des revenus du trimestre ni les cinq premiers clients finaux ne sont nommés : aucun client coté n’entre dans les comparables comme client documenté.', 'Chaîne d’options relevée marché fermé, inexploitable ; sentiment et tendances de recherche non retenus.', 'Barres d’une source de repli pour toutes les séries : la source principale présentait des séances manquantes sur plusieurs valeurs.'],
  limitations: ['Barres d’une source de repli (Webull).', 'Options inexploitables, marché fermé.', 'Clients finaux non nommés.'],
});
