'use strict';
// Dossier DDOG v3 au close du 2026-09-23 (lot R03). Contenu éditorial et niveaux propres au titre ;
// calculs, provenance et preuves délégués au gabarit commun tools/lib/analysis-v3-r03.cjs.
const R = require('../../../../tools/lib/analysis-v3-r03.cjs');
const GEN = 'analyses/DDOG/_runs/20260924/build-ddog.cjs';

R.build({
  ticker: 'DDOG', shortName: 'Datadog', cik: 1561550, generator: GEN, mode: 'breakout',
  xbrl: { ttm: { rev: ['RevenueFromContractWithCustomerExcludingAssessedTax'], ebit: ['OperatingIncomeLoss'], ni: ['NetIncomeLoss'], da: ['DepreciationAndAmortization', 'DepreciationDepletionAndAmortization'], ocf: ['NetCashProvidedByUsedInOperatingActivities'] },
    instant: { notes: ['ConvertibleLongTermNotesPayable'], cashEq: ['CashAndCashEquivalentsAtCarryingValue'], mkt: ['AvailableForSaleSecuritiesDebtSecuritiesCurrent'] }, da: ['da'], debt: ['notes'], cash: ['cashEq', 'mkt'] },
  scenarioBasis: 'revenue', scenarioMultiple: 12,
  valuationBasis: 'GAAP douze mois au 2026-06-30 (XBRL SEC) ; obligations 2029 à leur valeur comptable dans la dette ; trésorerie = liquidités et titres négociables ; actions de classe A et B au 31 juillet ; multiple de douze fois les revenus = hypothèse éditoriale',
  levels: { trigger: { d: '2026-08-10', c: 2 }, stop: { d: '2026-09-23', c: 3 }, abandon: { d: '2026-09-18', c: 3 },
    s1: { d: '2026-09-22', c: 3 }, r1: { d: '2026-09-23', c: 2 }, r2: { d: '2026-08-14', c: 2 }, r3: { d: '2026-08-05', c: 2 } },
  supports: ['stop', 's1', 'abandon'], resistances: ['r1', 'r2', 'trigger'],
  targets: ({ lv, entry, abandon }) => { const range = entry - abandon; return { tp1: lv('r3'), tp2: entry + range, range }; },
  levelsMethod: 'Déclencheur = plus haut du 10 août, sommet de la base formée après le gap du 6 août ; bas de la base = plus bas du 18 septembre ; stop = plus bas du 23 septembre ; TP1 = plus haut du 5 août, sommet de l’année, au-dessus du gap du 6 août ; TP2 = déclencheur + hauteur de la base ; plafond = (TP1 + 1,5 × stop) / 2,5 arrondi au cent inférieur ; pourcentages depuis l’entrée ; R/R = gain / risque.',
  inventory: 19,
  reviewScope: 'Dépôts EDGAR de Datadog du 1er janvier au 23 septembre 2026 (19 formulaires hors formulaires 3, 4, 5 et 144), dont le 10-K de l’exercice 2025. Les 8-K de gouvernance (items 5.02, 5.07), les procurations, le rapport annuel illustré et les déclarations 13G sont écartés comme non décisionnels ; le 10-Q et le communiqué du premier trimestre sont couverts par ceux du deuxième. Le 8-K du 22 avril (items 3.03 et 5.03) et la demande 40-APP du 13 août sont ouverts : ils changent le cadre juridique, pas le capital.',
  docs: [
    ['2026-08-06', '8-K / Exhibit 99.1', '0001628280-26-053829', 'ex-991x20260630x8k.htm', 'q2-8k__ex-991x20260630x8k.htm',
      'Communiqué du deuxième trimestre, publié avant l’ouverture : revenus de 1,12 Md$ (+36 %), résultat opérationnel GAAP de 5 M$, flux libre de 279 M$. Prévision de 1,135 à 1,145 Md$ au troisième trimestre et de 4,45 à 4,47 Md$ sur l’année.'],
    ['2026-08-06', '10-Q', '0001628280-26-054458', 'ddog-20260630.htm', 'q2-10q__ddog-20260630.htm',
      'Rapport trimestriel au 30 juin 2026 : baisse d’usage du premier client, non nommé, depuis le début du troisième trimestre, qui peut ralentir la croissance ; la cohorte des clients natifs de l’IA a apporté un gain de croissance « à un chiffre élevé ». 359,1 millions d’actions A et B au 31 juillet ; obligations 2029 de 1,0 Md$ convertibles à 217,60 $.'],
    ['2026-02-18', '10-K', '0001628280-26-008819', 'ddog-20251231.htm', 'fy25-10k__ddog-20251231.htm',
      'Rapport annuel 2025 : la cohorte des clients natifs de l’IA, qui inclut le premier client, a représenté environ sept points de la croissance du quatrième trimestre 2025 ; les grands clouds sont cités comme concurrents en supervision du cloud.'],
    ['2026-04-22', '8-K', '0001193125-26-168261', 'd81305d8k.htm', 'apr22-8k__d81305d8k.htm',
      'Transfert du siège juridique du Delaware au Nevada, approuvé par 332 195 858 voix contre 199 605 477, les actions B portant dix voix : aucun effet sur le nombre d’actions.'],
    ['2026-08-13', '40-APP', '0000947871-26-000790', 'ss6680462_40app.htm', 'aug13-40app__ss6680462_40app.htm',
      'Demande à la SEC de déclarer que Datadog n’est pas une société d’investissement : ses placements financiers dépassent 40 % de ses actifs hors titres d’État et liquidités. Démarche juridique, sans effet sur l’activité ni sur le capital.'],
  ],
  needles: {
    customer: [1, ['we saw a reduction in usage from our largest customer starting in the third quarter of 2026', 'which may cause a deceleration in revenue growth', 'our AI-native cohort, which cohort includes our largest customer, contributed high single digit percentage points', 'low-120%']],
    capital: [1, ['334,904,614 shares of the registrant’s Class A common stock and 24,170,410 shares', '4.5955 shares of Class A common stock per $1,000 principal amount', 'approximately $ 217.60 per share', 'Initial cap price per share, subject to certain adjustments $ 322.38', 'Convertible senior notes, net, non-current 985,545', '24,518,658 and 24,408,190 shares issued and outstanding', 'Marketable securities 4,550,481', 'delivered $ 634.1 million in cash and issued 1,354,569 shares', 'issued $ 1.0 billion aggregate principal amount of 0.00 % Convertible Senior Notes due 2029']],
    q2: [0, ['Revenue was $1.12 billion, an increase of 36% year-over-year', 'GAAP operating income was $5 million', 'non-GAAP operating margin was 23%', 'free cash flow of $279 million', 'Revenue between $1.135 billion and $1.145 billion', 'Revenue between $4.45 billion and $4.47 billion', 'assuming approximately 376 million weighted average diluted shares outstanding', 'about 4,720 customers with ARR of $100,000 or more', 'August 6, 2026 a t 8:00 A.M. Eastern Time']],
    annual: [2, ['with respect to Cloud monitoring, we compete with native solutions from cloud providers such as Amazon Web Services', 'represented approximately seven percentage points of our year-over-year revenue growth for the quarter ended December 31, 2025']],
    nevada: [3, ['approved the proposal to redomicile the Company from the State of Delaware to the State of Nevada by conversion', '332,195,858 199,605,477 351,779']],
    ica: [4, ['the value of the Company’s investment securities exceeds 40% of the value of its total assets']],
  },
  sectionDocs: { verdict: [1, 0], business: [0, 1, 2], news: [0, 1], earnings: [0], capitalStructure: [1, 3], filingsReview: [1, 0, 3, 4], risks: [1, 2], globalScore: [0], meta: [0], disclaimer: [0], macro: [0], options: [0], social: [0], header: [1] },
  score: { business: 24, technical: 4, capital: 2, calendar: 0, dilution: -1, risk: 28 },
  peers: true,
  shares: { value: 334904614 + 24170410, doc: 1 },
  route: (p, { prov, dep, B }) => /^news\.[01]\./.test(p) ? prov('bars', B, 'Ouverture et clôture lues sur les barres certifiées ; écart d’ouverture = ouverture / clôture de la veille − 1 ; comparaison avec IGV et Dynatrace sur la même séance.', [dep('comparison', '')]) : null,
  riskScoreReason: 'Jugement qualitatif sur dix : dépendance à un premier client qui réduit son usage, valorisation élevée et fenêtre d’entrée étroite.',
  compose: c => {
    const { fr, usd, pct, sgn, close, prev, bars, N, tech, st, M, adv, ret, G$, g, marketCap, ev, scn, lv, entry, stop, tp1, tp2, abandon, cap, rr1, rr2, riskAtr, sizeExample, ref, market, docs, raw, peerStat, shares } = c;
    const gs = c.gapStats(cap - entry), bufAtr = (cap - entry) / tech.atr14, blocked = gs.up / gs.total * 100;
    const bufPct = (cap / entry - 1) * 100, bk = c.breakoutStats(bufPct);
    // Repli borné, rejoué séance par séance sur les cassures non achetables à l'ouverture : ordre annulé si une séance
    // ouvre sous le stop, exécuté à l'ouverture si elle est sous le plafond, sinon si le plus bas l'atteint ; annulé
    // après une clôture sous le niveau cassé ; trois séances au plus.
    const rt = (() => { const pb = bufPct / 100, ps = 1 - stop / entry, k = 3; let miss = 0, back = 0, stopSame = 0;
      for (let i = 21; i < N - k; i++) { let lvl = -Infinity; for (let j = i - 20; j < i; j++) lvl = Math.max(lvl, bars[j][2]);
        if (!(bars[i][4] > lvl && bars[i - 1][4] <= lvl)) continue; const lim = lvl * (1 + pb), sl = lvl * (1 - ps);
        if (bars[i][4] <= lim && bars[i + 1][1] <= lim) continue; miss++;
        for (let q = i + 1; q <= i + k; q++) { const [, o, , l, cl] = bars[q];
          if (o < sl) break;
          if (o <= lim || l <= lim) { back++; if (l <= sl) stopSame++; break; }
          if (cl < lvl) break; } }
      return { miss, back, stopSame, k }; })();
    const aAgainst = 199605477 / (332195858 - 245186580 + 199605477 + 351779) * 100;
    const evRev = ev / G$.rev, evFwd = ev / 4.46e9, dil = 376e6, evDil = close * dil + G$.debt - G$.cash;
    const snow = peerStat('SNOW', 'enterpriseToRevenue'), dt = peerStat('DT', 'enterpriseToRevenue'), mdb = peerStat('MDB', 'enterpriseToRevenue');
    const bar = d => bars.find(b => b[0] === d), prevOf = d => bars[bars.findIndex(b => b[0] === d) - 1];
    const d0806 = bar('2026-08-06'), p0806 = prevOf('2026-08-06'), gapTop = p0806[4], rrGap = (gapTop - entry) / (entry - stop), rrGapCap = (gapTop - cap) / (cap - stop), low0908 = bar('2026-09-02');
    const igv21 = M.IGV.return21d, own21 = ret(21);
    return {
      meta: { lang: 'fr', dir: 'ltr', level: 'intermediate', tags: ['us', 'equities', 'ai-chain', 'software', 'technology'], grade: 'B-', date: '2026-09-24', dateDisplay: '24 septembre 2026', version: 3, status: 'watch', assetType: 'stock', levelsCloseDate: c.REF,
        description: 'Datadog : une croissance de 36 %, un premier client qui réduit son usage et un gap du 6 août encore ouvert. Dossier au close du 23 septembre 2026, statut surveiller.',
        ogDescription: 'Datadog : revenus +36 %, baisse d’usage du premier client depuis juillet, titre revenu à 251 $ sous le gap du 6 août ; niveaux à surveiller.',
        lastMcpRefresh: raw.status.captured_at, levelsVerifiedAt: raw.status.captured_at,
        lastEvent: c.archive.meta.lastEvent, statusHistory: [...c.archive.meta.statusHistory, { at: raw.status.captured_at, from: 'expired', to: 'watch', note: 'refonte v3 du 24 septembre : nouveau scénario, clôture de référence du 2026-09-23', close }] },
      header: { ticker: 'DDOG', name: 'Datadog, Inc.', exchange: 'NASDAQ', sector: 'Observabilité et sécurité des infrastructures cloud', price: close, changePct: pct(close, prev),
        badges: [{ text: 'SURVEILLER — ACTIVATION AU-DESSUS DU 10 AOÛT', color: 'blue' }, { text: 'Chaîne IA — supervision des charges d’IA', color: 'purple' }],
        metrics: { marketCap: fr(marketCap / 1e9, 1) + ' Md$', volume: fr(bars[N][5] / 1e6, 2) + ' M', evRevenue: fr(evRev, 1) + '×' }, halalStatus: 'unknown' },
      verdict: { score: 57, conviction: 'Moderate', bias: 'Neutral',
        confidence: 'Score éditorial non prédictif. Les chiffres d’entreprise viennent des dépôts SEC et des données XBRL officielles ; les niveaux, du close certifié du 23 septembre.',
        summary: 'Datadog a publié le 6 août un trimestre à 1,12 Md$ de revenus, en hausse de 36 %. Le même jour, son 10-Q signalait une baisse d’usage de son premier client, non nommé, depuis le début du troisième trimestre, « qui peut ralentir la croissance ». Le titre a ouvert ' + fr(Math.abs(pct(d0806[1], p0806[4])), 1) + ' % sous la veille et n’a jamais refermé ce gap. Il est remonté depuis de ' + usd(low0908[4]) + ' le 2 septembre à ' + usd(close) + ', sans dépasser le haut de sa base d’août. À ' + fr(evRev, 1) + ' fois les revenus des douze derniers mois, il se paie au niveau de Snowflake (' + fr(snow, 1) + '×) et bien au-dessus de MongoDB (' + fr(mdb, 1) + '×) et de Dynatrace (' + fr(dt, 1) + '×). Signal utile : une clôture au-dessus de ' + usd(entry) + ', le plus haut du 10 août. L’entrée resterait étroite : le plafond d’achat n’est qu’à ' + usd(cap - entry) + ' au-dessus.',
        whyBuy: [
          'Revenus du deuxième trimestre de 1,12 Md$, en hausse de 36 %, et flux libre de 279 M$.',
          'Environ 4 720 clients à plus de 100 000 $ de revenus annuels récurrents, contre environ 3 850 un an plus tôt.',
          'Rétention nette en dollars dans le bas de la fourchette de 120 % : les clients existants dépensent plus.',
          'Liquidités et titres négociables de ' + fr(G$.cash / 1e9, 2) + ' Md$ au 30 juin, contre ' + fr(G$.debt / 1e9, 2) + ' Md$ d’obligations convertibles.'],
        whyAvoid: [
          'Le premier client, non nommé, réduit son usage depuis le début du troisième trimestre ; le 10-Q prévient que cela peut ralentir la croissance.',
          'La prévision du troisième trimestre, 1,135 à 1,145 Md$, n’ajoute que 1 à 2 % au trimestre précédent.',
          'Au close du 23 septembre, la valeur d’entreprise représente ' + fr(evRev, 1) + ' fois les revenus GAAP des douze mois clos le 30 juin.',
          'Le résultat opérationnel GAAP du trimestre n’est que de 5 M$, contre 23 % de marge ajustée : la rémunération en actions absorbe presque tout.'],
        controlChecklist: [
          { label: 'Historique de cours', status: 'pass', statusLabel: 'Trois cents séances continues', evidence: 'Série quotidienne certifiée au close du 23 septembre, source de repli documentée.', action: 'Niveaux et indicateurs recalculés sur cette seule série.' },
          { label: 'Concentration client', status: 'warn', statusLabel: 'Premier client en retrait', evidence: 'Le 10-Q du 6 août signale une baisse d’usage du premier client depuis le troisième trimestre ; sa part des revenus n’est pas publiée et il n’est pas nommé.', action: 'Lire la prochaine publication d’abord sur la croissance hors cohorte IA.' },
          { label: 'Calendrier', status: 'pass', statusLabel: 'Aucune publication dans l’horizon', evidence: 'Aucune date de résultats de Datadog ni d’un comparable dans les quatorze jours du calendrier collecté ; la date du troisième trimestre n’est pas annoncée.', action: 'Vérifier la date avant toute prolongation de l’horizon.' }] },
      business: { theme: 'Supervision des infrastructures cloud, des applications et des charges d’IA',
        overview: '<p>Datadog vend un tableau de bord unique pour surveiller serveurs, applications, journaux et sécurité dans le cloud, facturé à l’usage. Au deuxième trimestre 2026, les revenus ont atteint 1,12 Md$, en hausse de 36 %, et environ 4 720 clients dépensaient plus de 100 000 $ par an. La marge opérationnelle ajustée est de 23 %, mais le résultat GAAP reste presque nul, à 5 M$, une fois la rémunération en actions comptée.</p><p>La croissance récente repose en partie sur une petite cohorte de clients natifs de l’IA, qui inclut le premier client. Le 10-K rapportait qu’elle avait apporté environ sept points de croissance au quatrième trimestre 2025 ; le 10-Q de juin parle d’un apport « à un chiffre élevé ». Le même document signale que ce premier client réduit son usage depuis le début du troisième trimestre. Son nom et sa part des revenus ne sont pas publiés.</p><p>Deux dépôts de 2026 changent le cadre sans toucher au capital : le transfert du siège juridique au Nevada, voté en avril par 332,2 millions de voix contre 199,6 millions, les actions B portant dix voix, et une demande auprès de la SEC pour ne pas être classée société d’investissement, ses placements de trésorerie dépassant 40 % de ses actifs hors titres d’État.</p>',
        moat: 'L’avantage tient à l’étendue de la plateforme : une fois les agents installés, chaque nouveau produit se vend au même client sans nouvelle intégration. Il est fort face aux spécialistes, plus discutable face aux outils natifs des grands clouds, que le 10-K cite comme concurrents, et face à des clients qui optimisent leur facture.',
        segments: [
          { name: 'Infrastructure et applications', revenue: 'Majorité des revenus', pct: 'Non ventilé', description: 'Supervision des serveurs, conteneurs et applications.' },
          { name: 'Journaux, sécurité et IA', revenue: 'Part croissante', pct: 'Non ventilé', description: 'Gestion des journaux, sécurité du cloud, supervision des modèles.' }],
        sourceRefs: [ref(0), ref(1), ref(2)],
        coverageMatrix: [
          { facet: 'Cours et historique', status: 'COUVERT', decision: 'Trois cents séances continues, close certifié ; base des niveaux et des indicateurs.' },
          { facet: 'Résultats et guidance', status: 'COUVERT — PRIMAIRE', decision: 'Communiqué et 10-Q du 6 août ; date du troisième trimestre non annoncée.' },
          { facet: 'Capital et dette', status: 'COUVERT — PRIMAIRE', decision: 'Obligations 2029, options plafonnées et deux classes d’actions séparées.' },
          { facet: 'Agrégats GAAP', status: 'COUVERT — XBRL', decision: 'Douze mois glissants au 30 juin 2026, reconstitués depuis les données XBRL officielles.' },
          { facet: 'Comparables et transmission', status: 'COUVERT — LOCAL', decision: 'Corrélations recalculées sur barres certifiées depuis la fin mars.' },
          { facet: 'Initiés', status: 'PARTIEL', decision: 'Couverture officielle incomplète ; aucun solde net affirmé.' },
          { facet: 'Options', status: 'NON EXPLOITABLE', decision: 'Chaîne relevée en séance le 24 septembre, non rattachée à la clôture de référence.' }] },
      news: [
        { date: '2026-08-06', title: 'Gap de ' + fr(pct(d0806[1], p0806[4]), 1) + ' % le jour du communiqué', impact: 'negative', detail: 'Le communiqué est publié avant l’ouverture, la conférence ayant lieu à 8 h, heure de New York. Le titre ouvre à ' + usd(d0806[1]) + ', ' + fr(Math.abs(pct(d0806[1], p0806[4])), 2) + ' % sous la clôture de la veille, ' + usd(p0806[4]) + ', et clôture à ' + usd(d0806[4]) + ' (' + fr(pct(d0806[4], p0806[4]), 2) + ' %). IGV a perdu 1,87 % et Dynatrace 3,91 % : environ ' + fr(Math.abs(pct(d0806[4], p0806[4])) - 1.87, 0) + ' points de la baisse sont propres au titre.', source: 'Barres certifiées', sourceUrl: c.evidenceUrl },
        { date: '2026-09-02', title: 'Point bas à ' + fr(low0908[4], 2) + ' $, puis rebond', impact: 'positive', detail: 'Clôture la plus basse depuis le gap le 2 septembre ; le titre gagne ensuite ' + sgn(pct(close, low0908[4]), 1) + ' jusqu’au 23. Sur vingt et une séances, il fait ' + sgn(own21, 1) + ' contre ' + sgn(igv21, 1) + ' pour IGV : environ ' + fr(own21 - igv21, 1) + ' points propres au titre.', source: 'Barres certifiées', sourceUrl: c.evidenceUrl },
        { date: '2026-08-13', title: 'Demande pour ne pas être classée société d’investissement', impact: 'neutral', detail: 'Les placements de trésorerie dépassent 40 % des actifs hors titres d’État : démarche juridique, sans effet sur l’activité.', source: 'Datadog — SEC', sourceUrl: docs[4].url }],
      fundamentals: { rows: [
          { metric: 'Revenus du deuxième trimestre', value: '1,12 Md$', signal: '+36 % sur un an, communiqué du 6 août', signalColor: 'green', _src: 0 },
          { metric: 'Prévision du troisième trimestre', value: '1,135 à 1,145 Md$', signal: 'Soit 1 à 2 % de plus qu’au deuxième trimestre', signalColor: 'amber', _src: 0 },
          { metric: 'Prévision de revenus 2026', value: '4,45 à 4,47 Md$', signal: 'Sur environ 376 millions d’actions diluées', signalColor: 'blue', _src: 0 },
          { metric: 'Flux libre du deuxième trimestre', value: '279 M$', signal: 'Flux opérationnel de 316 M$', signalColor: 'green', _src: 0 },
          { metric: 'Clients à plus de 100 000 $ par an', value: 'Environ 4 720', signal: 'Contre environ 3 850 un an plus tôt', signalColor: 'green', _src: 0 },
          { metric: 'Revenus GAAP sur douze mois', value: fr(G$.rev / 1e9, 2) + ' Md$', signal: 'Douze mois glissants au 30 juin 2026 (XBRL SEC)', signalColor: 'blue', _src: 'gaap' },
          { metric: 'Résultat opérationnel GAAP sur douze mois', value: fr(G$.ebit / 1e6, 1) + ' M$', signal: 'Douze mois glissants au 30 juin 2026', signalColor: G$.ebit > 0 ? 'amber' : 'red', _src: 'gaap' },
          { metric: 'Résultat net GAAP sur douze mois', value: fr(G$.ni / 1e6, 1) + ' M$', signal: 'Douze mois glissants au 30 juin 2026, produits financiers compris', signalColor: 'amber', _src: 'gaap' },
          { metric: 'Flux de trésorerie opérationnel sur douze mois', value: fr(G$.ocf / 1e9, 2) + ' Md$', signal: 'Douze mois glissants au 30 juin 2026', signalColor: 'green', _src: 'gaap' },
          { metric: 'Obligations 2029 au 30 juin 2026', value: fr(G$.debt / 1e6, 1) + ' M$', signal: 'Valeur comptable pour 1,0 Md$ de nominal, incluse dans la valeur d’entreprise', signalColor: 'amber', _src: 'gaap' },
          { metric: 'Liquidités et titres négociables au 30 juin 2026', value: fr(G$.cash / 1e9, 2) + ' Md$', signal: 'Trésorerie et titres négociables à court terme', signalColor: 'blue', _src: 'gaap' },
          { metric: 'EV/revenus GAAP', value: fr(evRev, 1) + '×', signal: 'Valeur d’entreprise au close du 2026-09-23, actions A et B au 31 juillet, sur revenus GAAP douze mois au 2026-06-30', signalColor: 'red', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus Snowflake à ' + fr(snow, 1) + '×, MongoDB à ' + fr(mdb, 1) + '× et Dynatrace à ' + fr(dt, 1) + '× (statistiques courantes du 24 septembre, non point-in-time) : Datadog se paie comme Snowflake, près du double de MongoDB et de Dynatrace.', _src: 'market', _peers: ['SNOW', 'MDB', 'DT'], _peerField: 'enterpriseToRevenue' },
          { metric: 'EV/revenus sur base diluée', value: fr(evDil / G$.rev, 1) + '×', signal: 'Même calcul au close du 2026-09-23 avec les 376 millions d’actions diluées retenues par la guidance 2026', signalColor: 'red', source: 'Clôture certifiée, XBRL SEC et communiqué du 6 août', comparison: 'Versus la base de 359,1 millions d’actions : les attributions salariales et la partie des convertibles dans la monnaie ajoutent environ un point de multiple.', _src: 'market' },
          { metric: 'EV sur revenus prévus pour 2026', value: fr(evFwd, 1) + '×', signal: 'Valeur d’entreprise au close du 2026-09-23 sur le milieu de la prévision de la société (4,46 Md$)', signalColor: 'amber', source: 'Clôture certifiée, XBRL SEC et communiqué du 6 août', comparison: 'Versus le multiple glissant : la prévision suppose que le recul du premier client soit absorbé.', _src: 'market' },
          { metric: 'EV/revenus — scénario de compression (hypothèse éditoriale)', value: fr(scn.price, 2) + ' $ par action', signal: 'Scénario : multiple ramené à douze fois les revenus GAAP douze mois au 2026-06-30 par hypothèse, bilan du 30 juin, soit ' + fr(scn.downside_pct, 0) + ' % sous le close du 2026-09-23', signalColor: 'red', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus MongoDB à ' + fr(mdb, 1) + '× : douze fois correspond à peu près au multiple de ce pair facturé à l’usage ; ce que coûterait un alignement, pas un objectif.', _src: 'market', _peers: ['MDB'], _peerField: 'enterpriseToRevenue' }],
        sourceRefs: [ref(0), ref(1), market('fondamentaux et statistiques')] },
      earnings: { quarters: [],
        beatNote: 'Deuxième trimestre 2026 : revenus de 1,12 Md$ (+36 %), résultat opérationnel GAAP de 5 M$ et marge ajustée de 23 %, bénéfice par action GAAP de 0,12 $ et ajusté de 0,65 $. La guidance vise 1,135 à 1,145 Md$ au troisième trimestre et 4,45 à 4,47 Md$ sur 2026, pour un bénéfice ajusté de 2,50 à 2,54 $ par action. Elle intègre, selon le 10-Q, une baisse d’usage du premier client depuis juillet. La date du troisième trimestre reste non annoncée par la société.',
        nextEarnings: 'Date non annoncée par l’émetteur ; aucune publication dans les quatorze jours du calendrier collecté.',
        sourceRefs: [ref(0), ref(1)] },
      capitalStructure: { sharesOutstanding: '334 904 614 actions A et 24 170 410 actions B au 31 juillet 2026 (page de garde du 10-Q)',
        sharesAuthorized: 'Actions autorisées non reprises : non décisionnel pour ce dossier.', dilutionRisk: 'low',
        shareHistory: 'Base retenue : actions A et B en circulation. Elles passent de 352,5 millions fin 2025 à 359,1 millions au 31 juillet, soit environ 1,9 % de plus en sept mois, par la rémunération en actions et la conversion des obligations 2025, réglées en 634,1 M$ de numéraire et 1 354 569 actions. Passage au nombre dilué : la guidance 2026 retient environ 376 millions d’actions diluées. Les obligations 2029, 1,0 Md$ de nominal, se convertissent à 217,60 $, soit 4,6 millions d’actions potentielles ; au cours du 23 septembre, elles sont dans la monnaie, mais les options plafonnées compensent la dilution jusqu’à 322,38 $. Aucun programme d’émission sur le marché ni de rachat d’actions n’est relevé.',
        warrants: [], atm: { active: false, authorized: 'Aucun programme d’émission d’actions sur le marché relevé', used: 'Sans objet', remaining: 'Sans objet' },
        sourceRefs: [ref(1), ref(3)] },
      filingsReview: { summary: 'Cinq dépôts décisionnels ouverts et hachés. Le point central est une phrase du 10-Q : le premier client réduit son usage depuis juillet. Le reste, siège au Nevada et demande d’exemption auprès de la SEC, change le cadre juridique sans toucher aux comptes ni au capital.',
        filings: docs.map(d => ({ date: d.date, form: d.form, accession: d.accession, finding: d.finding, url: d.url })),
        contrarianRisks: [
          'La part du premier client n’est pas publiée : l’ampleur du ralentissement ne sera connue qu’à la prochaine publication.',
          'Une facturation à l’usage expose à l’optimisation des clients, déjà vécue avec la cohorte des clients natifs du cloud.',
          'Les outils natifs des grands clouds, cités comme concurrents par le 10-K, pèsent sur les prix.',
          'Transfert au Nevada voté par 332,2 millions de voix contre 199,6 millions. Déduction, le détail par classe n’étant pas publié : si les quelque 24,5 millions d’actions B du 30 juin, soit environ 245 millions de voix, ont toutes voté pour, les actions A auraient voté contre à environ ' + fr(aAgainst, 0) + ' %.'] },
      technicals: { rsi14: +tech.rsi14.toFixed(2), macd: +tech.macd.toFixed(2), macdSignal: +tech.macdSignal.toFixed(2), ema20: +tech.ema20.toFixed(2), ema50: +tech.ema50.toFixed(2), ema200: +tech.ema200.toFixed(2),
        ma50Type: 'EMA', ma200Type: 'EMA', ma50Available: true, ma200Available: true, atr14: +tech.atr14.toFixed(2),
        badges: ['Au-dessus des moyennes à vingt, cinquante et deux cents séances', 'Gap du 6 août encore ouvert', 'Plafond d’achat très proche du déclencheur'],
        supports: [stop, lv('s1'), abandon], resistances: [lv('r1'), lv('r2'), entry],
        setupNote: 'Le titre clôture à ' + usd(close) + ', au-dessus de ses moyennes à vingt, cinquante et deux cents séances, dans le gap ouvert le 6 août entre ' + usd(d0806[2]) + ', plus haut du 6, et ' + usd(p0806[3]) + ', plus bas du 5 ; la clôture du 5 août, ' + usd(gapTop) + ', en marque le haut et forme la première résistance au-dessus du déclencheur. Avant activation, aucune entrée ; une clôture sous ' + usd(abandon) + ', le bas du 18 septembre, abandonne le scénario. Activation sur une clôture au-dessus de $' + entry.toFixed(2) + ', le plus haut du 10 août. Après activation, stop sous $' + stop.toFixed(2) + ', le plus bas du 23 septembre, soit ' + fr(riskAtr, 2) + ' ATR sous le déclencheur. Supports : ' + usd(stop) + ', ' + usd(lv('s1')) + ' et ' + usd(abandon) + '. Résistances : ' + usd(lv('r1')) + ', ' + usd(lv('r2')) + ' et ' + usd(entry) + ', puis ' + usd(lv('r3')) + ', plus haut de l’année le 5 août.',
        wyckoff: 'Non utilisé : le profil de volume n’est pas exploité dans ce dossier.',
        sourceRefs: [market('barres quotidiennes et indicateurs recalculés')] },
      options: { callOI: 'Non exploitable', putOI: 'Non exploitable', cpRatio: 'Non exploitable', maxPain: 'Non exploitable', ivMean: 'Non exploitable', skew: 'Chaîne relevée en séance le 24 septembre, non rattachée à la clôture de référence', unusual: 'Aucune activité inhabituelle qualifiée', sourceRefs: [market('options')] },
      shortInterest: { siPct: fr(st.shortPercentOfFloat * 100, 2) + ' % du flottant', daysToCover: fr(st.shortRatio, 2) + ' jours, date de règlement non précisée par le snapshot', ctb: 'Coût d’emprunt non retenu comme signal', trend: 'Positions vendeuses faibles ; aucune thèse de rachat forcé des vendeurs.', squeezeScore: 'Non pertinent', sourceRefs: [market('positions vendeuses')] },
      insiders: { signal: 'Aucune transaction de marché de dirigeant retenue dans la fenêtre relevée. Couverture officielle partielle : l’absence de ligne n’est pas la preuve d’une absence de vente.',
        recentTransactions: [],
        sourceRefs: [market('formulaires 4')] },
      macro: { indicators: [{ name: 'Clôture de référence', value: c.REF, signal: usd(close) + ', séance complète' }, { name: 'Rendement cinq séances', value: sgn(ret(5)), signal: 'Descriptif' }, { name: 'Rendement vingt et une séances', value: sgn(ret(21)), signal: 'Descriptif' }],
        regime: 'neutral', impact: 'Datadog vit des budgets cloud de ses clients : un ralentissement économique se traduit vite en optimisation de l’usage, donc en revenus. Payé plus de vingt fois ses revenus, le titre reste aussi sensible aux taux longs.' },
      risks: { riskScore: 6, riskProfile: 'High',
        riskSummary: 'Le risque de Datadog tient en une phrase du 10-Q : le premier client réduit son usage depuis juillet, et la société ne dit ni qui il est ni combien il pèse. La prochaine publication dira si le reste de la clientèle compense. D’ici là, le titre est payé ' + fr(evRev, 1) + ' fois ses revenus et l’entrée proposée laisse peu de marge : le stop est à ' + fr(riskAtr, 2) + ' ATR du déclencheur.',
        riskCards: [
          { title: 'Premier client en retrait', severity: 'high', icon: 'fa-user-minus', points: ['Baisse d’usage depuis le début du troisième trimestre.', 'Nom et part des revenus non publiés.'], verdict: 'La publication du troisième trimestre mesurera l’impact ; avant, toute position parie sur une inconnue.' },
          { title: 'Valorisation élevée', severity: 'medium', icon: 'fa-scale-unbalanced', points: [fr(evRev, 1) + ' fois les revenus des douze derniers mois.', 'Snowflake à ' + fr(snow, 1) + '×, Dynatrace à ' + fr(dt, 1) + '×.'], verdict: 'Un ralentissement confirmé rapprocherait le multiple de celui des pairs, même avec des comptes solides.' },
          { title: 'Gap du 6 août ouvert', severity: 'medium', icon: 'fa-arrows-up-down', points: ['Ouverture à ' + fr(pct(d0806[1], p0806[4]), 1) + ' % le jour du communiqué.', 'Vendeurs de fin juillet au-dessus du cours.'], verdict: 'Chaque remontée dans la zone du gap rencontre des acheteurs d’avant le 6 août qui veulent sortir.' },
          { title: 'Exécution de l’entrée', severity: 'medium', icon: 'fa-door-closed', points: ['Plafond à ' + usd(cap - entry) + ' au-dessus du déclencheur.', 'Environ ' + fr(blocked, 0) + ' % des ouvertures récentes auraient dépassé cet écart.'], verdict: 'Beaucoup de déclenchements ne seront pas achetables au prix prévu : laisser passer plutôt que payer plus haut.' }],
        pedagogy: 'Le 6 août a montré ce qu’est un gap : le titre a ouvert près de 20 % sous la veille, et aucun stop placé la veille n’a pu être exécuté à son prix. Le slippage, l’écart entre prix voulu et prix obtenu dans une séance normale, reste faible sur environ ' + fr(adv / 1e6, 0) + ' M$ échangés par séance ; c’est le gap de publication qui compte. Dimensionner la position sur la distance au stop, et ne pas la porter jusqu’à la prochaine publication sans l’avoir réduite.' },
      tradeIdea: { status: 'watch', statusNote: 'Surveiller. Avant activation : aucune entrée ; une clôture sous ' + usd(abandon) + ' abandonne le scénario. Activation : clôture au-dessus de ' + usd(entry) + ', puis achat à l’ouverture suivante seulement sous ' + usd(cap) + ', ou par ordre limité à ce plafond pendant trois séances, annulé après une clôture sous ' + usd(entry) + ' et jamais laissé actif sur une ouverture sous ' + usd(stop) + '. Après activation : stop sous ' + usd(stop) + '. L’ancien plan, jamais déclenché, a expiré le 14 septembre.',
        entry, stop, tp1, tp2,
        stopPct: pct(stop, entry).toFixed(1) + '%', tp1Pct: '+' + pct(tp1, entry).toFixed(1) + '%', tp2Pct: '+' + pct(tp2, entry).toFixed(1) + '%',
        rr: '1:' + rr1.toFixed(2) + ' TP1 / 1:' + rr2.toFixed(2) + ' TP2',
        entryNote: 'Déclencheur sur clôture au-dessus du plus haut du 10 août, pas sur un franchissement en séance. Entrée à l’ouverture suivante uniquement sous ' + usd(cap) + ' : au-delà, le R/R vers TP1 tomberait sous 1,5 avec le même stop. Ce plafond est à ' + usd(cap - entry) + ' au-dessus du déclencheur, soit ' + fr(bufAtr, 2) + ' ATR. Mesure : sur les ' + gs.total + ' dernières séances, ' + gs.up + ' ouvertures ont dépassé la clôture de la veille de plus de ' + usd(cap - entry) + ', soit environ ' + fr(blocked, 0) + ' % ; l’écart d’ouverture médian, dans un sens ou dans l’autre, vaut ' + usd(gs.medAbs) + '. Après une clôture de déclenchement au-delà de ' + usd(cap) + ', l’achat n’a lieu que si l’ouverture suivante revient sous ce plafond. Sur la série, ' + bk.n + ' clôtures ont cassé un plus haut de vingt séances : ' + bk.inBand + ' ont fini à moins de ' + fr(bufPct, 2) + ' % au-dessus du niveau cassé, l’écart relatif du plafond, et ' + bk.buyable + ' ont ensuite ouvert sous ce seuil, soit environ ' + fr(bk.buyable / bk.n * 100, 0) + ' % des cassures : l’entrée à l’ouverture reste étroite. Plan de repli : si l’ouverture dépasse le plafond, un ordre à cours limité à ' + usd(cap) + ', valable trois séances, garde le même R/R et le même stop tant que ses bornes tiennent ; sur ' + rt.miss + ' cassures non achetables à l’ouverture, le cours est revenu sous ce seuil dans les trois séances ' + rt.back + ' fois, dont ' + rt.stopSame + ' avec le stop touché la même séance.' + ' Bornes de cet ordre : il est annulé après toute clôture sous le déclencheur, ' + usd(entry) + ' ; il n’est pas laissé actif à l’ouverture d’une séance qui ouvre sous le stop, ' + usd(stop) + ', ni si le stop est touché avant exécution. Sans ces bornes, un gap sous le stop le ferait exécuter bien plus bas, et le R/R annoncé serait faux.' + ' Objectifs : TP1 au plus haut du 5 août, sommet de l’année ; TP2 à une hauteur de base au-dessus du déclencheur. Résistance intermédiaire : la clôture du 5 août, ' + usd(gapTop) + ', haut du gap ; une sortie à ce niveau ne donnerait qu’un R/R de ' + fr(rrGap, 2) + ' depuis le déclencheur et de ' + fr(rrGapCap, 2) + ' depuis le plafond. Liquidité : environ ' + fr(adv / 1e6, 0) + ' M$ échangés par séance, médiane des vingt dernières. Exemple de taille, non personnalisé : avec un budget de perte de 100 $, le risque au plafond, ' + usd(cap - stop) + ' par action, donne ' + sizeExample + ' actions.',
        horizon: 'Dix séances après activation',
        thesis: 'Le marché a sanctionné le 6 août la dépendance à un grand client de l’IA, puis a racheté le titre avec le reste du logiciel. Une clôture au-dessus de $' + entry.toFixed(2) + ', le haut de la base d’août, montrerait que les acheteurs acceptent de remonter dans le gap. Avant activation, une clôture sous ' + usd(abandon) + ' abandonne le dossier. Après activation, le stop sous $' + stop.toFixed(2) + ' limite le coût d’un faux départ. TP1 à ' + usd(tp1) + ', plus haut du 5 août, au-delà de la résistance du haut du gap à ' + usd(gapTop) + ', et TP2 à ' + usd(tp2) + '. Ne pas anticiper le déclencheur, ne pas acheter un gap au-dessus du plafond.',
        catalysts: ['Une clôture au-dessus du plus haut du 10 août, sur un volume au moins égal à la médiane récente.', 'Aucune publication de la société ni d’un comparable dans les quatorze jours du calendrier collecté : le risque de gap vient du secteur ou d’une annonce sur le premier client.', 'Tout commentaire de la société sur l’usage de la cohorte des clients natifs de l’IA.'],
        invalidation: ['Avant activation : une clôture sous ' + usd(abandon) + ', bas de la base, abandonne le scénario.', 'Après activation : une clôture sous ' + usd(stop) + ' invalide le trade.', 'Ouverture au-dessus de ' + usd(cap) + ' après la clôture de déclenchement : pas d’achat à l’ouverture ; seul l’ordre limité à ' + usd(cap) + ' reste valable trois séances.', 'Ordre limité de repli annulé après une clôture sous ' + usd(entry) + ', retiré avant toute ouverture sous le stop à ' + usd(stop) + ' et si le stop est touché avant exécution.', 'Une annonce de perte ou de forte baisse d’un grand client avant activation annule la thèse.'] },
      globalScore: { profile: 'Croissance forte, dépendance à un grand client de l’IA',
        keyTakeawaysPositive: ['Revenus +36 % au deuxième trimestre.', 'Flux libre de 279 M$ au trimestre.', 'Plus de 5 Md$ de liquidités et titres négociables.'],
        keyTakeawaysNegative: ['Premier client en retrait depuis juillet.', 'Plus de vingt fois les revenus.', 'Gap du 6 août encore ouvert au-dessus du cours.'],
        mindsetTip: 'Quand une société dit qu’un client « peut ralentir la croissance » sans le nommer, la bonne question est : combien pèse-t-il ? Tant que la réponse manque, la prudence est un calcul, pas une opinion.' },
      social: { platforms: [], sourceRefs: [market('sentiment non retenu faute de mesure qualifiée')] },
      disclaimer: 'Document de recherche éducatif. Ni conseil financier, ni signal de trading. Statut surveiller : aucun ordre actif.',
    };
  },
  groups: [
    { name: 'Référence du logiciel à l’usage', order: 1, transmission: 'Le titre coté qui co-évolue le plus avec Datadog depuis fin mars, lui aussi facturé à l’usage.', rows: [
      ['MDB', 'leader', 'Base de données en nuage facturée à l’usage', 'Corrélation la plus forte avec Datadog depuis fin mars ; son usage mesure les mêmes budgets cloud des développeurs.']] },
    { name: 'Pairs directs de l’observabilité', order: 1, transmission: 'Même budget de supervision des systèmes.', rows: [
      ['DT', 'direct_peer', 'Observabilité et performance applicative', 'Concurrent frontal cité par le 10-K ; sa croissance plus lente mesure la prime payée pour Datadog.'],
      ['ESTC', 'direct_peer', 'Recherche et gestion des journaux', 'Concurrent cité par le 10-K sur les journaux ; alternative moins chère pour les gros volumes.'],
      ['CSCO', 'direct_peer', 'Réseau et observabilité depuis Splunk', 'Concurrent cité par le 10-K en performance applicative et en journaux.'],
      ['SNOW', 'direct_peer', 'Plateforme de données en nuage', 'Concurrent pour le stockage des données d’observabilité et pair de croissance comparable.']] },
    { name: 'Amont : grands clouds', order: 1, transmission: 'Datadog achète des services cloud tiers et concurrence les outils natifs de ces mêmes clouds, cités par le 10-K.', rows: [
      ['AMZN', 'upstream', 'Cloud AWS et supervision native', 'Concurrent cité par le 10-K en supervision du cloud ; ses tarifs pèsent aussi sur les coûts d’hébergement de Datadog.'],
      ['MSFT', 'upstream', 'Cloud Azure et supervision native', 'Concurrent cité par le 10-K ; la croissance d’Azure élargit aussi le parc à surveiller.'],
      ['GOOGL', 'upstream', 'Google Cloud et supervision native', 'Concurrent cité par le 10-K ; ses outils natifs réduisent l’espace des spécialistes chez ses clients.'],
      ['ORCL', 'upstream', 'Cloud d’infrastructure pour l’IA', 'Son parc de calcul pour l’IA grossit la base d’infrastructures à superviser ; ses investissements précèdent la demande de supervision.']] },
    { name: 'Second ordre : logiciels voisins', order: 2, transmission: 'Budgets logiciels des mêmes équipes techniques.', rows: [
      ['NOW', 'second_order', 'Automatisation des processus d’entreprise', 'Reçoit les alertes et les incidents ; ses budgets suivent ceux des opérations informatiques.'],
      ['TEAM', 'second_order', 'Outils des équipes de développement', 'Même acheteur, les équipes techniques ; ses prévisions éclairent leurs budgets.'],
      ['GTLB', 'second_order', 'Chaîne de développement logiciel', 'Budget voisin des développeurs, sensible aux mêmes optimisations de dépenses.'],
      ['CRWD', 'second_order', 'Sécurité en nuage', 'Concurrent sur la sécurité du cloud, que Datadog vend en complément de la supervision.'],
      ['PANW', 'second_order', 'Plateforme de sécurité et observabilité', 'Depuis le rachat de Chronosphere, vend sa propre plateforme d’observabilité : un concurrent de plus chez les grands comptes.'],
      ['NET', 'second_order', 'Réseau et sécurité en périphérie', 'Budget cloud voisin, sensible au même trafic des applications.'],
      ['NVDA', 'second_order', 'Processeurs graphiques des charges d’IA', 'Le nombre de serveurs d’IA déployés détermine la quantité d’infrastructure à superviser.']] },
    { name: 'Contrôles sectoriels', order: 2, transmission: 'Paniers de référence pour isoler ce qui est propre à Datadog.', rows: [
      ['IGV', 'sector_proxy', 'Panier de logiciels américains', 'Un écart de performance avec ce panier isole ce qui est propre à Datadog.'],
      ['WCLD', 'sector_proxy', 'Panier de logiciels en nuage équipondéré', 'Mesure le sort des éditeurs cloud de taille moyenne, sans les géants.'],
      ['QQQ', 'sector_proxy', 'Grandes valeurs du Nasdaq', 'Contrôle large de la technologie : un mouvement commun avec ce panier n’a rien de spécifique.']] },
  ],
  eventDefault: { leader: 'Aucune publication dans les quatorze jours collectés ; ses chiffres d’usage donnent le ton du logiciel à l’usage', direct_peer: 'Aucune publication dans les quatorze jours collectés ; ses annonces de prix peuvent déplacer les parts de marché', upstream: 'Aucune publication dans les quatorze jours collectés ; ses investissements en calcul restent le signal à suivre', second_order: 'Aucune publication dans les quatorze jours collectés ; ses prévisions éclairent les budgets des équipes techniques', sector_proxy: 'Panier sans publication propre ; exposé aux résultats de ses grandes pondérations' },
  eventRisk: {},
  blastDoc: 1,
  scenarios: c => [
    { scenario: 'bullish', trigger: 'Le reste de la clientèle compense le recul du premier client et le logiciel prolonge sa hausse.', firstOrder: 'Le titre clôture au-dessus du plus haut du 10 août et remonte dans le gap.', secondOrder: 'MongoDB et Snowflake suivent ; IGV confirme.', confirmation: 'Une clôture au-dessus de ' + c.usd(c.entry) + ' avec IGV en hausse la même séance.', contradiction: 'Une cassure pendant que IGV et MongoDB reculent.' },
    { scenario: 'mixed', trigger: 'Pas de nouvelle sur le premier client avant la publication.', firstOrder: 'Le titre oscille entre le bas du 18 septembre et le haut de la base d’août.', secondOrder: 'L’écart de performance avec IGV reste faible, sans information propre au titre.', confirmation: 'Des clôtures entre ' + c.usd(c.abandon) + ' et ' + c.usd(c.entry) + ' pendant plusieurs séances.', contradiction: 'Une sortie franche d’un côté ou de l’autre.' },
    { scenario: 'bearish', trigger: 'Le recul du premier client s’avère plus fort que prévu, ou le logiciel recule.', firstOrder: 'Le titre repasse sous le bas du 18 septembre et retourne vers le point bas du 2 septembre.', secondOrder: 'Les éditeurs facturés à l’usage reculent davantage que le panier.', confirmation: 'Une clôture sous ' + c.usd(c.abandon) + ' avec IGV en baisse.', contradiction: 'Un repli du secteur que le titre ne suit pas.' }],
  contradictions: c => ['La croissance publiée atteint 36 %, mais la prévision du troisième trimestre n’ajoute que 1 à 2 % d’un trimestre à l’autre : le recul du premier client est déjà dans les chiffres de la société.', 'Une corrélation élevée avec MongoDB ne prouve pas un lien commercial ; le premier client de Datadog n’est pas nommé.'],
  missingData: c => ['Le premier client n’est ni nommé ni chiffré : aucun client coté n’entre dans les comparables comme client documenté.', 'Chaîne d’options relevée en séance, non rattachée à la clôture ; sentiment non retenu.', 'Barres d’une source de repli pour toutes les séries.'],
  limitations: ['Barres d’une source de repli (Webull).', 'Options non rattachées à la clôture de référence.', 'Part du premier client non publiée.'],
});
