'use strict';
// Dossier Applied Digital (APLD) v3 au close du 2026-09-25. Refonte de la v2 du 28 août (plan arrêté au stop
// le 10 septembre). Contenu éditorial et repères propres au titre ; calculs, provenance et preuves délégués au
// gabarit tools/lib/analysis-v3-r07.cjs (REF=2026-09-25, run 20260927).
// Agrégats GAAP lus dans les données XBRL officielles de la SEC (companyfacts, 10-K de l'exercice clos le
// 31 mai 2026 inclus) : douze mois glissants = exercice 2026 complet (aucun 10-Q postérieur, le premier trimestre
// de l'exercice 2027 n'est pas encore publié). EBITDA GAAP négatif, donc multiple de scénario appliqué aux
// revenus. Dette = billets à long terme + billets courants + passifs de location-financement au 31 mai.
// Trésorerie = liquidités et équivalents au 31 mai. Actions = 291 469 112 au 28 juillet (page de garde du 10-K).
const R = require('../../../../tools/lib/analysis-v3-r07.cjs');
const GEN = 'analyses/APLD/_runs/20260927/build-apld.cjs';
const SHARES = 291469112;

R.build({
  ticker: 'APLD', shortName: 'Applied Digital', cik: 1144879, generator: GEN, mode: 'archived',
  xbrl: {
    ttm: {
      rev: ['Revenues'],
      ebit: ['OperatingIncomeLoss'],
      ni: ['NetIncomeLossAvailableToCommonStockholdersBasic'],
      da: ['DepreciationDepletionAndAmortization'],
      ocf: ['NetCashProvidedByUsedInOperatingActivities'],
      capex: ['PaymentsToAcquireProductiveAssets'],
    },
    instant: {
      notesLong: ['LongTermNotesPayable'],
      notesCur: ['NotesPayableCurrent'],
      flCur: ['FinanceLeaseLiabilityCurrent'],
      flNon: ['FinanceLeaseLiabilityNoncurrent'],
      cashEq: ['CashAndCashEquivalentsAtCarryingValue'],
    },
    da: ['da'], debt: ['notesLong', 'notesCur', 'flCur', 'flNon'], cash: ['cashEq'],
  },
  scenarioBasis: 'revenue', scenarioMultiple: 10,
  valuationBasis: 'GAAP douze mois au 2026-05-31 (XBRL SEC) = exercice 2026 complet ; EBITDA GAAP négatif, donc multiple appliqué aux revenus GAAP ; dette = billets à long terme + billets courants + passifs de location-financement au 31 mai ; trésorerie = liquidités et équivalents au 31 mai ; 291 469 112 actions au 28 juillet ; multiple de dix fois les revenus = hypothèse éditoriale de re-cotation vers un bailleur d’infrastructure, bien en dessous des ~18× actuels',
  shares: { value: SHARES, doc: 0 },
  levels: {
    s1: { d: '2026-09-25', c: 3 }, // 25,96 — plus bas de la séance de référence
    s2: { d: '2026-09-15', c: 3 }, // 23,39 — plus bas de la base de septembre
    s3: { d: '2026-07-29', c: 3 }, // 22,93 — plus bas de la capitulation de fin juillet
    r1: { d: '2026-09-22', c: 2 }, // 29,099 — plus haut du rebond de la mi-septembre
    r2: { d: '2026-08-12', c: 2 }, // 33,04 — plus haut du mois d'août
    r3: { d: '2026-07-02', c: 2 }, // 35,80 — résistance de début juillet
  },
  supports: ['s1', 's2', 's3'], resistances: ['r1', 'r2', 'r3'],
  levelsMethod: 'Niveaux du plan précédent conservés à l’identique (archivés, inactifs) ; supports et résistances actuels lus sur les barres certifiées.',
  inventory: 133,
  reviewScope: 'Dépôts EDGAR d’Applied Digital du 25 septembre 2025 au 25 septembre 2026 (133 dépôts au total ; formulaires 3, 4, 5 et 144 de déclaration de détention exclus). Cinq dépôts décisionnels ouverts et hachés : le 10-K de l’exercice clos le 31 mai 2026, le communiqué de résultats du quatrième trimestre (8-K du 27 juillet, Exhibit 99.1), le 8-K du 26 juin sur la facilité de crédit renouvelable et le sixième avenant à l’accord d’achat d’actions préférentielles, l’amendement post-effectif à la déclaration d’enregistrement (POSASR du 25 septembre) qui chiffre les actions de conversion et de revente, et le 8-K du 5 mai actant la cession de l’activité cloud. Les 8-K de gouvernance, les Schedule 13D/G et les prospectus de tirage antérieurs sont écartés comme non décisionnels ou redondants avec ces cinq pièces.',
  docs: [
    ['2026-07-29', '10-K', '0001144879-26-000048', 'apld-20260531.htm', 'fy26-10k.htm',
      'Rapport annuel de l’exercice clos le 31 mai 2026 : chiffre d’affaires de 611,3 M$ (+167 %), perte opérationnelle de 236,5 M$, perte nette attribuable aux actionnaires ordinaires de 250,3 M$. L’accord d’achat d’actions préférentielles (PEPA) autorise l’émission de jusqu’à 2 Md$ d’actions préférentielles convertibles de série G ; 1 068 300 actions ont déjà été émises pour 1,04 Md$ bruts, dont 995 146 converties en actions ordinaires. Les billets sécurisés à 9,250 % échéance 2030 (2,35 Md$) sont émis par la filiale APLD ComputeCo. Baux « take-or-pay » à quinze ans avec CoreWeave et deux hyperscalers de qualité investissement.'],
    ['2026-07-27', '8-K / Exhibit 99.1', '0001144879-26-000044', 'apldq426earningsreleaseasf.htm', 'q4fy26-earnings.htm',
      'Communiqué du quatrième trimestre (activités poursuivies) : chiffre d’affaires de 258,7 M$ (+407 %), perte nette attribuable aux actionnaires ordinaires de 110,6 M$, EBITDA ajusté de 42,4 M$. Exercice 2026 : chiffre d’affaires de 611,3 M$. Nouveaux baux « take-or-pay » à quinze ans (300 MW chacun) avec un hyperscaler de qualité investissement, environ 36 Md$ de revenus locatifs contractés au total (environ 86 Md$ options de renouvellement comprises), cinq campus en construction pour deux hyperscalers et CoreWeave.'],
    ['2026-06-26', '8-K', '0001493152-26-030333', 'form8-k.htm', 'jun26-8k-financing.htm',
      'Facilité de crédit renouvelable sécurisée portée à 430,0 M$ (jusqu’à 550,0 M$ avec l’accordéon), arrangée par Goldman Sachs, échéance mai 2029 ; sixième avenant à l’accord d’achat d’actions préférentielles de série G. Financement mixte dette et capacité d’émission d’actions préférentielles.'],
    ['2026-09-25', 'POSASR', '0001493152-26-044312', 'formposasr.htm', 'shelf-posasr.htm',
      'Amendement post-effectif à la déclaration d’enregistrement automatique : revente de jusqu’à 78 225 643 actions ordinaires, dont 75 225 643 issues de la conversion des actions préférentielles convertibles de série G émises au titre du PEPA. Chiffre la dilution en actions ordinaires déjà engagée par le programme préférentiel.'],
    ['2026-05-05', '8-K', '0001493152-26-021333', 'form8-k.htm', 'may26-8k-disposition.htm',
      'Cession de l’activité cloud (calcul GPU) au titre d’un accord de contribution et d’échange : Applied Digital contribue 100 % de sa filiale cloud en échange de 138 216 820 actions nouvelles de l’entité acquéreuse. L’activité cloud est déconsolidée ; Applied Digital devient un bailleur d’infrastructure de centres de données.'],
  ],
  needles: {
    pepa: [0, ['preferred equity purchase agreement', 'Series G Convertible Preferred Stock', '$2 billion']],
    pepa_drawn: [0, ['1,068,300 shares of Series G Preferred Stock', '$1.04 billion']],
    notes2030: [0, ['9.250% senior secured notes due 2030', '$2.35 billion']],
    goingconcern: [0, ['going concern']],
    results: [1, ['$611.3 million', '$258.7 million, up 407%', 'Adjusted EBITDA: $42.4 million']],
    backlog: [1, ['$36 billion in total contracted lease revenue', '15-year take-or-pay lease']],
    revolver: [2, ['$430.0 million', '$550.0 million', 'Sixth Amendment']],
    shelf: [3, ['78,225,643 shares', 'Series G Convertible Preferred Stock']],
    divest: [4, ['divestiture of its cloud business', 'Contribution and Exchange Agreement', '138,216,820 newly issued shares']],
  },
  score: { business: 20, technical: -6, capital: -12, calendar: -4, dilution: -10, risk: 60 },
  riskScoreReason: 'Jugement qualitatif sur dix : carnet de commandes locatif contracté considérable mais revenus encore à construire, dette nette proche de 3,4 Md$, flux de trésorerie libre très négatif, machine de dilution active (PEPA série G, ATM, bons de souscription), bêta supérieur à cinq et positions vendeuses à plus de vingt pour cent du flottant, résultats attendus le 8 octobre.',
  compose: c => {
    const { fr, usd, pct, sgn, close, prev, bars, N, tech, st, M, adv, ret, G$, marketCap, ev, scn, entry, stop, tp1, tp2, rr1, rr2, ref, market, docs, raw, lv } = c;
    const evRev = ev / G$.rev;
    const bar = d => bars.find(b => b[0] === d), prevOf = d => bars[bars.findIndex(b => b[0] === d) - 1];
    const d0729 = bar('2026-07-29'), d0925 = bar('2026-09-25');
    const netDebt = G$.debt - G$.cash;
    return {
      meta: { lang: 'fr', dir: 'ltr', level: 'intermediate', tags: ['us', 'equities', 'ai-chain', 'technology', 'speculative'], grade: 'C+', date: '2026-09-27', dateDisplay: '27 septembre 2026', version: 3, status: 'no-trade', assetType: 'stock', levelsCloseDate: c.REF,
        description: 'Applied Digital : bailleur de centres de données IA au carnet de ~36 Md$ de baux à quinze ans, mais financé par 5 Md$ de dette et une dilution permanente. Revenus 611 M$ (+167 %), perte nette 250 M$, flux libre très négatif. Close du 25 septembre, aucun ordre.',
        ogDescription: 'Applied Digital : ~36 Md$ de baux IA contractés, mais 5 Md$ de dette, flux libre négatif et dilution active ; bêta > 5, résultats le 8 octobre. Aucun ordre.',
        lastMcpRefresh: raw.status.captured_at, levelsVerifiedAt: raw.status.captured_at,
        statusHistory: [...(c.archive.meta.statusHistory || []), { at: raw.status.captured_at, from: 'stopped', to: 'no-trade', note: 'refonte v3 du 27 septembre au close du 25 : le plan du 15 septembre a été arrêté au stop le 10 septembre ; titre à ' + usd(close) + ', sous ses moyennes à vingt, cinquante et deux cents séances, résultats attendus le 8 octobre ; aucun ordre au cours actuel', close }] },
      header: { ticker: 'APLD', name: 'Applied Digital Corporation', exchange: 'NASDAQ', sector: 'Infrastructure de centres de données pour l’IA et le calcul haute performance', price: close, changePct: pct(close, prev),
        badges: [{ text: 'AUCUN ORDRE — RÉSULTATS LE 8 OCTOBRE', color: 'amber' }, { text: 'Chaîne IA — bailleur de capacité de calcul', color: 'purple' }],
        metrics: { marketCap: fr(marketCap / 1e9, 2) + ' Md$', volume: fr(bars[N][5] / 1e6, 1) + ' M', evRevenue: fr(evRev, 1) + '×' }, halalStatus: 'unknown' },
      verdict: { score: 48, conviction: 'Low', bias: 'Neutral',
        confidence: 'Score éditorial non prédictif. Les chiffres d’entreprise viennent des dépôts SEC et des données XBRL officielles ; les niveaux, du close certifié du 25 septembre.',
        summary: 'Applied Digital a changé de métier. Après avoir cédé son activité cloud en mai, la société n’est plus un exploitant de calcul GPU mais un bailleur : elle construit des campus de centres de données et les loue à des hyperscalers par des baux « take-or-pay » à quinze ans. Le carnet est spectaculaire — environ 36 Md$ de revenus locatifs contractés pour cinq campus loués à CoreWeave et à deux hyperscalers de qualité investissement. Le problème est le chemin pour y arriver. Construire ces campus coûte des milliards par an ; le flux de trésorerie libre de l’exercice est négatif de près de 2,8 Md$, financé par une dette de 5,0 Md$ et par une émission continue d’actions — programme « at-the-market » et surtout un accord d’émission d’actions préférentielles convertibles de 2 Md$ dont plus de la moitié est déjà tirée et convertie. À ' + usd(close) + ', le titre a rendu près de la moitié de son plus haut de l’été, clôture sous ses moyennes à vingt, cinquante et deux cents séances, et publie ses résultats le 8 octobre. Un carnet de commandes n’est pas du cash : tant que les campus ne produisent pas, on n’achète pas ce titre au cours actuel. Aucun ordre.',
        whyBuy: [
          'Le carnet de commandes est hors norme : environ 36 Md$ de revenus locatifs contractés à quinze ans, jusqu’à 86 Md$ avec les renouvellements, sur des baux « take-or-pay » avec CoreWeave et deux hyperscalers de qualité investissement.',
          'Le chiffre d’affaires a bondi de 167 % sur l’exercice à 611,3 M$, et de 407 % au quatrième trimestre à 258,7 M$ : la bascule vers l’hébergement de capacité IA se lit déjà dans les comptes.',
          'La cession de l’activité cloud, moins margée et plus capitalistique, recentre la société sur un modèle de bailleur à revenus contractés et à visibilité longue.',
          'La trésorerie atteint 1,59 Md$ et le crédit des baux CoreWeave a été renforcé (garanties de CoreWeave, structure dédiée), après le refinancement de qualité A3 de ce dernier.'],
        whyAvoid: [
          'La dette atteint 5,0 Md$ pour une trésorerie de 1,6 Md$, soit une dette nette de ' + fr(netDebt / 1e9, 1) + ' Md$, sur une société encore en perte : la valorisation suppose que les campus paieront la facture.',
          'Le flux de trésorerie libre de l’exercice est négatif d’environ 2,8 Md$ (flux opérationnel de 89,7 M$ contre 2,87 Md$ d’investissements) : chaque campus à construire exige un financement externe.',
          'La dilution est structurelle : accord d’émission d’actions préférentielles convertibles de série G de 2 Md$, dont 1,04 Md$ déjà tiré et l’essentiel converti en actions ordinaires, plus un programme « at-the-market » et plusieurs séries de bons de souscription.',
          'Le titre est à haut risque de marché : bêta supérieur à cinq, positions vendeuses à ' + fr(st.shortPercentOfFloat * 100, 0) + ' % du flottant, sous toutes ses moyennes, et des résultats binaires attendus le 8 octobre.'],
        controlChecklist: [
          { label: 'Historique de cours', status: 'pass', statusLabel: 'Trois cents séances continues', evidence: 'Série quotidienne certifiée au close du 25 septembre.', action: 'Niveaux et moyennes calculés sur cette seule série.' },
          { label: 'Structure du capital', status: 'warn', statusLabel: 'Dette lourde et dilution active', evidence: '5,0 Md$ de dette, accord d’émission préférentielle de 2 Md$ (1,04 Md$ tiré), ATM et bons de souscription, lus dans le 10-K et le POSASR.', action: 'Relire chaque nouveau dépôt de financement avant toute entrée ; raisonner en actions pleinement diluées.' },
          { label: 'Point d’entrée', status: 'warn', statusLabel: 'Sous les moyennes, résultats imminents', evidence: 'Clôture à ' + usd(close) + ', sous les moyennes à vingt, cinquante et deux cents séances ; publication attendue le 8 octobre, mouvement implicite d’environ 8 %.', action: 'Aucun ordre au cours actuel ; attendre les résultats et une base.' }] },
      business: { theme: 'Bailleur de campus de centres de données pour l’IA et le calcul haute performance',
        overview: '<p>Applied Digital construit et exploite des campus de centres de données et loue leur capacité — puissance électrique, refroidissement, espace — à des clients qui font tourner de l’intelligence artificielle. Depuis la cession de son activité cloud en mai 2026, la société ne vend plus de calcul GPU en direct : elle est devenue un bailleur d’infrastructure, un modèle plus proche d’une foncière spécialisée que d’un fournisseur de cloud.</p><p>Le cœur de la thèse est le carnet de commandes. Applied Digital a signé des baux « take-or-pay » à quinze ans — le locataire paie même s’il n’utilise pas toute la capacité — avec CoreWeave sur son campus d’Ellendale (Dakota du Nord) et, plus récemment, avec deux hyperscalers de qualité investissement pour de nouveaux campus en Louisiane et ailleurs. Au total, la société revendique environ 36 Md$ de revenus locatifs contractés sur les durées de base, jusqu’à 86 Md$ si toutes les options de renouvellement sont exercées, pour cinq campus en construction.</p><p>Le revers est financier et physique. Construire ces campus — acheter le foncier, l’électricité, les transformateurs, le refroidissement — coûte des milliards avant le moindre loyer. Sur l’exercice clos le 31 mai, les investissements ont atteint 2,87 Md$ pour un flux opérationnel de 89,7 M$. Le trou est comblé par la dette (billets sécurisés à 9,250 % échéance 2030 pour 2,35 Md$ émis par une filiale dédiée, billets à 7,000 % échéance 2031 pour 1,59 Md$, facilité renouvelable Goldman Sachs) et par l’émission continue d’actions. Les premiers campus doivent entrer en service à partir de 2027 : jusque-là, la société dépense sans encaisser les loyers promis.</p>',
        moat: 'L’avantage tient à ce qui est difficile à répliquer vite : des sites raccordés à une électricité abondante, des permis, et des baux longue durée déjà signés avec des contreparties solvables. Il reste fragile tant que les campus ne sont pas construits et que la société dépend du marché des capitaux pour les financer : un renchérissement du crédit, un retard de raccordement électrique ou un client qui ralentit fragiliserait un modèle bâti à crédit.',
        segments: [
          { name: 'Hébergement de centres de données HPC/IA', revenue: 'Moteur de la thèse', pct: 'Baux 15 ans « take-or-pay »', description: 'Location de capacité à CoreWeave et à deux hyperscalers ; ~36 Md$ contractés, cinq campus en construction.' },
          { name: 'Hébergement historique (minage)', revenue: 'Part résiduelle et déclinante', pct: 'En transition', description: 'Hébergement d’infrastructure pour clients de minage, hérité du modèle d’origine.' },
          { name: 'Activité cloud (calcul GPU)', revenue: 'Cédée en mai 2026', pct: 'Déconsolidée', description: 'Contribuée à une entité tierce contre 138,2 M actions ; ne fait plus partie des activités poursuivies.' }],
        sourceRefs: [ref(0), ref(1), ref(4)],
        coverageMatrix: [
          { facet: 'Cours et historique', status: 'COUVERT', decision: 'Trois cents séances continues, close certifié ; base des niveaux.' },
          { facet: 'Résultats et guidance', status: 'COUVERT — PRIMAIRE', decision: 'Communiqué du 27 juillet et 10-Q ; prochaine publication au 8 octobre, source calendaire unique, non confirmée par l’émetteur.' },
          { facet: 'Agrégats GAAP', status: 'COUVERT — XBRL', decision: 'Exercice 2026 complet clos le 31 mai 2026, reconstitué depuis les données XBRL officielles ; premier trimestre 2027 non encore publié.' },
          { facet: 'Capital et dilution', status: 'COUVERT — PRIMAIRE', decision: 'Dette, PEPA série G, ATM et bons de souscription lus dans le 10-K et le POSASR ; dette et capitaux propres séparés.' },
          { facet: 'Comparables et transmission', status: 'COUVERT — LOCAL', decision: 'Corrélations recalculées sur barres certifiées ; CoreWeave, client d’ancrage, écarté du blast radius faute de série certifiée continue.' },
          { facet: 'Initiés', status: 'PARTIEL', decision: 'Une retenue fiscale de dirigeant relevée ; couverture officielle incomplète, aucun solde net affirmé.' },
          { facet: 'Options', status: 'COUVERT — INDICATIF', decision: 'Mouvement implicite d’environ 8 % avant résultats relevé ; non rattaché comme niveau à la clôture de référence.' },
          { facet: 'Sentiment et tendances de recherche', status: 'INDISPONIBLE', decision: 'Aucune mesure qualifiée (Reddit et Google Trends indisponibles) ; non utilisé.' }] },
      news: [
        { date: '2026-05-05', title: 'Cession de l’activité cloud : Applied Digital devient un bailleur', impact: 'neutral', detail: 'La société contribue 100 % de son activité cloud (calcul GPU) à une entité tierce contre 138,2 M actions nouvelles de cette dernière. Elle déconsolide un métier capitalistique et peu margé pour se concentrer sur la location de capacité de centres de données.', source: 'Applied Digital — SEC', sourceUrl: docs[4].url },
        { date: '2026-06-26', title: 'Facilité renouvelable de 430 M$ (jusqu’à 550 M$) et sixième avenant au programme préférentiel', impact: 'neutral', detail: 'Facilité de crédit renouvelable sécurisée arrangée par Goldman Sachs, échéance 2029, et sixième avenant à l’accord d’émission d’actions préférentielles convertibles : la société élargit à la fois sa dette et sa capacité de dilution pour financer la construction.', source: 'Applied Digital — SEC', sourceUrl: docs[2].url },
        { date: '2026-07-27', title: 'Résultats : chiffre d’affaires +407 % au trimestre, EBITDA ajusté positif, carnet de 36 Md$', impact: 'positive', detail: 'Chiffre d’affaires trimestriel de 258,7 M$ (+407 %) en activités poursuivies, EBITDA ajusté de 42,4 M$, mais perte nette attribuable aux actionnaires ordinaires de 110,6 M$. La société revendique environ 36 Md$ de revenus locatifs contractés et cinq campus en construction.', source: 'Applied Digital — SEC', sourceUrl: docs[1].url },
        { date: '2026-09-25', title: 'Le titre glisse sous ses moyennes avant les résultats', impact: 'negative', detail: 'Après ' + sgn(ret(5), 1) + ' en cinq séances, Applied Digital clôture à ' + usd(close) + ', sous ses moyennes à vingt (' + usd(tech.ema20) + '), cinquante (' + usd(tech.ema50) + ') et deux cents séances (' + usd(tech.ema200) + '), à environ deux semaines de sa publication du 8 octobre.', source: 'Barres certifiées', sourceUrl: c.evidenceUrl }],
      fundamentals: { rows: [
          { metric: 'Chiffre d’affaires du 4e trimestre (activités poursuivies)', value: '258,7 M$', signal: '+407 % sur un an, communiqué du 27 juillet', signalColor: 'green', _src: 1 },
          { metric: 'EBITDA ajusté du 4e trimestre', value: '42,4 M$', signal: 'Mesure non-GAAP publiée par la société, hors ChronoScale', signalColor: 'blue', _src: 1 },
          { metric: 'Perte nette du 4e trimestre (actionnaires ordinaires)', value: '−110,6 M$', signal: 'Soit −0,39 $ par action, communiqué du 27 juillet', signalColor: 'red', _src: 1 },
          { metric: 'Chiffre d’affaires GAAP sur l’exercice 2026', value: fr(G$.rev / 1e6, 1) + ' M$', signal: 'Exercice clos le 31 mai 2026 (XBRL SEC), +167 % sur un an', signalColor: 'green', _src: 'gaap' },
          { metric: 'Résultat opérationnel GAAP sur l’exercice', value: fr(G$.ebit / 1e6, 1) + ' M$', signal: 'Perte opérationnelle, exercice clos le 31 mai 2026', signalColor: 'red', _src: 'gaap' },
          { metric: 'Résultat net GAAP (actionnaires ordinaires)', value: fr(G$.ni / 1e6, 1) + ' M$', signal: 'Exercice clos le 31 mai 2026, après intérêts minoritaires et préférentiels', signalColor: 'red', _src: 'gaap' },
          { metric: 'EBITDA GAAP sur l’exercice', value: fr(G$.ebitda / 1e6, 1) + ' M$', signal: 'Négatif : aucun multiple d’EBITDA GAAP n’est significatif', signalColor: 'red', _src: 'gaap' },
          { metric: 'Flux de trésorerie opérationnel sur l’exercice', value: fr(G$.ocf / 1e6, 1) + ' M$', signal: 'Faiblement positif, exercice clos le 31 mai 2026', signalColor: 'amber', _src: 'gaap' },
          { metric: 'Investissements (capex) sur l’exercice', value: fr(G$.capex / 1e9, 2) + ' Md$', signal: 'Construction des campus, exercice clos le 31 mai 2026', signalColor: 'red', _src: 'gaap' },
          { metric: 'Flux de trésorerie libre sur l’exercice', value: fr(G$.fcf / 1e9, 2) + ' Md$', signal: 'Flux opérationnel − investissements : la construction consomme le capital', signalColor: 'red', _src: 'gaap' },
          { metric: 'Dette au 31 mai (billets + location-financement)', value: fr(G$.debt / 1e9, 2) + ' Md$', signal: 'Billets à long terme et courants + passifs de location-financement, bilan du 10-K', signalColor: 'red', _src: 'gaap' },
          { metric: 'Trésorerie et équivalents au 31 mai', value: fr(G$.cash / 1e9, 2) + ' Md$', signal: 'Liquidités et équivalents, bilan du 10-K', signalColor: 'blue', _src: 'gaap' },
          { metric: 'EV/revenus GAAP', value: fr(evRev, 1) + '×', signal: 'Valeur d’entreprise au close du 2026-09-25, 291,5 M actions, sur revenus GAAP de l’exercice 2026', signalColor: 'amber', source: 'Clôture certifiée et XBRL SEC', comparison: 'Multiple élevé pour un bailleur en perte : versus une valorisation historique de foncière d’infrastructure, il escompte des revenus contractés mais encore à produire.', _src: 'market' },
          { metric: 'EV/revenus — scénario de re-cotation basse (hypothèse éditoriale)', value: fr(scn.price, 2) + ' $ par action', signal: 'Scénario : multiple ramené à dix fois les revenus GAAP de l’exercice 2026, dette et trésorerie du 31 mai inchangées, soit ' + fr(scn.downside_pct, 0) + ' % sous le close du 2026-09-25', signalColor: 'red', source: 'Clôture certifiée et XBRL SEC', comparison: 'Hypothèse d’un marché cessant de payer près de dix-huit fois les revenus pour un carnet non encore construit ; ce n’est pas un objectif. À dix fois les revenus, la dette absorbe une grande part de la valeur d’entreprise.', _src: 'market' }],
        sourceRefs: [ref(0), ref(1), market('fondamentaux et statistiques')] },
      earnings: { quarters: [],
        beatNote: 'Quatrième trimestre de l’exercice 2026 (clos le 31 mai 2026, activités poursuivies) : chiffre d’affaires de 258,7 M$ (+407 %), EBITDA ajusté de 42,4 M$, résultat net ajusté de 12,9 M$, mais perte nette GAAP attribuable aux actionnaires ordinaires de 110,6 M$ (−0,39 $ par action). Sur l’exercice, chiffre d’affaires de 611,3 M$ et perte nette GAAP aux actionnaires ordinaires de 250,3 M$. La société ne publie pas de guidance chiffrée classique ; sa visibilité vient des baux contractés, pas d’une prévision trimestrielle. Aucune date de prochaine publication n’est confirmée par l’émetteur ; le 8 octobre provient d’une source calendaire unique.',
        nextEarnings: 'Publication du premier trimestre de l’exercice 2027 attendue le 8 octobre 2026 selon une source calendaire unique, non confirmée par l’émetteur ; mouvement implicite d’environ 8 % relevé sur les options.',
        sourceRefs: [ref(1)] },
      capitalStructure: { sharesOutstanding: '291 469 112 actions ordinaires au 28 juillet 2026 (page de garde du 10-K)',
        sharesAuthorized: 'Nombre d’actions autorisées non repris ici ; la capacité de dilution matérielle passe par le programme préférentiel, l’ATM et les bons de souscription décrits ci-dessous.',
        dilutionRisk: 'high',
        shareHistory: 'Le nombre d’actions en circulation est passé d’environ 261,5 millions au 29 juillet 2025 à 291,5 millions au 28 juillet 2026, et continue d’augmenter. Trois mécanismes alimentent cette dilution. D’abord l’accord d’achat d’actions préférentielles (PEPA) du 30 avril 2025, amendé six fois : il autorise l’émission de jusqu’à 2 Md$ d’actions préférentielles convertibles de série G, dont 1 068 300 déjà émises pour 1,04 Md$ bruts et 995 146 déjà converties en actions ordinaires ; l’amendement post-effectif du 25 septembre enregistre jusqu’à 75,2 millions d’actions ordinaires de conversion pour revente. Ensuite un programme « at-the-market » de vente d’actions ordinaires, utilisé régulièrement. Enfin plusieurs séries de bons de souscription (CoreWeave, STB, PEAK6, Jane Street, Building 4). En face, la dette financière atteint environ 5,0 Md$ (billets à 9,250 % échéance 2030 pour 2,35 Md$, billets à 7,000 % échéance 2031 pour 1,59 Md$, facilité renouvelable et location-financement). Le message est simple : chaque campus se finance par de la dette et par de nouvelles actions, et les deux pèsent sur l’actionnaire existant. Un nombre d’actions pleinement dilué à date n’est pas calculable depuis ces seuls dépôts, la conversion de la série G dépendant du cours et l’ATM étant continu.',
        warrants: [
          { series: 'CoreWeave', type: 'Client', note: 'Bons émis au client d’ancrage dans le cadre des baux d’Ellendale.' },
          { series: 'STB / Building 4', type: 'Financement de construction', note: 'Bons liés aux financements de construction de campus.' },
          { series: 'PEAK6 / Jane Street', type: 'Contrepartie de marché', note: 'Bons émis à des contreparties financières.' }],
        atm: { active: true, authorized: 'Programme « at-the-market » d’actions ordinaires actif', used: 'Utilisé régulièrement pour financer la croissance (produits récents d’environ 196 M$ relevés)', remaining: 'Capacité résiduelle non chiffrée ici ; à recouper à chaque dépôt' },
        sourceRefs: [ref(0), ref(3), ref(2)] },
      filingsReview: { summary: 'Cinq dépôts décisionnels ouverts et hachés, sur un inventaire de 133 formulaires hors déclarations d’initiés. Ils séparent trois réalités que le récit du carnet de commandes tend à confondre : les résultats et le carnet, réels et impressionnants ; le financement, par dette lourde et par dilution continue ; et la transformation du périmètre, avec la cession de l’activité cloud. Aucun rapport de vendeur à découvert activiste ni fonds hostile identifié dans la période.',
        filings: docs.map(d => ({ date: d.date, form: d.form, accession: d.accession, finding: d.finding, url: d.url })),
        contrarianRisks: [
          'Le carnet de 36 Md$ est un revenu futur contractuel, pas encaissé : il dépend de la mise en service de cinq campus encore en construction, entre 2027 et 2028.',
          'Le programme préférentiel de série G est un instrument de dilution puissant : convertible en actions ordinaires, tiré à plus de la moitié, avec un plafond d’échange qui borne — mais ne supprime pas — l’émission.',
          'La dette est portée par des filiales dédiées (structures ad hoc par campus) : la solvabilité dépend de la performance de chaque projet, pas seulement du bilan consolidé.',
          'La cession de l’activité cloud simplifie le modèle mais réduit les revenus déjà encaissés au profit de loyers encore à venir : la visibilité se déplace vers le futur.',
          'La concentration client est extrême : CoreWeave et deux hyperscalers portent l’essentiel du carnet ; une renégociation ou un défaut pèserait lourd malgré les clauses « take-or-pay ».'] },
      technicals: { rsi14: +tech.rsi14.toFixed(2), macd: +tech.macd.toFixed(2), macdSignal: +tech.macdSignal.toFixed(2), ema20: +tech.ema20.toFixed(2), ema50: +tech.ema50.toFixed(2), ema200: +tech.ema200.toFixed(2),
        ma50Type: 'EMA', ma200Type: 'EMA', ma50Available: true, ma200Available: true, atr14: +tech.atr14.toFixed(2),
        badges: ['Sous les moyennes à vingt, cinquante et deux cents séances', 'RSI neutre, MACD encore négatif', 'Résultats binaires le 8 octobre'],
        supports: [lv('s1'), lv('s2'), lv('s3')], resistances: [lv('r1'), lv('r2'), lv('r3')],
        setupNote: 'Le titre clôture à ' + usd(close) + ', sous ses moyennes à vingt (' + usd(tech.ema20) + '), cinquante (' + usd(tech.ema50) + ') et deux cents séances (' + usd(tech.ema200) + '), RSI à ' + fr(tech.rsi14, 0) + ', MACD sous zéro mais repassé au-dessus de sa ligne de signal — un début de stabilisation, pas un retournement. Il a rendu près de la moitié de son plus haut de l’été (au-dessus de 50 $ en juin) et se stabilise dans une base autour de ' + usd(lv('s2')) + '–' + usd(close) + '. Aucun ordre : les niveaux du plan précédent, entrée ' + usd(entry) + ' et stop ' + usd(stop) + ', sont archivés et inactifs. Supports : ' + usd(lv('s1')) + ', ' + usd(lv('s2')) + ' et ' + usd(lv('s3')) + '. Résistances : ' + usd(lv('r1')) + ', ' + usd(lv('r2')) + ' et ' + usd(lv('r3')) + '. ATR de ' + usd(tech.atr14) + ', soit une volatilité élevée cohérente avec un bêta supérieur à cinq.',
        wyckoff: 'Base possible après un marquage baissier depuis juin ; non utilisée pour fixer les niveaux.',
        sourceRefs: [market('barres quotidiennes et indicateurs recalculés')] },
      options: { callOI: 'Non détaillé', putOI: 'Non détaillé', cpRatio: 'Non détaillé', maxPain: 'Non détaillé', ivMean: 'Mouvement implicite d’environ 8 % avant résultats', skew: 'Non rattaché comme niveau à la clôture de référence', unusual: 'Le marché price une publication très volatile le 8 octobre (mouvement implicite ~8 %)', sourceRefs: [market('options — mouvement implicite avant résultats')] },
      shortInterest: { siPct: fr(st.shortPercentOfFloat * 100, 2) + ' % du flottant', daysToCover: fr(st.shortRatio, 2) + ' jours, date de règlement non précisée par le snapshot', ctb: 'Coût d’emprunt non disponible à la collecte', trend: 'Positions vendeuses élevées pour la taille : plus de vingt pour cent du flottant, environ ' + fr(st.sharesShort / 1e6, 0) + ' millions d’actions. Un dénouement forcé après une bonne nouvelle est possible, mais ce n’est pas une thèse d’achat en soi.', squeezeScore: 'Élevé mécaniquement, mais subordonné à un catalyseur ; non retenu comme thèse principale', sourceRefs: [market('positions vendeuses')] },
      insiders: { signal: 'Aucun achat de dirigeant relevé en septembre. Le mouvement documenté le plus récent est une retenue fiscale du président Jason Gechen Zhang (49 188 actions retenues le 12 septembre à 26,42 $, code F), c’est-à-dire un règlement d’impôt sur l’acquisition de droits, pas une vente de marché. La couverture officielle des transactions d’initiés est incomplète sur la période : aucun solde net acheteur ou vendeur n’est affirmé.',
        recentTransactions: [],
        sourceRefs: [market('formulaires 4'), ref(0)] },
      macro: { indicators: [{ name: 'Clôture de référence', value: c.REF, signal: usd(close) + ', séance complète' }, { name: 'Rendement cinq séances', value: sgn(ret(5)), signal: 'Descriptif' }, { name: 'Rendement vingt et une séances', value: sgn(ret(21)), signal: 'Descriptif' }],
        regime: 'neutral', impact: 'Applied Digital est doublement sensible aux taux longs : ils renchérissent le coût de la dette qui finance la construction, et ils compriment la valorisation d’un titre dont la valeur repose sur des loyers lointains. Le titre suit aussi l’appétit du marché pour la thématique des centres de données IA, très cyclique. Un durcissement du crédit ou un doute sur la demande de calcul le toucherait plus que la moyenne, bêta supérieur à cinq à l’appui.' },
      risks: { riskScore: 8, riskProfile: 'Very High',
        riskSummary: 'Le risque d’Applied Digital n’est pas l’absence de demande — le carnet de commandes le dément — mais le chemin de financement pour le servir. Tant que les campus ne produisent pas, la société brûle des milliards par an, comblés par de la dette de plus en plus lourde et par une dilution continue. Une hausse des taux, un retard de construction ou de raccordement électrique, ou un accès au capital plus difficile suffisent à casser un modèle bâti à crédit — et le marché le sanctionne déjà par un bêta supérieur à cinq et des positions vendeuses massives.',
        riskCards: [
          { title: 'Dette et flux de trésorerie', severity: 'critical', icon: 'fa-sack-dollar', points: ['Dette d’environ 5,0 Md$ contre 1,6 Md$ de trésorerie ; billets à 9,250 % et 7,000 %.', 'Flux de trésorerie libre négatif d’environ 2,8 Md$ sur l’exercice : la construction consomme le capital.'], verdict: 'Chaque campus exige un financement externe ; le service de la dette pèse avant même que les loyers n’arrivent.' },
          { title: 'Dilution structurelle', severity: 'critical', icon: 'fa-money-bill-trend-up', points: ['Programme d’actions préférentielles convertibles de 2 Md$ (série G), tiré à 1,04 Md$ et converti pour l’essentiel.', 'Programme « at-the-market » actif et plusieurs séries de bons de souscription.'], verdict: 'L’actionnaire existant est dilué en continu pour financer la croissance ; la conversion de la série G ajoute des actions au fil du cours.' },
          { title: 'Exécution et concentration', severity: 'high', icon: 'fa-flask', points: ['Cinq campus à livrer entre 2027 et 2028 ; dépendance à l’électricité, aux permis et aux équipements.', 'Carnet concentré sur CoreWeave et deux hyperscalers.'], verdict: 'Un retard de mise en service décale les loyers sans décaler la dette ; un défaut client, même avec clause « take-or-pay », serait lourd.' },
          { title: 'Risque de marché et de séance', severity: 'high', icon: 'fa-rocket', points: ['Bêta supérieur à cinq ; positions vendeuses à ' + fr(st.shortPercentOfFloat * 100, 0) + ' % du flottant.', 'Résultats attendus le 8 octobre, mouvement implicite d’environ 8 %.'], verdict: 'La taille d’une position doit rester modeste : un gap post-résultats peut sauter un stop d’un coup.' }],
        pedagogy: 'Applied Digital illustre la différence entre un carnet de commandes et un compte de résultat. Le carnet — 36 Md$ de loyers contractés — est réel, mais il se transforme en trésorerie seulement quand les campus sont construits et allumés, entre 2027 et 2028. D’ici là, la société finance sa construction par de la dette à taux élevé et par une émission continue d’actions : c’est pourquoi elle vaut environ dix-huit fois ses revenus tout en perdant de l’argent. Côté marché, le titre échange environ ' + fr(adv / 1e6, 0) + ' M$ par séance : la liquidité est excellente, mais un bêta supérieur à cinq et des résultats binaires le 8 octobre imposent de petites positions : un gap à l’ouverture après la publication peut sauter un stop d’un coup. Dimensionner à partir de la distance au stop et d’un budget de perte fixé d’avance, jamais à partir de l’objectif. Ici, la bonne décision est d’attendre : mieux vaut ne pas courir après le titre avant résultats ; pas de base confirmée, pas de trade.' },
      tradeIdea: { status: 'no-trade', archiveReferenceClose: c.archive.meta.levelsCloseDate,
        statusNote: 'Aucun ordre actif. Les niveaux affichés — entrée ' + usd(entry) + ', stop ' + usd(stop) + ', TP1 ' + usd(tp1) + ', TP2 ' + usd(tp2) + ' — sont ceux, archivés, du plan précédent, arrêté au stop le 10 septembre : inactifs et non exécutables. Aucun nouvel ordre au cours actuel, sous toutes les moyennes et à deux semaines d’une publication à fort mouvement implicite.',
        entry, stop, tp1, tp2,
        stopPct: pct(stop, entry).toFixed(1) + '%', tp1Pct: '+' + pct(tp1, entry).toFixed(1) + '%', tp2Pct: '+' + pct(tp2, entry).toFixed(1) + '%',
        rr: '1:' + rr1.toFixed(2) + ' TP1 / 1:' + rr2.toFixed(2) + ' TP2',
        entryNote: 'Aucune entrée. Les niveaux ci-dessus sont archivés et non exécutables. Conditions de réexamen, sans ordre : d’abord passer les résultats du 8 octobre, puis une base tenue au-dessus de ' + usd(lv('s2')) + ' et une clôture au-dessus de ' + usd(lv('r1')) + ' (plus haut du rebond de mi-septembre) sur volume, sans nouveau dépôt de financement dilutif. Liquidité : environ ' + fr(adv / 1e6, 0) + ' M$ échangés par séance ; ATR de ' + usd(tech.atr14) + '. Toute position devrait rester réduite compte tenu du bêta et du risque de gap.',
        horizon: 'Aucune position au cours actuel',
        thesis: 'Applied Digital est une histoire de carnet de commandes contre bilan. Le carnet — environ 36 Md$ de loyers contractés à quinze ans — est spectaculaire ; le bilan — 5 Md$ de dette, un flux libre négatif de 2,8 Md$, une dilution permanente — l’est tout autant. On n’achète pas ce titre à ' + usd(close) + ', sous toutes ses moyennes et à deux semaines d’une publication binaire, quand la thèse repose sur des campus encore en construction. Le plan précédent a été arrêté au stop ; le prochain se construira, s’il se construit, sur une base tenue après résultats et une reprise au-dessus de ' + usd(lv('r1')) + '. La valeur suppose une exécution parfaite d’un chantier financé à crédit : ce pari se prend après confirmation, pas avant.',
        catalysts: ['Les résultats du 8 octobre : premier point d’étape sur la montée en puissance des campus et la consommation de trésorerie.', 'Une clôture au-dessus de ' + usd(lv('r1')) + ' sur volume, après une base tenue au-dessus de ' + usd(lv('s2')) + '.', 'Un financement de campus par de la dette de projet plutôt que par de nouvelles actions, qui réduirait la pression dilutive.'],
        invalidation: ['Les niveaux affichés sont archivés et informatifs : aucun transfert vers une exécution actuelle.', 'Un achat au cours actuel, avant résultats et sous toutes les moyennes, contredit ce dossier.', 'Un nouveau tirage de la série G ou une émission « at-the-market » importante aggraverait la dilution et pèserait sur le titre.'] },
      globalScore: { profile: 'Bailleur de centres de données IA : carnet immense, bilan à crédit',
        keyTakeawaysPositive: ['Carnet locatif contracté d’environ 36 Md$ à quinze ans, jusqu’à 86 Md$ avec renouvellements.', 'Chiffre d’affaires +167 % sur l’exercice, EBITDA ajusté trimestriel redevenu positif.', 'Modèle recentré sur la location de capacité après la cession du cloud.'],
        keyTakeawaysNegative: ['Dette de 5 Md$ et flux de trésorerie libre négatif d’environ 2,8 Md$.', 'Dilution structurelle : programme préférentiel de 2 Md$, ATM et bons de souscription.', 'Bêta supérieur à cinq, sous toutes les moyennes, résultats binaires le 8 octobre.'],
        mindsetTip: 'Un carnet de commandes n’est pas du cash tant que les murs ne sont pas construits et allumés. Regarder qui paie la construction — dette et dilution — avant de se laisser porter par le chiffre du backlog, et ne pas prendre un pari binaire juste avant des résultats.' },
      social: { platforms: [], sourceRefs: [market('sentiment non retenu faute de mesure qualifiée')] },
      disclaimer: 'Document de recherche éducatif. Ni conseil financier, ni signal de trading. Statut aucun ordre : le plan affiché est archivé et arrêté ; les résultats du 8 octobre sont un risque binaire.',
    };
  },
  groups: [
    { name: 'Pairs directs — hébergeurs et neoclouds IA cotés', order: 1, transmission: 'Même modèle : construire des centres de données IA financés à crédit et les louer à des hyperscalers, ou d’anciens mineurs qui pivotent vers l’hébergement HPC. Leurs conditions de financement éclairent celles d’Applied Digital.', rows: [
      ['NBIS', 'direct_peer', 'Neocloud IA coté', 'Même modèle de location de capacité de calcul financé par capital externe ; repère de valorisation d’un pair en forte croissance.'],
      ['IREN', 'direct_peer', 'Mineur devenu hébergeur IA/HPC', 'Ancien mineur qui convertit ses sites en capacité IA ; même bascule que celle qu’Applied Digital a accélérée.'],
      ['WULF', 'direct_peer', 'Hébergeur HPC issu du minage', 'Convertit ses centres vers l’hébergement HPC pour hyperscalers ; ses baux et financements éclairent ceux d’Applied Digital.'],
      ['CIFR', 'direct_peer', 'Mineur en transition vers le HPC', 'Même chaîne de construction financée à crédit ; sensibilité comparable à l’appétit du marché pour l’infrastructure IA.']] },
    { name: 'Amont — puces, serveurs, alimentation', order: 1, transmission: 'Fournisseurs de la chaîne de construction : les campus d’Applied Digital et la demande de ses locataires passent par leurs puces, serveurs et équipements électriques.', rows: [
      ['NVDA', 'upstream', 'Fournisseur de processeurs graphiques', 'La demande de capacité IA, donc les baux d’Applied Digital, dérive de l’appétit pour ses puces.'],
      ['VRT', 'upstream', 'Alimentation et refroidissement', 'Équipements électriques et thermiques des centres de données ; goulot de mise en service.'],
      ['DELL', 'upstream', 'Intégrateur de serveurs IA', 'Assemble les serveurs installés chez les locataires ; son carnet reflète en partie la demande de capacité.'],
      ['SMCI', 'upstream', 'Serveurs IA denses', 'Fournisseur de serveurs haute densité pour les campus IA ; baromètre de la demande de déploiement.'],
      ['HPE', 'upstream', 'Serveurs et infrastructure d’entreprise', 'Fournisseur d’infrastructure de calcul ; exposé au même cycle de construction.'],
      ['LITE', 'upstream', 'Optique et réseau', 'Composants optiques des grappes IA ; un signal avancé d’équipement des sites.']] },
    { name: 'Demande — cloud et infrastructure IA', order: 1, transmission: 'Côté demande : les fournisseurs de cloud qui contractent de la capacité fixent le rythme et le prix des baux qu’Applied Digital peut signer.', rows: [
      ['ORCL', 'leader', 'Fournisseur d’infrastructure cloud', 'Contracte de grandes capacités de calcul IA ; son capex et ses tarifs disent si la demande de location tient.']] },
    { name: 'Second ordre — actifs numériques et infra digitale', order: 2, transmission: 'Demande indirecte et cousinage sectoriel : actifs numériques, minage et foncières d’infrastructure digitale, dont le mouvement croise celui d’Applied Digital.', rows: [
      ['GLXY', 'second_order', 'Services d’actifs numériques et centres de données', 'Acteur des actifs numériques qui investit aussi dans les centres de données IA ; cousin sectoriel financé sur les marchés de capitaux.'],
      ['WGMI', 'sector_proxy', 'Panier de mineurs de cryptoactifs', 'Panier des mineurs, dont beaucoup pivotent vers le HPC : contrôle du sous-secteur d’origine d’Applied Digital.'],
      ['DTCR', 'sector_proxy', 'Panier d’infrastructure digitale et centres de données', 'Foncières et opérateurs de centres de données : contrôle du thème auquel Applied Digital se rattache désormais.']] },
    { name: 'Contrôles sectoriels', order: 2, transmission: 'Paniers de référence pour séparer le mouvement du titre de celui de son secteur.', rows: [
      ['SMH', 'sector_proxy', 'Panier de semi-conducteurs', 'Contrôle de l’amont : si les puces montent et Applied Digital baisse, la cause est propre au titre.'],
      ['XLK', 'sector_proxy', 'Secteur technologie du S&P', 'Contrôle large de la technologie : un mouvement commun n’a rien de spécifique à Applied Digital.']] },
  ],
  eventDefault: { leader: 'Aucune publication dans les quatorze jours collectés ; son capital et ses tarifs restent le signal à suivre', direct_peer: 'Aucune publication dans les quatorze jours collectés ; ses baux et financements encadrent ceux d’Applied Digital', upstream: 'Aucune publication dans les quatorze jours collectés ; ses commandes précèdent l’équipement des campus', second_order: 'Aucune publication dans les quatorze jours collectés ; son accès au capital reste à suivre', sector_proxy: 'Panier sans publication propre ; exposé aux résultats de ses grandes pondérations' },
  eventRisk: {},
  blastDoc: 1,
  scenarios: c => [
    { scenario: 'bullish', trigger: 'Les résultats du 8 octobre montrent une montée en puissance des campus et une consommation de trésorerie maîtrisée, sans nouvelle émission d’actions.', firstOrder: 'Le titre franchit ' + c.usd(c.lv('r1')) + ' et reconstruit une tendance ; les revenus locatifs commencent à valider le carnet.', secondOrder: 'Les neoclouds et hébergeurs financés à crédit se refinancent plus facilement ; l’amont garde son carnet.', confirmation: 'Une clôture au-dessus de ' + c.usd(c.lv('r1')) + ' sur volume après résultats, sans nouveau dépôt dilutif.', contradiction: 'Un nouveau tirage de la série G ou une émission « at-the-market » importante malgré de bons résultats.' },
    { scenario: 'mixed', trigger: 'Les campus avancent comme prévu mais la construction continue de consommer plus de trésorerie que l’exploitation n’en dégage.', firstOrder: 'Le titre reste bloqué dans sa base, entre ' + c.usd(c.lv('s2')) + ' et ' + c.usd(c.lv('r1')) + ', au gré de l’appétit pour la thématique IA.', secondOrder: 'L’écart de performance avec l’amont se maintient : les fournisseurs encaissent, le bailleur attend ses loyers.', confirmation: 'Des clôtures dans le couloir pendant plusieurs séances, dilution poursuivie au rythme habituel.', contradiction: 'Une sortie franche du couloir, d’un côté ou de l’autre.' },
    { scenario: 'bearish', trigger: 'Un retard de construction ou de raccordement, un durcissement du crédit, ou une émission dilutive de grande taille.', firstOrder: 'Le titre casse ' + c.usd(c.lv('s2')) + ' puis se dirige vers ' + c.usd(c.lv('s3')) + ' ; le coût du financement pèse sur la thèse.', secondOrder: 'Les pairs financés à crédit décrochent davantage ; l’amont révise ses commandes de déploiement.', confirmation: 'Une clôture sous ' + c.usd(c.lv('s3')) + ' ou un dépôt de financement fortement dilutif.', contradiction: 'Une mise en service et des encaissements de loyers conformes malgré la hausse des taux.' }],
  contradictions: c => ['Le carnet de commandes est immense mais le titre a perdu près de la moitié de sa valeur depuis juin : le marché price le coût et le risque de construction, pas seulement le revenu futur.', 'Une corrélation élevée avec un pair mineur ou un panier IA ne prouve pas un lien commercial : CoreWeave, le vrai client d’ancrage, n’entre pas dans les comparables certifiés faute de série continue.'],
  missingData: c => ['CoreWeave (CRWV), locataire d’ancrage économiquement matériel, est écarté du blast radius certifié : sa série quotidienne est rejetée pour discontinuité de séances (introduction en bourse récente). Il est traité qualitativement dans les sections Activité et Risques.', 'Prochaine date de résultats (8 octobre) issue d’une source calendaire unique, non confirmée par l’émetteur.', 'Coût d’emprunt des positions vendeuses indisponible à la collecte ; sentiment Reddit et Google Trends indisponibles.', 'Fondamentaux et statistiques du fournisseur relevés en instantané, non reconstitués à la clôture de référence ; nombre d’actions autorisées non repris.'],
  limitations: ['CoreWeave et tout comparable à série discontinue écartés du calcul de corrélation.', 'EBITDA GAAP négatif : la valorisation relative repose sur les revenus, pas sur l’EBITDA.', 'Fondamentaux et statistiques du fournisseur relevés en instantané, non point-in-time ; court terme décrit qualitativement, aucun objectif d’analyste écrit comme gouvernant.'],
});
