'use strict';
// Dossier CCJ v3 au close du 2026-09-25 (lot R07). Cameco Corporation, émetteur étranger canadien :
// dépôts 40-F/6-K, taxonomie IFRS, ZÉRO tag us-gaap dans companyfacts, devise de PRÉSENTATION = dollar
// canadien (CAD). Les agrégats financiers sont fournis par cfg.manualFinancials — chaque valeur est lue
// dans l'état financier du dépôt primaire (40-F de l'exercice 2025 + 6-K du 31 juillet 2026), puis
// CONVERTIE de CAD en USD au taux de clôture de la période, pour rester cohérente avec la capitalisation
// (cours NYSE en USD). Aucune valeur n'est dérivée ni estimée par le générateur ; la conversion applique
// un taux daté et divulgué.
//
// ⚠️ DEVISE (point critique). Cameco publie ses comptes en CAD ; le cours et la capitalisation sont en USD.
// Pour ne jamais mélanger deux devises dans un même ratio, TOUS les agrégats financiers sont convertis
// CAD → USD au taux de clôture de la période, soit 1,4210 CAD pour 1 USD (taux de change quotidien de la
// Banque du Canada, série FXUSDCAD, 30 juin 2026 — date de clôture du bilan intermédiaire). USD = CAD / 1,4210.
// Le même taux daté est appliqué aux flux (douze mois glissants) et au bilan (30 juin 2026), par souci de
// cohérence et de traçabilité ; ce choix est explicité dans la prose et dans le champ de méthode.
//
// Base : douze mois glissants au 30 juin 2026 = exercice 2025 (40-F) + premier semestre 2026 (6-K du
// 31 juillet) − premier semestre 2025 (6-K du 31 juillet). Bilan au 30 juin 2026 (6-K). Scénario en
// EV/EBITDA (Cameco est rentable). Comparables : 12 symboles propres (uranium, nucléaire, utilities et
// équipement électrique) ; URA/NXE/LEU/EU/SMR/VST/URNM/URG/NLR/BWXT/NRG/PWR élagués (géométrie de barre
// invalide ou discontinuité de séances dans la fenêtre servie). peerFicheSha vide.
const R = require('../../../../tools/lib/analysis-v3-r07.cjs');
const GEN = 'analyses/CCJ/_runs/20260927/build-ccj.cjs';

// Taux de change daté (Banque du Canada, FXUSDCAD, 30 juin 2026) : 1 USD = 1,4210 CAD.
const FX = 1.4210; // CAD par USD ; USD = CAD / FX
const cad = k => Math.round(k / FX); // convertit un montant en dollars canadiens vers l'USD entier

// Agrégats IFRS lus dans les dépôts primaires (publiés en CAD), convertis en USD au taux du 30/06/2026.
// Flux = douze mois glissants au 30 juin 2026 = exercice 2025 + S1 2026 − S1 2025 (milliers de CAD → USD).
// rev  : 3 481 933 + 1 659 137 − 1 666 448 = 3 474 622 kCAD
// ebit : 618 142 + 247 976 − 351 763 = 514 355 kCAD  (résultat des activités d'exploitation, IFRS)
// ni   : 589 542 + 155 961 − 390 638 = 354 865 kCAD
// da   : 293 094 + 139 257 − 147 073 = 285 278 kCAD  (amortissements en coût des ventes)
// dette: 996 750 kCAD (emprunts à long terme au 30/06/2026, hors obligations locatives)
// tréso: 1 112 718 kCAD (trésorerie et équivalents au 30/06/2026)
const REV_TTM  = cad(3474622000); // 2 445 194 933 USD
const EBIT_TTM = cad(514355000);  //   361 966 925 USD
const NI_TTM   = cad(354865000);  //   249 729 064 USD
const DA_TTM   = cad(285278000);  //   200 758 621 USD
const DEBT     = cad(996750000);  //   701 442 646 USD
const CASH     = cad(1112718000); //   783 052 780 USD

// Excédent brut ajusté publié par Cameco (mesure non normalisée, INCLUANT sa quote-part de Westinghouse
// mise en équivalence). Cité en contexte, en CAD, non gouvernant. FY2025 : 1 929 M CA ; S1 2026 : 899 M CA.
const ADJ_EBITDA_FY25_CAD = 1929000000;

const ACC_40F = '0001193125-26-116229', ACC_6K = '0001193125-26-326768';

R.build({
  ticker: 'CCJ', shortName: 'Cameco', cik: 1009001, generator: GEN, mode: 'breakout',
  xbrl: { ttm: {}, instant: {}, da: ['da'], debt: ['debt'], cash: ['cash'] },
  manualFinancials: { figures: {
    rev:  { value: REV_TTM,  form: '6-K', accn: ACC_6K, start: '2025-07-01', end: '2026-06-30', doc: 1 },
    ebit: { value: EBIT_TTM, form: '6-K', accn: ACC_6K, start: '2025-07-01', end: '2026-06-30', doc: 1 },
    ni:   { value: NI_TTM,   form: '6-K', accn: ACC_6K, start: '2025-07-01', end: '2026-06-30', doc: 1 },
    da:   { value: DA_TTM,   form: '6-K', accn: ACC_6K, start: '2025-07-01', end: '2026-06-30', doc: 1 },
    debt: { value: DEBT,     form: '6-K', accn: ACC_6K, end: '2026-06-30', doc: 1 },
    cash: { value: CASH,     form: '6-K', accn: ACC_6K, end: '2026-06-30', doc: 1 },
  } },
  scenarioBasis: 'ebitda', scenarioMultiple: 50,
  valuationBasis: 'Agrégats IFRS lus dans les dépôts primaires de Cameco (émetteur étranger canadien, 40-F/6-K, devise de présentation CAD, aucun companyfacts us-gaap). Les montants sont convertis du dollar canadien vers le dollar américain au taux de change quotidien de la Banque du Canada du 30 juin 2026 (FXUSDCAD = 1,4210 CAD pour 1 USD ; USD = CAD / 1,4210), afin de rester cohérents avec la capitalisation, elle-même en USD (cours NYSE). Le même taux daté est appliqué aux flux et au bilan par souci de traçabilité. Flux = douze mois glissants au 30 juin 2026, reconstitués de l’exercice 2025 (40-F) + premier semestre 2026 (6-K du 31 juillet) − premier semestre 2025 : chiffre d’affaires 3 474,6 M$ CA (2 445,2 M$ US), résultat d’exploitation 514,4 M$ CA (362,0 M$ US), amortissements 285,3 M$ CA (200,8 M$ US), résultat net 354,9 M$ CA (249,7 M$ US). Bilan au 30 juin 2026 : trésorerie 1 112,7 M$ CA (783,1 M$ US) ; emprunts à long terme 996,8 M$ CA (701,4 M$ US), hors obligations locatives ; 435 532 978 actions ordinaires en circulation. L’EBITDA retenu ici = résultat d’exploitation + amortissements ; il EXCLUT la quote-part des résultats de Westinghouse (participation de 49 % mise en équivalence), dont la valeur comptable (≈ 2,9 Md$ CA) reste pourtant intégrée à la valeur d’entreprise : ce multiple d’exploitation strict est donc structurellement plus élevé que l’excédent brut ajusté publié par Cameco (1 929 M$ CA en 2025, Westinghouse compris). Le multiple de cinquante fois l’EBITDA du scénario est une hypothèse éditoriale de stress, pas une juste valeur.',
  levels: { trigger: { d: '2026-09-22', c: 2 }, stop: { d: '2026-09-23', c: 3 }, abandon: { d: '2026-09-25', c: 3 }, s1: { d: '2026-09-24', c: 3 }, s2: { d: '2026-09-25', c: 3 }, r1: { d: '2026-09-04', c: 2 }, r2: { d: '2026-09-08', c: 2 } },
  supports: ['s1', 'stop', 's2'], resistances: ['r1', 'r2', 'trigger'],
  targets: ({ entry, abandon }) => { const range = entry - abandon; return { tp1: entry + range, tp2: entry + 1.5 * range, range }; },
  levelsMethod: 'Déclencheur = plus haut du 22 septembre, sommet de la fourchette de la mi-septembre ; bas du couloir = plus bas du 25 septembre ; stop = plus bas du 23 septembre ; TP1 = déclencheur + hauteur du couloir ; TP2 = déclencheur + 1,5 × hauteur ; plafond d’achat = (TP1 + 1,5 × stop) / 2,5 arrondi au cent inférieur ; pourcentages depuis l’entrée ; R/R = gain / risque.',
  inventory: 41,
  reviewScope: 'Dépôts EDGAR de Cameco Corporation (CIK 1009001) revus jusqu’au 25 septembre 2026 : le 40-F de l’exercice clos le 31 décembre 2025 (déposé le 19 mars 2026 ; états financiers consolidés audités, rapport de gestion et notice annuelle en annexes) et le 6-K du 31 juillet 2026 (communiqué, rapport de gestion et états financiers intermédiaires condensés non audités des trois et six mois clos les 30 juin 2026 et 2025). Les 6-K de gouvernance, de dividendes et d’opérations mineures sont écartés du décompte décisionnel.',
  docs: [
    ['2026-03-19', '40-F', ACC_40F, 'd34605dex992.htm', 'fy25-40f-fs__d34605dex992.htm',
      'États financiers consolidés audités de l’exercice clos le 31 décembre 2025 (IFRS, CAD) : chiffre d’affaires de 3 481,9 M$ CA (contre 3 135,8 M$ CA), résultat d’exploitation de 618,1 M$ CA, amortissements de 293,1 M$ CA, résultat net de 589,5 M$ CA ; trésorerie de 1 114,9 M$ CA en fin d’exercice ; flux de trésorerie d’exploitation de 1 408,4 M$ CA et investissements de 333,0 M$ CA.', 1009001],
    ['2026-07-31', '6-K', ACC_6K, 'd125942dex993.htm', 'q2-6k-fs__d125942dex993.htm',
      'États financiers intermédiaires condensés non audités des trois et six mois clos les 30 juin 2026 et 2025 (IFRS, CAD) : chiffre d’affaires du semestre de 1 659,1 M$ CA (contre 1 666,4 M$ CA), résultat d’exploitation de 248,0 M$ CA (contre 351,8 M$ CA), amortissements de 139,3 M$ CA, résultat net de 156,0 M$ CA (contre 390,6 M$ CA) ; au 30 juin 2026, trésorerie de 1 112,7 M$ CA, emprunts à long terme de 996,8 M$ CA, participation de 49 % dans Westinghouse mise en équivalence de 2 906,9 M$ CA.', 1009001],
    ['2026-07-31', '6-K', ACC_6K, 'd125942dex991.htm', 'q2-6k-pr__d125942dex991.htm',
      'Communiqué des résultats du deuxième trimestre 2026 (31 juillet 2026, montants en dollars canadiens) : résultat net de 25 M$ CA et excédent brut ajusté de 391 M$ CA pour le trimestre, en recul sur un an, en partie sur une contribution moindre de Westinghouse ; commentaire de la direction sur le marché de l’uranium et les contrats à long terme.', 1009001],
    ['2026-07-31', '6-K', ACC_6K, 'd125942dex992.htm', 'q2-6k-mda__d125942dex992.htm',
      'Rapport de gestion du trimestre clos le 30 juin 2026 : 435 532 978 actions ordinaires en circulation ; excédent brut ajusté (non normalisé) de 899 M$ CA pour le premier semestre 2026 ; trésorerie d’environ 1,1 Md$ CA et dette totale d’environ 1,0 Md$ CA ; capacité de financement par prospectus préalable de base et programme d’émission d’actions sur le marché (ATM).', 1009001],
    ['2026-03-19', '40-F', ACC_40F, 'd34605dex993.htm', 'fy25-40f-mda__d34605dex993.htm',
      'Rapport de gestion de l’exercice 2025 : excédent brut ajusté consolidé (non normalisé, Westinghouse compris) de 1 929 M$ CA (contre 1 531 M$ CA en 2024) ; segments uranium, services de combustible et Westinghouse ; capacité de financement par prospectus préalable de base et programme d’émission d’actions sur le marché.', 1009001],
    ['2026-03-19', '40-F', ACC_40F, 'd34605dex991.htm', 'fy25-40f-aif__d34605dex991.htm',
      'Notice annuelle 2025 : description des activités (uranium, services de combustible, participation de 49 % dans Westinghouse aux côtés de Brookfield), des actifs miniers canadiens et des facteurs de risque ; mention du prospectus préalable de base et du programme d’émission d’actions sur le marché comme sources de financement possibles.', 1009001],
  ],
  needles: {
    rev: [1, ['Revenue from products and services', '1,659,137', '1,666,448']],
    ni: [1, ['Net earnings', '155,961', '390,638']],
    ebit: [1, ['Earnings from operations', '247,976', '351,763']],
    da: [1, ['Depreciation and amortization', '139,257', '147,073']],
    bal: [1, ['Cash and cash equivalents', '1,112,718', 'Long-term debt', '996,750']],
    annual: [0, ['3,481,933', '618,142', '589,542', '293,094', '1,114,860']],
    shares: [3, ['435,532,978', 'common shares']],
    adjebitda: [3, ['adjusted EBITDA', '899']],
    adjebitdaFY: [4, ['Adjusted EBITDA', '1,929']],
    atm: [5, ['at-the-market', 'base shelf']],
  },
  sectionDocs: { verdict: [1, 0, 3], business: [5, 4, 1], news: [2, 1], earnings: [1, 3], capitalStructure: [1, 5, 3], filingsReview: [0, 1, 2, 3, 4, 5], risks: [4, 1, 5], globalScore: [4], meta: [1], disclaimer: [1], macro: [4], options: [1], social: [1], header: [1], shortInterest: [1], insiders: [1] },
  score: { business: 30, technical: 4, capital: 4, calendar: 0, dilution: -3, risk: 8 },
  peers: true,
  peerFicheSha: {},
  shares: { value: 435532978, doc: 3 },
  route: (p, { prov, dep, B, TXP }) => {
    if (/^news\.[13]\./.test(p)) return prov('bars', B, 'Ouverture et clôture lues sur les barres certifiées ; variations calculées de clôture à clôture ; comparaison avec les pairs sur la même séance.', [dep('comparison', '')]);
    // L'agrégat d'initiés de cet émetteur expose recent_trades (et non un tableau transactions) : on pointe le nœud lui-même, qui résout.
    if (p === 'insiders.signal') return prov('insiders', TXP == null ? '' : TXP, 'Transactions d’initiés relevées dans le flux officiel ; couverture partielle pour un émetteur canadien (déclarations SEDI plutôt que formulaires 4 systématiques).', [dep('sec', '')]);
    return null;
  },
  riskScoreReason: 'Jugement qualitatif sur dix : titre payé environ soixante-huit fois son EBITDA d’exploitation strict des douze derniers mois (et ≈ vingt-huit fois l’excédent brut ajusté publié, Westinghouse compris) pour une croissance du chiffre d’affaires à un chiffre, un résultat net rendu volatil par la mise en équivalence de Westinghouse et les dérivés, une exposition thématique concentrée au complexe nucléaire et une amplitude journalière élevée ; atténué par une trésorerie nette positive, l’absence de dilution constatée et une position industrielle dominante.',
  compose: c => {
    const { fr, usd, pct, sgn, close, prev, bars, N, tech, st, M, adv, ret, G$, marketCap, ev, scn, lv, entry, stop, tp1, tp2, abandon, cap, rr1, rr2, riskAtr, sizeExample, ref, market, docs, raw, peerStat } = c;
    const gs = c.gapStats(cap - entry), bufAtr = (cap - entry) / tech.atr14, blocked = gs.up / gs.total * 100;
    const bufPct = (cap / entry - 1) * 100, bk = c.breakoutStats(bufPct), rt = c.retestStats(bufPct, (1 - stop / entry) * 100);
    const cmp = raw.comparison_bars.data.items[0].results[0].data;
    const dr = (sym, d) => { const b = cmp.find(x => x.symbol === sym).bars, i = b.findIndex(x => x[0] === d); return pct(b[i][4], b[i - 1][4]); };
    const bar = d => bars.find(b => b[0] === d);
    const d0908 = bar('2026-09-08'), d0925 = bar('2026-09-25'), d0826 = bar('2026-08-26');
    const win = bars.slice(Math.max(0, N - 251), N + 1); let hi = -1, lo = 1e9, hiD, loD;
    for (const b of win) { if (b[2] > hi) { hi = b[2]; hiD = b[0]; } if (b[3] < lo) { lo = b[3]; loD = b[0]; } }
    const y0 = bars.find(b => b[0] >= '2026-01-02'), ytd = pct(close, y0[4]);
    const evRev = ev / G$.rev, evEbitda = ev / G$.ebitda, opMargin = G$.ebit / G$.rev * 100, netMargin = G$.ni / G$.rev * 100;
    const pe = marketCap / G$.ni, netCash = G$.cash - G$.debt;
    const adjEbitdaFyUsd = ADJ_EBITDA_FY25_CAD / FX, evAdj = ev / adjEbitdaFyUsd;
    const cegEv = peerStat('CEG'), dEv = peerStat('D'), dukEv = peerStat('DUK');
    const ext20 = pct(close, tech.ema20);
    const big = Math.floor(1000 / (cap - stop));
    return {
      meta: { lang: 'fr', dir: 'ltr', level: 'intermediate', tags: ['us', 'energy', 'commodity', 'materials', 'nucleaire', 'trade-idea'], grade: 'C', date: '2026-09-25', dateDisplay: '25 septembre 2026', version: 3, status: 'watch', assetType: 'stock', levelsCloseDate: c.REF,
        description: 'Cameco, premier producteur d’uranium coté (émetteur canadien, IFRS, comptes en CAD). Douze mois au 30 juin 2026 convertis en USD au taux du 30/06 (1,4210) : 2,45 Md$ de revenus, EBITDA d’exploitation 0,56 Md$, trésorerie nette positive. Titre à 88,05 $, cher sur tous les multiples. Surveiller.',
        ogDescription: 'CCJ : douze mois au 30/06/2026 (comptes CAD convertis en USD au taux 1,4210) — 2,45 Md$ de revenus, 68× l’EBITDA d’exploitation, 28× l’excédent ajusté publié. Titre 88,05 $, surveiller.',
        lastMcpRefresh: raw.status.captured_at, levelsVerifiedAt: raw.status.captured_at,
        statusHistory: [...(c.archive.meta.statusHistory || []), { at: raw.status.captured_at, from: c.archive.meta.status || 'stopped', to: 'watch', note: 'refonte v3 harnachée du 25 septembre : émetteur étranger canadien IFRS (40-F/6-K) via agrégats de dépôt primaire convertis en USD au taux Banque du Canada du 30 juin 2026 (1,4210), base douze mois glissants au 30 juin, douze comparables uranium/nucléaire propres', close }] },
      header: { ticker: 'CCJ', name: 'Cameco Corporation', exchange: 'NYSE', sector: 'Uranium et combustible nucléaire', price: close, changePct: pct(close, prev),
        badges: [{ text: 'SURVEILLER — RECLASSEMENT AU-DESSUS DE LA FOURCHETTE DE MI-SEPTEMBRE', color: 'blue' }, { text: 'Premier producteur d’uranium coté', color: 'purple' }, { text: 'Comptes en CAD, cours en USD', color: 'amber' }],
        metrics: { marketCap: fr(marketCap / 1e9, 1) + ' Md$', volume: fr(bars[N][5] / 1e6, 2) + ' M', evEbitda: fr(evEbitda, 0) + '×' }, halalStatus: 'unknown' },
      verdict: { score: 43, conviction: 'Low', bias: 'Neutral',
        confidence: 'Score éditorial non prédictif. Les chiffres d’entreprise sont lus dans les états financiers IFRS des dépôts primaires (40-F 2025 et 6-K du 31 juillet 2026), publiés en dollars canadiens et convertis en dollars américains au taux daté du 30 juin 2026 (1,4210) ; les niveaux, sur le close certifié du 25 septembre.',
        summary: 'Cameco est le premier producteur d’uranium coté au monde et le moyen le plus direct de jouer la relance nucléaire en actions. Le débat ne porte pas sur la qualité de l’actif, réelle, mais sur le prix payé. Attention à la devise : Cameco publie en dollars canadiens, cours et capitalisation en dollars américains. Convertis au taux de la Banque du Canada du 30 juin (1,4210), les douze mois glissants au 30 juin 2026 donnent ' + fr(G$.rev / 1e9, 2) + ' Md$ de revenus, ' + fr(G$.ebit / 1e6, 0) + ' M$ de résultat d’exploitation et ' + fr(G$.ni / 1e6, 0) + ' M$ de résultat net. Au close du 25 septembre, ' + usd(close) + ' (' + sgn(pct(close, prev), 1) + '), le titre capitalise environ ' + fr(marketCap / 1e9, 0) + ' Md$, soit ' + fr(evEbitda, 0) + ' fois son EBITDA d’exploitation strict et ' + fr(evRev, 1) + ' fois ses revenus. Ce ' + fr(evEbitda, 0) + '× exclut la quote-part de Westinghouse (49 %, mise en équivalence), pourtant comptée dans la capitalisation ; sur l’excédent brut ajusté publié, la valeur d’entreprise ressort plutôt vers ' + fr(evAdj, 0) + ' fois. Dans les deux cas, une prime forte pour une croissance à un chiffre. Le titre a chuté d’environ ' + fr(Math.abs(pct(close, hi)), 0) + ' % depuis son sommet de janvier (' + usd(hi) + ') et reste cher après cette baisse — c’est la difficulté du dossier. Statut surveiller : pas d’entrée tant que le cours n’a pas reclassé la fourchette de la mi-septembre.',
        whyBuy: [
          'Position industrielle unique : premier producteur d’uranium coté, présent sur toute la chaîne du combustible, avec des actifs canadiens difficiles à répliquer.',
          'Bilan sain : ' + fr(G$.cash / 1e9, 2) + ' Md$ de trésorerie contre ' + fr(G$.debt / 1e9, 2) + ' Md$ de dette (au taux du 30/06), soit une trésorerie nette positive et aucune contrainte de financement.',
          'Aucune dilution constatée : le nombre d’actions est resté quasi stable, à 435,5 M ; le financement du modèle n’a pas reposé sur l’émission d’actions.',
          'Participation de 49 % dans Westinghouse, mise en équivalence : un actif technologique dont un projet d’introduction en bourse pourrait un jour révéler la valeur.'],
        whyAvoid: [
          'Environ ' + fr(evEbitda, 0) + ' fois l’EBITDA d’exploitation strict, ' + fr(evAdj, 0) + ' fois l’excédent brut ajusté publié et ' + fr(evRev, 1) + ' fois les revenus : une prime forte pour une croissance à un chiffre.',
          'Bien plus cher que les services publics nucléaires qui achètent son uranium : Constellation se paie ' + fr(cegEv, 0) + ' fois son EBITDA, Dominion ' + fr(dEv, 0) + ' fois, Duke ' + fr(dukEv, 0) + ' fois.',
          'Résultat net volatil et bruité : porté par la mise en équivalence de Westinghouse et des réévaluations de dérivés, il chute de ' + fr(390.6, 1) + ' à ' + fr(156.0, 1) + ' M$ CA d’un semestre à l’autre.',
          'Exposition thématique concentrée : cette ligne double une exposition nucléaire ou électricité déjà présente dans un portefeuille, elle ne s’ajoute pas comme une idée isolée.',
          'Titre en repli depuis son sommet d’août et sous ses moyennes courtes ; le rebond n’est pas confirmé.'],
        controlChecklist: [
          { label: 'Historique de cours', status: 'pass', statusLabel: 'Trois cents séances continues', evidence: 'Série quotidienne certifiée au close du 25 septembre.', action: 'Niveaux et indicateurs recalculés sur cette seule série.' },
          { label: 'Comptes et devise', status: 'warn', statusLabel: 'Émetteur canadien, IFRS, CAD', evidence: 'Cameco dépose 40-F/6-K et publie en dollars canadiens ; aucun agrégat us-gaap XBRL. Les chiffres sont lus dans les états IFRS des dépôts primaires puis convertis en USD au taux Banque du Canada du 30 juin 2026 (1,4210).', action: 'Lire tous les ratios comme des mesures entièrement en USD, jamais un mélange CAD/USD.' },
          { label: 'EBITDA et Westinghouse', status: 'warn', statusLabel: 'Deux mesures d’EBITDA', evidence: 'L’EBITDA d’exploitation strict exclut la quote-part de Westinghouse (mise en équivalence), pourtant présente dans la capitalisation ; l’excédent brut ajusté publié l’inclut.', action: 'Comparer le ' + fr(evEbitda, 0) + '× strict et le ' + fr(evAdj, 0) + '× ajusté, jamais l’un sans l’autre.' }] },
      business: { theme: 'Uranium et combustible nucléaire',
        overview: '<p>Cameco extrait, raffine et vend de l’uranium, et fournit des services au parc nucléaire mondial. C’est un émetteur étranger canadien coté au NYSE : il publie ses comptes en normes IFRS et en dollars canadiens, via des formulaires 40-F annuels et 6-K intermédiaires, et non les 10-K/10-Q américains. Le groupe s’organise autour de trois ensembles : l’uranium (extraction et vente de concentré), les services de combustible (raffinage, conversion, fabrication) et une participation de 49 % dans Westinghouse Electric, détenue aux côtés de Brookfield et mise en équivalence.</p><p>La thèse de fond est connue : la demande d’électricité pilotable augmente, les centres de données consomment davantage, plusieurs pays relancent des programmes nucléaires, et l’offre d’uranium primaire met des années à réagir. Cameco est le moyen le plus direct de s’y exposer en actions cotées.</p><p>Ce que la thèse ne dit pas, c’est à quel prix elle est déjà payée. Sur douze mois glissants au 30 juin 2026, le chiffre d’affaires est de ' + fr(G$.rev / 1e9, 2) + ' Md$ (converti au taux du 30/06) et n’a progressé que de 11 % sur l’exercice 2025 ; le premier semestre 2026 a même reculé, à ' + fr(1659.1, 1) + ' M$ CA contre ' + fr(1666.4, 1) + ' M$ CA un an plus tôt. Un contrat d’uranium se négocie sur des années, à des prix largement fixés à l’avance : la remontée du cours au comptant met du temps à atteindre le compte de résultat. C’est un avantage en bas de cycle et une limite en haut.</p>',
        moat: 'Réel mais lent. Ouvrir une mine d’uranium prend une décennie et demande des autorisations que peu d’acteurs obtiennent ; la base d’actifs canadienne de Cameco est difficile à répliquer, et la relation client dans le nucléaire se compte en décennies. Ce sont de vraies barrières, mais elles protègent la position concurrentielle, pas le rythme auquel les prix de contrat se répercutent dans les comptes — et c’est ce décalage que la valorisation actuelle paraît ignorer.',
        segments: [
          { name: 'Uranium', revenue: 'Cœur du modèle', pct: 'Segment principal', description: 'Extraction et vente de concentré, sur contrats pluriannuels qui lissent l’exposition au cours au comptant.' },
          { name: 'Services de combustible', revenue: '562 M$ CA de revenus au premier semestre 2026', pct: 'Appoint', description: 'Raffinage, conversion et fabrication : activité de péage, moins cyclique que l’extraction.' },
          { name: 'Westinghouse (49 %, mise en équivalence)', revenue: 'Portée en participation, pas en revenus consolidés', pct: 'Hors chiffre d’affaires', description: 'Technologie de réacteurs et services aux centrales, détenue avec Brookfield ; sa contribution passe par la ligne « quote-part des résultats », hors résultat d’exploitation.' }],
        sourceRefs: [ref(5), ref(4), ref(1)],
        coverageMatrix: [
          { facet: 'Cours et historique', status: 'COUVERT', decision: 'Trois cents séances continues, close certifié ; base des niveaux et des indicateurs.' },
          { facet: 'Comptes et agrégats', status: 'COUVERT — PRIMAIRE IFRS (CAD→USD)', decision: 'Agrégats lus dans le 40-F 2025 et le 6-K du 31 juillet 2026 ; douze mois glissants au 30 juin 2026 ; convertis en USD au taux Banque du Canada du 30/06 (1,4210) ; aucun companyfacts us-gaap n’existe pour cet émetteur.' },
          { facet: 'Capital et dette', status: 'COUVERT — PRIMAIRE', decision: 'Emprunts à long terme, trésorerie et nombre d’actions lus au bilan intermédiaire ; capacité d’émission sur le marché (ATM) sous prospectus de base.' },
          { facet: 'Comparables et transmission', status: 'COUVERT — LOCAL', decision: 'Corrélations recalculées sur barres certifiées ; douze comparables uranium/nucléaire propres (dix pairs élagués pour géométrie de barre ou discontinuité).' },
          { facet: 'Position vendeuse et coût d’emprunt', status: 'NON EXPLOITABLE', decision: 'Le snapshot ne fournit pas de position vendeuse exploitable ; le coût d’emprunt a échoué à la collecte (fournisseur en échec). Aucune thèse de rachat forcé n’est établie.' },
          { facet: 'Options et sentiment social', status: 'NON EXPLOITABLE', decision: 'Chaîne d’options non servie à la collecte ; ni Reddit ni tendances de recherche pour ce titre.' }] },
      news: [
        { date: '2026-07-31', title: 'Résultats du deuxième trimestre 2026 : ' + fr(25, 0) + ' M$ CA de résultat net, excédent brut ajusté de ' + fr(391, 0) + ' M$ CA', impact: 'neutral', detail: 'Le 6-K du 31 juillet présente un résultat net trimestriel de 25 M$ CA et un excédent brut ajusté de 391 M$ CA, en recul sur un an, en partie sur une contribution moindre de Westinghouse. Sur le semestre, le résultat net tombe à 156,0 M$ CA contre 390,6 M$ CA un an plus tôt : la baisse tient surtout à la mise en équivalence de Westinghouse et aux réévaluations de dérivés, pas à l’exploitation courante.', source: 'Cameco — SEC', sourceUrl: docs[2].url },
        { date: '2026-08-26', title: 'Sommet du rebond d’été à ' + usd(d0826[2]) + ', puis repli', impact: 'neutral', detail: 'Le titre touche ' + usd(d0826[2]) + ' en séance le 26 août, sommet du rebond estival, avant de refluer d’environ ' + fr(Math.abs(pct(close, d0826[2])), 0) + ' % jusqu’au 25 septembre. Le complexe nucléaire a mené la hausse comme la baisse.', source: 'Barres certifiées', sourceUrl: c.evidenceUrl },
        { date: '2026-09-08', title: 'Dernier plus haut à ' + usd(d0908[2]) + ' avant la glissade de septembre', impact: 'neutral', detail: 'Le 8 septembre, le titre inscrit ' + usd(d0908[2]) + ' en séance (clôture ' + usd(d0908[4]) + '), dernier plus haut avant une glissade continue vers ' + usd(close) + '. Constellation fait ' + sgn(dr('CEG', '2026-09-08'), 2) + ' et Duke ' + sgn(dr('DUK', '2026-09-08'), 2) + ' la même séance : le mouvement accompagne le complexe nucléaire.', source: 'Barres certifiées', sourceUrl: c.evidenceUrl },
        { date: '2026-09-25', title: 'Clôture à ' + usd(close) + ', près du bas de la fourchette récente', impact: 'neutral', detail: 'Le titre ouvre à ' + usd(d0925[1]) + ' et clôture à ' + usd(close) + ' (' + sgn(pct(close, prev), 2) + '), tout près de son plus bas de la veille. Denison fait ' + sgn(dr('DNN', '2026-09-25'), 2) + ' et Uranium Energy ' + sgn(dr('UEC', '2026-09-25'), 2) + ' la même séance ; le repli est partagé par le complexe uranium.', source: 'Barres certifiées', sourceUrl: c.evidenceUrl }],
      fundamentals: { rows: [
          { metric: 'Taux de change appliqué (CAD→USD)', value: '1,4210', signal: 'Taux de change quotidien de la Banque du Canada du 30 juin 2026 (série FXUSDCAD) ; USD = CAD / 1,4210. Appliqué à tous les agrégats pour éviter tout mélange de devises', signalColor: 'blue', _src: 4 },
          { metric: 'Chiffre d’affaires — douze mois glissants', value: fr(G$.rev / 1e9, 2) + ' Md$', signal: '3 474,6 M$ CA convertis au taux du 30/06 ; exercice 2025 + premier semestre 2026 − premier semestre 2025', signalColor: 'blue', _src: 'gaap' },
          { metric: 'Chiffre d’affaires de l’exercice 2025', value: fr(3481933 / 1e3 / FX, 0) + ' M$', signal: '3 481,9 M$ CA, en hausse de 11,0 % sur un an (3 135,8 M$ CA en 2024)', signalColor: 'green', _src: 0 },
          { metric: 'Résultat d’exploitation — douze mois', value: fr(G$.ebit / 1e6, 0) + ' M$', signal: '514,4 M$ CA ; marge d’exploitation de ' + fr(opMargin, 0) + ' %', signalColor: 'amber', _src: 'gaap' },
          { metric: 'EBITDA d’exploitation — douze mois', value: fr(G$.ebitda / 1e6, 0) + ' M$', signal: 'Résultat d’exploitation + amortissements (285,3 M$ CA) ; EXCLUT la quote-part de Westinghouse (mise en équivalence)', signalColor: 'amber', _src: 'gaap' },
          { metric: 'Excédent brut ajusté publié (2025, Westinghouse compris)', value: fr(adjEbitdaFyUsd / 1e9, 2) + ' Md$', signal: '1 929 M$ CA publiés par Cameco (mesure non normalisée) ; l’écart avec l’EBITDA d’exploitation vient surtout de la quote-part de Westinghouse', signalColor: 'blue', _src: 4 },
          { metric: 'Résultat net — douze mois glissants', value: fr(G$.ni / 1e6, 0) + ' M$', signal: '354,9 M$ CA ; volatil, porté par la mise en équivalence de Westinghouse et les réévaluations de dérivés', signalColor: 'amber', _src: 'gaap' },
          { metric: 'Trésorerie au 30 juin 2026', value: fr(G$.cash / 1e9, 2) + ' Md$', signal: '1 112,7 M$ CA de trésorerie et équivalents', signalColor: 'green', _src: 'gaap' },
          { metric: 'Dette au 30 juin 2026', value: fr(G$.debt / 1e9, 2) + ' Md$', signal: '996,8 M$ CA d’emprunts à long terme, hors obligations locatives ; trésorerie nette positive de ' + fr(netCash / 1e6, 0) + ' M$', signalColor: 'green', _src: 'gaap' },
          { metric: 'EV/EBITDA d’exploitation strict', value: fr(evEbitda, 1) + '×', signal: 'Valeur d’entreprise (enterprise value, entièrement en USD) au close du 2026-09-25 sur EBITDA d’exploitation douze mois glissants (trailing, au 30 juin 2026) ; élevé car Westinghouse est dans la valeur d’entreprise mais pas dans cet EBITDA', signalColor: 'red', source: 'Clôture certifiée et dépôts primaires', comparison: 'Versus les services publics nucléaires qui achètent l’uranium : Constellation à ' + fr(cegEv, 1) + '×, Dominion à ' + fr(dEv, 1) + '×, Duke à ' + fr(dukEv, 1) + '× (statistiques courantes, non point-in-time). Les producteurs d’uranium comparables (Denison, Uranium Energy, Energy Fuels) affichent un EBITDA négatif : Cameco est le seul grand nom rentable du complexe.', _src: 'market', _peers: ['CEG', 'D', 'DUK'], _peerField: 'enterpriseToEbitda' },
          { metric: 'EV/excédent brut ajusté publié (2025)', value: fr(evAdj, 1) + '×', signal: 'Valeur d’entreprise (enterprise value) sur l’excédent brut ajusté 2025 publié par Cameco (1 929 M$ CA, Westinghouse compris) : la mesure la plus proche de la façon dont le marché valorise le groupe entier', signalColor: 'red', source: 'Excédent brut ajusté 2025 publié (40-F) et clôture certifiée', comparison: 'Base : exercice 2025 (FY2025) publié au 40-F ; valeur d’entreprise au close du 2026-09-25.', _src: 4 },
          { metric: 'EV/chiffre d’affaires — douze mois', value: fr(evRev, 1) + '×', signal: 'Valeur d’entreprise (enterprise value) sur revenus douze mois glissants (trailing) au 30 juin 2026, entièrement en USD ; un ratio courant qui mélangeait EV en USD et revenus en CAD tomberait à tort vers 11×', signalColor: 'red', source: 'Clôture certifiée et dépôts primaires', comparison: 'Base : douze mois glissants au 30 juin 2026 (FY2025 + S1 2026 − S1 2025).', _src: 'market' },
          { metric: 'Cours sur bénéfice — douze mois', value: fr(pe, 0) + '×', signal: 'Bénéfice net glissant (trailing) au 30 juin 2026, bas et bruité (Westinghouse, dérivés) : ce ratio est peu fiable sur ce dossier et surestime la cherté', signalColor: 'amber', source: 'Clôture certifiée et dépôts primaires', comparison: 'Base : résultat net douze mois glissants au 30 juin 2026 ; peu significatif ici.', _src: 'market' },
          { metric: 'Marge nette — douze mois', value: fr(netMargin, 0) + ' %', signal: 'Marge d’exploitation de ' + fr(opMargin, 0) + ' % ; l’écart tient aux éléments financiers et à la mise en équivalence', signalColor: 'amber', _src: 'gaap' },
          { metric: 'Actions ordinaires en circulation', value: '435 532 978', signal: 'Au 30 juillet 2026 (rapport de gestion) ; quasi stable, aucune dilution constatée', signalColor: 'green', _src: 3 },
          { metric: 'Flux de trésorerie d’exploitation (exercice 2025)', value: fr(1408432 / 1e3 / FX, 0) + ' M$', signal: '1 408,4 M$ CA en 2025 ; investissements de 333,0 M$ CA la même année', signalColor: 'green', _src: 0 }],
        sourceRefs: [ref(0), ref(1), ref(4), market('agrégats et statistiques comparables')] },
      earnings: { quarters: [],
        beatNote: 'Deuxième trimestre 2026 (6-K du 31 juillet) : résultat net de 25 M$ CA, excédent brut ajusté de 391 M$ CA ; sur le semestre, chiffre d’affaires de 1 659,1 M$ CA (contre 1 666,4 M$ CA), résultat d’exploitation de 248,0 M$ CA (contre 351,8 M$ CA), résultat net de 156,0 M$ CA (contre 390,6 M$ CA). L’exercice 2025 (40-F) affichait 3 481,9 M$ CA de revenus, 618,1 M$ CA de résultat d’exploitation et 589,5 M$ CA de résultat net. Perspective (outlook) : l’émetteur ne publie pas de prévision chiffrée standardisée ; le chiffre d’affaires reste porté par le carnet de contrats à prix plancher et la remontée des prix de l’uranium, la répercussion des prix de contrat étant le fil à suivre pour le second semestre. Émetteur étranger : publication trimestrielle via 6-K, sans consensus standardisé vérifiable dans les états ouverts. Aucune date de résultats confirmée par l’émetteur ni signalée dans l’horizon du plan (résultats du troisième trimestre attendus courant novembre).',
        nextEarnings: 'Date non confirmée par l’émetteur ; cadence trimestrielle (résultats du troisième trimestre attendus courant novembre). Aucun événement de résultats n’est signalé dans l’horizon du plan par le calendrier collecté.',
        sourceRefs: [ref(1), ref(3)] },
      capitalStructure: { sharesOutstanding: '435 532 978 actions ordinaires en circulation au 30 juillet 2026 (rapport de gestion du 6-K du 31 juillet) ; quasi stable sur un an.',
        sharesAuthorized: 'Capacité d’émission : prospectus préalable de base et programme d’émission d’actions sur le marché (ATM) disponibles comme sources de financement, à la main de la société.', dilutionRisk: 'low',
        shareHistory: 'Le nombre d’actions ordinaires est resté quasi stable, à 435 532 978 au 30 juillet 2026 : aucune dilution n’a été constatée sur la période. Sur une base entièrement diluée, l’écart reste négligeable : Cameco ne porte ni bons de souscription ni obligations convertibles significatifs en circulation, de sorte que le nombre d’actions de base et le nombre entièrement dilué sont quasi identiques ; seul un régime d’intéressement en actions usuel les sépare marginalement. Le financement du modèle n’a pas reposé sur l’émission d’actions — la trésorerie (1,11 Md$ CA au 30 juin) dépasse la dette (996,8 M$ CA d’emprunts à long terme), soit une trésorerie nette positive. Point de vigilance et non de constat : Cameco conserve un prospectus préalable de base et un programme d’émission d’actions sur le marché (ATM), qui lui donnent la capacité de lever des fonds propres au fil de l’eau. Rien n’indique qu’il ait été tiré ; un programme au fil de l’eau se tire dans la force, pas dans la faiblesse. Le risque de dilution est donc faible aujourd’hui, sans être nul en cas de reprise marquée du cours.',
        warrants: [], atm: { active: true, authorized: 'Programme d’émission d’actions sur le marché (ATM) sous prospectus préalable de base, disponible comme source de financement', used: 'Aucun tirage constaté ; nombre d’actions quasi stable', remaining: 'Capacité non détaillée dans les dépôts ouverts' },
        sourceRefs: [ref(1), ref(5), ref(3)] },
      filingsReview: { summary: 'Six dépôts décisionnels ouverts et hachés : les états financiers, le rapport de gestion et la notice annuelle du 40-F 2025, puis les états financiers, le rapport de gestion et le communiqué du 6-K du 31 juillet 2026. Ils montrent un producteur d’uranium rentable et peu endetté, à la croissance modeste et au résultat net rendu volatil par la mise en équivalence de Westinghouse, dont les comptes sont tenus en dollars canadiens.',
        filings: docs.map(d => ({ date: d.date, form: d.form, accession: d.accession, finding: d.finding, url: d.url })),
        contrarianRisks: [
          'La croissance du chiffre d’affaires est modeste et le semestre a reculé : les contrats pluriannuels retardent la traduction d’une hausse de l’uranium dans les comptes.',
          'Le résultat net dépend fortement de Westinghouse (mise en équivalence) et des réévaluations de dérivés : il peut s’inverser d’un trimestre à l’autre.',
          'La valorisation intègre déjà plusieurs années de trajectoire favorable ; une compression des multiples du complexe nucléaire ferait mal.',
          'La capacité d’émission d’actions sur le marché existe : une reprise marquée du cours est le moment où son utilisation deviendrait probable.'] },
      technicals: { rsi14: +tech.rsi14.toFixed(2), macd: +tech.macd.toFixed(2), macdSignal: +tech.macdSignal.toFixed(2), ema20: +tech.ema20.toFixed(2), ema50: +tech.ema50.toFixed(2), ema200: +tech.ema200.toFixed(2),
        ma50Type: 'EMA', ma200Type: 'EMA', ma50Available: true, ma200Available: true, atr14: +tech.atr14.toFixed(2),
        badges: [fr(Math.abs(pct(close, hi)), 0) + ' % sous le sommet de janvier', fr(Math.abs(pct(close, d0826[2])), 0) + ' % sous le rebond d’août', 'ATR de ' + usd(tech.atr14)],
        supports: [lv('s1'), stop, lv('s2')], resistances: [lv('r1'), lv('r2'), entry],
        setupNote: 'Le titre clôture à ' + usd(close) + ', ' + fr(ext20, 1) + ' % par rapport à sa moyenne à vingt séances, après un repli d’environ ' + fr(Math.abs(pct(close, d0826[2])), 0) + ' % depuis le rebond d’août (' + usd(d0826[2]) + ') et ' + fr(Math.abs(pct(close, hi)), 0) + ' % sous le sommet de janvier (' + usd(hi) + '). Avant activation, aucune entrée ; une clôture sous ' + usd(abandon) + ', le plus bas du 25 septembre, abandonne le scénario. Activation sur une clôture au-dessus de $' + entry.toFixed(2) + ', le plus haut du 22 septembre, qui reclasserait la fourchette de la mi-septembre. Après activation, stop sous $' + stop.toFixed(2) + ', le plus bas du 23 septembre, soit ' + fr(riskAtr, 2) + ' ATR sous le déclencheur. Supports : ' + usd(stop) + ', ' + usd(lv('s1')) + ' et ' + usd(lv('s2')) + '. Résistances : ' + usd(entry) + ', ' + usd(lv('r1')) + ' et ' + usd(lv('r2')) + ' ; au-delà, la zone du rebond d’août, ' + usd(d0826[2]) + '.',
        wyckoff: 'Non utilisé : le profil de volume n’est pas exploité dans ce dossier.',
        sourceRefs: [market('barres quotidiennes et indicateurs recalculés')] },
      options: { callOI: 'Non exploitable', putOI: 'Non exploitable', cpRatio: 'Non exploitable', maxPain: 'Non exploitable', ivMean: 'Non exploitable', skew: 'Chaîne d’options non servie à la collecte du 28 septembre', unusual: 'Aucune activité inhabituelle qualifiée', sourceRefs: [market('options')] },
      shortInterest: { siPct: 'Non exploitable', daysToCover: fr(st.shortRatio, 2) + ' jours (ratio du snapshot)', ctb: 'Coût d’emprunt indisponible à la collecte (fournisseur en échec)', trend: 'Le snapshot ne fournit pas de position vendeuse exploitable pour ce titre (part du flottant non renseignée) et le coût d’emprunt a échoué à la collecte. Aucune thèse de rachat forcé n’est établie ; sur une valeur de cette taille et de cette liquidité, la position vendeuse n’est de toute façon pas un moteur du dossier.', squeezeScore: 'Non quantifié faute de données', sourceRefs: [market('positions vendeuses — snapshot incomplet')] },
      insiders: { signal: 'Aucun solde net d’initiés affirmé : la couverture officielle des transactions d’initiés est partielle pour un émetteur étranger canadien, dont les dirigeants déclarent sous le régime canadien (SEDI) plutôt que par formulaires 4 systématiques. Aucun mouvement d’initié décisif n’est établi sur la période.',
        recentTransactions: [],
        sourceRefs: [market('transactions d’initiés — couverture partielle')] },
      macro: { indicators: [{ name: 'Clôture de référence', value: c.REF, signal: usd(close) + ', séance complète' }, { name: 'Rendement cinq séances', value: sgn(ret(5)), signal: 'Descriptif' }, { name: 'Rendement vingt et une séances', value: sgn(ret(21)), signal: 'Descriptif' }],
        regime: 'neutral', impact: 'Cameco vit de la demande d’uranium des exploitants de centrales nucléaires et du redémarrage des programmes atomiques. Le moteur de fond — électrification, centres de données, sécurité d’approvisionnement — reste intact, mais il est lent : les contrats pluriannuels lissent les revenus et retardent l’effet d’une hausse du cours au comptant. Une compression des multiples de tout le complexe nucléaire, ou un ralentissement du calendrier de relance, toucherait un titre déjà payé cher.' },
      risks: { riskScore: 6, riskProfile: 'High',
        riskSummary: 'Le risque de Cameco n’est pas la qualité de l’actif, réelle, mais le prix payé et la lisibilité des comptes : environ ' + fr(evEbitda, 0) + ' fois l’EBITDA d’exploitation strict (' + fr(evAdj, 0) + ' fois l’excédent brut ajusté publié), une croissance à un chiffre, un résultat net brouillé par la mise en équivalence de Westinghouse, et une exposition thématique concentrée. Le bilan, lui, est solide.',
        riskCards: [
          { title: 'Valorisation en prime', severity: 'high', icon: 'fa-scale-balanced', points: ['Environ ' + fr(evEbitda, 0) + ' fois l’EBITDA d’exploitation strict et ' + fr(evAdj, 0) + ' fois l’excédent brut ajusté publié.', 'Bien plus cher que les services publics nucléaires (Constellation ' + fr(cegEv, 0) + '×, Duke ' + fr(dukEv, 0) + '×) pour une croissance à un chiffre.'], verdict: 'Une déception de croissance ou une compression des multiples du complexe ferait mal : la prime est intégralement dans le prix.' },
          { title: 'Devise et lisibilité des comptes', severity: 'medium', icon: 'fa-money-bill-trend-up', points: ['Comptes publiés en dollars canadiens, cours et capitalisation en dollars américains : tout ratio qui mélange les deux devises est faux.', 'L’EBITDA d’exploitation strict exclut Westinghouse, pourtant compté dans la valeur d’entreprise : deux mesures coexistent.'], verdict: 'Le dossier exige une discipline de devise et de périmètre ; les chiffres bruts de fournisseurs induisent en erreur.' },
          { title: 'Résultat net volatil', severity: 'medium', icon: 'fa-arrows-spin', points: ['Résultat net du semestre en chute, de 390,6 à 156,0 M$ CA sur un an.', 'La variation vient de la mise en équivalence de Westinghouse et des réévaluations de dérivés, pas de l’exploitation.'], verdict: 'Le bénéfice net et le cours sur bénéfice sont peu fiables ici : raisonner en exploitation et en excédent brut ajusté.' },
          { title: 'Concentration thématique et volatilité', severity: 'high', icon: 'fa-arrow-down-up-across-line', points: ['ATR de ' + usd(tech.atr14) + ' ; titre en repli de ' + fr(Math.abs(pct(close, d0826[2])), 0) + ' % depuis le rebond d’août.', 'Une ligne Cameco double une exposition nucléaire ou électricité déjà présente en portefeuille.'], verdict: 'Les écarts de plusieurs pour cent sont fréquents et la ligne ne diversifie pas : dimensionner sur la distance au stop.' }],
        pedagogy: 'Deux réflexes suffisent à ne pas se tromper sur Cameco. Le premier est la devise : les comptes sont en dollars canadiens, le cours en dollars américains ; un multiple qui compare une capitalisation en USD à des revenus en CAD paraît bon marché à tort. Tout est ramené ici au dollar américain, au taux daté du 30 juin (1,4210). Le second est le périmètre : l’EBITDA d’exploitation strict laisse de côté la participation de 49 % dans Westinghouse, alors que sa valeur est bien dans la capitalisation ; d’où un ' + fr(evEbitda, 0) + '× qui tombe vers ' + fr(evAdj, 0) + '× sur l’excédent brut ajusté publié, Westinghouse compris. Dans les deux lectures, le titre est cher pour une croissance modeste. La question utile n’est pas « Cameco est-il un bon actif ? » — il l’est — mais « à combien de fois ses résultats est-il raisonnable de l’acheter ? »' },
      tradeIdea: { status: 'watch', statusNote: 'Surveiller. Avant activation : aucune entrée ; une clôture sous ' + usd(abandon) + ' abandonne le scénario. Activation : clôture au-dessus de ' + usd(entry) + ', puis achat à l’ouverture suivante seulement sous ' + usd(cap) + ', ou par ordre limité à ce plafond pendant trois séances, annulé après une clôture sous ' + usd(entry) + ' et jamais laissé actif sur une ouverture sous ' + usd(stop) + '. Après activation : stop sous ' + usd(stop) + '. Au close du 25 septembre, le titre est sous le déclencheur : le plan n’est pas activé.',
        entry, stop, tp1, tp2,
        stopPct: pct(stop, entry).toFixed(1) + '%', tp1Pct: '+' + pct(tp1, entry).toFixed(1) + '%', tp2Pct: '+' + pct(tp2, entry).toFixed(1) + '%',
        rr: '1:' + rr1.toFixed(2) + ' TP1 / 1:' + rr2.toFixed(2) + ' TP2',
        entryNote: 'Déclencheur sur clôture au-dessus du plus haut du 22 septembre, pas sur un franchissement en séance. Entrée à l’ouverture suivante uniquement sous ' + usd(cap) + ' : au-delà, le R/R vers TP1 tomberait sous 1,5 avec le même stop. Ce plafond n’est qu’à ' + usd(cap - entry) + ' au-dessus du déclencheur, soit ' + fr(bufAtr, 2) + ' ATR. Mesure : sur les ' + gs.total + ' dernières séances, ' + gs.up + ' ouvertures ont dépassé la clôture de la veille de plus de ' + usd(cap - entry) + ', soit environ ' + fr(blocked, 0) + ' % ; l’écart d’ouverture médian, dans un sens ou dans l’autre, vaut ' + usd(gs.medAbs) + '. Sur la série, ' + bk.n + ' clôtures ont cassé un plus haut de vingt séances : ' + bk.inBand + ' ont fini à moins de ' + fr(bufPct, 2) + ' % au-dessus du niveau cassé, l’écart relatif du plafond, et ' + bk.buyable + ' ont ensuite ouvert sous ce seuil. Plan de repli : si l’ouverture dépasse le plafond, un ordre à cours limité à ' + usd(cap) + ', valable trois séances, garde le même R/R et le même stop ; il est annulé après toute clôture sous le déclencheur, ' + usd(entry) + ', n’est pas laissé actif à l’ouverture d’une séance sous le stop, ' + usd(stop) + ', ni si le stop est touché avant exécution. Rejoué avec ces bornes sur les ' + rt.miss + ' cassures non achetables à l’ouverture, l’ordre aurait été exécuté ' + rt.back + ' fois' + (rt.stopSame ? ', dont ' + rt.stopSame + ' avec le stop touché la même séance' : ', sans que le stop soit touché la même séance') + (rt.gapUnder ? ' ; ' + rt.gapUnder + ' fois retiré sur une ouverture sous le stop' : ' ; aucun retrait sur ouverture sous le stop') + '. Objectifs : TP1 à une hauteur de couloir au-dessus du déclencheur, TP2 à une fois et demie. Liquidité : environ ' + fr(adv / 1e6, 0) + ' M$ échangés par séance, médiane des vingt dernières. Exemple de taille, non personnalisé : avec un budget de perte de 100 $, le risque au plafond, ' + usd(cap - stop) + ' par action, donne ' + sizeExample + ' action' + (sizeExample > 1 ? 's' : '') + ' ; avec 1 000 $, ' + big + ' actions.',
        horizon: 'Dix à vingt séances après activation',
        thesis: 'Cameco est un actif de qualité à un prix élevé, pas une aubaine. Le bilan est sain et la position industrielle unique, mais le titre se paie environ ' + fr(evEbitda, 0) + ' fois son EBITDA d’exploitation (' + fr(evAdj, 0) + ' fois l’excédent brut ajusté publié) pour une croissance à un chiffre, et son résultat net est brouillé par Westinghouse. Rien n’oblige à courir après. Une clôture au-dessus de $' + entry.toFixed(2) + ' montrerait que les acheteurs reprennent la fourchette de la mi-septembre ; avant cela, une clôture sous ' + usd(abandon) + ' abandonne le dossier. Après activation, le stop sous $' + stop.toFixed(2) + ' limite le coût d’une fausse sortie. TP1 à ' + usd(tp1) + ' et TP2 à ' + usd(tp2) + '. Ne pas anticiper le déclencheur, ne pas acheter un gap au-dessus du plafond, et compter cette ligne dans une enveloppe thématique nucléaire, pas comme une idée isolée. Côté exécution : le titre est très liquide (plusieurs millions d’actions échangées par séance), donc le spread reste serré et le slippage minime à taille raisonnable ; le vrai risque d’exécution est le gap d’ouverture, pas la liquidité — dimensionner sur la distance au stop, pas sur une conviction de niveau.',
        catalysts: ['Le complexe nucléaire dans son ensemble : c’est lui qui a fait la baisse comme la hausse ; suivre les services publics nucléaires et les producteurs d’uranium avant tout élément propre à Cameco.', 'Les résultats du troisième trimestre, attendus courant novembre, et la mesure dans laquelle les prix de contrat commencent à se répercuter dans le chiffre d’affaires.', 'Toute avancée sur la valeur de la participation Westinghouse (par exemple un projet d’introduction en bourse) donnerait une référence de valorisation aujourd’hui implicite.'],
        invalidation: ['Avant activation : une clôture sous ' + usd(abandon) + ', bas du couloir, abandonne le scénario.', 'Après activation : une clôture sous ' + usd(stop) + ' invalide le trade.', 'Ouverture au-dessus de ' + usd(cap) + ' après la clôture de déclenchement : pas d’achat à l’ouverture ; seul l’ordre limité à ' + usd(cap) + ' reste valable trois séances.', 'Une émission d’actions sur le marché d’ampleur inattendue changerait l’équation de dilution et affaiblirait la thèse.'] },
      globalScore: { profile: 'Actif de qualité, valorisation élevée, croissance modeste',
        keyTakeawaysPositive: ['Premier producteur d’uranium coté, actifs canadiens difficiles à répliquer.', 'Trésorerie nette positive, aucune dilution constatée.', 'Moteur de fond intact : électrification et relance nucléaire.'],
        keyTakeawaysNegative: ['Environ ' + fr(evEbitda, 0) + ' fois l’EBITDA d’exploitation (' + fr(evAdj, 0) + ' fois l’excédent brut ajusté publié).', 'Croissance à un chiffre et résultat net brouillé par Westinghouse.', 'Exposition thématique concentrée et titre en repli.'],
        mindsetTip: 'Une thèse de fond juste ne dit rien du prix payé. Sur Cameco, deux disciplines évitent l’erreur : ramener tous les chiffres à une seule devise, et distinguer l’exploitation de la participation Westinghouse. La qualité de l’actif ne rend pas le multiple bon marché.' },
      social: { platforms: [], sourceRefs: [market('sentiment non retenu faute de mesure qualifiée')] },
      disclaimer: 'Document de recherche éducatif. Ni conseil financier, ni signal de trading. Statut surveiller : aucun ordre actif.',
    };
  },
  groups: [
    { name: 'Référence du complexe nucléaire', order: 1, transmission: 'Le plus grand exploitant de centrales nucléaires cotées mène le récit de la relance atomique : ses contrats d’électricité et sa demande de combustible orientent le sentiment de tout le complexe, uranium compris.', rows: [
      ['CEG', 'leader', 'Exploitant de centrales nucléaires', 'Premier producteur d’électricité nucléaire coté ; ses contrats avec les grands consommateurs fixent le ton de la thèse nucléaire et, par ricochet, de la demande d’uranium.']] },
    { name: 'Pairs directs — producteurs et développeurs d’uranium', order: 1, transmission: 'Mêmes gisements, même moteur de prix : leurs cours suivent le même cycle de l’uranium que Cameco, même si aucun n’est encore rentable.', rows: [
      ['DNN', 'direct_peer', 'Producteur et développeur d’uranium', 'Développeur canadien du même bassin ; suit directement le cycle de l’uranium, mais sans bénéfices établis.'],
      ['UEC', 'direct_peer', 'Producteur d’uranium américain', 'Producteur américain en montée en puissance ; exposé au même prix de l’uranium, EBITDA encore négatif.'],
      ['UUUU', 'direct_peer', 'Uranium et terres rares', 'Producteur diversifié uranium et terres rares ; même sensibilité au cycle, rentabilité non établie.']] },
    { name: 'Aval — services publics nucléaires (clients)', order: 2, transmission: 'Ils exploitent les réacteurs qui consomment l’uranium : leur demande de combustible et leurs multiples de rentabilité éclairent directement le prix payé pour Cameco.', rows: [
      ['D', 'downstream', 'Service public à parc nucléaire', 'Exploitant de centrales nucléaires ; acheteur final de combustible et repère de valorisation d’un actif rentable.'],
      ['DUK', 'downstream', 'Service public à parc nucléaire', 'Grand exploitant nucléaire réglementé ; sa valorisation encadre celle des acteurs rentables du complexe.']] },
    { name: 'Réacteurs avancés — demande future', order: 2, transmission: 'Les développeurs de petits réacteurs modulaires promettent une demande d’uranium future : leur cours porte l’optimisme du complexe, sans revenus ni rentabilité aujourd’hui.', rows: [
      ['OKLO', 'second_order', 'Petits réacteurs modulaires', 'Développeur de micro-réacteurs ; baromètre de l’enthousiasme nucléaire, sans revenus établis.'],
      ['NNE', 'second_order', 'Développeur de micro-réacteurs nucléaires', 'Développeur de micro-réacteurs à un stade précoce ; forte volatilité, demande d’uranium purement prospective.']] },
    { name: 'Second ordre — équipement et électrification', order: 2, transmission: 'Même vague d’investissement dans l’électricité et les centres de données qui sous-tend la thèse nucléaire, du côté de l’équipement et du réseau.', rows: [
      ['GEV', 'second_order', 'Équipement électrique et turbines', 'Fournit turbines et équipements de production, nucléaire compris ; carnet lié à l’électrification.'],
      ['VRT', 'second_order', 'Alimentation et refroidissement des centres de données', 'Son carnet suit la demande d’électricité des centres de données, moteur avancé de la thèse nucléaire.']] },
    { name: 'Contrôles sectoriels', order: 2, transmission: 'Paniers de référence pour isoler ce qui est propre à Cameco.', rows: [
      ['XLU', 'sector_proxy', 'Panier de services publics', 'Contrôle du secteur des services publics ; un écart isole ce qui est propre à l’uranium.'],
      ['URNJ', 'upstream', 'Prix de l’uranium (panier producteurs)', 'Le complexe uranium dont le prix commande directement le chiffre d’affaires de Cameco : c’est le moteur amont des revenus, comme le métal l’est pour un mineur.']] },
  ],
  eventDefault: { leader: 'Aucune publication dans les quatorze jours collectés ; ses contrats et sa demande de combustible restent le signal à suivre', direct_peer: 'Aucune publication dans les quatorze jours collectés ; le cycle de l’uranium reste le signal à suivre', upstream: 'Panier sans publication propre ; suit le prix de l’uranium, moteur amont des revenus', downstream: 'Aucune publication dans les quatorze jours collectés ; sa demande de combustible fixe le débouché', second_order: 'Aucune publication dans les quatorze jours collectés ; baromètre de sentiment à suivre', sector_proxy: 'Panier sans publication propre ; exposé à ses grandes pondérations' },
  eventRisk: {},
  blastDoc: 4,
  scenarios: c => [
    { scenario: 'bullish', trigger: 'Le complexe nucléaire repart et Cameco reclasse la fourchette de la mi-septembre.', firstOrder: 'Le titre clôture au-dessus du plus haut du 22 septembre et vise la zone du rebond d’août.', secondOrder: 'Constellation, Duke et les producteurs d’uranium accompagnent le mouvement.', confirmation: 'Une clôture au-dessus de ' + c.usd(c.entry) + ' avec le complexe nucléaire en hausse.', contradiction: 'Un dépassement isolé pendant que les services publics nucléaires reculent.' },
    { scenario: 'mixed', trigger: 'Pas de nouvelle propre ; le marché digère la valorisation.', firstOrder: 'Le titre oscille entre le bas du 25 septembre et le plus haut du 22.', secondOrder: 'L’écart avec le complexe nucléaire reste faible.', confirmation: 'Des clôtures entre ' + c.usd(c.abandon) + ' et ' + c.usd(c.entry) + ' pendant plusieurs séances.', contradiction: 'Une sortie franche d’un côté ou de l’autre.' },
    { scenario: 'bearish', trigger: 'Compression des multiples du complexe nucléaire ou déception sur les prix de contrat.', firstOrder: 'Le titre repasse sous le bas du 25 septembre et ouvre le vide technique vers son plus bas annuel.', secondOrder: 'Les producteurs d’uranium reculent plus vite que les services publics.', confirmation: 'Une clôture sous ' + c.usd(c.abandon) + ' avec les producteurs d’uranium en baisse.', contradiction: 'Un repli du complexe que Cameco ne suit pas.' }],
  contradictions: c => ['Le titre est cher sur l’EBITDA d’exploitation strict (' + c.fr(c.ev / c.G$.ebitda, 0) + '×), mais nettement moins sur l’excédent brut ajusté publié : la participation Westinghouse, comptée dans la valeur d’entreprise mais pas dans l’EBITDA d’exploitation, explique l’essentiel de l’écart.', 'Le chiffre d’affaires de l’exercice 2025 progresse de 11 %, mais le premier semestre 2026 recule : la croissance n’est ni linéaire ni rapide.', 'Le résultat net glissant est positif alors qu’il a chuté d’un semestre à l’autre : il dépend de Westinghouse et des dérivés, pas seulement de l’exploitation.'],
  missingData: c => ['Aucun companyfacts us-gaap n’existe pour cet émetteur étranger canadien : les agrégats sont lus dans les états IFRS des dépôts primaires, en dollars canadiens, puis convertis en USD au taux Banque du Canada du 30 juin 2026 (1,4210).', 'Position vendeuse non renseignée par le snapshot et coût d’emprunt indisponible à la collecte ; chaîne d’options non servie ; ni Reddit ni tendances de recherche pour ce titre.', 'Couverture officielle des transactions d’initiés partielle pour un émetteur canadien (déclarations SEDI) ; aucun solde net affirmé.', 'Dix comparables élagués (URA, NXE, LEU, EU, SMR, VST, URNM, URG, NLR, BWXT, NRG, PWR) pour géométrie de barre invalide ou discontinuité de séances dans la fenêtre servie ; douze comparables propres conservés, couvrant six groupes économiques.'],
  limitations: ['Émetteur étranger canadien IFRS : agrégats reconstitués depuis les dépôts primaires en dollars canadiens, convertis en USD au taux daté du 30 juin 2026 (1,4210) ; un taux de clôture unique est appliqué aux flux et au bilan.', 'EBITDA d’exploitation strict (résultat d’exploitation + amortissements) : il exclut la quote-part de Westinghouse, présente dans la valeur d’entreprise ; l’excédent brut ajusté publié est cité en parallèle.', 'Base de flux en douze mois glissants au 30 juin 2026 ; le résultat net glissant est volatil (mise en équivalence, dérivés).', 'Coût d’emprunt, position vendeuse, options et sentiment social non exploitables à la collecte.'],
});
