const fs=require('fs'),crypto=require('crypto');const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');const write=(p,v)=>fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n');
function get(o,p){return p.split('.').reduce((v,k)=>v?.[k],o)}function set(o,p,v){let a=p.split('.'),k=a.pop(),x=o;for(const n of a)x=x[n]??=(/^\d+$/.test(n)?[]:{});x[k]=v}
function walk(o,p='',out={}){if(typeof o==='number'||typeof o==='string'&&/\d/.test(o)&&!/^https?:/.test(o))out[p]=o;else if(o&&typeof o==='object')for(const [k,v]of Object.entries(o))walk(v,p?p+'.'+k:k,out);return out}
for(const t of ['EMR','MTDR']){let p=`data/analyses-data/${t}.json`,ep=`data/analyses-evidence/${t}.json`,cp=`analyses/${t}/_data/calculations.json`,d=JSON.parse(fs.readFileSync(p)),e=JSON.parse(fs.readFileSync(ep)),c=JSON.parse(fs.readFileSync(cp));
const dup=t==='EMR'?'Sur 21 séances, EMR a varié de -7,09 % : contexte technique descriptif, sans argument fondamental ni promesse de rebond.':'L’amélioration du cash n’est pas seulement une histoire de volumes : le pétrole réalisé ressort à 98,16 $ au T2 contre 72,83 $ au T1, soit environ +35 %, ce qui rend la lecture cyclique des prix centrale.';let field=t==='EMR'?'technicals.setupNote':'business.overview';set(d,field,get(d,field).replace(dup+' '+dup,dup));
d.technicals.setupNote=d.technicals.setupNote.replace(`$${d.tradeIdea.stop.toFixed(2)} comme invalidation`,`$${d.tradeIdea.stop.toFixed(2)} comme stop dur`);
if(t==='EMR'){
 d.header.metrics.fwdPE='23,24x ajusté / 31,12x GAAP — guidance 2026';
 d.business.segments=[['Control Systems & Software',1199,'Commandes de contrôle industriel et logiciels ; croissance sous-jacente de 7 %.'],['Test & Measurement',445,'Croissance sous-jacente de 23 %, mais seulement 9,13 % des ventes : ce moteur ne représente pas tout Emerson.'],['Sensors',1091,'Mesure industrielle ; croissance sous-jacente de 7 %.'],['Final Control',1586,'Vannes et contrôle de procédés ; croissance sous-jacente de 3 %, poids supérieur au pôle test.'],['Safety & Productivity',552,'Outillage et sécurité ; croissance sous-jacente de 2 %.']].map(([name,n,description])=>({name,revenue:n.toLocaleString('fr-FR')+' M$ — T3 fiscal 2026',pct:(n/4873*100).toFixed(2).replace('.',',')+' %',description}));
 d.fundamentals.pedagogy=(d.fundamentals.pedagogy||'')+' Au cours de 152,19 $, la comparaison des deux bases de guidance 2026 donne 23,24x le BPA ajusté de 6,55 $ et 31,12x le BPA GAAP de 4,89 $. L’écart de 1,66 $ représente 25,3 % du BPA ajusté ; le rapprochement de la direction comprend notamment 1,39 $ d’amortissement des incorporels et 0,24 $ de restructuration. Le multiple ajusté suppose donc que le lecteur accepte ces retraitements. Avec un rendement du FCF guidé de 4,24 %, le prix exige aussi que la cible de 3,6 Md$ se transforme en cash et que le mix soutienne les marges. Aucun multiple homogène de pair ou historique n’est établi ici : cette comparaison de bases explique les attentes, sans démontrer une décote ni une juste valeur.';
}else{
 d.business.segments=[{name:'Exploration et production',revenue:'1 083,333 M$ de pétrole et gaz — T2 2026',pct:'N/D — ligne partielle',description:'Ligne de revenus pétrole et gaz du segment, hors gaz acheté et résultats de dérivés ; ne pas assimiler au cash-flow.'},{name:'Midstream',revenue:'146,328 M$ de services bruts — T2 2026',pct:'N/D — avant éliminations',description:'Dont 101,735 M$ éliminés en consolidation ; 44,593 M$ de services externes consolidés. Bases partielles différentes : ces deux lignes ne doivent pas être additionnées comme une ventilation exhaustive du chiffre d’affaires.'}];
 const cap=7555194886.8,prior=437e6,forward=900e6;const fmt=n=>n.toFixed(2).replace('.',',');
 d.fundamentals.pedagogy=(d.fundamentals.pedagogy||'')+` Comparaison historique et scénario à capitalisation constante : le communiqué indique 437 M$ de FCF ajusté pour l’exercice 2025, contre une guidance 2026 d’environ 900 M$ conditionnée au strip de fin juillet. Avec la capitalisation du 11 septembre de 7,555 Md$, conserver un cash annuel équivalent à 2025 donnerait ${fmt(prior/cap*100)} % de rendement et ${fmt(cap/prior)}x prix/FCF ; réaliser la guidance donnerait ${fmt(forward/cap*100)} % et ${fmt(cap/forward)}x. L’écart de cash à produire est de ${fmt((forward/prior-1)*100)} %. Les deux états utilisent le même prix actuel : ce ne sont ni des multiples boursiers historiques, ni une juste valeur, ni des probabilités. Ce modèle montre ce que l’apparente valorisation à 8,39x exige : plus que doubler le cash ajusté 2025, avec des prix, volumes et dépenses compatibles. Le FCF reste non-GAAP ; une baisse du pétrole réalisé ou une hausse du capex peut ramener le rendement vers le premier état, ou plus bas.`;
 c.primary_cash_scenarios={capitalization_as_of:'2026-09-11',capitalization:cap,actual_2025_adjusted_fcf:prior,guided_2026_adjusted_fcf:forward,source_path:'analyses/MTDR/_review/primary-q2-ex991.htm',source_sha256:hash('analyses/MTDR/_review/primary-q2-ex991.htm'),historical_cash_at_current_cap:{yield_pct:prior/cap*100,price_to_fcf:cap/prior},guidance_cash_at_current_cap:{yield_pct:forward/cap*100,price_to_fcf:cap/forward},required_cash_change_pct:(forward/prior-1)*100};
}
write(p,d);c.analysis_sha256=hash(p);c.final_editorial_amendment={path:'.agent/source-repair-20260912/analysis-emr-mtdr/final-depth.cjs',sha256:hash(__filename)};const vals=walk(d);c.values={};c.string_numeric_claims={};for(const [k,v]of Object.entries(vals)){set(c.values,k,v);if(typeof v==='string')c.string_numeric_claims[k]=v;if(!c.claim_provenance[k])c.claim_provenance[k]={input_path:`analyses/${t}/_review/${t==='EMR'?'primary-q3-ir.html':'primary-q2-10q.htm'}`,input_sha256:hash(`analyses/${t}/_review/${t==='EMR'?'primary-q3-ir.html':'primary-q2-10q.htm'}`),source_pointer:'/primary_text',method:'Lecture primaire et calcul explicite des parts ou scénarios ; voir amendment et texte source.'};}write(cp,c);e.analysis_sha256=hash(p);e.claims=Object.entries(vals).map(([k,v])=>({path:k,value:v,as_of:'2026-09-11',source_artifact:cp,source_sha256:hash(cp),source_pointer:'/values/'+k.split('.').join('/')}));write(ep,e);fs.writeFileSync(`analyses/${t}/_review/preview/index.html`,require('../../../tools/render-analysis.js').render(d));console.log(t,hash(p),hash(ep));}
