'use strict';
// Dossier SMCI v3 au close du 2026-09-23 (lot R02). Scénario de sortie par le haut du plus haut du 23 septembre,
// avec un capital élargi en juin (actions ordinaires et préférentielles convertibles) ; gabarit commun.
const R = require('../../../../tools/lib/analysis-v3-r02.cjs');
const GEN = 'analyses/SMCI/_runs/20260924/build-smci.cjs';

R.build({
  ticker: 'SMCI', shortName: 'Supermicro', cik: 1375365, generator: GEN, mode: 'breakout',
  // Actions ordinaires au 31 juillet (10-K) + actions issues de la conversion obligatoire des préférentielles au
  // taux minimal (86,25 M × 1,5152), applicable tant que le cours dépasse 32,9989 $ : dénominateur homogène avec
  // une valeur d’entreprise qui ne compte pas les préférentielles comme dette.
  shares: { value: 656965384 + Math.round(86.25e6 * 1.5152), doc: 1 },
  xbrl: { ttm: { rev: ['RevenueFromContractWithCustomerExcludingAssessedTax'], ebit: ['OperatingIncomeLoss'], ni: ['NetIncomeLoss'], da: ['DepreciationDepletionAndAmortization'], ocf: ['NetCashProvidedByUsedInOperatingActivities'], capex: ['PaymentsToAcquirePropertyPlantAndEquipment'] },
    instant: { bank: ['DebtLongtermAndShorttermCombinedAmount'], conv: ['ConvertibleLongTermNotesPayable'], cashEq: ['CashAndCashEquivalentsAtCarryingValue'] },
    da: ['da'], debt: ['bank', 'conv'], cash: ['cashEq'] },
  scenarioMultiple: 8, valuationBasis: 'GAAP de l’exercice clos le 2026-06-30 (XBRL SEC) ; multiple de huit fois l’EBITDA = hypothèse éditoriale ; actions au 31 juillet 2026 selon le 10-K, plus 130,7 millions d’actions de conversion obligatoire des préférentielles',
  levels: { trigger: { d: '2026-09-23', c: 2 }, stop: { d: '2026-09-21', c: 3 }, abandon: { d: '2026-09-16', c: 3 },
    s1: { d: '2026-09-18', c: 3 }, r1: { d: '2026-08-13', c: 2 }, r2: { d: '2026-06-09', c: 2 } },
  supports: ['stop', 's1', 'abandon'], resistances: ['r1', 'trigger', 'r2'],
  targets: ({ entry, abandon }) => { const range = entry - abandon; return { tp1: entry + 0.75 * range, tp2: entry + range, range }; },
  levelsMethod: 'Déclencheur = plus haut du 23 septembre ; bas du couloir = plus bas du 16 septembre ; stop = plus bas du 21 septembre ; TP1 = déclencheur + 0,75 × hauteur du couloir ; TP2 = déclencheur + hauteur ; plafond = (TP1 + 1,5 × stop) / 2,5 ; pourcentages depuis l’entrée ; R/R = gain / risque.',
  inventory: 41,
  reviewScope: 'Dépôts EDGAR de Supermicro du 1er janvier au 23 septembre 2026 (41 formulaires hors formulaires 3, 4, 5 et 144), dont le 10-K de l’exercice 2026. Les 8-K de gouvernance, le 8-K/A, le formulaire SD, les déclarations 13G et les procurations sont écartés comme non décisionnels. Le S-3ASR du 9 juin, les cinq 424B5 et les deux FWP de juin portent les émissions d’actions ordinaires et de préférentielles convertibles, dont les conditions définitives sont reprises au 10-K ; le 8-A12B et le certificat du 15 juin inscrivent à la cote les certificats d’actions préférentielles ; le S-8 du 8 juin enregistre des actions pour les plans salariés.',
  docs: [
    ['2026-08-11', '8-K / Exhibit 99.1', '0001375365-26-000021', 'exhibit991_20260630.htm', 'q4-8k__exhibit991_20260630.htm',
      'Communiqué du quatrième trimestre de l’exercice 2026 : ventes de 11,1 Md$, marge brute de 17,5 % contre 9,9 % au trimestre précédent. Prévision de 14,5 à 15,5 Md$ pour le premier trimestre et de 65,0 à 72,0 Md$ pour l’exercice 2027, sur 745 millions d’actions diluées.'],
    ['2026-08-31', '10-K', '0001375365-26-000022', 'smci-20260630.htm', 'fy26-10k__smci-20260630.htm',
      'Rapport annuel de l’exercice 2026 : un client à 28,1 % des ventes, flux d’exploitation négatif de 6,81 Md$, émission de 52,3 millions d’actions à 27,50 $ et de 86,25 millions de certificats d’actions préférentielles convertibles en juin, programme de vente au fil de l’eau de 1,25 Md$, et mise en examen d’un ancien vice-président pour violation des contrôles à l’exportation.'],
    ['2026-06-12', '8-K', '0001193125-26-269703', 'd45696d8k.htm', 'jun12-8k__d45696d8k.htm',
      'Contrat de distribution d’actions du 11 juin avec J.P. Morgan, Goldman Sachs et Citigroup, qui encadre le programme de vente au fil de l’eau, et contrat de prise ferme de l’émission d’actions ordinaires. Aucun financeur spécialisé dans les émissions toxiques n’apparaît.'],
  ],
  needles: {
    q4: [0, ['Net sales of $11.1 billion', 'Gross margin of 17.5% versus 9.9% in Q3\'26', 'net sales in the range of $14.5 billion and $15.5 billion', 'net sales in the range of $65.0 billion to $72.0 billion', 'fully diluted share count of 745 million shares for GAAP', 'total bank debt and convertible notes were $8.7 billion', 'Net income of $1,178 million']],
    tenk: [1, ['sales to one customer represented 28.1 % of total net sales', 'Net cash (used in) provided by operating activities $ (6,809.9)', '45,454,545 shares of our common stock at a public offering price of $ 27.50', 'exercised their option to purchase an additional 6,818,181 shares', 'exercised their option to purchase an additional 11,250,000 depositary shares', '75,000,000 depositary shares', 'Greater than $ 32.9989 (the “Threshold Appreciation Price”) 30.3040 shares', 'Between 30.3040 and 36.3640 shares', 'on or about June 1, 2029', 'aggregate offering price of up to $ 1.25 billion', 'As of June 30, 2026, we had not sold any shares of common stock under the program', 'approximately $ 83.44 per share', 'approximately $ 61.06 per share', 'approximately $ 55.20 per share', 'including Yih-Shyan (Wally) Liaw', 'the Company received a subpoena from the SEC', '656,965,384 shares']],
    atm: [2, ['Equity Distribution Agreement, dated as of June 11, 2026, by and among Super Micro Computer, Inc., J.P. Morgan Securities LLC, Goldman Sachs & Co. LLC and Citigroup Global Markets Inc.']],
  },
  sectionDocs: { verdict: [0, 1], business: [0, 1], news: [0], earnings: [0], capitalStructure: [1, 2], filingsReview: [0, 1, 2], risks: [1, 0, 2], globalScore: [0, 1], meta: [0], disclaimer: [0], macro: [0], options: [0], social: [0], header: [0] },
  score: { business: 26, technical: 4, capital: -6, calendar: 0, dilution: -8, risk: 30 },
  peers: true,
  riskScoreReason: 'Jugement qualitatif sur dix : dilution de juin et convertibles, client à 28,1 % des ventes, flux d’exploitation négatif et procédure pénale visant un ancien dirigeant.',
  compose: c => {
    const { nb, fr, usd, pct, sgn, dfr, close, prev, bars, N, tech, st, M, adv, ret, G$, shares, marketCap, ev, scn, lv, entry, stop, tp1, tp2, abandon, cap, rr1, rr2, riskAtr, sizeExample, ref, market, docs, raw, tx } = c;
    const pref = 86.25e6, prefMin = pref * 1.5152, prefMax = pref * 1.8182, common = 45454545 + 6818181;
    const liang = tx.transactions.filter(x => x.insider_name === 'Liang Charles' && x.type_code === 'S');
    const lS = liang.reduce((s, x) => s + x.shares, 0), lV = liang.reduce((s, x) => s + x.value_usd, 0);
    const gs = c.gapStats(cap - entry);
    const aug12 = bars.find(b => b[0] === '2026-08-12'), aug11 = bars.find(b => b[0] === '2026-08-11'), jul17 = bars.find(b => b[0] === '2026-07-17');
    return {
      meta: { lang: 'fr', dir: 'ltr', level: 'intermediate', tags: ['us', 'equities', 'ai-chain', 'tech', 'technology', 'speculative'], grade: 'C+', date: '2026-09-24', dateDisplay: '24 septembre 2026', version: 3, status: 'watch', assetType: 'stock', levelsCloseDate: c.REF,
        description: 'Supermicro : des ventes qui doublent, un capital élargi en juin et un titre qui teste son plus haut depuis. Dossier au close du 23 septembre 2026, statut surveiller.',
        ogDescription: 'Supermicro : prévision de 65 à 72 Md$, 130 millions d’actions à venir via les préférentielles, un client à 28,1 % ; niveaux à surveiller.',
        lastMcpRefresh: raw.status.captured_at, levelsVerifiedAt: raw.status.captured_at,
        statusHistory: [{ at: raw.status.captured_at, from: 'wait', to: 'watch', note: 'refonte v3 du 24 septembre : nouveau scénario, clôture de référence du 2026-09-23', close }] },
      header: { ticker: 'SMCI', name: 'Super Micro Computer, Inc.', exchange: 'NASDAQ', sector: 'Serveurs et baies d’IA refroidies par liquide', price: close, changePct: pct(close, prev),
        badges: [{ text: 'SURVEILLER — PAS D’ENTRÉE AU COURS ACTUEL', color: 'blue' }, { text: 'Chaîne IA — serveurs', color: 'purple' }],
        metrics: { marketCap: fr(marketCap / 1e9, 1) + ' Md$', volume: fr(bars[N][5] / 1e6, 1) + ' M', evEbitda: fr(ev / G$.ebitda, 1) + '×' }, halalStatus: 'unknown' },
      verdict: { score: 46, conviction: 'Low', bias: 'Neutral',
        confidence: 'Score éditorial non prédictif. Les chiffres d’entreprise viennent des dépôts SEC et des données XBRL officielles ; les niveaux, du close certifié du 23 septembre.',
        summary: 'Supermicro assemble les baies de serveurs d’IA que les néo-clouds et les grands comptes installent. L’exercice 2026 a atteint 39,1 Md$ de ventes, et la société vise 65 à 72 Md$ pour l’exercice 2027. Le prix de cette croissance est le capital. En juin, 52,3 millions d’actions ont été vendues à 27,50 $, et 86,25 millions de certificats d’actions préférentielles, chacun représentant un vingtième d’action préférentielle, se convertiront obligatoirement en 2029 : au cours actuel, ces seules préférentielles donneront environ ' + fr(prefMin / 1e6, 0) + ' millions d’actions ordinaires, en plus des 52,3 millions de juin. Le flux d’exploitation de l’exercice est négatif de 6,81 Md$, un client pèse 28,1 % des ventes, et Wally Liaw, ancien vice-président principal et ancien administrateur, est poursuivi pour violation des contrôles à l’exportation. Le titre a gagné ' + fr(pct(close, jul17[3]), 0) + ' % depuis son plus bas du 17 juillet et bute sur ' + usd(entry) + '. Pas d’entrée au cours actuel.',
        whyBuy: [
          'Les ventes du quatrième trimestre atteignent 11,1 Md$, contre 5,8 Md$ un an plus tôt, avec une marge brute remontée à 17,5 %.',
          'La prévision de l’exercice 2027 vise 65,0 à 72,0 Md$ de ventes, contre 39,1 Md$ sur l’exercice 2026.',
          'Au close du 23 septembre, préférentielles converties, la valeur d’entreprise représente ' + fr(ev / G$.ebitda, 1) + ' fois l’EBITDA GAAP de l’exercice 2026.',
          'Le financement de juin a été placé par J.P. Morgan et Goldman Sachs, sans financeur spécialisé dans les émissions toxiques.'],
        whyAvoid: [
          'Les préférentielles convertibles ajouteront entre ' + fr(prefMin / 1e6, 0) + ' et ' + fr(prefMax / 1e6, 0) + ' millions d’actions en 2029, soit 20 à 24 % du nombre actuel, et le programme de vente de 1,25 Md$ peut vendre des actions depuis juillet : ses ventes ne sont pas encore publiées, le nombre du 31 juillet peut déjà être dépassé.',
          'Le flux d’exploitation de l’exercice 2026 est négatif de 6,81 Md$ : la croissance se finance par le capital et la dette.',
          'Un client non nommé a pesé 28,1 % des ventes de l’exercice 2026.',
          'Le 19 mars 2026, Wally Liaw, ancien vice-président principal et ancien administrateur, a été mis en examen pour violation des contrôles à l’exportation, et la SEC a adressé une demande de documents.'],
        controlChecklist: [
          { label: 'Historique de cours', status: 'pass', statusLabel: 'Trois cents séances continues', evidence: 'Série quotidienne certifiée au close du 23 septembre, source de repli documentée.', action: 'Niveaux et indicateurs recalculés sur cette seule série.' },
          { label: 'Dilution', status: 'fail', statusLabel: 'Capital élargi en juin', evidence: 'Actions ordinaires, préférentielles convertibles et programme de vente au fil de l’eau décrits au 10-K.', action: 'Lire au prochain 10-Q les actions vendues depuis juillet.' },
          { label: 'Procédure pénale', status: 'warn', statusLabel: 'Ancien dirigeant poursuivi', evidence: 'Mise en examen du 19 mars et demande de documents de la SEC, décrites au 10-K.', action: 'Tout développement judiciaire peut provoquer un écart à l’ouverture.' }] },
      business: { theme: 'Serveurs d’IA, baies refroidies par liquide et solutions de centres de données',
        overview: '<p>Supermicro conçoit et assemble des serveurs et des baies complètes pour l’IA, avec les processeurs de Nvidia et d’AMD, la mémoire, le stockage et le refroidissement par liquide. Ses clients sont des néo-clouds, des grandes entreprises et des opérateurs de centres de données. L’exercice 2026, clos le 30 juin, a atteint 39,1 Md$ de ventes contre 22,0 Md$ l’exercice précédent.</p><p>Le quatrième trimestre marque un tournant de marge : 17,5 % de marge brute contre 9,9 % au trimestre précédent et 9,5 % un an plus tôt, pour un résultat net de 1,18 Md$. La direction l’attribue à un meilleur mix de clients d’entreprise et à ses solutions de centres de données par blocs. Sur l’exercice entier, la marge brute reste à 10,8 %.</p><p>Cette croissance consomme du cash. Le flux d’exploitation de l’exercice est négatif de 6,81 Md$, surtout en stocks, et la société a levé en juin des actions ordinaires et des préférentielles convertibles pour plus de 5,4 Md$ nets. Un client a représenté 28,1 % des ventes, et une procédure pénale vise Wally Liaw, ancien vice-président principal et ancien administrateur, avec deux autres personnes, pour violation des contrôles à l’exportation.</p>',
        moat: 'Supermicro sait livrer vite des baies complètes et refroidies par liquide dès qu’une nouvelle génération de processeurs sort. Cet avantage de rapidité est réel mais peu défendable : Dell et HPE assemblent les mêmes processeurs, et les marges dépendent du mix de clients.',
        segments: [
          { name: 'Exercice 2026', revenue: '39,1 Md$', pct: '100 %', description: 'Contre 22,0 Md$ sur l’exercice 2025.' },
          { name: 'Quatrième trimestre', revenue: '11,1 Md$', pct: '28 %', description: 'Marge brute de 17,5 %.' }],
        sourceRefs: [ref(0), ref(1)],
        coverageMatrix: [
          { facet: 'Cours et historique', status: 'COUVERT', decision: 'Trois cents séances continues, close certifié ; base des niveaux et des indicateurs.' },
          { facet: 'Résultats et guidance', status: 'COUVERT — PRIMAIRE', decision: 'Communiqué du 11 août et 10-K ; prochaine date non confirmée.' },
          { facet: 'Capital et dilution', status: 'COUVERT — PRIMAIRE', decision: 'Émissions de juin, préférentielles, convertibles et programme de vente lus dans le 10-K.' },
          { facet: 'Agrégats GAAP', status: 'COUVERT — XBRL', decision: 'Exercice clos le 30 juin 2026 lu dans les données XBRL officielles.' },
          { facet: 'Comparables et transmission', status: 'COUVERT — LOCAL', decision: 'Corrélations recalculées sur barres certifiées depuis la fin mars.' },
          { facet: 'Juridique', status: 'COUVERT — PRIMAIRE', decision: 'Mise en examen et demande de la SEC décrites au 10-K ; issue inconnue.' },
          { facet: 'Options', status: 'NON EXPLOITABLE', decision: 'Chaîne relevée marché fermé, sans intérêt ouvert utilisable.' }] },
      news: [
        { date: '2026-08-11', title: 'Quatrième trimestre à 11,1 Md$ et marge brute de 17,5 %', impact: 'positive', detail: 'Le lendemain, le titre a pris ' + sgn(pct(aug12[4], aug11[4]), 1) + ' : le marché a salué la marge plus que les ventes.', source: 'Supermicro — SEC', sourceUrl: docs[0].url },
        { date: '2026-08-31', title: 'Le 10-K chiffre la dilution de juin', impact: 'negative', detail: 'Actions ordinaires à 27,50 $, préférentielles convertibles en 2029 et programme de vente de 1,25 Md$ : le nombre d’actions va continuer de monter.', source: 'Supermicro — SEC', sourceUrl: docs[1].url },
        { date: '2026-06-12', title: 'Programme de vente confié à trois grandes banques', impact: 'neutral', detail: 'J.P. Morgan, Goldman Sachs et Citigroup encadrent le programme : pas de financeur toxique, mais une offre d’actions possible à tout moment.', source: 'Supermicro — SEC', sourceUrl: docs[2].url }],
      fundamentals: { rows: [
          { metric: 'Ventes du quatrième trimestre', value: '11,1 Md$', signal: 'Contre 5,8 Md$ un an plus tôt', signalColor: 'green', _src: 0 },
          { metric: 'Marge brute du quatrième trimestre', value: '17,5 %', signal: '9,9 % au trimestre précédent', signalColor: 'green', _src: 0 },
          { metric: 'Prévision de l’exercice 2027', value: '65,0 à 72,0 Md$', signal: 'Premier trimestre à 14,5–15,5 Md$', signalColor: 'blue', _src: 0 },
          { metric: 'Dette bancaire et convertibles', value: '8,7 Md$', signal: 'Au 30 juin 2026, contre 7,5 Md$ de trésorerie', signalColor: 'amber', _src: 0 },
          { metric: 'Flux d’exploitation de l’exercice', value: '−6,81 Md$', signal: 'Exercice clos le 30 juin 2026, 10-K', signalColor: 'red', _src: 1 },
          { metric: 'Part du premier client', value: '28,1 %', signal: 'Exercice 2026, client non nommé', signalColor: 'amber', _src: 1 },
          { metric: 'Revenus GAAP de l’exercice', value: fr(G$.rev / 1e9, 1) + ' Md$', signal: 'Exercice clos le 30 juin 2026 (XBRL SEC)', signalColor: 'blue', _src: 'gaap' },
          { metric: 'EBITDA GAAP de l’exercice', value: fr(G$.ebitda / 1e9, 2) + ' Md$', signal: 'Résultat opérationnel + amortissements, exercice clos le 30 juin 2026', signalColor: 'blue', _src: 'gaap' },
          { metric: 'Résultat net GAAP de l’exercice', value: fr(G$.ni / 1e9, 2) + ' Md$', signal: 'Exercice clos le 30 juin 2026', signalColor: 'green', _src: 'gaap' },
          { metric: 'Flux de trésorerie libre de l’exercice', value: fr(G$.fcf / 1e9, 2) + ' Md$', signal: 'Flux d’exploitation moins investissements industriels, exercice 2026', signalColor: 'red', _src: 'gaap' },
          { metric: 'Dette et trésorerie au 30 juin 2026', value: fr(G$.debt / 1e9, 2) + ' Md$ / ' + fr(G$.cash / 1e9, 2) + ' Md$', signal: 'Dette bancaire et convertibles ; liquidités', signalColor: 'amber', _src: 'gaap' },
          { metric: 'EV/EBITDA GAAP', value: fr(ev / G$.ebitda, 1) + '×', signal: 'Valeur d’entreprise au close du 2026-09-23 sur EBITDA GAAP de l’exercice clos le 2026-06-30', signalColor: 'green', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus Dell à ' + fr(c.peerEv('DELL'), 1) + '× et HPE à ' + fr(c.peerEv('HPE'), 1) + '× (statistiques courantes du 24 septembre, non point-in-time) : préférentielles comprises, le multiple reste bas, reflet de la dilution et d’un flux de trésorerie négatif.', _src: 'market', _peers: ['DELL', 'HPE'] },
          { metric: 'P/E GAAP de l’exercice', value: fr(marketCap / G$.ni, 1) + '×', signal: 'Exercice 2026 : capitalisation au 2026-09-23, préférentielles converties, sur résultat net GAAP de l’exercice clos le 2026-06-30', signalColor: 'green', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus 745 millions d’actions diluées retenues par la société pour sa prévision : le multiple par action dilué est plus élevé.', _src: 'market' },
          { metric: 'EV/EBITDA — scénario de compression (hypothèse éditoriale)', value: fr(scn.price, 2) + ' $ par action', signal: 'Scénario : multiple ramené à huit fois l’EBITDA GAAP par hypothèse, dette et trésorerie du 2026-06-30 inchangées, préférentielles converties, soit ' + fr(scn.downside_pct, 0) + ' % sous le close du 2026-09-23', signalColor: 'red', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus le close : ce que coûterait un retour au multiple d’un assembleur à faible marge ; ce n’est pas un objectif.', _src: 'market' }],
        sourceRefs: [ref(0), ref(1), market('fondamentaux et statistiques')] },
      earnings: { quarters: [],
        beatNote: 'Quatrième trimestre de l’exercice 2026 : bénéfice par action GAAP dilué de 1,62 $ et ajusté de 1,70 $, résultat net de 1,18 Md$. La guidance du premier trimestre de l’exercice 2027 vise 14,5 à 15,5 Md$ de ventes et un bénéfice GAAP de 0,89 à 0,98 $ par action, sur 745 millions d’actions diluées. Pour l’exercice 2027 entier, la société prévoit 65,0 à 72,0 Md$ de ventes. Aucune date de prochaine publication n’est confirmée par l’émetteur à ce jour.',
        nextEarnings: 'Date non confirmée par l’émetteur ; aucune publication dans les quatorze jours du calendrier collecté.',
        sourceRefs: [ref(0)] },
      capitalStructure: { sharesOutstanding: '656 965 384 actions au 31 juillet 2026 (page de garde du 10-K)',
        sharesAuthorized: 'Actions autorisées non reprises : la contrainte est la dilution effective, chiffrée ci-dessous.', dilutionRisk: 'high',
        shareHistory: 'Pont vers un nombre dilué : 657 millions d’actions au 31 juillet, après 52,3 millions vendues en juin à 27,50 $. Les 86,25 millions de certificats, chacun égal à un vingtième d’action préférentielle, se convertiront vers le 1er juin 2029 en 1,5152 à 1,8182 action chacune, soit ' + fr(prefMin / 1e6, 1) + ' à ' + fr(prefMax / 1e6, 1) + ' millions d’actions ; au-dessus de 33 $, c’est le bas de la fourchette qui s’applique. Le programme de 1,25 Md$ représenterait environ ' + fr(1.25e9 / close / 1e6, 0) + ' millions d’actions au cours actuel. Les convertibles 2028, 2029 et 2030 ne se convertissent qu’à 61,06 $, 83,44 $ et 55,20 $. La société retient 745 millions d’actions diluées pour sa prévision, 13 % de plus que le nombre en circulation : c’est cette base qui compte pour le bénéfice par action.',
        warrants: [], atm: { active: true, authorized: '1,25 Md$ (contrat du 11 juin 2026)', used: 'Aucune action vendue au 30 juin 2026', remaining: 'Jusqu’à 1,25 Md$ ; ventes possibles depuis juillet, non encore publiées' },
        sourceRefs: [ref(1), ref(2)] },
      filingsReview: { summary: 'Trois dépôts décisionnels ouverts et hachés. Les ventes et la marge progressent vite ; le capital, lui, a été élargi en juin et le sera encore par les préférentielles et le programme de vente ; la procédure pénale reste ouverte.',
        filings: docs.map(d => ({ date: d.date, form: d.form, accession: d.accession, finding: d.finding, url: d.url })),
        contrarianRisks: [
          'La marge brute de 17,5 % d’un seul trimestre peut ne pas tenir : sur l’exercice, elle n’est que de 10,8 %.',
          'Le programme de vente au fil de l’eau permet de vendre des actions pendant une hausse du cours ; il plafonne les sorties par le haut.',
          'Un client à 28,1 % des ventes : un seul report de livraison suffit à rater une prévision.',
          'Une évolution de la procédure pénale ou de l’enquête de la SEC peut faire décrocher le titre sans lien avec l’activité.'] },
      technicals: { rsi14: +tech.rsi14.toFixed(2), macd: +tech.macd.toFixed(2), macdSignal: +tech.macdSignal.toFixed(2), ema20: +tech.ema20.toFixed(2), ema50: +tech.ema50.toFixed(2), ema200: +tech.ema200.toFixed(2),
        ma50Type: 'EMA', ma200Type: 'EMA', ma50Available: true, ma200Available: true, atr14: +tech.atr14.toFixed(2),
        badges: ['Au-dessus des moyennes à vingt, cinquante et deux cents séances', 'Sous le plus haut du 23 septembre', 'Pas d’entrée au cours actuel'],
        supports: [stop, lv('s1'), abandon], resistances: [lv('r1'), entry, lv('r2')],
        setupNote: 'Le titre clôture à ' + usd(close) + ', au-dessus de ses moyennes à vingt, cinquante et deux cents séances, après avoir touché ' + usd(entry) + ' en séance. Avant activation, aucune entrée ; une clôture sous ' + usd(abandon) + ', plus bas du 16 septembre, abandonne le scénario. Activation sur une clôture au-dessus de $' + entry.toFixed(2) + ', plus haut du 23 septembre. Après activation, stop sous $' + stop.toFixed(2) + ', plus bas du 21 septembre, soit ' + fr(riskAtr, 2) + ' ATR sous le déclencheur. Supports : ' + usd(stop) + ', ' + usd(lv('s1')) + ' et ' + usd(abandon) + '. Résistances : ' + usd(lv('r1')) + ', ' + usd(entry) + ' et ' + usd(lv('r2')) + ', plus haut de la veille de l’émission de juin.',
        wyckoff: 'Non utilisé : le profil de volume n’est pas exploité dans ce dossier.',
        sourceRefs: [market('barres quotidiennes et indicateurs recalculés')] },
      options: { callOI: 'Non exploitable', putOI: 'Non exploitable', cpRatio: 'Non exploitable', maxPain: 'Non exploitable', ivMean: 'Non exploitable', skew: 'Chaîne relevée marché fermé, sans intérêt ouvert utilisable', unusual: 'Aucune activité inhabituelle qualifiée', sourceRefs: [market('options')] },
      shortInterest: { siPct: fr(st.shortPercentOfFloat * 100, 1) + ' % du flottant', daysToCover: fr(st.shortRatio, 2) + ' jours, date de règlement non précisée par le snapshot', ctb: 'Non mesuré dans ce relevé', trend: 'Positions vendeuses élevées, mais une partie couvre vraisemblablement des convertibles et des préférentielles : leurs porteurs vendent l’action pour se protéger, sans parier sur la baisse. Ne pas y lire une réserve de rachats forcés.', squeezeScore: 'Faible à modéré : vendeurs nombreux, en partie couverts par des convertibles', sourceRefs: [market('positions vendeuses')] },
      insiders: { signal: 'Charles Liang, fondateur et directeur général, a déclaré la vente de ' + nb(lS) + ' actions pour environ ' + fr(lV / 1e6, 1) + ' M$ les 3 et 4 septembre, détenues indirectement ; Sara Liu, cofondatrice, vice-présidente principale et administratrice selon le 10-K, déclare les mêmes ' + nb(lS) + ' actions en détention directe. Il s’agit très probablement des mêmes titres déclarés deux fois : ne pas additionner. Les autres lignes sont des attributions d’actions.',
        recentTransactions: [{ date: '2026-09-04', insider: 'Charles Liang — fondateur et directeur général', type: 'sell', shares: nb(lS), value: fr(lV / 1e6, 1) + ' M$' }],
        sourceRefs: [market('formulaires 4')] },
      macro: { indicators: [{ name: 'Clôture de référence', value: c.REF, signal: usd(close) + ', séance complète' }, { name: 'Rendement cinq séances', value: sgn(ret(5)), signal: 'Descriptif' }, { name: 'Rendement vingt et une séances', value: sgn(ret(21)), signal: 'Descriptif' }],
        regime: 'neutral', impact: 'Supermicro finance ses stocks par la dette et le capital : des taux longs à 5,11 % le 23 septembre, plus haut depuis juillet 2007, renchérissent ce financement et pèsent sur un titre déjà très sensible au sentiment.' },
      risks: { riskScore: 8, riskProfile: 'Very High',
        riskSummary: 'Le risque de Supermicro n’est pas la demande, qui double, mais la façon de la financer et la gouvernance. Le capital a été élargi en juin et le sera encore, le flux d’exploitation est fortement négatif, un client pèse plus d’un quart des ventes, et une procédure pénale vise un ancien dirigeant. Chaque sortie par le haut se fait face à une offre d’actions possible.',
        riskCards: [
          { title: 'Dilution continue', severity: 'critical', icon: 'fa-money-bill-trend-up', points: ['52,3 millions d’actions vendues en juin à 27,50 $.', 'Environ ' + fr(prefMin / 1e6, 0) + ' millions d’actions à venir via les préférentielles, plus le programme de 1,25 Md$.'], verdict: 'Le nombre d’actions monte plus vite que la plupart des pairs : la croissance par action sera inférieure à celle des ventes.' },
          { title: 'Flux de trésorerie négatif', severity: 'high', icon: 'fa-water', points: ['Flux d’exploitation de −6,81 Md$ sur l’exercice.', 'Dette bancaire et convertibles de 8,7 Md$.'], verdict: 'Tant que les stocks absorbent le cash, la société dépend des marchés financiers.' },
          { title: 'Procédure pénale et SEC', severity: 'high', icon: 'fa-gavel', points: ['Mise en examen de Wally Liaw, ancien vice-président principal et ancien administrateur, le 19 mars 2026.', 'Demande de documents de la SEC sur certains clients.'], verdict: 'Un développement judiciaire peut provoquer un écart à l’ouverture sans lien avec les résultats.' },
          { title: 'Client dominant', severity: 'medium', icon: 'fa-user-tie', points: ['Un client non nommé à 28,1 % des ventes.', 'Clients concentrés parmi les néo-clouds.'], verdict: 'Un report de livraison chez ce client suffit à manquer une prévision trimestrielle.' }],
        pedagogy: 'Sur un titre aussi volatil, un gap à l’ouverture peut dépasser toute la distance au stop, et le slippage est plus large qu’il n’y paraît malgré la liquidité. La taille de position doit être réduite en conséquence : partir de la distance au stop et d’un petit budget de perte. Un dépôt de la SEC ou un événement judiciaire peut survenir à tout moment. Ne pas anticiper la sortie : attendre la clôture au-dessus du déclencheur.' },
      tradeIdea: { status: 'watch', statusNote: 'Surveiller. Avant activation : aucune entrée ; une clôture sous ' + usd(abandon) + ' abandonne le scénario. Activation : clôture au-dessus de ' + usd(entry) + ', puis achat à l’ouverture suivante seulement sous ' + usd(cap) + '. Après activation : stop sous ' + usd(stop) + '. L’ancien repère de 38,95 $ du 28 août était dormant et n’a jamais été un ordre.',
        entry, stop, tp1, tp2,
        stopPct: pct(stop, entry).toFixed(1) + '%', tp1Pct: '+' + pct(tp1, entry).toFixed(1) + '%', tp2Pct: '+' + pct(tp2, entry).toFixed(1) + '%',
        rr: '1:' + rr1.toFixed(2) + ' TP1 / 1:' + rr2.toFixed(2) + ' TP2',
        entryNote: 'Déclencheur sur clôture au-dessus du plus haut du 23 septembre, pas sur un franchissement en séance. Entrée à l’ouverture suivante uniquement sous ' + usd(cap) + ' : au-delà, le R/R vers TP1 tomberait sous 1,5 avec le même stop. Le plafond n’est qu’à ' + usd(cap - entry) + ' au-dessus du déclencheur, soit ' + fr((cap - entry) / tech.atr14, 2) + ' ATR : un écart d’ouverture plus large annule l’entrée, il ne se rattrape pas. Sur les ' + gs.total + ' dernières séances, ' + gs.up + ' ouvertures ont dépassé la clôture de la veille de plus de ' + usd(cap - entry) + ', soit environ ' + fr(gs.up / gs.total * 100, 0) + ' % ; l’écart d’ouverture médian, dans un sens ou dans l’autre, vaut ' + usd(gs.medAbs) + '. Première résistance sur la route : ' + usd(lv('r2')) + ', plus haut de la veille de l’émission de juin, entre l’entrée et TP1 ; jusque-là, le R/R ne vaut que ' + fr((lv('r2') - entry) / (entry - stop), 2) + ' depuis le déclencheur et ' + fr((lv('r2') - cap) / (cap - stop), 2) + ' depuis le plafond. Le stop n’est qu’à ' + fr(riskAtr, 2) + ' ATR du déclencheur : une séance ordinaire de ce titre peut le toucher par simple bruit. Objectifs : TP1 aux trois quarts de la hauteur du couloir au-dessus du déclencheur, TP2 à sa hauteur entière. Liquidité : environ ' + fr(adv / 1e9, 2) + ' Md$ échangés par séance, médiane des vingt dernières. Exemple de taille, non personnalisé : avec un budget de perte de 100 $, le risque au plafond, ' + usd(cap - stop) + ' par action, donne ' + sizeExample + ' actions.',
        horizon: 'Dix séances après activation',
        thesis: 'Le marché paie Supermicro ' + fr(marketCap / G$.ni, 0) + ' fois ses résultats de l’exercice parce qu’il attend la dilution et doute de la marge du quatrième trimestre. Avant activation, surveillance seulement, et une clôture sous ' + usd(abandon) + ' abandonne le scénario. Une clôture au-dessus de $' + entry.toFixed(2) + ' dirait que l’offre d’actions nouvelles est absorbée ; l’achat n’a lieu qu’à l’ouverture suivante et sous ' + usd(cap) + '. Après activation, le stop sous $' + stop.toFixed(2) + ' limite le risque, mais il est proche : taille réduite. TP1 à ' + usd(tp1) + ', TP2 à ' + usd(tp2) + ', avec une résistance à ' + usd(lv('r2')) + ' entre les deux. Ne pas acheter un gap au-dessus du plafond.',
        catalysts: ['Une clôture au-dessus du plus haut du 23 septembre, sur un volume au moins égal à la médiane récente.', 'Les résultats de Micron, le 30 septembre après la clôture selon deux calendriers : un test de la demande de serveurs d’IA.', 'Le prochain 10-Q, qui dira combien d’actions ont été vendues par le programme depuis juillet.'],
        invalidation: ['Avant activation : une clôture sous ' + usd(abandon) + ', bas du couloir, abandonne le scénario.', 'Après activation : une clôture sous ' + usd(stop) + ' invalide le trade.', 'Ouverture au-dessus de ' + usd(cap) + ' après la clôture de déclenchement : pas d’achat, le R/R deviendrait insuffisant.', 'Un nouveau développement judiciaire ou une émission d’actions annoncée annule la thèse avant activation.'] },
      globalScore: { profile: 'Croissance forte, capital et gouvernance sous tension',
        keyTakeawaysPositive: ['Prévision de 65 à 72 Md$ de ventes pour l’exercice 2027.', 'Marge brute remontée à 17,5 % au quatrième trimestre.', 'Multiple bas des résultats de l’exercice.'],
        keyTakeawaysNegative: ['Dilution de juin et environ 130 millions d’actions à venir.', 'Flux d’exploitation de −6,81 Md$ sur l’exercice.', 'Procédure pénale visant Wally Liaw, ancien vice-président principal et ancien administrateur.'],
        mindsetTip: 'Un multiple bas n’est une aubaine que si le nombre d’actions ne bouge pas. Ici, il bouge : comptez en actions diluées avant de trouver le titre bon marché.' },
      social: { platforms: [], sourceRefs: [market('sentiment non retenu faute de mesure qualifiée')] },
      disclaimer: 'Document de recherche éducatif. Ni conseil financier, ni signal de trading. Statut surveiller : aucun ordre actif.',
    };
  },
  groups: [
    { name: 'Fournisseurs de processeurs', order: 1, transmission: 'Supermicro assemble leurs processeurs : leurs lancements fixent ses cycles de ventes.', rows: [
      ['NVDA', 'leader', 'Fournisseur principal des processeurs graphiques', 'Chaque nouvelle plateforme Nvidia relance les commandes de baies ; un retard la décale.'],
      ['AMD', 'leader', 'Seconde source d’accélérateurs et de processeurs', 'Ses baies Helios et ses processeurs EPYC ouvrent un second canal de ventes.'],
      ['INTC', 'upstream', 'Processeurs de serveurs', 'Ses processeurs Xeon équipent encore une partie des serveurs classiques de Supermicro.']] },
    { name: 'Pairs directs : intégrateurs de serveurs', order: 1, transmission: 'Même marché, mêmes processeurs, concurrence sur les prix et les délais.', rows: [
      ['DELL', 'direct_peer', 'Premier intégrateur de serveurs d’IA', 'Son carnet de serveurs d’IA et sa marge disent si les prix tiennent chez les intégrateurs.'],
      ['HPE', 'direct_peer', 'Serveurs pour les entreprises', 'Concurrent direct sur les grands comptes et les centres de données d’entreprise.'],
      ['CSCO', 'direct_peer', 'Serveurs et réseau d’entreprise', 'Concurrent sur les baies d’entreprise qui combinent serveurs et réseau.'],
      ['NTAP', 'direct_peer', 'Stockage pour les entreprises', 'Ses ventes de stockage pour l’IA recoupent l’offre de stockage de Supermicro.']] },
    { name: 'Amont : mémoire, stockage et énergie', order: 1, transmission: 'Composants et infrastructures qui conditionnent le coût et la livraison des baies.', rows: [
      ['MU', 'upstream', 'Mémoire HBM et DRAM de serveurs', 'Une mémoire chère comprime la marge des intégrateurs ; ses résultats du 30 septembre le diront.'],
      ['WDC', 'upstream', 'Disques durs de centres de données', 'Ses prix de stockage entrent dans le coût des baies de stockage.'],
      ['VRT', 'upstream', 'Alimentation et refroidissement', 'Ses équipements accompagnent les baies refroidies par liquide dans les mêmes sites.'],
      ['ANET', 'upstream', 'Commutateurs de réseau des clusters', 'Le réseau livré avec les baies conditionne la mise en service des clusters.']] },
    { name: 'Aval : néo-clouds et grands acheteurs', order: 2, transmission: 'Leurs capacités de financement fixent la demande de baies.', rows: [
      ['CRWV', 'downstream', 'Néo-cloud spécialisé dans l’IA', 'Acheteur typique de baies complètes : sa capacité de financement se transmet aux commandes.'],
      ['NBIS', 'downstream', 'Néo-cloud d’origine européenne', 'Ses centres en construction achètent des baies d’IA ; un signal de la demande hors États-Unis.'],
      ['ORCL', 'downstream', 'Cloud d’infrastructure pour l’IA', 'Ses nouveaux sites consomment des serveurs d’IA en grands volumes.'],
      ['META', 'downstream', 'Grand acheteur de calcul', 'Son capex fixe une partie de la demande de serveurs d’IA de tout le secteur.'],
      ['MSFT', 'downstream', 'Premier acheteur de calcul', 'Ses commandes de serveurs se répartissent entre intégrateurs ; un signal de la demande totale.'],
      ['CEG', 'second_order', 'Production d’électricité nucléaire', 'La puissance disponible limite le nombre de baies que les centres peuvent brancher.']] },
    { name: 'Contrôles sectoriels', order: 2, transmission: 'Paniers de référence pour isoler ce qui est propre à Supermicro.', rows: [
      ['SMH', 'sector_proxy', 'Panier de semi-conducteurs', 'Isole ce qui revient au cycle du matériel d’IA dans le mouvement du titre.'],
      ['XLK', 'sector_proxy', 'Panier technologique large', 'Contrôle du secteur technologique au sens large, hors effet propre à Supermicro.'],
      ['QQQ', 'sector_proxy', 'Grandes valeurs du Nasdaq', 'Contrôle large : un mouvement commun n’a rien de spécifique.']] },
  ],
  eventDefault: { leader: 'Aucune publication dans les quatorze jours collectés ; ses lancements de plateformes fixent le cycle des baies', direct_peer: 'Aucune publication dans les quatorze jours collectés ; ses marges de serveurs sont le signal à suivre', upstream: 'Aucune publication dans les quatorze jours collectés ; ses prix pèsent sur la marge des baies', downstream: 'Aucune publication dans les quatorze jours collectés ; son financement fixe ses commandes', second_order: 'Aucune publication dans les quatorze jours collectés ; ses contrats d’électricité conditionnent les mises en service', sector_proxy: 'Panier sans publication propre ; exposé aux résultats de Micron le 30 septembre' },
  eventRisk: { MU: 'Résultats le 30 septembre après la clôture, date confirmée par deux calendriers ; le coût de la mémoire pèse sur la marge des intégrateurs' },
  blastDoc: 1,
  scenarios: c => [
    { scenario: 'bullish', trigger: 'La marge du quatrième trimestre se confirme et les commandes des néo-clouds restent financées.', firstOrder: 'Le titre sort de son couloir par le haut et vise le plus haut de la veille de l’émission de juin.', secondOrder: 'Dell et HPE suivent sur l’idée d’un marché de serveurs où les prix tiennent.', confirmation: 'Une clôture au-dessus de 42,70 $ avec Dell en hausse le même jour.', contradiction: 'Une vente d’actions par le programme annoncée pendant la hausse.' },
    { scenario: 'mixed', trigger: 'Les ventes tiennent mais la marge revient vers la moyenne de l’exercice.', firstOrder: 'Le titre reste dans son couloir entre 35 et 43 $.', secondOrder: 'Les fournisseurs de processeurs progressent plus vite que les intégrateurs.', confirmation: 'Des clôtures qui butent sous le plus haut du 23 septembre.', contradiction: 'Une prévision relevée par un grand néo-cloud.' },
    { scenario: 'bearish', trigger: 'Un développement judiciaire, une nouvelle émission ou un report chez le client dominant.', firstOrder: 'Le titre casse le bas de son couloir avec un écart d’ouverture.', secondOrder: 'Les néo-clouds très endettés reculent avec lui.', confirmation: 'Une clôture sous le plus bas du 16 septembre.', contradiction: 'Une marge du premier trimestre au-dessus de 15 %.' }],
  contradictions: c => ['Le titre corrèle avec les fournisseurs de processeurs, mais sa marge dépend de leur prix : une hausse de Nvidia peut être une mauvaise nouvelle pour Supermicro.', 'Les positions vendeuses élevées amplifient les mouvements dans les deux sens ; la corrélation mesurée ne distingue pas un rachat forcé d’une demande réelle.'],
  missingData: c => ['Le client à 28,1 % des ventes n’est pas nommé : aucun client coté n’entre dans les comparables comme client documenté.', 'Actions vendues par le programme depuis juillet non publiées à ce jour ; chaîne d’options inexploitable, marché fermé.', 'Issue de la procédure pénale et de l’enquête de la SEC inconnue.'],
  limitations: ['Barres d’une source de repli (Webull).', 'Options inexploitables, marché fermé.', 'Client dominant non nommé ; ventes du programme depuis juillet non publiées.'],
});
