'use strict';
// Dossier MU v3 au close du 2026-09-23 (lot R02). Aucun plan actif : la publication du 30 septembre tombe
// dans l'horizon de tout déclenchement. Les niveaux du 27 août restent affichés comme référence archivée.
const R = require('../../../../tools/lib/analysis-v3-r02.cjs');
const GEN = 'analyses/MU/_runs/20260924/build-mu.cjs';

R.build({
  ticker: 'MU', shortName: 'Micron', cik: 723125, generator: GEN, mode: 'archived',
  xbrl: { ttm: { rev: ['RevenueFromContractWithCustomerExcludingAssessedTax'], ebit: ['OperatingIncomeLoss'], ni: ['NetIncomeLoss'], da: ['DepreciationDepletionAndAmortization'], ocf: ['NetCashProvidedByUsedInOperatingActivities'], capex: ['PaymentsToAcquirePropertyPlantAndEquipment'] },
    instant: { debtTotal: ['DebtAndCapitalLeaseObligations'], cashEq: ['CashAndCashEquivalentsAtCarryingValue'], afsCur: ['AvailableForSaleSecuritiesDebtSecuritiesCurrent'], afsNon: ['AvailableForSaleSecuritiesDebtSecuritiesNoncurrent'] },
    da: ['da'], debt: ['debtTotal'], cash: ['cashEq', 'afsCur', 'afsNon'] },
  scenarioMultiple: 10, valuationBasis: 'GAAP douze mois au 2026-05-28 (XBRL SEC) ; multiple de dix fois l’EBITDA = hypothèse éditoriale de normalisation du cycle',
  levels: { s1: { d: '2026-09-22', c: 3 }, s2: { d: '2026-09-18', c: 3 }, s3: { d: '2026-09-16', c: 3 }, r1: { d: '2026-09-23', c: 2 }, r2: { d: '2026-06-30', c: 2 }, r3: { d: '2026-06-25', c: 2 } },
  supports: ['s1', 's2', 's3'], resistances: ['r1', 'r2', 'r3'],
  inventory: 15,
  reviewScope: 'Dépôts EDGAR de Micron du 1er janvier au 23 septembre 2026 (15 formulaires hors formulaires 3, 4, 5 et 144), plus le 10-K de l’exercice 2025. Les 8-K de gouvernance et les 8-K d’information du printemps, le formulaire SD et les déclarations 13G sont écartés comme non décisionnels ; le S-8 d’avril enregistre des actions destinées aux plans de rémunération, sans offre au public. Aucun prospectus d’émission d’actions n’est relevé.',
  docs: [
    ['2026-06-24', '8-K / Exhibit 99.1', '0000723125-26-000013', 'a2026q3ex991-pressrelease.htm', 'q3fy26-8k__a2026q3ex991-pressrelease.htm',
      'Communiqué du troisième trimestre de l’exercice 2026 : chiffre d’affaires de 41,46 Md$, contre 9,30 Md$ un an plus tôt, marge brute GAAP de 84,6 % et résultat net de 28,24 Md$. Prévision du quatrième trimestre à 50,0 Md$ à plus ou moins 1,0 Md$, marge brute d’environ 86 %, bénéfice par action GAAP de 30,73 $.'],
    ['2026-06-25', '10-Q', '0000723125-26-000015', 'mu-20260528.htm', 'q3fy26-10q__mu-20260528.htm',
      'Rapport trimestriel au 28 mai 2026 : accords clients stratégiques pluriannuels de type prendre-ou-payer, avec plafond de prix proche du marché du deuxième trimestre civil 2026 et plancher. Un client à 10 % des revenus sur neuf mois, 9,38 Md$ de dette remboursés, dette ramenée à 5,7 Md$.'],
    ['2025-10-03', '10-K', '0000723125-25-000028', 'mu-20250828.htm', 'fy25-10k__mu-20250828.htm',
      'Rapport annuel de l’exercice 2025 : un client a représenté 17 % du chiffre d’affaires, principalement dans l’unité de mémoire pour le cloud, contre 10 % en 2024 et aucun client au-dessus de 10 % en 2023. La concentration a monté avec le cycle de l’IA.'],
  ],
  needles: {
    q3: [0, ['$ 41,456', '84.6 %', '28,243', '$50.0 billion ± $1.0 billion', 'Approximately 86%', '$30.73 ± $1.00', '$31.00 ± $1.00', '$30.2 billion', 'HBM4, built on 1-beta DRAM technology, is in high-volume shipments']],
    sca: [1, ['structured as take-or-pay agreements', 'ceiling price for existing products that approximates the market price in the second calendar quarter of 2026', 'Revenue from one customer was 10 %', 'Repayments of debt ( 9,380 )', 'Current debt 582', 'Long-term debt 5,140', '1,129 outstanding', 'Repurchase of stock – repurchase program — — — — ( 650 )']],
    concentration: [2, ['Revenue from one customer was 17 %']],
  },
  sectionDocs: { verdict: [0, 1], business: [0, 1, 2], news: [0], earnings: [0], capitalStructure: [1], filingsReview: [0, 1, 2], risks: [1, 0, 2], globalScore: [0, 1], meta: [0], disclaimer: [0], macro: [0], options: [0], social: [0], header: [0] },
  score: { business: 34, technical: 4, capital: 6, calendar: -8, dilution: 0, risk: 24 },
  peers: true,
  riskScoreReason: 'Jugement qualitatif sur dix : publication dans cinq séances, cyclicité des prix de la mémoire et amplitude des réactions passées.',
  compose: c => {
    const { fr, usd, pct, sgn, dfr, close, prev, bars, N, tech, st, M, adv, ret, G$, marketCap, ev, scn, lv, entry, stop, tp1, tp2, rr1, rr2, archive, ref, market, docs, raw } = c;
    const E = raw.earnings_risk.events[0];
    const pre = bars.find(b => b[0] === '2026-06-24')[4], post = bars.find(b => b[0] === '2026-06-25')[4], jul29 = bars.find(b => b[0] === '2026-07-29')[4];
    const jump = pct(post, pre), drop = pct(jul29, lv('r3'));
    return {
      meta: { lang: 'fr', dir: 'ltr', level: 'intermediate', tags: ['us', 'equities', 'ai-chain', 'semis', 'earnings', 'technology'], grade: 'B', date: '2026-09-24', dateDisplay: '24 septembre 2026', version: 3, status: 'no-trade', assetType: 'stock', levelsCloseDate: c.REF,
        description: 'Micron à cinq séances de ses résultats : des marges record, un prix de la mémoire verrouillé par contrat. Dossier au close du 23 septembre 2026, aucun plan actif.',
        ogDescription: 'Micron : marge brute de 84,6 %, prévision de 50 Md$ et publication le 30 septembre ; aucun ordre avant les résultats.',
        lastMcpRefresh: raw.status.captured_at, levelsVerifiedAt: raw.status.captured_at,
        statusHistory: [{ at: raw.status.captured_at, from: 'wait', to: 'no-trade', note: 'refonte v3 du 24 septembre : publication du 30 septembre dans l’horizon, niveaux du 27 août archivés', close }] },
      header: { ticker: 'MU', name: 'Micron Technology, Inc.', exchange: 'NASDAQ', sector: 'Mémoire DRAM, HBM et NAND', price: close, changePct: pct(close, prev),
        badges: [{ text: 'AUCUN PLAN — RÉSULTATS LE 30 SEPTEMBRE', color: 'amber' }, { text: 'Chaîne IA — mémoire', color: 'purple' }],
        metrics: { marketCap: fr(marketCap / 1e12, 2) + ' T$', volume: fr(bars[N][5] / 1e6, 1) + ' M', evEbitda: fr(ev / G$.ebitda, 1) + '×' }, halalStatus: 'unknown' },
      verdict: { score: 60, conviction: 'Moderate', bias: 'Neutral',
        confidence: 'Score éditorial non prédictif. Les chiffres d’entreprise viennent des dépôts SEC et des données XBRL officielles ; la date de publication vient de deux calendriers de données ; Micron ne l’a pas annoncée dans ses dépôts.',
        summary: 'Micron gagne aujourd’hui plus d’argent par dollar vendu que presque toute l’industrie des semi-conducteurs : marge brute GAAP de 84,6 % au troisième trimestre, 41,46 Md$ de revenus et une prévision de 50,0 Md$ pour le quatrième. Le titre a pris ' + sgn(ret(5), 1) + ' en cinq séances, du 16 au 23 septembre, et clôture à ' + usd(close) + '. Le point qui compte est ailleurs : les nouveaux accords clients fixent un plafond de prix proche du marché du printemps 2026, en échange d’un plancher et de volumes garantis. Micron échange une partie de la hausse contre de la durée. Les résultats tombent le 30 septembre après la clôture, dans cinq séances. En juin, la publication avait fait ' + sgn(jump, 1) + ' sur la seule séance du 25 juin, même ampleur par coïncidence, puis le titre avait perdu ' + fr(Math.abs(drop), 0) + ' % en cinq semaines depuis son plus haut du 25 juin. Aucun ordre avant la publication.',
        whyBuy: [
          'La marge brute GAAP atteint 84,6 % au troisième trimestre, contre 37,7 % un an plus tôt, sur 41,46 Md$ de revenus.',
          'La prévision du quatrième trimestre vise 50,0 Md$ de revenus et environ 86 % de marge brute.',
          'Les accords stratégiques sont en prendre-ou-payer avec un prix plancher : la baisse d’un cycle mémoire serait amortie sur leur durée.',
          'La dette a été ramenée à 5,7 Md$ après 9,38 Md$ de remboursements en neuf mois, contre 30,2 Md$ de trésorerie et placements.'],
        whyAvoid: [
          'Les résultats du 30 septembre tombent dans cinq séances : en juin, la réaction a atteint ' + sgn(jump, 1) + ' le 25 juin avant une baisse de ' + fr(Math.abs(drop), 0) + ' % en cinq semaines.',
          'Le plafond de prix des accords stratégiques, proche du marché du printemps 2026, limite ce que Micron captera si les prix au comptant continuent de monter.',
          'Le consensus de bénéfice par action, ' + fr(E.consensus_eps, 2) + ' $, se situe au-dessus du milieu de la fourchette ajustée de la société : la barre est haute.',
          'Le titre a pris ' + sgn(ret(5), 1) + ' en cinq séances, du 16 au 23 septembre, juste avant la publication : une partie de la bonne nouvelle est déjà payée.'],
        controlChecklist: [
          { label: 'Historique de cours', status: 'pass', statusLabel: 'Trois cents séances continues', evidence: 'Série quotidienne certifiée au close du 23 septembre, source de repli documentée.', action: 'Supports et résistances recalculés sur cette seule série.' },
          { label: 'Calendrier', status: 'fail', statusLabel: 'Résultats le 30 septembre', evidence: 'Date donnée par deux calendriers de données, après la clôture selon l’un d’eux, sans annonce de Micron dans ses dépôts. Période de précaution du 25 septembre au 1er octobre : pas de nouvelle position autour des résultats.', action: 'Aucun plan avant la publication ; nouveau dossier après les chiffres.' },
          { label: 'Contrats clients', status: 'warn', statusLabel: 'Prix plafonné', evidence: 'Accords en prendre-ou-payer décrits dans le 10-Q, avec plafond et plancher de prix.', action: 'Lire la part des revenus sous contrat dans la prochaine publication.' }] },
      business: { theme: 'Mémoire pour l’IA : HBM, DRAM de centres de données et stockage NAND',
        overview: '<p>Micron fabrique de la mémoire : des puces DRAM, dont la mémoire à haute bande passante (HBM) montée à côté des processeurs d’IA, et des puces NAND pour le stockage. Au troisième trimestre de l’exercice 2026, clos le 28 mai, le chiffre d’affaires a atteint 41,46 Md$, contre 23,86 Md$ au trimestre précédent et 9,30 Md$ un an plus tôt. La HBM4 est en livraison à grand volume pour la plateforme du principal client.</p><p>La hausse vient surtout du prix. Selon le 10-Q, les ventes de DRAM ont progressé de 343 % sur un an, avec des prix moyens en hausse d’environ 260 % et des volumes en hausse d’environ 20 %. La demande dépasse ce que l’industrie peut produire, et Micron répartit son offre entre clients.</p><p>Les accords clients stratégiques changent la nature du titre. Ils sont en prendre-ou-payer, sur plusieurs années, avec des volumes fermes. Les plus gros fixent un plafond de prix proche du marché du deuxième trimestre civil 2026 et un plancher sur toute la durée. Micron dit attendre, même au plancher, des marges supérieures aux pics de tous les cycles passés. Le titre devient moins cyclique à la baisse, mais aussi moins explosif à la hausse.</p>',
        moat: 'Micron est l’un des trois producteurs mondiaux de DRAM et le seul américain. Sa HBM qualifiée chez le principal client et ses accords pluriannuels à prix plancher lui donnent une visibilité inhabituelle pour une valeur de mémoire, tant que l’offre du secteur reste contrainte.',
        segments: [
          { name: 'Mémoire pour le cloud', revenue: '13,77 Md$ au trimestre', pct: '33 %', description: 'Marge opérationnelle de 78 %.' },
          { name: 'Centres de données', revenue: '11,52 Md$ au trimestre', pct: '28 %', description: 'Marge opérationnelle de 83 %.' },
          { name: 'Mobile et PC', revenue: '11,52 Md$ au trimestre', pct: '28 %', description: 'Marge opérationnelle de 86 %.' },
          { name: 'Automobile et embarqué', revenue: '4,63 Md$ au trimestre', pct: '11 %', description: 'Marge opérationnelle de 75 %.' }],
        sourceRefs: [ref(0), ref(1)],
        coverageMatrix: [
          { facet: 'Cours et historique', status: 'COUVERT', decision: 'Trois cents séances continues, close certifié ; base des supports et résistances.' },
          { facet: 'Résultats et guidance', status: 'COUVERT — PRIMAIRE', decision: 'Communiqué du 24 juin et 10-Q ; publication du 30 septembre donnée par deux calendriers de données, non annoncée par Micron dans ses dépôts.' },
          { facet: 'Contrats clients', status: 'COUVERT — PRIMAIRE', decision: 'Structure des accords stratégiques lue dans le 10-Q ; volumes sous contrat non publiés.' },
          { facet: 'Agrégats GAAP', status: 'COUVERT — XBRL', decision: 'Douze mois glissants reconstitués depuis les données XBRL officielles.' },
          { facet: 'Comparables et transmission', status: 'COUVERT — LOCAL', decision: 'Corrélations recalculées sur barres certifiées depuis la fin mars.' },
          { facet: 'Initiés', status: 'PARTIEL', decision: 'Aucune transaction relevée dans la fenêtre ; couverture officielle partielle.' },
          { facet: 'Options', status: 'NON EXPLOITABLE', decision: 'Mouvement implicite indisponible, marché fermé au relevé.' }] },
      news: [
        { date: '2026-06-24', title: 'Troisième trimestre : 41,46 Md$ et 84,6 % de marge brute', impact: 'positive', detail: 'Le titre a pris ' + sgn(jump, 1) + ' le lendemain, jusqu’au plus haut historique, avant de reculer fortement en juillet.', source: 'Micron — SEC', sourceUrl: docs[0].url },
        { date: '2026-06-25', title: 'Le 10-Q détaille les accords clients à prix plancher', impact: 'neutral', detail: 'Des volumes fermes sur plusieurs années, en échange d’un plafond de prix proche du marché du printemps 2026 pour les plus gros contrats.', source: 'Micron — SEC', sourceUrl: docs[1].url },
        { date: '2026-06-25', title: '9,38 Md$ de dette remboursés en neuf mois', impact: 'positive', detail: 'La dette tombe à 5,7 Md$ : le bilan n’est plus un sujet, la trésorerie dépasse largement l’endettement.', source: 'Micron — SEC', sourceUrl: docs[1].url }],
      fundamentals: { rows: [
          { metric: 'Chiffre d’affaires du trimestre', value: '41,46 Md$', signal: 'Contre 9,30 Md$ un an plus tôt', signalColor: 'green', _src: 0 },
          { metric: 'Marge brute GAAP du trimestre', value: '84,6 %', signal: 'Contre 37,7 % un an plus tôt', signalColor: 'green', _src: 0 },
          { metric: 'Résultat net GAAP du trimestre', value: '28,24 Md$', signal: '24,67 $ par action diluée', signalColor: 'green', _src: 0 },
          { metric: 'Prévision du quatrième trimestre', value: '50,0 Md$ ± 1,0 Md$', signal: 'Marge brute d’environ 86 %', signalColor: 'blue', _src: 0 },
          { metric: 'Trésorerie et placements', value: '30,2 Md$', signal: 'Y compris trésorerie soumise à restrictions, fin mai 2026', signalColor: 'green', _src: 0 },
          { metric: 'Part du premier client (neuf mois)', value: '10 %', signal: 'Contre 17 % sur l’exercice 2025', signalColor: 'blue', _src: 1, _also: [2] },
          { metric: 'Revenus GAAP sur douze mois', value: fr(G$.rev / 1e9, 1) + ' Md$', signal: 'Douze mois glissants au 28 mai 2026 (XBRL SEC)', signalColor: 'blue', _src: 'gaap' },
          { metric: 'EBITDA GAAP sur douze mois', value: fr(G$.ebitda / 1e9, 1) + ' Md$', signal: 'Résultat opérationnel + amortissements, douze mois au 28 mai 2026', signalColor: 'blue', _src: 'gaap' },
          { metric: 'Résultat net GAAP sur douze mois', value: fr(G$.ni / 1e9, 1) + ' Md$', signal: 'Douze mois glissants au 28 mai 2026', signalColor: 'green', _src: 'gaap' },
          { metric: 'Flux de trésorerie libre sur douze mois', value: fr(G$.fcf / 1e9, 1) + ' Md$', signal: 'Flux d’exploitation moins investissements industriels, douze mois au 28 mai 2026', signalColor: 'green', _src: 'gaap' },
          { metric: 'Dette au 28 mai 2026', value: fr(G$.debt / 1e9, 1) + ' Md$', signal: 'Dette courante et à long terme, bilan du 10-Q', signalColor: 'green', _src: 'gaap' },
          { metric: 'EV/EBITDA GAAP', value: fr(ev / G$.ebitda, 1) + '×', signal: 'Valeur d’entreprise au close du 2026-09-23 sur EBITDA GAAP douze mois au 2026-05-28', signalColor: 'blue', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus le scénario de normalisation ci-dessous : les douze mois incluent deux trimestres d’avant la flambée des prix, le multiple trailing surestime donc la cherté.', _src: 'market' },
          { metric: 'P/E GAAP sur douze mois', value: fr(marketCap / G$.ni, 1) + '×', signal: 'Douze mois glissants : capitalisation au 2026-09-23 sur résultat net GAAP douze mois au 2026-05-28', signalColor: 'blue', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus le résultat du seul troisième trimestre, 28,24 Md$ : le marché paie la durée du cycle, pas son niveau actuel.', _src: 'market' },
          { metric: 'EV/EBITDA — scénario de normalisation (hypothèse éditoriale)', value: fr(scn.price, 2) + ' $ par action', signal: 'Scénario : multiple ramené à dix fois l’EBITDA GAAP par hypothèse, dette et trésorerie du 2026-05-28 inchangées, soit ' + fr(scn.downside_pct, 0) + ' % sous le close du 2026-09-23', signalColor: 'red', source: 'Clôture certifiée et XBRL SEC', comparison: 'Versus Sandisk à ' + fr(c.peerEv('SNDK'), 1) + '× et Dell à ' + fr(c.peerEv('DELL'), 1) + '× (statistiques courantes du 24 septembre, non point-in-time) : dix fois suppose un retournement du cycle, pas la situation actuelle ; ce n’est pas un objectif.', _src: 'market', _peers: ['SNDK', 'DELL'] }],
        sourceRefs: [ref(0), ref(1), market('fondamentaux et statistiques')] },
      earnings: { quarters: [],
        beatNote: 'Troisième trimestre de l’exercice 2026 : bénéfice par action GAAP de 24,67 $ et ajusté de 25,11 $, marge opérationnelle GAAP de 80,4 %. La guidance du quatrième trimestre vise 50,0 Md$ de revenus à plus ou moins 1,0 Md$, une marge brute d’environ 86 % et un bénéfice par action GAAP de 30,73 $ à plus ou moins 1,00 $ (31,00 $ ajusté). Le consensus relevé, ' + fr(E.consensus_eps, 2) + ' $, se place dans la moitié haute de la fourchette ajustée : une publication conforme pourrait décevoir un titre qui vient de monter.',
        nextEarnings: E.report_date,
        sourceRefs: [ref(0), market('calendrier de résultats')] },
      capitalStructure: { sharesOutstanding: fr(st.sharesOutstanding / 1e9, 3) + ' milliard d’actions (statistiques du 24 septembre ; 1,129 milliard au 28 mai selon le 10-Q)',
        sharesAuthorized: '3 milliards d’actions autorisées selon le bilan du 10-Q.', dilutionRisk: 'low',
        shareHistory: 'Le nombre d’actions en circulation passe de 1,122 milliard fin août 2025 à 1,129 milliard fin mai 2026, soit environ 0,6 % de dilution par la rémunération en actions. Les rachats du programme, 650 M$ sur neuf mois, ne compensent qu’une partie. Aucun enregistrement d’émission d’actions ni programme de vente au fil de l’eau n’est relevé ; la priorité de la trésorerie est allée au remboursement de 9,38 Md$ de dette. Un nombre d’actions entièrement dilué n’est pas calculable depuis ces seuls dépôts ; aucun convertible ni bon de souscription n’y figure.',
        warrants: [], atm: { active: false, authorized: 'Aucun programme d’émission d’actions relevé', used: 'Sans objet', remaining: 'Sans objet' },
        sourceRefs: [ref(1)] },
      filingsReview: { summary: 'Trois dépôts décisionnels ouverts et hachés. Ils racontent le même trimestre sous deux angles : des marges historiques, et une stratégie commerciale qui renonce à une partie de la hausse des prix pour sécuriser des volumes sur plusieurs années.',
        filings: docs.map(d => ({ date: d.date, form: d.form, accession: d.accession, finding: d.finding, url: d.url })),
        contrarianRisks: [
          'Le plafond de prix des grands accords, proche du marché du printemps 2026, transforme une partie de la hausse future des prix en manque à gagner.',
          'Une marge brute de 84,6 % attire l’investissement : la réponse de l’offre des concurrents coréens n’apparaît dans les prix qu’avec retard.',
          'Le consensus, dans la moitié haute de la fourchette ajustée, laisse peu de place à une publication simplement conforme.',
          'La réaction de juin montre l’amplitude : ' + sgn(jump, 1) + ' le 25 juin, puis ' + fr(drop, 0) + ' % jusqu’au 29 juillet.'] },
      technicals: { rsi14: +tech.rsi14.toFixed(2), macd: +tech.macd.toFixed(2), macdSignal: +tech.macdSignal.toFixed(2), ema20: +tech.ema20.toFixed(2), ema50: +tech.ema50.toFixed(2), ema200: +tech.ema200.toFixed(2),
        ma50Type: 'EMA', ma200Type: 'EMA', ma50Available: true, ma200Available: true, atr14: +tech.atr14.toFixed(2),
        badges: ['Au-dessus des moyennes à vingt, cinquante et deux cents séances', 'Sous le plus haut historique du 25 juin', 'Aucun plan avant les résultats'],
        supports: [lv('s1'), lv('s2'), lv('s3')], resistances: [lv('r1'), lv('r2'), lv('r3')],
        setupNote: 'Le titre clôture à ' + usd(close) + ', au-dessus de ses moyennes à vingt, cinquante et deux cents séances, après ' + sgn(ret(5), 1) + ' en cinq séances, du 16 au 23 septembre. Supports : ' + usd(lv('s1')) + ', plus bas du 22 septembre, ' + usd(lv('s2')) + ' et ' + usd(lv('s3')) + '. Résistances : ' + usd(lv('r1')) + ', plus haut du 23 septembre, ' + usd(lv('r2')) + ' et ' + usd(lv('r3')) + ', plus haut historique du 25 juin. L’ATR à quatorze séances vaut ' + usd(tech.atr14) + ' : une séance de résultats peut en parcourir plusieurs. Aucun plan n’est ouvert avant le 30 septembre.',
        wyckoff: 'Non utilisé : le profil de volume n’est pas exploité dans ce dossier.',
        sourceRefs: [market('barres quotidiennes et indicateurs recalculés')] },
      options: { callOI: 'Non exploitable', putOI: 'Non exploitable', cpRatio: 'Non exploitable', maxPain: 'Non exploitable', ivMean: 'Non exploitable', skew: 'Mouvement implicite de la publication indisponible, marché fermé au relevé', unusual: 'Aucune activité inhabituelle qualifiée', sourceRefs: [market('options')] },
      shortInterest: { siPct: fr(st.shortPercentOfFloat * 100, 2) + ' % du flottant', daysToCover: fr(st.shortRatio, 2) + ' jour, date de règlement non précisée par le snapshot', ctb: 'Coût d’emprunt bas, sans tension', trend: 'Positions vendeuses faibles ; aucune thèse de rachat forcé des vendeurs.', squeezeScore: 'Non pertinent', sourceRefs: [market('positions vendeuses')] },
      insiders: { signal: 'Aucune transaction de dirigeant relevée dans la fenêtre collectée. Couverture officielle partielle : l’absence de ligne n’est pas la preuve d’une absence de vente.', recentTransactions: [], sourceRefs: [market('formulaires 4')] },
      macro: { indicators: [{ name: 'Clôture de référence', value: c.REF, signal: usd(close) + ', séance complète' }, { name: 'Rendement cinq séances', value: sgn(ret(5)), signal: 'Descriptif' }, { name: 'Rendement vingt et une séances', value: sgn(ret(21)), signal: 'Descriptif' }],
        regime: 'neutral', impact: 'La mémoire est plus sensible au cycle d’investissement des centres de données qu’aux taux. Le 10 ans américain à 5,11 % le 23 septembre, plus haut depuis juillet 2007, pèse sur les multiples, mais le prix de la DRAM reste la variable qui décide.' },
      risks: { riskScore: 7, riskProfile: 'High',
        riskSummary: 'Le risque de Micron n’est pas le bilan, redevenu solide, ni la demande, qui dépasse l’offre. C’est le calendrier et l’amplitude : une publication dans cinq séances sur un titre qui vient de monter, et un marché qui a déjà montré qu’il pouvait passer de l’euphorie à une baisse de plus de 40 % en cinq semaines.',
        riskCards: [
          { title: 'Publication imminente', severity: 'high', icon: 'fa-calendar-day', points: ['Résultats le 30 septembre, dans la période de précaution du 25 septembre au 1er octobre.', 'Consensus dans la moitié haute de la fourchette ajustée.'], verdict: 'Entrer avant la publication revient à parier sur un chiffre, pas sur un plan.' },
          { title: 'Plafond de prix contractuel', severity: 'medium', icon: 'fa-lock', points: ['Plafond proche du marché du printemps 2026 pour les plus gros accords.', 'Part des revenus sous contrat non publiée.'], verdict: 'Micron gagne en durée ce qu’il cède en potentiel de hausse ; le marché devra réviser sa lecture.' },
          { title: 'Cycle de la mémoire', severity: 'high', icon: 'fa-arrows-spin', points: ['Hausse des revenus tirée d’abord par les prix, pas par les volumes.', 'Marges qui attirent de nouvelles capacités chez les concurrents.'], verdict: 'Les prix de la mémoire ont toujours fini par se retourner ; les accords amortissent le choc sans le supprimer.' },
          { title: 'Amplitude des réactions', severity: 'medium', icon: 'fa-chart-line', points: ['Réaction de ' + sgn(jump, 1) + ' le 25 juin, lendemain de la publication de juin.', 'Baisse de ' + fr(Math.abs(drop), 0) + ' % entre le 25 juin et le 29 juillet.'], verdict: 'La taille de position doit supposer un écart de plusieurs ATR à l’ouverture du 1er octobre.' }],
        pedagogy: 'Un titre qui vient de prendre plus de 10 % en cinq séances avant ses résultats a souvent déjà intégré une bonne publication. Le gap du lendemain peut sauter n’importe quel stop, et le slippage ne se contrôle pas même sur une valeur aussi liquide. Si une position existe déjà, sa taille doit supposer ce gap. Pour une nouvelle entrée, ne pas anticiper : attendre la publication et relire le plan sur les chiffres.' },
      tradeIdea: { status: 'no-trade', archiveReferenceClose: archive.meta.levelsCloseDate,
        statusNote: 'Aucun plan. Les niveaux affichés sont ceux, archivés, du dossier du 27 août : ils n’ont jamais été activés et aucun ordre n’y est attaché. Un nouveau plan ne sera construit qu’après la publication du 30 septembre.',
        entry, stop, tp1, tp2,
        stopPct: pct(stop, entry).toFixed(1) + '%', tp1Pct: '+' + pct(tp1, entry).toFixed(1) + '%', tp2Pct: '+' + pct(tp2, entry).toFixed(1) + '%',
        rr: '1:' + rr1.toFixed(2) + ' TP1 / 1:' + rr2.toFixed(2) + ' TP2',
        entryNote: 'Niveaux historiques affichés pour mémoire, non exécutables : le cours actuel est au-dessus de tous. Liquidité : environ ' + fr(adv / 1e9, 1) + ' Md$ échangés par séance, médiane des vingt dernières ; la profondeur du marché ne protège pas contre un écart d’ouverture le lendemain des résultats.',
        horizon: 'Aucun horizon : pas de plan avant la publication',
        thesis: 'Le marché achète Micron comme une valeur de croissance de l’IA ; les accords clients en font aussi une valeur à rendement plafonné. La publication du 30 septembre dira laquelle des deux lectures l’emporte, à travers la marge du quatrième trimestre, la prévision suivante et la part des revenus sous contrat. Entrer à cinq séances de ce chiffre, après une hausse de plus de 10 %, c’est parier sur la réaction plutôt que suivre un plan. Aucun ordre : attendre les chiffres, puis reconstruire des niveaux sur les séances qui suivent.',
        catalysts: ['La publication du 30 septembre après la clôture : marge brute, prévision du premier trimestre de l’exercice 2027 et part des revenus sous contrat.', 'Les commentaires sur la HBM4E, attendue en volume en 2027, et sur les qualifications chez de nouveaux clients.', 'L’évolution des prix au comptant de la DRAM face aux plafonds contractuels.'],
        invalidation: ['Toute entrée avant la publication du 30 septembre contredit ce dossier.', 'Une marge brute du quatrième trimestre nettement sous 86 % remettrait en cause la lecture du cycle.', 'Une prévision du trimestre suivant en baisse sur 50,0 Md$ signalerait que les prix plafonnés commencent à peser.'] },
      globalScore: { profile: 'Cycle de la mémoire au sommet des marges, résultats dans cinq séances',
        keyTakeawaysPositive: ['Marge brute GAAP de 84,6 % et prévision de 50,0 Md$.', 'Bilan assaini : 5,7 Md$ de dette contre 30,2 Md$ de trésorerie.', 'Accords pluriannuels à prix plancher et volumes fermes.'],
        keyTakeawaysNegative: ['Résultats le 30 septembre, après une hausse de plus de 10 % en cinq séances.', 'Plafond de prix contractuel sur les plus gros accords.', 'Des réactions passées de grande amplitude, dans les deux sens.'],
        mindsetTip: 'Avant des résultats, la bonne question n’est pas « les chiffres seront-ils bons ? » mais « que faut-il pour surprendre un marché qui vient de monter ? ».' },
      social: { platforms: [], sourceRefs: [market('sentiment non retenu faute de mesure qualifiée')] },
      disclaimer: 'Document de recherche éducatif. Ni conseil financier, ni signal de trading. Aucun plan actif : les niveaux affichés sont historiques.',
    };
  },
  groups: [
    { name: 'Acheteurs de mémoire pour l’IA', order: 1, transmission: 'Leurs plateformes d’accélérateurs et leur capex fixent la demande de HBM et de DRAM de serveurs.', rows: [
      ['NVDA', 'leader', 'Premier acheteur de HBM pour ses accélérateurs', 'Le rythme de ses plateformes détermine l’essentiel de la demande de HBM de Micron.'],
      ['AMD', 'leader', 'Accélérateurs concurrents gros consommateurs de HBM', 'Ses gains chez les clouds élargissent la base de clients de la HBM.'],
      ['AVGO', 'leader', 'Puces sur mesure des grands clouds', 'Ses accélérateurs sur mesure embarquent aussi de la HBM : un second canal de demande.'],
      ['MSFT', 'leader', 'Premier acheteur de calcul', 'Son capex de centres de données se traduit en commandes de DRAM de serveurs.'],
      ['META', 'leader', 'Grand acheteur de calcul pour ses modèles', 'Ses révisions de capex se transmettent directement à la demande de mémoire.']] },
    { name: 'Pairs directs : mémoire et stockage', order: 1, transmission: 'Même cycle de prix, même demande des centres de données.', rows: [
      ['SNDK', 'direct_peer', 'Pur acteur de la NAND', 'Ses prix de NAND recoupent ceux de l’activité stockage de Micron.'],
      ['WDC', 'direct_peer', 'Disques durs de centres de données', 'Le stockage de masse concurrence la NAND ; ses prix disent la tension du stockage.'],
      ['STX', 'direct_peer', 'Disques durs de grande capacité', 'Même lecture : un stockage tendu soutient les prix de la NAND.']] },
    { name: 'Amont : équipement et test', order: 1, transmission: 'Les nouvelles capacités de mémoire passent par leurs machines ; leurs commandes annoncent l’offre future.', rows: [
      ['AMAT', 'upstream', 'Dépôt et gravure pour la mémoire', 'Ses commandes mémoire signalent les capacités qui arriveront dans un à deux ans.'],
      ['LRCX', 'upstream', 'Gravure, très exposé à la mémoire', 'Premier indicateur des investissements des fabricants de mémoire.'],
      ['KLAC', 'upstream', 'Contrôle de procédé', 'Ses ventes suivent l’investissement de toute l’industrie des puces, mémoire comprise.'],
      ['ENTG', 'upstream', 'Matériaux et consommables de fabrication', 'Ses volumes de consommables suivent le nombre de plaquettes réellement produites en usine.'],
      ['TER', 'upstream', 'Test de mémoire et de HBM', 'Ses ventes de testeurs HBM suivent la montée en volume des nouvelles générations.'],
      ['ONTO', 'upstream', 'Inspection de l’assemblage avancé', 'L’empilement de la HBM passe par ses outils d’inspection.']] },
    { name: 'Aval : serveurs et appareils', order: 2, transmission: 'Ils achètent la mémoire au prix du marché ; ses hausses pèsent sur leurs marges.', rows: [
      ['DELL', 'downstream', 'Serveurs et PC', 'Une mémoire chère comprime ses marges de PC et renchérit ses serveurs.'],
      ['HPE', 'downstream', 'Serveurs pour les entreprises', 'Même effet de coût sur les serveurs hors grands clouds.'],
      ['SMCI', 'downstream', 'Intégrateur de serveurs d’IA', 'Ses marges disent qui, du fabricant de mémoire ou de l’intégrateur, capte la rareté.'],
      ['AAPL', 'downstream', 'Téléphones et ordinateurs', 'Premier acheteur de mémoire mobile : ses contrats pèsent sur l’unité mobile.']] },
    { name: 'Second ordre : fonderie et concurrence de procédé', order: 2, transmission: 'L’assemblage avancé de la HBM et la capacité des fondeurs conditionnent les livraisons.', rows: [
      ['TSM', 'second_order', 'Fondeur des processeurs et assemblage avancé', 'Sa capacité d’assemblage avancé fixe le nombre d’accélérateurs, donc de piles HBM, livrables.'],
      ['INTC', 'second_order', 'Processeurs de serveurs et fonderie', 'Ses plateformes de serveurs déterminent la demande de DRAM classique.']] },
    { name: 'Contrôles sectoriels', order: 2, transmission: 'Paniers de référence pour isoler ce qui est propre à Micron.', rows: [
      ['SMH', 'sector_proxy', 'Panier de semi-conducteurs', 'Isole ce qui revient au secteur dans le mouvement de Micron.'],
      ['SOXX', 'sector_proxy', 'Panier de semi-conducteurs moins concentré', 'Plus sensible aux valeurs moyennes, dont les équipementiers.'],
      ['QQQ', 'sector_proxy', 'Grandes valeurs du Nasdaq', 'Contrôle large : un mouvement commun n’a rien de spécifique.']] },
  ],
  eventDefault: { leader: 'Aucune publication dans les quatorze jours collectés ; ses commentaires de capex restent le signal à suivre', direct_peer: 'Aucune publication dans les quatorze jours collectés ; ses prix de stockage donnent une lecture croisée', upstream: 'Aucune publication dans les quatorze jours collectés ; ses commandes mémoire annoncent l’offre future', downstream: 'Aucune publication dans les quatorze jours collectés ; ses marges disent qui capte la rareté', second_order: 'Aucune publication dans les quatorze jours collectés ; sa capacité conditionne les livraisons', sector_proxy: 'Panier sans publication propre ; exposé aux résultats de Micron le 30 septembre' },
  eventRisk: {},
  blastDoc: 1,
  scenarios: c => [
    { scenario: 'bullish', trigger: 'La marge brute dépasse 86 % et la prévision suivante progresse encore au-delà de 50 Md$.', firstOrder: 'Le titre retourne vers son plus haut historique du 25 juin et les attentes de bénéfice montent.', secondOrder: 'Les équipementiers exposés à la mémoire, LRCX et AMAT, suivent sur l’anticipation de capacités.', confirmation: 'Une clôture au-dessus de 1 105,50 $ tenue sur deux séances après la publication.', contradiction: 'Une part des revenus sous contrat qui plafonnerait les prix plus tôt que prévu.' },
    { scenario: 'mixed', trigger: 'Les chiffres sont conformes à la fourchette, sans surprise sur la prévision.', firstOrder: 'Le titre rend une partie de sa hausse de cinq séances.', secondOrder: 'Les pairs de stockage restent stables, les équipementiers se tassent.', confirmation: 'Un retour vers le plus bas du 22 septembre sans rupture des moyennes.', contradiction: 'Une hausse des prix au comptant de la DRAM annoncée par les concurrents.' },
    { scenario: 'bearish', trigger: 'La prévision suivante marque une pause ou la marge recule sous l’effet des plafonds contractuels.', firstOrder: 'Le titre répète le schéma de juillet, avec une baisse de plusieurs ATR.', secondOrder: 'Les intégrateurs de serveurs profitent d’une détente du coût de la mémoire ; les équipementiers baissent.', confirmation: 'Une clôture sous le plus bas du 16 septembre.', contradiction: 'Des volumes sous contrat en hausse qui compensent la pause des prix.' }],
  contradictions: c => ['Le titre suit les paniers de semi-conducteurs sur la période, mais son amplitude propre autour des résultats dépasse ce que la corrélation laisse attendre.', 'Une corrélation élevée avec un acheteur de HBM ne prouve pas la taille de ses commandes ; le client à 10 % n’est pas nommé.'],
  missingData: c => ['Le client à 10 % des revenus sur neuf mois n’est pas nommé : aucun client coté n’entre dans les comparables comme client documenté.', 'Mouvement implicite de la publication indisponible, marché fermé au relevé ; sentiment non retenu.', 'Part des revenus sous accords stratégiques et niveaux de prix plafond non publiés.'],
  limitations: ['Barres d’une source de repli (Webull).', 'Mouvement implicite indisponible.', 'Client à 10 % non nommé.'],
});
